debezium/debezium

- .travis.yml
- README.md
- debezium-core/src/main/java/io/debezium/relational/Tables.java
- debezium-ingest-mysql/pom.xml
- debezium-ingest-mysql/src/test/java/io/debezium/mysql/ingest/ReadBinLogIT.java
- pom.xml
Changed how Travis-CI uses Docker and fixed Travis-CI build.
> Changed Docker usage on Travis-CI

- debezium-core/pom.xml
- debezium-core/src/main/java/io/debezium/relational/ddl/DdlParser.java
- debezium-core/src/main/java/io/debezium/util/IoUtil.java
- debezium-core/src/test/java/io/debezium/kafka/KafkaCluster.java
- debezium-core/src/test/java/io/debezium/kafka/KafkaClusterTest.java
- debezium-core/src/test/java/io/debezium/kafka/KafkaServer.java
- debezium-core/src/test/java/io/debezium/kafka/ZookeeperServer.java
- debezium-core/src/test/java/io/debezium/kafka/ZookeeperServerTest.java
- debezium-core/src/test/resources/log4j.properties
- pom.xml
This utility is only suitable for unit tests and therefore is defined in the test JAR of the `debezium-core` module. It certainly should never be used for production purposes.
> DBZ-10 Added small utility so unit tests can run an embedded Kafka cluster in-process

- README.md
- debezium-connector-mysql/pom.xml
- debezium-connector-postgres/pom.xml
- pom.xml
> add option to run without integration tests

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/TableConverters.java
This PR corrects two problems. The first is that the MySQL connector's `SourceInfo` class was not properly recovering its state from a `Map<String,Object>` in cases when that map was previously serialized and then deserialized using JSON. The JSON format represents all numeric integral values in the same way, so upon deserialization all integers were converted to longs, resulting in a class cast exception. The first commit fixes this issue.
The second commit ensures that the MySQL connector does not fail when it comes across an "unknown" table, which is a table for which the `CREATE TABLE` statement does not appear in the binlog. (For example, the binlog may have been started after the table was defined.) Because the connector did not know about the table, it has no schema information and …
> DBZ-26 Corrected the MySQL connector to not fail when it comes across an unknown table

- debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution.xml
- debezium-connector-mysql/pom.xml
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/TableConverters.java
- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
- pom.xml
Several issues were discovered and fixed while building a tutorial to run Debezium and the MySQL connector.
> DBZ-15 Fixed several issues discovered during testing

- debezium-connector-mysql/pom.xml
- pom.xml
Thanks for the reminding from https://issues.jboss.org/browse/DBZ-63\?focusedCommentId\=13242595\&page\=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel\#comment-13242595
> DBZ-63 Fix POM dependency management.

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
- debezium-connector-mysql/src/test/docker/init/setup.sql
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
- debezium-connector-mysql/src/test/resources/ddl/mysql-integration.ddl
- debezium-core/src/main/java/io/debezium/data/SchemaUtil.java
- debezium-core/src/main/java/io/debezium/jdbc/TimeZoneAdapter.java
- debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
- debezium-core/src/test/java/io/debezium/data/VerifyRecord.java
- debezium-core/src/test/java/io/debezium/jdbc/TimeZoneAdapterTest.java
- pom.xml
Backported multiple pull-requests to the `0.2.x` branch for inclusion in 0.2.3.
> DBZ-84, DBZ-85, DBZ-87

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
Additional cleanup of changes made for DBZ-132.
> DBZ-132 Cleanup of code

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetrics.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetricsMXBean.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/Metrics.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReaderMetrics.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReaderMetricsMXBean.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotReaderIT.java
Added an MXBean for the MySQL connector that captures various metrics while reading the binlog.
> DBZ-134 Enabled JMX metrics for MySQL connector

- debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
It also updates `EmbeddedEngine` to use the Kafka commit callbacks introduced after 0.10 and updates `AbstractConnectorTest` to better synchronize with the embedded engine
> DBZ-156 Updates EmbeddedEngine to better handle exceptional cases and provide more feedback during startup

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
Corrected the logic of the MySQL connector when getting the server’s GTID set. Previously, this logic failed if GTIDs are not used.
> DBZ-161 Corrected MySQL connector logic when no GTIDs are used

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoUtil.java
Corrected the `onCollection` utility method in the `MongoUtil` class to pass in the collection name rather than the database name.
> DBZ-167 Corrected the MongoUtil class

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
Corrected the MySQL DDL parser to support `ON UPDATE NOW` clauses in addition to `ON UPDATE CURRENT_TIMESTAMP`, with optional trailing parentheses.
> DBZ-169 MySQL connector support for ON UPDATE clauses

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
Added more logic to the snapshot reader to better handle errors when reading the list of table names in each database. Now, any errors with a single database (e.g., some of the not-quite-a-database names described in the JIRA issue) will cause the snapshot reader to simply skip that database name and continue on (with proper logging).
This change also quotes all of the database and table names when used in SQL statements issued via JDBC to the MySQL server. This does not change any DDL statements captured or records produced during snapshot.
> DBZ-164 Improved MySQL snapshot reader logic

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
MySQL recently added additional binlog events, and this commit adds support to handle these new events by ignoring them.
> DBZ-174 Added support for new binlog events

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RecordMakers.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java
Added to the event `source` information the name of the database and table to which the event applies.
> DBZ-184 Added database and table name to change event metadata

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
Improved the MySQL connector's logic to better handle Amazon RDS that does not allow giving user `SUPER` privileges. As before, the connector starts a transaction and attempts to get a global read lock via `FLUSH TABLES WITH READ LOCK` to prevent writes to the database so that the binlog position can be accurately read _and_ the table schemas can be read without interference from other clients. Once that is done, the connector releases the global read lock and continues in the same transaction to read all table rows. This means that our snapshot is consistent, but we maintain the global read lock for a very short period of time.
Amazon's RDS and Aurora are hosted MySQL instances that do not allow users to have the `SUPER` privilege, which means the user cannot get a global read lock. In …
> DBZ-140 Improved locking logic to support RDS

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
> DBZ-140: modify the query used to fetch the table list so that it includes tables only (no views)

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractReader.java
- debezium-connector-mysql/src/test/docker/init/setup.sql
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
- debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
Added a table and inserted rows that tries to replicate the problem reported in DBZ-195, but the test was unable to replicate the problem. In fact, this really is no different than existing tests. Changed the log messages so that if/when this happens again it will be possible to know which row was problematic.
> DBZ-195 Added tests to try to replicate a reported issue

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
Added a test case that uses the MySQL DDL parser to parse similar DDL statements to those reported in the issue, but these are properly handled with the current state of the `master` branch.
> DBZ-204 Added test case but unable replicate error

- debezium-core/src/test/java/io/debezium/kafka/KafkaServer.java
- pom.xml
- changed version from 0.10.11.1 to 0.10.2.0
- jackson version had to be upgraded correspondingly from 2.6.3 to 2.8.5 
- upgraded confluent platform from 3.1.2 to 3.2.0
> DBZ-203 Upgrade kafka version from 0.10.1.1 to 0.10.2.0

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java
When connector receives `new primary` oplog event, check whether this event is from current primary before existing. Newly elected primary has `new primary` oplog event as well, this will make sure connector resumes properly when connects to newly elected primary.
> DBZ-214 Fix MongoDB connector resumes on newly elected primary.

- debezium-core/src/main/java/io/debezium/transforms/ByLogicalTableRouter.java
This can be a bit spammy in the info level
> Change ByLogicalTableRouter logging from info to debug

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
https://issues.jboss.org/projects/DBZ/issues/DBZ-215
> DBZ-215 Validating configuration to prevent that database history topic and schema change topic collide

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
- debezium-connector-mysql/src/test/docker/init/setup.sql
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlFixedLengthBinaryColumnIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTableMaintenanceStatementsIT.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java
- debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java
https://issues.jboss.org/browse/DBZ-254
Hey @rhauch, could you give this a look? Thanks!
> DBZ-254 Right-padding values for fixed-length BINARY columns on MySQL

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationConnection.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
https://issues.jboss.org/browse/DBZ-250.
> DBZ-250 Correct PostgreSQL connector to not overload PG server

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/CollectionId.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoUtil.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetDiscovery.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSets.java
- debezium-core/src/main/java/io/debezium/document/Paths.java
- debezium-core/src/main/java/io/debezium/function/Predicates.java
- debezium-core/src/main/java/io/debezium/relational/ColumnId.java
- debezium-core/src/main/java/io/debezium/relational/TableId.java
https://issues.jboss.org/browse/DBZ-311
Nothing fancy, but it caught my attention when reviewing other changes, so I decided to quickly extract these patterns while at it.
> DBZ-311 Pre-compile and simplify some regular expressions

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
https://issues.jboss.org/browse/DBZ-319
> DBZ-319 Views are now ignored in snapshots

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTaskContextTest.java
https://issues.jboss.org/browse/DBZ-333
> DBZ-333 Filter database.history props out of JDBC URL

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
https://issues.jboss.org/browse/DBZ-210
> DBZ-210 Lock tables before starting tx in snapshot

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
https://issues.jboss.org/browse/DBZ-279
> DBZ-279 Consume SQL warnings

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
https://issues.jboss.org/browse/DBZ-356
> DBZ-356 Close leaked JDBC connection

- debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution.xml
It is pulled with kafka-embedded as test dependency only
> DBZ-370 log4j is a test dependency

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
https://issues.jboss.org/browse/DBZ-336
> DBZ-336 Test for PAGE_CHECKSUM

- jenkins-jobs/scripts/release-pipeline.groovy
https://issues.jboss.org/browse/DBZ-361
> DBZ-361 Adding MongoDB example image to release pipeline

- jenkins-jobs/wal2json-test.yaml
https://issues.jboss.org/browse/DBZ-403
http://ci.hibernate.org/view/Debezium/job/debezium-postgresql-test-wal2json/
> DBZ-403 Job for CI of wal2json

- pom.xml
- support/checkstyle/pom.xml
https://issues.jboss.org/browse/DBZ-227
> DBZ-227 Enabling Debezium to be built on Java 9

- pom.xml
https://issues.jboss.org/browse/DBZ-398
> DBZ-398 Upgraded binlog connector

- debezium-connector-postgres/pom.xml
https://issues.jboss.org/browse/DBZ-404
> DBZ-404 Postgres container is detected as started after initialization

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
https://issues.jboss.org/browse/DBZ-419
> DBZ-419 PK constraint name is optional

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
https://issues.jboss.org/browse/DBZ-412
> DBZ-412 Definition for column named `column` can be changed

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
- debezium-core/src/main/java/io/debezium/relational/ddl/DdlParser.java
https://issues.jboss.org/browse/DBZ-429
> DBZ-429 Fixed signed default value handling

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
https://issues.jboss.org/browse/DBZ-428
> DBZ-428 TEXT datatype can have an optional length

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
https://issues.jboss.org/browse/DBZ-401
> DBZ-401 Log binlog reader position in case of exception

- debezium-core/src/test/java/io/debezium/transforms/UnwrapFromEnvelopeTest.java
- pom.xml
https://issues.jboss.org/browse/DBZ-432
> DBZ-432 Rebased to Kafka 1.0.0

- jenkins-jobs/postgresql-10-test.yml
- jenkins-jobs/scripts/release-pipeline.groovy
https://issues.jboss.org/browse/DBZ-427
> DBZ-427 CI support for PostgreSQL 10

- COPYRIGHT.txt
- debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution.xml
- debezium-connector-mongodb/pom.xml
- debezium-connector-mysql/pom.xml
- debezium-connector-postgres/pom.xml
- debezium-core/pom.xml
- debezium-embedded/pom.xml
- pom.xml
https://issues.jboss.org/browse/DBZ-285
> DBZ-285: Use provided or test dependencies for Connect and Kafka dependencies

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
https://issues.jboss.org/browse/DBZ-439
> DBZ-439 Support for PRECISION keyword

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
https://issues.jboss.org/browse/DBZ-425
> DBZ-425 Fix ALTER column for changing default value

- debezium-core/src/test/java/io/debezium/kafka/KafkaServer.java
- debezium-core/src/test/java/io/debezium/relational/history/KafkaDatabaseHistoryTest.java
https://issues.jboss.org/browse/DBZ-456
> DBZ-456 Reduce text execution time

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.jboss.org/browse/DBZ-259
> DBZ-259 Return correct value for null Duration

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
https://issues.jboss.org/browse/DBZ-475
> DBZ-475 Support for RENAME USER statement

- jenkins-jobs/scripts/release-pipeline.groovy
https://issues.jboss.org/browse/DBZ-468
> DBZ-468 Issues must have component set during release

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
- debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
https://issues.jboss.org/browse/DBZ-478
> DBZ-478 Correctly handling null values for array-typed columns

- debezium-core/src/test/java/io/debezium/kafka/KafkaServer.java
https://issues.jboss.org/browse/DBZ-479
> DBZ-479 Forced fsync slows down tests

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
- debezium-core/src/main/java/io/debezium/text/TokenStream.java
https://issues.jboss.org/browse/DBZ-476
> DBZ-476 Doubled quotes are parsed as escaped

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/Wal2JsonReplicationMessage.java
https://issues.jboss.org/browse/DBZ-478
> DBZ-478 Fix null array handling for wal2json

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
https://issues.jboss.org/browse/DBZ-483
> DBZ-483 Removing two unused methods from MySqlSchema

- debezium-core/src/main/java/io/debezium/relational/history/AbstractDatabaseHistory.java
- debezium-core/src/main/java/io/debezium/relational/history/FileDatabaseHistory.java
- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
- debezium-core/src/main/java/io/debezium/relational/history/MemoryDatabaseHistory.java
Hi @rhauch, is this what you had in mind for https://issues.jboss.org/browse/DBZ-464?
> DBZ-464 MySQL connector may not read database history to end

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
Modifying unit tests to always convert to UTC timezone
https://issues.jboss.org/browse/DBZ-491
> DBZ-491 Failing unit tests when run in EST timezone

- pom.xml
https://issues.jboss.org/browse/DBZ-492
> DBZ-492 Rebase to Confluent 4.0.0

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlUnsignedIntegerIT.java
https://issues.jboss.org/browse/DBZ-461
> DBZ-461 Changed default bigint conversion to long

- jenkins-jobs/postgresql-10-test.yml
- jenkins-jobs/postgresql-9.6-legacy-test.yml
- jenkins-jobs/wal2json-legacy-test.yaml
https://issues.jboss.org/browse/DBZ-495
> DBZ-495 Testing of connectors with and w/o metadata

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationMessage.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoReplicationMessage.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/Wal2JsonReplicationMessage.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
https://issues.jboss.org/browse/DBZ-498
> DBZ-498 Unknown types can be handled as binary data

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
https://issues.jboss.org/browse/DBZ-512
> DBZ-512 Need to use OID with the old Postgres connector version

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DecoderDifferences.java
https://issues.jboss.org/browse/DBZ-517
> DBZ-517 Manually override RDS environment

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.jboss.org/browse/DBZ-518
> DBZ-518 Remove a leftover event

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
This seems to unblock the defect
> DBZ-522 Adding null check when encounting null TIME fields during snapshot

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/DateTimeFormat.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/wal2json/ISODateTimeFormatTest.java
https://issues.jboss.org/browse/DBZ-525
> DBZ-525 Timestamp supports optional microseconds part

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
https://issues.jboss.org/browse/DBZ-524
> DBZ-524 RESTRICT in DROP COLUMN

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/RecordMakersTest.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java
- debezium-core/src/main/java/io/debezium/document/ComparableValue.java
- debezium-core/src/main/java/io/debezium/document/ConvertingValue.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java
- debezium-core/src/main/java/io/debezium/util/MathOps.java
- debezium-core/src/main/java/io/debezium/util/Strings.java
- debezium-core/src/test/java/io/debezium/kafka/KafkaCluster.java
https://issues.jboss.org/browse/DBZ-455
> DBZ-455 Use valueOf instead of constructors

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SnapshotWithOverridesProducerIT.java
https://issues.jboss.org/browse/DBZ-510
> DBZ-510 snapshot.select.statement.overrides for Postgres

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/Wal2JsonReplicationMessage.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
https://issues.jboss.org/browse/DBZ-506
> DBZ-506 Support for char and varchar arrays

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
https://issues.jboss.org/browse/DBZ-530
> DBZ-530 Multiple PARTITION defintions supported

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderBufferIT.java
https://issues.jboss.org/browse/DBZ-411
> DBZ-411 ROLLBACK TO savepoint is parseable

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
- debezium-core/src/main/java/io/debezium/relational/ddl/DdlParser.java
- debezium-core/src/main/java/io/debezium/relational/history/AbstractDatabaseHistory.java
- debezium-core/src/main/java/io/debezium/text/TokenStream.java
https://issues.jboss.org/browse/DBZ-538
> DBZ-538 Improve invalid DDL statement reporting

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
https://issues.jboss.org/browse/DBZ-534
> DBZ-534 Using correct datattype in list lookup

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.jboss.org/browse/DBZ-504
> DBZ-504 Type changes detected for constraints

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/ChangeEvent.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationMessage.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationStream.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoReplicationMessage.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/Wal2JsonMessageDecoder.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/Wal2JsonReplicationMessage.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/ReplicationConnectionIT.java
https://issues.jboss.org/browse/DBZ-521
> DBZ-521 Record LSN for the last message committed to Connect

- .travis.yml
https://issues.jboss.org/browse/DBZ-568
> DBZ-568 Test wal2json as part of Travis build

- debezium-core/src/main/java/io/debezium/relational/ddl/DdlParser.java
https://issues.jboss.org/browse/DBZ-538
@jpechane Logging unparseable DDL in one more case which we previously missed.
> DBZ-538 Capturing unparseable DDL for logging in one more place

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
https://issues.jboss.org/browse/DBZ-577
> DBZ-577 Numeric arrays correctly working

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
https://issues.jboss.org/browse/DBZ-572
> DBZ-572 Transaction is completed also by XID event

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
- debezium-core/src/main/java/io/debezium/util/Threads.java
- debezium-embedded/src/test/java/io/debezium/embedded/ConnectorOutputTest.java
https://issues.jboss.org/browse/DBZ-587
> DBZ-587 Centralize and unify thread management

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SourceInfoTest.java
- debezium-core/src/main/java/io/debezium/connector/AbstractSourceInfo.java
https://issues.jboss.org/browse/DBZ-593
> DBZ-593 Add Debezium version to source in envelope

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
https://issues.jboss.org/browse/DBZ-590
> DBZ-590 Detect non-available offset

- debezium-core/src/main/java/io/debezium/config/Field.java
- debezium-core/src/main/java/io/debezium/relational/history/DatabaseHistory.java
- debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java
https://issues.jboss.org/browse/DBZ-576
> DBZ-576 Internal parameters

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresType.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/AbstractReplicationMessageColumn.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationMessage.java
https://issues.jboss.org/browse/DBZ-616
> DBZ-616 Get default length and scale for types

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RecordMakers.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/Configurator.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TopicSelector.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SnapshotWithOverridesProducerIT.java
- debezium-core/src/main/java/io/debezium/relational/TableSchema.java
- debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
- debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java
https://issues.jboss.org/browse/DBZ-620
> DBZ-620 Avoiding repeated recreation of envelope schema

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTaskContextIT.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/data/Envelope.java
https://issues.jboss.org/browse/DBZ-628
> DBZ-628 Unifying some connector properties

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderIT.java
https://issues.jboss.org/browse/DBZ-629
> DBZ-629 Fixed intermittent test issues

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-core/src/main/java/io/debezium/document/ComparableValue.java
https://issues.jboss.org/browse/DBZ-625
> DBZ-625 Fix parsing of float without decimals

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
https://issues.jboss.org/browse/DBZ-615
> DBZ-615 Init unset Decimal props to default values

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
- debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
https://issues.jboss.org/browse/DBZ-605
> DBZ-605 Support for BYTEA datatype

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
> Revert default Postgres decoder plugin for testing

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
https://issues.jboss.org/browse/DBZ-623
> DBZ-623 Fix NPE for invlid restored LSNs

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/resources/postgis_create_tables.ddl
- debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
https://issues.jboss.org/browse/DBZ-635
> DBZ-635 Fixing column schemas that were marked as optional incorrectly

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetDiscovery.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetMonitorThread.java
https://issues.jboss.org/browse/DBZ-648
> DBZ-648 InterrupedException handled by MongoDB

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
https://issues.jboss.org/browse/DBZ-660
> DBZ-660 Fix for CONSTRAINT UNIQUE syntax

- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
https://issues.jboss.org/browse/DBZ-663
> DBZ-663 disable cleaning of history topic based on size

- debezium-core/src/main/java/io/debezium/document/JacksonReader.java
https://issues.jboss.org/browse/DBZ-657
> DBZ-657 Handle JSON with control chars not according to specs

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java
https://issues.jboss.org/browse/DBZ-592
> DBZ-592 Make snapshot/init-sync false instead of null

- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
https://issues.jboss.org/browse/DBZ-669
> DBZ-669 Closing AdminClient instance after usage

- .travis.yml
- debezium-connector-mongodb/pom.xml
- pom.xml
https://issues.jboss.org/browse/DBZ-529
> DBZ-529 Upgrade to MongoDB 3.6, compatibility testing

- debezium-connector-postgres/pom.xml
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
https://issues.jboss.org/browse/DBZ-676
> DBZ-676 Support testing against 8bit enc database

- debezium-core/src/test/java/io/debezium/kafka/KafkaServer.java
- pom.xml
https://issues.jboss.org/browse/DBZ-687
> DBZ-687 Kafka 1.1.0

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
https://issues.jboss.org/browse/DBZ-697
> DBZ-697 Support for large type OIDs

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
- debezium-core/src/main/java/io/debezium/time/Conversions.java
https://issues.jboss.org/browse/DBZ-694
> DBZ-694 Support milliseconds for pre-epoch dates

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
https://issues.jboss.org/browse/DBZ-701
> DBZ-701 Support for arrays with large OID

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
https://issues.jboss.org/browse/DBZ-699
> DBZ-699 Close JDBC connection when initialization fails

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetrics.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetricsMXBean.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/ReaderMetricsMXBean.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReaderMetrics.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReaderMetricsMXBean.java
https://issues.jboss.org/browse/DBZ-598
> DBZ-598 Metrics expose the list of captured tables

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/DateTimeFormat.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
https://issues.jboss.org/browse/DBZ-681
> DBZ-681 Time with precision for wal2json plug-in

- debezium-core/src/main/java/io/debezium/config/Configuration.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
https://issues.jboss.org/browse/DBZ-702
> DBZ-702 Mask SASL configuration

- debezium-connector-mysql/pom.xml
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RowDeserializers.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/UniqueDatabase.java
- debezium-connector-postgres/pom.xml
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/MessageDecoder.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoMessageDecoder.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoReplicationMessage.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/NonStreamingWal2JsonMessageDecoder.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/StreamingWal2JsonMessageDecoder.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/Wal2JsonReplicationMessage.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
- debezium-core/src/main/java/io/debezium/config/Field.java
- debezium-core/src/main/java/io/debezium/time/Conversions.java
https://issues.jboss.org/browse/DBZ-578
> DBZ-578 Process timestamps without timezones as in server timezone

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
https://issues.jboss.org/browse/DBZ-711
@jpechane A small addition to the doc update for DBZ-711.
> DBZ-711 Using correct SSL mode names

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/NonStreamingWal2JsonMessageDecoder.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/StreamingWal2JsonMessageDecoder.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DecoderDifferences.java
https://issues.jboss.org/browse/DBZ-679
> DBZ-679 Support decoding of out-of-order fragments

- support/ide-configs/sublimetext/debezium.sublime-project
Enable working with Debezium in Sublime.
> Initial Sublime config

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueAllZeroTimeIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
https://issues.jboss.org/browse/DBZ-765
> DBZ-765 Reduce the amount of test prints

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
https://issues.jboss.org/browse/DBZ-767
> DBZ-767 Column should not be renamed when name is not changed

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnector.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.jboss.org/browse/DBZ-743
> DBZ-743 Empty password for PostgreSQL and MySQL

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDecimalColumnIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlNumericColumnIT.java
- debezium-connector-mysql/src/test/resources/ddl/decimal_column_test.sql
- debezium-connector-mysql/src/test/resources/ddl/numeric_column_test.sql
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
- debezium-core/src/main/java/io/debezium/data/SpecialValueDecimal.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java
- debezium-core/src/test/java/io/debezium/data/VerifyRecord.java
- debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java
https://issues.jboss.org/browse/DBZ-751
@jpechane This one came up recently in the chat room.
I also did a (manual) test that the parameter from the Connect schema is correctly translated into its Avro schema counterpart.
> DBZ-751 Propagating DECIMAL column precision to Avro schemas

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDefaultValuePreConverter.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/AbstractMysqlDefaultValueTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueAllZeroTimeIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
https://issues.jboss.org/browse/DBZ-768
@gunnarmorling Please think about impact of timezones on default values. Do we have it covered?
> DBZ-768 Default values with variable second fractions

- debezium-connector-mongodb/pom.xml
- debezium-connector-mysql/pom.xml
- pom.xml
https://issues.jboss.org/browse/DBZ-779
> DBZ-779 Detect mongo replicator init completion

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReaderMetrics.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReaderMetricsMXBean.java
https://issues.jboss.org/browse/DBZ-789
Exposing new snapshot metric:
Map containing tableName -> Rows Scanned
> DBZ-789 Expose more granular snapshot metrics via JMX

- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
- debezium-core/src/main/java/io/debezium/util/Clock.java
- debezium-core/src/main/java/io/debezium/util/Collect.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
Changes to core requred by SQL Server support
https://issues.jboss.org/browse/DBZ-40
> WIP: DBZ-40 Changes to support SQL Server connector

- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalSnapshotChangeEventSource.java
@jpechane As discussed. Will send the corresponding Oracle adjustment in a bit.
> DBZ-720 Signaling cancellation of snapshot through InterruptedException

- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/relational/history/TableChanges.java
- debezium-core/src/main/java/io/debezium/schema/SchemaChangeEvent.java
@jpechane I thought you could find this useful for the SQL Server work.
> DBZ-40 Pulling up some common code to HistorizedRelationalDatabaseSchema

- jenkins-jobs/scripts/release-pipeline.groovy
https://issues.jboss.org/browse/DBZ-796
> DBZ-796 Do not create new image dirs when exists

- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalSnapshotChangeEventSource.java
https://issues.jboss.org/browse/DBZ-803
> DBZ-803 Finalizing snapshot in offsets also for schema-only snapshots

- debezium-core/src/main/java/io/debezium/util/NumberConversions.java
- debezium-core/src/test/java/io/debezium/data/SchemaAndValueField.java
Preparations in core for https://issues.jboss.org/browse/DBZ-804
> DBZ-804 Better schema comparison in tests; preparing byte conversion

- debezium-core/src/main/java/io/debezium/data/VariableScaleDecimal.java
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlLexer.g4
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
https://issues.jboss.org/browse/DBZ-804
I've also filed https://github.com/antlr/grammars-v4/issues/1190 upstream.
> DBZ-804 Supporting negative scale values in Oracle grammar

- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
https://issues.jboss.org/browse/DBZ-816
@jpechane This will save a bit of repetition in the SQL Server connector. PR for Oracle is coming up.
> DBZ-816 Preparing code for database history set-up for re-use

- debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
- pom.xml
https://issues.jboss.org/browse/DBZ-858
> DBZ-858 Upgrade to Kafka 2.0.0

- jenkins-jobs/kafka-1.x-test.yml
http://ci.hibernate.org/view/Debezium/job/debezium-kafka-1.x-test/
> DBZ-858 CI for Kafka 1.x backward compatibility

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/relational/Tables.java
- debezium-core/src/main/java/io/debezium/relational/ddl/DdlParser.java
https://issues.jboss.org/browse/DBZ-872
> DBZ-872 Honor filters in ALTER TABLE parsing

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
https://issues.jboss.org/projects/DBZ/issues/DBZ-887
> DBZ-887 Close connection even for non-started producer

- jenkins-jobs/release.yaml
- jenkins-jobs/scripts/release-pipeline.groovy
https://issues.jboss.org/browse/DBZ-884
https://issues.jboss.org/browse/DBZ-885
https://issues.jboss.org/browse/DBZ-889
>  DBZ-884 DBZ-889 DBZ-885 Build process improvements

- jenkins-jobs/scripts/release-pipeline.groovy
https://issues.jboss.org/browse/DBZ-891
> DBZ-891 Release must contain at least one resolved issue

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TopicSelectorTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/TopicNameSanitizationIT.java
- debezium-connector-mysql/src/test/resources/ddl/topic_name_sanitization_test.sql
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-core/src/main/java/io/debezium/schema/TopicSelector.java
- debezium-core/src/main/java/io/debezium/util/BoundedConcurrentHashMap.java
- support/checkstyle/src/main/resources/checkstyle-suppressions.xml
https://issues.jboss.org/browse/DBZ-878, https://issues.jboss.org/browse/DBZ-865
Hey @jpechane, this PR sanitizes topic names by replacing any characters disallowed in Kafka topic names with a "_" character.
> DBZ-865 DBZ-878 Replacing invalid topic name characters with "_";

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.jboss.org/browse/DBZ-895
> DBZ-895 Make tcpKeepalive enabled by default

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
https://issues.jboss.org/browse/DBZ-907
> DBZ-907 Log refreshing schema due to different column count

- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
https://issues.jboss.org/browse/DBZ-819
> DBZ-819 Cache prepared statements in connection

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java
https://issues.jboss.org/browse/DBZ-784
> DBZ-784 Terminate execute loops during shutdown

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
https://issues.jboss.org/browse/DBZ-769
> DBZ-769 Try to release table locks during exception

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
https://issues.jboss.org/browse/DBZ-910
Upstream https://github.com/antlr/grammars-v4/pull/1234
> DBZ-910 Improve support for CHECK constraint

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- pom.xml
https://issues.jboss.org/browse/DBZ-912
> DBZ-912 Upgrading to Postgres driver 42.2.5

- jenkins-jobs/scripts/release-pipeline.groovy
https://issues.jboss.org/browse/DBZ-914
> DBZ-914 MAVEN_CENTRAL_SYNC_TIMEOUT should be an integer

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
https://issues.jboss.org/projects/DBZ/issues/DBZ-926
Just a minor fallout of DBZ-926. Still unclear whether it's actually an issue or not. If not, let's repurpose it to solely improving this log message.
> DBZ-926 Adding flushed LSN to log message

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/Wal2JsonReplicationMessage.java
https://issues.jboss.org/browse/DBZ-937
> DBZ-937 add wal2json replication message handling for CITEXT

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
Test fix for cases like https://github.com/debezium/debezium/pull/656
> DBZ-937 Disable auto-handling of unknown types in test

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlValueConvertersTest.java
https://issues.jboss.org/projects/DBZ/issues/DBZ-935
> DBZ-935 Error while parsing json column type for MySQL

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
https://issues.jboss.org/browse/DBZ-959
https://github.com/antlr/grammars-v4/pull/1284
> DBZ-959 ADD PARTITION needs parenthesis

- pom.xml
Docker images PR is open https://github.com/debezium/docker-images/pull/106
Not sure if I should update more dependencies, let's see how the build goes (Mongo is expected to fail due to mongo-init issues)
> DBZ-979 Upgrade Kafka to 2.0.1

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetrics.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetricsMXBean.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReaderMetrics.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReaderMetricsMXBean.java
- debezium-core/src/main/java/io/debezium/connector/common/CdcSourceTaskContext.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/ChangeEventSourceMetricsMXBean.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/Metrics.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/SnapshotChangeEventSourceMetrics.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/SnapshotChangeEventSourceMetricsMXBean.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/StreamingChangeEventSourceMetrics.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/StreamingChangeEventSourceMetricsMXBean.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/ArrivedEventListener.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/ChangeEventSourceFactory.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/DataChangeEventListener.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/SnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/SnapshotProgressListener.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalSnapshotChangeEventSource.java
https://issues.jboss.org/browse/DBZ-776
>  DBZ-776 A first set of metrics implemented in new framework

- .travis.yml
- debezium-connector-mysql/pom.xml
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlValueConvertersTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueTest.java
https://issues.jboss.org/browse/DBZ-757
> DBZ-757 Use antlr parser by default

- CONTRIBUTE.md
Easier to see here https://github.com/renatomefi/debezium/blob/docs/contributing/CONTRIBUTE.md
> Improve Contribute documentation

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
https://issues.jboss.org/browse/DBZ-1006
> DBZ-1006 Guard against NPE when start() fails

- debezium-ddl-parser/pom.xml
https://issues.jboss.org/browse/DBZ-1004
> DBZ-1004 antlr tests honor skipTests

- pom.xml
https://issues.jboss.org/browse/DBZ-1001
> DBZ-1001 Upgrade to Kafka 2.1

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
https://issues.jboss.org/browse/DBZ-1010
> DBZ-1010 Handle error deserialization also in deserializers

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
- debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
https://issues.jboss.org/browse/DBZ-1009
> DBZ-1009 Support for unknown types during snapshot

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
https://issues.jboss.org/browse/DBZ-1016
> DBZ-1016 Fix expected records count

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
https://issues.jboss.org/browse/DBZ-1005
> DBZ-1005 Detect GTID by database setting not GTID set

- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/schema/HistorizedDatabaseSchema.java
https://issues.jboss.org/browse/DBZ-1003
> DBZ-1003 Initialize database history

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.jboss.org/browse/DBZ-1021
> DBZ-1021 Ignore events for dropped table

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/UnwrapFromMongoDbEnvelope.java
Now it's easier to follow what makes an insert, update or delete within the transformer, also reduced the amount of npath complexity by doing early returns and certain extractions.
I think  it's better to review by reading the new code, the diff is quite messy
> DBZ-1020 Refactor UnwrapFromMongoDbEnvelope logic

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/UnwrapFromMongoDbEnvelope.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/UnwrapFromMongoDbEnvelopeTest.java
https://issues.jboss.org/browse/DBZ-1032
> DBZ-1032 UnwrapFromMongoDbEnvelope doesn't support operation header on tombstone messages

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTaskContextIT.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
https://issues.jboss.org/browse/DBZ-960
> DBZ-960 Run SnapshotReader in a single transaction

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTaskContextTest.java
https://issues.jboss.org/browse/DBZ-1008
> DBZ-1008 Process first GTID after failover

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
- debezium-connector-mysql/src/test/docker/init-alt-replica/setup.sql
- debezium-connector-mysql/src/test/docker/init-replica/setup.sql
- debezium-connector-mysql/src/test/docker/init/setup.sql
- debezium-connector-mysql/src/test/docker/server-gtids/my.cnf
- debezium-connector-mysql/src/test/docker/server-replica/my.cnf
- debezium-connector-mysql/src/test/docker/server/my.cnf
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/DatabaseDifferences.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MetadataIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySQLConnection.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlGeometryIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
- debezium-connector-mysql/src/test/resources/ddl/geometry_test.sql
- debezium-connector-mysql/src/test/resources/ddl/geometry_test_5.sql
- debezium-connector-mysql/src/test/resources/ddl/geometry_test_8.sql
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- jenkins-jobs/mysql-matrix-test.yaml
- pom.xml
There are 5 test failures under investigation
> DBZ-688 Support for test execution on MySQL 8 server

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
https://issues.jboss.org/browse/DBZ-996
> DBZ-996 Tolerate race condition in PK updates

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
https://issues.jboss.org/browse/DBZ-1059
> DBZ-1059 Support qualified table name in rename

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
https://issues.jboss.org/browse/DBZ-1067
> DBZ-1067 Add column blacklist field to RelationalDatabaseConnectorConfig

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlSourceTypeInSchemaIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
- debezium-core/src/main/java/io/debezium/relational/mapping/PropagateSourceTypeToSchemaParameter.java
- debezium-core/src/test/java/io/debezium/relational/mapping/PropagateSourceTypeToSchemaParameterTest.java
This PR adds the scale, if exists, to the column type propagation.
> [DBZ-1073] Propagate column type scale

- COPYRIGHT.txt
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/ChainedReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/Filters.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/HaltingPredicate.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/ParallelSnapshotReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/ReconcilingBinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RecordMakers.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTaskContextTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ParallelSnapshotReaderTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReconcilingBinlogReaderTest.java
Integrate all the smaller DBZ-175 changes into a final change that will trigger parallel snapshotting if the proper config is enabled and there are new tables in the config.
> DBZ-175 integration into normal task flow

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.jboss.org/browse/DBZ-781
> DBZ-781 Enable unstable tests

- debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
- debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java
https://issues.jboss.org/browse/DBZ-1089
> DBZ-1089 Use only schema name when both catalog and schema is present

- debezium-core/src/main/java/io/debezium/transforms/ByLogicalTableRouter.java
- debezium-core/src/test/java/io/debezium/transforms/ByLogicalTableRouterTest.java
https://issues.jboss.org/browse/DBZ-1086
> DBZ-1086 Added functionality to handle key-less messages if topic routing is enabled

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetrics.java
addressing Jiri's comment re: metrics names.
> DBZ-175: Modify BinlogReaderMetrics to take in the BinlogReader name.

- COPYRIGHT.txt
- debezium-connector-mysql/pom.xml
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetrics.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/ChainedReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/Filters.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/HaltingPredicate.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/ParallelSnapshotReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/ReconcilingBinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RecordMakers.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/Configurator.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTaskContextIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTaskContextTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ParallelSnapshotReaderTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReconcilingBinlogReaderTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotReaderIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java
- pom.xml
as discussed on the DBZ-175 ticket, merge the [DBZ-175](https://issues.jboss.org/browse/DBZ-175) feature branch into master.
> Merge DBZ-175 into master

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractReader.java
https://issues.jboss.org/browse/DBZ-1099
> DBZ-1099 Don't enque further records after request to stop

- COPYRIGHT.txt
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalSnapshotChangeEventSource.java
https://issues.jboss.org/browse/DBZ-947
> DBZ-947 SQL Server snapshot.locking.modes overhaul

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationConnection.java
https://issues.jboss.org/browse/DBZ-1111
@jpechane I think this should go into 0.9.0.Final. I.e. it needs merging not only into master but into a 0.9.0 delivery branch, too.
> DBZ-1111 Allowing to use drop-slot-on-close with PG 10 or newer

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
https://issues.jboss.org/browse/DBZ-1097
> DBZ-1097 High-level design description of SQL Server streaming

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeRecordEmitter.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
@jpechane Small fix while musing over DBZ-1096.
> DBZ-1096 Removing unused parameter

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/TxLogPosition.java
https://issues.jboss.org/browse/DBZ-1131
> DBZ-1131 Correct log position comparison

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDefaultValuePreConverter.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/AbstractMysqlDefaultValueTest.java
https://issues.jboss.org/browse/DBZ-983
> DBZ-983 BigDecimal default value scales according to column

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerDatabaseSchema.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSchemaChangeEventEmitter.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerChangeTableSetIT.java
- debezium-core/src/main/java/io/debezium/relational/history/AbstractDatabaseHistory.java
- debezium-core/src/main/java/io/debezium/relational/history/TableChanges.java
https://issues.jboss.org/browse/DBZ-1121
> DBZ-1121 Emit ALTER event for updated tables

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
https://issues.jboss.org/browse/DBZ-1065
> DBZ-1065 Result set is only partionally buffered by default

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnector.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetMonitorThread.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/ReplicationConnectionIT.java
- debezium-core/src/main/java/io/debezium/util/Metronome.java
https://issues.jboss.org/browse/DBZ-1019
> DBZ-1019 Guard against wall-clock change

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerOffsetContext.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/TxLogPosition.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
https://issues.jboss.org/browse/DBZ-1128
includes https://github.com/debezium/debezium/pull/780
>  DBZ-1128 Data could be lost from incompletely streamed tx after restart

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-core/src/main/java/io/debezium/relational/TableEditorImpl.java
https://issues.jboss.org/browse/DBZ-997
> DBZ-997 Test PK structure change

- pom.xml
https://issues.jboss.org/browse/DBZ-1140
> DBZ-1140 Upgrading binlog client to 0.19.0

- debezium-connector-sqlserver/pom.xml
https://issues.jboss.org/browse/DBZ-1138
> DBZ-1138 Fixing dependency scopes for SQL Server connector

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
https://issues.jboss.org/browse/DBZ-1147
> DBZ-1147 Single quotes for string constant

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SpecialCharsInNamesIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerChangeTableSetIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
- debezium-connector-sqlserver/src/test/resources/generate_cdc_wrappers.sql
- debezium-core/src/main/java/io/debezium/relational/history/TableChanges.java
https://issues.jboss.org/browse/DBZ-1153
> DBZ-1153 Support for special char names

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
- pom.xml
https://issues.jboss.org/browse/DBZ-1156
https://issues.jboss.org/browse/DBZ-1157
> DBZ-1156 DBZ-1157 Upgrade to Kafka 2.1.1, Confluent Plat. 5.1.2

- COPYRIGHT.txt
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbTaskContext.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ReplicatorIT.java
Feel free to comment regarding any issues you find.
https://issues.jboss.org/browse/DBZ-867
> DBZ-867 Add snapshot mode NEVER for MongoDB connector

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DecoderDifferences.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.jboss.org/browse/DBZ-1146
> DBZ-1146 Handle toastable columns for snapshotted tables

- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalSnapshotChangeEventSource.java
https://issues.jboss.org/browse/DBZ-1170
> DBZ-1170 Detect and handle errors like ULE

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnector.java
https://issues.jboss.org/browse/DBZ-1188
> DBZ-1188 False pasitive warning for non-empty password

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
https://issues.jboss.org/browse/DBZ-1186
> DBZ-1186 Comma is not mandatory between table options

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.jboss.org/browse/DBZ-1161
> DBZ-1161 Start snapshot in async thread

- pom.xml
https://issues.jboss.org/browse/DBZ-1191
> DBZ-1191 Fix unsigned short deserialization problem

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDateTimeInKeyIT.java
- debezium-connector-mysql/src/test/resources/ddl/datetime_key_test.sql
- debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
https://issues.jboss.org/browse/DBZ-1194
> DBZ-1194 Convert nulls even for key

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PublicGeometryIT.java
https://issues.jboss.org/browse/DBZ-1144
It needs postres images rebuilt with https://github.com/debezium/postgres-decoderbufs/pull/17 to pass the tests.
> DBZ-1144 Test for geometry in public schema

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnector.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java
- debezium-core/src/main/java/io/debezium/relational/TableSchema.java
- debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
- debezium-core/src/main/java/io/debezium/relational/ddl/AbstractDdlParser.java
- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
- debezium-core/src/main/java/io/debezium/transforms/UnwrapFromEnvelope.java
- debezium-core/src/main/java/io/debezium/util/IoUtil.java
- debezium-core/src/main/java/io/debezium/util/Threads.java
- debezium-core/src/test/java/io/debezium/kafka/KafkaCluster.java
- debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
https://issues.jboss.org/browse/DBZ-1212
> DBZ-1212 SLF4J usage issues

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/ColumnDefinitionParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlEnumColumnIT.java
- debezium-connector-mysql/src/test/resources/ddl/enum_column_test.sql
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/main/java/io/debezium/antlr/AntlrDdlParser.java
https://issues.jboss.org/browse/DBZ-1203
> DBZ-1203 Alter Enum Column When Changing Character Set

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlSourceTypeInSchemaIT.java
- debezium-connector-mysql/src/test/resources/ddl/source_type_as_schema_parameter_test.sql
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
https://issues.jboss.org/browse/DBZ-1220
> DBZ-1220 FLOAT supports also single precision constraint

- pom.xml
https://issues.jboss.org/browse/DBZ-1227
> DBZ-1227 Upgrade to Kafka 2.2.0

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDefaultValuePreConverter.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlAntlrDefaultValueTest.java
https://issues.jboss.org/browse/DBZ-1249
> DBZ-1249 Fix default value conversion for larget bits

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PgOid.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoReplicationMessage.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/Wal2JsonReplicationMessage.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java
- debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
DBZ-1076 [Postgresql ARRAY support](https://issues.jboss.org/browse/DBZ-1076?jql=project%20%3D%20DBZ%20AND%20status%20%3D%20Open%20AND%20labels%20%3D%20easy-starter)
> DBZ-1076 Postgresql ARRAY support

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDefaultValuePreConverter.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTimestampColumnIT.java
- debezium-connector-mysql/src/test/resources/ddl/timestamp_column_test.sql
https://issues.jboss.org/browse/DBZ-1243
> DBZ-1243 Fix handling of default value for datetime(0)

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
https://issues.jboss.org/browse/DBZ-1236
> DBZ-1236 Support full timestamptz precision

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/ColumnDefinitionParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlEnumColumnIT.java
- debezium-connector-mysql/src/test/resources/ddl/enum_column_test.sql
- debezium-core/src/main/java/io/debezium/relational/Column.java
- debezium-core/src/main/java/io/debezium/relational/ColumnEditor.java
- debezium-core/src/main/java/io/debezium/relational/ColumnEditorImpl.java
- debezium-core/src/main/java/io/debezium/relational/ColumnImpl.java
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
https://issues.jboss.org/browse/DBZ-1226
**NOTE**: Be sure to change the commit message to DBZ-1226 prior to merge.
> DBZ-1226 Fix parsing of enum/set values to support values that contain commas or escaped characters.

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-core/src/main/java/io/debezium/heartbeat/HeartbeatImpl.java
https://issues.jboss.org/browse/DBZ-1245
> DBZ-1245 Heartbeat only when offsets ready

- COPYRIGHT.txt
https://issues.jboss.org/browse/DBZ-1259
I'll circle back to this right before 0.10 to capture any recent commits from new contributors.
> WIP: DBZ-1259 Add missing contributors to COPYRIGHT.txt

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateUniqueIndexParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
https://issues.jboss.org/browse/DBZ-1264
> DBZ-1264 Ignore unique index for non-monitored tables

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
https://issues.jboss.org/browse/DBZ-1281
> DBZ-1281 Warning for no change table situations

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateUniqueIndexParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
https://issues.jboss.org/browse/DBZ-1246
> DBZ-1246 Convert unique index to primary key

- COPYRIGHT.txt
- jenkins-jobs/scripts/check-contributors.sh
- jenkins-jobs/scripts/config/Aliases.txt
- jenkins-jobs/scripts/config/FilteredNames.txt
- jenkins-jobs/scripts/release-pipeline.groovy
https://issues.jboss.org/browse/DBZ-1282
> DBZ-1282 -  Automate contributor check during release pipeline

- debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
https://issues.jboss.org/browse/DBZ-1257
> DBZ-1257 Validate data against schema

- debezium-core/src/main/java/io/debezium/pipeline/metrics/ChangeEventSourceMetricsMXBean.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/Metrics.java
https://issues.jboss.org/browse/DBZ-1209
> DBZ-1209 Remove events skipped metric form common metrics

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlRestartIT.java
https://issues.jboss.org/browse/DBZ-1276
> DBZ-1276 Skip events upon connector restart

- debezium-core/src/main/java/io/debezium/transforms/UnwrapFromEnvelope.java
- debezium-core/src/test/java/io/debezium/transforms/UnwrapFromEnvelopeTest.java
https://issues.jboss.org/browse/DBZ-1234
@Naros, this relates to the removal of deprecated features. I'll also send a PR for updating the docs. Thanks!
> DBZ-1234 Removing deprecated "drop.deletes" SMT option

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/UseStatementParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlGeometryIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlRestartIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ZZZGtidSetIT.java
- debezium-core/src/main/java/io/debezium/relational/ddl/AbstractDdlParser.java
- debezium-core/src/main/java/io/debezium/relational/ddl/DdlChanges.java
- debezium-core/src/main/java/io/debezium/relational/ddl/DdlParserListener.java
- debezium-ddl-parser/src/main/java/io/debezium/antlr/AntlrDdlParser.java
https://issues.jboss.org/browse/DBZ-683
> DBZ-683 Snapshot supports storing only whitelisted tables setting

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/ColumnDefinitionParserListener.java
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
https://issues.jboss.org/browse/DBZ-1127
Upstream PR https://github.com/antlr/grammars-v4/pull/1410
> DBZ-1127 Synchronize MySQL grammar with upstream grammar.

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/OutboxEventRouterIT.java
- debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterConfigDefinition.java
https://issues.jboss.org/browse/DBZ-1289
@renatomefi And here's the code fix. I went for the "event" suffix everywhere, as that seemed most consistent to me.
> DBZ-1289 Making outbox router options more consistent

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/Filters.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/Filters.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/relational/Selectors.java
- debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
- debezium-core/src/main/java/io/debezium/relational/Tables.java
https://issues.jboss.org/browse/DBZ-1092
@jpechane, ready for review now. I'm limiting the scope of this issue to column name filters and will create a follow-up for the others. It's not too critical, but I wanted to get this pending PR off the plate eventually.
> DBZ-1092 Using ColumnNameFilter instead of Predicate<Column>

- debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-drivers.xml
- debezium-connector-mongodb/pom.xml
- debezium-connector-mysql/pom.xml
- debezium-connector-postgres/pom.xml
- debezium-connector-sqlserver/pom.xml
- pom.xml
https://issues.jboss.org/browse/DBZ-1303
> DBZ-1303 Assembly without database drivers

- jenkins-jobs/scripts/release-pipeline.groovy
https://issues.jboss.org/browse/DBZ-1304
> Align release pipeline to the new Dockerfiles

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotReaderIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSourceInfoStructMaker.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SourceInfoTest.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceInfo.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerOffsetContext.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/LegacyV1SourceInfoTest.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SourceInfoTest.java
- debezium-core/src/main/java/io/debezium/connector/AbstractSourceInfo.java
- debezium-core/src/main/java/io/debezium/connector/AbstractSourceInfoStructMaker.java
- debezium-core/src/main/java/io/debezium/connector/SnapshotRecord.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceInfo.java
- debezium-core/src/main/java/io/debezium/pipeline/spi/OffsetContext.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalSnapshotChangeEventSource.java
https://issues.jboss.org/browse/DBZ-1295
> DBZ-1295 Support for 3state snapshot

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationStream.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/ReplicationConnectionIT.java
https://issues.jboss.org/browse/DBZ-1310
@jpechane, @Naros: minor improvement I did during the native replication exploration. Could either of you merge it? Thanks!
> DBZ-1310 Removing methods only needed for testing

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/MongoDataConverter.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/MongoDataConverterTest.java
https://issues.jboss.org/browse/DBZ-1315
> DBZ-1315 UNDEFINED field causes exception

- pom.xml
https://issues.jboss.org/browse/DBZ-1316
> DBZ-1316 Update to Kafka 2.2.1

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseSchema.java
- debezium-core/src/test/java/io/debezium/junit/logging/LogInterceptor.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
https://issues.jboss.org/browse/DBZ-1242
> DBZ-1242 Issue warning when filters produce an empty schema

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
https://issues.jboss.org/browse/DBZ-1321
> DBZ-1321 Fix alter by modify column about default value

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
@gunnarmorling This is just a very short followup to DBZ-1318
Thinking about the issue I beleive the conversion should not be done silently as it can do something that might not be expected by the operator.
> DBZ-1318 Log when conversion happens

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/LegacyV1MongoDbSourceInfoStructMaker.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSourceInfoStructMaker.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/RecordMakers.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/MongoDataConverter.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/LegacyV1SourceInfoTest.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/RecordMakersTest.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/LegacyV1SourceInfoTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SourceInfoTest.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceInfo.java
- debezium-core/src/main/java/io/debezium/connector/AbstractSourceInfo.java
https://issues.jboss.org/browse/DBZ-1317
@jpechane, that's a fallout from the source info refactoring.
> DBZ-1317 Collection id is optional in MongoDB events

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/StreamingWal2JsonMessageDecoder.java
https://issues.jboss.org/browse/DBZ-1323
> DBZ-1323 Initialize commitTime for out-of-order chunk

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerOffsetContext.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
https://issues.jboss.org/browse/DBZ-1152
> DBZ-1152 Record operation order for changes with the same LSNs

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
https://issues.jboss.org/browse/DBZ-835
> DBZ-835 Emit tombstone optionally

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldBlacklistTest.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldRenamesTest.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/RecordMakersTest.java
- pom.xml
Jira is not running so no issue has been created yet.
> DBZ-1333 Upgrade MongoDb driver to 3.10.1

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
https://issues.jboss.org/browse/DBZ-1329
> DBZ-1329 Support for rename index

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.jboss.org/browse/DBZ-1331
> DBZ-1331 | allow `SET NEW.column=expression` in triggers

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.jboss.org/browse/DBZ-1332
> DBZ-1332 | COLLATE support in return types of the MySQL functions

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeEventSourceFactory.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
https://issues.jboss.org/projects/DBZ/issues/DBZ-1065
> DBZ-1065 Use separate connection for metadata

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RecordMakers.java
- debezium-core/src/main/java/io/debezium/util/Strings.java
- debezium-core/src/test/java/io/debezium/util/StringsTest.java
https://issues.jboss.org/browse/DBZ-1340
> DBZ-1340 Guard against binlog misconfiguration

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
https://issues.jboss.org/browse/DBZ-1342
> DBZ-1342 Partitioned table is included in snapshot

- debezium-core/src/main/java/io/debezium/connector/SnapshotRecord.java
https://issues.jboss.org/projects/DBZ/issues/DBZ-1346
> DBZ-1346 Fix description for state of Snapshot

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
https://issues.jboss.org/browse/DBZ-1349
> DBZ-1349 Support for UTF8mb3 charset

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
https://issues.jboss.org/browse/DBZ-1345
> DBZ-1345 Should not snapshot materialized views

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationStream.java
https://issues.jboss.org/browse/DBZ-1347
> DBZ-1347 Switch to non-blocking stream read

- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
https://issues.jboss.org/browse/DBZ-1361
> DBZ-1361 Restoring compatibility with Apache Kafka 1.x

- debezium-core/src/test/java/io/debezium/kafka/KafkaServer.java
- pom.xml
https://issues.jboss.org/browse/DBZ-1358
> DBZ-1358 Update to Kafka 2.3.0

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/AbstractReplicationMessageColumn.java
https://issues.jboss.org/browse/DBZ-1366
> DBZ-1366 Avoid creating unnecessary TypeMetadataImpl instances; only init once.

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbTaskContext.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java
https://issues.jboss.org/browse/DBZ-1365
@Naros Can you review and merge? Just a small improvement as I was looking for callers of `CommonConnectorTask#isEmitTombstones()`. Thanks!
> Handling option for emitting tombstones conistently

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-core/src/main/java/io/debezium/heartbeat/HeartbeatImpl.java
https://issues.jboss.org/browse/DBZ-1363
> DBZ-1363 Generate heartbeat periodically not upon event

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/ChangeEventSourceMetricsMXBean.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/PipelineMetrics.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/DataChangeEventListener.java
https://issues.jboss.org/browse/DBZ-1222
> DBZ-1222 EventsInError metric added

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-core/src/main/java/io/debezium/annotation/VisibleForTesting.java
https://issues.jboss.org/browse/DBZ-1380
> DBZ-1380 Guard against partially initilized replication slot

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
Ticket: https://issues.jboss.org/browse/DBZ-1379
Inspired by: https://github.com/debezium/debezium/pull/816
> DBZ-1379 Fix PostgreSQL false empty password Warn

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderBufferIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-core/src/main/java/io/debezium/relational/history/DatabaseHistory.java
https://issues.jboss.org/browse/DBZ-794
> DBZ-794 Filter out savepoints from database history

- README.md
- debezium-connector-postgres/RDS.md
- debezium-connector-postgres/README.md
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/ReplicationConnectionIT.java
- debezium-connector-postgres/src/test/resources/init_postgis.ddl
https://issues.jboss.org/browse/DBZ-1371
> DBZ-1371 Fix tests to run more reliably on Amazon RDS

- debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java
- debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
https://issues.jboss.org/browse/DBZ-1388
This will enable consumers/SMTs and others to operate knowing the intent of the message, rather than guessing by the destination topic
> DBZ-1388 Add header to heartbeat records

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbTaskContext.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbTopicSelector.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
- debezium-core/src/main/java/io/debezium/heartbeat/Heartbeat.java
- debezium-core/src/main/java/io/debezium/heartbeat/HeartbeatImpl.java
https://issues.jboss.org/browse/DBZ-1198
> DBZ-1198 Heartbeat for MongoDB connector

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
Just review with white space change ignore
https://issues.jboss.org/browse/DBZ-599
> DBZ-599 Emit schema change only for DDL with no errors

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
https://issues.jboss.org/browse/DBZ-916
> DBZ-916 Keyless tables have null key by default

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
https://issues.jboss.org/browse/DBZ-1397
Upstream issue - https://github.com/antlr/grammars-v4/pull/1465
> DBZ-1397 Support CHARSET in CAST function

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
https://issues.jboss.org/browse/DBZ-1398
upstream issue https://github.com/antlr/grammars-v4/pull/1463
> DBZ-1398 Support for arbitrary third party engine name

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/Filters.java
https://issues.jboss.org/browse/DBZ-1409
> DBZ-1409 Built-in database filter throws NPE

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
https://issues.jboss.org/browse/DBZ-1410
> DBZ-1410 Filter DML before throwing an invalid replication format error

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalSnapshotChangeEventSource.java
Re-order the captured tables in the same order as the 'table.whitelist' parameter.
> [DBZ-1254] Re-order the captured tables

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/ExportedSnapshotter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.jboss.org/browse/DBZ-1035
> DBZ-1035 Support PostgreSQL lock-free snapshot using exported snapshots

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
https://issues.jboss.org/browse/DBZ-1411
Upstream issue https://github.com/antlr/grammars-v4/pull/1472
> DBZ-1411 Support unquted full names in GRANT

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ZZZGtidSetIT.java
https://issues.jboss.org/browse/DBZ-1414
> DBZ-1414 Lock only monitored tables

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java
https://issues.jboss.org/browse/DBZ-1417
> DBZ-1417 Lock is tablewide, remove fullscan

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java
https://issues.jboss.org/browse/DBZ-1381
> DBZ-1381 Introduce permanent metadata connection

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentState.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTest.java
https://issues.jboss.org/browse/DBZ-1430
> DBZ-1430 Support heartbeat ExtractNewDocumentState

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
https://issues.jboss.org/browse/DBZ-1432
> DBZ-1432 Align custom engine parsing with upstream

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
https://issues.jboss.org/browse/DBZ-1436
> DBZ-1436 Fix postgres connector not honoring publication.name configuration

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
https://issues.jboss.org/browse/DBZ-1440
> Supports exported snapshots for Pg 9.4+

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/ExportedSnapshotter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/InitialOnlySnapshotter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.jboss.org/browse/DBZ-1437
> DBZ-1437 Fix ExportedSnapshotter/InitialOnlySnapshotter to properly determine when to run a snapshot

- documentation/modules/ROOT/pages/connectors/cassandra.adoc
Migrated PR https://github.com/debezium/debezium.github.io/pull/345 to the main repository since we have moved documentation here rather than in the website repository.
> DBZ-1406 Update doc for cassandra connector config file with properties format.

- CONTRIBUTE.md
- RELEASING.md
@Naros, @jpechane Added some lines to the contribution guide on the doc branching.
> DBZ-317 Updating contribution guides regarding documentation

- documentation/modules/ROOT/pages/configuration/event-flattening.adoc
- documentation/modules/ROOT/pages/configuration/mongodb-event-flattening.adoc
https://issues.jboss.org/browse/DBZ-1471
> DBZ-1471 Use UnwrapFromEnvelope SMT name in 0.9 docs

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.jboss.org/browse/DBZ-1472
> DBZ-1472 Speak of primary/secondary rather than master/slave for PostgreSQL

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
- debezium-core/src/main/java/io/debezium/schema/FieldNameSelector.java
- debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java
- documentation/modules/ROOT/pages/configuration/avro.adoc
- documentation/modules/ROOT/pages/connectors/cassandra.adoc
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/mysql.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.jboss.org/browse/DBZ-1044
This PR supersedes PR #961.  It includes all the previous commit work plus additional work rebased against the current repository master branch.
> DBZ-1044 Sanitize column/topic names to always be valid Avro Names

- documentation/modules/ROOT/pages/install.adoc
- jenkins-jobs/sync-images.yaml
https://issues.jboss.org/browse/DBZ-1178
> DBZ-1178 Synchronize Debezium images

- documentation/modules/ROOT/pages/postgres-plugins.adoc
https://issues.jboss.org/browse/DBZ-1286
> DBZ-1286 Document protobuf installation from RPM

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoUtil.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetMonitorThread.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/AbstractMySqlConnectorOutputTest.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
- debezium-core/src/main/java/io/debezium/util/DelayStrategy.java
- debezium-core/src/main/java/io/debezium/util/Threads.java
- debezium-core/src/test/java/io/debezium/kafka/ZookeeperServer.java
- debezium-embedded/README.md
- debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
- documentation/modules/ROOT/pages/operations/embedded.adoc
https://issues.jboss.org/browse/DBZ-1438
Superesedes https://github.com/debezium/debezium/pull/1001
> DBZ-1438 Fix InterruptedException handling

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
https://issues.jboss.org/browse/DBZ-1500
> DBZ-1500 Fix race condition in mysql connector test suite

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.jboss.org/browse/DBZ-1503
* Use current versus 9.6 (version specific) documentation links
* Rephrased a section to have better readability
> DBZ-1503 Update PostgreSQL connector documentation

- debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java
https://issues.jboss.org/browse/DBZ-1495
> DBZ-1495 Avoid NPE by throwing more meaningful error messages

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-core/src/main/java/io/debezium/time/MicroDuration.java
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.jboss.org/browse/DBZ-1497
> DBZ-1497 Using int64 for INTERVAL microseconds mapping

- pom.xml
https://issues.jboss.org/browse/DBZ-1462
> DBZ-1462 Upgrade to latest PostgreSQL JDBC driver

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDefaultValueConverter.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
https://issues.jboss.org/browse/DBZ-1501
> DBZ-1501 Support partial timstamps in default values

- debezium-core/src/test/java/io/debezium/document/DocumentTest.java
https://issues.jboss.org/browse/DBZ-1508
> DBZ-1508 Avoiding assertion based on platform-specific line endings

- .travis.yml
https://issues.jboss.org/projects/DBZ/issues/DBZ-1504
> DBZ-1504 Reverting temporary image change

- debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java
- debezium-core/src/test/java/io/debezium/transforms/ExtractNewRecordStateTest.java
https://issues.jboss.org/browse/DBZ-1517
> DBZ-1517 Skip unknow records while operation header is used

- documentation/modules/ROOT/pages/connectors/mysql.adoc
https://issues.jboss.org/browse/DBZ-685
> DBZ-685 Document MySQL session timeout

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.jboss.org/browse/DBZ-1515
> DBZ-1515 Add poll pause only after multiple no message attempts

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MetadataIT.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java
- debezium-core/src/main/java/io/debezium/relational/Key.java
- debezium-core/src/main/java/io/debezium/relational/Table.java
- debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java
- debezium-core/src/test/java/io/debezium/relational/TableTest.java
https://issues.jboss.org/browse/DBZ-1507
> DBZ-1507 Ensure message keys have correct field order

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
- debezium-core/src/test/java/io/debezium/junit/logging/LogInterceptor.java
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.jboss.org/browse/DBZ-1280
> DBZ-1280 Lock timeout for SQL Server

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentState.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTest.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/StreamingChangeEventSourceMetrics.java
- debezium-core/src/main/java/io/debezium/pipeline/spi/SnapshotResult.java
- debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java
- debezium-core/src/main/java/io/debezium/transforms/SmtManager.java
- debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java
- debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
Start for discussion on https://issues.jboss.org/browse/DBZ-1513?focusedCommentId=13791336&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13791336
> DBZ-1513 Centralize handling of non-data messages in SMT

- .travis.yml
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoReplicationMessage.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-core/src/main/java/io/debezium/time/Interval.java
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.jboss.org/browse/DBZ-1498
Depends on https://github.com/debezium/postgres-decoderbufs/pull/21
> DBZ-1498 Support for precise interval value

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SnapshotWithOverridesProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TablesWithoutPrimaryKeyIT.java
- debezium-connector-sqlserver/pom.xml
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TablesWithoutPrimaryKeyIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
https://issues.jboss.org/browse/DBZ-1401
> DBZ-1401 Handle tables without explicit PK

- documentation/modules/ROOT/pages/operations/amq-streams.adoc
- documentation/modules/ROOT/pages/operations/embedded.adoc
- documentation/modules/ROOT/pages/operations/logging.adoc
- documentation/modules/ROOT/pages/operations/monitoring.adoc
- documentation/modules/ROOT/pages/operations/openshift.adoc
@Naros, can you review and merge. I don't think an issue is needed, it's still "typo fix" level :) Thanks!
> [docs] Adding table of contents on multiple pages

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.jboss.org/browse/DBZ-892
> DBZ-892 Flush on empty messages

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
Extends https://github.com/debezium/debezium/pull/1086
> DBZ-1564 Close open idle transactions

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-core/src/main/java/io/debezium/relational/TableEditorImpl.java
https://issues.jboss.org/browse/DBZ-1560
> DBZ-1560 Removed dropped PK from the list

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.jboss.org/browse/DBZ-1525
> DBZ-1525 Validate replication slot name

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
https://issues.jboss.org/browse/DBZ-1428
> DBZ-1428 Restore TX isolation level after table read lock

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
The grammar was simpliefied in upstream project
> DBZ-1534 DBZ-1535 Simplify grammar

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
https://issues.jboss.org/browse/DBZ-1554
> DBZ-1554 Add connection parameters into params list

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
https://issues.jboss.org/browse/DBZ-1583
> DBZ-1583 Propagate Replicator exception to Kafka Connect

- documentation/modules/ROOT/pages/operations/amq-streams.adoc
https://issues.jboss.org/browse/DBZ-1543
> DBZ-1543 Update documentation based on Technology Preview

- debezium-core/src/test/java/io/debezium/junit/logging/LogInterceptor.java
https://issues.jboss.org/browse/DBZ-1590
> DBZ-1590 Fix LogInterceptor to be thread-safe

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.jboss.org/browse/DBZ-1576
> DBZ-1576 Gracefully skip TRUNCATE messages with pgoutput decoder on PG11+

- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
https://issues.jboss.org/browse/DBZ-1592
> DBZ-1592 Generate heartbeats for filtred events

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
https://issues.jboss.org/browse/DBZ-1593
> DBZ-1593 Add tombstones.on.delete to options list

- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
https://issues.jboss.org/browse/DBZ-1569
> DBZ-1569 Don't compute index statistics

- pom.xml
https://issues.jboss.org/browse/DBZ-1597
> DBZ-1597 Upgrade MongoDB driver to 3.11.1

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.jboss.org/browse/DBZ-1595
> DBZ-1595 Use dots as separator in param name

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
https://issues.jboss.org/browse/DBZ-1596
> DBZ-1596 Fix open resources while initializing publication

- documentation/modules/ROOT/pages/operations/amq-streams.adoc
Fixed Beta1 -> Beta2 in upstream release reference.
> DBZ-1543 fixed upstream release reference in AMQ docs

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.jboss.org/browse/DBZ-1518
> DBZ-1518 Clarify default replica identity event content

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RecordMakers.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-core/src/main/java/io/debezium/data/Envelope.java
- debezium-core/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java
- debezium-core/src/test/java/io/debezium/transforms/ExtractNewRecordStateTest.java
- debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
https://issues.jboss.org/browse/DBZ-1607
Incorporates https://github.com/debezium/debezium/pull/1128
> DBZ-1588 DBZ-1607 use Instant for envelope timestamps

- pom.xml
https://issues.jboss.org/projects/DBZ/issues/DBZ-1612
> Upgrade to Kafka 2.3.1

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.jboss.org/browse/DBZ-1610
> DBZ-1610 Document renamed ts_usec to ts_ms

- .travis.yml
- CONTRIBUTE.md
- pom.xml
https://issues.jboss.org/browse/DBZ-1603
> DBZ-1603 Only run format validation on Travis CI and not auto-format.

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/pipeline/spi/SnapshotResult.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/schema/DatabaseSchema.java
https://issues.jboss.org/browse/DBZ-1519
This PR supersedes PR #1087.
> [DBZ-1519] Debezium Erroneously Reporting No Tables to Capture

- debezium-core/src/main/java/io/debezium/util/VariableLatch.java
https://issues.jboss.org/browse/DBZ-1622
> DBZ-1622 VariableLatch Bugfix

- debezium-core/src/main/java/io/debezium/util/IoUtil.java
https://issues.jboss.org/browse/DBZ-1621
> DBZ-1621 IoUtil Bugfix	

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java
https://issues.jboss.org/browse/DBZ-825
> DBZ-825 Unify decimal upscaling

- .travis.yml
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSourceInfoStructMaker.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/RecordMakers.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldBlacklistTest.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldRenamesTest.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/RecordMakersTest.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TestHelper.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTest.java
https://issues.jboss.org/browse/DBZ-1215
> DBZ-1215 Added support for transactions

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.jboss.org/browse/DBZ-1480
> DBZ-1480 Add read_committed snapshot isolation level

- .travis.yml
- debezium-connector-mongodb/pom.xml
- debezium-connector-mysql/pom.xml
- debezium-connector-postgres/pom.xml
- debezium-connector-sqlserver/pom.xml
- debezium-core/src/main/java/io/debezium/config/Instantiator.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
- debezium-core/src/main/java/io/debezium/relational/mapping/ColumnMappers.java
- debezium-core/src/test/java/io/debezium/junit/ConditionalFail.java
- debezium-ddl-parser/pom.xml
- debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
- debezium-embedded/src/test/java/io/debezium/embedded/ConnectorOutputTest.java
- pom.xml
- support/checkstyle/pom.xml
https://issues.jboss.org/browse/DBZ-1402
Supersedes https://github.com/debezium/debezium/pull/1039
> DBZ-1402 Support for JDK 11

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
https://issues.jboss.org/browse/DBZ-1201
> DBZ-1201 Always store SET commands

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
https://issues.jboss.org/browse/DBZ-1645
> DBZ-1645 Allow alter and rename table in a single step

- jenkins-jobs/job-dsl/sql_server_matrix_test.groovy
https://issues.jboss.org/browse/DBZ-1644
> DBZ-1644 Add SQL Server test matrix

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlEnumColumnIT.java
https://issues.redhat.com/browse/DBZ-1636
> DBZ-1636 Add MySQL ENUM test propagating source type schema parameters

- debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution.xml
- debezium-core/pom.xml
- debezium-core/src/main/java/io/debezium/serde/Serdes.java
- debezium-core/src/main/java/io/debezium/serde/json/JsonSerde.java
- debezium-core/src/main/java/io/debezium/serde/json/JsonSerdeConfig.java
- debezium-core/src/test/java/io/debezium/serde/SerdeTest.java
- debezium-core/src/test/resources/json/serde-unwrapped.json
- debezium-core/src/test/resources/json/serde-update.json
- debezium-core/src/test/resources/json/serde-with-schema.json
- debezium-core/src/test/resources/json/serde-without-schema.json
- documentation/modules/ROOT/nav.adoc
- documentation/modules/ROOT/pages/configuration/serdes.adoc
- pom.xml
https://issues.jboss.org/browse/DBZ-1533
> DBZ-1533 JSON payload serde

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-1659
> DBZ-1659 Parse return-only function

- pom.xml
https://issues.redhat.com/browse/DBZ-1660
> DBZ-1660 Upgrade PostgreSQL pgjdbc driver to 42.2.9

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SpecialCharsInNamesIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
- debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java
https://issues.redhat.com/browse/DBZ-824
> DBZ-824 Assert serialization of every processed record

- debezium-core/src/main/java/io/debezium/serde/DebeziumSerdes.java
- debezium-core/src/test/java/io/debezium/serde/SerdeTest.java
- documentation/modules/ROOT/pages/configuration/serdes.adoc
https://issues.redhat.com/browse/DBZ-1670
> DBZ-1670 Rename Serdes to DebeziumSerdes

- documentation/modules/ROOT/pages/modules/cdc-mysql-connector/p_enable-the-mysql-binlog-for-cdc.adoc
Doc had problems with the mysql query supplied for checking binary log status. This PR fixes it.
> Fixed Doc for checking mysql binlog status

- documentation/modules/ROOT/pages/connectors/oracle.adoc
Documents https://github.com/debezium/debezium-incubator/pull/127
https://issues.redhat.com/browse/DBZ-1552
> DBZ-1552 Decimal handling mode for Oracle docs

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
https://issues.redhat.com/browse/DBZ-1168
> DBZ-1168 Suport non-admin authSources

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.redhat.com/browse/DBZ-1684
> DBZ-1684 Create missing publication when replication slot exists

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-1699
The upstream PR https://github.com/antlr/grammars-v4/pull/1604 has also been filed for this change.
> DBZ-1699 Support MySQL CAST as JSON grammar syntax

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/ViewSelectedColumnsParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotReaderIT.java
https://issues.redhat.com/browse/DBZ-1693
> DBZ-1693 Use corrent TableId component

- debezium-core/src/main/java/io/debezium/serde/json/JsonSerde.java
- debezium-core/src/main/java/io/debezium/serde/json/JsonSerdeConfig.java
- debezium-core/src/test/java/io/debezium/serde/SerdeTest.java
- debezium-core/src/test/resources/json/serde-unknown-property.json
- documentation/modules/ROOT/pages/configuration/serdes.adoc
https://issues.redhat.com/browse/DBZ-1703
> DBZ-1703 Add option to JSON SerDes for ignoring unknown properties

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.redhat.com/browse/DBZ-1600
> DBZ-1600 Remove deprecated "slot.drop_on_stop" postgres config option

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-1685
> DBZ-1685 Document and add support for column.mask.with for PostgreSQL

- DOCUMENTATION.md
- documentation/modules/ROOT/pages/_attributes.adoc
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
In order to capture what we have learned from recent discussions about formatting and conventions in Debezium docs, I have added some contributor notes to the `DOCUMENTATION.md` file. This is still a work in progress, but I thought it would be good to get the ball rolling.
I'm not sure if this is the ideal place to put these notes. If necessary, I could add them somewhere else and create a new PR.
> Documentation contrib update

- .travis.yml
https://issues.redhat.com/browse/DBZ-1724
> DBZ-1724 Run CI tests for non-connector modules

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-1733
> DBZ-1733 TRANSACTIONAL keyword support

- documentation/antora.yml
- documentation/modules/ROOT/pages/_attributes.adoc
- documentation/modules/ROOT/pages/modules/cdc-mysql-connector/p_install-the-mysql-connector.adoc
https://issues.redhat.com/browse/DBZ-1687
This is the branch 1.1 equalvalent of https://github.com/debezium/debezium/pull/1224.
> DBZ-1687 Consolidate attributes for branch 1.1

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoMessageDecoder.java
- debezium-connector-postgres/src/main/proto/pg_logicaldec.proto
https://issues.redhat.com/browse/DBZ-1746
> DBZ-1746 Gracefully handle unknown protobuf messages

- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
https://issues.redhat.com/browse/DBZ-1748
> DBZ-1748 Mask JDBC passwords from log messages

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.redhat.com/browse/DBZ-1698
> DBZ-1698 Handle toasted unknown column values

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
https://issues.redhat.com/browse/DBZ-1158
> DBZ-1158 Add test for REPLICA IDENTITY fallback values

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/RecordMakers.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentState.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-core/src/main/java/io/debezium/converters/CloudEventsConverter.java
- debezium-core/src/main/java/io/debezium/data/Envelope.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/transforms/ByLogicalTableRouter.java
- debezium-core/src/main/java/io/debezium/transforms/SmtManager.java
https://issues.redhat.com/browse/DBZ-1751
> DBZ-1751 Centralize envelope schema naming

- documentation/modules/ROOT/pages/connectors/db2.adoc
Document the DB2 snapshot isolation modes included in debezium/debezium-incubator#135
> DBZ-1752 Document DB2 Isolation modes properly

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.redhat.com/browse/DBZ-1783
> DBZ-1783 Ignore empty transactions

- COPYRIGHT.txt
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/StreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-1766
Supersedes #1245.
> DBZ-1766 Update lastOffset to commit only after a record is committed

- debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java
- debezium-core/src/test/java/io/debezium/transforms/ExtractNewRecordStateTest.java
https://issues.redhat.com/browse/DBZ-1772
> DBZ-1772 Trimming values for add.source.fields option

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-1758
> DBZ-1758 Documentation update

- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
- documentation/modules/ROOT/pages/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
https://issues.redhat.com/browse/DBZ-1704
> DBZ-1704 Document logical name constraints

- debezium-quarkus-outbox/integration-tests/pom.xml
https://issues.redhat.com/browse/DBZ-1799
> DBZ-1799 Correct dependency management

- debezium-core/src/main/java/io/debezium/relational/history/DatabaseHistory.java
- debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java
https://issues.redhat.com/browse/DBZ-1775
> DBZ-1775 Filter out rds_monitor DML events

- debezium-core/src/main/java/io/debezium/data/Envelope.java
https://issues.redhat.com/browse/DBZ-1805
> DBZ-1805 Removing unused private method parameter

- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.redhat.com/browse/DBZ-1779
> DBZ-1779 Document topic name, fix JSON formatting

- debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/OutboxIT.java
- debezium-quarkus-outbox/runtime/src/main/resources/META-INF/quarkus-extension.yaml
Add Quarkus extension metadata and native-image test
> DBZ-1711 Add quarkus-extension.yaml and native-image test

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTaskContextTest.java
- documentation/modules/ROOT/pages/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
https://issues.redhat.com/browse/DBZ-1705
> DBZ-1705 Switch new GTID process to earliest

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-core/src/main/java/io/debezium/relational/Key.java
https://issues.redhat.com/browse/DBZ-1825
> DBZ-1825 Keep keys for non-matching table

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderIT.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- documentation/modules/ROOT/pages/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
https://issues.redhat.com/browse/DBZ-1826
> DBZ-1826 Rename error handling config field

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
Fixing false positive warning for default value
> DBZ-1826 Avoid default false warning with default value

- documentation/modules/ROOT/pages/modules/cdc-mysql-connector/c_how-the-mysql-connector-maps-data-types.adoc
https://issues.redhat.com/browse/DBZ-1800
> DBZ-1800 Correct TINYINT mapping

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerChangeTableSetIT.java
https://issues.redhat.com/browse/DBZ-1778
> DBZ-1778 Trigger migration only for change tables planned to discontinue

- documentation/modules/ROOT/nav.adoc
- documentation/modules/ROOT/pages/development/converters.adoc
- documentation/modules/ROOT/pages/development/engine.adoc
- documentation/modules/ROOT/pages/operations/embedded.adoc
Let's use this PR also for convertor docs
> Document Debezium API

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/TopicNameSanitizationIT.java
- debezium-connector-mysql/src/test/resources/ddl/topic_name_sanitization_test.sql
- debezium-core/src/main/java/io/debezium/relational/ddl/AbstractDdlParser.java
https://issues.redhat.com/browse/DBZ-1834
> DBZ-1834 Support dots in table names

- documentation/modules/ROOT/pages/assemblies/tutorial/as_starting-services.adoc
- documentation/modules/ROOT/pages/modules/tutorial/p_deleting-record-database-viewing-delete-event.adoc
- documentation/modules/ROOT/pages/modules/tutorial/p_updating-database-viewing-update-event.adoc
- documentation/modules/ROOT/pages/modules/tutorial/p_viewing-create-event.adoc
Made a couple updates to the tutorial (which shouldn't change the upstream content):
* Fixed a broken xref
* Added conditionalization to enable downstream reuse (the upstream uses watch-topic, and the downstream uses kafka-console-consumer)
> NO-JIRA: Add conditionalization to tutorial

- documentation/modules/ROOT/pages/tutorial.adoc
update tutorial to reflect current database content
> NO-JIRA: Show the actual tables from the preconfigured MySQL container (Branch 1.1)

- documentation/modules/ROOT/pages/tutorial.adoc
update tutorial to reflect current database content
> NO-JIRA: Show the actual tables from the preconfigured MySQL container (Branch 1.0)

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationMessage.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/NonStreamingWal2JsonMessageDecoder.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
Fixes for issues in https://github.com/debezium/debezium/pull/1298
>  DBZ-1840 Fix pgoutput and wal2json

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.redhat.com/browse/DBZ-1824
The fix goes against processing heartbeat logic - it has to be reconciled with it yet.
> DBZ-1824 Restart incomplete Tx for wal2json

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/FieldSelector.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/AbstractMongoConnectorIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldRenamesIT.java
https://issues.redhat.com/browse/DBZ-1848
> DBZ-1848 Skip adding rename field if source field does not exist.

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java
https://issues.redhat.com/browse/DBZ-1849
> DBZ-1849 Avoid type refresh for unchanged root type

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java
https://issues.redhat.com/browse/DBZ-1849?focusedCommentId=13991795&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13991795
> DBZ-1849 Only log message was fixed

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java
https://issues.redhat.com/browse/DBZ-1850
> DBZ-1850 Delegate signed/nonsigned converion to driver

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlMetricsIT.java
- debezium-connector-mysql/src/test/resources/ddl/connector_metrics_test.sql
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresMetricsIT.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
https://issues.redhat.com/browse/DBZ-1664
> DBZ-1664 Verify correctness of JMX metrics

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-1858
> DBZ-1858 Document PostgreSQL connector metrics

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/SnapshotChangeEventSourceMetrics.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/SnapshotProgressListener.java
- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-1856
> DBZ-1856 Deprecation process is not necessary

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresErrorHandler.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/pipeline/ErrorHandler.java
- debezium-core/src/main/java/io/debezium/util/Throwables.java
https://issues.redhat.com/browse/DBZ-1723
> DBZ-1723 Retrying upon connection loss for Postgres

- documentation/modules/ROOT/pages/integrations/outbox.adoc
https://issues.redhat.com/browse/DBZ-1804
> DBZ-1804 Clarify column type defaults for Outbox Quarkus extension

- .travis.yml
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldBlacklistIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldRenamesIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TestHelper.java
- debezium-connector-mongodb/src/test/resources/log4j.properties
https://issues.redhat.com/browse/DBZ-1867
https://issues.redhat.com/browse/DBZ-1871
> DBZ-1867 DBZ-1871 - MongoDB 3.2 test fixes & Travis CI job

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationStream.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.redhat.com/browse/DBZ-1730
> DBZ-1730 Stream from replica slot position not end of tx log

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresMetricsIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TransactionMetadataIT.java
https://issues.redhat.com/browse/DBZ-1875
> DBZ-1730 Test stabilization

- debezium-testing/debezium-testing-openshift/pom.xml
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/OpenShiftUtils.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/KafkaDeployer.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/OperatorController.java
- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/ConnectorTestBase.java
- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/resources/ConfigProperties.java
- jenkins-jobs/docker/Dockerfile.AMQ
- jenkins-jobs/job-dsl/downstream_strimzi_prepare.groovy
- jenkins-jobs/job-dsl/openshift_test.groovy
- jenkins-jobs/pipelines/downstream_prepare_pipeline.groovy
- jenkins-jobs/pipelines/openshift_pipeline.groovy
- jenkins-jobs/scripts/build-connect-image.sh
- jenkins-jobs/scripts/copy-images.sh
Two job definitions and related pipelies. 
Downstream preparation job
- Takes our internal builds a pushes them to private org in Quay
- Builds connect image on top of productised AMQ Streams and our productised artefacts and produces an image in Quay
OpenShift test Pipeline
- Able to run openshift tests for upstream and downstream
> DBZ-1817 CI job definition for OpenShift tests

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/AbstractMongoConnectorIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoMetricsIT.java
https://issues.redhat.com/browse/DBZ-1879
> DBZ-1879 Introduce JMX tests

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/AbstractColumnValue.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.redhat.com/browse/DBZ-1755
> DBZ-1755 Handle error conditions better for the Pg MONEY datatype

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-core/src/main/java/io/debezium/heartbeat/DatabaseHeartbeatImpl.java
- debezium-core/src/main/java/io/debezium/heartbeat/Heartbeat.java
- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-1815
Supersedes #1309.
@jpechane, could you check this one one? Thx!
> DBZ-1815 (Heart beat action queries)

- debezium-testing/debezium-testing-openshift/pom.xml
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/databases/DatabaseController.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/KafkaConnectController.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/OperatorController.java
- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/ConnectorTestBase.java
- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/mysql/MySqlConnectorIT.java
- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/postgresql/PostgreSqlConnectorIT.java
- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/resources/ConfigProperties.java
- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/resources/ConnectorFactories.java
Includes also improvements to modification of Strimzi operator deployment. Ideally, those would be a separate pull request, however, I needed the changes.
> [DBZ-1663] OpenShift tests for MySQL Connector restart/downtime

- documentation/modules/ROOT/pages/integrations/outbox.adoc
https://issues.redhat.com/browse/DBZ-1902
> DBZ-1902 Fix typo in Quarkus Outbox extension documentation

- documentation/modules/ROOT/pages/install.adoc
https://issues.redhat.com/browse/DBZ-1907
> DBZ-1907 Fix broken install links

- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
https://issues.redhat.com/browse/DBZ-1918
> DBZ-1918 Initialize Metronome when needed

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/StreamingWal2JsonMessageDecoder.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- jenkins-jobs/job-dsl/postgresql_matrix_test.groovy
https://issues.redhat.com/browse/DBZ-1922
> DBZ-1922 wal2_json streaming uses NOOP messages

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReaderMetrics.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlMetricsIT.java
https://issues.redhat.com/browse/DBZ-1932
> DBZ-1932 Snapshot events calculated from table stats

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
https://issues.redhat.com/browse/DBZ-1926
> DBZ-1926 Log unexpected exceptions during snapshot

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java
https://issues.redhat.com/browse/DBZ-1882
> DBZ-1882 Restarting after connection losses in SQL Server

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/OutboxEventRouterIT.java
- debezium-core/src/test/java/io/debezium/junit/SkipTestRule.java
- debezium-core/src/test/java/io/debezium/junit/SkipWhenKafkaVersion.java
- pom.xml
https://issues.redhat.com/browse/DBZ-1925
> DBZ-1925 Upgrade to Kafka 2.4.1 and CP 5.4.1

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.redhat.com/browse/DBZ-1945
> DBZ-1945 Remove deprecated connector option "initial_schema_only"

- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
- documentation/modules/ROOT/pages/modules/cdc-all-connectors/r_connector-monitoring-schema-history-metrics.adoc
- documentation/modules/ROOT/pages/modules/cdc-all-connectors/r_connector-monitoring-snapshot-metrics.adoc
- documentation/modules/ROOT/pages/modules/cdc-all-connectors/r_connector-monitoring-streaming-metrics.adoc
- documentation/modules/ROOT/pages/modules/cdc-mysql-connector/r_mysql-connector-monitoring-metrics.adoc
- documentation/modules/ROOT/pages/operations/monitoring.adoc
https://issues.redhat.com/browse/DBZ-1920
> DBZ-1920 Extract common metrics to included pages

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
- debezium-core/src/main/java/io/debezium/util/Threads.java
- debezium-core/src/test/java/io/debezium/relational/history/KafkaDatabaseHistoryTest.java
https://issues.redhat.com/browse/DBZ-1905
> DBZ-1905 Validate database history topic

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-1960
> DBZ-1960 Remove sources of busy wait

- debezium-core/src/main/java/io/debezium/transforms/Filter.java
- debezium-core/src/main/java/io/debezium/transforms/filter/Engine.java
- debezium-core/src/test/java/io/debezium/transforms/FilterTest.java
- documentation/modules/ROOT/pages/configuration/filtering.adoc
https://issues.redhat.com/browse/DBZ-1782
@jpechane, as discussed.
> DBZ-1782 Allowing any JSR 223 implementation for filtering SMT

- pom.xml
https://issues.redhat.com/browse/DBZ-1958
> DBZ-1958 MongoDB driver 3.12.3 upgrade

- debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/AdditionalJaxbMappingProducerImpl.java
https://issues.redhat.com/browse/DBZ-1966
> DBZ-1966 Fix NPE during quarkus:dev operation of Outbox Extension

- pom.xml
https://issues.redhat.com/browse/DBZ-1943
> DBZ-1943 Align jackson versions on classpath

- documentation/modules/ROOT/pages/install.adoc
- documentation/modules/ROOT/partials/assemblies/tutorial/as_viewing-change-events.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_how-the-mysql-connector-maps-data-types.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_how-the-mysql-connector-performs-database-snapshots.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_mysql-connector-events.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_configure-the-mysql-connector.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_create-a-mysql-user-for-cdc.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-monitoring-metrics.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-purges-binlog-files.adoc
... to point to large page instead of the assemblies
cc: @gunnarmorling
> DBZ-1944 updating links to mysql documentation

- documentation/modules/ROOT/pages/install.adoc
- documentation/modules/ROOT/pages/operations/logging.adoc
- documentation/modules/ROOT/pages/operations/monitoring.adoc
- documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_connector-common-issues.adoc
- documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_deploy-the-mysql-connector.adoc
- documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_overview-of-how-the-mysql-connector-works.adoc
- documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_setup-the-mysql-server.adoc
- documentation/modules/ROOT/partials/assemblies/logging/as_configuring-logging.adoc
- documentation/modules/ROOT/partials/assemblies/monitoring/as_enabling-jmx-docker.adoc
- documentation/modules/ROOT/partials/assemblies/monitoring/as_enabling-jmx-local-installations.adoc
- documentation/modules/ROOT/partials/assemblies/tutorial/as_deploying-mysql-connector.adoc
- documentation/modules/ROOT/partials/assemblies/tutorial/as_starting-services.adoc
- documentation/modules/ROOT/partials/assemblies/tutorial/as_viewing-change-events.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_how-the-mysql-connector-maps-data-types.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_how-the-mysql-connector-performs-database-snapshots.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_mysql-connector-events.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_configure-the-mysql-connector.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_create-a-mysql-user-for-cdc.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-monitoring-metrics.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-purges-binlog-files.adoc
plus fix-up for extra colon in include
cc @gunnarmorling
> DBZ-1944 updating links to mysql documentation to point to large page

- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
- documentation/modules/ROOT/pages/install.adoc
- documentation/modules/ROOT/pages/operations/logging.adoc
- documentation/modules/ROOT/pages/operations/monitoring.adoc
- documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_connector-common-issues.adoc
- documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_deploy-the-mysql-connector.adoc
- documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_overview-of-how-the-mysql-connector-works.adoc
- documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_setup-the-mysql-server.adoc
- documentation/modules/ROOT/partials/assemblies/logging/as_configuring-logging.adoc
- documentation/modules/ROOT/partials/assemblies/monitoring/as_enabling-jmx-docker.adoc
- documentation/modules/ROOT/partials/assemblies/monitoring/as_enabling-jmx-local-installations.adoc
- documentation/modules/ROOT/partials/assemblies/tutorial/as_deploying-mysql-connector.adoc
- documentation/modules/ROOT/partials/assemblies/tutorial/as_starting-services.adoc
- documentation/modules/ROOT/partials/assemblies/tutorial/as_viewing-change-events.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_how-the-mysql-connector-maps-data-types.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_how-the-mysql-connector-performs-database-snapshots.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_mysql-connector-events.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_configure-the-mysql-connector.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_create-a-mysql-user-for-cdc.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-monitoring-metrics.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-purges-binlog-files.adoc
This also removes a surplus colon and fixed on anchor link
cc: @gunnarmorling
> DBZ-1944 updating links to mysql documentation in 1.0

- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-monitoring-metrics.adoc
https://issues.redhat.com/browse/DBZ-1947
> DBZ-1947 Excluding obsolete metrics from downstream docs

- documentation/antora.yml
- documentation/modules/ROOT/partials/modules/monitoring/c_metrics-monitoring-connectors.adoc
- documentation/modules/ROOT/partials/modules/tutorial/p_registering-connector-monitor-inventory-database.adoc
https://issues.redhat.com/browse/DBZ-1983
> DBZ-1983 Fixing broken link

- debezium-quarkus-outbox/runtime/src/main/resources/META-INF/quarkus-extension.yaml
https://issues.redhat.com/browse/DBZ-1991
> DBZ-1991 Update Outbox Quarkus extension YAML

- debezium-core/src/main/java/io/debezium/transforms/ByLogicalTableRouter.java
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
https://issues.redhat.com/browse/DBZ-2006
> DBZ-2006 Misc. fixes to MongoDB connector docs

- COPYRIGHT.txt
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
https://issues.redhat.com/browse/DBZ-1895
Supersedes #1360.
> DBZ-1895 (Skipped ops for MySQL)

- debezium-core/src/main/java/io/debezium/transforms/filter/GraalJsEngine.java
- debezium-core/src/main/java/io/debezium/transforms/filter/Jsr223Engine.java
- debezium-core/src/test/java/io/debezium/transforms/FilterTest.java
- documentation/modules/ROOT/pages/configuration/filtering.adoc
https://issues.redhat.com/browse/DBZ-1993
> DBZ-1993 Allowing for property-style access in filter SMT with JS

- debezium-core/src/main/java/io/debezium/data/Envelope.java
- pom.xml
https://issues.redhat.com/browse/DBZ-2007
> DBZ-2007 Upgrade Formatter and Impsort plugins

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java
https://issues.redhat.com/browse/DBZ-1923
> DBZ-1923 Detect lost database history

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/config/ConfigDefinition.java
- debezium-core/src/main/java/io/debezium/config/ConfigDefinitionEditor.java
- debezium-core/src/main/java/io/debezium/config/Field.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
https://issues.redhat.com/browse/DBZ-1750
@jpechane, this supersedes your earlier PR #1438. Note I've amended your commit which caused the test failure around validation of Kafka history topic config options. Also refined the commit for making things immutable.
> DBZ-1750 Centralising config options

- debezium-core/src/main/java/io/debezium/transforms/ContentBasedRouter.java
- debezium-core/src/main/java/io/debezium/transforms/Filter.java
- debezium-core/src/main/java/io/debezium/transforms/ScriptingTransformation.java
- debezium-core/src/main/java/io/debezium/transforms/scripting/Engine.java
- debezium-core/src/main/java/io/debezium/transforms/scripting/GraalJsEngine.java
- debezium-core/src/main/java/io/debezium/transforms/scripting/Jsr223Engine.java
- debezium-core/src/test/java/io/debezium/transforms/RouterTest.java
- documentation/modules/ROOT/nav.adoc
- documentation/modules/ROOT/pages/configuration/content-based-routing.adoc
- documentation/modules/ROOT/pages/configuration/filtering.adoc
https://issues.redhat.com/browse/DBZ-2000
> DBZ-2000 Content based router SMT

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
https://issues.redhat.com/browse/DBZ-2025
> DBZ-2025 Reduce capture job poll interval

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-2030
So the changes mostly use Awaitility as a means to wait until database state is properly set before it allows the main test thread to proceed to the next step and retrying operations if they fail up to a maximum of 60 seconds.  
One additional change is the introduction of the following SQL call:
`ALTER DATABASE testDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;`
I found that in the event there are other operations currently running against the testDB, this forces those steps to terminate immediately allowing the drop to succeed.  
Hopefully these all combined help stabilize the test suite going forward.
> DBZ-2030 Use Awaitility to manage database drops

- COPYRIGHT.txt
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoColumnValue.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-core/src/test/java/io/debezium/data/VerifyRecord.java
https://issues.redhat.com/browse/DBZ-1969
> DBZ-1969 Add support for enum arrays

- documentation/modules/ROOT/pages/connectors/cassandra.adoc
- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
https://issues.redhat.com/browse/DBZ-1933
> DBZ-1933 Add anchors to connector properties

- pom.xml
- support/checkstyle/pom.xml
https://issues.redhat.com/browse/DBZ-2039
> DBZ-2039 Upgrade to jboss-parent 36 and checkstyle 8.32

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java
This changes the enum query to returns results like this:
```
=# SELECT t.enumtypid as id, array_agg(t.enumlabel) as enum_values FROM pg_catalog.pg_enum t GROUP BY id;
id   |  enum_values
-------+--------------
25022 | {FOO,BAR}
```
The results of this query get joined into the existing query for type information. This means that we now have all of the information needed about Postgres types from a single query.
https://issues.redhat.com/browse/DBZ-2044
> DBZ-2044 Load Postgres enum values with a single query instead of N queries

- .travis.yml
https://issues.redhat.com/browse/DBZ-2043
> DBZ-2043 Reduce log verbosity

- documentation/modules/ROOT/pages/connectors/mongodb.adoc
https://issues.redhat.com/browse/DBZ-1901
> DBZ-1901 Reword MongoDB documentation to use snapshot/streaming semantics

- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_configure-the-mysql-connector.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_install-the-mysql-connector.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
- documentation/modules/ROOT/partials/modules/monitoring/c_metrics-monitoring-connectors.adoc
https://issues.redhat.com/browse/DBZ-2011
> Backport of DBZ-2011 for 1.0

- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_configure-the-mysql-connector.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_install-the-mysql-connector.adoc
- documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
- documentation/modules/ROOT/partials/modules/monitoring/c_metrics-monitoring-connectors.adoc
https://issues.redhat.com/browse/DBZ-2011
> Backport of DBZ-2011 for 1.1

- debezium-core/src/main/java/io/debezium/transforms/SmtManager.java
https://issues.redhat.com/browse/DBZ-2036
> DBZ-2036 Change logging from warn to debug

- pom.xml
https://issues.redhat.com/browse/DBZ-1981
> DBZ-1981 Upgrade to Kafka 2.5.0

- pom.xml
https://issues.redhat.com/browse/DBZ-1975
> DBZ-1975 Upgrade to Quarkus 1.4.1.Final

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/OutboxEventRouterIT.java
- debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java
- debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterConfigDefinition.java
- debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
- documentation/modules/ROOT/pages/configuration/outbox-event-router.adoc
https://issues.redhat.com/browse/DBZ-2014
> DBZ-2014 Do not include outbox eventType field by default

- debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
https://issues.redhat.com/browse/DBZ-2054
> DBZ-2054 Fix compatibility regression with Kafka 1.x

- debezium-core/src/main/java/io/debezium/transforms/ByLogicalTableRouter.java
- debezium-core/src/test/java/io/debezium/transforms/ByLogicalTableRouterTest.java
- documentation/modules/ROOT/pages/configuration/topic-routing.adoc
https://issues.redhat.com/browse/DBZ-2034
> DBZ-2034 Make ByLogicalTableRouter SMT unique key enforcement optional

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DebeziumEngineIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TransactionMetadataIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TransactionMetadataIT.java
- debezium-core/src/test/java/io/debezium/junit/SkipWhenKafkaVersion.java
https://issues.redhat.com/browse/DBZ-2068
> DBZ-2068 Skip tests incompatible with Kafka 1.x

- documentation/modules/ROOT/pages/development/engine.adoc
https://issues.redhat.com/projects/DBZ/issues/DBZ-2073
> DBZ-2073 Update DebeziumEngine.ChangeConsumer api in docs

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/ColumnDefinitionParserListener.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateTableParserListener.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/DefaultValueParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-core/src/main/java/io/debezium/relational/NoOpTableEditorImpl.java
- debezium-core/src/main/java/io/debezium/relational/TableEditor.java
- debezium-core/src/main/java/io/debezium/relational/TableEditorImpl.java
https://issues.redhat.com/browse/DBZ-2061
> DBZ-2061 Handle change of default value

- debezium-core/src/main/java/io/debezium/transforms/ScriptingTransformation.java
- debezium-core/src/test/java/io/debezium/transforms/FilterTest.java
- debezium-core/src/test/java/io/debezium/transforms/RouterTest.java
- documentation/modules/ROOT/pages/configuration/content-based-routing.adoc
- documentation/modules/ROOT/pages/configuration/filtering.adoc
https://issues.redhat.com/browse/DBZ-2024
> DBZ-2024 Adding topic.regex option to routing and filtering SMTs

- debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-drivers.xml
- debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution.xml
https://issues.redhat.com/browse/DBZ-2076
> DBZ-2076 Remove Jackson transitive dependencies

- jenkins-jobs/job-dsl/mysql_matrix_test.groovy
https://issues.redhat.com/browse/DBZ-2041
I've already manually updated the Jenkins CI job with 8.0.20 and it passed, see builds 241+.
> DBZ-2041 Test using MySQL 8.0.20; up from 8.0.13.

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql
https://issues.redhat.com/browse/DBZ-2080
> DBZ-2080 Support named PKs in ALTER TABLE

- debezium-core/src/main/java/io/debezium/transforms/scripting/GraalJsEngine.java
- debezium-core/src/main/java/io/debezium/transforms/scripting/Jsr223Engine.java
- debezium-core/src/main/java/io/debezium/transforms/scripting/RecordHeader.java
- debezium-core/src/test/java/io/debezium/transforms/FilterTest.java
- documentation/modules/ROOT/pages/configuration/content-based-routing.adoc
- documentation/modules/ROOT/pages/configuration/filtering.adoc
https://issues.redhat.com/browse/DBZ-2074
> DBZ-2074 Expose topic and headers in scripting SMTs

- debezium-connector-mongodb/pom.xml
- debezium-connector-mysql/pom.xml
- debezium-connector-postgres/pom.xml
- debezium-connector-sqlserver/pom.xml
- debezium-server/pom.xml
https://issues.redhat.com/browse/DBZ-2088
> DBZ-2088 Use POSIX tar

- COPYRIGHT.txt
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceTimestampMode.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SourceTimestampModeTest.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.redhat.com/browse/DBZ-1988
> DBZ-1988: Skip LSN timestamp query when using Oracle CDC jobs

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
https://issues.redhat.com/browse/DBZ-2090
> DBZ-2090 Remove unused sourceInfo variable

- debezium-core/src/main/java/io/debezium/metrics/Metrics.java
https://issues.redhat.com/browse/DBZ-2089
> DBZ-2089 JMX no longer mandatory

- debezium-server/src/main/java/io/debezium/server/Any.java
- debezium-server/src/main/java/io/debezium/server/DebeziumServer.java
https://issues.redhat.com/browse/DBZ-2104
> DBZ-2104 Remove typecasting hack

- debezium-microbenchmark/src/main/java/io/debezium/performance/core/SmtOverheadPerf.java
https://issues.redhat.com/browse/DBZ-1929
```
SmtOverheadPerf.base         thrpt    3  3040.082 ± 205.224  ops/us
SmtOverheadPerf.noop         thrpt    3  1028.323 ±  57.565  ops/us
SmtOverheadPerf.newRecord    thrpt    3   306.763 ±  57.972  ops/us
```
> DBZ-1929 Baseline of SMT impact

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
https://issues.redhat.com/browse/DBZ-1657
> DBZ-1657 Remove duplicate option definitions

- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.redhat.com/browse/DBZ-1312
> DBZ-1312 Change whitelist format to schema.table ids

- pom.xml
https://issues.redhat.com/browse/DBZ-2119
> DBZ-2119 Upgrade to Quarkus 1.5.0.Final

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-core/src/main/java/io/debezium/relational/Key.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseSchema.java
- debezium-core/src/main/java/io/debezium/relational/TableId.java
- debezium-core/src/main/java/io/debezium/relational/mapping/ColumnMappers.java
- debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java
- debezium-core/src/test/java/io/debezium/relational/mapping/ColumnMappersTest.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.redhat.com/browse/DBZ-1312
> DBZ-1312 Omit constatnt db name in column and key mappers

- DOCUMENTATION.md
- Remove non-existing anchor links
- Fix typos
> Fix documentation typos

- jenkins-jobs/prod-release.yaml
- jenkins-jobs/scripts/prod-release-pipeline.groovy
https://issues.redhat.com/browse/DBZ-2137
> DBZ-2137 Product artifacts also from incubator repo

- debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
https://issues.redhat.com/browse/DBZ-2124
> DBZ-2124 Do not call markBatchFinished on failure

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-2130
> DBZ-2130 CHARACTER keyword used also as a type

- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
- documentation/modules/ROOT/pages/integrations/cloudevents.adoc
https://issues.redhat.com/browse/DBZ-2020
https://issues.redhat.com/browse/DBZ-1956
> Miscellaneous documentation changes

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
Fixes recent test failures introduced in MySQL module.
> DBZ-2130 Avoid ambiguity between type and charset keyword

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
https://issues.redhat.com/browse/DBZ-2140
> DBZ-2140 Handle drop default value

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-2143
https://issues.redhat.com/browse/DBZ-2142
Best review when ignoring whitelist changes
> DBZ-2143 Rebase grammar on the latest upstream

- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
> DBZ-1557: Correct spelling error.

- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
- debezium-core/src/test/java/io/debezium/relational/history/KafkaDatabaseHistoryTest.java
https://issues.redhat.com/browse/DBZ-2144
> DBZ-2140 Internal configs must not be validated

- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/DebeziumContainerTest.java
https://issues.redhat.com/browse/DBZ-2033
> DBZ-2033 Making integration test more resilient

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationConnection.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/projects/DBZ/issues/DBZ-1813
@gunnarmorling I havn't implemented the tests yet, but wanted to run this by you first before embarking on that. If you like this implementation I can work on adding in some unit tests that show the different modes.
> WIP initial commit of changes, next step is unit tests

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SchemaHistoryTopicIT.java
https://issues.redhat.com/browse/DBZ-2060
https://issues.redhat.com/browse/DBZ-2157
> DBZ-2060 DBZ-2157 Fix intermittent test failures

- pom.xml
https://issues.redhat.com/browse/DBZ-2160
> [DBZ-2160][Increment mysql binlog java connector version]

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/dml_select.sql
https://issues.redhat.com/browse/DBZ-2153
> DBZ-2153: support cast as int

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-2154
> DBZ-2154: utc_timestamp without parentheses

- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
https://issues.redhat.com/browse/DBZ-2150
@Naros, @jpechane, could either of you review and apply? Thx!
> DBZ-2150 Awaiting coordinator shutdown in embedded engine

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/ReplicationConnectionIT.java
https://issues.redhat.com/browse/DBZ-2156
@jpechane small improvement as per today's thread on the ML.
> DBZ-2156 More meaningful exception in case of replication slot conflict

- debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
https://issues.redhat.com/browse/DBZ-2152
This fixes the test failure introduced by the initial changes for DBZ-2152.
> DBZ-2152 Fix test failure

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetrics.java
https://issues.jboss.org/browse/DBZ-1989
> DBZ-1989 Avoid returning distorted (Milli)SecondsBehindSource values

- debezium-api/pom.xml
- debezium-api/src/chore/intentional-api-changes.xml
- debezium-connector-postgres/pom.xml
- pom.xml
- support/revapi/pom.xml
- support/revapi/src/main/resources/revapi/debezium-api-changes.xml
- support/revapi/src/main/resources/revapi/revapi-configuration.xml
https://issues.redhat.com/browse/DBZ-2159
Supersedes #1566.
> DBZ-2159 (RevApi)

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbChangeRecordEmitter.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
- debezium-connector-mongodb/src/test/resources/fieldnamedop.json
https://issues.redhat.com/browse/DBZ-2116
> DBZ-2116 Snapshot fix for documents with a field named "op"

- debezium-server/debezium-server-core/pom.xml
- debezium-server/debezium-server-kinesis/pom.xml
- debezium-server/debezium-server-pubsub/pom.xml
- debezium-server/debezium-server-pulsar/pom.xml
https://issues.redhat.com/browse/DBZ-2192
> DBZ-2192 Add Jandex files

- documentation/modules/ROOT/pages/operations/debezium-server.adoc
https://issues.redhat.com/browse/DBZ-2198
> DBZ-2198 Document http port and database history

- debezium-server/debezium-server-distro/src/main/resources/assemblies/server-distribution.xml
https://issues.redhat.com/browse/DBZ-2201
> DBZ-2201 Keep Pulsar client dependencies

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
https://issues.redhat.com/browse/DBZ-2177
> DBZ-2177 Fix inconsistent test failure

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
https://issues.redhat.com/browse/DBZ-2120
> DBZ-2120 move check null logic in query to java code

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-1916
> DBZ-1916 Add tests for datatype.propagate.source.type

- documentation/modules/ROOT/pages/operations/debezium-server.adoc
https://issues.redhat.com/browse/DBZ-2163
> DBZ-2163 Link to topic mapper example

- debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
https://issues.redhat.com/browse/DBZ-2199
> DBZ-2199 Avoid IndexOutOfBoundsException when no task config is available

- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Also adding connector property to MongoDB connector
https://issues.redhat.com/browse/DBZ-2069
@Naros, can you check out this one and also backport to 1.1? Thanks!
> DBZ-2069 Removing obsolete incubating note;

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
https://issues.redhat.com/browse/DBZ-2207
> DBZ-2207 Intermittnet test failure

- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java
- documentation/antora.yml
- documentation/modules/ROOT/pages/configuration/avro.adoc
https://issues.redhat.com/browse/DBZ-2206
> DBZ-2206 Upgrade apicurio to 1.2.2.Final

- documentation/modules/ROOT/pages/architecture.adoc
The title says it all. This is ready to merge unless you notice something that needs to be fixed. 
Please backport this PR to 1.1.
Thanks!
> DBZ-2029 Edited the architecture description

- documentation/antora.yml
- documentation/modules/ROOT/pages/operations/debezium-server.adoc
https://issues.redhat.com/browse/DBZ-2212
> DBZ-2212 Fix Debezium Server download link

- debezium-server/debezium-server-pulsar/docker/conf/bkenv.sh
- debezium-server/debezium-server-pulsar/docker/conf/bookkeeper.conf
- debezium-server/debezium-server-pulsar/docker/conf/broker.conf
- debezium-server/debezium-server-pulsar/docker/conf/client.conf
- debezium-server/debezium-server-pulsar/docker/conf/discovery.conf
- debezium-server/debezium-server-pulsar/docker/conf/filesystem_offload_core_site.xml
- debezium-server/debezium-server-pulsar/docker/conf/functions-logging/console_logging_config.ini
- debezium-server/debezium-server-pulsar/docker/conf/functions-logging/logging_config.ini
- debezium-server/debezium-server-pulsar/docker/conf/functions_worker.yml
- debezium-server/debezium-server-pulsar/docker/conf/global_zookeeper.conf
- debezium-server/debezium-server-pulsar/docker/conf/log4j2-scripts/filter.js
- debezium-server/debezium-server-pulsar/docker/conf/log4j2.yaml
- debezium-server/debezium-server-pulsar/docker/conf/presto/catalog/pulsar.properties
- debezium-server/debezium-server-pulsar/docker/conf/presto/config.properties
- debezium-server/debezium-server-pulsar/docker/conf/presto/jvm.config
- debezium-server/debezium-server-pulsar/docker/conf/presto/log.properties
- debezium-server/debezium-server-pulsar/docker/conf/proxy.conf
- debezium-server/debezium-server-pulsar/docker/conf/pulsar_env.sh
- debezium-server/debezium-server-pulsar/docker/conf/pulsar_tools_env.sh
- debezium-server/debezium-server-pulsar/docker/conf/schema_example.conf
- debezium-server/debezium-server-pulsar/docker/conf/standalone.conf
- debezium-server/debezium-server-pulsar/docker/conf/websocket.conf
- debezium-server/debezium-server-pulsar/docker/conf/zookeeper.conf
- debezium-server/debezium-server-pulsar/pom.xml
https://issues.redhat.com/browse/DBZ-2210
> DBZ-2210 Increase Pulsar timeouts

- debezium-testing/debezium-testing-openshift/pom.xml
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/ConfigProperties.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/HttpUtils.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/OpenShiftUtils.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/WaitConditions.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/databases/DatabaseController.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/databases/SqlDatabaseClient.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/databases/mongodb/MongoController.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/databases/mongodb/MongoDatabaseClient.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/databases/sqlserver/SqlServerController.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/KafkaConnectController.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/KafkaDeployer.java
- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/OperatorController.java
- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/ConnectorTestBase.java
- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/mongodb/MongoConnectorIT.java
- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/mysql/MySqlConnectorIT.java
- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/postgresql/PostgreSqlConnectorIT.java
- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/resources/ConnectorFactories.java
- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/sqlserver/SqlServerConnectorIT.java
- jenkins-jobs/job-dsl/openshift_test.groovy
- jenkins-jobs/pipelines/openshift_pipeline.groovy
Adding the ability to scale wait time in an attempt to improve test-suite stability
> DBZ-2194 Scalable wait times in OpenShift tests

- documentation/modules/ROOT/pages/connectors/db2.adoc
https://issues.redhat.com/browse/DBZ-1835
Hey @SeanRooooney, would you mind taking a quick look at this one? I've removed the part in braces which I think caused the confusion and pulled up the sentences on licensing. Thanks!
> DBZ-1835 Licensing clarification for Db2 connector

- pom.xml
https://issues.redhat.com/browse/DBZ-2192
@jpechane Minor fix to increase fidelity of the build. Should go into 1.2.0.CR2.
> DBZ-2192 Using fixed version of Jandex Maven plug-in

- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
https://issues.redhat.com/browse/DBZ-2228
> DBZ-2228 Using unique names for admin clients

- debezium-embedded/src/test/java/io/debezium/connector/simple/SimpleSourceConnectorOutputTest.java
https://issues.redhat.com/browse/DBZ-2241
> DBZ-2241 Reduce wait time for engine thread interrupt

- debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/ConnectorTestBase.java
- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java
- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/DebeziumContainerTest.java
https://issues.redhat.com/browse/DBZ-2240
> DBZ-2240 Use 1.1 compatible API in tests

- documentation/modules/ROOT/pages/connectors/cassandra.adoc
Updated doc for Cassandra Connector about the issue in DBZ-2117
> [DBZ-2117] Update doc for Cassandra Connector

- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Please merge and backport to 1.1. 
Thanks!
> DBZ-1956 This conditionalizes "Schema Change Topic" to be upstream only

- documentation/modules/ROOT/pages/configuration/event-flattening.adoc
After merging, please backport this to 1.1.
> DBZ-2021 Updates to event flattening SMT per Chris's review

- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/converters/CloudEventsConverter.java
- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java
https://issues.redhat.com/browse/DBZ-2250
> DBZ-2250 Allowing to use CloudEventsConverter with Avro via Apicurio;

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
https://issues.redhat.com/browse/DBZ-2230
> DBZ-2230 Fix intermittent CI test failure - Postgres

- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Please backport this update to 1.1. Thanks!
> DBZ-1956 Two updates to doc for SQL Server connector per Gunnar

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderIT.java
https://issues.redhat.com/browse/DBZ-2262
> DBZ-2261 Take the full filter count into assert

- documentation/modules/ROOT/pages/configuration/event-flattening.adoc
Please merge and backport to 1.1.
Thanks!
> DBZ-1956 Removed link to upstream code

- documentation/modules/ROOT/pages/connectors/mongodb.adoc
Please merge and backport to 1.1. Thanks!
> DBZ-1956 Removed Kafka .10 note, and link to a blog post

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
https://issues.redhat.com/browse/DBZ-2261
> DBZ-2261 Prolong waiting for tx to change

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SchemaHistoryTopicIT.java
https://issues.redhat.com/browse/DBZ-2211
> DBZ-2211 Harden test against potential extra schema event

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/ColumnDefinitionParserListener.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/DefaultValueParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
https://issues.redhat.com/browse/DBZ-2267
> DBZ-2267 Optionality ignored while converting default value

- debezium-core/pom.xml
- debezium-core/src/test/java/io/debezium/transforms/RouterTest.java
- documentation/modules/ROOT/pages/configuration/content-based-routing.adoc
- documentation/modules/ROOT/pages/configuration/filtering.adoc
- pom.xml
https://issues.redhat.com/browse/DBZ-2255
> DBZ-2255 Document JSON parsing in groovy-based SMTs

- jenkins-jobs/job-dsl/postgresql_matrix_test.groovy
> DBZ-2279 Running correct maven module for PostgreSQL test matrix

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
https://issues.redhat.com/browse/DBZ-2278
> DBZ-2278 Resolve concurrent access to the thread map

- .github/workflows/formatting-check.yml
- .github/workflows/sanity-check.yml
https://issues.redhat.com/browse/DBZ-2287
> DBZ-2287 Adding formatting check GitHub Action

- .travis.yml
- debezium-quarkus-outbox/runtime/pom.xml
Also making sure debezium-api is built as a predecessor on CI
https://issues.redhat.com/browse/DBZ-2276
> DBZ-2276 Minimizing dependencies for outbox extension;

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
https://issues.redhat.com/browse/DBZ-2301
> DBZ-2301 Hide internal config fields

- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java
https://issues.redhat.com/browse/DBZ-2256
> DBZ-2256 Using upstream image for Apicurio testing

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
https://issues.redhat.com/browse/DBZ-2220
> DBZ-2220 Fix test failure - SqlServerConnectorIT#verifyOffsets

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.redhat.com/browse/DBZ-2271
> DBZ-2271 Fix test failure - RecordsStreamProducerIT#testEmptyChangesProducesHeartbeat

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerChangeTableSetIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-2231
> DBZ-2231 Fix test failure - SqlServerChangeTableSetIT#readHistoryAfterRestart

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.redhat.com/browse/DBZ-2319
> DBZ-2319 Fix test failure - PostgresConnectorIT#shouldOutputRecordsInCloudEventsFormat

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldRenamesIT.java
https://issues.redhat.com/browse/DBZ-2286
> DBZ-2286 Fix test slowness with FieldRenamesIT

- pom.xml
https://issues.redhat.com/browse/DBZ-2317
> DBZ-2317 PostgeSQL driver upgrade

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
https://issues.redhat.com/browse/DBZ-2325
> DBZ-2325 Fix test failure - SqlServerConnectorIT#readOnlyApplicationIntent

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlSchemaTest.java
- debezium-connector-mysql/src/test/resources/ddl/mysql-decimal-issue.ddl
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
Allow single dimension DECIMAL in CAST
https://issues.redhat.com/browse/DBZ-2305
> DBZ-2305 Allow single dimension DECIMAL in CAST

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
After merging, please backport this to 1.1 and 1.2.   Thanks!
> DBZ-2333 Replaces a broken link with a correct link to doc for Kafka log compaction

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
https://issues.redhat.com/browse/DBZ-2331
> DBZ-2331 Fix test failure - SnapshotIT#takeSnapshotWithOldStructAndStartStreaming

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
- debezium-core/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
See https://issues.redhat.com/browse/DBZ-2307 / https://gitter.im/debezium/user?at=5efdf769c3362026a90a6618. 
@Naros @gunnarmorling Let's try again with a PR, this supersedes https://github.com/debezium/debezium/pull/1674.
> DBZ-2307 - Improve logging when primary keys are missing

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
fixes https://issues.redhat.com/browse/DBZ-2318
> DBZ-2318 add column check constraints and JSON validation check constraints to debezium-ddl-parser ANTLR v4 MySQL grammar

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/ChangeTableResultSet.java
https://issues.redhat.com/browse/DBZ-2329
> DBZ-2329 Fix for: Change events lost when connnector is restarted while processing transaction with PK update

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
https://issues.redhat.com/browse/DBZ-2373
> DBZ-2373 Azure product name breaks version check

- jenkins-jobs/scripts/release-pipeline.groovy
Depends on https://github.com/debezium/docker-images/pull/176
> DBZ-2147 Release process for Server image

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
This is an initial pass at https://issues.redhat.com/browse/DBZ-2379.
> DBZ-2379 SnapshodeMode.INITIAL_ONLY support

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/Filters.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/FiltersTest.java
https://issues.redhat.com/browse/DBZ-1939
Supersedes https://github.com/debezium/debezium/pull/1664.
> DBZ-1939 Ignoring AWS built-in tables

- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.redhat.com/browse/DBZ-2362
> DBZ-2362 add configurable restart wait time and connection retries

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
Updated the docs to include guidance for [Azure Database for PostgreSQL](https://docs.microsoft.com/en-us/azure/postgresql/)
> DBZ-2394 Added Azure PostgreSQL guidance

- debezium-connector-mysql/pom.xml
- pom.xml
https://issues.redhat.com/browse/DBZ-2173
> DBZ-2173 Upgrade MySQL binlog client 0.23.1

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDecimalIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-2332
> DBZ-2332 Fix test failures with Kafka 1.x CI

- debezium-api/src/main/java/io/debezium/engine/DebeziumEngine.java
- debezium-server/debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java
- debezium-server/debezium-server-pubsub/src/main/java/io/debezium/server/pubsub/PubSubChangeConsumer.java
https://issues.redhat.com/browse/DBZ-2277
> DBZ-2277 Disable tombstones when using Google PubSub sink

- CHANGELOG.md
- COPYRIGHT.txt
- documentation/antora.yml
- jenkins-jobs/scripts/config/Aliases.txt
> Prep 1.3.0.alpha1

- debezium-core/src/test/java/io/debezium/kafka/KafkaServer.java
- pom.xml
https://issues.redhat.com/browse/DBZ-2411
> DBZ-2411 Upgrade to Kafka 2.6.0

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql
https://mysqlserverteam.com/mysql-8-0-invisible-indexes/
> DBZ-2425 Added MySql8 visible/invisible index support

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
https://issues.redhat.com/projects/DBZ/issues/DBZ-2423
@jpechane Another small fall-out of the PoC work. Not so bad actually in terms of capturing these little issues here and there :)
> DBZ-2423 Applying port defaults

- documentation/modules/ROOT/pages/operations/openshift.adoc
https://issues.redhat.com/browse/DBZ-1908
@jcechace 
I messed up the previous PR, https://github.com/debezium/debezium/pull/1706. 
So I closed it. 
This is a new PR with the same updates and also I removed references to minishift. I also removed the reference to the example that uses minishift. 
This is still missing a Dockerfile. I don't know what the content of the Dockerfile should be.
> DBZ-1908 Replacement PR, update doc for installing Debezium on OpenShift

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSchemaChangeEventEmitter.java
- debezium-core/src/main/java/io/debezium/transforms/ByLogicalTableRouter.java
- debezium-core/src/test/java/io/debezium/transforms/ByLogicalTableRouterTest.java
https://issues.redhat.com/projects/DBZ/issues/DBZ-2412
@rk3rn3r, can you review + merge this one? Best reviewed commit by commit. Thx!
> DBZ-2412 Avoiding NPE in logical router

- debezium-core/src/main/java/io/debezium/metrics/Metrics.java
https://issues.redhat.com/browse/DBZ-2427
@Naros saw you where involved with this, can you review and merge? Thx!
> DBZ-2427 Logging inability to unregister metrics MBean as WARN

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceInfo.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSourceInfoStructMaker.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SchemaHistoryTopicIT.java
- debezium-core/src/main/java/io/debezium/connector/AbstractSourceInfoStructMaker.java
https://issues.redhat.com/browse/DBZ-2303
> DBZ-2303 Set source when new table detected

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/LegacyV1PostgresSourceInfoStructMaker.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresOffsetContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSourceInfoStructMaker.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/AbstractMessageDecoder.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/Lsn.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/MessageDecoder.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationStream.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ServerInfo.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/WalPositionLocator.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/spi/OffsetState.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/spi/SlotCreationResult.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/spi/SlotState.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresConnectionIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/ReplicationConnectionIT.java
https://issues.redhat.com/browse/DBZ-2338
https://issues.redhat.com/browse/DBZ-2200
https://issues.redhat.com/browse/DBZ-2397
> DBZ-2338 Base WAL position detection on commit LSNs

- debezium-quarkus-outbox/deployment/pom.xml
- debezium-quarkus-outbox/pom.xml
- debezium-server/pom.xml
- pom.xml
https://issues.redhat.com/browse/DBZ-2454
> DBZ-2454 Upgrade to Quarkus 1.7.1.Final

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldRenamesIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TestHelper.java
https://issues.redhat.com/browse/DBZ-2464
> DBZ-2464 Fix intermittent failures with FieldRenamesIT

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
https://issues.redhat.com/browse/DBZ-2429
> DBZ-2429 Clarify Field descriptions for include/exclude

- debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/OpenShiftUtils.java
> DBZ-2407 Service creation util method for OCP tests

- jenkins-jobs/scripts/release-pipeline.groovy
https://issues.redhat.com/browse/DBZ-2467
> DBZ-2467 Bypass Java SSL cert issues

- pom.xml
https://issues.redhat.com/browse/DBZ-2281
> DBZ-2281 Enforce Maven 3.6.3

- .github/workflows/sanity-check.yml
https://issues.redhat.com/browse/DBZ-2479
> DBZ-2479 Diff against base branch

- documentation/modules/ROOT/pages/connectors/cassandra.adoc
- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
:warning: Must only be merged AFTER https://github.com/debezium/debezium-incubator/pull/188
Docs PR for incubator connectors (include/exclude lists) https://issues.redhat.com/browse/DBZ-2462
> DBZ-2462 avoid divisive language in incubator docs

- documentation/modules/ROOT/pages/connectors/oracle.adoc
Small update to DBZ-137 to add information about how to toggle between XStreams and Log Miner.
> DBZ-137 Add doc section about database connection adapter

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentState.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTestIT.java
- debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java
- debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordStateConfigDefinition.java
- debezium-core/src/test/java/io/debezium/transforms/ExtractNewRecordStateTest.java
- documentation/modules/ROOT/pages/configuration/event-flattening.adoc
- documentation/modules/ROOT/pages/configuration/mongodb-event-flattening.adoc
DBZ-2504: Added support for field and header prefix.
> Add support for field and header prefix
