debezium/debezium

debezium-connector-mysql/NOTES.md, debezium-connector-mysql/README.md, debezium-connector-mysql/pom.xml, debezium-connector-mysql/src/test/docker/alt-server/mysql.cnf, pom.xml
Refactored the profiles in the `debezium-connector-mysql` module so that any of the normal Maven commands can be used with the usual MySQL Docker image or, when the `-Palt-mysql` profile is specified, an alternative MySQL Docker image.
This same pattern should be able to be used by other modules that use Docker.
=> DBZ-14 Corrected the 'alt-mysql' Maven profile

debezium-connector-mysql/pom.xml, debezium-core/src/main/java/io/debezium/document/Value.java, debezium-core/src/main/java/io/debezium/relational/ddl/DdlParser.java, debezium-core/src/test/java/io/debezium/kafka/ZookeeperServer.java, pom.xml
Modified the 'docs' profile to build and attach JavaDoc JARs for each module's source and test source artifacts. The profile will be automatically used when releasing. 
Also made minor changes to the code to eliminate several JavaDoc warnings.
=> DBZ-13 Changed Maven build to attach JavaDoc JARs to each module

debezium-assembly-descriptors/pom.xml, debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution.xml, debezium-connector-mysql/pom.xml, debezium-connector-postgres/pom.xml, debezium-core/pom.xml, debezium-embedded/pom.xml, debezium-kafka-connect/pom.xml, pom.xml
The MySQL connector module now creates during the `assembly` profile two distribution files, `debezium-connector-mysql-<version>-plugin.tar.gz` and `debezium-connector-mysql-<version>-plugin.zip`. Either of these artifacts can be used to add the necessary JAR files for the module into a Kafka Connect service.
These archives contain the module's JAR plus any dependencies required by the module, except for any Kafka Connect API and implementation-related artifacts that are to be provided by the Kafka Connect service.
=> DBZ-17 Added plugin distribution ZIP for MySQL and other connectors

pom.xml
As of today, the `org.jolokia:docker-maven-plugin` has moved into the Fabric8 community and changed its Maven groupID to `io.fabric8`. This PR changes the groupID and also upgrades the release number from 0.13.9 to 0.14.1 (the latest). The plugins [change log](https://github.com/fabric8io/docker-maven-plugin/blob/master/doc/changelog.md) is available.
=> DBZ-22 Adapted to the Docker Maven Plugin's move to Fabric8 community

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/TableConverters.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-core/src/main/java/io/debezium/relational/Tables.java, debezium-core/src/test/java/io/debezium/util/Testing.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
Corrected the logic of the MySQL connector upon restart to properly recover the table information from the database history, and changed one of the integration tests to verify the correct behavior. 
Also corrected the embedded connector framework (which is used in the integration tests) to properly shut down the connectors, and changed the MySQL connector to return from `poll()` when the connector is stopped. Several log statements were improved.
=> DBZ-26 Corrected how MySQL table info is recovered from db history upon connector restart

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/TableConverters.java
Corrects a bug where a deleted row was written to Kafka in the same as an insert, making them indistinguishable. Now, a deleted row is written with the row's primary/unique key as the record key, and a null record value. Note that if the row has no primary/unique key, no record is written to Kafka.
=> DBZ-28 Corrected MySQL connector's behavior for representing deletes

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java, debezium-core/src/main/java/io/debezium/relational/ddl/DdlParser.java, debezium-core/src/main/java/io/debezium/relational/ddl/DdlParserListener.java, debezium-core/src/main/java/io/debezium/relational/ddl/DdlParserSql2003.java, debezium-core/src/test/java/io/debezium/relational/ddl/SimpleDdlParserListener.java
Refactored the mechanism by which components can listen to the activities of a DDL parser. The new approach should be significantly more flexible for additional types of DDL events while making it easier to maintain backward compatibility. It also will enable passing event-specific information on each DDL event.
Now, the `DdlParserListener` interface has a single method:
```
@FunctionalInterface
public interface DdlParserListener {
/**
* Handle a DDL event.
* @param event the DDL event; never null
*/
void handle(Event event);
}
```
where `Event` is an abstract base class:
```
public static abstract class Event {
...
/**
* Get the type of event. This is useful when switching on the kind of event.
* @return the type of event; never null
*/
public EventType type() { ... }
/**
* Get the DDL …
```
=> DBZ-38 Changed the listening framework of the DDL parser

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/TableConverters.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-core/src/main/java/io/debezium/config/Configuration.java, debezium-core/src/main/java/io/debezium/function/Predicates.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java, debezium-core/src/main/java/io/debezium/relational/ColumnId.java, debezium-core/src/main/java/io/debezium/relational/ColumnMapper.java, debezium-core/src/main/java/io/debezium/relational/ColumnMappers.java, debezium-core/src/main/java/io/debezium/relational/Selectors.java, debezium-core/src/main/java/io/debezium/relational/TableId.java, debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java, debezium-core/src/main/java/io/debezium/relational/Tables.java, debezium-core/src/main/java/io/debezium/relational/ValueConverter.java, debezium-core/src/main/java/io/debezium/util/Strings.java, debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java, debezium-core/src/test/java/io/debezium/function/PredicatesTest.java, debezium-core/src/test/java/io/debezium/relational/ColumnMappersTest.java, debezium-core/src/test/java/io/debezium/relational/SelectorsTest.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
Changes the MySQL connector to use regular expressions in the database and table blacklist/whitelists, and adds support for excluding, truncating, and masking certain columns.
Changed the MySQL connector to use comma-separated lists of regular expressions for the database and table whitelist/blacklists. Literals are still accepted and will match fully-qualified table names, although the `.` character used as a delimiter is also a special character in regular expressions and therefore may need to be escaped (e.g., preceded by a double backslash (`\\`) or surrounded by square brackets) to more carefully match fully-qualified table names.
Added several new configuration properties for the MySQL connector that instruct it to hide, truncate, and/or mask certain columns. The properties' values …
=> DBZ-29 Changed MySQL connector to be able to hide, truncate, and mask specific columns

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/TableConverters.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
When a row is updated in the database and the primary/unique key for that table is changed, the MySQL connector continues to generate an update event with the new key and new value, but now also generates a _tombstone event_ for the old key. This ensures that when a Kafka topic is compacted, all prior events with the old key will (eventually) be removed. It also ensures that consumers see that the row represented by the old key has been removed.
=> DBZ-44 Generate a tombstone for old key when row's key is changed

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/TableConverters.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-core/src/main/java/io/debezium/data/Envelope.java, debezium-core/src/main/java/io/debezium/data/SchemaUtil.java, debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java, debezium-core/src/test/java/io/debezium/data/EnvelopeTest.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
The new envelope Struct contains fields for the local time at which the connector processed the event, the kind of operation (e.g., read, insert, update, or delete), the state of the record before and after the change, and the information about the event source. The latter two items are connector-specific. The timestamp is merely the time using the connector's process clock, and no guarantees are provided about accuracy, monotonicity, or relationship to the original source event.
The envelope structure is now used as the value for each event message in the MySQL connector; they keys of the event messages remain unchanged. Note that to facilitate Kafka log compaction (which requires a null value), a delete event containing the envelope with details about the deletion is followed by a …
=> DBZ-52 Added top-level container structure to all messages

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
Two unit tests are added and they show that the existing MySQL DDL parser properly handles column definitions of the form `... VARCHAR(50) CHARACTER SET utf8 ...`. Note that the [MySQL documentation](http://dev.mysql.com/doc/refman/5.7/en/charset-column.html) makes no mention of supporting `CHARSET`.
=> DBZ-57 Support CHARSET alias for CHARACTER SET

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
Added to the Debezium event message's `source` information the MySQL server ID for the cluster process that recorded the event and the MySQL timestamp at which the event was recorded.
The following is a sample of the new `source` struct in a message's envelope:
```
"source" : {
"name" : "kafka-connect",
"server-id" : 112233,
"ts" : 1463753313000,
"file" : "mysql-bin.000003",
"pos" : 1081,
"row" : 0
},
```
Note that the `server-id` and `ts` fields are both new, and the `name` field was previously called `server` and contains the connector's logical name of the server; the rest of the fields in `source` are unchanged, as are any other part of the event structure. The schema for the `source` struct is now:
```
{
"type" : "struct",
"fields" : [ {
"type" : "string",
"optional" : false,
"field" …
```
=> DBZ-60 Added MySQL server ID and timestamp to event's source info

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
Adds integration test logic to verify that UPDATE events include both `before` and `after` states (previously added as part of DBZ-52), to verify that altering a table does not generate events for the rows in that table, and that the `before` and `after` states (read from the binlog) are always defined in terms of the _current_ table schema. IOW, no special logic is needed to handle a 'before' state that has different columns than defined in the current table's definition.
Also added support for properly handling an ALTER TABLE statement that adds columns AFTER another existing column. This error was discovered during aforementioned testing.
=> DBZ-45 Confirmed and tested support for 'before' and 'after' states in UPDATE events

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/TableConverters.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java, debezium-core/src/main/java/io/debezium/relational/ddl/DdlChanges.java, debezium-core/src/main/java/io/debezium/relational/ddl/DdlParser.java, debezium-core/src/main/java/io/debezium/relational/ddl/DdlParserListener.java, debezium-core/src/main/java/io/debezium/relational/ddl/DdlParserSql2003.java, debezium-core/src/main/java/io/debezium/relational/history/DatabaseHistory.java, debezium-core/src/test/java/io/debezium/relational/ddl/DdlChangesTest.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
Previously, the DDL statements were being filtered and recorded based upon the name of the database that appeared in the binlog. That database name, however, is actually the name of the database to which the client submitting the operation is connected, and is not necessarily the database _affected_ by the operation (e.g., when an operation includes a fully-qualified table name not in the connected-to database).
With these changes, the table/database _affected_ by the DDL statements is now being used to filter the recording of the statements. The order of the DDL statements in the binlog is still maintained, but since each DDL statement can apply to a separate database, the DDL statements are batched (in the same original order) based upon the affected database. For example, two …
=> DBZ-55 Corrected filtering of DDL statements based upon affected database

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-mysql/src/test/resources/log4j.properties, debezium-core/src/main/java/io/debezium/util/LoggingContext.java, debezium-core/src/main/java/io/debezium/util/Strings.java
Changed the MySQL connector to make use of MDC logging contexts, which allow thread-specific parameters that can be written out on every log line by simply changing the logging configuration (e.g., Log4J configuration file).
We adopt a convention for all Debezium connectors with the following MDC properties:
* `dbz.connectorType` - the type of connector, which would be a single well-known value for each connector (e.g., "MySQL" for the MySQL connector)
* `dbz.connectorName` - the name of the connector, which for the MySQL connector is simply the value of the `server.name` property (e.g., the logical name for the MySQL server/cluster). Unfortunately, Kafka Connect does not give us its name for the connector.
* `dbz.connectorContext` - the name of the thread or context, which is "task" for …
=> DBZ-58 Added MDC logging contexts to connector

debezium-connector-mysql/pom.xml, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RecordMakers.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/Configurator.java, debezium-core/pom.xml, debezium-core/src/main/java/io/debezium/data/SchemaUtil.java, debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java, debezium-core/src/test/java/io/debezium/data/VerifyRecord.java, debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java, pom.xml
The `VerifyRecord` utility class has methods that will verify a `SourceRecord`, and is used in many of our integration tests to check whether records are constructed in a valid manner. The utility already checks whether the records can be serialized and deserialized using the JSON converter (provided with Kafka Connect); this change also checks with the Avro Converter (which produces much smaller records and is more suitable for production).
Note that version 3.0.0 of the Confluent Avro Converter is required; version 2.1.0-alpha1 could not properly handle complex Schema objects with optional fields (see https://github.com/confluentinc/schema-registry/pull/280).
Also, the names of the Kafka Connect schemas used in MySQL source records has changed.
1. The record's envelope Schema used to be …
=> DBZ-64 Added Avro Converter to record verification utilities

debezium-connector-mysql/src/test/docker/init/setup.sql, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java, debezium-core/src/main/java/io/debezium/data/SchemaUtil.java, debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java, debezium-core/src/test/java/io/debezium/data/VerifyRecord.java
Binary values read from the MySQL binlog may include strings, in which case they need to be converted to binary values.
Interestingly, work on this uncovered [KAFKA-3803](https://issues.apache.org/jira/browse/KAFKA-3803) whereby Kafka Connect's `Struct.equals` method does not properly handle comparing `byte[]` values. Upon researching the problem and potentially supplying a patch, it was discovered that the Kafka Connect codebase and the Avro converter all use `ByteBuffer` objects rather than `byte[]`. Consequently, the Debezium code that converts JDBC values to Kafka Connect values was changed to return `ByteBuffer` objects rather than `byte[]` objects.
Unfortunately, the JSON converter rehydrates objects with just `byte[]`, so that still means that Debezium's `VerifyRecords` logic …
=> DBZ-61 Improved MySQL connector's handling of binary values

debezium-assembly-descriptors/pom.xml, debezium-connector-mysql/pom.xml, debezium-core/pom.xml, debezium-embedded/pom.xml
The version specifications in child modules are not require when they are the same as the parent.
=> Removed duplicate versions in POMs

debezium-connector-mysql/pom.xml, pom.xml
Corrected the MySQL connector plugin to include the MySQL JDBC driver, which was only used in tests in 0.1. Also upgraded the MySQL JDBC driver from 5.1.38 to 5.1.39, which is the latest available.
=> DBZ-71 Corrected MySQL connector plugin archives and upgraded MySQL JDBC driver

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/Configurator.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlSchemaTest.java
Corrected the Kafka Connect schema names generated for each table. These were missing a delimiter between the connector's logical name and the fully qualified table name. Added a unit test to verify it is being set correctly.
=> DBZ-72 Corrected the naming of the Schemas for the keys and values

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RecordMakers.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlSchemaTest.java
Fixes two issues with how the binlog coordinates are handled.
The first, DBZ-73, fixes how the offsets are recording the _next_ binlog coordinates within the offsets, which is fine for single-row events but which can result in dropped events should Kafka Connect flush the offset of some but not all of the rows before the Kafka Connect crashes. Upon restart, the offset contains the binlog coordinates for the _next_ event, so any of the last rows from the previous events will be lost.
With this fix, the offset used with all but the last row (in the binlog event) has the binlog coordinates of the current event, with the event row number set to be the next row that needs to be processed. The offset for the last row will have the binlog coordinates of the next event.
The second issue, DBZ-76, …
=> DBZ-73, DBZ-76 Corrected how binlog coordinates are recorded and put into change events

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RecordMakers.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
Added unit tests that verify the behavior of the MySQL connector's `SourceInfo` component. This testing reveal an issue with how offsets were being recorded at the end of a snapshot ([DBZ-77](https://issues.jboss.org/browse/DBZ-77)). The second commit corrects this problem by utilizing the recently-added logic for different offset and `source` field information on the very last record produced during the snapshot.
=> DBZ-73, DBZ-77 Added offset tests and fix for incomplete snapshot bug

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RecordMakers.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
Added unit tests that verify the behavior of the MySQL connector's `SourceInfo` component. This testing reveal an issue with how offsets were being recorded at the end of a snapshot ([DBZ-77](https://issues.jboss.org/browse/DBZ-77)). The second commit corrects this problem by utilizing the recently-added logic for different offset and `source` field information on the very last record produced during the snapshot.
=> DBZ-73, DBZ-77 Added offset tests and fix for incomplete snapshot bug (for 0.2.x)

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/GtidSet.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/GtidSetTest.java
Removed several of the `GtidSet` convenience methods that are not in the [improved](https://github.com/shyiko/mysql-binlog-connector-java/pull/100) `com.github.shyiko.mysql.binlog.GtidSet` class. Getting these out of our API will make it easier to reuse the improved `com.github.shyiko.mysql.binlog.GtidSet` class.
=> DBZ-79 Changed public methods in GtidSet to reflect the MySQL Binary Log Connector's class

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/GtidSet.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/GtidSetTest.java
Removed several of the `GtidSet` convenience methods that are not in the [improved](https://github.com/shyiko/mysql-binlog-connector-java/pull/100) `com.github.shyiko.mysql.binlog.GtidSet` class. Getting these out of our API will make it easier to reuse the improved `com.github.shyiko.mysql.binlog.GtidSet` class.
=> DBZ-79 Changed public methods in GtidSet to reflect the MySQL Binary Log Connector's class (0.2.x)

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
The MySQL connector now maps TINYINT and SMALLINT columns to INT16 (rather than INT32) because INT16 is smaller and yet still large enough for all TINYINT and SMALLINT values. Note that the range of TINYINT values is either -128 to 127 for signed or 0 to 255 for unsigned, and thus INT8 is not an acceptable choice since it can only handle values in the range 0 to 255. Additionally, the JDBC Specification also suggests the proper Java type for SQL-99's TINYINT is short, which maps to Kafka Connect's INT16.
This change will be backward compatible, although the generated Kafka Connect schema will be different than in previous versions. This shouldn't cause a problem, since clients should expect to handle schema changes, and this schema change does comply with Avro schema evolution rules.
=> DBZ-87 Changed mapping of MySQL TINYINT and SMALLINT columns from INT32 to INT16

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java, debezium-connector-mysql/src/test/docker/init/setup.sql, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java, debezium-core/src/main/java/io/debezium/data/SchemaUtil.java, debezium-core/src/main/java/io/debezium/jdbc/TimeZoneAdapter.java, debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java, debezium-core/src/test/java/io/debezium/jdbc/TimeZoneAdapterTest.java, pom.xml
Added an integration test case to diagnose the loss of the fractional seconds from MySQL temporal values. The problem appears to be a bug in the MySQL Binary Log Connector library that we used, and this bug was reported as https://github.com/shyiko/mysql-binlog-connector-java/issues/103. That will have to be fixed and released before we can resolve the issue in Debezium.
During testing, though, one small issue was discovered in how Time values are handled, so that was corrected.
=> DBZ-85 Added test case and made small correction to temporal values

debezium-core/src/test/java/io/debezium/jdbc/TimeZoneAdapterTest.java, debezium-core/src/test/java/io/debezium/kafka/ZookeeperServer.java
* fixes a java.sql.Date conversion test to take into account zone offsets
* makes sure the ZK DB is closed during testing, otherwise file handles may leak and cause test failures
=> Fixes a couple of test related issues for debezium-core

debezium-connector-mysql/pom.xml
The `mysql:5.7` docker image was recently updated and changed its output to be more like `mysql/mysql-server:5.7`. This broke our build since our build looks for specific lines in the output to know when the server has completed initialization. Simply changing the pattern corrects the problem.
=> Corrected build to look for updated output of alt-mysql container

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RecordMakers.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-core/src/main/java/io/debezium/function/BufferedBlockingConsumer.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java, debezium-core/src/main/java/io/debezium/util/Strings.java, debezium-core/src/test/java/io/debezium/function/BufferedBlockingConsumerTest.java
By default the MySQL JDBC driver will put the entire result set into memory, which obviously doesn't work for tables of even moderate sizes. This change adds support for streaming rows in result sets when the tables have more than a configurable number of rows (defaults to 1,000).
This posed a problem for how we were previously finding the last row in the last table; the MySQL driver does not support `ResultSet.isLast()` on result sets that are streamed. Instead, this commit wraps the consumer to which the snapshot reader writes all source records, with a consumer that buffers the last record. When the snapshot completes, the offset is updated (denoting the end of the snapshot) and set on the last buffered record before that record is flushed to the normal consumer. This should add …
=> DBZ-94 Added support for copying very large tables during snapshot

pom.xml
Although Kafka 0.10.0.1 has a dependency on Zookeeper 3.4.6, the http://zookeeper.apache.org states that the stable release is 3.4.8, and it incorporates numerous bug fixes since 3.4.6.
=> DBZ-62 Upgraded to Kafka 0.10.0.1 and Zookeeper 3.4.8

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnector.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySQLConnection.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTaskContextIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadBinLogIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotReaderIT.java, debezium-core/src/main/java/io/debezium/config/Field.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java, pom.xml
Changed the MySQL connector to have several new configuration properties for setting up the SSL key store and trust store, which can be used in place of System or JDK properties. Two additional configuration properties separately enable secure connections to MySQL and to enable secure connections for the database history's Kafka producer and consumer.
Modified several integration tests to ensure all MySQL connections are made with `useSSL=false`.
=> DBZ-99 Added support for MySQL connector to connect securely to MySQL

CHANGELOG.md, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractReader.java
The binlog reader and JDBC operations might throw exceptions with this information, so in these cases the connector now captures the error code and SQLSTATE code from the exception and includes them in the message.
=> DBZ-109 Captured MySQL error code and SQLSTATE code in exceptions

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/GtidSet.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/GtidSetTest.java
The MySQL connector was improperly comparing the GTID set required by the connector to the GTID set of the MySQL instance. In particular, when the GTID set of the MySQL server contained a newline character, the comparison logic failed. (This should have been fixed as part of DBZ-107.)
=> DBZ-111 Corrected GTID set comparison logic of the MySQL connector

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
The MySQL connector now outputs an INFO log message whenever its task's `poll()` method returns a non-empty list of `SourceRecord` objects, where the message includes the number of records and the offset of the last record.
=> DBZ-116 Improved logging when MySQL connector is reading binlog

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java
The MongoDB connector now outputs an INFO log message whenever its task's `poll()` method returns a non-empty list of `SourceRecord` objects, where the message includes the number of records and the offset of the last record.
=> DBZ-117 Improved logging when MongoDB connector is reading oplog

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
This is to support Long data types for server.id instead of int.
=> DBZ-118 Change database.server.id to support Long instead of Int

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RowDeserializers.java, debezium-connector-mysql/src/test/docker/init/setup.sql, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java, debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
MySQL supports "zero-value" dates and timestamps, but these cannot be represented as valid dates or timestamps using the Java types. For example, the zero-value `0000-00-00` for a date has what Java considers to be an invalid month and day-of-the-month.
This commit changes how the MySQL connector handles these values to not throw exceptions. When columns allow nulls, such values will be treated as nulls; when columns do not allow null values, these values will be converted to a "zero-value" for the corresponding Java representation (e.g., the epoch day or timestamp). A new test case verifies the behaviors.
=> DBZ-114 MySQL connector now handles "zero-value" dates and timestamps

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java, debezium-core/src/main/java/io/debezium/config/Configuration.java, debezium-core/src/main/java/io/debezium/relational/history/DatabaseHistory.java, debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java, debezium-core/src/test/java/io/debezium/relational/history/KafkaDatabaseHistoryTest.java, debezium-core/src/test/resources/log4j.properties
The `KafkaDatabaseHistory` was always creating a new producer whenever its `start()` method was called, even if it were called more than once. And, the `MySqlSchema` was calling `start()` twice, resulting in multiple producers being created and registered with JMX. Both issues were fixed.
Also, UUIDs were being used as the name of the JMX MBean for the producer, unless the `database.history.consumer.client.id` and `database.history.producer.client.id` properties were being explicitly set. Now, the MySQL connector will by default set the `client.id` property on both the database history's Kafka consumer and producer to `{connectorName}-dbhistory`. Of course, the `database.history.consumer.client.id` and `database.history.producer.client.id` properties can still be set to define the name of …
=> DBZ-124 Eliminated the JMX "already registered" warning in the MySQL connector

debezium-core/src/main/java/io/debezium/config/Configuration.java, debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java, debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java
Anytime we `toString()` a `Configuration`, any values for password properties should be masked. We define a password property as one whose key ends in `password` in a case-insensitive manner.
=> DBZ-122 Prevent logging of password configuration property values

debezium-core/src/main/java/io/debezium/config/Configuration.java, debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java, debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java
Anytime we `toString()` a `Configuration`, any values for password properties should be masked. We define a password property as one whose key ends in `password` in a case-insensitive manner.
=> DBZ-122 Prevent logging of password configuration property values (0.3.x)

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java, debezium-connector-mysql/src/test/docker/init/setup.sql, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java, debezium-core/src/main/java/io/debezium/data/Bits.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java
Corrected how the MySQL connector is treating columns of type `BIT(n)`, where _n_ is the number of bits in the value. When  `n=1`, the resulting values are booleans; when `n>1`, the resulting values are little endian `byte[]` that have the minimum number of bytes to hold the `n` bits.
=> DBZ-123 Corrected MySQL Connector's support for BIT(n) columns

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
Added logic to verify that MySQL's row-level binlog is enabled, and whether it is likely that when snapshots are not performed that the binlog is likely to have been purged. Some situations will result in an error, while others are logged as warnings.
=> DBZ-128 Improved checking of MySQL status and configuration

debezium-connector-mysql/src/test/docker/init/setup.sql, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
Added tests with and without snapshots. Behavior appears to work fine, even when a statement like `CREATE TABLE db.a LIKE other.b` statement is used and the database `db` is included in the connector's database whitelist filter and database `other` is excluded by the connector's database whitelist filter.
=> DBZ-104 Added test to verify behavior of CREATE TABLE LIKE expression

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-core/src/main/java/io/debezium/util/DelayStrategy.java, debezium-core/src/main/java/io/debezium/util/ElapsedTimeStrategy.java, debezium-core/src/test/java/io/debezium/util/ElapsedTimeStrategyTest.java, debezium-core/src/test/java/io/debezium/util/MockClock.java
When the MySQL connector is reading the binlog, it outputs INFO log messages reporting status at an exponentially-increasing rate, starting at every 5 seconds and doubling until a max period of 1 hour. This output is useful when the connector starts to know that it is working, but thereafter the usefulness decreases. Once an hour is probably acceptable output.
This is not intended to replace the capturing of metrics, but is merely an aid to easily tell via the logs whether the connector continues to work.
Also improved the log message when the binlog reader stops to capture the total number of events recorded by Kafka Connect and the last recorded offset.
=> DBZ-131 Improved logging while reading binlog

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java, debezium-connector-mysql/src/test/resources/ddl/mysql-dbz-123.ddl, debezium-core/src/main/java/io/debezium/relational/ddl/DdlParser.java
The DDL parser now properly handles bit-set literals, and several minor case-sensitivity bugs dealing with other escaped literals.
=> DBZ-123 Corrected the MySQL DDL parser to properly handle bit-set literals

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
Reason for this pull request is because of the following error:
```
2016-10-07 22:47:31,575 TRACE  MySQL|my_williedb|binlog  Ignoring event due to missing handler: Event{header=EventHeaderV4{timestamp=1475873147000, eventType=UPDATE_ROWS, serverId=1, headerLength=19, dataLength=117, nextPosition=1120, flags=0}, data=UpdateRowsEventData{tableId=748, includedColumnsBeforeUpdate={0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, includedColumns={0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, rows=[
{before=[16192792, 12, 34227952, 10, 8, 0, 1109399502, 2016-06-25T17:55:33Z, 2016-10-07T20:23:48.472583Z, 0], after=[16192792, 12, 34227952, 10, 8, 0, 1109459289, 2016-06-25T17:55:33Z, 2016-10-07T20:45:47.985929Z, 0]}
]}}   [io.debezium.connector.mysql.BinlogReader]
```
The binlog reader does not recognize any `EventType` with …
=> DBZ-115 Add support to recognize older row_event formats

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RowDeserializers.java, debezium-connector-mysql/src/test/docker/init/setup.sql, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorJsonIT.java, pom.xml
Adds support for MySQL 5.7's `JSON` type, which is capable of holding JSON objects, JSON arrays, and scalar values. The Debezium MySQL connector represents `JSON` values as string with a `io.debezium.data.Json` semantic type (which is basically a string schema that has a special name to denote the semantics), and the _contents_ of that string will be the JSON representation of the object, array, or scalar value.
=> DBZ-126 Added support for MySQL JSON type (0.3.x)

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RowDeserializers.java, debezium-connector-mysql/src/test/docker/init/setup.sql, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorJsonIT.java, pom.xml
Adds support for MySQL 5.7's `JSON` type, which is capable of holding JSON objects, JSON arrays, and scalar values. The Debezium MySQL connector represents `JSON` values as string with a `io.debezium.data.Json` semantic type (which is basically a string schema that has a special name to denote the semantics), and the _contents_ of that string will be the JSON representation of the object, array, or scalar value.
=> DBZ-126 Added support for MySQL JSON type

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java
MySQL records the timestamp with second precision in binlog events, but the library we use multiplies by 1000 to return the padded value in milliseconds (even though the value still has second precision). The BinlogReader converts this back to seconds, so the SourceInfo should not also be dividing by 1000.
=> DBZ-139 Corrected binlog timestamp handling

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotReaderIT.java
Enables schema-only snapshot mode that does capture the database table schemas but does *not* copy the data. When this snapshot completes, the connector will continue by reading the binlog from the point in time the snapshot was made.
This option should be used with care because it does not provide a consistent copy of the database. However, it still is very useful when the change event consumers need only the changes from the point in time the snapshot is made. For example, consider an application that merely wants to know about the database changes that were made _since the application has started running_.
This supersedes #125, which had an extra merge in the history, but does retain all of the changes made by @pranmitt to implement this feature and add tests to verify initial data is …
=> DBZ-133 Support 'schema' snapshot mode for MySQL connector

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotReaderIT.java
Enables schema-only snapshot mode that does capture the database table schemas but does *not* copy the data. When this snapshot completes, the connector will continue by reading the binlog from the point in time the snapshot was made.
This option should be used with care because it does not provide a consistent copy of the database. However, it still is very useful when the change event consumers need only the changes from the point in time the snapshot is made. For example, consider an application that merely wants to know about the database changes that were made _since the application has started running_.
See also #126 for the pull request to the `master` branch.
=> DBZ-133 Support 'schema' snapshot mode for MySQL connector (0.3.x)

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/GtidSet.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTaskContextTest.java
Make Debezium merge its GTID set with the GTID set on the server that it's connecting to. This allows Debezium to consume from a MySQL server that might have a different set of channels (upstream masters), provided that the server has the data that Debezium needs.
=> DBZ-143 Support multi-channel MySQL failover

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java, debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
Improved the error handling of the MySQL connector to ensure that we’re always stopping the connector when we have a problem handling a binlog event or if we have problems starting.
=> DBZ-146 Improved error handling of MySQL Connector

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
The MySQL connector (or rather the DDL parser used in the connector) improperly assumed a `CHAR` JDBC type (and Avro schema `STRING` type) for MySQL columns of type `BINARY`. This corrects the error.
=> DBZ-149 Corrected type of BINARY column

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTaskContextTest.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java, debezium-connector-mysql/src/test/resources/log4j.properties, debezium-core/src/main/java/io/debezium/document/Document.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java, debezium-core/src/main/java/io/debezium/relational/history/AbstractDatabaseHistory.java, debezium-core/src/test/java/io/debezium/data/VerifyRecord.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
Added tests to verify whether the connector is properly restarting in the binlog when previously the connector failed or stopped in the middle of a transaction. The tests showed that the connector is not able to properly start when using or not using GTIDs, since restarting from an arbitrary binlog event causes problems since the `TABLE_MAP` events for the affected tables are skipped.
The logic was changed significantly to record in the offsets the binlog coordinates of each transaction, which should work whether or not GTIDs are used. Upon restart, the connector may have to re-read the events that were previously processed, but now the offset also includes the number of events that were previously processed so that these can be skipped upon restart. When GTIDs are used, the offset also …
=> DBZ-144 Corrected MySQL connector restart logic

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java, debezium-connector-mysql/src/test/docker/init/setup.sql, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java
By default the MySQL connector handles `DECIMAL` and `NUMERIC` columns using `java.math.BigDecimal` values and describing them using the `org.apache.kafka.connect.data.Decimal` schema type, which serializes the values to a binary form.
This change adds a configuration option that will keep the default behavior, but will instead allow handling `DECIMAL` adn `NUMERIC` values as Java `double` and a schema type of `FLOAT64`.
=> DBZ-147 Added ability to treat MySQL DECIMAL as double

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java, debezium-core/src/test/java/io/debezium/relational/ddl/DataTypeParserTest.java
Changed the MySQL connector to support ENUM and SET literals with parentheses.
=> DBZ-153 MySQL connector supports enum and set values with parentheses

debezium-connector-mysql/pom.xml, pom.xml
Upgraded the Docker Maven plugin to 0.18.2, which required changing our use of the `docker.image` to `docker.filter` (per the [changes in 0.17.1](https://github.com/fabric8io/docker-maven-plugin/blob/master/doc/changelog.md)).
=> DBZ-157 Upgraded Docker Maven plugin

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java, debezium-core/src/main/java/io/debezium/relational/ddl/DdlParser.java
DBZ-160 - Issue while parsing create table script with ENUM type and default value 'b'
=> DBZ-160 - Issue while parsing create table script with ENUM type and default value 'b'

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-connector-mysql/src/test/docker/init/setup.sql, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java, debezium-connector-mysql/src/test/resources/ddl/mysql-dbz-162.ddl, debezium-core/src/main/java/io/debezium/relational/ddl/DdlParser.java, debezium-core/src/test/java/io/debezium/relational/history/AbstractDatabaseHistoryTest.java
The MySQL DDL parser was not properly consuming function declarations. For functions, the parser consumes the entire statement without handline the various expressions within the function declaration, but the parser was not properly finding the end of the statement and instead was continuing to try to consume values beyond the end of the statement.
Specifically, when the parser consumes a `BEGIN`, it looks for a corresponding `END`. However, if it encountered an `END IF`, the `IF` plus any remaining tokens were left on the token stream and unprocessed. This confused the parser, which keep looking for statements and ultimately ended with a `No more content` error.
This case was replicated in integration tests, and the code fixed to properly find the end of the statements.
=> DBZ-162 Corrected DDL parsing of MySQL functions

.travis.yml
Recently, Travis-CI changed the sudo enabled Trusty images that we use in our builds to by-default install and run MySQL 5.6 and Postgres 9.6. This commit stops those services in the `before_install` step of our Travis-CI builds.
=> DBZ-163 Stop Travis-CI’s MySQL and PostgreSQL instances

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
Determining the number of rows in large InnoDB tables using `SELECT COUNT(*) FROM ...` queries could be expensive and time consuming. Rather than always doing these checks, this change expands the MySQL connector’s `min.row.count.to.stream.results` configuration property to accept a value of 0 (rather than just positive numbers). The connector uses a zero value to signify that streaming should be used for all tables and to completely avoid running `SELECT COUNT(*) FROM tableA` queries.
=> DBZ-152 Enabled MySQL connector to skip table count checks during snapshot

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
MySQL 5.7.7 introduced new behavior for handling XA events in the binlog. See the [MySQL documentation](http://dev.mysql.com/doc/refman/5.7/en/xa-restrictions.html) for details. This PR changes the binlog reader so that `XA …` statements appearing in the binlog are ignored altogether.
=> DBZ-168 MySQL connector ignores XA binlog events

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetDiscovery.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSets.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java
This change alters the way the MongoDB connects to the various servers in a cluster. Previously, the ConnectionContext constructor currently set up the MongoDB client with credentials for the `admin` and `config` databases, and apparently the client eagerly performs authentication against all databases passed in, rather than doing this lazily as DBs are use.
Instead, the code no longer sets up the credentials for the `config` database and instead only sets up credentials for the `admin` database for authentication and authorization. This works as long as the user specified in the connector configuration can read the `config` database.
Several other changes were made to improve the error handling and reporting when the replica set information cannot be read from the `config` database.
=> DBZ-170 Changed the MongoDB connector’s connection logic

debezium-connector-postgres/pom.xml, pom.xml
The PostgreSQL connetor was not able to build locally, since the Maven build would wait forever trying to talk to the TCP port for PostgreSQL before starting the integration tests. Even when I corrected the `wait` specification to use the localhost (rather than the direct container address), the build successfully connected to Postgres when it started the first time but before it shutdown to adjust the configuration, and thus the tests failed as the server was shutdown. The build now looks for a specific log message which is unique and output by the container after the second startup, and this seems to work great (at least locally).
=> DBZ-3 Changed the PostgreSQL connector’s use of Docker containers

integration-tests/mysql/debezium-connector-mysql-5.6-gtid-integration-tests/src/test/expected/master/no-snapshot/filter-db/expected-records.json, integration-tests/mysql/debezium-connector-mysql-5.6-gtid-integration-tests/src/test/expected/master/no-snapshot/filter-table/expected-records.json, integration-tests/mysql/debezium-connector-mysql-5.6-gtid-integration-tests/src/test/expected/master/no-snapshot/no-filter/expected-records.json, integration-tests/mysql/debezium-connector-mysql-5.6-gtid-integration-tests/src/test/expected/master/snapshot/filter-db/expected-records.json, integration-tests/mysql/debezium-connector-mysql-5.6-gtid-integration-tests/src/test/expected/master/snapshot/filter-table/expected-records.json, integration-tests/mysql/debezium-connector-mysql-5.6-gtid-integration-tests/src/test/expected/master/snapshot/no-filter/expected-records.json, integration-tests/mysql/debezium-connector-mysql-5.6-gtid-integration-tests/src/test/expected/replica/no-snapshot/filter-db/expected-records.json, integration-tests/mysql/debezium-connector-mysql-5.6-gtid-integration-tests/src/test/expected/replica/no-snapshot/filter-table/expected-records.json, integration-tests/mysql/debezium-connector-mysql-5.6-gtid-integration-tests/src/test/expected/replica/no-snapshot/no-filter/expected-records.json, integration-tests/mysql/debezium-connector-mysql-5.6-gtid-integration-tests/src/test/expected/replica/snapshot/filter-db/expected-records.json, integration-tests/mysql/debezium-connector-mysql-5.6-gtid-integration-tests/src/test/expected/replica/snapshot/filter-table/expected-records.json, integration-tests/mysql/debezium-connector-mysql-5.6-gtid-integration-tests/src/test/expected/replica/snapshot/no-filter/expected-records.json, integration-tests/mysql/debezium-connector-mysql-5.7-integration-tests/src/test/expected/no-snapshot/filter-db/env.properties, integration-tests/mysql/debezium-connector-mysql-5.7-integration-tests/src/test/expected/no-snapshot/filter-table/env.properties, integration-tests/mysql/debezium-connector-mysql-5.7-integration-tests/src/test/expected/no-snapshot/no-filter/env.properties
New MySQL patch versions in the Docker images introduce new log events, and therefore our expected results need to change slightly to account for the different positions and transactions.
=> Fixed MySQL integration tests to handle new log events from new MySQL versions

debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java, debezium-core/src/test/java/io/debezium/relational/history/KafkaDatabaseHistoryTest.java, pom.xml
The `KafkaDatabaseHistory` class was not behaving well in tests using my local development environment. When restoring from the persisted Kafka topic, the class would set up a Kafka consumer and see repeated messages. It is unclear whether the repeats were due to our test environment and very short poll timeouts. Regardless, the restore logic was refactored to track offsets so as to only process messages once.
=> DBZ-173 Additional fixes to KafkaDatabaseHistory class for Kafka 0.10.1.0

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/AbstractMySqlConnectorOutputTest.java, debezium-embedded/src/test/java/io/debezium/embedded/ConnectorOutputTest.java, pom.xml
Changed the events’ `source` structure to optionally contain the identifier of the MySQL thread where appropriate. The thread is included on each `BEGIN` binlog event, so these are captured and added to all of the associated change events produced for that transaction.
=> DBZ-113 Added MySQL threads to the event’s source metadata

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java, debezium-connector-mysql/src/test/resources/ddl/mysql-dbz-176.ddl, debezium-core/src/main/java/io/debezium/relational/ddl/DdlTokenizer.java
The MySQL DDL parser was not correclty handling `DEFINER` clauses within `CREATE TRIGGER` or `CREATE EVENT` statements. Support for `DEFINER` clauses was previously added for the various forms of `CREATE PROCEDURE`, `CREATE FUNCTION` and `CREATE VIEW` statements. These are the only kinds of statements that have the definer attribute, per the [MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/stored-programs-security.html).
=> DBZ-176 Corrected MySQL DDL parser to support creating triggers with definers

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
Corrected the MongoDB connector upon startup to restart an initial sync if the previously recorded offset signals that an initial sync was not completed in the prior run.
Also change the connector’s replicator to buffer the last record during an initial sync so that, upon completion of the initial sync, the last record can be updated with an offset that reflects that the initial sync was completed. This way, if the initial sync is completed but there are no other events in the oplog, the connector will still consider the initial sync as completed.
=> DBZ-182 Restart MongDB initial sync if necessary

pom.xml
Some of our test cases verify (de)serialization using the Avro Converter, which is included in the Confluent Platform. This commit upgrades the Confluent Platform to version 3.1.2, which matches Kafka 0.10.1.1.
=> DBZ-173 Upgraded Confluent Platform libraries used in test cases

pom.xml
Upgraded Shyiko’s MySQL binary log client library from 0.8.0 to 0.9.0 to get new timeout behavior when it opens sockets and fix for JSON array processing.
=> DBZ-186 Upgraded MySQL binary log client library

pom.xml
Upgraded the MongoDB server to 3.2.12 and the Java driver to 3.4.2.
=> DBZ-187 Upgrade MongoDB server and Java driver versions

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/Configurator.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTaskContextTest.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java
Corrects how the MySQL connector reloads database history to take into account the included and excluded GTID sources. This only affects a connector configured to capture changes from _multiple_ MySQL database servers when GTID sources are explicitly excluded or included.
=> DBZ-185 MySQL’s database history now filters GTID sources

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java, debezium-core/src/main/java/io/debezium/function/Predicates.java, debezium-core/src/main/java/io/debezium/util/Strings.java, debezium-core/src/test/java/io/debezium/function/PredicatesTest.java
Changed the GTID source filters in the MySQL connector to be far more efficient when the filters specify literal UUIDs rather than regex patterns. In these cases, the predicate just checks whether a supplied value is in a hash set, and no regular expression patterns are used.
The GTID source filters can still be a combination of UUID literals and regular expressions, and the predicate will use the best implementation for each. For example, if the filters include all UUID literals, then regular expressions will never be used.
=> DBZ-188 More efficient GTID source filters for MySQL Connector

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java, debezium-connector-mysql/src/test/resources/ddl/mysql-dbz-193.ddl
Corrected the MySQL DDL parser to correctly handle `FULLTEXT` indexes within a `CREATE TABLE` statement. The parser was incorrectly using `canConsume(...)` with a list of options instead of `canConsumeAnyOf(...)`.
=> DBZ-193 MySQL DDL parser handling FULLTEXT index

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/Filters.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/FiltersTest.java
The MySQL connector’s built-in table filter now just filters out all tables within the known built-in databases, and does not check the names of the tables. Thus, the connector should no longer filter out tables in other databases that happen to have the same names as the tables in the built-in databases.
=> DBZ-194 Improved MySQL connector’s built-in table filtering

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java
Hi Randall,
Here's the code that I've been using in testing to allow debezium to parse `SAVEPOINT`. As near as I can tell, there isn't any special logic required for mysql; the connector just needs to be able to parse and discard the statement.
=> DBZ-196 Handle SAVEPOINT statements appearing in a MySQL replication stream

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java, debezium-connector-mysql/src/test/resources/ddl/mysql-dbz-198.ddl, debezium-core/src/main/java/io/debezium/relational/ddl/DdlParser.java, debezium-core/src/main/java/io/debezium/text/TokenStream.java, debezium-core/src/test/java/io/debezium/text/TokenStreamTest.java
The MySQL parser now properly handles control blocks such as `BEGIN…END`, `IF…END IF`, `REPEAT…END REPEAT`, and `LOOP…END LOOP`, even in cases where the block is preceded by and terminated by a label.
=> DBZ-198 Improved MySQL DDL parser to better handle blocks

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
MySQL represents an invalid [enum literal](https://dev.mysql.com/doc/refman/5.7/en/enum.html) in the binlog events as an empty string or an value of `0`. Now, when the connector comes across such a value in the binlog, it will instead use an empty string for the enum literal.
=> DBZ-197 Corrected MySQL connector to handle invalid enum values

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/RecordMakers.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
Corrected how the MongoDB extracts the event key from the update event’s ObjectID, and verified the behavior with an integration test.
=> DBZ-201 Corrected handling of ObjectID within non-insert events

debezium-connector-mongodb/pom.xml, pom.xml
Changed how the mongo-init process waits to begin by now looking for the second MongoDB server log message saying it is ready, since the MongoDB image now has different startup behavior.
=> DBZ-213 Corrected MongoDB connector build

debezium-core/pom.xml, debezium-core/src/main/java/io/debezium/config/Field.java, debezium-core/src/main/java/io/debezium/transforms/ByLogicalTableRouter.java
…ons.
As an example, I have the following transformation configured:
```
"transforms": "sharded_router,non_sharded_router", 
"transforms.sharded_router.type": "io.debezium.transforms.ByLogicalTableRouter", 
"transforms.sharded_router.topic.regex": ".*\\.(?<logicalDb>etsy_[^.]+)_\\d+\\.(?<table>[^.]+)",
"transforms.sharded_router.topic.replacement": "${logicalDb}.${table}",
"transforms.sharded_router.key.field.regex": ".*\\.(?<db>etsy_[^.]+)\\.(?<table>[^.]+)",
"transforms.sharded_router.key.field.replacement": "${db}",
"transforms.non_sharded_router.type": "io.debezium.transforms.ByLogicalTableRouter",
"transforms.non_sharded_router.topic.regex": ".*\\.(?<db>etsy_[^.]+)\\.(?<table>[^.]+)",
"transforms.non_sharded_router.topic.replacement": "${db}.${table}", …
```
=> DBZ-121: routing to custom topic names via Kafka Connect Transformations

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
If a user wants to simplify a dev environment and skip certificate validation he needs to provide a custom socket factory.
=> [DBZ-244] Allow unvalidated SSL connections

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/Filters.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/FiltersTest.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlSchemaTest.java
When the `table.ignore.built` is set to `false`, the MySQL connector included all of the ~250 system tables yet the database and table filters were never applied to these system tables and therefore all would be captured. With this change, the database filters and table filters now apply to the system tables should they not be ignored.
Note that this does change the behavior of the connector when `table.ignore.built` is set to `false`. However, it is unlikely that anyone is seriously capturing all of the system table changes, so correcting the behavior is the preferred solution.
=> DBZ-242 Corrected MySQL filters to handle built-in tables

debezium-connector-mysql/pom.xml, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
Hey @rhauch, I'm not 100% sure: it is optional for Postgres, so perhaps the isRequired validation is actually a glitch in the MySQL connector?
Also I was wondering whether we should try and consolidate the settings shared acrossed connectors within core. This would avoid this sort of inconsistency. WDYT?
=> DBZ-243 Don't mention default value for "database.server.name"

debezium-connector-mysql/src/test/docker/init/setup.sql
Test execution is depending on test order - if MySqlConnectorIT is executed before MetadataIT then readbinlog_test is empty and method shouldValidateAcceptableConfiguration() fails onvalidation of list of tables
=> DBZ-251 Prepopulate readbinlog_test database

debezium-core/src/test/java/io/debezium/kafka/KafkaServer.java
https://github.com/EnMasseProject/amqp-kafka-bridge/ is using your `KafkaCluster` for testing and when testing an error scenario I noticed that it's impossible to create a cluster with `auto.create.topics.enable=false`, because it's always overwritten in `KafkaServer`.
=> Respect any existing auto.create.topics.enable when creating a server

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
Parse and ignore any `DELETE` statements that might be seen in the binlog.
Theoretically, the binlog of a properly-configured MySQL server with row-level binlog enabled should never see these statements. However, users on Amazon RDS run into this quite frequently, and we should just handle and ignore them.
=> DBZ-216 MySQL connector should ignore `DELETE FROM` statements

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PgOid.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
Hi Debezium team,
My team was hoping to take advantage of the postgres connector, but we ran into a slight snag as the current implementation does not handle the tstzrange type well. It gets declared a json type in the schema and the fallback code, when pushing, call it a binary array datum, which consequently gets sent onward by the connector as a "toString" byte array (ex: [B@6e33589e ).
I have not checked what happens with other range types, but notice they also fall out of the covered types.
Let me know what I can do to help this along. 
arosenber
=> Add postgres tstzrange support to connector

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java, debezium-connector-mysql/src/test/docker/init/setup.sql, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlGeometryIT.java
A fix for [DBZ-284](https://issues.jboss.org/browse/DBZ-284) when inserting a `NULL` value in a column with `POINT` datatype.
=> DBZ-284 Fix NPE when inserting a NULL in a POINT column

COPYRIGHT.txt, debezium-core/src/main/java/io/debezium/transforms/ByLogicalTableRouter.java, debezium-core/src/test/java/io/debezium/transforms/ByLogicalTableRouterTest.java
The two tickets unintentionally resulted in a higher modification as expected.
@gunnarmorling Sorry, there were a few conflicting changes (could be sorted to the one or the other ticket). I decided not to put effort in keeping them separated, but in producing working software.
- Move cache initialisation to the class members. The cache is per instance of the class and SMTs are bound to the connector in which they are configured. Clearing the cache on stop() seems therefore unnecessary, as we want to reuse the cache for the same connector instance on (re-)start.
- Remove the identity equality checks in favour of Objects.equals(), which are left-hand null-safe. Null-checks are still needed for semantical purposes.
- Logger moved to static member.
- Add new "isNotNull" validation function to …
=> DBZ-326, DBZ-327

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java
According to Mysql document, https://dev.mysql.com/doc/refman/5.7/en/numeric-types.html
keywords DEC and FIXED are synonyms for DECIMAL.
https://issues.jboss.org/browse/DBZ-359
=> Add support for dec and fixed for mysql ddl parser.

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java
As far as I can tell this comment is inaccurate.  
The method appears to be filtering the tables, even though the comment claims it will include those tables excluded by the filter.
=> Fix inaccurate comment on MySQLSchema.tables method

debezium-connector-postgres/pom.xml, pom.xml
It would have been needed for the Postres module only anyways. But it seems the generator plug-in is adding that source path automatically to the compilation already, so it's not needed at all.
https://issues.jboss.org/browse/DBZ-416
=> DBZ-416 Removing unneccessary configuration of build helper plug-in;

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
We can validate PostgreSQL version first and then use select pg_current_wal_lsn() instead when we use PostgreSQL 10.
https://issues.jboss.org/browse/DBZ-424
=> DBZ-424 Can't support PostgreSQL 10

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/EventDataDeserializationExceptionData.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
* Catching the exception and wrapping it into a pseudo INCIDENT event
* Logging the exception and the current SourceInfo state
https://issues.jboss.org/browse/DBZ-217
@rhauch I'm not yet familiar with the binlog format, but I hope the source info provides the state required for spotting the flawed event? It'll log output like so:
2017-05-31 16:16:28,909 ERROR  MySQL|myServer1|binlog  Exception during event data deserialization (source info: binlog file 'mysql-bin.000002', pos=879, skipping 12758 events plus 0 rows, partion: {server=myServer1})   [io.debezium.connector.mysql.BinlogReader]
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1496225416000, eventType=EXT_WRITE_ROWS, serverId=112233, …
=> DBZ-217 Handling exceptions ocurring during binlog event deserialization

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RowDeserializers.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotReaderIT.java, debezium-connector-mysql/src/test/resources/ddl/connector_test_ro.sql, debezium-connector-mysql/src/test/resources/ddl/regression_test.sql, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java, debezium-core/src/main/java/io/debezium/jdbc/TemporalPrecisionMode.java, debezium-core/src/main/java/io/debezium/time/Conversions.java, integration-tests/mysql/debezium-connector-mysql-5.6-gtid-integration-tests/src/test/docker/init/setup.sql, integration-tests/mysql/debezium-connector-mysql-5.6-integration-tests/src/test/docker/init/setup.sql, integration-tests/mysql/debezium-connector-mysql-5.7-gtid-integration-tests/src/test/docker/init/setup.sql, integration-tests/mysql/debezium-connector-mysql-5.7-integration-tests/src/test/docker/init/setup.sql
DBZ-342: fix broken handling of MySQL data type "TIME" for negative values and positive values >= 24:00:00 hours 
@see https://issues.jboss.org/browse/DBZ-342
=> [DBZ-342] fix broken MySQL data type "TIME"

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorTaskIT.java
PostgresConnectorTask throws java.lang.NullPointerException during commit for PAUSED connector after the restart of Kafka Connect application.
https://issues.jboss.org/browse/DBZ-519
=> DBZ-519 NullPointerException happened for PAUSED task

debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java, debezium-core/src/main/java/io/debezium/relational/Tables.java, debezium-core/src/test/java/io/debezium/data/KeyValueStore.java
https://issues.jboss.org/browse/DBZ-543
=> DBZ-543 Removing a few unused methods

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
https://issues.jboss.org/browse/DBZ-595
* shutting down the snapshotting thread and the DB history producer client
if the connector is stopped while trying to write to the history topic
* reducing the time that KafkaProducer#send() will block if Kafka isn't
available; this will release the producer thread quicker in case the
connector is stopped during snapshotting
* not returning from finally block (!) in case the TX is rolled back; This
prevented the failed state to be set by the outer catch clause in execute()
@jpechane that's best reviewed [ignoring whitespace](https://github.com/debezium/debezium/pull/432/files?w=1) differences as I wrapped an entire block of the snapshotting routine in try/catch block without any actual changes to this code (step 6).
We were leaking both the …
=> DBZ-595 Making sure resources are cleaned up when snapshotting fails;

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsProducer.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/MessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationStream.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/Wal2JsonMessageDecoder.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SnapshotWithOverridesProducerIT.java, debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
https://issues.jboss.org/browse/DBZ-580
@jpechane That's the queue implementation we were talking about. It's meant to be used by all connectors, in this PR I include the required changes for PG and MongoDB. I thought it'd be better to wait with doing the same change in MySQL until the DBZ-175 work has been merged, to avoid bigger merging trouble.
=> DBZ-580 Establishing ChangeEventQueue type to be used as queue across all the connectors

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
Halting predicates now force readers to immediately stop and do not read any records beyond their limits.
Logic is now contained in AbstractReader.
=> Modify halting predicate logic.

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java, debezium-core/src/main/java/io/debezium/relational/history/AbstractDatabaseHistory.java, debezium-core/src/main/java/io/debezium/relational/history/DatabaseHistory.java, debezium-core/src/test/java/io/debezium/relational/history/AbstractDatabaseHistoryTest.java, debezium-core/src/test/java/io/debezium/relational/history/KafkaDatabaseHistoryTest.java
https://issues.jboss.org/browse/DBZ-632
@jpechane, a quick clean-up in preparation of adding a non-DDL-based table representation to the schema history (which in turn I need for the Oracle support).
=> DBZ-632 Removing unused method parameter

pom.xml
*Updating to Apache Kafka 1.0.1*
As discussed in [DBZ-647](https://issues.jboss.org/browse/DBZ-647), the used JARs need to be updated
__NOTE:__ I have one error, on MongoDB connector, locally w/ the build - that's happening w/o this PR too...
=> Using latest Kafka libs

debezium-core/src/main/java/io/debezium/heartbeat/HeartbeatImpl.java, debezium-core/src/test/java/io/debezium/transforms/ByLogicalTableRouterTest.java
As @gunnarmorling recommended [here](https://issues.jboss.org/browse/DBZ-668?focusedCommentId=13548206&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13548206), I have changed the heartbeat key message to `Struct` from `String` in order to leverage the `ByLogicalTableRouter` SMT and route all heartbeat messages into a single topic instead of individual topics for each source task
=> DBZ-668 Change the key schema for the heartbeat messages from String to Struct

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationMessage.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoReplicationMessage.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/NonStreamingWal2JsonMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/StreamingWal2JsonMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/Wal2JsonReplicationMessage.java
the getInteger method returns a null when the value txid is not integer
=> DBZ-673 txId must be long in wal2jon decoder

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java, debezium-core/src/test/java/io/debezium/data/VerifyRecord.java
@jpechane That's a side product of my explorations that led to DBZ-727. It's verifying the records now (including their default values).
It uncovered a bug in Kafka Connect ([KAFKA-7058](https://issues.apache.org/jira/browse/KAFKA-7058)) and one in the Avro converter (https://github.com/confluentinc/schema-registry/issues/833). To work around those, schema comparison is done manually in the code instead of relying on `ConnectSchema#equals()` and record validation is commented out for a few records.
=> DBZ-191 Adding record validations

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbTaskContext.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/AbstractMongoIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ConnectionIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/UnwrapFromMongoDbEnvelopeTestIT.java
https://issues.jboss.org/browse/DBZ-713
https://issues.jboss.org/browse/DBZ-782
@jpechane This fixes two issues, I noticed DBZ-782 while working on DBZ-713. It's best reviewed commit by commit, as they are largely independent and I did some clean-up not strictly related to the original issue. Also disable whitelist differences to further ease the diff. Thanks!
In terms of testing, it seems all the MongoDB ITs we have don't deal with authentication/authorization at all. It seems worth to have some tests for that, but let's handle it separately. I tested the original issue manually successfully, i.e. collections from a DB the connector user isn't authorized for won't cause any harm if that other DB is not part of the filter config. I've added some basic tests which make sure that the …
=> DBZ-713 Only getting collections for databases matching filters

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/Filters.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/Filters.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java, debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java, debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java, debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseSchema.java, debezium-core/src/main/java/io/debezium/relational/RelationalTableFilters.java, debezium-core/src/main/java/io/debezium/relational/Tables.java
Only the MySQL connector's Filters class still uses Predicate for the time being, so to avoid to much merging trouble with DBZ-175.
https://issues.jboss.org/browse/DBZ-793
=> DBZ-793 Using TableFilter consistently;

debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java, debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java, debezium-core/src/main/java/io/debezium/pipeline/spi/ChangeRecordEmitter.java, debezium-core/src/main/java/io/debezium/pipeline/spi/OffsetContext.java, debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java
https://issues.jboss.org/browse/DBZ-720
Hey @jpechane, so here's the actual data snapshotting implementation. `HistorizedRelationalSnapshotChangeEventSource` defines a variety of hooks to be implemented by connector-specific sub-classes. I tried to make the overall flow in `execute()` somewhat generic, but of course it's driven by the needs for Oracle. I suppose we'll have to make some adjustments to make it work with other implementations, too, but we have to start somewhere :)
It's based on top of #569, only the last commit is new.
=> DBZ-720 Generic RDBMS snapshotting

debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
https://issues.jboss.org/browse/DBZ-801
@jpechane Ok, so for now I didn't specify that `ChangeEventQueue` should only accept `DataChangeEvent` and nothing else. The reason being that the a loop within `poll()` is needed to get the `List<ChangeRecord>`. That's not great indeed. The event dispatcher currently expects `DataChangeEvent`, though, so I cleaned it up there a bit. Probably worth re-visiting this entire topic later on, but it's not urgent right now.
=> DBZ-801 Parameterizing ChangeEventQueue<DataChangeEvent>

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-core/src/main/java/io/debezium/heartbeat/Heartbeat.java, debezium-core/src/main/java/io/debezium/heartbeat/HeartbeatImpl.java, debezium-core/src/main/java/io/debezium/heartbeat/OffsetPosition.java, debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java, debezium-core/src/main/java/io/debezium/pipeline/spi/OffsetContext.java
https://issues.jboss.org/browse/DBZ-800
@jpechane So I think this could be enough actually to add the heartbeat to Postgres and Oracle/SQL Server. En passent, this will also resolve the original issue of not committing offsets for a longer time if no whitelisted table receives changes.
I'm unsure about testing, though. Do you see any viable approach other than some manual verification?
=> DBZ-800 Add heartbeat events to postgres connector

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java
Initial synchronization of MongoDb connector is not interrupted by stopping task.
This PR adds the following condition in the `while` loop:
```
while (running.get() && cursor.hasNext())
```
https://issues.jboss.org/browse/DBZ-838
=> DBZ-838 Adding condition to interrupt initial sync if task is stopped

debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
- Fix kafka database history storage miscount attemp number even if there are more records to consume.
https://issues.jboss.org/browse/DBZ-853
=> DBZ-853 Fix kafka database history storage miscount attemp number even if there are more records to consume.

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/AbstractMySqlConnectorOutputTest.java
1. Removed the unused param sql for the read system variables methods
2. Extract the duplicate block from the two read system variables methods into a reusable method
3. Extract the sql statement to be a field static final variable
=> DBZ-849 Refact read mysql sytem variables methods to make them more readable

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
https://issues.jboss.org/browse/DBZ-820
method isGtidModeEnabled when to check gtid mode ,it'll always be true
=> DBZ-820 Fix GtidModeEnabled method check gtid mode will always be true

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDefaultValuePreConverter.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/AbstractMysqlDefaultValueTest.java
https://issues.jboss.org/browse/DBZ-901
=> DBZ-901 Handle default date/time values without micros

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java, debezium-core/src/main/java/io/debezium/util/Collect.java, debezium-core/src/test/java/io/debezium/util/CollectTest.java
https://issues.jboss.org/browse/DBZ-899
@jpechane I think I've found an acceptable solution which avoids hard-coding the core types' names.
=> DBZ-899 Bypass n+1 problem in Postgres JDBC metadata

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Module.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/Module.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/Module.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SourceInfoTest.java, debezium-core/src/main/java/io/debezium/connector/AbstractSourceInfo.java
This will allow consumers to recognize the Debezium connector used for creating a given message, helping them to adjust their behavior for a variety of connectors.
https://issues.jboss.org/browse/DBZ-918
=> DBZ-918 Adding Debezium connector field to source info

.travis.yml, COPYRIGHT.txt, debezium-connector-postgres/pom.xml, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresConnectionIT.java
This PR adds support for temporary replication slots if Postgres >= 10 is used and `slot.drop_on_stop` is enabled. This ensures that the slot is dropped even if the debezium connector is shutdown ungracefully or communication is not possible anymore because of a network outage.
I've added a `postgres-10` build profile which can be used to execute the tests with a Postgres 10 instance.
Documentation on temporary replication slots: https://www.postgresql.org/docs/10/static/protocol-replication.html#PROTOCOL-REPLICATION-CREATE-SLOT
=> DBZ-934 Temporary replication slots with Postgres >= 10

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/MongoDataConverter.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/UnwrapFromMongoDbEnvelope.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/MongoDataConverterTest.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/UnwrapFromMongoDbEnvelopeTest.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/UnwrapFromMongoDbEnvelopeTestIT.java, debezium-core/src/main/java/io/debezium/transforms/UnwrapFromEnvelope.java, debezium-core/src/test/java/io/debezium/transforms/UnwrapFromEnvelopeTest.java
This PR packs together multiple DBZ issues, since the code being changed is almost always the same I had to stack many PRs, thus this new approach.
**Important** Please [review by commit](https://github.com/debezium/debezium/pull/682/commits), check commit messages and if necessary also check the related PR below, thanks!
You can go to the PRs and tickets for full context since many discussions happened already
- [DBZ-612](https://issues.jboss.org/browse/DBZ-612) Support `$unset` operator: #669 
- This entails in supporting `$rename`, `$unset` and other mongo queries
- Null values support is required to achieve this
- [DBZ-987](https://issues.jboss.org/browse/DBZ-987) Support full document updates: #679 
- [DBZ-989](https://issues.jboss.org/browse/DBZ-989) Support tombstone messages …
=> DBZ-612 DBZ-987 DBZ-989 DBZ-563 DBZ-971 MongoDB bug fixes  

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
With this fix all messages with replica identity full will be processed and emitted as events even if they do not have primary keys. 
Before that all messages without PK has been discarded despite they could have all necessary data in the 'before' and 'after' parts.
=> DBZ-1029 handling messages from tables with replica identity full in postgres connector

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java, debezium-embedded/src/main/java/io/debezium/embedded/StopConnectorException.java, debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java
https://issues.jboss.org/browse/DBZ-1080
This introduces a new API to the EmbeddedEngine, the ChangeConsumer,
which gives the user a more flexible option for consuming changes by
exposing groups of records as well as the ability to control the
comitting of those records.
This remainds completely backwards compatible with the old API as the
ChangeConsumer wraps the existing Consumer interface with a default
implementation.
=> DBZ-1080 new API for EmbeddedEngine for batch/async

.travis.yml, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/Lsn.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/Nullable.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceInfo.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerOffsetContext.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/TxLogPosition.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
https://issues.jboss.org/browse/DBZ-1090
Please see the linked issue. The problem is that LSN of each change is monotonically increasing inside transaction abut not accross transactions. I guess this huppens with concurrent transactions. So to get total ordered position we need to combine both commit LSN and change LSN and do comparison by it.
For this a new class `TxPositionLog` is introduced that effecivelly combines twose two LSNs and introduces ordering based first on commit LSN and then on change LSN.
=>  DBZ-1090 Change position consists of commit LSN and change LSN

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/MessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/NonStreamingWal2JsonMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/StreamingWal2JsonMessageDecoder.java
https://issues.jboss.org/browse/DBZ-1083
@jpechane, so this passes the "include-unchanged-toast" option only for wal2json but not for decoderbufs. ``MessageDecoder``s have a way now to provide optional "try once" options, which is used by wal2json for that purpose.
=> DBZ-1083 Passing "include-unchanged-toast" option only for wal2json

COPYRIGHT.txt, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDdlParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDdlParserTest.java, debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
Currently MySqlDdlParser does not support adding multiple partitions in a single ALTER TABLE ... ADD PARTITION statement. It restricts that only a single partition can be added. Given it is a valid mysql command, the parser should support this as well.
For example:
It supports:
```
ALTER TABLE test ADD PARTITION (
PARTITION p1 VALUES LESS THAN (10)
);
ALTER TABLE test ADD PARTITION (
PARTITION p2 VALUES LESS THAN MAXVALUE
);
```
But it does not support:
```
ALTER TABLE test ADD PARTITION (
PARTITION p1 VALUES LESS THAN (10),
PARTITION p2 VALUES LESS THAN MAXVALUE
);
```
=> [WIP] DBZ-1113 allow adding multiple partitions in a single statement

COPYRIGHT.txt, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/junit/SkipTestDependingOnDatabaseVersionRule.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/junit/SkipWhenDatabaseVersionLessThan.java, debezium-core/src/test/java/io/debezium/junit/AnnotationBasedTestRule.java
When the postgres snapshot producer's `generateReadRecord` method is invoked, it must clear any existing value in `currentRecord`.  If it does not, and the method ends up returning early without setting a new value, the prior record is resent.
As detailed in https://issues.jboss.org/browse/DBZ-1118 this can occur when using postgres table partitions.  Since the parent partition table definition does not contain primary keys, when the base table is processed (e.g. `select * from base_partition`) the `generateReadRecord` method always ends up aborting early like this since the `key` object is `null`:
```
Object key = tableSchema.keyFromColumnData(rowData);
Struct value = tableSchema.valueFromColumnData(rowData);
if (key == null || value == null) {
return;
}
```
Before this patch the …
=> DBZ-1118 Postgres snapshot - On null records, clear prior value

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/wal2json/ISODateTimeFormatTest.java
Tests at io.debezium.connector.postgresql.connection.wal2json.ISODateTimeFormatTest fail with a Locale "es_ES".
We fix it setting "Before Current Era" display value to the appropriate one depending on the environment default locale.
=> DBZ-1126 Localize era display value to default locale

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationConnection.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/junit/SkipTestDependingOnDecoderPluginNameRule.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/junit/SkipWhenDecoderPluginNameIs.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/junit/SkipWhenDecoderPluginNameIsNot.java
Added config param "slot.stream_params" to the Postgres connector to allow passing optional params to logical decoder on stream start.
The format is key and values are separated by "=" and key value pairs are separated by ";". So for example "add-tables=public.table,public.table2;include-lsn=true'" would be the equivalent of passing "-o add-tables=public.table,public.table2 -o include-lsn=true" when streaming from the replication slot manually with pg_recvlogical etc.
I have this change (based of the latest 9.0 release) running against a PG server with the WAL2JSON decoder and the optional param to filter tables is working.
=> Config option to pass optional logical decoder stream params

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-connector-sqlserver/src/test/resources/log4j.properties, debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java, debezium-core/src/main/java/io/debezium/relational/TableSchema.java, debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
Within `convertHstoreToJsonString`, during the snapshot, column values arrive as HashMaps, rather than byte arrays or strings. This code checks for fixes that circumstance. 
A couple of notes: 
* There's a lot of debug statements in here, which I was using to introspect the values (I'm using vim as my code editor, rather than an IDE). I'm happy to remove all of these if you all wish.
* I haven't coded in java regularly in about a decade, just fyi 😛
* I am unclear as to whether the `data` object arriving in `convertHstoreToJsonString` _should_ be a HashMap. Some cursory investigation seemed to reveal that HashMap<String, String> is type [returned via the JDBC driver](https://stackoverflow.com/questions/35013800/postgres-hstore-casting-works-wrong)
=> DBZ-1162 - fix for HStore snapshot vs streams

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
[DBZ-1177](https://issues.jboss.org/browse/DBZ-1177)
- The previous statement was never achievable since `ReplicaSets.parse(hosts)` can never return null
- Also removed some code duplication for better readability
=> DBZ-1177 Improve MongoDB hosts validation

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/NonStreamingWal2JsonMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/StreamingWal2JsonMessageDecoder.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.jboss.org/browse/DBZ-1181
PR to add support to the process events from wal2json that have no changes in them. Logic has been added for both streaming and non-streaming versions.
=> DBZ-1181 - Process WAL2JSON Events with Empty Changes

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ServerInfo.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/AlwaysSnapshotter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/InitialOnlySnapshotter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/InitialSnapshotter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/NeverSnapshotter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/QueryingSnapshotter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/spi/OffsetState.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/spi/SlotState.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/spi/Snapshotter.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/CustomTestSnapshot.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SnapshotWithOverridesProducerIT.java, debezium-core/src/main/java/io/debezium/annotation/Incubating.java, debezium-core/src/main/java/io/debezium/time/Conversions.java, debezium-core/src/main/java/io/debezium/util/Clock.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
This commit does a few things:
- Refactors snapshot modes to be encapsulated by an interface and
to only use that interface in determining when to snapshot and in
determing the type of the `RecordProducer` interface to instantiate
- Refactors the configuration of existing snapshot modes to tie the
existing snapshot modes to their aligned implementation
- Adds a new snapshot.mode, custom, and a new configuration option to
specify a custom implementation that will be loaded by the class loader
- Changes the visibility of some classes to allow for custom snapshot
modes to get enough context to make an informed choice
- Adds some metadata about slots (the catalog_xmin) to give a full idea
of the state of slots which can be useful in implementing snapshot
modes (which is also configurable, as …
=> DBZ-1082 Add new custom recovery mode, more metadata

debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
The following error was encountered while bootstrapping a new table with the MySQLConnector.
```
March 30th 2019, 10:06:27.881 [2019-03-30 17:06:27,880] ERROR WorkerSourceTask{id=dbz-monolith-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
March 30th 2019, 10:06:27.882 org.apache.kafka.connect.errors.ConnectException: Error reading MySQL variables: The last packet successfully received from the server was 171,318,974 milliseconds ago. The last packet sent successfully to the server was 171,318,978 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client …
```
=> DBZ-1207 MySQL connection timeout after bootstrapping a new table

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetricsMXBean.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderIT.java, debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java, debezium-core/src/main/java/io/debezium/pipeline/metrics/ChangeEventSourceMetricsMXBean.java, debezium-core/src/main/java/io/debezium/pipeline/metrics/Metrics.java, debezium-core/src/main/java/io/debezium/pipeline/source/spi/DataChangeEventListener.java
For [DBZ-1206](https://issues.jboss.org/browse/DBZ-1206) and [DBZ-1209](https://issues.jboss.org/browse/DBZ-1209)
MySQL binlog connector currently exposes the ability to filter events based on database name (database.whitelist, database.blacklist), by table name (table.whitelist, table.blacklist), and/or by column name (column.blacklist). Currently when a record is filtered based on these criteria, it is exposed by a debug log statement, but no corresponding metric is exposed.
Other debezium connectors expose how many events were filtered due to whitelist/blacklist configuration by using the "numberOfSkippedEvents" metric.  The MySQL Debezium connector currently uses the "numberOfSkippedEvents" metric to represent how many MySQL binlog events were unparsable by the underlying …
=> [DBZ-1206][DBZ-1209] Add/rename metric numberOfSkippedEvents -> numberOfFilteredEvents

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetrics.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetricsMXBean.java
For [DBZ-1221](https://issues.jboss.org/browse/DBZ-1221) 
Currently debezium-mysql-connector indirectly exposes if the underlying binlog client is using GTIDs to maintain its position from MySQL via the GtidSet and SourceEventPosition metrics.
Rather than indirectly infer if the connector is using Gtids by presence or absence of values in these metrics, it'd be nice if the connector directly exposed this via a metric like:
`boolean getIsGtidModeEnabled();`
=> [DBZ-1221] create new metric getIsGtidModeEnabled

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PgOid.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoReplicationMessage.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/Wal2JsonReplicationMessage.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
https://issues.jboss.org/browse/DBZ-1193
Add supoorts for network types `CIDR`, `MACADDR`, `MACADDR8`.
DDL (PostgreSQL 9.6): 
```
CREATE TABLE inventory.network (pk SERIAL, i INET, c CIDR, m MACADDR, PRIMARY KEY(pk));
```
DDL (PostgreSQL 10 and 11):
```
CREATE TABLE network_address_table (pk SERIAL, i INET, c CIDR, m MACADDR, m8 MACADDR8, PRIMARY KEY(pk));
```
DML (PostgreSQL 9.6): 
```
INSERT INTO inventory.network VALUES (1001, '192.168.2.0/12', '192.168.100.128/25', '08:00:2b:01:02:03');
```
DDL (PostgreSQL 10 and 11):
```
INSERT INTO network_address_table (i, c, m, m8) VALUES ('192.168.2.0/12', '192.168.100.128/25', '08:00:2b:01:02:03', '08:00:2b:01:02:03:04:05');
```
Before Patch:
```
{
"schema": {
"type": "struct",
"fields": [
{
"type": "int32",
"optional": false,
"field": "pk"
}
], …
```
=> [DBZ-1193] Add support for network type MACADDR and MACADDR8 in PostgreSQL connector

debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java, jenkins-jobs/mysql-matrix-test.yaml
1) Jenkins slaves in http://ci.hibernate.org have a MySQL server already running at port 3306 (probably with root permissions).
2) SourceTaskContext#configs() wasn't present in Kafka API v1.x, thus removing @Override annotation
=> Updated MySQL connector Jenkins job to use custom ports for MySQL

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SourceInfoTest.java
@gunnarmorling Could you verify if this change doesn't break the [DBZ-1082](https://github.com/debezium/debezium/commit/8e21139ca3ee140a07b99cbfb87b6a92b1253308#diff-f28bb7eecf710b4c4de5235a03902776R181)?
=> DBZ-1241 - allow null values again for commitTime

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Replicator.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java, debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalSnapshotChangeEventSource.java
The `documents.fetch.size` configuration property is an positive integer value that specifies the maximum number of documents that should be read in one go from each collection while taking a snapshot. The connector will read the collection contents in multiple batches of this size. Default to `0`, which indicates that the server chooses an appropriate fetch size.
https://issues.jboss.org/browse/DBZ-1247
=> DBZ-1247 Adding property to specify snapshot fetch size

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationStream.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
This adds a small change to the postgres connector which
works around a problem when large databases take more
than a minute to refresh the schema
This works by creating a simple background thread that ensures we send
statusUpdate messages periodically
I considered if we could refresh the schema before we create the
replication connection but I believe we choose our offset in the log
and then get the schema in order to ensure we don't get out of sync with
any potential schema changes
=> [DBZ-1214] Ensure PG connection keep alive

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
A connection to SQL server with client-side SSL authentication (like Google Cloud SQL) cannot be established.
The issue is caused because of the [shutdown method](https://github.com/debezium/debezium/blob/7748be6056bb84edf77f63ad979e0bd61917f7d0/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnector.java#L107) being called here. This is why the connection test succeeds, but fails later. The next time when debezium attempts to connect to the database [here](https://github.com/debezium/debezium/blob/7748be6056bb84edf77f63ad979e0bd61917f7d0/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java#L286), these variables are not set and the connection fails.
We can set the system variables before the call is made. Since the [start …
=>  DBZ-1228: MySQL connection with client authentication does not work

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MetadataIT.java, pom.xml
From https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-16.html
> In the DatabaseMetaDataUsingInfoSchema interface, the getProcedureColumns() and getFunctionColumns() methods returned wrong results for the PRECISION column, and the getColumns() and getVersionColumns() methods returned wrong results for the COLUMN_SIZE column. The errors were due to the wrong handling of the temporal type precision by Connector/J, which has now been fixed. (Bug #29186870)
Mongo was bumped only to latest 3.9 release due to things breaking with 3.10.x -- since we are currently using a deprecated release distribution I will create Jira to upgrade to the latest driver (reactive might provide better performance, sync one  will have easier migration)
=> [DBZ-1273] Bumping JDBC and Mongo driver versions

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
https://issues.jboss.org/browse/DBZ-1353
Compare with ignored whitespaces.
=> DBZ-1353 MySQL 8 returns null for unspecified timestmap column

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
In order to use the MySQL heartbeat feature to enable keeping the connections, I set the variable named heartbeatInterval of the class BinaryLogClient with a number less than keepaliveInterval in the BinlogReader constructor. Then, the debezium connector will receive the heartbeat packet from the MySQL server and find the connection problem under heartbeatInterval ms.
=> DBZ-1338 Support for ensuring keepalive by using MySQL heartbeat

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsSnapshotProducer.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/RecordsStreamProducer.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/InitialSnapshotter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/SnapshotterWrapper.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/spi/SlotCreationResult.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/spi/SlotState.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/spi/Snapshotter.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/CustomTestSnapshot.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/OutboxEventRouterIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SnapshotWithOverridesProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresConnectionIT.java
https://issues.jboss.org/projects/DBZ/issues/DBZ-1238
This commit adds some more options to the Postgres Snapshottter SPI
interface, specifically, the ability to create the query for the start
of a snapshot, as well as the ability to generate a statement to lock
the tables.
Additionally, some rework is done to allow for the usage of an exported
snapshot in conjuction with the SPI taking metadata about a newly
created slot. This also changes how slots are initialized to allow for
the exported snapshot to be referenced, which requires adding a more
granular setup of a ReplicationConnection
Together, these options allow for a lot more flexibility, such as not
taking locks when snapshotting large databases as well as potentially to
use exported snapshots.
A future version should perhaps make …
=> DBZ-1238 Allow more options for snapshot SPI

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/OutboxEventRouterIT.java, debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java, debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterConfigDefinition.java
https://issues.jboss.org/browse/DBZ-1385
Current implementation expects that evetn type is mapped to field named `eventType`. If it is the case the configuration is completely taken from additional fields. If such add field does not exist then `eventType` field is added to payload.
Complete backward compatibility is ensured. `eventType` field is always first in the message struct.
=> DBZ-1385 eventType can be configured as add field

debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java, debezium-core/src/test/java/io/debezium/transforms/ExtractNewRecordStateTest.java
We are using the CDC connector to replicate into S3 and I noticed that delete rewrites are not receiving the source fields added to their rewrite message when specified. This was causing the records to be written to S3 with essentially 2 schemas. Inserts and updates did receive the source fields and the order of the message was {original_fields, source_fields, __deleted}. Deletes came through like {original_fields, __deleted}. This fix puts the source fields back into delete rewrites in the correct order so messages have a consistent schema regardless of transaction type.
=> DBZ-1448 Source fields for rewrite

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
https://issues.jboss.org/browse/DBZ-1457
@gunnarmorling I couldn't really write a test, it was really hard to find a scenario where the task is started and the `coordinator` has value but no offset in here: https://github.com/debezium/debezium/blob/f4246df6e436343b3c08080452be92542ad39859/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java#L182
I tried some things, check the last commit, maybe you have a tip for me, otherwise let me know if I should remove the test or what to do! Thanks
Update: I've remove the test commit, here is how the code looked like:
```java
@Test
@FixFor("DBZ-1457")
public void shouldNotThrowExceptionWhenACommitIsAttemptedWithoutOffsets() {
Configuration config = TestHelper.defaultConfig().build(); …
```
=> [DBZ-1457] Fix NPE when trying to commit without offsets

documentation/modules/ROOT/pages/connectors/mysql.adoc
Should solve the issue with this exception when pointing to a RDS MySQL read replica:
```
Caused by: java.lang.IllegalStateException: Cannot read the binlog filename and position via 'SHOW MASTER STATUS'. Make sure your server is correctly configured
at io.debezium.connector.mysql.SnapshotReader.lambda$readBinlogPosition$16(SnapshotReader.java:761)
at io.debezium.jdbc.JdbcConnection.query(JdbcConnection.java:444)
at io.debezium.jdbc.JdbcConnection.query(JdbcConnection.java:385)
at io.debezium.connector.mysql.SnapshotReader.readBinlogPosition(SnapshotReader.java:745)
at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:370)
```
Will open up another PR in the FAQ repo with the stack trace and more details, if it makes sense.
=> Adds warning for 'bin_log' property in RDS MySQL

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/OutboxEventRouterIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PublicGeometryIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
https://issues.jboss.org/browse/DBZ-1383
This is a first pass at addressing test stability for the PostgreSQL connector.  There are further changes I'm looking into but this at least addresses a few of the known tests so far that fail randomly.
=> DBZ-1383 Fix PostgreSQL tests that fail intermittently

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/MessageDecoderConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
https://issues.jboss.org/browse/DBZ-1436
This should resolve the lingering hardcoded values and fixes the test to verify that the publication we expected is actually created in the database.
=> DBZ-1436 Fix postgres connector not honoring configured `publication.name` setting

.travis.yml, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/ToastedReplicationMessageColumn.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/MessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoReplicationMessage.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/NonStreamingWal2JsonMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/StreamingWal2JsonMessageDecoder.java, debezium-connector-postgres/src/main/proto/pg_logicaldec.proto, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DecoderDifferences.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.jboss.org/browse/DBZ-1367
https://issues.jboss.org/browse/DBZ-1368
https://issues.jboss.org/browse/DBZ-1399
Depends on https://github.com/debezium/postgres-decoderbufs/pull/20
The code now expects that bot pgoutput and protobuf signals fields that contain unchanged toasted values. wal2json with `columns_diff_exclude_unchanged_toast` supposes that missing toasted column means exactly the same thing.
The code replaces missing value with a string or binary placeholder. In case of update messages when non-toasted column is updated the PR will read old toasted value if available in the message and write it into the new value instead of placeholder.
=> DBZ-1367 DBZ-1368 DBZ-1399 Toasted column not read out-of-bands

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
https://issues.jboss.org/browse/DBZ-1532
=> DBZ-1532 Pgoutput string decoding should not rely on JVM default charset

documentation/modules/ROOT/pages/connectors/postgresql.adoc
@gunnarmorling ok, it seems that as a by-product of copy/paste the documentation of all connectors already mentioned unique key constraint to be source of key fields. I've added to the postgres only note about necessity to use REPLICA IDENTITY USING INDEX on the table.
Also the other parts of the text you've refered to in postgres documentation ar still valid as they speak of limitations of decoder plugins ntot connector itself.
=> DBZ-1401 Document REPLICA IDENTITY for unique key on postgres

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/FiltersTest.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SpecialCharsInNamesIT.java, debezium-core/src/main/java/io/debezium/util/Strings.java
The table whitespace parameter should remove whitespace between regular expressions
since tables cannot start with whitespace characters.
https://issues.jboss.org/browse/DBZ-1546
=> DBZ-1546 Remove whitespaces between table.whitelist regexes

.travis.yml
We have less workers than builds so the slowest should run first
=> [CI] Order builds by build time

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.jboss.org/browse/DBZ-1570
=> DBZ-1570 handle null toasted values for wal2json

jenkins-jobs/job-dsl/README.md, jenkins-jobs/job-dsl/kafka_1_x_test.groovy, jenkins-jobs/job-dsl/monfodb_matrix_test.groovy, jenkins-jobs/job-dsl/mysql_matrix_test.groovy, jenkins-jobs/job-dsl/postgresql_matrix_test.groovy
https://issues.jboss.org/browse/DBZ-1581
The first step of extending the jobs -- migration to Job DSL. This is required to be aligned (tool wise) with other QE teams. 
Right now these are direct copies of what we have. however will be further expanding these definitions in future PRs.
=> DBZ-1581 Job DSL

documentation/modules/ROOT/pages/tutorial.adoc
I've followed the tutorial and I got to the step when we had to delete a customer.
When running:
```
DELETE FROM customers WHERE id=1004;
```
I got back:
```
ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`inventory`.`addresses`, CONSTRAINT `addresses_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`))
```
So I added some instructions on deleting this entry first before continuing.
=> [tutorial] Added missing step when deleting customers

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/OutboxEventRouterIT.java, debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java, debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
- kafka topics names are case sensitive. We should not perform
a toLowerCase on the topic name. It can cause some issue if
topic name have a upper case
=> DBZ-1648 outbox EventRouter remove topic toLowerCase 

documentation/modules/ROOT/pages/_attributes.adoc, documentation/modules/ROOT/pages/configuration/outbox-event-router.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/index.adoc
This commit adjusts the JIRA references such that we introduced a new jira-url
Ascidoc attribute which now points to issues.redhat.com rather than using full
url references across all pages to the same host.
=> Adjusting JIRA references to issues.redhat.com

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc
Ref: https://issues.redhat.com/projects/DBZ/issues/DBZ-1671
Adds `lock_wait_timeout` to Mysql Connector Snapshot Reader. Enables the use of Debezium on tables with a large number of additional clients competing for table locks. 
Some more context on this issue; we're currently testing running Debezium in a high concurrency environment, where our LWTO is set very low (to avoid outages if someone attempts to lock a busy table), we'd like to be able to tune the setting back up for the single case of snapshotting.
=> DBZ-1671 Adding configurable lock_wait_timeout for mysql connector 

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationMessageColumnValueResolver.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoColumnValue.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.redhat.com/browse/DBZ-1680
This fix applies to the scenario where include.unknown.datatypes is disabled and
the decoder is pgoutput or wal2json as decoderbufs was unaffected.
=> DBZ-1680 Fix enum value resolution across all PostgreSQL decoders

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
https://issues.redhat.com/browse/DBZ-1684
This should be the final fix hopefully, which guarantees that the publication is always created prior to the replication slot regardless of when we create the replication slot.
=> DBZ-1684 - Always create publication prior to replication slot

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/OutboxEventRouterIT.java, debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java, debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
Depending on the width of the configured TIMESTAMP column, a microsecond or nanosecond timestamp could have been returned before, whereas this should always be milliseconds.
https://issues.redhat.com/browse/DBZ-1707
=> DBZ-1707 Ensuring correct Kafka record timestamp for outbox events;

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java
https://issues.redhat.com/browse/DBZ-1712
=> DBZ-1712 MySQL connector use default port when database.port option not specified

debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java, debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordStateConfigDefinition.java, debezium-core/src/test/java/io/debezium/transforms/ExtractNewRecordStateTest.java, documentation/modules/ROOT/pages/configuration/event-flattening.adoc
https://issues.redhat.com/browse/DBZ-1715
As explained in DBZ-1715 this SMT adds the ability to set a topic based on the field in the table this SMT is consuming. 
I've checked on the Gitter dev channel if this is potentially interesting for core and @Naros replied that it might be. I've added some basic tests, would like to know how much more testing coverage is required for this piece of code.
=> [DBZ-1715] Add route by field option for ExtractRecordState transformation

documentation/modules/ROOT/pages/_attributes.adoc, documentation/modules/ROOT/pages/architecture.adoc, documentation/modules/ROOT/pages/docker.adoc, documentation/modules/ROOT/pages/integrations/outbox.adoc, documentation/modules/ROOT/pages/modules/cdc-mysql-connector/c_how-the-mysql-connector-performs-database-snapshots.adoc
This restores the functionality of Antora to pick images from the assets/images folder automatically.
It also changes some Markdown style headings to AsciiDoc style. 
Creating the site locally the images are now showing correctly:
=> DBZ-1725 fix broken images in documentation

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
This change allows proxied postgres connections to be used by the connector. 
[io.debezium.connector.postgresql.TypeRegistry](https://github.com/debezium/debezium/blob/c32b771e1b6a545208d1df3c5615bf754d5c3140/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java#L312) already casts connections to BaseConnection but in these other files it is being cast to PgConnection. Java Proxies can be cast to interfaces but not to concrete classes so those break if the connection is being proxied.
See https://issues.redhat.com/browse/DBZ-1738 for more information. 
I couldn't see any clear way to add a test for this based on the existing test, but I'm open to suggestions.
=> DBZ-1738 replaced casts to PgConnection with interface BaseConnection

documentation/modules/ROOT/pages/connectors/cassandra.adoc
Cassandra Connector has been using Kafka Connect Schema instead of Avro Schema for a while, replacing inaccurate "Avro" with "Kafka Connect" in the doc.
=> Replace inaccurate "Avro" with "Kafka Connect" for Cassandra Connect.

debezium-core/src/main/java/io/debezium/converters/CloudEventsMaker.java, debezium-core/src/test/java/io/debezium/converters/CloudEventsConverterTest.java, documentation/modules/ROOT/pages/integrations/cloudevents.adoc
https://issues.redhat.com/browse/DBZ-1784
see spec: https://github.com/cloudevents/spec/blob/85e5df9f35faeb2913766343ec878bdfb07b39aa/kafka-protocol-binding.md#325-example
/assign @slinkydeveloper
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
=> For avro, the spec says that we wanna use 'application/avro'

documentation/modules/ROOT/pages/operations/openshift.adoc
maven seems to require https and also central.maven.org does not appear to be a valid hostname according to whatsmydns.  repo1 might bypass some cdn/load balancer but at least it works!
=> Change maven.org address in script

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationStream.java
https://issues.redhat.com/browse/DBZ-1840
Note this means to that WAL offsets cannot be acknowledged in cases
where a null message is received from the server (e.g. wal2json for
DDL events). But as we cannot tell apart null events from the server
from readPending() simply having no events to read, the current
logic renders the pausing between two read calls without events
obsolete, so that's the lesser evil
@jpechane, @Naros, still doing some more testing, but pushing it here for feedback. Best review ignoring whitespace changes. Thx!
=> DBZ-1840 Re-instantiating pausing between readPending() calls without event

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-testing/debezium-testing-openshift/src/test/resources/database-resources/mysql/deployment.yaml, debezium-testing/debezium-testing-openshift/src/test/resources/database-resources/postgresql/deployment.yaml
Fixed typos in the YAML. An unnecessary call to TimeUnit has also been removed.
=> NO-JIRA: Typos in deployment.yaml and code readability

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlSourceTypeInSchemaIT.java, debezium-core/src/main/java/io/debezium/function/Predicates.java, debezium-core/src/main/java/io/debezium/relational/mapping/ColumnMappers.java, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
https://issues.redhat.com/browse/DBZ-1830
This change provides support for the new connector property
```
datatype.propagate.source.type
```
to propagate the column data type as a parameter to the corresponding field schemas in the emitted change messages. The expected value is a comma-separated list of database-specific type names,  fully qualified with DB schema and table names, in example:
```
db1.table1.VARCHAR,db1,table1.INT,db1.table2.TIMESTAMP
```
regular expressions are allowed, in example:
```
db1\..*\.VARCHAR,.*\.INT
```
=> DBZ-1830 new connector property datatype.propagate.source.type

COPYRIGHT.txt, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, documentation/modules/ROOT/pages/connectors/mongodb.adoc
https://issues.redhat.com/browse/DBZ-1831
This PR supersedes https://github.com/debezium/debezium/pull/1294 and is based on the work that is in PR https://github.com/debezium/debezium/pull/1316.  
@gunnarmorling Would it make more sense for me to cherry-pick the final commit into PR #1294 or is it sufficient that we merely rebase this once PR #1294 has been merged to master?
=> DBZ-1831 Support MongoDB Oplog operations as config

documentation/modules/ROOT/pages/configuration/event-flattening.adoc, documentation/modules/ROOT/pages/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
With this change, if the "cdc-product" attribute it set (as in the downstream), the deprecated content will not appear in the output. If "cdc-product" is not set (as in the upstream), the deprecated content will appear in the content.
=> DBZ-1829 Conditionalize deprecated options for downstream doc

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
https://issues.redhat.com/browse/DBZ-1863
Small follow-up based on the changes to `BaseSourceTask` to handle the coordinator lifecycle in one place.
=> DBZ-1863 Centralizing coordinator shutdown

documentation/modules/ROOT/pages/assemblies/logging/as_configuring-logging.adoc, documentation/modules/ROOT/pages/modules/logging/c_logging-concepts.adoc, documentation/modules/ROOT/pages/modules/logging/c_understanding-default-logging-configuration.adoc, documentation/modules/ROOT/pages/modules/logging/p_adding-mapped-diagnostic-contexts.adoc, documentation/modules/ROOT/pages/modules/logging/p_changing-logging-level.adoc, documentation/modules/ROOT/pages/modules/logging/p_configuring-log-level-docker.adoc, documentation/modules/ROOT/pages/operations/logging.adoc
This PR modularizes the logging doc so that it can be reused in the downstream doc. 
To be clear, the Docker-related procedure (p_configuring-log-level-docker.adoc) is upstream-specific, so it will not be included in the downstream doc.
I will create a separate PR to cherry-pick this to 1.0.
=> DBZ-1861 Modularize the logging doc

documentation/modules/ROOT/pages/connectors/postgresql.adoc
Removed the tech preview notices from the Postgres connector doc, which is GA for the 1.0 GA downstream release.
=> DBZ-1651 Remove tech preview notice from postgresql.adoc

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
This is follow-up to https://github.com/debezium/debezium/pull/1351
There were two problems
- the heartbeat table shodul be created in advance to starting the connector
- there was an exception complaining that heartbeat cannot write to database as the transaction is read-only
=> DBZ-1815 Use separatae conection for db heartbeat

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java, debezium-embedded/src/main/java/io/debezium/connector/simple/SimpleSourceConnector.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java, debezium-embedded/src/test/java/io/debezium/connector/simple/SimpleSourceConnectorOutputTest.java, debezium-embedded/src/test/java/io/debezium/embedded/ConnectorOutputTest.java, debezium-embedded/src/test/resources/simple/test/e/connector.properties, debezium-embedded/src/test/resources/simple/test/e/env.properties, debezium-embedded/src/test/resources/simple/test/e/expected-records.json
https://issues.redhat.com/browse/DBZ-1857
=> DBZ-1857 Support for autorestart for embedded engine

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbChangeRecordEmitter.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RecordMakers.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java, debezium-core/src/main/java/io/debezium/pipeline/spi/ChangeRecordEmitter.java, debezium-core/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/modules/cdc-mysql-connector/c_mysql-connector-events.adoc
DBZ-1531 added headers for primary key update events to reference the original key
Current state:
- implementation for the "new" relational* architecture (postgres and sqlserver) is done and unit tests added, but sqlserver is not capable
- MySQL server is done and tested
- MongoDB uses the default new Relational* architecture imlpementation, if it sends an UPDATE event that DBZ can recognize as PK update, then it should send the header. but I doubt that (based on the code) and also had no time to test this, so I expect it doesn't set the header.
- unit tests updated
- unit tests for postgres are green
- sqlserver doesn't support primary key upate recognition by debezium (it sends separate DELETE and INSERT events for a PK update and it looks like it doesn't carry the previous key in any …
=> DBZ-1531 added headers for primary key update events

debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/WaitConditions.java, debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/KafkaConnectController.java, debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/KafkaDeployer.java, debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/OperatorController.java, debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/ConnectorTestBase.java, debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/mysql/MySqlConnectorIT.java, debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/postgresql/PostgreSqlConnectorIT.java
The Connect crash is currently simulated by
- Disabling Kafka Operator by scaling it to ZERO
- Connect pods are then force deleted (grace period ZERO)
- Immediately after Connect deployment is scaled to ZERO -- this prevents new pod to fully start 
After that, we make a database insert and verify that the connector is indeed down.
In the last step, Operator is enabled again, given time to reconcile deployed Connect cluster and then we check for number of messages as well as "grep" for the inserted record by used email.
=> DBZ-1663 Resume tests after Connect crash in OpenShift for MySQL and PostgreSQL

documentation/antora.yml, documentation/modules/ROOT/pages/modules/cdc-mysql-connector/c_mysql-connector-events.adoc
This content was originally in 0.1, but got dropped from subsequent versions. This commit should be applied to 1.0 and later versions of the doc.
=> DBZ-1919 Restore create, update, delete event structure examples in doc

documentation/modules/ROOT/pages/connectors/cassandra.adoc
Adding a paragraph of doc to Cassandra Connector regarding how to manually trigger re-snapshot when a Cassandra table's cdc feature gets disabled then re-enabled.
Not actually related to DBZ-1927, but it is required to include a JIRA ticket in commit log.
=> [DBZ-1927] Add doc about Cassandra Connector

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.redhat.com/browse/DBZ-1954
Added `column.truncate.to._length_.chars` and `column.mask.with._length_.chars` properties to the documentaion of relational database connectors.
=> DBZ-1954 Add docs for mask column and truncate column features

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
https://issues.redhat.com/browse/DBZ-1950
This is the fix for bootstrapping Debezium with MySQL 5.5.
=> DBZ-1950 Make validation of binlog_row_image compatible with MySQL 5.5

documentation/modules/ROOT/nav.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_connector-common-issues.adoc, documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_deploy-the-mysql-connector.adoc, documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_overview-of-how-the-mysql-connector-works.adoc, documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_setup-the-mysql-server.adoc
This is a follow-up to #1405. I moved the last remaining assembly files to {partialsdir}/assemblies. I also changed the nav so that mysql.adoc includes each of the assemblies instead of xref-ing them. The result is that the MySQL connector doc is now presented on a single page, which is consistent with all of the other connectors.
=> NO-JIRA: Move mysql connector assemblies to partials

debezium-api/src/main/java/io/debezium/engine/DebeziumEngine.java, debezium-api/src/main/java/io/debezium/engine/format/Avro.java, debezium-api/src/main/java/io/debezium/engine/format/Change.java, debezium-api/src/main/java/io/debezium/engine/format/ChangeEvent.java, debezium-api/src/main/java/io/debezium/engine/format/CloudEvents.java, debezium-api/src/main/java/io/debezium/engine/format/Json.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DebeziumEngineIT.java, debezium-embedded/src/main/java/io/debezium/embedded/ConvertingEngineBuilder.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java, debezium-embedded/src/main/resources/META-INF/services/io.debezium.engine.DebeziumEngine$Builder, debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java
https://issues.redhat.com/browse/DBZ-1807
Documentation will be added when the code is approved
Open question - we need to provide offsets to the callback function `Committer.markProcessed()`
Current implementation intoruces opaque `Change.reference()` theat is used for this purpose so the user should not make any assumptions on offsets. The other option is to expose it as method `offset` with type `Map` so the users can assess the offsets.
To complement `Connect` format the latter is prefered, to tighten isolation the former is preferred.
=> DBZ-1807 Converters in Debezium engine

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetrics.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReaderMetricsMXBean.java, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-monitoring-metrics.adoc
https://issues.redhat.com/browse/DBZ-1947
This removes the obsolete metrics `SecondsSinceLastEvent` and `SecondsBehindMaster` from both the exposed JMX metrics as well as the MySQL connector documentation.
=> DBZ-1947 Remove obsolete MySQL metrics

documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_connector-common-issues.adoc, documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_deploy-the-mysql-connector.adoc, documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_overview-of-how-the-mysql-connector-works.adoc, documentation/modules/ROOT/partials/assemblies/cdc-mysql-connector/as_setup-the-mysql-server.adoc
This removes some attributes from the partials that interfered with generating the ToC properly.  This commit should likely also be cherry-picked back to the 1.0 branch as it exhibits the same behavior problems.
=> DBZ-1980 Only top-level menu items shown for MySQL connector

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/Filters.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/Filters.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java, debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java, debezium-core/src/main/java/io/debezium/relational/Tables.java, debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java, documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-1962
Right now the Debezium Postgres connector just supports `column.blacklist`. Added `column.whitelist` as well which might be convenient in some cases.
=> DBZ-1962 Introduce column.whitelist for the Postgres connector

documentation/antora.yml, documentation/modules/ROOT/partials/assemblies/tutorial/as_viewing-change-events.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_how-the-mysql-connector-maps-data-types.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_how-the-mysql-connector-performs-database-snapshots.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_mysql-connector-events.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_configure-the-mysql-connector.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_create-a-mysql-user-for-cdc.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-monitoring-metrics.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-purges-binlog-files.adoc, documentation/modules/ROOT/partials/modules/tutorial/r_watching-connector-start-up.adoc
Updated several xrefs so that the links will not break in the downstream doc. In addition, I cleaned up some of the MySQL connector doc xrefs; now that all of the MySQL connector doc is presented on a single page on the Antora site, the xrefs do not need to point to the full path of the target.
=> NO-JIRA: update doc xrefs to work downstream

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
https://issues.redhat.com/browse/DBZ-1949
When converting Postgres bit varying column, convert to byte array
instead of short/int/long to handle cases where the value is larger than
Long.MAX_VALUE
=> DBZ-1949 Return BitSet instead of short/int/long

debezium-connector-mongodb/pom.xml, debezium-connector-mysql/pom.xml, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java, debezium-embedded/pom.xml, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java, pom.xml
https://issues.redhat.com/browse/DBZ-2027
=> DBZ-2027 Upgrading Postgres JDBC driver to 42.2.12

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresType.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java
This attempts to factor out a lot of duplicated logic that I noticed when working on my last PR. There is currently a lot of logic duplicated when querying for array vs non-array types. There's also a lot of duplicated logic when priming the initial type registry vs resolving an unknown type later. These changes try to consolidate all of that and have the added benefit of producing fewer queries to Postgres.
https://issues.redhat.com/browse/DBZ-2038
=> DBZ-2038 Refactor Postgres TypeRegistry

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
https://issues.redhat.com/browse/DBZ-1969
This is the last portion of this issue to add support for these time-based array data types.
=> DBZ-1969 Add array support for time, timetz, timestamp, and timestamptz

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java, debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
Debezium will currently throw an error if a table is created with the syntax below which is completely valid:
```CREATE TABLE foo ( c1 INTEGER NOT NULL ) engine=TokuDB `compression`=tokudb_zlib;```
This would **not** throw an error however
```CREATE TABLE foo ( c1 INTEGER NOT NULL ) engine=TokuDB compression=tokudb_zlib;```
This PR addresses the issue described above, however I'm not extremely familiar with ANTLR so if there's a better way to accomplish this, please let me know and I will make updates. Thanks!
=> DBZ-2062 allowing compression keyword to contain backticks in create table for MariaDB

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java, debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4, debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql
https://issues.redhat.com/browse/DBZ-2067
Updated Antlr grammar to support `ALGORITHM=INSTANT` on alter table statements.
=> DBZ-2067 Add support for ALGORITHM=INSTANT on alter table statements

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
https://issues.redhat.com/browse/DBZ-775
This PR introduces all documentation changes relevant to column masking/truncation in addition to clarifying the format used for message key columns configurations.  
There is a parallel PR in the incubator repository that should be merged in tandem with this.
=> DBZ-775 Update documentation for column mask/truncation and key columns

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumContainer.java, debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/DebeziumContainerTest.java, documentation/modules/ROOT/pages/integrations/testcontainers.adoc
https://issues.redhat.com/browse/DBZ-2070
@jpechane, would be nice to include this one. Note I've changed the expected format when instantiating the container, it seems more inline with e.g. the database containers. I think it's fine to do so at this point in time, it's incubating after all and we haven't heard yet of many user reports.
=> DBZ-2070 Specifying full name of container images with Testcontainers

documentation/antora.yml, documentation/modules/ROOT/pages/configuration/event-flattening.adoc, documentation/modules/ROOT/pages/configuration/topic-routing.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
@Naros   cc: @gunnarmorling 
This PR provides revised doc for topic routing and event flattening. My revision of the content needs to be reviewed. Please let me know what needs to change. 
I used a new conditionalization approach. I added `:community:` to the list of AsciiDoc attributes in `antora.yml`. I enclosed upstream only content like this: 
```
ifdef::community[]
upstream only content here
endif::community[]
```
I enclosed downstream only content like this: 
```
ifdef::product[]
upstream only content here
endif::product[]
```
Upstream, the `:product:` attribute is not defined. 
I used conditionalization to have short headings upstream, which are easy for scanning on the individual page minitocs on the right. While downstream, there are the longer, descriptive headings required by …
=> DBZ-2021 Updated doc for 1.1 SMTs for topic routing and event flattening

documentation/antora.yml, documentation/modules/ROOT/pages/configuration/avro.adoc, documentation/modules/ROOT/pages/configuration/mongodb-event-flattening.adoc, documentation/modules/ROOT/pages/connectors/cassandra.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/operations/monitoring.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-monitoring-metrics.adoc
Added `link-debezium-monitoring` attribute to `antora.yml`.
Used that attribute to change the link format for some links so they will work upstream and downstream. 
Changed the `names` anchor ID to `avro-naming` to avoid duplicate anchor IDs. 
With these updates, fetching the 1.1 branch from downstream should enable the Debezium User Guide to build.
=> DBZ-2021 Updates to allow downstream UG to build

documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_how-the-mysql-connector-handles-schema-change-topics.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_how-the-mysql-connector-maps-data-types.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_how-the-mysql-connector-performs-database-snapshots.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_how-the-mysql-connector-uses-database-schemas.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/c_mysql-connector-events.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_configure-the-mysql-connector.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_create-a-mysql-user-for-cdc.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_enable-the-mysql-binlog-for-cdc.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-monitoring-metrics.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-purges-binlog-files.adoc
Update anchor IDs for MySQL connector properties to be unique. 
Update anchor IDs in postgresql.adoc and sqlserver.adoc to be unique - missed the in the previous uber PR. 
Replaced "xref:" formatted cross references in MySQL content with cross-references that use link attributes. Something in the previous uber PR must have changed something that cause these cross-references to no longer work. Or I just missed them in the previous PR.
=> DBZ-2129 More updates so downstream user guide can build

documentation/modules/ROOT/pages/connectors/sqlserver.adoc
The title says it all. Please backport to 1.1. Thanks!
=> DBZ-2017 Remove Tech Preview note from SQL Server connector doc

documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/operations/debezium-server.adoc
This removed the Tech Preview note from the MongoDB connector doc. The note was conditionalized to be downstream only. When I ran antora to confirm that the doc still built, there were some errors in the debezium-server.adoc file. Some table formatting was causing the errors so I fixed that and ran antora again - no errors. 
Please backport this to 1.1.
=> DBZ-2016 Remove Tech Preview note for MongoDB connector doc

debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java
ChangeEventQueue's javadoc refers to a function `producerFailure`, which has been renamed to `producerException`.
=> DBZ-2136 Update ChangeEventQueue Javadoc by fixing typo

debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java, debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
https://issues.redhat.com/browse/DBZ-2152
Enhances the EventRouter to pass along keys that are not Strings
Based off of https://github.com/debezium/debezium/pull/1568 and rebases to master.
=> DBZ-2152 EventRouter with bytes based keys

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractReader.java, debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java, debezium-core/src/main/java/io/debezium/time/Temporals.java
Javadoc for `ConfigurationDefaults.RETURN_CONTROL_INTERVAL` says: *"The **maximum** wait time before `poll()` return control back to Connect when no events are available."*
That requires a `min()` call not a `max()`.
=> Fix for misuse of ConfigurationDefaults.RETURN_CONTROL_INTERVAL 

documentation/modules/ROOT/pages/architecture.adoc, documentation/modules/ROOT/pages/integrations/cloudevents.adoc
I edited the content for exporting CloudEvents formatted events to be consistent with Red Hat style conventions and to add annotations that will enable the file to be split into modules in a future release. 
In the architecture.adoc file, I updated the "image" reference to be consistent with what is required downstream. I ran antora and confirmed that the image appears. 
This update needs to be backported to 1.1. Thanks!
=> DBZ-2019 Revised content for CloudEvents

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
https://issues.redhat.com/browse/DBZ-2176
Checking pg_stat_activity for transactions with a state of "idle in transaction"
should be more reliable to find open abandoned transaction than looking for
a non-null backend_xmin. For example, an autovaccum process will have a
backend_xmin but will not have a state of "idle in transaction"
=> DBZ-2176 Open transaction tests are more reliable

documentation/antora.yml, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
I removed that attribute that was not needed: 
link-mysql-connector-properties
I updated the references to that attribute to instead use link-mysql-connector.
And I deleted an extraneous xref and comment from the top of the file. Not sure when that crept in but it is not needed.
I rant antora to confirm that the doc builds successfully.
=> DBZ-1995 Removed unneeded attribute definition. 

documentation/modules/ROOT/pages/configuration/event-flattening.adoc
Good catch Gunnar! Sorry about the typos. 
This correct two instances of property names that had hyphens where they should have had dots. 
Please backport this to 1.1.
=> DBZ-1956 Corrected property names by replacing dots with hyphens

documentation/modules/ROOT/pages/connectors/sqlserver.adoc
I added "SQL Server data types" as the link's target text. So "SQL Server data types" will render in place of the content's URL.
=> DBZ-1956 Inserts link target text so URL does not render

documentation/modules/ROOT/pages/integrations/cloudevents.adoc
This updates the content about exportiing CloudEvents format, based on Chris's comments in this Google document: 
https://docs.google.com/document/d/1lKSq4WUU7I3Ndz1CYgPuQRf5B10A4Y7wWIMZflkWrck/edit?usp=sharing
I also adjusted the column widths for a table that is reused for the doc for multiple connectors.
=> DBZ-1956 Updates to CloudEvents content, and fix for a table format

documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.redhat.com/browse/DBZ-2266
This introduces a branch 1.1 specific change to align column widths used by several connector tables that were rendering incorrectly downstream.
=> DBZ-2266 Adjust column widths

documentation/modules/ROOT/partials/modules/cdc-mysql-connector/p_install-the-mysql-connector.adoc, documentation/modules/ROOT/partials/modules/cdc-mysql-connector/r_mysql-connector-configuration-properties.adoc
There was an uppercase instance of Debezium in a path.
This needed to be lowercase. 
Please backport to 1.1.
Thanks.
=> DBZ-2266 Replace {prodname} attribute with literal "debezium" 

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TransactionMetadataIT.java
https://issues.redhat.com/browse/DBZ-2217
This was yet another example of where we did a pre-snapshot insert that may not be propagated to the capture tables before the snapshot process is started causing the later expectations of the test to fail.
=> DBZ-2217 Fix test failure - TransactionMetadataIT#restartInTheMiddleOfTxAfterSnapshot

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
https://issues.redhat.com/browse/DBZ-2229
=> DBZ-2229 Fix test failure - MySqlConnectorRegressionIT#shouldConsumeAllEventsFromDecimalTableInDatabaseUsingBinlogAndNoSnapshot

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
https://issues.redhat.com/browse/DBZ-2270
=> DBZ-2270 Fix test failure - MySqlConnectorIT#shouldNotParseQueryIfServerOptionDisabled

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
https://issues.redhat.com/browse/DBZ-2243
=> DBZ-2243 Fix test failure - MySqlConnectorRegressionIT#shouldConsumeAllEventsFromDatabaseUsingBinlogAndNoSnapshot

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlSourceTypeInSchemaIT.java
https://issues.redhat.com/browse/DBZ-2269
=> DBZ-2269 Fix test failure - MySqlSourceTypeInSchemaIT#shouldPropagateSourceTypeByDatatype

debezium-core/src/main/java/io/debezium/config/Instantiator.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java, debezium-embedded/src/main/java/io/debezium/embedded/spi/OffsetCommitPolicy.java, debezium-embedded/src/test/java/io/debezium/embedded/OffsetCommitPolicyTest.java
In order to fix the issue that is reported in [DBZ-2302](https://issues.redhat.com/browse/DBZ-2302), the `EmbeddedEngine` should initiate the `OffsetCommitPolicy` with `Properties` type being provided instead of `Configuration` type in order to keep the `debezium-api` light without depending on `debezium-core` (if I understood it correctly) for `Configuration` type.
Sorry in advance @gunnarmorling @jpechane if I have missed something, is been sometime since I contributed to Debezium :). 
P/S: Also I have tested with camel-debezium-* integration tests that we have there
=> DBZ-2302: Allow OffsetCommitPolicy to be initiated with Properties object

debezium-connector-mongodb/pom.xml, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
https://issues.redhat.com/browse/DBZ-2264
The default lock timeout in MongoDB is `5ms` and apparently this was too short for the environment where this error occurred.  The POM now introduces a new configurable property, `mongo.data.transaction.lock.timeout.ms` which by default I have increased to `1000ms`.  This should likely be sufficient for the Jenkins environment; however if we find it is not we can increase this in the Jenkins job rather than making code changes now.
=> DBZ-2264 Fix test failure - MongoDbConnectorIT#shouldConsumeTransaction

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlSourceTypeInSchemaIT.java
https://issues.redhat.com/browse/DBZ-2238
=> DBZ-2238 Fix test failure - MySqlSourceTypeInSchemaIT#shouldPropagateSourceTypeAsSchemaParameter

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TablesWithoutPrimaryKeyIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-2324
I went ahead in this PR and created a utility method in `TestHelper` to allow us to validate the existence of the CDC records prior to allowing the test to proceed and validate the expected connector observations as I think this is going to become a more prominent problem in our SQL Server tests are we uncover more timing-related issues.  If there are better ways to structure that check, I'm welcome to any suggestions.
=> DBZ-2324 Fix test failure - TablesWithoutPrimaryKeyIT#shouldProcessFromStreaming

documentation/modules/ROOT/pages/configuration/avro.adoc
After https://github.com/debezium/docker-images/pull/173/ and https://github.com/debezium/docker-images/pull/175/ this should update the docs to use new `ENABLE_APICURIO_CONVERTERS` env var to enable Apicurio converters.
=> DBZ-2083 fix docs for Apicurio Avro converter

documentation/modules/ROOT/partials/modules/cdc-all-connectors/r_connector-monitoring-schema-history-metrics.adoc, documentation/modules/ROOT/partials/modules/cdc-all-connectors/r_connector-monitoring-snapshot-metrics.adoc, documentation/modules/ROOT/partials/modules/cdc-all-connectors/r_connector-monitoring-streaming-metrics.adoc
The table column specification had a %s at the end where it should have been %a.
I rant Antora and this update enables rendering the text without bold.
=> DBZ-2326 Fixed a typo that was causing bold font for metric table description columns

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/AbstractMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/MessageDecoderConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/NonStreamingWal2JsonMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/StreamingWal2JsonMessageDecoder.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorTaskIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java, documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-2288
=> DBZ-2288 Events in exported snapshot no longer filtered by LSN

documentation/modules/ROOT/pages/integrations/outbox.adoc
https://issues.redhat.com/browse/DBZ-2367
Fix the dependency group id from `io.debezium.quarkus` to `io.debezium`.
Reference:
https://mvnrepository.com/artifact/io.debezium/debezium-quarkus-outbox/
=> DBZ-2367 Fix dependency groupId on Outbox Quarkus Extension documentation

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
See https://issues.redhat.com/browse/DBZ-2310 for more explanation.
Short summary: Whenever LSNs are skipped return back that messages have
been processed, which will cause two things:
* The replication can be advanced properly
* The connector does not fallback to the poll timeout waiting interval
I also think its more correct to say, "yes I have read messages, but
still skipped all of them".
=> DBZ-2310: Return true when messages are skipped

documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-2376
The option `column.whitelist` was not added until Debezium 1.2.  The documentation for 1.1 references this instead of the option `column.blacklist` which was part of the connector options in Debezium 1.1.  This PR fixes this typo reference.
=> DBZ-2376 Restore column.blacklist option in docs

documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-2376
This should address the remaining reference to `column.whitelist` identified by @TovaCohen.
=> DBZ-2376 Remove remaining references to column.whitelist

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/ParallelSnapshotReader.java
I ended up making two changes here:
1. don't change the timestamp to a 0 if we get a heartbeat event. This partially because it seems more correct and also in a related ticket Gunnar suggested doing that: https://issues.redhat.com/browse/DBZ-1989?focusedCommentId=14048603&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14048603
2. Even if we don't change the timestamp to a 0 (when we get a heartbeat), there is still the possibility of a 0/null timestamp reaching the halting predicate, because we could have only a heartbeat event after a snapshot, with no "real" binlog events with timestamps (snapshot events do not set a binlog timestamp). I think the safest thing to do in this case is just ignore events with no timestamps in the halting predicate, so that's …
=> DBZ-2387 fix NPE in ParallelHaltingPredicate

documentation/antora.yml
DBZ-2399 is an ongoing Jira for issues like this one: unexpected, small, doc updates required for 1.2GA. 
This PR just updates the value of the AsciiDoc attribute, `strimzi-version`. 
This update belongs in the 1.2 branch. I don't know if that requires a backport. 
Link to Jira:  https://issues.redhat.com/browse/DBZ-2399
=> DBZ-2399 Updates strimzi version attribute from 0.13.0 to 0.18.0

documentation/modules/ROOT/pages/connectors/postgresql.adoc
This is a major revision of the doc for the PostgreSQL connector.  The updates include:
- Comments that contain “Category”, “Type”, “ModuleID” and “Title” are annotations for splitting the upstream file into multiple downstream files. This lets us have one file upstream, and, as required, multiple assembly and module files downstream.
- Content revisions for consistency with Red Hat doc style conventions: 
- Edits for clarity and completeness that focus on user tasks.
- Present tense and not future tense. 
- Active voice and not passive voice. 
- No contractions or Latin phrases (i.e., e. g., via)
- Shorter and complete sentences. 
- Procedures have prerequisites.
- Tables have headings. 
- Headings use sentence case and not title case
- For downstream, sections that have many subsections …
=> DBZ-2333 Modularize and edit content for PostgreSQL connector

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnector.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java, documentation/modules/ROOT/pages/connectors/mongodb.adoc
https://issues.redhat.com/browse/DBZ-2225
This PR not only addresses allowing a shorter configuration for the SSL test timeout as described in the issue but it also exposes a way for users to customize 3 different timeouts based on their needs:
* `server.selection.timeout.ms`
* `connect.timeout.ms`
* `socket.timeout.ms`
=> DBZ-2225 Introduce MongoDB timeout configuration options

documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/partials/modules/cdc-all-connectors/r_connector-monitoring-streaming-metrics.adoc
Hey @TovaCohen and @Naros, some clean-up after the PG connector docs overhaul. Most importantly, there was a recent addition related to running the connector with an Azure-managed PG, which got lost during that PR. I've added this back. Otherwise, I agree with what Chris said elsewhere: the new structure of that page is much nicer to follow. Would love to see this being applied consistently for all the connectors.
=> DBZ-2333 Some clean-up

documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/partials/modules/mysql-connector/con-how-the-mysql-connector-maps-data-types.adoc, documentation/modules/ROOT/partials/modules/mysql-connector/ref-mysql-connector-configuration-properties.adoc
I edited the Azure content in the postgresql.adoc file. 
I changed some anchor IDs in the MySQL and PostgreSQL content because they were the same and this prevents the downstream guide from building. I also updated all references to those anchor IDs. 
This needs to be backported to 1.2.
=> DBZ-2399 Edit new Azure content. Change anchor IDs to avoid duplicates

documentation/antora.yml, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-2408
This PR fixes a 2 mistakes when doing prior backports of commits to the 1.1 branch for the Oracle.  This should resolve the warnings the documentation build gets when pulling in branch 1.1.
=> DBZ-2408 Fix build errors with oracle documentation

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java, debezium-core/src/main/java/io/debezium/heartbeat/DatabaseHeartbeatImpl.java
https://issues.redhat.com/browse/DBZ-2418
=> DBZ-2418 More meaningful error message in case of incorrect credentials

documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-2399 miscellaneous doc updates](https://issues.redhat.com/browse/DBZ-2399)
This just replaces "Avro Connector" with "Avro converter" in the mongodb.adoc file and the sqlserver.adoc file. 
I have other in-progress work that will make this change in the postgresql.adoc file and the db2.adoc files.
=> DBZ-2399 Changes "Avro Connector" to "Avro converter"

documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-schema-history-metrics.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc, documentation/modules/ROOT/partials/modules/mysql-connector/ref-mysql-connector-monitoring-metrics.adoc
DBZ-2375 Add links to entries in the mySQL metrics tables so that developers can share the anchor urls when responding to questions about the various metrics.
=> DBZ-2375 Hyperlink entries in the mysql metrics tables to facilitate sharing.

documentation/modules/ROOT/pages/integrations/cloudevents.adoc
Commented out `product` conditional content and ` community` conditional tags so that the same avro information renders upstream and downstream.
=> DBZ-2245 Edit conditionals to expose Avro info downstream

documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/mysql-connector/ref-mysql-connector-configuration-properties.adoc
DBZ-2476
@Naros  and @gunnarmorling 
This is a new PR. There are two commits. One for MongoDB, SQL Server, and MySQL. A second commit for just PostgreSQL.
This contains only fixes for the link rendering for the include/exclude list properties.
=> DBZ-2476 Second try at fixing include/exclude list property link rendering

debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
Simple change to ensure that when a table is skipped during a snapshot it still decrements the "RemainingTables" metric
=> DBZ-2191 Decrement remaining for skipped tables

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/partials/modules/mysql-connector/con-how-the-mysql-connector-maps-data-types.adoc
This is for DBZ-2500. 
A few tweaks are needed so the downstream user guide builds automatically after a fetch. 
Event thought the TBA example was conditionalized for upstream only, it was causing a build problem downstream. I don't know why. Hope it is okay to just remove it. 
Please backport this update to 1.2.
Thanks!
=> DBZ-2500 A few doc tweaks to correct formatting in db2 and postgresql doc

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeEventSourceCoordinator.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeEventSourceFactory.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresOffsetContext.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/spi/Snapshotter.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/CustomPartialTableTestSnapshot.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/CustomStartFromStreamingTestSnapshot.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java, debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
When a connector resumes after previously streaming and takes a
snapshot, through a new method on the snapshotter interface,
shouldStreamEventsStartingFromSnapshot, can choose whether
to resume streaming from the last known streaming position or the
beginning of the snapshot. This is helpful for snapshotters that
may not want to resnapshot every table in the whitelist/blacklist
but not miss event on the tables that are skipped.
This PR was created to address changes requested in #1596
=> DBZ-2094 Allow Postgres snapshotter to set streaming start on resume

documentation/antora.yml, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/assemblies/mysql-connector/assembly-deploy-the-mysql-connector.adoc, documentation/modules/ROOT/partials/modules/mysql-connector/proc-add-mysql-connector-configuration-to-kafka-connect.adoc, documentation/modules/ROOT/partials/modules/mysql-connector/proc-configure-the-mysql-connector.adoc
These updates are for [DBZ-2049](https://issues.redhat.com/browse/DBZ-2049).
I used the deployment instructions that we updated in the PostgreSQL connector doc as the model to update and add deployment instructions for each connector. 
There is a separate commit for the updates in each connector. 
I manually copied the updated files downstream to make sure that the downstream book builds. You might notice a few updates that seem unrelated to this update, but I had to make them to get the book to build. 
In the PostgreSQL connector doc, I updated a link target URL. 
I confirmed that Antora builds the doc. 
These updates are not required for 1.2, but it would be nice to be able to provide them in the downstream 1.2 doc. 
Let me know what needs to change.
=> DBZ-2049 Add deployment steps to the doc for each connector

pom.xml
Closes DBZ-2523. 
- Removes a duplicate `<version.surefire.plugin>` which already exists [here](https://github.com/debezium/debezium/compare/master...eric-weaver:DBZ-2523-remove-duplicate-surefire-version-property?expand=1#diff-600376dffeb79835ede4a0b285078036R121)
- Fixes what appears to have been a regression introduced in https://github.com/debezium/debezium/pull/1085 where maven-surefire-plugin and maven-failsafe-plugin were incidentally dropped from version 3.0.0-M3 to 2.22.2
=> DBZ-2523 remove duplicate surefire version property

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
fixes:
https://issues.redhat.com/browse/DBZ-2516 : Create Configuration Fields for datatype.propagate.source.type and column.propagate.source.type
https://issues.redhat.com/browse/DBZ-2526 : Connector Type properties has missing displayName property (UI)
https://issues.redhat.com/browse/DBZ-2527 : Add missing ListOfRegex validator to all regex list fields and remove legacy whitelist/blacklist dependents
=> DBZ-2516 DBZ-2526 DBZ-2527 fix Debezium UI PoC issues

documentation/modules/ROOT/pages/configuration/content-based-routing.adoc
These updates are for DBZ-2519.
They apply changes to make the documentation for the content-based routing SMT consistent with recent updates for the other SMT topics.
I confirmed that Antora builds the topics locally.
These changes must be backported to 1.2.
=> DBZ-2519 Edit content-based routing doc for consistency

documentation/modules/ROOT/pages/configuration/content-based-routing.adoc, documentation/modules/ROOT/pages/configuration/filtering.adoc
This update inserts an annotation comment at the head of the doc to support the downstream build. 
Also, conditionalize :toc: entries In the filtering file and in content-based-routing.adoc so that render in the upstream doc only.
The update is required for 1.2.
=> DBZ-2539 Insert file annotation to identify component for downstream doc

documentation/modules/ROOT/pages/configuration/event-flattening.adoc, documentation/modules/ROOT/pages/configuration/topic-routing.adoc, documentation/modules/ROOT/pages/integrations/cloudevents.adoc
This is for [DBZ-2554](https://issues.redhat.com/browse/DBZ-2554). 
There are edits to topic-routing.adoc and event-flattening.adoc to make this doc consistent with the doc for other SMTs: 
- Change references to the SMT to plain text
- Remove conditionalization and add nebel split annotations in comments
- Ensure that headings contain "Debezium" for optimum search success
- Standardize on "option" in place of "property"
- Add some introductory sentences
- Insert {zwsp} as needed.
These changes will be needed for the downstream 1.3 release. They are NOT needed for the 2020-Q3 (1.2) release.
=> DBZ-2554 Edit topic routing/event flattening SMTs format/style/annotations/conditionalization

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresOffsetContext.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
Normally when a connector gracefully shuts down, the connect framework attempts to commit offsets so the latest committed state gets acked on the replication stream.  While the connector is running, the framework periodically commits offsets. Debezium does not manage triggering an offset commit.  When the catch up streaming phase ends, there may be uncommitted state and the connector is unable to determine when the next commit will occur because the commit timing is externally managed. If a commit is not triggered between the end of the catch up streaming phase and the normal streaming phase after the snapshot, the connector may produce some duplicated messages.
Although the replication stream may be out of date, the internal OffsetContext is aware of the latest committed offset. When the …
=> DBZ-2550 Prevent duplicate events using catch up streaming

documentation/modules/ROOT/pages/configuration/content-based-routing.adoc, documentation/modules/ROOT/pages/configuration/filtering.adoc
To address a security issues with the filter, and content-based routing SMTs, were removed from the core product, and the documentation was revised (DBZ-2549) to describe how to obtain and set up the SMTs.   
This issue is for updates related to preparing the revised documentation for use downstream. The updates include:
- Heading annotation comments to support splitting/modularizing the files for downstream use.
- Language edits to comply with standard product doc use. 
- Minor restructuring/shuffling of content to improve flow.
This change needs to be backported to 1.2.
=> DBZ 2567 Prepare revised SMT docs for downstream

debezium-quarkus-outbox/integration-tests/pom.xml, debezium-quarkus-outbox/integration-tests/src/main/resources/application.properties, debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/DatabaseTestResource.java
Either we will need a new 1.2 version for Quarkus 1.9 (before October 6th) or a new DBZ release in Quarkus but that means some discussions with the Camel Quarkus team.
Having a new 1.2 ASAP would be very nice if it's not too much work for you. That would secure our CI and the release schedule.
/cc @ppalaga @lburgazzoli
=> DBZ-2558 Fix the Quarkus datasource configuration

documentation/modules/ROOT/pages/configuration/content-based-routing.adoc, documentation/modules/ROOT/pages/configuration/filtering.adoc
In a pair of files, the annotations that define the titles for the modularized downstream documentation included a typo in the attribute that represents the product name (a closing square bracket instead of the required curly brace). This fix corrects that error.  
The fix was already applied independently in the downstream docs. Fixing the error upstream to prevent overwriting the correction the next time we fetch from the source.
The fix has no visible effect on the upstream doc.
Fix to be backported to 1.2 branch.
=> DBZ-2577 Fix malformed attribute references in downstream title annotations

documentation/modules/ROOT/pages/configuration/event-flattening.adoc, documentation/modules/ROOT/pages/configuration/outbox-event-router.adoc, documentation/modules/ROOT/pages/configuration/topic-routing.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-schema-history-metrics.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc
[DBZ-2564](https://issues.redhat.com/browse/DBZ-2564)
I already made these changes downstream for the Q3 release so these updates do NOT need to be backported to 1.2. 
There are separate commits for each connector's doc and for other groups of similar changes. 
There are no updates in the doc for the MySQL connector. I'm about to re-unify the doc for MySQL into one file and updating format for MySQL will be part of that work.
=> DBZ-2564 format updates for better downstream rendering

documentation/modules/ROOT/pages/configuration/event-flattening.adoc, documentation/modules/ROOT/pages/configuration/topic-routing.adoc
This is for [DBZ-2596](https://issues.redhat.com/browse/DBZ-2596).
After merging this PR to master, please merge[ PR-1819](https://github.com/debezium/debezium/pull/1819) to the 1.3 branch, and THEN merge this update also to the 1.3 branch. 
I ran antora locally and I confirmed that this removes the error in the table headings.
=> DBZ-2596 Correct format error in config options table header

documentation/modules/ROOT/pages/configuration/content-based-routing.adoc, documentation/modules/ROOT/pages/configuration/filtering.adoc
This update fixes an issue in the docs for the filter and content-based routing SMTs, in which a link in the  _Language specifics_  sections does not render, because the link specification omits any link text.
Also fixed issues with table formatting (col width, bad line breaks in cells, removal of extra delimiter characters).
Testing via a local antora build confirmed that the links work as intended.
This fix requires a backport to 1.2.
=> Dbz 2593 add missing link text

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/AbstractSqlServerDatatypesTest.java
https://issues.redhat.com/browse/DBZ-2474
It seems the issue could be somewhat two fold where the CDC records are not propagated prior to the snapshot being completed and so some checks were added to the base test to make sure that the snapshot has completed prior to advancing to the actual test itself and secondly, that the test's seed data has been replicated to the capture tables.
=> DBZ-2474 Fix test failure - DatatypesFromSnapshotIT#stringTypes

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlValueConvertersTest.java
https://issues.redhat.com/browse/DBZ-2563
This is not top quality implementation. The best approach would be unification of errors in `BinlogReader` but this would be quite invasive. So the code should be handled like an interim solution with the final one in the rewritten connector.
=> DBZ-2563 JSON processing can ignore deserialization errors

documentation/modules/ROOT/pages/connectors/db2.adoc
A warning on BOOLEAN types until the issue is resolved with IBM support.
=> DBZ-2587 Warning on BOOLEAN type on Db2

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java
Current mysql debezium connector fails once it sees an event generated
with statement or mixed based replication.
As users and programs can call SET SESSION binlog_format='STATEMENT'; as
they wish, they are able to break debezium connector. Only MySQL 8.0.14
is fixing this, but not everyone is on that version.
To prevent connector crashing in such cases, there should be an option
to log these issues and continue. That would be similar to processing
inconsistent schema (on the setting level).
=> DBZ-2583 MySQL connector - ignore statement-based logs

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
https://issues.redhat.com/browse/DBZ-2544
As some background, I think the underlying problem here is that we previously double dipped on the database check.  While locally testing, when the test would fail showed some metadata queries that the connector wasn't issuing but seemed to be coming from the JDBC driver itself.  Because of how we asserted the state, I think this is what lead to the inconsistent pass/fail of this test.
This PR instead changes the behavior to rely solely on the `Awaitility` API call and if that results in a time-out, we fail the test.  If that call results in success, that should be sufficient to allow the test to pass without the additional query & assertion check.
=> DBZ-2544 Fix test failure - PostgresConnectorIT#customSnapshotterSkipsTablesOnRestart

documentation/modules/ROOT/pages/connectors/db2.adoc
Confirmed with IBM support, SQL replication on Db2 does not currently support BOOLEAN.
This is to make it official in the documentation.
=> DBZ-2587 SQL replication on Db2 does not support BOOLEAN

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
The value of the default can be specified as an expression; it need not  be a constant.
Source: https://dev.mysql.com/doc/refman/5.7/en/declare-local-variable.html
=> DBZ-2615: Use expression as default for variable declaration.

documentation/antora.yml
[DBZ-2609](https://issues.redhat.com/browse/DBZ-2609) reports an error in the path for a container image. This path is set by the :DockerKafkaConnect: attribute, and we use in in only downstream Debezium doc. However, this attribute is in the antora.yml file so I am updating it.
=> DBZ-2609 Updated value of DockerKafkaConnect attribute to add "rhel7" to the path

pom.xml
We met the issue that DATE column was truncated incorrectly with database.useCursorFetch": "true". It's fixed in a later release:
https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-19.html
> When retrieving TIME values using ResultSet.getTimestamp(), the fractional seconds are truncated when useCursorFetch=true. This patch corrects the problem by fixing the TIME value decoding in the MysqlBinaryValueDecoder. It also corrects some inconsistencies in formatting the fractional seconds when returning the TIME values as strings. (Bug #30119545, Bug #96383)
=> DBZ-2626 upgrade Mysql driver jar version to 8.0.19

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-2610](https://issues.redhat.com/browse/DBZ-2610) notes an error in the installation guide for installing Debezium on OpenShift. This is downstream only content, however the same content is in the user guide for each connector, and we fetch and reuse this upstream content in the downstream user guide. 
So this update makes the same edit to the doc for the MongoDB, DB2, PostgreSQL, and SQL Server connectors. I'll do the MySQL update in the open PR for the reunified content.
=> DBZ-2610 In downstream-only content, add context directory to podman command example

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-2584](https://issues.redhat.com/browse/DBZ-2584) asks for clarifications in the descriptions of change data events. 
I made the following changes:
- Replace `ts_sec` with `ts_ms`
- Add that `source.ts_ms` is the timestamp of the change in the database
- Add that `payload.ms_ts` can be compared with `source.ts_ms` to determine lag
I did this for each connector that has downstream doc. 
I did a separate commit for each connector. 
It would be great to get this correction into the downstream Q3 published documentation. So let me know if this can be backported to 1.2. But if not, we can manually  update the downstream files. Please let me know about this.
=> DBZ-2584 Replace ts_sec with ts_ms, clarify meaning of source.ts_ms

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java
Fixes: https://issues.redhat.com/browse/DBZ-2643
This PR adds a check to `maybeSetFilterDataFromConfig` for the case where a connector has filter info, but snapshot.new.tables is not set to parallel. In this case we unset the filters.
I'm also updating the `MySQLConnectorTask` to run `maybeSetFilterDataFromConfig` in every case where it's picking up from an existing offset, rather than only running the update when offsets are missing filter info.
I've tested this change in our staging environment.
=> Only set filter info in offsets when snapshot.new.tables = parallel

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotReaderIT.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.redhat.com/browse/DBZ-2456
Hi @jpechane, @gunnarmorling as per your comments on #1766. I have re-modeled the change to include a property snapshot.table, which would allow for selectively taking the snapshot and is honored by all types of connectors. So Effectively only the subset of tables specified in the above configuration are considered for snapshots and are locked, post which streaming resumes. Could you please check and let me know if this suffices.
My apologies for creating a new PR as I had some problems in merging the refs from upstream.
=> DBZ-2456 selective snapshot implementation

documentation/modules/ROOT/pages/connectors/postgresql.adoc
[DBZ-2621](https://issues.redhat.com/browse/DBZ-2621) describes a number of problems with the downstream instructions for deploying a PostgreSQL connector. 
I worked with @rareddy and @roldanbob  to revise the instructions and the update is in this PR. 
In addition, I moved the section about Monitoring, out of the Deployment section and into its own second-level section, so it is now a peer of Setting Up, and Deploying, and other sections. This is consistent with the way the doc is organized for the MySQL and Db2 connectors. 
There are also a few other changes that I noticed were needed. 
When this is approved and merged, we should update and republish the downstream Debezium User Guide (1.2, 2020-Q3). However, I think that that will have to be a manual process. I don't think that you …
=> DBZ-2621 Reorganize deployment instructions in downstream doc

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/MaxLsnResult.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
https://issues.redhat.com/browse/DBZ-2582.
This is an example of what would be done if the changes for DBZ-2582 were implemented across the board.
A more general/customizable option should be built instead.
Edit: I updated the PR to make the select something that's configurable. I really do not like any of the names I gave these things (the configuration and the class/variable names), but I am honestly not sure what to call them that is concise yet informative. Suggestions welcome!
=> DBZ-2582 Updating LSN handling

debezium-microbenchmark/pom.xml, pom.xml, support/checkstyle/src/main/resources/checkstyle-suppressions.xml
That way, any generated sources won't be parsed to begin with, instead of only discarding their violations. This saves ~30 sec. for the DDL parser module.
https://issues.redhat.com/browse/DBZ-2669
=> DBZ-2669 Explicitly specifying source directories for Checkstyle;

debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java, debezium-core/src/test/java/io/debezium/jdbc/JdbcConnectionTest.java
Upon investigation I found out that long running connections to an Aurora RDS MySQL database do not close properly and time out instead -- if the connection is still in the process of streaming data on another thread. 
It seems that AWS at least partially acknowledged this issue as a networking layer issue: https://forums.aws.amazon.com/thread.jspa?messageID=440379. 
But since it isn't feasible for us (and I imagine many others) to alter our security groups to circumvent this issue it would be better if we can solve it in the application layer. I tried using `socketTimeout` and `connectTimeout ` as a JDBC url parameter but to not avail as these parameters are ignored when you try to close a connection.
The solution I came up with was to attempt a graceful close of the connection, but if …
=> DBZ-2632: Force closing the JDBC connection if failed to close it gracefully.

documentation/modules/ROOT/pages/configuration/event-flattening.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc
I re-opened [DBZ-2681](https://issues.redhat.com/browse/DBZ-2681) because I missed three updates needed for downstream rendering. I accidentally added on to the previous PR, which was merged, so I cancelled that and created a new topic branch and pushed from that. Sorry for any confusion!
I think this should be the last of the needed tweaks for downstream. I'll fetch from master as soon as this is merged. 
No need to back port to 1.2.  THANKS in advance for merging this. 
@jpechane and @Naros
=> DBZ-2681 From a new branch, two fixes, and moved one anchor ID into upstream-only content

debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java, debezium-core/src/test/java/io/debezium/junit/relational/TestRelationalDatabaseConfig.java, debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java, debezium-core/src/test/java/io/debezium/relational/mapping/ColumnMappersTest.java
1. Always call the underlying connector from the wrapper since it may convert NULL to a non-NULL.
2. Extract `TestRelationalDatabaseConfig` to a public class to be able to reuse it in the new test.
=> DBZ-2682: Mapper converters should leave empty dates as zero

documentation/modules/ROOT/pages/development/converters.adoc
Fixed the typo: `ield` -> `field`
=> DBZ-2717 Fix typo in converters doc

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-core/src/main/java/io/debezium/heartbeat/DatabaseHeartbeatImpl.java, debezium-core/src/main/java/io/debezium/heartbeat/Heartbeat.java, debezium-core/src/main/java/io/debezium/heartbeat/HeartbeatErrorHandler.java, debezium-core/src/main/java/io/debezium/heartbeat/HeartbeatImpl.java, debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java, pom.xml
DBZ-2617 Failing heartbeats should put Postgres connector into FAILED state to allow proper shutdown of Postgres when shutdown was triggered with shutdown mode "fast"
closes https://issues.redhat.com/browse/DBZ-2617
=> DBZ-2617 Failing heartbeats should put Postgres connector into FAILED state

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotReaderIT.java
One of our legacy databases stores binary data in a MySQL CHAR(32) Latin1 field. Converting this field to binary would be the ideal solution but unfortunately isn't easily feasible. 
The problem lies in the fact that the MySQL JDBC driver converts MySQL's latin1 charset to Windows-1252 whereas our legacy system stores these bytes using IANA Latin1 (or ISO-8859-1) charset and these implementations do not have a 1:1 mapping. 
An elegant way to solve this issue is by using Debezium's newly supported custom converters (https://debezium.io/documentation/reference/1.3/development/converters.html). 
The only issue with this approach is that MySQL's `SnapshotReader` does not return char-type fields' raw bytes making it impossible to encode the char field's raw bytes into the desired charset. This …
=> DBZ-2673 Read the raw bytes of a character-type field

debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java, debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordStateConfigDefinition.java, debezium-core/src/test/java/io/debezium/transforms/ExtractNewRecordStateTest.java, documentation/modules/ROOT/pages/configuration/event-flattening.adoc
https://issues.redhat.com/browse/DBZ-2606
Added ability to map new name for the fields and headers.
The "new name" mapping is completely optional and we will not
be affecting the existing functionality.
=> DBZ-2606: Map new name for the fields and headers

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDefaultValueConverter.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
https://issues.redhat.com/browse/DBZ-2726
Although MySQL can do some basic validation of the default value of the `TIMESTAMP` column, all the following default values can be applied successfully to MySQL, because MySQL can automatically fix them when applying the DDL. However, the raw DDL is sent to Debezium and many of the values will make the MySQL Connector task fail when updating the internal schema:
```sql
CREATE TABLE my_table (
ts_col01 TIMESTAMP DEFAULT '2020-01-02',
ts_col02 TIMESTAMP DEFAULT '2020-01-02 ',
ts_col03 TIMESTAMP DEFAULT '2020-01-02:',
ts_col04 TIMESTAMP DEFAULT '2020-01-02--',
ts_col05 TIMESTAMP DEFAULT '2020-01-02 03',
ts_col06 TIMESTAMP DEFAULT '2020-01-02 003',
ts_col07 TIMESTAMP DEFAULT '2020-01-02 03:',
ts_col08 TIMESTAMP DEFAULT '2020-01-02 03:04',
ts_col09 …
```
=> DBZ-2726 Clean MySQL TIMESTAMP default value

documentation/modules/ROOT/pages/operations/logging.adoc
This change restores content about Debezium logging into a single upstream file, `logging.adoc`. In an earlier release, content about  Debezium logging was modularized and split into individual files that were stored in the `/partials` directory. The doc team now uses a script that splits the content in the main file when we fetch it for downstream re-use.
=> DBZ-2721 Reintegrate content from modularized files to logging.adoc

debezium-connector-mysql/src/test/resources/ddl/connector_test_ro.sql, debezium-core/src/main/java/io/debezium/relational/TableEditorImpl.java, debezium-core/src/test/java/io/debezium/relational/TableEditorTest.java, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
DBZ-2580 Fix "The primary key cannot reference a non-existant column" error from MySQL DDL parser when CREATE TABLE statement starts with a primary key definition like
```
CREATE TABLE Products (
PRIMARY KEY (id),
...
)
```
where the referenced primary key column is not yet defined.
closes https://issues.redhat.com/browse/DBZ-2580
=> DBZ-2580 Fix "The primary key cannot reference a non-existant column" error

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotReaderIT.java, documentation/modules/ROOT/pages/connectors/mysql.adoc
Adds a backwards compatible config for the mysql connectors snapshot events to be marked as reads.
=> DBZ-2775 add option for setting snapshot events as reads

documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Changes to support modularizing SQL Server connector doc for downstream use. 
- Restructures content for consistency with MySQL and PostgreSQL connector docs, including changes to heading levels.
- Adds comments that the file splitter routine uses to delimit modules.
- Changes to headings for capitalization and wording consistency.
There are _no significant *content* changes_ in this PR. I'll follow up with a separate PR with content changes to address language changes for consistency, clarity, and to comply with a11y and translatability considerations.
=> DBZ-2335 Add modularization annotations and restructure for consistency

debezium-server/debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java
edit: https://issues.redhat.com/projects/DBZ/issues/DBZ-2785
I've started this from the merge-base of 1.3, 1.4, and master to keep it easy to move if you don't want this as a patch on 1.3.
As mentioned on the ticket, I haven't actually used Quarkus before & don't have the bandwidth to learn it to the extent needed for proper testing.  I have, however, tested locally with a bad SQL password to verify that the fix works.
=> [DBZ-2785] shut down Quarkus server if debezium-server crashes

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumContainer.java
* fix try-with-resources block should not be used when OkHttp Response object is returned in DebeziumContainer
closes https://issues.redhat.com/browse/DBZ-2827
=> DBZ-2827 fix try-with-resources block should not be used when OkHttp Response object is returned

debezium-testing/debezium-testing-testcontainers/pom.xml, debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/ConnectorConfiguration.java
Add Mongo DB default config helper to ConnectorConfiguration in Debezium Testing Testcontainers package.
relates to: https://issues.redhat.com/browse/DBZ-2808
=> DBZ-2808 Add Mongo DB default config helper to ConnectorConfiguration

documentation/modules/ROOT/pages/connectors/sqlserver.adoc
This change fixes errors in the conditionalization statements and in the annotation comments that are used to parse the content for the downstream documentation build
Some annotations were missing, and others contained invalid space characters, or capital letters, that could result in unexpected behavior.
Other updates include changes to address inconsistencies in terminology and in the format of IDs, and removal of erroneous cross-reference links.
Tested successfully in local antora build.
=> DBZ-2824 Fix xrefs, anchor ids, conditionals; standardize terminology

documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc
This change replaces the `'strm'` strings in the prefixes of anchor IDs in `/partials/ref-connector-monitoring-snapshot-metrics.adoc` with `'snaps'` to make the IDs unique from those used for metrics with the same names in `ref-connector-monitoring-streaming-metrics.adoc` The fix resolves a duplicate ID error that caused build failures in the downstream documentation.
=> DBZ-2839 Fix duplicate anchor IDs in snapshot metrics

documentation/modules/ROOT/pages/operations/monitoring.adoc
This changes removes the stray characters `"]` that were appended to the ModuleID values in the annotation comments for several topics.
=> DBZ-2838 Remove erroneous characters appended to ModuleID definitions.

documentation/modules/ROOT/pages/operations/monitoring.adoc
This change removes a closing square bracket ( `]` ) from the ModuleID comment for the heading `=== Zookeeper JMX environment variables`. The extra character caused a build failure in the downstream documentation.
=> DBZ-2843 Delete closing `]` from ModuleID for zookeeper jmx topic

documentation/modules/ROOT/pages/operations/logging.adoc
After fetching the` logging.adoc` file for use downstream, the file splitting utility could not process the file, because of the intervening lines between some annotation comments and the corresponding upstream anchor IDs.
Of the following changes, the first one addresses the main problem. The second one cleans up superfluous comments. The last one changes the downstream heading text, and its corresponding ID for compliance with Red Hat style. 
- Deletes empty line between the annotation comments and the corresponding anchor ID/heading pair.
- Removes unnecessary `Category` declarations.
- Modifies one set of downstream titles/ModuleIDs.
None of these changes affect the presentation of the community documentation.
=> DBZ-2846 Remove category statements,  trailing newlines fr. annotations

documentation/modules/ROOT/pages/connectors/mysql.adoc
Removes link in first sentence of section that targets the title of the same section.
=> DBZ-2710 Remove self-referential link in pass-through config properties

documentation/modules/ROOT/pages/connectors/vitess.adoc
https://issues.redhat.com/browse/DBZ-2854
Related features:
- DBZ-2578: Add support for using Vitess primary key as Kafka message key
- DBZ-2836: Invalid column name caused by Vitess vstream bug should fail connector with meaningful message
- DBZ-2852: Add support for Vitess gRPC static authentication
=> DBZ-2854 Update Vitess Connector documentation

documentation/modules/ROOT/pages/connectors/vitess.adoc
https://issues.redhat.com/browse/DBZ-2851
Vitess Connector already supports the sanitize.field.names configuration. I've added an integration test in other [PR](https://github.com/debezium/debezium-connector-vitess/pull/14).
=> DBZ-2851 Add sanitize.field.names to Vitess documentation

documentation/modules/ROOT/pages/connectors/oracle.adoc
Add the jdbc url property to the oracle connector documentation
=> DBZ-2859 Support TNS Names and full RAC connection strings

debezium-quarkus-outbox/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/OutboxProcessor.java, pom.xml
https://issues.redhat.com/browse/DBZ-2860
Creating as a draft, since Quarkus 1.11.0.Beta1 hasn't been released yet.
To test this:
* Get [that PR](https://github.com/quarkusio/quarkus/pull/13929) in your local clone of Quarkus, then build it with `./mvnw -U -Dquickly`
* Go to your local clone of Debezium and get this PR
* `mvn clean install -DskipTests -DskipITs -Dquarkus.version=999-SNAPSHOT`
* `cd debezium-quarkus-outbox`
* `TESTCONTAINERS_RYUK_DISABLED=true mvn clean install  -Dquarkus.version=999-SNAPSHOT`
=> DBZ-2860 Explicitly declare to Quarkus that ORM XML mapping is required for the outbox extension

debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java, debezium-core/src/test/java/io/debezium/junit/logging/LogInterceptor.java, debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java
https://issues.redhat.com/browse/DBZ-2849
@gunnarmorling @jpechane This issue was reported as a failure with the Oracle connector but through investigation the root cause is a bad lookup in debezium-core when sanitized field names are enabled for Avro serialization.
=> DBZ-2849 Fix value converter field lookups with sanitized field names

.github/workflows/jdk-outreach-workflow.yml
https://issues.redhat.com/browse/DBZ-2861
As https://github.com/debezium/debezium/actions/runs/480375579 has passed after adding `debezium-assembly-descriptors` and `debezium-core` I believe it's going to work for the outreach testing module. FYI postgres test failure might be a blocker. I have logged a JIRA for that.
=> DBZ-2861 Fix Testing Module under Outreach Jobs

documentation/modules/ROOT/pages/connectors/mysql.adoc
| PR Status  | Type  | Impact level |
| :---: | :---: | :---: |
| Ready | Documentation | Low  |
- Fix the description in the `database.user` section.
- Name of the MySQL ~~database~~ / user to use when connecting to the MySQL database server.
=> Update typo in database.user description

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerValueConverters.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerBinaryModeIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.redhat.com/browse/DBZ-2912
=> [DBZ-2912] Add support for binary.handling.mode to the SQL Server connector

documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc
I thought that I had fixed this previously, but in doing a test build downstream I encountered errors related to duplicate IDs and traced the problem back to the  upstream source file. 
One point of confusion is that I would expect the `*QueueSizeInBytes` metrics to appear in the doc for other connectors that are part of the downstream product, but I don't see references to them. The following files all reference the same file (`ref-connector-monitoring-snapshot-metrics.adoc`):
```
modules/ROOT/pages/connectors/sqlserver.adoc
modules/ROOT/pages/connectors/postgresql.adoc
modules/ROOT/pages/connectors/oracle.adoc
modules/ROOT/pages/connectors/mysql.adoc
modules/ROOT/pages/connectors/db2.adoc
modules/ROOT/pages/connectors/mongodb.adoc
```
=> DBZ-2958 Fix incorrect link IDs in connectors snapshot metrics table

documentation/modules/ROOT/pages/connectors/cassandra.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc
This change replaces the blacklist/whitelist strings that remained in some anchor link IDs in the connectors documentation with equivalent exclude-list/include-list strings.
=> DBZ-2918 Conscious language update: replace black-/white- list strings

documentation/modules/ROOT/pages/connectors/cassandra.adoc
[DBZ-2966](https://issues.redhat.com/browse/DBZ-2966) After reviewing the merged PR for DBZ-2918 I noticed that I incorrectly replaced one instance of `blacklist` with `include-list` instead of `exclude-list`.  This change correctly sets the anchor ID to `exclude-list`.
=> DBZ-2966 Correct anchor id to `exclude-list` vs. `include-list`

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
(Maybe this is part 1 to quickly fix user's issues, I'm working on a Testcontainers integration test in order to check another way of properly testing the replication slot assignments, even in config update cases).
closes https://issues.redhat.com/browse/DBZ-2952
=> DBZ-2952 Remove Postgres replication slot validation

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
Fix that an invalid regex for `database.inlcude.list` and `database.exlcude.list` does not raise a validation error for MySQL connector and the connector only fails on start, also the config validated before
closes https://issues.redhat.com/browse/DBZ-3008
=> DBZ-3008 Fix that an invalid regex for `database.inlcude.list` and `database.exlcude.list` does not raise a validation error

jenkins-jobs/job-dsl/release_deploy_snapshots.groovy, jenkins-jobs/job-dsl/release_upstream.groovy
I don't know if this is an issue as long as git access is with a proper user agent and github redirects to the correct URL, but it won't hurt anyways?
FYI @jpechane 
closes https://issues.redhat.com/browse/DBZ-3011
=> DBZ-3011 Add git repository suffix to repo URLs

documentation/modules/ROOT/pages/connectors/db2.adoc
[DBZ-2814](https://issues.redhat.com/browse/DBZ-2814)
Removes caveats that the Db2 connector is in Technology preview/incubating state.
=> DBZ-2814 Remove Db2 Tech prev/incubating statements for promotion to GA.

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
https://issues.redhat.com/browse/DBZ-2420
Won't it be wise to keep the `PORT` field for the `xxxConnectorConfig` class rather than defining it with `PORT.withDefault()`? Rest all fields can be defined in `RelationalDatabaseConnectorConfig`.
=> DBZ-2420 Define database configs under RelationalDatabaseConnectorConfig

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumContainer.java, debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/DebeziumContainerTest.java
DBZ-2950 and DBZ-3002 need some enhancements to DebeziumContainer. In order to have SNAPSHOT packages in the Sonatype repository and new code in nightly builds of debezium/connect containers I need to have this migrated to the main repo in order to continue with DBZ-2950 (add MySQL connector to UI backend) prior finishing DBZ-3002 (re-add Postgress replication slot validation).
closes https://issues.redhat.com/browse/DBZ-3024
=> DBZ-3024 Migrate DebeziumContainer enhancements for DBZ-2950 and DBZ-2952 into main repository

documentation/modules/ROOT/pages/connectors/mysql.adoc
JIRA issue [DBZ-3013](https://issues.redhat.com/browse/DBZ-3013)
Removed erroneous underscores from MySQL connector doc references to granting `LOCK_TABLES` permissions.
=> DBZ-3013 Remove underscore from references to `LOCK_TABLES`

debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
The KafkaProducer in KafkaDatabaseHistory is not closed with a  timeout This can cause the producer to wait indefinitely and still produce logs after connector/task is deleted.
This change closes producer with a timeout of 30s.
=> DBZ-3075 Close Kafka Database History producer with a timeout of 30s.

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputRelationMetaData.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
Fix issue where `PgOutputMessageDecoder` does not define primary key metadata in key-order.
`PgOutputMessageDecoder.getTablePrimaryKeyColumnNamesFromDatabase()` returns a `Set`, leading to unordered
primary keys in the metadata. Switch the logic to call `JdbcConnection.readPrimaryKeyNames()` which
_does_ correctly return an ordered primary key list.
=> DBZ-3074 PgOutputMessageDecoder - Fix unordered keys

documentation/modules/ROOT/pages/configuration/avro.adoc
Jira issue [DBZ-2815](https://issues.redhat.com/browse/DBZ-2815)
The only references to use of the service registry/Apicurio Removed TP statement in the Avro serialization chapter (`avro.adoc`). This change removes the Tech Preview note at the beginning of that chapter. 
Pending information to the contrary, based on exchanges with @jcechace that update looks to be sufficient for moving information about using the service registry feature to GA.
=> Dbz 2815 prep service registry docs for ga

debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
Fix issue [DBZ-3096](https://issues.redhat.com/browse/DBZ-3096)
The MySqlConnectorTask will submit two checking topic tasks to the thread pool checkTopicSettingsExecutor, the thread pool will be shutted down when it executed successfully, so submit the second task will be rejected and throw the exception.
=> DBZ-3096 Getting RejectedExecutionException when checking topic settings from KafkaDatabaseHistory.checkTopicSettings

documentation/modules/ROOT/pages/connectors/index.adoc
Jira issue [DBZ-3097](https://issues.redhat.com/browse/DBZ-3097?filter=-2)
This change is a followup to [DBZ-2814 _IBM Db2 Connector promoted to GA_](https://issues.redhat.com/browse/DBZ-2814). It removes the string `(Incubating)` from the Db2 connector item in the list of connectors in the Connectors **Overview** topic (`connectors/index.adoc`).
=> DBZ-3097 Remove parenthetical ref to Db2 connector being `Incubating`

documentation/modules/ROOT/pages/connectors/cassandra.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc
Jira [DBZ-3111](https://issues.redhat.com/browse/DBZ-3111)
This change removes redundant anchors that I erroneously inserted into the tables for the `*include-` and `*exclude-` .list properties for all of the connectors when I updated terminology in [DBZ-2918](https://issues.redhat.com/browse/DBZ-2918). The duplicates generated build warnings that prevented Antora from building the documentation.
Verified in a local Antora build that the build now completes successfully, that the property names render correctly, and that the links work as expected.
=> DBZ-3111 Remove dup anchors introduced into props tables in DBZ-2918.

debezium-api/src/main/java/io/debezium/engine/DebeziumEngine.java, debezium-embedded/src/main/java/io/debezium/embedded/ConvertingEngineBuilder.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java, debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java, documentation/modules/ROOT/pages/development/engine.adoc, support/revapi/src/main/resources/revapi/debezium-api-changes.xml
https://issues.redhat.com/browse/DBZ-2897
Extended the DebeziumEngine interface to include a new method for marking a record processed with updated source offsets. Implemented the new interface method in both ConvertingEngineBuilder and EmbeddedEngine. EmbeddedEngine creates a new SourceRecord with the updated sourceOffsets and passes this to the original markProcessed method. Added a unit test in EmbeddedEngineTest that verifies that the file offset storage contains the updated source offset’s partition. Added a revapi ignore case to prevent failure from a method added to an interface without a default method. Updated docs for Debezium Engine that describe the new functionality.
=> DBZ-2897 Extended RecordCommitter interface to handle updated source offsets.

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc
Jira [DBZ-3087](https://issues.redhat.com/browse/DBZ-3087)
This change removes instances of {zwsp} from properties tables in the documentation for Debezium connectors and recodes strings that included the zero-width spaces as passthrough literal monospace by enclosing them in \`+ +\`.
I tested the change locally and found that all of the strings render correctly and the encoded self-referential links work as expected. However, there's a reversion to the past behavior of Firefox inserting hyphens when long property name strings break after the page width decreases below a certain threshold. For example:
In a local test of the downstream build, no hyphenation occurs. 
The hyphenation behavior is not evident in Chrome upstream or downstream.
I tested copy and paste from the FF tables to the …
=> DBZ-3087 Remove zero-width spaces from prop names subject to copying

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/SnapshotReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/transforms/ReadToInsertEvent.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotSourceIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/legacy/SnapshotReaderIT.java, documentation/modules/ROOT/pages/connectors/mysql.adoc
https://issues.redhat.com/browse/DBZ-2788
- Revert back DBZ-2775
- Introduce `ReadToInsertEvent` SMT.
@jpechane up for final review. Thanks.
=> DBZ-2788 Replace MySQL connector option with SMT for mitigating wrong op flag

documentation/modules/ROOT/pages/connectors/vitess.adoc
https://issues.redhat.com/browse/DBZ-3124
Update Vitess Connector Documentation: add Enum support.
=> DBZ-3124 Add ENUM support to Vitess documentation

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnector.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnector.java
In case of database connection validation failures, the logged message is at the  `INFO` level, without the stack trace or root cause in place.
```
2021-02-19 10:04:31,757 INFO  || Failed testing connection for
jdbc:mysql://xxxxx:3306/?useInformationSchema=true&nullCatalogMeansCurrent=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull
with user 'migration-user'  [io.debezium.connector.mysql.MySqlConnector]
```
This message is not useful in understanding or rectifying the issue.
Therefore, suggesting to log at the `ERROR` level along with the thrown
exception.
=> Log database connection validation failures at ERROR level with exception

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
https://issues.redhat.com/browse/DBZ-3151
I took the liberty to refactor this hook so that its generic for any connector that may require this in the future.  The Oracle connector needs a way to control that a system-generated unique index is to be excluded.
=> DBZ-3151 Add filter hook for table unique index resolution

documentation/modules/ROOT/pages/connectors/postgresql.adoc
Jira [DBZ-3195](https://issues.redhat.com/browse/DBZ-3195)
Added a missing `e` to the anchor id for the `truncate.handling.mode` property entry in the _Required connector configuration properties_ table in the PostgreSQL connector doc. The typo caused the downstream build to fail.
**Anchor string**: postgresql-property-**truncat**-handling-mode Missing an `e`.
**Link string**: postgresql-property-truncate-handling-mode
=> DBZ-3195 Correct typo in anchor id for entry in PG properties table

documentation/modules/ROOT/pages/connectors/postgresql.adoc
Jira [DBZ-3192](https://issues.redhat.com/browse/DBZ-3192)
Based on review input, updated the pronoun references that refer to the Debezium database user to mention the use _that_ is created in the PG database vs. the user _who_ is created.
=> DBZ-3192 Per review feedback, update pronoun references to DBZ db user.

documentation/modules/ROOT/pages/connectors/postgresql.adoc
Per the [DBZ-3197](https://issues.redhat.com/browse/DBZ-3197) enhancement request, this change adds information about how to use non-master accounts for PG logical replication by granting them the replication role.
Tested change via local Antora build.
=> DBZ-3197 Describe how to grant replication role to non-master account.

documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-3208
Associated PR in the incubator repository, https://github.com/debezium/debezium-incubator/pull/277
=> DBZ-3208 Document Oracle support for Boolean types

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-3190
* Option deprecated
* If provided, value continues to be used with warning logged
* If not provided, value will be resolved by database version
=> DBZ-3190 Deprecate database.tablename.case.insensitive option

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-3242
* Default value `0` disables the check
* Any negative value will show a configuration problem
* Any positive value over `0` will enable the retention check
=> DBZ-3242 Disable log.mining.transaction.retention.hours by default

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SignalsIT.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresMetricsIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SignalsIT.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java, debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java, debezium-core/src/main/java/io/debezium/pipeline/signal/Log.java, debezium-core/src/main/java/io/debezium/pipeline/signal/SchemaChanges.java, debezium-core/src/main/java/io/debezium/pipeline/signal/Signal.java, debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java, debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseSchema.java, debezium-core/src/main/java/io/debezium/relational/history/JsonTableChangeSerializer.java, debezium-core/src/test/java/io/debezium/pipeline/signal/SignalTest.java
https://issues.redhat.com/browse/DBZ-3141
Vitess failure handled in https://github.com/debezium/debezium-connector-vitess/pull/27
=> DBZ-3141 Support for signalling table

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Jira [DBZ-2122](https://issues.redhat.com/browse/DBZ-2122)
Adds capture job configuration for Db2. Although the information about the parameters is specific to Db2, the bulk of this material is conceptual and should be ready for reuse more or less as-is in sqlserver.adoc. I'll add a version of this material to the SQL Server connector doc after we agree on the conceptual content.
**UPDATE**:
Adds capture job configuration content for Db2 and SQL Server.
Tested in local upstream Antora build and downstream asciidoctor build.
=> DBZ-2122 Add Db2 and SQL Server topics about capture job configuration

documentation/modules/ROOT/pages/connectors/db2.adoc
Jira [DBZ-3259](https://issues.redhat.com/browse/DBZ-3259)
This change updates the Db2 connector doc to remove references to the Db2 docker container image, and apply standard prerequisites section formatting.
=> DBZ-3259 Remove references to upstream docker setup

documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Jira [DBZ-3273](https://issues.redhat.com/browse/DBZ-3273)
In reviewing a doc build to check updates to the Db2 doc, I noticed that several of the connectors had the same typo that had been corrected in the Db2 **Data change events** section where "converver" was used in place of "converter".
=> DBZ-3273 Correct typo repeated in mongodb, mysql, and sqlserver docs

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbErrorHandler.java
When connecting to the server or executing some queries, due to
networking issues, timeouts sometimes occur which would crash the whole
connector. By including a few extra exceptions in the error handler we
make sure it will retry in these situations.
I couldn't find any unit tests for this but let me know if something in the integration tests could be added.
Fixes https://issues.redhat.com/browse/DBZ-3278
=> DBZ-3278 Retry on MongoDB timeouts

documentation/modules/ROOT/pages/connectors/db2.adoc
Jira [DBZ-3272](https://issues.redhat.com/browse/DBZ-3272)
There ifdef/endif delimiters that enclose conditonal text in `db2.adoc` appear to be causing some problems for the splitter utility that breaks the upstream files into modular files when they're fetched to the downstream repo.
I updated the following instances where text is conditionalized for downstream-only use:
- Merged a pair of delimiters for the `product` conditional that were applied in succession (Lines 39 -54)
- Broke one set of delimiters that spanned topic boundaries into two separate sets (Lines 1518-1552).
I applied the change downstream already, and it remedied the problem. This change should be backported to the 1.4 branch to avoid regressions in case there's a need to refresh content.
=> DBZ-3272 adjust positions of delimiters for product conditionals

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/Filters.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/Filters.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-core/src/main/java/io/debezium/relational/ColumnFilterMode.java, debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java, debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java, debezium-core/src/main/java/io/debezium/relational/Tables.java, debezium-core/src/test/java/io/debezium/junit/relational/TestRelationalDatabaseConfig.java
https://issues.redhat.com/browse/DBZ-3271
Accompanied by these PRs in downstream repos:
* Vitess: https://github.com/debezium/debezium-connector-vitess/pull/30
* Db2: https://github.com/debezium/debezium-connector-db2/pull/14
=> DBZ-3271 Unifying filter handling across relational connectors

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlMetricsIT.java
https://issues.redhat.com/browse/DBZ-3304
=> DBZ-3304 Fix intermittent test failure

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
https://issues.redhat.com/browse/DBZ-3295
It was brought to our attention that certain operations such as COMMIT, ROLLBACK, MISSING_SCN, and DDL were not scoped to the defined SCN [start,end] window.  Additionally, the original change for DBZ-2875 in Beta2 would eventually lead to a situation where an event could be missed due to the SCN boundary being used in the LogMiner query.  Both of these have been addressed in this PR which should ultimately conclude changes needed for DBZ-2875.
=> DBZ-3295 Restrict all LogMiner results to specified SCN boundary

.github/workflows/release-contributors-list.yml, COPYRIGHT.txt, github-support/list-contributors.sh, jenkins-jobs/scripts/config/Aliases.txt
https://issues.redhat.com/browse/DBZ-2592
Re `https://github.com/r-ballard[unknown]`, this contributor has a `username` but no `Author name` in his GitHub profile, hence it returns `unknown`.
=> DBZ-2592 Minor improvements on the release contributors script

documentation/modules/ROOT/pages/development/engine.adoc
https://issues.redhat.com/browse/DBZ-2665
Originally added to the *obsolete* docs not the current one.
=> DBZ-2665 Add database history docs to new engine docs

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
https://issues.redhat.com/browse/DBZ-3319
Rather than relying on log switch detection by looking at the name of the current log file, this change uses the unique and always
increasing sequence to derive the log switch state to avoid any type of ambiguity.
=> DBZ-3319 Fix race condition with log switch detection

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/DmlParser.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/SimpleDmlParser.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/OracleDmlParserTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/ValueHolderTest.java
https://issues.redhat.com/browse/DBZ-3257
* Snapshot now emits clob/nclob values correctly (all adapters)
* Fixed bug with LogMiner emitting clob/nclob values when using new parser
=> DBZ-3257 Revert Clob behavior for Oracle LogMiner to avoid null values

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/legacy/SourceInfoTest.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresOffsetContext.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SourceInfoTest.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SourceInfoTest.java, debezium-core/src/main/java/io/debezium/connector/AbstractSourceInfo.java, debezium-core/src/main/java/io/debezium/connector/AbstractSourceInfoStructMaker.java, documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-2911
Adds a new "sequence" field to PostgresSQL sources to allow downstream
systems to deduplicate PostgreSQL records in O(1) time. The sequence
field is a stringified list, containing the last committed LSN and the
current LSN. A new integration test was added.
Note: I ended up adding this field as a string because I was unable to add it
as a struct or array. I tried doing so first, but found that adding non-scalar types
to the source object caused the `CloudEvents` tests to fail. It looks like
`CloudEvents` [only support scalar types](https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#type-system). Since no other type of source performs a
struct -> string conversion for `CloudEvents`, it seemed safer just to make it
a string.
=> DBZ-2911 Add additional LSN information to PostgreSQL sources

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SourceInfoTest.java
https://issues.redhat.com/browse/DBZ-2911
This fixes a regression with Oracle test suite after merging PR #2172.
=> DBZ-2911 Fix Oracle test compatibility

documentation/modules/ROOT/pages/connectors/postgresql.adoc
Jira [DBZ-3338](https://issues.redhat.com/browse/DBZ-3338)
Modifies code block formatting in Deployment section to fix a problem with an attribute reference in the block failing to resolve in the downstream product doc. Also includes other minor edits for consistency across the deployment instructions for the different connectors.
This is a follow on change to the change that I already merged into the downstream documentation. 
The primary change is conditionalized to be downstream only and has no effect on the upstream documentation. Edits in the Configuration example and Adding a configuration sections apply upstream.
Tested in a local Antora build to verify that content conditionalized for upstream, or that content is meant to be common, renders as expected.
=> DBZ-3338 Mirror downstream codeblock fix in PostgreSQL connector doc. Other consistency edits.

documentation/modules/ROOT/pages/connectors/postgresql.adoc
Jira [DBZ-3372](https://issues.redhat.com/browse/DBZ-3372)
Minor edits to the downstream content in the Deployment section of the PG connector doc. 
Tested the changes in a local Antora build to confirm that they are not visible in the upstream version of the content.
=> DBZ-3372 Add missing space and insert missing docker build command

documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Jira: [DBZ-3297](https://issues.redhat.com/browse/DBZ-3297) 
This change to the SQL Server connector doc propagates downstream corrections to the deployment instructions that were implemented in the PG connector doc in Q3 2020. The changes required some restructuring.
Tested in a local Antora build. Other than restructuring the content to eliminate one unnecessary heading level, the changes do not have any effect on the documentation that is rendered upstream.
=> Dbz 3297 user guide corrections for sqlserver connector

documentation/modules/ROOT/pages/connectors/mysql.adoc
Jira [DBZ-3402](https://issues.redhat.com/browse/DBZ-3402)
Remove duplicate entry for `mysql-property-skipped-operations` in MySQL properties table.
=> DBZ-3402 Remove duplicate entry in MySQL properties table

documentation/modules/ROOT/pages/connectors/mysql.adoc
Jira: [DBZ-3299](https://issues.redhat.com/browse/DBZ-3299)
This change to the MySQL connector documentation incorporates corrections to the deployment instructions that were made for the PG connector in Q3 2020, along with other changes for consistency with the documentation for other connectors. The changes include restructuring content.
Upstream, the restructuring changes and other minor changes are apparent in some places.
Changes are tested in a local Antora build and in a local downstream documentation build.
If possible, we should backport these changes to 1.4, as the corrections apply there.
=> Dbz 3299 user guide corrections for mysql connector

documentation/modules/ROOT/pages/connectors/db2.adoc
[DBZ-3298](https://issues.redhat.com/browse/DBZ-3298) 
This change to the Db2 connector documentation incorporates corrections to the deployment instructions that were made for the PG connector in Q3 2020. The changes include restructuring content.
Upstream, the restructuring changes and other minor changes are apparent in some places.
Changes are tested in a local Antora build and in a local downstream documentation build.
Please backport these changes to 1.4
=> DBZ-3298 Update Db2 connector instructions for accuracy/consistency

documentation/modules/ROOT/pages/connectors/mongodb.adoc
Jira [DBZ-3300](https://issues.redhat.com/browse/DBZ-3300)
Rework _Deployment_ section to incorporate general connector corrections. For consistency with other connectors, also moved the _Monitoring_ section so that I could append the _Configuration properties_ section to the _Deployment_ section.   
Tested in upstream and downstream builds. 
As with the deployment corrections for the other connector docs, this could be backported to 1.4; however, to reduce churn, I'd suggest waiting until the refactoring related to the modularization work for [DBZ-2334](https://issues.redhat.com/browse/DBZ-2334) is complete.
=> DBZ-3300 Incorporate deployment corrections in MongoDB connector doc

documentation/modules/ROOT/pages/configuration/content-based-routing.adoc, documentation/modules/ROOT/pages/configuration/filtering.adoc
Jira [DBZ-3411](https://issues.redhat.com/browse/DBZ-3411)
Reformats the first step in the product versions of the setup instructions for the _Content-based routing_ and _Filtering_ SMTs to eliminate a trailing period character that broke the URL for the Downloads site.  
This update has no effect on the content that is conditionalized for use in the community version of the documentation.
=> DBZ-3411 Reformat Downloads URLs to remove period characters.

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/BinlogReader.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
After successful merging https://github.com/debezium/debezium/pull/1920. It's time for optimizing connectors for this feature. Currently, we already Implemented fro MongoDB connector and MySQL. but the problem here is that when we did it on the connector side, it's not necessary to check it on the core again.
=> DBZ-3403 Semi Optimisation on MongoDB and MySQL connector for skipped.operations

documentation/modules/ROOT/pages/operations/monitoring.adoc
Jira [DBZ-3409](https://issues.redhat.com/browse/DBZ-3409)
AMQ content linked from the downstream Debezium _Monitoring_ topic was moved to a new location, breaking the existing link. Updated the link URL to use a new attribute that refers to the new AMQ title that now includes the target content. 
I successfully tested the change in a downstream build. 
This change has no effect on the documentation that's exposed upstream.
=> DBZ-3409 Fix links to Streams content in downstream doc.

documentation/modules/ROOT/pages/configuration/topic-auto-create-config.adoc
Jira [DBZ-3414](https://issues.redhat.com/browse/DBZ-3414)
Because no link text was added to an xref declaration, two adjacent sentences that contained links were getting merged together when the topic was rendered in the downstream product doc. After adding the link text, I tested the topic in a local downstream build and both links function properly. 
The links already functioned in the upstream Antora build. I ran a local build and verified that they continue to function as expected.
=> DBZ-3414 Add absent link text to xref in auto-topic creation content

documentation/modules/ROOT/pages/configuration/filtering.adoc
[DBZ-3415](https://issues.redhat.com/browse/DBZ-3415)
Correct erroneous expansion of SMT from "simple" message transform to "single" message transform.
=> DBZ-3415 Correct expansion of "SMT" acronym in filtering doc

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java
https://issues.redhat.com/browse/DBZ-3413
Double single quotes are treated as 2 quotes instead of 1 escaped quote in the WHERE clause parsing function. Small change to fix this and added a unit test.
=> DBZ-3413 Handle double single quotes in LogMinerDmlParser

documentation/modules/ROOT/pages/connectors/oracle.adoc
Lately, the script for fetching content for use downstream began complaining about unmatched conditional delimiters. This change standardizes the format of a conditional statement to align it with what the script typically expects.
=> [docs] Modify conditional delimiter in attempt to fix downstream error.

README.md, debezium-api/pom.xml, debezium-connector-mongodb/pom.xml, debezium-connector-mysql/pom.xml, debezium-connector-oracle/pom.xml, debezium-connector-postgres/pom.xml, debezium-connector-sqlserver/pom.xml, debezium-ddl-parser/pom.xml, debezium-parent/pom.xml, debezium-server/debezium-server-core/pom.xml, debezium-server/debezium-server-pulsar/pom.xml, debezium-server/debezium-server-redis/pom.xml, pom.xml
https://issues.redhat.com/browse/DBZ-3449
@Naros, @rk3rn3r, @jpechane, this allows to build the connector archives/JARs as quickly as possible via `mvn clean verify -Pquick`, without having to remember all the individual options for skipping plug-ins. Saw this in Quarkus and think it's a great idea, e.g. if you want to build the archives for manual testing in KC.
=> DBZ-3449 Adding "quick" profile

documentation/modules/ROOT/pages/configuration/content-based-routing.adoc
[DBZ-3412](https://issues.redhat.com/browse/DBZ-3412)
An attribute string in an internal cross reference link failed to resolve downstream. 
I replaced the series of attributes in the link with a basic xref statement. 
Tested in local upstream and downstream doc builds and confirmed that the link works in both instances.
=> DBZ-3412 Fix internal cross-reference link in content-based-routing doc

documentation/modules/ROOT/pages/configuration/topic-routing.adoc
[DBZ-3410](https://issues.redhat.com/browse/DBZ-3410)
Per my comments in the Jira, this change might _adequately_ resolve the issue with broken links in the SMT routing options table. I've tested the updated links locally in the upstream and downstream builds and the links _very nearly_ work as intended.
Links beginning in the row for the `key.field.name` entry behave slightly differently than the entries in the earlier rows in that, when you click the associated links, the entries don't pop to the top of the window like the earlier entries.
However, the link URL for the entries do display in the browser address box, and if you copy the URL to a new browser, because the three entries `key.field.name`, `key.field.regex`, and `key.field.replacement` are adjacent to one another, you can see …
=> DBZ-3410 Fix broken table links

documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-3393
=> DBZ-3393 Document `log.mining.strategy` for Oracle connector

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/integrations/cloudevents.adoc
[DBZ-3518](https://issues.redhat.com/browse/DBZ-3518)
This change removes the dual anchor IDs in subtopics of the Db2 metrics section, a change that is consistent with similar sections in the other connector docs. The downstream tooling cannot parse the dual IDs, preventing the files from being split for downstream modular use, and preventing the subtopics from displaying in the table of contents.
This change also corrects formatting in the table of CloudEvents options to place the anchor IDs inside of the associated table cells. 
Tested in a local Antora build. No content changes.
=> DBZ-3518 Update formatting to correct rendering and linking problems

documentation/modules/ROOT/pages/operations/logging.adoc
[DBZ-3502](https://issues.redhat.com/browse/DBZ-3502)
This change updates a link in content that is conditionalized for product use only and modifies the wording of the sentence that contains the link. The change is necessary for the Q3 release of Debezium, because the former target topic in the Streams 7.7 doc was moved when the Streams doc was restructured for its 2021.Q2 release.
=> DBZ-3502 Update link to Streams Kafka Connect logging properties content

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceTimestampMode.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeTablePointer.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
See [DBZ-3452](https://issues.redhat.com/browse/DBZ-3452).
1. When `source.timestamp.mode=commit`, instead of fetching the timestamp of each LSN individually, the connector will them alongside the CDC data.
2. `SqlServerConnection#lsnToInstantCache` has been removed as no longer needed.
This is a working solution from the performance improvement standpoint, but API-wise it might need some improvement:
1. `SourceTimestampMode#getTimestamp()` currently requires both `SqlServerConnection connection` and `Clock`, although only one of them is used by each mode. Ideally, instead of being part of the method signature, those should be replaced with dependencies injected via a constructor but it probably won't work with constants. A better solution might be to create a factory method that would …
=> DBZ-3452: source.timestamp.mode=commit imposes a significant performance penalty

documentation/modules/ROOT/pages/connectors/mongodb.adoc
Hello,
First, thanks for making this project open source. It is such a great piece of software.
While I was playing with it and try to configure a mongodb connector, I noticed that the json example to configure a mongodb connector is not valid. There is an unnecessary comma at the end of the payload.
Here is a minor contribution that could help and could save some time for the future users.
=> [docs] fix typo in mongodb connector example

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
https://issues.redhat.com/browse/DBZ-3256
This PR addresses moving the log resolution to a single query to address the following concerns:
* Moves de-duplication to database using SQL query, i.e. no duplicate SCN ranges
* Provides a consistent view of logs rather than relying on multiple queries
=> DBZ-3256 Consolidate Oracle redo/archive log queries

debezium-connector-oracle/pom.xml
https://issues.redhat.com/browse/DBZ-3539
I believe this should restore the exclusion of the dependency in the distribution to behave in the same way prior to DBZ-3365.
=> DBZ-3539 Mark xstream dependency scope as provided

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/AbstractStreamingAdapter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleChangeEventSourceFactory.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/StreamingAdapter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerAdapter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamAdapter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleOffsetContextTest.java, debezium-core/src/main/java/io/debezium/config/Instantiator.java
https://issues.redhat.com/browse/DBZ-2203
https://issues.redhat.com/browse/DBZ-3240
=> DBZ-3240 Remove `database.tablename.case.insensitive` deprecated option

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-3525](https://issues.redhat.com/browse/DBZ-3525)
This change corrects the link targets for cross-references to the AMQ Streams documentation. The links broke after the Streams docs were refactored and the target topics were moved from the _Using_ guide to the _Deploying and Upgrading_ guide.  
In searching for instances where the incorrect links were used, I realized that the introductory content and prerequisites in the downstream _Deploying_ topics lacked consistency across the different connectors, so I made changes to address the inconsistencies. 
There's also a metadata change to the MongoDB content to correct the way that the file is split when it's fetched for downstream use.  As part of this change, I removed the `[[mongodb-fault-tolerance]]` anchor id that was one of two …
=> DBZ-3525 Fix link, standardize intro and prereqs in `Deploying` topics.

documentation/modules/ROOT/pages/connectors/mysql.adoc
[DBZ-3582](https://issues.redhat.com/browse/DBZ-3582)
Per the documentation change made for [DBZ-3572](https://issues.redhat.com/browse/DBZ-3572), for Debezium 1.5 and later the MySQL connector now refers to streaming metrics rather than binlog metrics. To mirror that update downstream, this change modifies annotation comments in `mysql.adoc` that control the downstream titles and anchor IDs to also refer to streaming metrics.
=> DBZ-3582 Update downstream MySQL doc to refer to streaming metrics

CONTRIBUTE.md
I was following [CONTRIBUTE.md](https://github.com/debezium/debezium/blob/master/CONTRIBUTE.md) instructions to setup Debezium locally and it incurred into an error, since JDK 8 is no longer supported. I'm opening this PR to reflect the change.
I've also edited some parts of the GitHub pull request instructions because the path described there is not available anymore, after some Github UI changes.
=> Update CONTRIBUTE.md to reflect the new version of required tools and github pull request path

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFile.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperTest.java
https://issues.redhat.com/browse/DBZ-3563
This Oracle RAC deployments this de-duplication logic and previous iterations were not compliant and lead to duplicate log files being added to the mining session, thus resulting in ORA-01289 errors.  This PR adjusts the de-duplication logic to rather be based upon the atomically assigned log sequence number, which will guarantee we don't mine multiple logs with the same sequence.
=> DBZ-3563 Deduplicate logs based on sequence number and not scn ranges

documentation/modules/ROOT/pages/configuration/outbox-event-router.adoc
[DBZ-3569](https://issues.redhat.com/browse/DBZ-3569)
Minor update to remove TP statement and filter out content about tracing from the productized documentation. 
This issue will be followed up by  [DBZ-3227](https://issues.redhat.com/browse/DBZ-3227) to provide information about how to use predicates to configure the SMT.
=> Dbz 3569 promote outbox event router to ga

.github/workflows/server-workflow.yml, debezium-connector-postgres/pom.xml, debezium-quarkus-outbox/deployment/pom.xml, debezium-quarkus-outbox/runtime/pom.xml, debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/EventDispatcher.java, debezium-server/debezium-server-core/src/main/java/io/debezium/server/ConnectorLifecycle.java, debezium-server/debezium-server-core/src/test/java/io/debezium/server/TestConfigSource.java, debezium-server/debezium-server-pravega/pom.xml, debezium-server/pom.xml, pom.xml
https://issues.redhat.com/browse/DBZ-3550
* Upgrades Quarkus dependency to 2.0.0.Alpha3
* Fixes dependency issues in outbox extension pom
* Remove deprecated usages of OpenTracing API
This is marked as a draft PR as we're awaiting on the official release of Quarkus 2.0.0.Final in early June.
=> DBZ-3550 Upgrade to Quarkus 2.0

documentation/modules/ROOT/pages/integrations/outbox.adoc
`artifactId` was spelled incorrectly.
=> Fix typo in outbox.adoc

documentation/modules/ROOT/pages/integrations/outbox.adoc
I already created a PR (#2461), that got merged, but I've just seen, that it was only for version `1.5`.
So here's the PR for the master branch.
=> Fix typo in outbox.adoc (on branch master)

debezium-server/debezium-server-pravega/src/main/java/io/debezium/server/pravega/PravegaChangeConsumer.java
During manual testing of the Pravega sink, I found that I didn't set the default value of the `debezium.sink.pravega.transaction` config to false, as was intended & documented (https://debezium.io/documentation/reference/operations/debezium-server.html#pravega-transaction).
=> DBZ-3546 default debezium.sink.pravega.transaction to false

debezium-bom/pom.xml, debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/ApicurioTestResourceLifeCycleManager.java, debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumContainer.java, debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java, documentation/antora.yml
https://issues.redhat.com/browse/DBZ-3171
Requires debezium/connect:1.6 image built with https://github.com/debezium/docker-images/pull/230
=> DBZ-3542 Use Apicurio 2.0

COPYRIGHT.txt, documentation/modules/ROOT/pages/configuration/content-based-routing.adoc, documentation/modules/ROOT/pages/configuration/signalling.adoc, documentation/modules/ROOT/pages/configuration/topic-routing.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc, documentation/modules/ROOT/pages/integrations/cloudevents.adoc, documentation/modules/ROOT/pages/operations/monitoring.adoc
@roldanbob, this PR backports a few docs issues which fell through the cracks so far:
* https://issues.redhat.com/browse/DBZ-3402
* https://issues.redhat.com/browse/DBZ-3416
* https://issues.redhat.com/browse/DBZ-3300
* https://issues.redhat.com/browse/DBZ-3412
* https://issues.redhat.com/browse/DBZ-3410
* https://issues.redhat.com/browse/DBZ-2334
* https://issues.redhat.com/browse/DBZ-3518
* A range of [docs] commits
Could you build upstream and downstream docs from this PR and see whether this looks good? In general, let's make sure that:
* Any Jira issue that needs backporting has a comment stating that fact
* Any change that needs backporting has a Jira issue (I feel the number of issues solely tagged with [docs] here is too large, this should only really be the case for small-ish …
=> 1.5 docs backport

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/AlterTableParserListener.java
https://issues.redhat.com/browse/DBZ-3612
Using MySQL as a guide, I added a similar check to the `ALTER TABLE` listener to silently return and ignore these DDL events if the table is not known to the connector, logging a message on debug level for visibility.
=> DBZ-3612 Do not parse Oracle ALTER TABLE ddl for unknown tables

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/TransactionalBuffer.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-3616
This addresses 2 core issues:
* Avoid logging warnings unnecessarily
* Only emit DDL changes once, avoid re-emission when doing re-mining since older SCNs.
=> DBZ-3616 Avoid logging processed trx warnings & emit DDL changes once

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/SourceInfo.java
I see every SourceInfo is public, except for mysql
=> DBZ-3638 Modify Mysql SourceInfo to be public

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
https://issues.redhat.com/browse/DBZ-3631
This is a small follow-up on DBZ-3631.  During testing those changes with Xstream, a small inconsistency was identified where Xstream emitted empty strings and empty byte buffer values for CLOB/BLOB respectively if the fields were being set to NULL where-as LogMiner emitted actual `null` values.  This follow-up makes that behavior consistent across both adapters to emit `null`.
=> DBZ-3631 Fix Xstream to emit NULL BLOB/CLOB values when fields explicitly set to NULL like LogMiner implementation did.

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-3634
So at the core this PR allows `DatabaseHistory.STORE_ONLY_CAPTURED_TABLES_DDL` to influence where the DDL predicate is placed in the LogMiner query.  If the setting is false, the behavior remains unchanged from the way the connector behaves now.  If the setting is true, the DDL events are predicated against the schema and table include/exclude lists.
In conjunction with this change, I took the opportunity to do a small refactor:
* All methods that relate to building the LogMiner query were moved to LogMinerQueryBuilder & removed from SqlUtils
* All tests related to LogMiner queries were moved to LogMinerQueryBuilderTest & removed from SqlUtilsTest
* The query was reworked have a slightly better SQL explain plan than before
*
=> DBZ-3634 Enable DDL events to be filtered by include/exclude lists

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/TransactionalBuffer.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SnapshotDatatypesIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/StreamingDatatypesIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionalBufferTest.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-3645
=> DBZ-3645 Make Oracle LOB support opt-in

documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-3651
- Split LOB data types into separate table
- Mark LOB data types as incubating
=> DBZ-3651 Oracle LOB documentation updates

documentation/modules/ROOT/pages/configuration/avro.adoc
[DBZ-3430](https://issues.redhat.com/browse/DBZ-3430)
The Localization detected broken links in the Debezium documentation and requested updates. 
Links in the downstream content in `avro.adoc` pointed to the discontinued _Getting Started with Service Registry_ document. This change updates the links so that they now point to the replacement guide, _Installing and Deploying Service Registry on OpenShift_. 
This change modifies only content that is conditionalized for downstream use. 
I tested the change on a local Antora build and confirmed that there is no effect on the upstream _Avro Serialization_ chapter.
If possible, please backport this to 1.5.
=> DBZ-3430 Update links to point to new Service Registry Install guide

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java
https://issues.redhat.com/projects/DBZ/issues/DBZ-3770
DBZ-3770 Optimize ObjectMapper initialization by replacing repeated initialization with one time initilization in PostgreSQL `SourceInfo.sequence()`. Overall Performance Improvement of approx 5% - 15%.
Performance Benchmark was done for 1M row CDC events on a table with 4 columns (NOOP DebeziumEngine.notifying)
<div class="table-wrap">
.sequence() | Before | After | Diff
-- | -- | -- | --
1M Rows | 2,879 ms (9.4%) | 256 ms (1.1%) | -88.9% (x11.2 improvement)
</div>
**Before Optimization**
**After Optimization**
JMH Benchmarks
```
Benchmark                                        Mode  Cnt        Score        Error  Units
PostgresConnectorConfigPerf.benchmark_1_before  thrpt    3   550040.596 ±  16847.245  ops/s …
```
=> DBZ-3770 Optimize ObjectMapper initialization by replacing repeated initialization with one time initilization

documentation/modules/ROOT/pages/connectors/mysql.adoc
[DBZ-3140](https://issues.redhat.com/browse/DBZ-3140)
This change inserts a note conditionalized for the downstream product doc to mirror the upstream note that informs users about the new Tech Preview capturing implementation for the MySQL connector.  
I tested the new content in an local Antora build and confirmed that it is not rendered in the upstream version.
Please backport this change to the 1.5 branch.
=> DBZ-3140 Insert downstream note about new MySQL capturing implementation

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-3772](https://issues.redhat.com/browse/DBZ-3772)
This change harmonizes the deployment instructions for the Oracle connector with the instructions that we provide for the other Debezium connectors, including conditionalizing steps for exclusive upstream or downstream use.
Tested in a local Antora build. Also tested that the annotations for splitting the file for downstream use return the expected results, and that the conditionalization behaves as expected.  
Please backport these changes to the 1.5 branch.
=> Dbz 3772 update oracle connector deployment instructions

documentation/modules/ROOT/pages/integrations/outbox.adoc
[DBZ-3649](https://issues.redhat.com/browse/DBZ-3649)
Add self-referencing links for entries in tables of properties.
Tested change in local Antora build.
This change affects the upstream content only and is not part of the downstream product documentation.
=> DBZ-3649 Add self-referencing links to properties

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-3802](https://issues.redhat.com/browse/DBZ-3802)
The connector property column.mask.hash.with.salt is used with several of connectors, but the description in the documentation for each connector differs slightly. Updated the information. This change synchronizes the descriptions in the documentation for the Db2, MySQL, PostgreSQL, and SQL Server connectors.
=> DBZ-3802 Describe  column.mask.hash.with.salt property consistently

debezium-server/debezium-server-kinesis/src/main/java/io/debezium/server/kinesis/KinesisChangeConsumer.java
https://issues.redhat.com/browse/DBZ-3827
Address issue of a record value potentially being `null` by defining an empty string to ensure `getBytes()` passes as expected.
=> DBZ-3827 Debezium Server Kinesis Sink Cannot Handle Null Events

debezium-server/debezium-server-dist/src/main/resources/distro/run.sh
https://issues.redhat.com/browse/DBZ-3840
Debezium Server's `run.sh` startup script fails on Windows due to a difference in path separators between Windows (";") and Linux (":").
This fix allows `run.sh` to succeed on Git Bash for Windows, Cygwin, MinGW, and MSYS2.
=> DBZ-3840 allow run.sh to work on Cygwin, MinGW & MSYS2

debezium-server/debezium-server-bom/pom.xml
https://issues.redhat.com/browse/DBZ-3841
Pravega 0.9.1 was released in June 2021.
=> DBZ-3841 upgrade Pravega to 0.9.1

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-3407](https://issues.redhat.com/browse/DBZ-3407)
Add annotation comments and other edits to prepare doc for downstream use.
Changes tested in local Antora and downstream builds
This change needs to be backported to 1.5.
=> DBZ-3407 Add metadata, style/usage edits to support doc productization

documentation/modules/ROOT/pages/configuration/signalling.adoc
The `id` column holds UUID in string form (36 characters) and can be appended with suffix `-open` or `-close` (a maximum of 6 characters); so 42 characters would be the minimal length of the `id` column.
=> DBZ-3867 Signaling table id column too small in example

debezium-parent/pom.xml, debezium-testing/debezium-testing-system/pom.xml
https://issues.redhat.com/browse/DBZ-3824
=> DBZ-3824 NoClassDefFoundError for junit platform 

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
[DBZ-3870](https://issues.redhat.com/browse/DBZ-3870)
1) Reuse parsed TableId to avoid expensive PostgresSchema.parse() call
2) Immediate conditional return in synchronizeTableSchema() call
=> DBZ-3870 PostgreSQL - Performance Improvements in PostgresChangeRecordEmitter

documentation/modules/ROOT/pages/configuration/content-based-routing.adoc, documentation/modules/ROOT/pages/configuration/outbox-event-router.adoc, documentation/modules/ROOT/pages/configuration/topic-auto-create-config.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-3858](https://issues.redhat.com/browse/DBZ-3858)
This change modifies the format of links that caused build failures downstream that required manually fixing each of the dozen or so links every time that I refreshed content from the upstream branch. The links in question each targets an anchor ID that differs in the upstream and downstream documentation, and I suspect that the way the links were constructed prevented the fetch script from converting the links for downstream use. Not 100% sure that the update will completely resolve the problem. 
I verified that the links in the upstream content work as expected in a local Antora build.
=> DBZ-3858 Fix links in topic auto-create, CBR, outbox & connector docs

debezium-connector-sqlserver/pom.xml, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceTimestampMode.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
See [DBZ-3479](https://issues.redhat.com/browse/DBZ-3479).
The current implementation works like this:
```sql
SELECT tran_begin_time,
CURRENT_TIMEZONE() AS TZ,
tran_begin_time AT TIME ZONE 'UTC' AS UTC
FROM testDB.cdc.lsn_time_mapping;
```
And yields the results like the following:
```
tran_begin_time         TZ                                      UTC
----------------------- --------------------------------------- ------------------------------
2021-04-28 16:26:36.387 (UTC-08:00) Pacific Time (US & Canada)  2021-04-28 16:26:36.387 +00:00
2021-04-28 16:26:36.360 (UTC-08:00) Pacific Time (US & Canada)  2021-04-28 16:26:36.360 +00:00
2021-04-28 16:26:43.293 (UTC-08:00) Pacific Time (US & Canada)  2021-04-28 16:26:43.293 +00:00
2021-04-28 16:26:45.347 (UTC-08:00) Pacific Time (US & Canada) …
```
=> DBZ-3479: Rework handling timezones in SQL Server connector

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/logwriter/RacCommitLogWriterFlushStrategy.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-3813
So the underlying core problem here was that the user did not provide a `database.port` but instead only a `database.url`.  This caused a regression when using the connector in RAC mode because the RAC connections expected a PORT value to be supplied but it was not available.
This also raised a valid concern that a RAC node does not have to be configured with the same port across the entire cluster.  In fact, Node A could use port 1521 while Node B uses port 1522.  Unfortunately, the connector's RAC code didn't support this scenario at all, so this PR aims to address both the above and this concern.
* If `rac.nodes` is not provided, no special validation occurs.
* If `rac.nodes` is provided and an entry has no port, `database.port` must be …
=> DBZ-3813 Add `rac.nodes` port validation

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceTimestampMode.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnector.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
See [DBZ-3823](https://issues.redhat.com/browse/DBZ-3823).
See https://github.com/debezium/debezium/pull/2572#issuecomment-896977723.
<details>
<summary>Previous approach:</summary>
1. (optional) Do not wrap `SQLException` thrown from within `SqlServerConnection` constructor into a `RuntimeException`. This simplifies retriable error handling and should improve the user experience. The previously thrown "Couldn't obtain database name" error doesn't really provide any useful information to the operator. On the contrary, it makes them scroll one page down to get to the underlying connection error.
2. Use the error handler to convert the exception thrown during `BaseSourceTask#start(config)`. Otherwise, it's never a `RetriableException`.
3. Catch `RetriableException` in …
=> DBZ-3823 SQL Server connector doesn't handle retriable errors during task start

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnector.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerPartition.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SchemaHistoryTopicIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotWithSelectOverridesIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectionIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorConfigTest.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerPartitionTest.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TransactionMetadataIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java, debezium-core/src/main/java/io/debezium/config/Configuration.java, debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
**Key highlights**:
1. The SQL Server connection used by the task no longer `USE`s any database and ignores the `DATABASE` parameter when building the JDBC connection string. All object names used in SQL statements must be fully qualified.
2. As a result, the test connection used by integration tests has to execute `USE testDB` upon connecting to the instance. Whether this is temporary or not will depend on what we decide to do with the test suite later on.
3. The connection has to be explicitly tested by the connector since the real database name is no longer retrieved from within the connection constructor, and even though `getSqlServerVersion()` still attempts to connect, it won't throw an exception if it fails. We may want to reconsider this design and let it throw an exception …
=> DBZ-2975: Use fully-qualified table and procedure names

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/OracleDdlParser.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/AlterTableParserListener.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDdlParserTest.java
https://issues.redhat.com/browse/DBZ-3896
This PR supersedes #2616 by not only enabling the semicolon terminator in Oracle multi-statement table DDL queries but it also supports detecting primary key changes using indexes in conjunction with `ALTER TABLE` such as:
```
CREATE TABLE sample (id NUMBER(*,0), DATA varchar2(25));
CREATE UNIQUE INDEX sample_pk ON sample ("ID");
ALTER TABLE sample ADD CONSTRAINT idx_sample_pk PRIMARY KEY ("ID") USING INDEX "SAMPLE_PK";
```
=> DBZ-3896 Support multi-statement table DDLs

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-schema-history-metrics.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc
Add content to shared file that specifies when snapshot metrics are exposed. Also move information about MBean for each metric type from the connector files to the shared file.
Do we want to backport this to 1.6 for the next downstream release?
=> DBZ-3613 Specify when snapshot metrics are available.

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java, debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
It shouldn't be needed as we select from a single table, and it caused the columns to not be found for the Db2 connector.
https://issues.redhat.com/browse/DBZ-2525
This is causing Db2 tests to fail (see https://github.com/debezium/debezium-connector-db2/pull/32).
=> DBZ-2525 Don't qualify selected columns with table name;

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotContext.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java
https://issues.redhat.com/browse/DBZ-3947
Related to https://issues.redhat.com/browse/DBZ-3577
Check heartbeat reaching low watermark in case the high watermark is empty(no binlog events between watermarks)
=> DBZ-3947 Fix empty high watermark check

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-3961](https://issues.redhat.com/browse/DBZ-3961)
Add note to the Transaction metadata sections in each of the connector docs to inform users that the connectors capture transaction metadata only for operations that occur after the connector is deployed. 
This change implements input that was originally proposed in PR #2657 (DBZ-3845).
=> DBZ-3961-specify-when-connectors-begin-to-collect-metadata

jenkins-jobs/pipelines/deploy-snapshots.groovy, jenkins-jobs/pipelines/downstream_apicurio_prepare_pipeline.groovy, jenkins-jobs/pipelines/downstream_prepare_pipeline.groovy, jenkins-jobs/pipelines/release-pipeline.groovy, jenkins-jobs/pipelines/rhel_downstream_prepare_pipeline.groovy, jenkins-jobs/scripts/build-connect-image.sh, jenkins-jobs/scripts/build-rhel-kafka-image.sh, jenkins-jobs/scripts/copy-images.sh, jenkins-jobs/scripts/release-pipeline.groovy
https://issues.redhat.com/browse/DBZ-3690
Unfortunately, Scope under RHEL8/Centos 8  is colliding with our externally installed docker due to dependency on containerd.io.
This PR
- removes the usage of Scopeo replacing it with plain docker 
- uses centos user in release scripts
=> DBZ-3690 Removing scopeo usage and cleaning utility scripts

debezium-core/src/main/java/io/debezium/relational/TableId.java, debezium-core/src/main/java/io/debezium/relational/TableIdParser.java, debezium-microbenchmark/src/main/java/io/debezium/performance/core/TableIdPerf.java
[DBZ-4015](https://issues.redhat.com/browse/DBZ-4015) Efficient String Replacement using String.replace in TableIdParser (improvement of x4-x5 times)
(https://medium.com/javarevisited/micro-optimizations-in-java-string-replaceall-c6d0edf2ef6)
Previously 1.5s - 2.5s is spent on `TableIdParser.parse` for 10M records of Incremental CDC which is around 15% - 25% of overall time taken (8s). Based on `String.replace` optimizations from Java 9, simply switching from `String.replaceAll` to `String.replace` would reduce the time spend on `TableIdParser.parse` by x4-x5 times. Corresponding JMH metrics are included for verifying performance improvement.
**JMH Benchmarks**
```java
package io.debezium.relational;
import io.debezium.text.TokenStream;
import org.openjdk.jmh.annotations.*;
import …
```
=> DBZ-4015 Efficient String Replacement using String.replace in TableIdParser (improvement of x4-x5 times)

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotContext.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/ExecuteSnapshotKafkaSignal.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/KafkaSignalThread.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java, debezium-core/src/main/java/io/debezium/pipeline/signal/ExecuteSnapshot.java, documentation/modules/ROOT/pages/connectors/mysql.adoc
An alternative way to signalling table mechanism to execute an incremental snapshot using Kafka topic configured with `signal.kafka.topic` property when the MySQL connection is read-only.
Test failures fix is covered by https://github.com/debezium/debezium/pull/2653
Related to https://issues.redhat.com/browse/DBZ-3577
=> DBZ-3948 Support kafka topic based signals

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-3603](https://issues.redhat.com/browse/DBZ-3603)
Reword description of the property and apply it consistently across the connector docs, add example, correct error in PG description, and remove reference to setting a point for resuming snapshots.
Also made a general update to properties tables to explicitly specify when a property has no default, per [DBZ-3327](https://issues.redhat.com/browse/DBZ-3327).    
Tested changes in a local Antora build.
=> DBZ-3603 Add example for snapshot.select.statement.overrides property

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresMetricsIT.java, debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java
https://issues.redhat.com/browse/DBZ-3887
Major improvements for Throughput Bottleneck and Inefficient Batching in ChangeEventQueue
(Replaced naive metronome.pause and Thread.sleep with efficient wait() and notify())
- x10 - x100 Improvements in overall throughput
- Efficient batching based on maxBatchSize
This improvement would be visible across all supported databases
**Snapshot Benchmark**
```java
package io.debezium.connector.postgresql;
import io.debezium.config.CommonConnectorConfig;
import io.debezium.config.Configuration;
import io.debezium.connector.postgresql.PostgresConnectorConfig.LogicalDecoder;
import io.debezium.embedded.Connect;
import io.debezium.embedded.EmbeddedEngine;
import io.debezium.engine.ChangeEvent;
import io.debezium.engine.DebeziumEngine;
import …
```
=> DBZ-3887 Major improvements for Throughput Bottleneck and Inefficient Batching in ChangeEventQueue

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/CreateTableParserListener.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java
https://issues.redhat.com/browse/DBZ-4037
This avoids the connector failing when a DDL statement contains a `RAW` column data type.  Instead, the connector will properly handle the unsupported column type by simply logging a warning about the unsupported type and still permitting the capture of changes for the table for other column data types that are supported.
=> DBZ-4037 Gracefully handle unsupported RAW data types

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/InfinispanLogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-4067
It is not guaranteed that the flush strategy will force all LGWR buffer entries to be written to the redo logs in which case the mining boundaries must then be calculated based on the lastProcessedScn rather than the current batch endScn. This prevents event loss between mining sessions when this timing scenario occurs.
@jpechane This is the fix for the `IncrementalSnapshotIT` tests failing.  Could you give this a try against your Oracle 12 env as well to verify that it solves the problem?  I've ran the tests locally against both Oracle 12 and 19 using the memory & infinispan buffer types and all tests have passed.
=> DBZ-4067 Correctly calculate mining session boundaries

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-4067
It is not guaranteed that the flush strategy will force all LGWR buffer entries
to be written to the redo logs in which case the mining boundaries must then be
calculated based on the lastProcessedScn rather than the current batch endScn.
This prevents event loss between mining sessions when this timing scenario
occurs.
(cherry-picked from commit 582a169f928b9c97510d6fe43f8c5d1061bb176c)
=> [1.6] DBZ-4067 Correctly calculate mining session boundaries

debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java, debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterConfigDefinition.java, debezium-core/src/main/java/io/debezium/transforms/outbox/SchemaBuilderUtil.java, debezium-core/src/main/java/io/debezium/transforms/outbox/StructBuilderUtil.java, debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java, documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc
This is a first step of [DBZ-1297](https://issues.redhat.com/browse/DBZ-1297) for managing transformation of an escaped JSON string into JSON, inferring the connect Schema from the JSON document structure. 
This allow the Outbox Event Router to directly produce JSON message on Kafka like:
```json
{
"id": 1, "lineItems": [{"id": 1, "item": "Debezium in Action", "status": "ENTERED", "quantity": 2, "totalPrice": 39.98}, {"id": 2, "item": "Debezium for Dummies", "status": "ENTERED", "quantity": 1, "totalPrice": 29.99}], "orderDate": "2019-01-31T12:13:01", "customerId": 123
}
```
This option is off by default and can be turned-on using: `transforms.outbox.debezium.expand.json.payload=true`
=> DBZ-1297 Expand JSON escaped string as JSON

.github/workflows/mongodb-workflow.yml
It's still tested via Jenkins, plus it's unsupported by now.
@jpechane
=> [ci] Don't test with MongoDB 3.2 on GH Actions;

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-4077
The Oracle test suite failed with a NPE after the introduction of the DBZ-4077 code changes to main.  This PR supplements the original work by addressing the NPE failure.
=> DBZ-4077 Fix NPE with Oracle test suite

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDdlParserTest.java
https://issues.redhat.com/browse/DBZ-4233
While working on DBZ-3710, I uncovered that we are not correctly deriving the length for CHAR and NCHAR data types when we parse a DDL statement.  This PR makes adjustments to the DDL parser code and adjusts the faulty test that masked the problem in the first place.
=> DBZ-4233 CHAR / NCHAR precision not derived from DDL

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java, debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
The sp contains query statement which have `select` and `where` statements, but without`from` statment, cause this parser error.
sp:
CREATE DEFINER=`system_user`@`%` PROCEDURE `update_order`(IN orderID bigint(11))
BEGIN    insert into order_config(order_id, attribute, value, performer)
**SELECT** orderID, 'first_attr', 'true', 'AppConfig'
**WHERE** NOT EXISTS (select 1 from inventory.order_config t1 where t1.order_id = orderID and t1.attribute = 'first_attr') OR
EXISTS (select 1 from inventory.order_config p2 where p2.order_id = orderID and p2.attribute = 'first_attr' and p2.performer = 'AppConfig')
ON DUPLICATE KEY UPDATE value   = 'true',
performer   = 'AppConfig';    -- Enable second_attr for order
insert into order_config(order_id, attribute, value, performer)
select orderID, …
=> DBZ-4229 CREATE PROCEDURE DDL throws ParsingException

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/IncrementalSnapshotChangeEventSource.java
Processing transaction started/committed events in MySQL read-only incremental snapshot allows making progress faster in case there are too few other binlog events
https://issues.redhat.com/browse/DBZ-4197
=> DBZ-4197 Process transaction started/committed in read-only incremental snapshot

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/marshalling/TransactionAdapter.java
https://issues.redhat.com/browse/DBZ-4159
As noted in the attached Jira comments, during the backport of DBZ-4159 to 1.7.1.Final, the format needed to be adjusted so that the protobuf fields were sequentially ordered.  This means since username is not in 1.7 that the number of events needed to be listed as field 4.  Ergo, so that the 1.7.1.Final format is forward compatible with 1.8, the username and number of events order needed to be reversed for 1.8 to account for that.
=> DBZ-4159 Make Oracle Infinispan trx cache layout forward compatible

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java, debezium-connector-mysql/src/test/resources/ddl/incremental_snapshot_test.sql, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSignalBasedIncrementalSnapshotChangeEventSource.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedIncrementalSnapshotChangeEventSource.java, debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedSnapshotChangeEventSourceTest.java, debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
Refer the discussion from [DBZ-4107](https://issues.redhat.com/browse/DBZ-4107?filter=12358727)
I have implemented the [option 1] to support incremental snapshot for without pk tables, add the method getKeyMapper() instead of "table.primaryKeyColumns()" in AbstractIncrementalSnapshotChangeEventSource.
@jpechane, feel free to help review this code changes.
=> DBZ-4107 Incremental snapshot doesn't work without primary key

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java
See [DBZ-4245](https://issues.redhat.com/browse/DBZ-4245).
Automated testing of this scenario is non-trivial but should be possible. Hence, marking this as a draft.
=> DBZ-4245: Handle SQL Server connection errors during database state transition

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/operations/debezium-server.adoc, documentation/modules/ROOT/pages/operations/embedded.adoc, documentation/modules/ROOT/pages/transformations/content-based-routing.adoc
Also changing listing format from Markdown to AsciiDoc style. All xrefs to files should have the .adoc extension (will be required by Antora v3)
=> DBZ-4254 fixing several anchors in documentation

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/SnapshotReader.java, debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
This is mainly a WIP to reduce the test log verbosity as some connector logs are substantially large.  We can determine whether these changes are worth it and then assign an issue number after-the-fact.
=> Reduce Incremental Snapshot Test verbosity

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/IncrementalSnapshotIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/IncrementalSnapshotIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/IncrementalSnapshotContext.java, debezium-core/src/main/java/io/debezium/relational/ColumnImpl.java, debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java, debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotWithSchemaChangesSupportTest.java
https://issues.redhat.com/browse/DBZ-4196
Blocked by https://issues.redhat.com/browse/DBZ-4197 to make the schema changes integration tests pass faster. Temporarily included DBZ-4197 related commit to this PR
When incremental snapshot queries a database for the next chunk of rows, the rows have the table’s current schema. However, if the binlog stream is behind the in-memory representation the table’s schema may be different from the current schema. For connectors with historized schema the solution is to wait for the connector to receive the DDL event in the binlog stream and update the in-memory representation of the table’s schema. After that, the connector can use the cached table’s structure to produce the correct incremental snapshot chunk events.
In order to detect schema changes …
=> DBZ-4196 Support schema changes during incremental snapshot

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java
From the [documentation](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-events-and-errors?view=sql-server-ver15):
| Error  | Description |
| ------------- | ------------- |
| 18401  | Login failed for user '%.*ls'. Reason: Server is in script upgrade mode. Only administrator can connect at this time.%.*ls |
=> DBZ-4285: Handle login failure during instance upgrade as retriable

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouter.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouterConfigDefinition.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouterTest.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouterTestIT.java, debezium-core/src/main/java/io/debezium/transforms/outbox/AdditionalFieldsValidator.java, debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java, debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterConfigDefinition.java, debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterDelegate.java, debezium-core/src/main/java/io/debezium/transforms/outbox/SchemaBuilderUtil.java, debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java, documentation/antora.yml, documentation/modules/ROOT/nav.adoc, documentation/modules/ROOT/pages/transformations/index.adoc, documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc, documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc
https://issues.redhat.com/browse/DBZ-3528
* Added Kafka Connect SMT for MongoDB Outbox Event Router
* Added unit tests and integration tests
* Added documentation for MongoDB Outbox Event Router
* Extracted a method to utilize as util method for validating configuration string of [additional fields](https://debezium.io/documentation/reference/transformations/outbox-event-router.html#emitting-messages-with-additional-fields)
* Modified access modifiers of Outbox Event Router's configuration fields to use in mapping from MongoDB Outbox Event Router's configuration fields to existing ones
=> DBZ-3528 Support for MongoDB Outbox Event Router SMT

COPYRIGHT.txt, debezium-bom/pom.xml, jenkins-jobs/scripts/config/Aliases.txt
Prerequisite for https://issues.redhat.com/browse/DBZ-4295
=> DBZ-4295: Update Vitess version to 12.0.0

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java, debezium-core/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java
Added a way to avoid that by overriding `getLogger()`; default behavior is the same to avoid build breaks in case I missed some other connectors (db2?) / connectors in other repos
Fixes: https://issues.redhat.com/browse/DBZ-4309
=> DBZ-4309 Avoid calling 'LoggerFactory.getLogger(getClass())' for each new instance of the RelationalChangeRecordEmitter

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Filters.java
The `config` database was not include among builtins albeit it should. It was not a problem for earlier MongoDB versions but version 5.0 contains collections there that require special privileges so it is necessary to get rid of it.
=> DBZ-3938 Add config database among builtins

documentation/modules/ROOT/pages/connectors/vitess.adoc
Add documentation for https://issues.redhat.com/browse/DBZ-4324:
- Remove vtctld configs
- Update vitess.gtid default value
=> DBZ-4324 Update doc for Vitess connector

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouterConfigDefinition.java
https://issues.redhat.com/browse/DBZ-4337
---
Fixed a bug in a configuration field for expanding JSON payload in MongoDB Outbox Event Router
follow-up for debezium#2877
=> DBZ-4337 Wrong configuration option name for MongoDB Outbox SMT

.github/workflows/mongodb-workflow.yml, jenkins-jobs/job-dsl/connector_mongodb_matrix_test.groovy
https://issues.redhat.com/browse/DBZ-4327
Requires https://github.com/debezium/docker-images/pull/272 and image 4.4 built and published to pass CI
=> DBZ-4327 Add support for MongoDB 4.4

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeEventSourceCoordinator.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingExecutionContext.java, debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java, debezium-core/src/main/java/io/debezium/pipeline/source/spi/StreamingChangeEventSource.java
This moves the poll interval logic of the `SqlServerStreamingChangeEventSource` to a new `SqlServerChangeEventSourceCoordinator` class in order to support iterating over multiple partitions.
=> DBZ-2975: Move the poll interval logic to the SqlServerChangeEventSourceCoordinator.

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeTable.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerChangeTableSetIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectionIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TransactionMetadataIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
This pull request contains fixes for [DBZ-3992](https://issues.redhat.com/browse/DBZ-3992) and [DBZ-4273](https://issues.redhat.com/browse/DBZ-4273). Although the two issues are unrelated, fixing them requires changing the same code, so it makes sense to combine their fixes together.
The root cause of [DBZ-3992](https://issues.redhat.com/browse/DBZ-3992) (SQL Server fails to read CDC events if there is a schema change ahead) is that the connector tries to use all available capture instances for a table, even though the newest one doesn't contain the changes that fall into the currently processed LSN interval (only applicable if `max.iteration.transactions` is configured).
```
CI  |                                                               LSNs …
```
=> DBZ-3992, DBZ-4273: Improve capture instance instrospection logic

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/LogicalDecodingMessageMonitor.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/LogicalDecodingMessageIT.java, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-2363
@lairen, @jpechane, this uses the prefix as message key, allowing for consistent ordering of all logical messages with the same prefix, which seems like a sensible behavior, allowing to partition the messages topic, too.
=> DBZ-2363 (follow up)

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-3635
There exists a small potential race condition where logs transition from `ONLINE` to `ARCHIVE` non-atomically and during this transition, the query used by the connector to get a list of logs to be mined may throw a false-positive error indicating that no log exists based on the SCN value.  This is because the query doesn't contain a record that contains the SCN as we would expect since it has been removed from the `ONLINE` table but Oracle hasn't yet inserted it into the `ARCHIVE` table.
To address the race condition, this PR introduces a configurable option called `log.mining.log.file.query.max.retries`.  This will be the basis for the number of attempts that the connector will retry to get a list of logs from these two tables that contain the …
=> DBZ-3635 Allow fetching of transaction logs to be retried.

documentation/modules/ROOT/pages/connectors/vitess.adoc
Follow up on https://github.com/debezium/debezium-connector-vitess/pull/59 to update the example in doc:
- replace `schema` with `keyspace`
- set `db` field to empty string - this is not ideal, but since this is set on the parent class we will have to keep it for now
=> DBZ-4428 update Vitess source metadata example

debezium-core/src/main/java/io/debezium/util/Strings.java, debezium-core/src/test/java/io/debezium/util/StringsTest.java, debezium-microbenchmark/src/main/java/io/debezium/performance/core/DurationToStringPerf.java
https://issues.redhat.com/browse/DBZ-4423
Not that it matters in the large scheme of things, but the implementation of this method was really itching me. JMH numbers before and after:
```
Benchmark                       (value)  Mode  Cnt     Score     Error  Units
DurationToStringPerf.before      3750520  avgt    5  3155,963 ± 149,810  ns/op
DurationToStringPerf.after       3750520  avgt    5    38,933 ±   4,301  ns/op
```
=> DBZ-4423 Micro-optimizing Strings::duration()

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/transforms/outbox/OracleEventRouterConfigurationProvider.java, debezium-connector-oracle/src/main/resources/META-INF/services/io.debezium.transforms.outbox.EventRouterConfigurationProvider, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OutboxEventRouterIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/OutboxEventRouterIT.java, debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterConfigurationProvider.java, debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterDelegate.java, debezium-embedded/src/test/java/io/debezium/transforms/outbox/AbstractEventRouterTest.java
https://issues.redhat.com/browse/DBZ-3940
This PR adds the ability for a connector to override some default behavior based on connector semantics, such as with Oracle all fields are always upper-case whereas for others the case is lower by default.  
In addition, I also took the liberty to unify the tests for the Outbox EventRouter by creating an abstract implementation and having PostgreSQL and Oracle extend.  This follows the same goals as was done with Incremental Snapshots.
=> DBZ-3940 Add connector-driven EventRouter configuration

debezium-quarkus-outbox/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/DebeziumOutboxConfig.java, debezium-quarkus-outbox/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/OutboxEventHbmWriter.java, debezium-quarkus-outbox/integration-tests/src/main/resources/application.properties, debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/AbstractOutboxTest.java, debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/OutboxTest.java, documentation/modules/ROOT/pages/integrations/outbox.adoc
https://issues.redhat.com/browse/DBZ-3552
This PR extends the capabilities of the `payload` field by allowing users to define a custom user-defined type handler that can be used to bridge the transformation of the payload value between the Java representation and that of the database.  This normally can be done using a JPA attribute converter; however, there are pre-existing user-defined type implementations that also do this in "Hibernate terms" and so the new `quarkus.debezium-outbox.payload.explicit-type` configuration property enables this usage.
=> DBZ-3552 Allow usage of payload custom types

README.md, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentState.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTestIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/UpdateOperators/ExtractNewDocumentStateArrayOperatorTestIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/UpdateOperators/ExtractNewDocumentStateUpdateBitOperatorTestIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/UpdateOperators/ExtractNewDocumentStateUpdateFieldOperatorTestIT.java
As discussed here: https://issues.redhat.com/browse/DBZ-4413
=> Fix DBZ-4413 MongoDB Extract Document State SMT overwrites id field

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
Refer https://issues.redhat.com/browse/DBZ-4473
Have removed in upstream grammars-v4
=> DBZ-4473 Remove unused brackets in MySqlParser

documentation/modules/ROOT/pages/configuration/signalling.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/features.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-ad-hoc-snapshots.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-incremental-snapshot.adoc, documentation/modules/ROOT/partials/modules/all-connectors/obs_ref-connector-incremental-snapshot.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-incremental-snapshot-metrics.adoc
[DBZ-3457](https://issues.redhat.com/browse/DBZ-3457)
Supersedes earlier PRs #2923 and #2954.
This change describes the Ad hoc and Incremental snapshot processes, together with how to use the signaling mechanism to trigger the connector to perform operations.
The changes include:
* Updates and restructures the upstream content. 
* Refactors the original `ref-connector-incremental-snapshot.adoc` file into two files to create a separate `con-connector-incremental-snapshot.adoc` and  `con-ad-hoc-snapshots.adoc` files.
* Rearranges and consolidates content from the original Signaling and Incremental snapshots files to reduce redundancy.
* Incorporates content from the Incremental snapshots blog post by @jpechane, and the 1.6.x release announcements by Jiri and @Naros.
* Fixes ID conflicts, …
=> Dbz 3457 incremental snapshots make over

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/IncrementalSnapshotIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java, debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotWithSchemaChangesSupportTest.java
The `source.query` field must be null in the read-only incremental snapshot events
=> DBZ-4501 Null out incremental snapshot event's query field

documentation/modules/ROOT/pages/connectors/postgresql.adoc
@gunnarmorling @jpechane adding docs for `bytea_output`. Should I also add something on the `binary.handling.mode` configuration table row?
https://issues.redhat.com/browse/DBZ-4461
=> DBZ-4461 Add documentation for postgres bytea_output

.gitignore, COPYRIGHT.txt, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DomainTypesIT.java, jenkins-jobs/scripts/config/Aliases.txt
This resolves [DBZ-3657](https://issues.redhat.com/browse/DBZ-3657).
I have integration tests for the issue, but they utilize PG syntax that does not exist in 9.6. I have verified these manually by running ITs against my own PG database (v13). I can commit and add to this PR if there is a way to do that without breaking all the tests. :)
=> DBZ-3657: add null check when building array converters

documentation/modules/ROOT/pages/integrations/outbox.adoc
See also original PR: #3090
> Was `quarkus.debezium-outbox.tracingspancontext`, but should be `quarkus.debezium-outbox.tracing-span`
> 
> Check https://github.com/debezium/debezium/blob/1.7/debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/DebeziumTracerEventDispatcher.java
> 
> Otherwise the following warning will be printed:
> 
```bash
2022-01-07 13:15:02,488 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.debezium-outbox.tracingspancontext.name" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```
> 
> 
> The suggested config
```yaml
quarkus:
debezium-outbox:
tracingspancontext:
name: TRACINGSPANCONTEXT
```
> is incorrect and does only work like this: …
=> DBZ-4529: <docs> fix wrong mention of config property quarkus.debezium-outbox.tracing-span

documentation/modules/ROOT/pages/connectors/cassandra.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc
[DBZ-4300](https://issues.redhat.com/browse/DBZ-4300)
Replace any hard-coded information about supported database versions for each connector with links to the upstream Debezium release overview and the downstream supported configurations page.
There are currently no merge conflicts, so with a backport, we could potentially include this in 1.7.
=> DBZ-4300 Link to up/down-stream pages for info re: supported db versions

documentation/modules/ROOT/pages/connectors/vitess.adoc
https://issues.redhat.com/browse/DBZ-4532
Add docs for configurations:
- vitess.grpc.headers (new)
- column.propagate.source.type (already supported)
- datatype.propagate.source.type (already supported)
cc @jeffchao
=> DBZ-4532 Update Vitess connector documentation

.github/workflows/testing-workflow.yml, debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java, debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ConnectorConfigurationTest.java, debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/DebeziumContainerTest.java
https://issues.redhat.com/browse/DBZ-4544
`debezium-testing-testcontainers` module provides services also for Quarkus based modules. It means it brings JUnit 5.
The test in the module are written in JUnit 4 but surefire chooses launcher for JUnit 5 as it is present on classpath.
There are mutiple solutions to this issue
1) exclude JUnit 5 from quarkus dependencies. The problem is that every consumer of this module would need to explicitly reintroduce them.
2) Split the module for tests and test infra structure
3) Change the tests to use JUnit 5
I've opted for the last option. We are using JUnit 5 in other modules too so it is not a precedent. The tests to change were just few and other two options would just bring complications for no gain.
=> DBZ-4544 Change tests to JUnit 5

.github/workflows/missing-commits-by-issue-key.yml, github-support/list-missing-commits-by-issue-key.sh, jenkins-jobs/pipelines/release-pipeline.groovy
https://issues.redhat.com/browse/DBZ-4063, this supersedes #3035.  
At first, I tried making some correlations between components and repositories but that quickly became unwieldy.  I decided to take a more practical approach and examine each repository to verify at least one commit for the issue key exists.  If one commit is found, we add the issue to the "found" output; if not it gets added to the "not found" output.
In testing this I did notice the following using 1.8.0.CR1 as the fix version and the span of v1.8.0.Beta1 to v1.8.0.CR1 tags:
[DBZ-4391](https://issues.redhat.com/browse/DBZ-4391) - Not found; incorporated by DBZ-4389 but DBZ-4391 not in commit message.
[DBZ-4249](https://issues.redhat.com/browse/DBZ-4249) - Jira has it marked in 1.8.0.CR1; was part of 1.8.0.Beta1. …
=> DBZ-4063 Script/Action to check for missing commits by branch

debezium-connector-postgres/pom.xml
https://issues.redhat.com/browse/DBZ-4131
GH CI will use PostgreSQL 10 by default. Jenkins CI was not testing 9.6 so no changes are needed.
=> DBZ-4131 Test with PostgreSQL 10 by default

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/BinlogReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/SnapshotReader.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDatabaseSchemaTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/AbstractProcessorUnitTest.java, debezium-core/src/main/java/io/debezium/metrics/Metrics.java, debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java, debezium-core/src/main/java/io/debezium/pipeline/metrics/ChangeEventSourceMetrics.java, debezium-core/src/main/java/io/debezium/relational/history/DatabaseHistoryMetrics.java, debezium-core/src/main/java/io/debezium/schema/DatabaseSchema.java
See [DBZ-4541](https://issues.redhat.com/browse/DBZ-4541).
1. Make `DatabaseSchema` extend `AutoCloseable`. This isn't strictly necessary but allows writing less code.
2. Maintain a single schema instance in the tests for the MySQL and Oracle connectors. Multiple schema instances can no longer co-exist in a single process since they would use the same metrics name.
Additionally, remove the `logger` parameter from the `Metrics#register` and `unregister` methods as suggested in https://github.com/debezium/debezium/pull/3047#discussion_r783075907.
=> DBZ-4541: Promote failure to register metrics to exception

documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-ad-hoc-snapshots.adoc
[DBZ-4553](https://issues.redhat.com/browse/DBZ-4552)
@Naros alerted me that a link in a shared file that I created for DBZ-3457 was generating multiple errors in the upstream Antora build that were not present in my local Antora build when I submitted PR #3057 last month. 
Changed the link format and tested that it works in both Antora and in the downstream build. 
Also fixed an unrelated error in `sqlserver.adoc` that resulted from a missing `#` in a property link.
Please backport this change to 1.7 and 1.8.
=> DBZ-4552 Modify link format to eliminate upstream Antora build error

documentation/modules/ROOT/pages/configuration/signalling.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-streams-deployment.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-connector.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-verifying-the-connector-deployment.adoc
[DBZ-3991](https://issues.redhat.com/browse/DBZ-3991)
Adds instructions to the downstream docs for deploying connectors via the Streams deployment mechanism. The changes are not rendered in the upstream content. 
The change adds three shared files to the` /partials/modules/all-connectors` folder, and modifies the `product`-conditionalized content in the deployment sections of the six connector files that we use downstream. 
~I'm still working through one remaining downstream build issue. For some reason the Oracle deployment instructions don't build, but I can't see any differences in the structure compared to the other documents. 
@fbolton if you have a moment to take a look, it might be helpful.~ 
~Yet to do:~
~- Update the downstream steps for obtaining Oracle JDBC driver to point to …
=> Dbz 3991 reflect new streams deployment mechanism in connector docs

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
https://issues.redhat.com/browse/DBZ-4536
This rework addressed two problems.  
The first was that the `OracleErrorHandler` would not trigger retrying an error if the exception had no cause, which isn't necessarily always going to be the case.  If the raised error had the desired text in terms of either the error code or contained some text we deem retriable, then we should have allowed the error handler to proceed even if no cause was in the stack.
I took this a step further and applied the error code and text inspection to both the top-level and the cause (if available) portions of the stack trace.  In addition, I also changed the `NetException` check to be applied to each portion of the stack trace since this is often a deep exception thrown by the driver and could be n-levels deep in …
=> DBZ-4536 Make OracleErrorHandler more flexible of retriable errors

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_flush.sql
Resolves https://issues.redhat.com/browse/DBZ-4561
According to the [documentation of MySQL](https://dev.mysql.com/doc/refman/8.0/en/flush.html#flush-tables) `FLUSH TABLE` and `FLUSH TABLES` can be used without listing tables, which means all open tables will be flushed.
=> DBZ-4561: Add flush table[s] grammer for all open tables

documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc
[DBZ-4573](https://issues.redhat.com/browse/DBZ-4573)
Reword admonition and add filter to designate information about using the MongoDB outbox router as `community` content.
Tested in local Antora build and in a local downstream build.
Please backport to the 1.7 and 1.8 branches.  
This change is already implemented downstream. so merging this PR is not a dependency  for building the downstream 1.7 doc.
=> DBZ-4573 Conditionalize note about using the MongoDB outbox event router

documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc
[DBZ-4574](https://issues.redhat.com/browse/DBZ-4574)
The PG connector doc had a missing space between two words in a property description. This change rewrites the description and updates the link and target anchor. 
For consistency, I added a similar note to the same property in the Oracle connector doc, and similarly updated the links and target anchor.
Please backport this change to 1.7 and 1.8. The updates are _not_ required to build the doc downstream for 1.7.
=> DBZ-4574 Update description of `snapshot.mode` property in PG doc

documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-connector.adoc
[DBZ-4582](https://issues.redhat.com/browse/DBZ-4582)
Per review comment from @jcechace, the instructions in the deployment file that is shared by the downstream connectors seem to imply that it's necessary to create a Kafka Connect instance for each connector that is deployed. 
This change modifies the sentence to indicate that you can use an existing KC to deploy. 
This change applies to content that is conditionalized for downstream use only and it does not affect the community version of the doc.
Please backport to 1.7 and 1.8.
=> DBZ-4582 Clarify that an existing KC can be used to deploy a connector

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TablesWithoutPrimaryKeyIT.java, documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-3953
=> DBZ-3953 Mark wal2json plugin as deprecated

debezium-quarkus-outbox/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/DebeziumOutboxConfig.java, debezium-quarkus-outbox/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/OutboxEventHbmWriter.java, debezium-quarkus-outbox/integration-tests/src/main/java/io/debezium/outbox/quarkus/it/MyOutboxEvent.java, debezium-quarkus-outbox/integration-tests/src/main/java/io/debezium/outbox/quarkus/it/MyService.java, debezium-quarkus-outbox/integration-tests/src/main/java/io/debezium/outbox/quarkus/it/UpperCaseAttributeConverter.java, debezium-quarkus-outbox/integration-tests/src/main/resources/application.properties, debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/AbstractOutboxTest.java, debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/OutboxTest.java, debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/ExportedEvent.java, debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/AbstractEventDispatcher.java, documentation/modules/ROOT/pages/integrations/outbox.adoc
https://issues.redhat.com/browse/DBZ-4317
@gunnarmorling This is a first pass working example of adding this behavior.  Please see the discussion in the associated Jira about the long-term concerns with how we supply this mapping and whether we should consider an alternative approach on how these types of mappings are supplied to the extension, possibly preferring annotations over configuration.
=> DBZ-4317 Allow additional field mappings w/Quarkus Outbox extension

debezium-microbenchmark-oracle/pom.xml
https://issues.redhat.com/browse/DBZ-4581
With this merged, the GH actions workflow improvements can be adjusted to no longer need to exclude the benchmark from the builds since the xstream dependency will be excluded automatically via the profile `-xstream-dependency` like we do for the Oracle connector submodule.
=> DBZ-4581 Remove Oracle benchmark dependency on XStreams

COPYRIGHT.txt, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, jenkins-jobs/scripts/config/Aliases.txt
Currently, it's not possible to perform ad hoc snapshots using Oracle 11g because the algorithm makes use of syntax that was only introduced in Oracle 12c and later.  As suggested on DBZ-4404, I've added logic to support Oracle 11g by having conditional logic for versions earlier than major version 12.
The structure of the select for versions earlier than 12c will be:
SELECT * FROM (SELECT columnname FROM tablename ORDER BY orderbycolumn) WHERE ROWNUM <=1
This is slightly more complicated than initially proposed as I did a bunch of reading and I couldn't find any confirmation that Oracle guarantees the "order by" without the nested select and so I'd rather be safe when constructing the alternate sql query.
=> DBZ-4404 Added signal table support for Oracle 11G

documentation/modules/ROOT/pages/connectors/postgresql.adoc
I could only count 5 steps 😄. It looks a step was removed in [5fbc181](https://github.com/debezium/debezium/commit/5fbc181b5e00673ac53d0b78c0e2d08223222395#diff-45bffa421745d2a514764902fc79864a8f59787194a17c8c05ee0d4c41ae2b97L129).
=> [docs] Fix reference to Postgres snapshot steps

documentation/modules/ROOT/pages/configuration/avro.adoc
The link to the apicurio-registry-distro-connect-converter package is broken, with an extra -converter which is removed.
=> Fix broken link to apicurio-registry-distro-connect-converter

COPYRIGHT.txt, debezium-connector-mysql/src/test/java/io/debezium/relational/history/KafkaDatabaseHistoryTest.java, debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java, debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc, jenkins-jobs/scripts/config/Aliases.txt
When creating history topic, debezium core module's KafkaDatabaseHistory class make an API call using KafkaAdminClient to get broker default replication factor.
The call can get timed-out if there are SSL encryption and SASL validation happens on server side while creating connection.
The aim here is to make timeout configurable.
=> DBZ-4518 Make kafka query timeout configurable

documentation/modules/ROOT/pages/connectors/vitess.adoc
Update mappings for Vitess basic data types to accommodate https://github.com/debezium/debezium-connector-vitess/pull/74
JIRA: https://issues.redhat.com/browse/DBZ-4705
cc @gunnarmorling @jeffchao @y5w
=> DBZ-4705 Update Vitess connector docs on bytes support

COPYRIGHT.txt, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java, jenkins-jobs/scripts/config/Aliases.txt
According to Debezium documentation[1], on AWS RDS, the `rds_replication` role
is enough to read the wal_log. However, on the connection validation step,
this case is omitted and the connector cannot start. The issue is pressent
starting at least v1.4.x.Final.
[1] https://debezium.io/documentation/reference/1.8/connectors/postgresql.html#postgresql-on-amazon-rds
[2] https://issues.redhat.com/browse/DBZ-4710
=> DBZ-4710: fix replication role check on RDS Postgres

documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-connector.adoc
[DBZ-4700](https://issues.redhat.com/browse/DBZ-4700)
Multiple updates to the connector deployment instructions:
- Minor rewording of introductory paragraph in Deploying procedure.
- Insert cross-reference links to OCP, Streams doc in Prereqs section.
- Correct file name in Kafka Connect example title.
- Correct YAML indentations in Kafka Connect custom resource.
- Update filename in `oc` command to create connector to clarify that the command creates a connector and not a KC resource.
These updates do not affect the upstream content.
Updates apply to all future releases. Apply to main and backport to 1.7 and 1.8 branches. 
I submitted a separate PR to the downstream doc repo to refresh the content in the released Q1 docs.
=> Dbz 4700 update shared deployment file

debezium-connector-mysql/src/test/java/io/debezium/relational/history/KafkaDatabaseHistoryTest.java, debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
Currently, History topic creation will fail if the KafkaHistory Admin client has no DESCRIBE_CLUSTER ACL at the broker level.
In a SaaS environment, you won't likely have this higher privilege.
Since Kafka 2.4, NewTopic can be used without specifying the replication factor, using Kafka Broker default automatically.
This will try first using this new constructor and will revert to old behaviour if it's not supported yet.
https://issues.redhat.com/browse/DBZ-4547
https://kafka.apache.org/24/javadoc/org/apache/kafka/clients/admin/NewTopic.html#NewTopic-java.lang.String-java.util.Map-
=> DBZ-4547 Create History Topic with optional RF

.github/workflows/doc-changes-workflow.yml, github-support/notify-documentation-changes.sh
https://issues.redhat.com/browse/DBZ-4653
* Secrets :exclamation: 
** ZULIP_TOKEN
** ZULIP_TOKEN_EMAIL_ADDRESS
* Zulip Stream :heavy_check_mark: 
As communicated to @roldanbob, I investigated a number of avenues for this which included:
1. Sending email directly to Bob
2. Checking whether we could send a custom notification to Bob's GH notifications inbox
3. Zulip integration
With (1), this would have required we set up all the necessary authentication to send email via a public provider and you would still have the risk that an email could be lost in transit, consumed by a junk/spam filter, etc.  With (2), I didn't find any action that provided this so unfortunately, I had to skip this.  With (3), we already have some integration with GH with our notification webhooks so I utilized an …
=> DBZ-4653 Cron-based doc changes workflow

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/LogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-4718
There PR fixes a problem where transaction retention was being managed on each log switch rather than after each mining session which could lead to a situation on a restart where the SCN in the connector offsets has aged out of the available logs.  We will now tick transaction retention on each mining loop so that when heartbeats are enabled or events are received from the database, the offset's SCN is kept up-to-date in really low volume environments.
=> DBZ-4718 Process transaction retention on each mining iteration

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
https://issues.redhat.com/browse/DBZ-4635
Fixes a regression during the upgrade from older connectors to 1.8.1+ or 1.9.0.Alpha2+.
=> DBZ-4635 Prevent NPE from offsets during Oracle connector upgrade

documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc
[DBZ-4791](https://issues.redhat.com/browse/DBZ-4791)
Comments inserted in `mongodb-outbox-event-router.adoc` for defining the ModuleIDs and Titles used in modularizing content were duplicated from `outbox-event-router-adoc`, resulting in collisions that prevented the downstream documentation from building.  This change updates comments and titles so that they are unique across topics that are included in the downstream docs, and updates the intra-file links to those IDs.  
Also includes other formatting changes and minor editorial updates.
Tested locally in Antora and in a downstream build.
**Note**: Links that target content outside of `mongodb-outbox-event-router.adoc` are intentionally constructed using the `{link-prefix}` and link category attributes (e.g., …
=> DBZ-4791 Update anchor IDs, titles, ModuleID defs, link formatting

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeEventSourceCoordinator.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnector.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerPartition.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerTaskContext.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metrics/AbstractSqlServerTaskMetrics.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metrics/SqlServerSnapshotTaskMetrics.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metrics/SqlServerStreamingTaskMetrics.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SchemaHistoryTopicIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorConfigTest.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorMultiPartitionModeIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, debezium-core/src/main/java/io/debezium/connector/common/CdcSourceTaskContext.java, debezium-core/src/main/java/io/debezium/metrics/Metrics.java, debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
Change summary:
1. Manage change tables for each partition individually.
2. Expose the actual task id to the metrics in order to be able to run multiple tasks.
3. Run the connector with multiple databases and multiple tasks.
Note, running multiple tasks is _not_ necessary for capturing multiple databases. Furthermore, running multiple tasks cannot be tested in the current test suite. The only reason why it's contributed here is that extracting the support for multiple tasks in a separate patch would require extra work (it was originally implemented like this). I can remove it from the patch, if necessary.
**TODO**:
1. Modify `docker-compose-sqlserver.yaml` from the [tutorial](https://github.com/debezium/debezium-examples/tree/main/tutorial#using-sql-server) to use the Docker image built …
=> DBZ-4783: Support for multiple databases and tasks in the SQL Server connector

DOCUMENTATION.md
[DBZ-4776](https://issues.redhat.com/browse/DBZ-4776)
Consolidates the two sections that discuss linking formats and updates the guidance about how to construct links so that they resolve correctly upstream and downstream.
On L197, I attempt to link directly to the `antora.yml` file. Not sure whether the path that I added is correct.
=> DBZ-4776 Update linking guidelines in `DOCUMENTATION.MD`

documentation/modules/ROOT/pages/configuration/avro.adoc, documentation/modules/ROOT/pages/configuration/signalling.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/operations/monitoring.adoc, documentation/modules/ROOT/pages/transformations/content-based-routing.adoc, documentation/modules/ROOT/pages/transformations/filtering.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-ad-hoc-snapshots.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-incremental-snapshot.adoc
[DBZ-4655](https://issues.redhat.com/browse/DBZ-4655)
This change updates connector files, shared files, and signaling files to:
-  Remove incubating/TP designations for signaling and ad hoc/incremental snapshots features. 
-  Remove filter condition that prevents MongoDB incremental snapshots topic from being exposed downstream. 
@jpechane: 
-  TBD: Should incremental snapshots be designated as TP for MongoDB? 
- Should the MongoDB connector properties table include entries for:
-- incremental.snapshot.chunk.size -- Modify the description to refer to max # documents vs. rows?
-- signal.data.collection
I based the branch for this change on `main`. 
Please backport the change to 1.9.
=> Dbz 4655 incremental snapshots ga doc updates

DOCUMENTATION.md
These links were replaced by [Adding cross references](https://github.com/debezium/debezium/blob/main/DOCUMENTATION.md#adding-cross-references-that-link-to-other-content) TOC item recently.
=> [docs] Remove non-existing items from TOC

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlParserIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/junit/SkipTestDependingOnSslModeRule.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/junit/SkipWhenSslModeIsNot.java
I implement the SkipWhenSslModeIsNot annotation and SkipTestDependingOnSslModeRule rule to skip MySqlParserIT test when ssl is not enabled mode.
=> DBZ-4787 Skip some tests with SSL auth enabled

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc
[DBZ-4014](https://issues.redhat.com/browse/DBZ-4014)
Adds admonition to description of `database.server.name` property for all connectors, warning users that changing the value disrupts connector operations.
Tested in local Antora build. 
Need clarification of whether property is intentionally omitted for MongoDB connector.
=> DBZ-4014 Warns users not to modify database.server.name

documentation/modules/ROOT/pages/connectors/mysql.adoc
According to https://dev.mysql.com/doc/refman/5.7/en/information-schema-variables-table.html, information_schema.global_variables has been deprecated ( and removed on 8.x ) in favour of performance_schema, so this documentation reflects the new way to achieve this
=> Update documentation to reflect mysql 8 changes

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-4861
The current log isn't informative enough due to a repeat of the same information : 
```
2022-03-15 10:16:35,352 INFO Reading structure of schema 'dataset_tenants' (io.debezium.connector.postgresql.PostgresSnapshotChangeEventSource) [debezium-postgresconnector-postgres-mu │
│ 2022-03-15 10:16:36,106 INFO Reading structure of schema 'dataset_tenants' (io.debezium.connector.postgresql.PostgresSnapshotChangeEventSource) [debezium-postgresconnector-postgres-mu │
│ 2022-03-15 10:16:36,647 INFO Reading structure of schema 'dataset_tenants' (io.debezium.connector.postgresql.PostgresSnapshotChangeEventSource) [debezium-postgresconnector-postgres-mu │
│ 2022-03-15 10:16:37,171 INFO Reading structure of schema 'dataset_tenants' …
```
=> fix(DBZ-4861): change log for schema snapshot postgres

.gitattributes, COPYRIGHT.txt, debezium-server/debezium-server-dist/src/main/resources/distro/run.bat
https://issues.redhat.com/browse/DBZ-4821
The current run.sh is not working if the path to Java has spaces in it. Also the file separator is not the right one in lib/*.
=> DBZ-4821 Added run.bat to debezium-server-dist

documentation/modules/ROOT/pages/connectors/cassandra.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc
[DBZ-4052](https://issues.redhat.com/browse/DBZ-4052)
This change updates entries in the table of configuration properties for the SQL Server  connector based on the recent review. 
Need to clarify whether the discrepancies in the default value for `max.queue.size` are correct: 
* The Db2, MongoDB, MySQL, Oracle, and SQL Server docs say `8192`. 
* The PostgreSQL docs says `20240`. 
Please backport to 1.9 after merging, if necessary. Thanks.
=> DBZ-4052 Updates properties table in SQL Server connector doc

debezium-connector-mysql/README.md, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java, debezium-core/src/main/java/io/debezium/pipeline/signal/SchemaChanges.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/IncrementalSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
A new schema can be applied to the chunk with an old schema if DDL event is within the chunk select window.
The chunk's JDBC schema in this case is the same as before. Schema change won't be detected. The binlog schema will get updated with the DDL event. The chunk is inserted after window close event. The events mapping uses the latest schema for the chunk.
The fix is simple: re-read chunk on DDL event. In this case chunk will have schema that is up to date with the binlog schema.
=> DBZ-4878 Re-read incremental snapshot chunk on DDL event

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-4436](https://issues.redhat.com/browse/DBZ-4436)
This change updates the upstream Oracle connector deployment documentation to provide separate instructions for obtaining the OJDBC driver for use with a standard Oracle database and Oracle XStream, and points to Maven Central vs. the Oracle website as the download source for the standard JAR file.
Information related to the XStream deployment is moved to the XStream section of the documentation.
=> DBZ-4436 Restructure upstream steps for obtaining JDBC driver

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-4852 - Gracefully handle BFILE column data type while streaming
https://issues.redhat.com/browse/DBZ-4853 - Gracefully handle LONG column data type while streaming
https://issues.redhat.com/browse/DBZ-4880 - Oracle DDL correctly interpret NCLOB column types while streaming
=> DBZ-4852 DBZ-4853 DBZ-4880 Graceful handling of Oracle unsupported data types in DDL parsing

documentation/antora.yml, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-4835](https://issues.redhat.com/browse/DBZ-4835)
Modifies the deployment instructions for the Db2 and Oracle connectors to highlight that the connectors do not include the JDBC drivers that are required to enable access to source databases. 
This change also incorporates the update requested in [DBZ-4883](https://issues.redhat.com/browse/DBZ-4883), to specify that driver files be added to the same directory as the connector plugin file.
=> Dbz 4835 note that oracle and db2 connectors exclude jdbc driver

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/BinlogReader.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
In some cases (e.g. in some cases when MEMORY engine is used), DML
records can appear in binlog in spite of the fact it's set to ROW
format. Always ignore these records.
https://issues.redhat.com/browse/DBZ-3949
=> DBZ-3949 Ignore DML records in binlog in MySQL connector

debezium-server/debezium-server-bom/pom.xml
https://issues.redhat.com/browse/DBZ-4901
=> DBZ-4901 Updated google-cloud libraries bom to version 25.0.0

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
`ON` can be used as a value for e.g. some server system variables
like unique_checks [1].
[1] https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_unique_checks
=> DBZ-4896 Allow `ON` as an expression value

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc
[DBZ-4906](https://issues.redhat.com/browse/DBZ-4906)
Fixes link error introduced in DBZ-4052 [79fd0a6](https://github.com/debezium/debezium/pull/3290/commits/79fd0a6f9dadac6d5aa847e4c0ba8c7038bbb793)
Upstream, this fix does not result in any apparent change, as  the links worked correctly despite the typo.
But the fix is significant downstream, because previously, the error did not pass the validator, and prevented the build from completing. 
This change is required in the 1.9 branch.
=> DBZ-4906 Fixes typo in link text

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Add test for SQL server schema filters. This requires smaller change in test helper which currently allows to enable CDC only for tables under default schema.
https://issues.redhat.com/browse/DBZ-2793
=> Add test for SQL server schema filters

.github/workflows/jdk-outreach-workflow.yml
https://issues.redhat.com/browse/DBZ-4924
Use Quality Outreach's new [oracle-actions/setup-java](https://github.com/oracle-actions/setup-java) action to download and setup "latest-and-greatest" OpenJDK.
See also https://inside.java/2022/03/11/setup-java
=> Update Quality Outreach workflow

documentation/modules/ROOT/pages/connectors/oracle.adoc
=> DBZ-4926 spelling mistake in oracle.adoc

debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java, debezium-server/debezium-server-core/src/test/java/io/debezium/server/DebeziumServerConfigProvidersIT.java, debezium-server/debezium-server-core/src/test/java/io/debezium/server/DebeziumServerFileConfigProviderProfile.java, debezium-server/debezium-server-core/src/test/resources/secrets_test.txt
https://issues.redhat.com/browse/DBZ-4742
This changes the config values passed to the connector to use those that were processed by the WorkerConfig, similar to those sent to the OffsetStore. It then enables any ConfigProviders such as FileConfig to support secrets.
I ran the tests and could not see any side effects. Please review.
=> DBZ-4742 change connect config to use WorkerConfig

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
`CREATE OR REPLACE TRIGGER` is not possible in MySQL [1], however this
is possible in MariaDB [2].
[1] https://dev.mysql.com/doc/refman/8.0/en/create-trigger.html
[2] https://mariadb.com/kb/en/create-trigger/
https://issues.redhat.com/browse/DBZ-4927
=> DBZ-4927 Allow `OR REPLACE` when creating trigger

COPYRIGHT.txt, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractMysqlFieldReader.java, jenkins-jobs/scripts/config/Aliases.txt
When doing a snapshot on a MySQL database that has char type columns (VARCHAR, TEXT, CHAR) and they are null, and a custom converter is present, the MySQL reader throws an NPE.
This fix addresses the problem by returning an object from the `null` value, as well as it checks if the converter is used for the column which is being read from.
https://issues.redhat.com/browse/DBZ-4933
=> DBZ-4933 Fix NPE on null column data in MySQL

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-3317](https://issues.redhat.com/browse/DBZ-3317)
Reworks numberic data types section in Oracle connector doc to consolidate information about how the connector maps  Oracle decimal and numeric types.
Replaces #3302
=> DBZ-3317 Rework numeric data types section of Oracle connector doc.

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-4879
At a high level, the issue here is that a separate query for calculating the maximum SCN from the `V$ARCHIVED_LOG` table was being used and this could return a SCN that was higher than the logs that had previously been added to the mining session due to a redo log aging out to an archive log in between the collection of logs and calculation of the maximum archive log SCN.
The goal here was to instead return a `List<LogFile>` that way we resolve the logs once and we then use this list instead as the basis for the SCN boundary calculations when archive log mode is enabled, completely avoiding this race condition.
=> DBZ-4879 Correctly resolve archive-log-only SCN mining range

.github/workflows/debezium-workflow.yml
After merging Cassandra connector [PR #52](https://github.com/debezium/debezium-connector-cassandra/pull/52), connector stopped requesting Java 1.8 and uses default Java 11. However, GH workflow still uses 1.8 and therefore tests fail.
https://issues.redhat.com/browse/DBZ-4949
=> DBZ-4949 Use Java 17 for Cassandra connector tests

debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterDelegate.java, debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
https://issues.redhat.com/browse/DBZ-4989
A fix based on the conversation in https://debezium.zulipchat.com/#narrow/stream/302529-users/topic/Expand.20JSON.20Payload.20with.20additional.20envelope.20fields
=> DBZ-4989 Passthrough payload schema in EventRouterDelegate

debezium-server/debezium-server-redis/src/main/java/io/debezium/server/redis/RedisConnection.java
=> DBZ-4993 Redis Sink - clientSetname is taking place before auth

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-4998
To identify the event time and process time from schema change event, I want to add the "ts_ms" processing time field to SchemaChangeEvent and HistoryRecord.
=> DBZ-4998 Should store event header timestamp in HistoryRecord

.github/workflows/doc-changes-workflow.yml
* Don't run doc changes workflow on fork where it fails anyway.
* Fix cron comment to reflect the reality.
https://issues.redhat.com/browse/DBZ-5007
=> DBZ-5007 Run doc changes workflow only on main repo

COPYRIGHT.txt, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorConfigTest.java, jenkins-jobs/scripts/config/Aliases.txt
Incremental snapshots on a MongoDB connector are broken. In the signaling table you are expected to provide json in the `data` (ex: `"data": { "data-collections": ["database.collection"] }`) that specifies which tables to make the snapshot. However when parsing that `data` using `Document.parse` and looping over the values of the fields, if it finds nested json will be treated as another `Document`. Just calling the `.toString()` on that will not give the value in json. We need the resulting string for that field to be in json still as there is another json parser later in the method `Signal.process`
=> DBZ-5015 Get the json value of a Document when parsing signaling message

.github/workflows/debezium-workflow.yml, debezium-connect-rest-extension/pom.xml, debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedSnapshotChangeEventSourceTest.java, debezium-parent/pom.xml, debezium-schema-generator/pom.xml, debezium-server/debezium-server-http/pom.xml, jenkins-jobs/docker/debezium-testing-system/Dockerfile, jenkins-jobs/docker/rhel_kafka/Dockerfile, pom.xml
Debezium now uses Java 11 as baseline and Java 17 for tests, e.g.
```
$ javap -verbose debezium-core/target/classes/io/debezium/annotation/GuardedBy.class |grep "major version"
major version: 55
$ javap -verbose debezium-core/target/test-classes/io/debezium/config/ConfigDefinitionMetadataTest.class |grep "major version"                                                                                        
major version: 61
```
TBD:
* test changes in Jenkins job
* update Cassandra connector to be able to run tests with Java 17, see [DBZ-4910](https://issues.redhat.com/browse/DBZ-4910)
https://issues.redhat.com/browse/DBZ-4949
=> DBZ-4949 Use Java 11 as a baseline

pom.xml
https://github.com/osheroff/mysql-binlog-connector-java/commit/324858397ec1cb8328d6035f67d411bb16d17740
Hi guys, 
The version 0.25.6 from mysql-binlog-connector-java had fixed the array index out of bounds exception, so we need to upgrade it.
=> DBZ-3848 Mysql connector throws java.lang.ArrayIndexOutOfBoundsException

.github/workflows/debezium-workflow.yml
Cassandra now allows building with JDK 11 and therefore modified
enforcer rules were removed and default one (requiring at least JDK11)
is used.
=> DBZ-4910 Don't build Cassandra with JDK8

.github/workflows/doc-changes-workflow.yml
The docs workflow was having a [startup failure](https://github.com/debezium/debezium/actions/runs/2223624630). Here is a quick fix.
=> [ci] Use single quotes for repository name

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java, debezium-core/src/main/java/io/debezium/relational/history/DatabaseHistory.java
See [DBZ-5033](https://issues.redhat.com/browse/DBZ-5033).
The Javadoc changes complement the API changes made in https://github.com/debezium/debezium/pull/457 and https://github.com/debezium/debezium/pull/1104.
=> DBZ-5033: Ignore null offsets when recovering database history

COPYRIGHT.txt, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-5005
seems more logical to use the current batch size in order to determine if said batch size needs to be increased or decreased.
(additionally it feels weird that the default batch size currently has an extra - hidden - meaning; this makes it harder to pick a good value for it.)
not sure if there's any formal theory to point to? (makes intuitive sense for me ...)
opening PR towards 1.9 (so I'll be able to enjoy the change faster, and because it feels like a 'fix').
is there any kind of formal statement you need from me or the company I work for regarding IP?
cc @Naros
=> DBZ-5005 adjust LogMiner batch size based on comparison with currently used batch size

jenkins-jobs/docker/debezium-testing-system/Dockerfile
https://issues.redhat.com/browse/DBZ-5064
(more changes in other repos for preparing OS images are needed)
=> DBZ-5064 Use maven 3.8.4

jenkins-jobs/job-dsl/ocp_downstream_trigger_all_prepare.groovy, jenkins-jobs/job-dsl/trigger_preparations.groovy, jenkins-jobs/pipelines/connector_tests_trigger_pipeline.groovy, jenkins-jobs/pipelines/downstream_apicurio_prepare_pipeline.groovy, jenkins-jobs/pipelines/downstream_artifact_server_prepare_pipeline.groovy, jenkins-jobs/pipelines/downstream_preparations_trigger_pipeline.groovy, jenkins-jobs/pipelines/downstream_prepare_pipeline.groovy, jenkins-jobs/pipelines/rhel_downstream_prepare_pipeline.groovy
added a job, that triggers all downstream preparation jobs, collects artifacts from them and modified downstream preparation jobs to archive zips with its names on them, so the trigger job doesn't have duplicities in collected artifact
https://issues.redhat.com/browse/DBZ-4956?filter=-1
=> DBZ-4956 Create trigger job to run all downstream preparation jobs

COPYRIGHT.txt, debezium-core/src/main/java/io/debezium/jdbc/CancellableResultSet.java, debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
**Overview**
The changes and rationale are detailed in the DBZ ticket but the gist is that some JDBC drivers (for example, SQL Server for JDBC > 2.0) cannot close() a `ResultSet` without first looping through all the remaining rows. This means that when we try to interrupt a snapshot process it might hang indefinitely for all intents and purposes.
The fix is to cancel() the parent `Statement` which usually involves a round trip to the server, which means that no further results will be returned within the result set.
I tested that it definitely solves our problem with the event change coordinator thread taking too long to stop and doing it not-so-gracefully when it does.
https://issues.redhat.com/browse/DBZ-5087
Open to feedback, thank you!
=> DBZ-5087 Added a decorator for result sets that can cancel the parent statements

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractMySqlFieldReader.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/IncrementalSnapshotIT.java, debezium-connector-mysql/src/test/resources/ddl/incremental_snapshot-test.sql
MySQL protocol can change during connection and as a result our custom
field reader may fail. In such case fall back to JDBC to read the value.
This is workaround until proper solution, which will require bigger
refactoring, is implemented, see DBZ-5084 for more details.
https://issues.redhat.com/browse/DBZ-4939
=> DBZ-4939 Fall back to JDBC driver if we fail to read timestamp

COPYRIGHT.txt, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresErrorHandler.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresErrorHandlerTest.java, jenkins-jobs/scripts/config/Aliases.txt
These two error messages can occur when running inside docker and the
postgres container is either killed (sigtermed) or brought down
using `docker stop`.
In both cases these are retryable as the postgres server can be
restarted shortly thereafter.
=> DBZ-5097: Add two new retryable postgresql error messages

COPYRIGHT.txt, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, jenkins-jobs/scripts/config/Aliases.txt
decimal.handling VS decimal.handing - "l" was missing
Please see https://issues.redhat.com/browse/DBZ-5040 for problem statement.
=> DBZ-5040 Fix typo about decimal.handling

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/metadata/MySqlConnectorMetadata.java, debezium-core/src/main/java/io/debezium/config/Field.java
https://issues.redhat.com/browse/DBZ-5101
* Removes default value assignment from field
* Removes auto-generation blurb from description
NOTE: This specifically targets 1.9 branch because we only want this behavior there.  For Debezium 2.0, this will be defaulted by the new `Field` definition introduced in DBZ-5100, so these two are mutually exclusive changes on two differing branches.
=> DBZ-5101 Adjust schema generator for MySQL for database.server.id

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlBinaryProtocolFieldReader.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/IncrementalSnapshotIT.java, debezium-connector-mysql/src/test/resources/ddl/incremental_snapshot-test.sql
When date is zero and binary protocol use comperssion, date has zero
length [1]:
if year, month, day, hour, minutes, seconds and micro_seconds are all 0, length is 0 and no other field is sent
Allow zero-lenght date and return it as a date which has all components
zero
[1] https://dev.mysql.com/doc/internals/en/binary-protocol-value.html#packet-ProtocolBinary::MYSQL_TYPE_TIME
https://issues.redhat.com/browse/DBZ-5099
=> DBZ-5099 Allow zero-length dates

debezium-core/src/main/java/io/debezium/converters/BinaryDataConverter.java, debezium-core/src/main/java/io/debezium/converters/ByteArrayConverter.java, debezium-core/src/main/java/io/debezium/converters/ByteBufferConverter.java, debezium-core/src/test/java/io/debezium/converters/BinaryDataConverterTest.java, debezium-core/src/test/java/io/debezium/converters/ByteArrayConverterTest.java, documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc
**Overview**
Debezium currently provides `ByteBufferConverter`. This converter works great when converting from PostgreSQL DBs, but doesn’t work for MongoDB (where the data shape is different - a Binary BSON object internally). See: https://issues.redhat.com/browse/DBZ-4600
Instead we ended up using `ByteArrayConverter` from core Kafka-Connect - which works fine for our basic use-case.
However - we want to take advantage of the delegate config and pattern Debezium provides. 
I.e. the user should be able to provide a value for `delegate.converter.type` in the configuration to specify a “backup” converter which can be used in the event the shape of the data doesn’t match that expected. 
We've recently added heartbeats to our Debezium config - following the docs - and immediately discovered …
=> DBZ-4600 - Add a new ByteArrayConverter with delegate support

documentation/modules/ROOT/pages/transformations/topic-routing.adoc
[DBZ-5128](https://issues.redhat.com/browse/DBZ-5128)
Assigns unique anchor ID to topic routing option that was introduced in DBZ-5072 (`schema.name.adjustment.mode`). The option was originally assigned the same ID as `logical.table.cache.size`. The resulting collision resulted in an error when attempting to build the Antora documentation.
If DBZ-5072 is backported to 1.9, then this fix should be treated likewise.
=> DBZ-5128 Assign unique anchor ID to recently added topic routing option

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java
https://issues.redhat.com/browse/DBZ-4782
=> DBZ-4782 Flush SCN values upon schema changes

documentation/modules/ROOT/pages/connectors/cassandra.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc, documentation/modules/ROOT/pages/development/converters.adoc
[DBZ-4588](https://issues.redhat.com/browse/DBZ-4588)
- Prepares custom converters doc for downstream use (edits and add modularization comments).
- Adds links to the converters doc from the data types topics in the connectors docs.
- Add `converters` entry to connector configuration properties tables. 
Tested in local Antora build and local downstream build.
Todos:
* Add links from MySQL and Oracle Boolean custom converter examples to Custom converters topic.
* Update properties table entry for consistency with the Boolean custom converter example.
=> DBZ-4588 restructure custom converters doc

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
Clear tableMapEventByTableId on rotate event to prevent it from growing indefinitely.
=> DBZ-5126 Clear tableMapEventByTableId on rotate event

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/IncrementalSnapshotIT.java
Cuncurrent reading and modification of MySQL table can result into MySQL
JDBC driver ArrayIndexOutOfBoundsException when it tried to merge table
fields. This is result fo caching parepared statements while table
schema is modified. It seems that caching of prepared statements is
triggered by using fetch size. Use it only in test which needs this
option to work properly and which don't do any schema changes.
https://issues.redhat.com/browse/DBZ-5131
=> DBZ-5131 Use fetch size only in tests which need it

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metrics/SqlServerStreamingPartitionMetrics.java
Call StreamingMeter.onEvent for every event so that it reports the
metrics correctly.
=> DBZ-5137: MilliSecondsBehindSource is not reported by SQL Server connector

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-5132](https://issues.redhat.com/browse/DBZ-5132)
Some mostly minor language changes and added internal links to prep the Oracle connector doc for its downstream GA. 
Please forward-port to main and subsequent release branches where applicable.
=> DBZ-5132 Edit Oracle connector doc to prep for downstream GA

COPYRIGHT.txt, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/IncrementalSnapshotIT.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java, debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-ad-hoc-snapshots.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-incremental-snapshot.adoc, jenkins-jobs/scripts/config/Aliases.txt
https://issues.redhat.com/browse/DBZ-5123
This is a quick  attempt at redefining the data-collections-ids of a Debezium signal for ad-hoc snapshot to be a comma-separated list of regular expressions (similar to the`table.include.list` configuration parameter) instead of a comma-separated list of fully-qualified-names. Since this ad-hoc snapshotting signal and the `table.include.list` property appear to be complements, there seems to be value, at least to me, in bringing these concepts closer together by allowing them to be defined and interpreted in the same way. 
A few consequences of this:
1. the ad-hoc snapshotting no longer accepts _quoted_ fully-qualified-names (the `IncrementalSnapshotIT` class in the debezium-mysql-connector relied on this). Quoted fully-qualified-names do not work …
=> DBZ-5123: Interpret data-collections signal as regex for ad-hoc snapshotting

debezium-bom/pom.xml
https://issues.redhat.com/browse/DBZ-4409
Hey @jpechane, do we BOM-manage versions of solely transitive dependencies? Gson isn't used by any Debezium connector as of this change (there's a corresponding PR for the Vitess connector which replaces the only existing usage with Jackson), so we don't really need this any longer.
Gson is a transitive dependency of the Vitess GRPC client though (and in fact the version we managed here doesn't match the actual definition). So I am leaning towards removing it, but I'm wondering whether we did have a policy to manage _all_ dependencies showing up in the dependency tree, no matter whether directly used or only transitively used. If we want to keep managing it, the version should be updated to what's actually used by the client.
WDYT?
// CC @sonne5 …
=> DBZ-4409 Removing Gson from BOM

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/events/LogMinerEventRow.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
https://issues.redhat.com/browse/DBZ-5147
@jpechane wrt Xstream, this would be mostly to handle LcrHandler callback errors and prefer to log/skip if the processing mode is set to warn/skip or fail as we do now by default.  Do you think it's warranted or should this mostly focus on LogMiner?
=> DBZ-5147 Add `event.processing.failure.handling.mode` for Oracle

COPYRIGHT.txt, debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java, debezium-core/src/test/java/io/debezium/transforms/ExtractNewRecordStateTest.java
DBZ-5166 Fixed ExtractNewRecordState SMT to pass all columns' data "as is", i.e: without potential unwanted values manipulation.
Prior to this fix, when inserting an explicit NULL value to a nullable column which has a default value, resulted in a record which contains the corresponding field with the default value (instead of NULL) after applying ExtractNewRecordState transformation.
A new unit test was added as well.
=> DBZ-5166 Fixed ExtractNewRecordState SMT to pass all columns' data as is

COPYRIGHT.txt, debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterConfigDefinition.java, debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterDelegate.java, debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java, documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc, documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc, jenkins-jobs/scripts/config/Aliases.txt
[DBZ-5089](https://issues.redhat.com/browse/DBZ-5089)
In some use cases, it would be useful to be able to specify on which partition an outbox event should be produced. This is currently not possible as `null` is hardcoded into the record constructor - let's add it to the config and plumb it down.
=> DBZ-5089: Add partition to outbox event router

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetrics.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleStreamingMetricsTest.java, debezium-core/src/main/java/io/debezium/util/LRUCacheMap.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-5179
So we previously used an unbounded `Set` implementation in the Oracle metrics to track the rollback and abandoned transaction identifiers.  In some environments with high numbers of rollback or abandoned transactions, this could cause this object's memory footprint to grow unbounded.  This PR is meant to cap the number of elements in these collections to a maximum number of elements defined by `OracleStreamingChangeEventSourceMetrics#TRANSACTION_ID_SET_SIZE`.
=> DBZ-5179 Use BoundedLinkedHashSet to avoid high memory usage

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/AbstractStreamingAdapter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/StreamingAdapter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFile.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerAdapter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamAdapter.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-5085
This fix is to guarantee the read consistency between resolving the current SCN and the in-progress transaction state by using a single database query rather than relying on multiple queries as we did previously.
=> DBZ-5085 Enforce read-consistency determining snapshot offsets

documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc
[DBZ-5219](https://issues.redhat.com/browse/DBZ-5219)
Reinstates the heading _Emitting messages with additional fields_ in` mongodb-outbox-event-router.adoc`. 
The heading was [present in 1.8](https://debezium.io/documentation/reference/1.8/transformations/mongodb-outbox-event-router.html#emitting-messages-with-additional-fields), but was inadvertently removed in [DBZ-5089](https://github.com/debezium/debezium/commit/802feaea7145e3c510a46e55d235531ebba42339#diff-cce4a09e0aba9be7ba0293df7c28dd8057895065250cb3c95936bc5bd6be5ee4L243).
Tested in local Antora build and local downstream build.
This fix should be backported to 1.9.
=> DBZ-5219 Restore deleted topic heading

documentation/modules/ROOT/pages/configuration/signalling.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-incremental-snapshot.adoc
[DBZ-5220](https://issues.redhat.com/browse/DBZ-5220)
Corrects the following typos that prevented a clean documentation build:
- The `link-signalling` attribute is spelled inconsistently (with a single `l`) in the incremental snapshots partial (`con-connector-incremental-snapshot.adoc`).
- In `signalling.adoc`, the anchor ID declaration for the topic `debezium-signaling-stop-ad-hoc-snapshots` is missing a closing `"`.
This update should be backported to 1.9.
=> DBZ-5220 Fix typos in instance of link-signalling attribute, anchor ID

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-5221](https://issues.redhat.com/browse/DBZ-5221)
Add `community` conditional to `NumberOfOversizedTransactions` metric in the Oracle connector documentation.
=> DBZ-5221 Conditionalize entry in metrics table as upstream content

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc, documentation/modules/ROOT/partials/modules/all-connectors/frag-common-snapshot-mbean-name.adoc, documentation/modules/ROOT/partials/modules/all-connectors/frag-common-streaming-mbean-name.adoc, documentation/modules/ROOT/partials/modules/all-connectors/frag-mongodb-snapshot-mbean-name.adoc, documentation/modules/ROOT/partials/modules/all-connectors/frag-mongodb-streaming-mbean-name.adoc, documentation/modules/ROOT/partials/modules/all-connectors/frag-sqlserver-snapshot-mbean-name.adoc, documentation/modules/ROOT/partials/modules/all-connectors/frag-sqlserver-streaming-mbean-name.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc
[DBZ-5233](https://issues.redhat.com/browse/DBZ-5233)
This pull request cherry picks the changes in #3599 and addresses conflicts that prevented the original PR from being merged to the 1.9 branch.
Tested in a local Antora build and in a local build of the downstream 1.9 docs.
=> DBZ-5233-refactor-MBean-name-formats-for-1.9-branch

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerAdapter.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-5256
This internal option is meant to replace the previous internal option `log.mining.query.logs.for.snapshot.offset`. This now enum-based setting provides much more flexibility by being able to completely disable the in-progress transaction check, only grab the transactions that are in-progress based on V$TRANSACTION, or to gather all in-progress transactions by scanning the redo logs and inspecting V$TRANSACTION.  
In addition, for the sake of downstream, I've opted to temporarily enforce SKIP as the default.  The option is _internal_ so that if users want to explore this feature they can opt-in to it, but this seems like the most logical way to keep the connector behavior stable.
=> DBZ-5256 Add `internal.log.mining.transaction.snapshot.boundary.mode`option

COPYRIGHT.txt, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/WalPositionLocator.java
We had an incident where the Debezium connector restarted and kept skipping messages for 22 hours while committing offset, which causes lots of data lost. More details can be found in https://issues.redhat.com/browse/DBZ-5031.
We propose to enhance the skip message condition to prevent this kind of issue. In the current `WalPositionLocator`, if the last received Lsn passes the `startStreamingLsn` for any reason after restart, the connector would never stop skipping the messages (seems nobody will switch off the filtering).
In our case, when the connector resumed and started processing messages, its last received Lsn jumped to `LSN{DAE0/CCEEC338}` for some reason, which is higher than the startStreamingLsn `LSN{DAE0/CBE21C68}` in `WalPositionLocator`. Then it just kept skipping following …
=> DBZ-5031 Stop skipping message if last received Lsn is higher or equal to start streaming Lsn
