debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DebeziumEngineIT.java

https://issues.redhat.com/browse/DBZ-2461

DBZ-2461 LSN must not be flushed after connection close

---

documentation/antora.yml
documentation/modules/ROOT/nav.adoc
documentation/modules/ROOT/pages/configuration/topic-auto-create-config.adoc
documentation/modules/ROOT/pages/install.adoc

Debezium Configuration docs for https://issues.redhat.com/browse/DBZ-78

DBZ-78 add Debezium auto-creation topics configuration documentation

---

jenkins-jobs/docker/Dockerfile.AMQ
jenkins-jobs/job-dsl/downstream_strimzi_prepare.groovy
jenkins-jobs/pipelines/downstream_prepare_pipeline.groovy
jenkins-jobs/scripts/build-connect-image.sh

Ability to add jars and zip overlays to our connect image

DBZ-2560 Extending KC image build script with ability to add extra libraries

---

debezium-testing/debezium-testing-openshift/pom.xml
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/ConfigProperties.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/WaitConditions.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/databases/DatabaseController.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/databases/SqlDatabaseClient.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/databases/SqlDatabaseController.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/databases/db2/DB2Controller.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/databases/db2/DB2Deployer.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/KafkaConnectController.java
debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/db2/DB2ConnectorIT.java
debezium-testing/debezium-testing-openshift/src/test/java/io/debezium/testing/openshift/resources/ConnectorFactories.java
debezium-testing/debezium-testing-openshift/src/test/resources/database-resources/db2/deployment.yaml
debezium-testing/debezium-testing-openshift/src/test/resources/database-resources/db2/service-lb.yaml
debezium-testing/debezium-testing-openshift/src/test/resources/database-resources/db2/service.yaml
jenkins-jobs/pipelines/openshift_pipeline.groovy

DB2 connector tests with OpenShift.

DBZ-2383 OpenShift tests for DB2 connector

---

debezium-core/src/main/java/io/debezium/converters/ByteBufferConverter.java
debezium-core/src/test/java/io/debezium/converters/ByteBufferConverterTest.java
documentation/modules/ROOT/pages/configuration/outbox-event-router.adoc

https://issues.redhat.com/browse/DBZ-2396

DBZ-2396 ByteBufferConverter support converter delegation for unsupported values

---

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java

https://issues.redhat.com/browse/DBZ-2599

DBZ-2599 Fix test failure - SQLServerConnectorIT#verifyOffsets

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java

https://issues.redhat.com/browse/DBZ-2468

DBZ-2468 Fix test failure - PostgresConnectorIT#shouldExecuteOnConnectStatements

---

documentation/modules/ROOT/pages/connectors/postgresql.adoc

https://issues.redhat.com/browse/DBZ-2605

DBZ-2605 Postgres uses schemas not databases

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/ReplicationConnectionIT.java

https://issues.redhat.com/browse/DBZ-2435

DBZ-2435 - Fix test failure - ReplicationConnectionIT#shouldResumeFromLastReceivedLSN

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSchema.java

https://issues.redhat.com/browse/DBZ-2597

DBZ-2597 Fix ConcurrentModificationException when schema modified in sharded cluster

---

jenkins-jobs/release.yaml
jenkins-jobs/scripts/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-2611

DBZ-2611 Release pipeline for multiple incubator repos

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java

https://issues.redhat.com/browse/DBZ-2344

DBZ-2344 Fix test failure - RecordsStreamProducerIT - shouldReceiveHeartbeatAlsoWhenChangingNonWhitelistedTable

---

jenkins-jobs/deploy-snapshots.yml
jenkins-jobs/scripts/deploy-snapshots.groovy

https://issues.redhat.com/browse/DBZ-2618

DBZ-2618 Deploy snapshots for Vitess connector

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateTableParserListener.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateViewParserListener.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java

https://issues.redhat.com/browse/DBZ-2604

DBZ-2604 Use default db charset as default table charset

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-2641

DBZ-2641 BLOB type has dimension

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerDefaultValueConverter.java

https://issues.redhat.com/browse/DBZ-2642

DBZ-2642 Hide scary stacktrace

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/dml_select.sql

https://issues.redhat.com/browse/DBZ-2639
Before merging let's wait for upstream vetting - https://github.com/antlr/grammars-v4/pull/1885

DBZ-2639 Refer to arbitrary table alias

---

COPYRIGHT.txt
README.md
README_ZH.md

Add 'ReadMe_ZH.md’ in Chinese

---

debezium-server/debezium-server-dist/pom.xml
debezium-server/pom.xml

https://issues.redhat.com/browse/DBZ-2660

DBZ-2660 Add eventhubs to server distro

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java

https://issues.redhat.com/browse/DBZ-2653

DBZ-2653 Process commits even with tx monitoring

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/MongoDataConverter.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTestIT.java

Their are an issue during the sanitisation to avro on mongodb connector.
The sanitization failed on sub struct like
{​
"_id": "222",
"metrics": {​
"metric::fct":
{​"min": 0, "max": 1 }
​
}
https://issues.redhat.com/browse/DBZ-2680

DBZ-2680 Sanitize field name do not santize sub struct field

---

documentation/modules/ROOT/pages/configuration/event-flattening.adoc
documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/postgresql.adoc

[DBZ-2681](https://issues.redhat.com/browse/DBZ-2681)
This fixes a few glitches that I found downstream.

DBZ-2681 Minor typo and format fixes needed for downstream rendering

---

debezium-testing/debezium-testing-openshift/src/test/resources/database-resources/db2/deployment.yaml

Complementary PR to https://github.com/debezium/debezium-examples/pull/135

DBZ-2693 using db2 image with ocp entry-point

---

documentation/modules/ROOT/pages/connectors/cassandra.adoc

DBZ-2701 - Corrected cassandra connector doc

---

.github/workflows/jdk-outreach-workflow.yml
github-support/README.md
github-support/jdk-matrix.yml

https://issues.redhat.com/browse/DBZ-2638

DBZ-2638 update OpenJDK quality outreach jobs

---

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java

https://issues.redhat.com/browse/DBZ-2625

DBZ-2625 Fix intermittent failures in SqlServerConnectorIT

---

.github/workflows/jdk-outreach-workflow.yml

Fix syntax errors of existing outreach jobs.

DBZ-2638 fix OpenJDK outreach jobs

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java

https://issues.redhat.com/browse/DBZ-2704
This fix addresses the specific test failure; however as mentioned in the Jira; I think we may need a follow-up that may only apply to PostgreSQL to deal with empty transactions, e.g. BEGIN/END messages without any DML operations.

DBZ-2704 Fix test failure - PostgresConnectorIT#shouldRegularlyFlushLsnWithTxMonitoring

---

debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java

https://issues.redhat.com/browse/DBZ-2690

DBZ-2690 get oracle specific changes into debezium-core

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java

https://issues.redhat.com/browse/DBZ-2727

DBZ-2727: Added exception to retry when there is Write failed

---

debezium-connector-postgres/pom.xml
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresShutdownIT.java
debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
debezium-testing/debezium-testing-testcontainers/pom.xml
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/Connector.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/ConnectorConfiguration.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumContainer.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/PostgresInfrastructure.java
debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/DebeziumContainerTest.java
pom.xml

DBZ-2724 Add integration tests for DBZ-2617 (fix Postgres was not able to shutdown with shutdown mode "fast")
DBZ-2602 Migrate Testcontainers related changes on DebeziumContainer from UI PoC backend to Debezium main repo
closes https://issues.redhat.com/browse/DBZ-2724
closes https://issues.redhat.com/browse/DBZ-2602

DBZ-2724 DBZ-2602 Add integration tests for DBZ-2617 and migrate Testcontainers related changes on DebeziumContainer from UI PoC backend

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeTablePointer.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerChangeTableSetIT.java

https://issues.redhat.com/browse/DBZ-2716

DBZ-2716 Guard against missing position mapping

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeTablePointer.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerChangeTableSetIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java

Depends on https://github.com/debezium/debezium/pull/1925

DBZ-2625 Make out-of-sync LSN retriable

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
documentation/modules/ROOT/pages/connectors/mongodb.adoc

https://issues.redhat.com/browse/DBZ-2742

DBZ-2742 Migrate initial.sync.max.threads to snapshot.max.threads

---

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java

https://issues.redhat.com/browse/DBZ-2747

DBZ-2747 Disable unstable corner case test

---

debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/databases/DatabaseController.java

IOB Exception was caused by public LoadBalancer not being available at the time. Solved by adding polled waiting.

DBZ-2758 Added polling when extracting LB url for database services

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-2729
This PR should only be incorporated once the sibling PR in the debezium-incubator repository have been merged.

DBZ-2729 Document new Oracle LogMiner config options

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-2760

DBZ-2760 Support for DROP CONSTRAINT

---

.github/workflows/postgres-workflow.yml
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java

DBZ-2637 Enhance Postgres validation checks
+ add wal_level config check
+ add LOGIN and REPLICATION roles check
+ add replication slot is already in use check
closes https://issues.redhat.com/browse/DBZ-2637

DBZ-2637 Enhance Postgres validation checks

---

debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-drivers.xml
debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution.xml
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractReader.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresMetricsIT.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
debezium-core/pom.xml
debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java
debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueueMetrics.java
debezium-core/src/main/java/io/debezium/pipeline/metrics/ChangeEventSourceMetricsMXBean.java
debezium-core/src/main/java/io/debezium/pipeline/metrics/PipelineMetrics.java
debezium-core/src/main/java/io/debezium/util/ObjectSizeCalculator.java
documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/vitess.adoc
documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc
documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc

[JIRA](https://issues.redhat.com/browse/DBZ-2662)

DBZ-2662 Handle ChangeEventQueue by the size in bytes

---

documentation/modules/ROOT/pages/tutorial.adoc
documentation/modules/ROOT/partials/modules/tutorial/proc-cleaning-up.adoc
documentation/modules/ROOT/partials/modules/tutorial/proc-registering-connector-monitor-inventory-database.adoc
documentation/modules/ROOT/partials/modules/tutorial/proc-starting-kafka-connect.adoc
documentation/modules/ROOT/partials/modules/tutorial/proc-starting-kafka.adoc
documentation/modules/ROOT/partials/modules/tutorial/proc-starting-mysql-command-line-client.adoc
documentation/modules/ROOT/partials/modules/tutorial/proc-starting-mysql-database.adoc
documentation/modules/ROOT/partials/modules/tutorial/proc-starting-zookeeper.adoc
documentation/modules/ROOT/partials/modules/tutorial/proc-viewing-create-event.adoc

Signed-off-by: Ramesh Reddy <rareddy@jboss.org>

DBZ-2753: Modified instructions to use Podman to run the core example

---

CONTRIBUTE.md

Any more quick points to add? 
cc : @gunnarmorling

Update CONTRIBUTE.md for CI migration from Travis to GitHub Actions

---

.github/workflows/formatting-check.yml
.github/workflows/jdk-outreach-workflow.yml

https://issues.redhat.com/browse/DBZ-2770

DBZ-2770 Upgrade Setup Java step

---

documentation/modules/ROOT/pages/connectors/cassandra.adoc
documentation/modules/ROOT/pages/connectors/mongodb.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/oracle.adoc
documentation/modules/ROOT/pages/connectors/postgresql.adoc
documentation/modules/ROOT/pages/connectors/sqlserver.adoc
documentation/modules/ROOT/pages/connectors/vitess.adoc
documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc

Hi @jpechane Could you please guide me where else should I update the docs?

DBZ-2662 - update docs for DBZ-2662

---

documentation/modules/ROOT/pages/connectors/vitess.adoc

https://issues.redhat.com/browse/DBZ-2578
Requires https://github.com/debezium/debezium-connector-vitess/pull/7

DBZ-2578 Update Vitess documentation for adding primary key support

---

.github/workflows/jdk-outreach-workflow.yml

https://issues.redhat.com/browse/DBZ-2777

DBZ-2777 Update JDK outreach to 16.0.0-ea.24

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-2763

DBZ-2763 Update default value for Oracle database.history.retention.hours

---

.github/workflows/jdk-outreach-workflow.yml

https://issues.redhat.com/browse/DBZ-2781

DBZ-2781 Auto resolve JDK EA release number

---

.github/workflows/incubator-workflow.yml
.github/workflows/vitess-workflow.yml

https://issues.redhat.com/browse/DBZ-2773

DBZ-2773 Trigger non-core connectors to resolve cross-repo builds

---

jenkins-jobs/job-dsl/release_deploy_snapshots.groovy

https://issues.redhat.com/browse/DBZ-2744

DBZ-2744 Build and Deploy snapshots four times per day

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDecimalIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
debezium-core/src/test/java/io/debezium/data/VerifyRecord.java
debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java

https://issues.redhat.com/browse/DBZ-735

DBZ-735 Verify Avro serialization

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java

https://issues.redhat.com/browse/DBZ-2772

DBZ-2772 wal2json needs db write to complete catch-up phase

---

debezium-connector-mongodb/pom.xml
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/JsonSerialization.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoClients.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnector.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoUtil.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetDiscovery.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoClientsIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/UpdateOperators/AbstractExtractNewDocumentStateUpdateOperatorsTestIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/UpdateOperators/ExtractNewDocumentStateUpdateFieldOperatorTestIT.java
debezium-testing/debezium-testing-openshift/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-2138
Contains https://github.com/debezium/debezium/pull/1978

DBZ-2138 Use MongoDB 4.x driver

---

debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java

https://issues.redhat.com/browse/DBZ-2561

DBZ-2561 Upgrade apicurio to 1.3.2.Final

---

documentation/modules/ROOT/pages/connectors/sqlserver.adoc

Update language for consistency and clarity, along with considerations for a11y and translatability. Edit and add some module IDs. Insert downstream aggregate links.

Dbz 2782 sql server connector edit

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/dml_select.sql

https://issues.redhat.com/browse/DBZ-2692
Upstream PR - https://github.com/antlr/grammars-v4/pull/1954

DBZ-2692 Allow procedure variables in LIMIT clause

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-2821
Upstream PR - https://github.com/antlr/grammars-v4/pull/1957

DBZ-2821 Support for CHAR VARYING use

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoUtil.java

closes https://issues.redhat.com/browse/DBZ-2831

DBZ-2831 Allow non default Mongo DB ports

---

jenkins-jobs/job-dsl/release_deploy_snapshots.groovy
jenkins-jobs/job-dsl/release_upstream.groovy

https://issues.redhat.com/browse/DBZ-2636

DBZ-2636 Cassandra released from a unique repository

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-2603

DBZ-2603 Document missing Oracle connector options

---

debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/EventDispatcher.java

https://issues.redhat.com/browse/DBZ-2847

DBZ-2847 Outbox event read-only to not generate updates

---

debezium-ddl-parser/src/main/java/io/debezium/antlr/AntlrDdlParser.java
debezium-ddl-parser/src/main/java/io/debezium/antlr/ParsingErrorListener.java

https://issues.redhat.com/browse/DBZ-2366

DBZ-2366 Log DDL causing parsing error

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-2840
Upstream PR - https://github.com/antlr/grammars-v4/pull/1969

DBZ-2840 Parse comments followed by tabs

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-2882

DBZ-2882 Support for MariaDB PERSISTENT keyword

---

pom.xml

https://issues.redhat.com/browse/DBZ-2887

DBZ-2887 MySQL JDBC driver bumped to 8.0.21

---

debezium-core/pom.xml

https://issues.redhat.com/browse/DBZ-2888

DBZ-2880 Guava bumped to 30.0

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-2825

DBZ-2825 Document Oracle log.mining.archive.log.hours option

---

debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java

https://issues.redhat.com/browse/DBZ-2889
@jpechane, noticed this while working on the Saga example.

DBZ-2889 Don't access payload id field if not present

---

pom.xml

Pre-requisite for https://github.com/debezium/debezium-connector-vitess/pull/15

DBZ-2892 Define Netty version

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java

closes https://issues.redhat.com/browse/DBZ-2800

DBZ-2800 Fix AWS user roles validation

---

.github/workflows/db2-workflow.yml
.github/workflows/incubator-workflow.yml
.github/workflows/mongodb-workflow.yml
.github/workflows/mysql-workflow.yml
.github/workflows/postgres-workflow.yml
.github/workflows/quarkus-outbox-workflow.yml
.github/workflows/server-workflow.yml
.github/workflows/sqlserver-workflow.yml
.github/workflows/testing-workflow.yml
.github/workflows/vitess-workflow.yml

https://issues.redhat.com/browse/DBZ-2896

DBZ-2896 Trigger builds when root pom.xml is changed

---

debezium-server/debezium-server-core/pom.xml
debezium-server/debezium-server-core/src/test/java/io/debezium/server/DebeziumServerIT.java
debezium-server/debezium-server-core/src/test/java/io/debezium/server/TestConfigSource.java
debezium-server/debezium-server-core/src/test/java/io/debezium/server/TestDatabase.java
debezium-server/debezium-server-eventhubs/pom.xml
debezium-server/debezium-server-eventhubs/src/test/java/io/debezium/server/eventhubs/EventHubsIT.java
debezium-server/debezium-server-eventhubs/src/test/java/io/debezium/server/eventhubs/EventHubsTestConfigSource.java
debezium-server/debezium-server-kinesis/pom.xml
debezium-server/debezium-server-kinesis/src/test/java/io/debezium/server/kinesis/KinesisIT.java
debezium-server/debezium-server-kinesis/src/test/java/io/debezium/server/kinesis/KinesisTestConfigSource.java
debezium-server/debezium-server-pubsub/pom.xml
debezium-server/debezium-server-pubsub/src/test/java/io/debezium/server/pubsub/PubSubIT.java
debezium-server/debezium-server-pubsub/src/test/java/io/debezium/server/pubsub/PubSubTestConfigSource.java
debezium-server/debezium-server-pulsar/pom.xml
debezium-server/debezium-server-pulsar/src/test/java/io/debezium/server/pulsar/PulsarIT.java
debezium-server/debezium-server-pulsar/src/test/java/io/debezium/server/pulsar/PulsarTestConfigSource.java
debezium-server/pom.xml
debezium-testing/debezium-testing-testcontainers/pom.xml
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/PostgresTestResourceLifecycleManager.java

https://issues.redhat.com/browse/DBZ-2868
implementing QuarkusTestResourceLifecycleManager with TestDatabase it simplifies IT tests
i will open jira ticket if the changes looks ok

DBZ-2868 imprt TestDatabase as QuarkusTestResource for debezium-server IT tests

---

pom.xml

https://issues.redhat.com/browse/DBZ-2499

DBZ-2499 Solve unknown event types

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresShutdownIT.java
debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java

https://issues.redhat.com/browse/DBZ-2923
@jpechane

DBZ-2923 Improving test stability

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerDefaultValueConverter.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectionIT.java

https://issues.redhat.com/browse/DBZ-2698
DBZ-2698 Added support for null default value for types int, bigint, smallint, tinyint, float, real

DBZ-2698 Added support for null default value for types int, bigint, smallint, tinyint, float, real

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-2938

DBZ-2938 Test stability

---

README.md
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerDefaultValueConverter.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/ApicurioRegistryContainer.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/ContainerImageVersions.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumContainer.java

https://issues.redhat.com/browse/DBZ-2945

DBZ-2945 Fetch correct latest apicurio version for testcontainers

---

documentation/modules/ROOT/pages/connectors/sqlserver.adoc

Multiple edits to address points of confusion in the SQL Server documentation. I've tested the changes in a local Antora build and in a downstream build.

DBZ-2675 Edit SQL Server connector doc to improve clarity

---

pom.xml

https://issues.redhat.com/browse/DBZ-2630

DBZ-2630 Update Kafka to 2.6.1

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/dml_insert.sql

https://issues.redhat.com/browse/DBZ-3017

DBZ-3017 Allow parentheses for functions with optional

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-3018

DBZ-3018 Signal option values can be calculated

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-2970

DBZ-2970 Add Oracle frequent problems section

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-3020

DBZ-3020 Ignore expressions in default values

---

jenkins-jobs/pipelines/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-2274

DBZ-2274 Make release more resilient against failures

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.jboss.org/browse/DBZ-2982
Added several new properties that existed in code and that now allow customizing log mining behavior.

DBZ-2982 Adding docs for properties that customize log mining behavior

---

jenkins-jobs/job-dsl/connector_postgresql_matrix_test.groovy

https://issues.redhat.com/browse/DBZ-3022
@jpechane ^^^

DBZ-3022 Test with Postgres 13

---

jenkins-jobs/job-dsl/connector_postgresql_matrix_test.groovy

https://issues.redhat.com/browse/DBZ-3022

DBZ-3022 Add PostgreSQL 13 to filter

---

debezium-server/debezium-server-pubsub/src/main/java/io/debezium/server/pubsub/PubSubChangeConsumer.java

DBZ 3037 Key being used as value in pubsub batch handler

DBZ-3037 Key being used as value in pubsub batch handler

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/zzz/ZZZGtidSetIT.java

https://issues.redhat.com/browse/DBZ-3047

DBZ-3047 Run the test after legacy package

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateTableParserListener.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java

https://issues.redhat.com/browse/DBZ-3023

DBZ-3023 Handle default charsets for table

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-3039

DBZ-3039 Add MariaDB existence predicates

---

pom.xml

https://issues.redhat.com/browse/DBZ-3066

DBZ-3066 Upgrade testcontainers to 1.15.1

---

jenkins-jobs/pipelines/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-3022

DBZ-3022 Add Postgres 13 to release pipeline

---

.github/workflows/db2-workflow.yml
.github/workflows/formatting-check.yml
.github/workflows/incubator-workflow.yml
.github/workflows/jdk-outreach-workflow.yml
.github/workflows/mongodb-workflow.yml
.github/workflows/mysql-workflow.yml
.github/workflows/postgres-workflow.yml
.github/workflows/quarkus-outbox-workflow.yml
.github/workflows/server-workflow.yml
.github/workflows/sqlserver-workflow.yml
.github/workflows/testing-workflow.yml
.github/workflows/vitess-workflow.yml

https://issues.redhat.com/browse/DBZ-3083

DBZ-3083 Make CI builds resilient against disconnects on GH Actions infrastructure

---

jenkins-jobs/job-dsl/connector_db2_matrix_test.groovy

https://issues.redhat.com/browse/DBZ-2235

DBZ-2235 Job for upstream db2 connector tests

---

documentation/modules/ROOT/pages/connectors/vitess.adoc

https://issues.redhat.com/browse/DBZ-3100
Related PRs:
- Vitess tutorial: https://github.com/debezium/debezium-examples/pull/156
- Compatibility matrix on the website: https://github.com/debezium/debezium.github.io/pull/639

DBZ-3100 Vitess Connector supports Vitess 9.0.0

---

jenkins-jobs/pipelines/release-pipeline.groovy
pom.xml

https://issues.redhat.com/browse/DBZ-3069

DBZ-3069 New Maven infra for release

---

debezium-core/src/main/java/io/debezium/relational/TableId.java
debezium-core/src/test/java/io/debezium/relational/TableIdTest.java

https://issues.redhat.com/browse/DBZ-3057
This PR provides changes to Debezium Core needed for https://github.com/debezium/debezium-incubator/pull/252.

DBZ-3057 Add some TableId helper methods

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnector.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnector.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorTest.java
debezium-core/src/main/java/io/debezium/connector/common/RelationalBaseSourceConnector.java
debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java

https://issues.redhat.com/browse/DBZ-3056
DBZ-3056 Add validation for SQL Server connector.

DBZ-3056 Add validation for SQL Server connector.

---

pom.xml

https://issues.redhat.com/browse/DBZ-3116

DBZ-3116 Quarkus version update

---

documentation/modules/ROOT/pages/connectors/vitess.adoc

https://issues.redhat.com/browse/DBZ-3115

DBZ-3115 Add support for JSON column to Vitess 9.0.0

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/MongoDataConverter.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTestIT.java

The pull request https://github.com/debezium/debezium/pull/1902 was never push to the master to missing from master 1.4 and 1.5

DZ-2680 Sanitize field name do not santize sub struct field (master)

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/MongoDataConverter.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTestIT.java

The pull request https://github.com/debezium/debezium/pull/1902 was never push to the master to missing from master 1.4 and 1.5
​

DZ-2680 Sanitize field name do not santize sub struct field (1.4)

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-2754
This PR documents the changes found in https://github.com/debezium/debezium-incubator/pull/251

DBZ-2754 Document `log.mining.transaction.retention.hours` option

---

jenkins-jobs/job-dsl/release_upstream.groovy
jenkins-jobs/pipelines/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-3027
As was agrred we are not doing Maven releases just Docker builds so only source tagging is used.

DBZ-3027 Add UI for release

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderBufferIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ConnectionIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MetadataIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDateTimeInKeyIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlGeometryIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlMetricsIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlRestartIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlSchemaMigrationIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTestConnection.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTinyIntIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlYearIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultDatabaseCharsetIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadBinLogIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotSourceIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/StreamingSourceIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/TransactionMetadataIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/UniqueDatabase.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/junit/MySqlDatabaseVersionResolver.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/legacy/BinlogReaderIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/legacy/SnapshotReaderIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/zzz/ZZZGtidSetIT.java

https://issues.redhat.com/browse/DBZ-3147

DBZ-3147 Renaming test connection class

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-3095
@jpechane, this fixes the issue for me locally. It's not quite clear to me why we only see this with 15, but the situation is that the BLC reader thread doesn't propagate the "socket closed" exceptions, remaining in a busy loop trying to read from the log. That's why the change event source thread fails to obtain the lock to disconnect. This happens for multiple tests during the suite, with each BLC reader thread keeping one core busy 100%.
While I'd love to exactly understand why this is happening, I think the fix is sound and can be merged if tests pass on CI, too.

DBZ-3095 Propagating socket exceptions

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-connector-postgres/src/test/resources/log4j.properties

https://issues.redhat.com/browse/DBZ-2865

DBZ-2865 Regression in warning message cleanup

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/AbstractColumnValue.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoColumnValue.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/DateTimeFormat.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl
debezium-core/src/main/java/io/debezium/time/Conversions.java
documentation/modules/ROOT/pages/connectors/postgresql.adoc

https://issues.redhat.com/browse/DBZ-2614
built on https://github.com/debezium/debezium/pull/1877

DBZ-2614 Support for infinite timestamps

---

debezium-core/src/main/java/io/debezium/data/Enum.java
debezium-core/src/test/java/io/debezium/data/EnumTest.java
documentation/modules/ROOT/pages/connectors/vitess.adoc

https://issues.redhat.com/browse/DBZ-3124
Related PRs:
- Feature implementation: https://github.com/debezium/debezium-connector-vitess/pull/20
- Website: https://github.com/debezium/debezium.github.io/pull/641

DBZ-3124 Update Vitess documentation of ENUM limitation for Vitess 8.0.0

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-2795

DBZ-2795 Document CDB vs non-CDB configuration nuances

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java

https://issues.redhat.com/browse/DBZ-3107

DBZ-3107 Fix timing issue in test

---

.github/workflows/jdk-outreach-workflow.yml
pom.xml

https://issues.redhat.com/browse/DBZ-3116

DBZ-3116 Quarkus 1.12.0.Final

---

documentation/modules/ROOT/pages/connectors/db2.adoc

https://issues.redhat.com/browse/DBZ-3163

DBZ-3163 Documentation clarification

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3009
* Added schema include/exclude options
* Note when using LogMiner to only use POSIX Regexs.

DBZ-3009 Oracle documentation changes

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-3067

DBZ-3067 Add OR REPLACE condition for create index

---

debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java

https://issues.redhat.com/browse/DBZ-3034
This PR is required for https://github.com/debezium/debezium-incubator/pull/262

DBZ-3034 Add validate methods to CommonConnectorConfig

---

debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/KafkaConnectController.java

https://issues.redhat.com/browse/DBZ-3170

DBZ-3170 Adding KC Promethes port to allowed network policy

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3167

DBZ-3167 Document Oracle column include/exclude list options

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3038

DBZ-3038 Update Oracle LogMiner JMX metrics

---

debezium-core/src/main/java/io/debezium/data/EnumSet.java
debezium-core/src/test/java/io/debezium/data/EnumSetTest.java
documentation/modules/ROOT/pages/connectors/vitess.adoc

https://issues.redhat.com/browse/DBZ-3199
related vitess connector PR: https://github.com/debezium/debezium-connector-vitess/pull/26

DBZ-3199 Add support for SET column to Vitess Connector

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3156
I took the liberty to reorganize some of the Oracle documentation, moving some parts around to be in similar sections to that of the other connectors.  In addition, I reviewed the data type mappings as originally indicated.

DBZ-3156 Update Oracle connector documentation

---

pom.xml

https://issues.redhat.com/browse/DBZ-3212

DBZ-3212 Upgrade MongoDB driver

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/converters/NumberOneToBooleanConverter.java

https://issues.redhat.com/browse/DBZ-3208
There was a small test failure with Oracle XStreams, this fixes the regression.

DBZ-3208 Fix regression with Oracle XStreams

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/converters/NumberOneToBooleanConverter.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/TransactionMetadataIT.java

https://issues.redhat.com/browse/DBZ-3237

DBZ-3237 Cleanup test method artifacts

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java

https://issues.redhat.com/browse/DBZ-3219

DBZ-3219 Fix column include/exclude support for Oracle

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java

https://issues.redhat.com/browse/DBZ-3030

DBZ-3030 Do not execute initial statements on connector validation

---

pom.xml

http://issues.jboss.org/browse/DBZ-3106

DBZ-3106 Upgrade binlog client to 0.25.0

---

documentation/modules/ROOT/pages/connectors/postgresql.adoc

Second PR for Jira [DBZ-3197](https://issues.redhat.com/browse/DBZ-3197)
This changes includes edits in response to comments in PR #2173

DBZ-3197 Specify that superuser grants role; SELECT grant also needed

---

debezium-connector-oracle/pom.xml
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3241

DBZ-3241 Use LogMiner adapter as default for Oracle connector

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java

https://issues.redhat.com/browse/DBZ-2417

DBZ-2417 Order returned values for clustered index cases

---

debezium-core/src/main/java/io/debezium/config/Configuration.java

https://issues.redhat.com/browse/DBZ-3084

DBZ-3084 Handle wrong warnings about deprecated options

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java

https://issues.redhat.com/browse/DBZ-3235

DBZ-3235 Do not fail parsing Oracle LogMiner SQL without a WHERE-clause

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java

https://issues.redhat.com/browse/DBZ-2885

DBZ-2885 Handle misleading error message for filtered publication

---

debezium-server/debezium-server-dist/pom.xml

https://issues.redhat.com/browse/DBZ-3217

DBZ-3217 Use legacy JAR for Debezium Server

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java

https://issues.redhat.com/browse/DBZ-2885

DBZ-2885 Fix test

---

documentation/modules/ROOT/pages/configuration/topic-auto-create-config.adoc

Jira [DBZ-2654](https://issues.redhat.com/browse/DBZ-2654)
**WIP**: Pending meeting with @rk3rn3r to discuss some aspects of the material.
I tested the file as-is in a local Antora build, as well as in a local downstream build.

DBZ-2654 Edit Customizing Topic Auto-Creation

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java

https://issues.redhat.com/browse/DBZ-3258

DBZ-3258 Parse space in table name

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFile.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerMetrics.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/Scn.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/TransactionalBuffer.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/TransactionalBufferMetrics.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerMetricsTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerUtilsTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/RowMapperTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionalBufferMetricsTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionalBufferTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/ValueHolderTest.java

https://issues.redhat.com/browse/DBZ-3145

DBZ-3145 Don't rely on Oracle version-specific max SCN values

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnector.java

https://issues.redhat.com/browse/DBZ-3254

DBZ-3254 Log exception on failed connection validation

---

documentation/modules/ROOT/pages/connectors/sqlserver.adoc

https://issues.redhat.com/browse/DBZ-3267

DBZ-3267 Add decimal.handling.mode back to SQL Server docs

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java

https://issues.redhat.com/browse/DBZ-3236

DBZ-3236 Make ORA-26653 is a retriable exception

---

documentation/modules/ROOT/pages/connectors/sqlserver.adoc

https://issues.redhat.com/browse/DBZ-3261

DBZ-3261 Document delayed END marker

---

.github/workflows/release-contributors-list.yml
COPYRIGHT.txt
github-support/list-contributors.sh
jenkins-jobs/scripts/config/Aliases.txt

https://issues.redhat.com/browse/DBZ-2592

DBZ-2592 Add script to list contributors of a release

---

documentation/modules/ROOT/pages/configuration/content-based-routing.adoc
documentation/modules/ROOT/pages/configuration/filtering.adoc

https://issues.redhat.com/browse/DBZ-3280
https://issues.redhat.com/browse/DBZ-3269

DBZ-3269 DBZ-3280 Scripting docs improvements

---

documentation/modules/ROOT/nav.adoc
documentation/modules/ROOT/pages/configuration/signalling.adoc
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3141

DBZ-3141 Documentation for signalling

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SnapshotSelectOverridesIT.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3250
Moved this back to draft as I want to include an integration test.

DBZ-3250 Document snapshot.select.statement.overrides for Oracle

---

jenkins-jobs/pipelines/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-2536

DBZ-2536 Set Target Release field

---

debezium-server/debezium-server-bom/pom.xml
debezium-server/pom.xml

https://issues.redhat.com/browse/DBZ-3277

DBZ-3277 Add commons-logging explicitly to the Server

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java

https://issues.redhat.com/browse/DBZ-3305

DBZ-3305 Fix IndexOutOfBoundsException for LogMiner Update DMLs

---

documentation/modules/ROOT/pages/connectors/sqlserver.adoc

https://issues.redhat.com/browse/DBZ-3244

DBZ-3244 Highlight the need for fully-qualified names

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java

https://issues.redhat.com/browse/DBZ-3309

DBZ-3309 Revert to MySQL specific default snapshot fetch size

---

documentation/modules/ROOT/pages/operations/embedded.adoc

https://issues.redhat.com/browse/DBZ-2665

DBZ-2665 Document the need for database history props

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSchema.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/MySqlSchema.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/RecordMakers.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
debezium-core/src/main/java/io/debezium/converters/CloudEventsConverter.java
debezium-core/src/main/java/io/debezium/heartbeat/HeartbeatImpl.java
debezium-core/src/main/java/io/debezium/pipeline/txmetadata/TransactionMonitor.java
debezium-core/src/main/java/io/debezium/relational/history/ConnectTableChangeSerializer.java
debezium-core/src/main/java/io/debezium/transforms/ByLogicalTableRouter.java
debezium-core/src/main/java/io/debezium/util/SchemaNameAdjuster.java
debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java
debezium-core/src/test/java/io/debezium/util/SchemaNameAdjusterTest.java

https://issues.redhat.com/browse/DBZ-2511
https://github.com/debezium/debezium-connector-db2/pull/16
https://github.com/debezium/debezium-connector-vitess/pull/32

DBZ-2511 Provide separate logger for adjuster messages

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java

https://issues.redhat.com/browse/DBZ-3292

DBZ-3292 Prefer archived logs over redo logs for same SCN range.

---

debezium-bom/pom.xml

https://issues.redhat.com/browse/DBZ-2872

DBZ-2872 Upgrade Kafka to 2.7.0

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-3311

DBZ-3311 Add TokuDB ROW_FORMAT variants to MySQL DDL parser

---

documentation/modules/ROOT/pages/development/engine.adoc

https://issues.redhat.com/browse/DBZ-2520

DBZ-2520 Add advanced example for JSON format

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SnapshotDatatypesIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/StreamingDatatypesIT.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3268

DBZ-3268 Fix Oracle time.precision.mode support

---

.github/workflows/website-build-workflow.yml

https://issues.redhat.com/browse/DBZ-3320

DBZ-3320 Build debezium website upon documentation changes

---

.github/workflows/cassandra-workflow.yml

https://issues.redhat.com/browse/DBZ-3335

DBZ-3335 Build Cassandra as part of CI

---

jenkins-jobs/job-dsl/connector_db2_matrix_test.groovy

https://issues.redhat.com/browse/DBZ-3337

DBZ-3337 using 'main' as default branch for DB2 matrix

---

debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/registry/RegistryController.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/registry/RegistryDeployer.java

https://issues.redhat.com/browse/DBZ-3336

DBZ-3336 Using correct labels on Apicurio Registry deployments

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-3344

DBZ-3344 Fix Oracle test failures

---

documentation/modules/ROOT/pages/connectors/mysql.adoc

https://issues.redhat.com/browse/DBZ-3353

DBZ-3353 Correct event.deserialization.failure.handling.mode documentation

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java

https://issues.redhat.com/browse/DBZ-3348

DBZ-3348 Oracle LogMiner can incorrectly resolve starting SCN is available

---

.github/workflows/cassandra-workflow.yml

https://issues.redhat.com/browse/DBZ-3357

DBZ-3357 Set up Java 8 for Cassandra CI

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SchemaHistoryTopicIT.java
debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java

https://issues.redhat.com/browse/DBZ-3347

DBZ-3347 Emit schema change events with correct source partition

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
debezium-core/src/main/java/io/debezium/relational/history/AbstractDatabaseHistory.java

https://issues.redhat.com/browse/DBZ-3361

DBZ-3361 Prefer DDL over logical schema for MySQL

---

.github/workflows/db2-workflow.yml
.github/workflows/mongodb-workflow.yml
.github/workflows/mysql-legacy-workflow.yml
.github/workflows/mysql-workflow.yml
.github/workflows/postgres-workflow.yml
.github/workflows/quarkus-outbox-workflow.yml
.github/workflows/server-workflow.yml
.github/workflows/sqlserver-workflow.yml
.github/workflows/testing-workflow.yml
.github/workflows/vitess-workflow.yml

https://issues.redhat.com/browse/DBZ-3358

DBZ-3358 Trigger workflow on workflow definition update

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java

https://issues.redhat.com/browse/DBZ-3367

DBZ-3367 Correctly parse function string-args with parenthesis characters

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlValueConvertersTest.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java

https://issues.redhat.com/browse/DBZ-3371

DBZ-3371: Adjust scale of fallback BigDecimal values to match column schema

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java

https://issues.redhat.com/browse/DBZ-3343

DBZ-3343 Re-using single shared SqlTypeMapper instance

---

README.md
README_ZH.md

https://issues.redhat.com/browse/DBZ-3383

DBZ-3383 Remove wrong badges from README

---

.github/workflows/oracle-workflow.yml
debezium-connector-oracle/pom.xml
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/AbstractStreamingAdapter.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleChangeEventSourceFactory.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSourceInfoStructMaker.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/StreamingAdapter.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerAdapter.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerOracleOffsetContextLoader.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamAdapter.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamOracleOffsetContextLoader.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleOffsetContextTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionalBufferTest.java

https://issues.redhat.com/browse/DBZ-3365

DBZ-3365 Allow building Oracle connector on CI

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
documentation/modules/ROOT/pages/connectors/cassandra.adoc
documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/oracle.adoc
documentation/modules/ROOT/pages/connectors/postgresql.adoc
documentation/modules/ROOT/pages/connectors/sqlserver.adoc
documentation/modules/ROOT/pages/connectors/vitess.adoc

implement `skipped.operation` in core and also implement it on `Postgresql`

DBZ-2699 implement skipped.operation in core

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractMysqlFieldReader.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MysqlBinaryProtocolFieldReader.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MysqlFieldReader.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MysqlTextProtocolFieldReader.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/MySqlJdbcContext.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/SnapshotReader.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotSourceIT.java
debezium-connector-mysql/src/test/resources/ddl/connector_read_binary_field_test.sql

[DBZ-3238](https://issues.redhat.com/browse/DBZ-3238)
Read the return value of mysql according to different protocols

DBZ-3238 Snapshot fails when reading TIME, DATE, DATETIME fields in mysql from ResultSet

---

debezium-connector-sqlserver/pom.xml
debezium-testing/debezium-testing-openshift/src/test/resources/database-resources/sqlserver/deployment.yaml
jenkins-jobs/job-dsl/connector_sql_server_matrix_test.groovy

https://issues.redhat.com/browse/DBZ-3379

DBZ-3379 Use current SQL Server container image

---

documentation/modules/ROOT/pages/connectors/sqlserver.adoc

Jira [DBZ-3392](https://issues.redhat.com/browse/DBZ-3392)
Minor adjustment that I missed when responding to comments for [PR 2256](https://github.com/debezium/debezium/pull/2256#discussion_r607731060)

DBZ-3392 Revise prerequisite in downstream deployment procedure

---

debezium-server/debezium-server-core/pom.xml
debezium-server/debezium-server-core/src/test/java/io/debezium/server/DebeziumServerSchemaRegistryProfile.java
debezium-server/debezium-server-core/src/test/java/io/debezium/server/DebeziumServerWithApicurioIT.java
debezium-server/debezium-server-core/src/test/java/io/debezium/server/DebeziumServerWithSchemaRegistryIT.java
debezium-server/debezium-server-core/src/test/java/io/debezium/server/TestConfigSource.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/SchemaRegistryContainer.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/SchemaRegistryTestResourceLifecycleManager.java

https://issues.redhat.com/browse/DBZ-3369

DBZ-3369 Add Schema Registry Lifecycle Manager to test Protobuf Converters

---

jenkins-jobs/job-dsl/ocp_openshift_test.groovy

https://issues.redhat.com/browse/DBZ-3404

DBZ-3404 Build strimzi from branch main

---

COPYRIGHT.txt
documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/mongodb.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/oracle.adoc
documentation/modules/ROOT/pages/connectors/postgresql.adoc
documentation/modules/ROOT/pages/connectors/sqlserver.adoc
documentation/modules/ROOT/pages/connectors/vitess.adoc

https://issues.redhat.com/browse/DBZ-3416

Tombstone docs

---

debezium-testing/debezium-testing-openshift/pom.xml
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/OpenShiftUtils.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/WaitConditions.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/KafkaConnectController.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/KafkaController.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/kafka/KafkaDeployer.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/registry/RegistryController.java
debezium-testing/debezium-testing-openshift/src/main/java/io/debezium/testing/openshift/tools/registry/RegistryDeployer.java

https://issues.redhat.com/browse/DBZ-3349

DBZ-3349 Updated kube-client version to 5.x

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/BinlogReader.java

https://issues.redhat.com/browse/DBZ-3233

DBZ-3233 Propagating socket exceptions

---

pom.xml

https://issues.redhat.com/browse/DBZ-2870

DBZ-2870 Enforce Java 11

---

debezium-bom/pom.xml

https://issues.redhat.com/browse/DBZ-3463

DBZ-3463 Upgrading binlog client

---

debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-drivers.xml
debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution.xml

https://issues.redhat.com/browse/DBZ-3458

DBZ-3458 No need to exclude test scoped dependency from assembly

---

debezium-testing/debezium-testing-openshift/pom.xml

https://issues.redhat.com/browse/DBZ-3474

DBZ-3474 Adding Apicurio converters to connect image 

---

.gitignore
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-3468

 DBZ-3468 Add missing parentheses to subpartition definition

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDefaultValueConverter.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDefaultValueTest.java

https://issues.redhat.com/browse/DBZ-3497

DBZ-3497 Handle MySQL DATE default value parser to accept timestamp

---

README.md
README_JA.md
README_ZH.md

Use case in official readme https://github.com/debezium/debezium#common-use-cases is great summary. Hope this README.md is available in Japanese also.
* debezium/dev thread: https://gitter.im/debezium/dev?at=60922454f7e4221825ba4567
* JIRA: [&#91;DBZ-3503&#93; Provide Japanese translation of README.md - Red Hat Issue Tracker](https://issues.redhat.com/browse/DBZ-3503)

DBZ-3503 Provide Japanese translation of README.md

---

debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java

https://issues.redhat.com/browse/DBZ-3438

DBZ-3438 Add mapped diagnostic contexts for snapshotting & streaming

---

documentation/modules/ROOT/pages/connectors/cassandra.adoc

Update doc for Debezium Cassandra Connector

---

debezium-bom/pom.xml

https://issues.redhat.com/browse/DBZ-3460

DBZ-3460 Update Oracle driver to 21.1.0.0

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java

See [DBZ-3505](https://issues.redhat.com/browse/DBZ-3505).
With the proposed change, the invalid configuration is reported as follows:
```
Caused by: java.lang.IllegalArgumentException: Filtered column list for table testDB.dbo.tablea is empty
```
**Testing considerations**:
1. There doesn't seem to be a way to add a unit test for this code since it's part of the `private` API with the closest `public` caller being `RelationalSnapshotChangeEventSource#doExecute`.
2. It is possible to add an integration test for it like follows:
```java
@Test(expected = ConnectException.class)
@FixFor("DBZ-3505")
public void shouldFailOnInvalidColumnFilter() throws Exception {
final Configuration config = TestHelper.defaultConfig()
.with(SqlServerConnectorConfig.COLUMN_INCLUDE_LIST, ".^")
.build(); …
```

DBZ-3505: Better handling of invalid SQL Server connector configuration

---

debezium-core/src/main/java/io/debezium/config/Configuration.java
debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java

Fixes [DBZ-3514](https://issues.redhat.com/browse/DBZ-3514)
Signed-off-by: Alfusainey Jallow <alf.jallow@gmail.com>

DBZ-3514 prevent configuration modification after creation

---

debezium-server/debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java
debezium-server/debezium-server-core/src/test/java/io/debezium/server/DebeziumServerTest.java
debezium-server/debezium-server-core/src/test/java/io/debezium/server/TestConfigSource.java

https://issues.redhat.com/browse/DBZ-2622

DBZ-2622 Configure Debezium Server via smallrye/microprofile env vars

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-3516

DBZ-3516 Oracle redo log switch not detected when using multiple archiver threads

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-832

DBZ-832 Add Oracle test for table without primary key

---

.github/workflows/formatting-check.yml

https://issues.redhat.com/browse/DBZ-3520

DBZ-3520 Upgrade actions/cache to v2

---

debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
debezium-core/src/test/java/io/debezium/data/VerifyRecord.java

https://issues.redhat.com/browse/DBZ-3469

DBZ-3469 Emit null keys without schema

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java

https://issues.redhat.com/browse/DBZ-3339

DBZ-3339 Connection refused can be retried

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlErrorHandler.java

https://issues.redhat.com/browse/DBZ-2300

DBZ-2300 Make too many connections retriable

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-3331

DBZ-3331 Do not stream if offset no longer in the MongoDB oplog

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc

[DBZ-2334](https://issues.redhat.com/browse/DBZ-2334)
This change adds downstream modularization comments and includes some restructuring updates, style and consistency edits, and link fixes.

DBZ-2334 Add comments to modularize content; minor content tweaks

---

debezium-bom/pom.xml
debezium-server/debezium-server-bom/pom.xml
debezium-server/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-3498

DBZ-3498 Use Kafka dependency version from Debezium

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java

https://issues.redhat.com/browse/DBZ-3377

DBZ-3377 Restart Oracle connector on ORA-01291, missing logfile

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java

https://issues.redhat.com/browse/DBZ-3339

DBZ-3339 Allow retry for transient error in SqlServerConnection.retrieveRealDatabaseName()

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java

https://issues.redhat.com/browse/DBZ-3519

DBZ-3519 Avoid NPE in autoboxing

---

documentation/modules/ROOT/pages/operations/monitoring.adoc

https://issues.redhat.com/browse/DBZ-3082

DBZ-3082 Document Flight Recoder

---

documentation/antora.yml
documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/postgresql.adoc
documentation/modules/ROOT/pages/connectors/sqlserver.adoc
documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-incremental-snapshot.adoc

@gunnarmorling Please review the text for Postgres connector. When approved I'll do the copy and paste for other connectors.

DBZ-3500 Document incremental and ad-hoc snapshot for Postgres

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/RowMapper.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/TransactionalBuffer.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/valueholder/LogMinerDmlEntry.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/valueholder/LogMinerDmlEntryImpl.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/RowMapperTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionalBufferTest.java

https://issues.redhat.com/browse/DBZ-3322

DBZ-3322 Handle Oracle partially committed transactions

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SignalsIT.java

https://issues.redhat.com/browse/DBZ-3533

DBZ-3533 Drop tables after signal tests concluded

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetrics.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetricsMXBean.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/RowMapper.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/TransactionalBuffer.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleStreamingMetricsTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/RowMapperTest.java
debezium-core/src/main/java/io/debezium/annotation/VisibleForTesting.java

https://issues.redhat.com/browse/DBZ-3456

DBZ-3456 Timezone difference not considered in `LagFromSourceInMilliseconds` calculation

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java

https://issues.redhat.com/browse/DBZ-3472

DBZ-3472 Relax retry logic for "No more data to read from socket"

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/dml_select.sql

See [DBZ-3543 ](https://issues.redhat.com/browse/DBZ-3543)

DBZ-3543: Missing schema function in DDL Parser

---

github-support/list-contributors.sh

https://issues.redhat.com/browse/DBZ-3544

DBZ-3544 Support names with "/" in list-contributors script

---

documentation/modules/ROOT/pages/connectors/mysql.adoc

https://issues.redhat.com/browse/DBZ-1145

DBZ-1145 Clarify MariaDB support in MySQL documentation

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/SelectLobParser.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SelectLobParserTest.java

https://issues.redhat.com/browse/DBZ-3545

DBZ-3545 Check for "IS NULL" in SelectLobParser

---

debezium-microbenchmark-oracle/src/main/java/io/debezium/performance/connector/oracle/EndToEndPerf.java
debezium-microbenchmark-oracle/src/main/java/io/debezium/performance/connector/oracle/parser/LogMinerDmlParserPerf.java

https://issues.redhat.com/browse/DBZ-3560

DBZ-3560 Oracle perf benchmark changes

---

documentation/modules/ROOT/partials/modules/tutorial/proc-starting-kafka-connect.adoc

https://issues.redhat.com/browse/DBZ-3466

DBZ-3466 Dcument impact of setting container hostname

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-3515

DBZ-3515 Execute periodic TX commits

---

debezium-connector-mysql/pom.xml
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
debezium-ddl-parser/src/test/resources/mysql/examples/dml_select.sql

https://issues.redhat.com/browse/DBZ-3559

DBZ-3559 Support MySQL JSON functions

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java

https://issues.redhat.com/browse/DBZ-3556
* Combines BLOB chunks into a single hex-string for conversion
* Moved several strings to static variables
This is the follow-up changes for DBZ-3556 that was discussed in the associated jira issue.

DBZ-3556 Remove ByteBuffer usage and refactor

---

debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java

https://issues.redhat.com/browse/DBZ-400

DBZ-400 Add a system property for number of allowed runs when no records are consumed

---

documentation/modules/ROOT/pages/connectors/mysql.adoc

https://issues.redhat.com/browse/DBZ-3572
Needs to be backported to 1.5 branch

DBZ-3572 Binlog metrics were renamed to streaming

---

documentation/modules/ROOT/pages/configuration/signalling.adoc

https://issues.redhat.com/browse/DBZ-3568

DBZ-3568 Column optionallity of signalling table

---

documentation/modules/ROOT/pages/connectors/cassandra.adoc

Update doc for major changes in the following PRs:
debezium/debezium-connector-cassandra#26
debezium/debezium-connector-cassandra#29
Replicate of https://github.com/debezium/debezium/pull/2396

DBZ-3506 Update docs for new schema evolution approach.

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3557

DBZ-3557 Add `snapshot.locking.mode` option for Oracle

---

jenkins-jobs/docker/debezium-testing-opneshift/Dockerfile
jenkins-jobs/docker/debezium-testing-opneshift/docker-compose.yml
jenkins-jobs/docker/debezium-testing-opneshift/library.sh
jenkins-jobs/docker/debezium-testing-opneshift/testsuite-deployment.sh

https://issues.redhat.com/browse/DBZ-3201

 DBZ-3201 testsuite docker container

---

documentation/modules/ROOT/pages/operations/debezium-server.adoc

Reading the rendered docs at https://debezium.io/documentation/reference/operations/debezium-server.html#_pravega, I found a typo and a formatting gaffe in the new docs for the Pravega sink.
Thanks again!
cc: @jpechane

DBZ-3546 fix typo & formatting in Pravega sink docs

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java

issue link ：[DBZ-3587](https://issues.redhat.com/browse/DBZ-3587?filter=-2&jql=order%20by%20created%20DESC)

DBZ-3587 fix NPE when builder is null

---

debezium-bom/pom.xml

https://issues.redhat.com/browse/DBZ-3589

DBZ-3589 Upgrade Cassandra driver

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3062

DBZ-3062 Oracle connector support `snapshot.include.collection.list`

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java

https://issues.redhat.com/browse/DBZ-3591

DBZ-3591 Fix SelectLobParser throwing NPE for unknown tables

---

debezium-server/debezium-server-pulsar/src/main/java/io/debezium/server/pulsar/PulsarChangeConsumer.java
debezium-server/debezium-server-pulsar/src/test/java/io/debezium/server/pulsar/PulsarIT.java
debezium-server/debezium-server-pulsar/src/test/java/io/debezium/server/pulsar/PulsarTestConfigSource.java

https://issues.redhat.com/browse/DBZ-3595

DBZ-3595 Null key should not be converted

---

documentation/modules/ROOT/pages/operations/debezium-server.adoc

https://issues.redhat.com/browse/DBZ-3601

DBZ-3601 Document Pulsar topic name mapper

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFile.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3561

DBZ-3561 Introduce archive log only mode for Oracle

---

debezium-core/src/main/java/io/debezium/pipeline/spi/OffsetContext.java

https://issues.redhat.com/browse/DBZ-3607

DBZ-3607 Document incremental snapshot SPI

---

debezium-server/debezium-server-core/pom.xml

https://issues.redhat.com/browse/DBZ-3542

DBZ-3542 Server Core should not make an assembly

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java

https://issues.redhat.com/browse/DBZ-3599

DBZ-3599 Fix Oracle RAC url variable substitution

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TablesWithUniqueIndexOnlyIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TablesWithoutPrimaryKeyIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java

https://issues.redhat.com/browse/DBZ-3597

DBZ-3597 Remove non-captured colmuns from PK

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/grant.sql

https://issues.redhat.com/browse/DBZ-3610
Upstream PR - https://github.com/antlr/grammars-v4/pull/2231

DBZ-3610 Support for grant/revoke role

---

debezium-testing/debezium-testing-openshift/pom.xml

https://issues.redhat.com/browse/DBZ-2145

DBZ-3625 Fixed dependency issues caused by BOM introduction

---

jenkins-jobs/job-dsl/release_deploy_snapshots.groovy
jenkins-jobs/job-dsl/release_upstream.groovy

https://issues.redhat.com/browse/DBZ-3275

DBZ-3275 Vitess master branch renamed to main

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java

See https://issues.redhat.com/browse/DBZ-3615.

DBZ-3615: Keep database connection closed during schema recovery

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java

https://issues.redhat.com/browse/DBZ-3631
This issue actually highlighted a problem with the `LogMinerDmlParser` regarding `UPDATE` event parsing.  In the user's report, the `UPDATE` event was setting all columns in the set-clause to `NULL` and after checking, the logic to set the after state for an `UPDATE` was flawed.  So this fix addresses two changes to the DML parser as it relates to only `UPDATE` parsing:
* The after state is always resolved, where-as before there was an unusual corner case that prevented it.
* A null sentinel value was added to differentiate between explicitly setting a field to null in the set-clause versus the field wasn't in the set-clause and therefore should have its value seeded from the where-clause before state.

DBZ-3631 Fix Oracle trx reconciliation not finding PK columns

---

debezium-core/src/main/java/io/debezium/pipeline/txmetadata/TransactionMonitor.java

https://issues.redhat.com/browse/DBZ-3593

DBZ-3593 Only emit commit event if there is an active transaction

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/ChunkColumnValues.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java

https://issues.redhat.com/browse/DBZ-3631
This is the minor optimization you asked about @gunnarmorling.

DBZ-3631 Introduce ChunkColumnValues wrapper optimization

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/TransactionalBuffer.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-3639

DBZ-3639 Send heartbeat events during periods of low activity.

---

debezium-testing/debezium-testing-openshift/src/test/resources/database-resources/sqlserver/deployment.yaml

https://issues.redhat.com/browse/DBZ-3648

DBZ-3648 Updated MsSql image to 2019 and using fixed hostname

---

pom.xml

https://issues.redhat.com/browse/DBZ-3646

DBZ-3646 Aligning version of Anltr runtime

---

pom.xml

https://issues.redhat.com/browse/DBZ-3602

DBZ-3602 Upgrade to Quarkus 2.0.0.Final

---

documentation/modules/ROOT/pages/configuration/avro.adoc

https://issues.redhat.com/browse/DBZ-3171

DBZ-3171 Update docs to use Apicurio 2

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetrics.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetricsMXBean.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleStreamingMetricsTest.java

https://issues.redhat.com/browse/DBZ-3664

DBZ-3664 Adjust log level for max batch reached message

---

debezium-bom/pom.xml
debezium-ddl-parser/pom.xml
pom.xml

Also updating Antlr4 test plug-in and making variable name consistent with others.
https://issues.redhat.com/browse/DBZ-3675

DBZ-3675 Using same Antlr version for compilation and testing;

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java

https://issues.redhat.com/browse/DBZ-3665?filter=12359047

DBZ-3665 Provide better error description when enabling archive log 

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDatabaseSchema.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDatabaseSchemaTest.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/UniqueDatabase.java
debezium-connector-mysql/src/test/resources/ddl/mysql-schema-captured.ddl
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
debezium-core/src/main/java/io/debezium/relational/ddl/DdlChanges.java
debezium-core/src/main/java/io/debezium/util/IoUtil.java

https://issues.redhat.com/browse/DBZ-3622

DBZ-3622 Fix non-captured database storing; make the code more robust

---

jenkins-jobs/pipelines/prod-release-pipeline.groovy

[release] Change parent name to debezium-build-parent

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-3686

DBZ-3686 Support MySQL `CREATE ROLE` DDL syntax

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnector.java

https://issues.redhat.com/browse/DBZ-3677

DBZ-3677 Change connection validation failure message log level

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java

https://issues.redhat.com/browse/DBZ-3684

DBZ-3684 OracleSchemaMigrationIT - Fix possible false positive test failures

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-3685

DBZ-3685 Postgres keepalive thread uses correct name

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnector.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java

https://issues.redhat.com/browse/DBZ-3632

DBZ-3632 Pulling up getJdbcConfig() to RelationalDatabaseConnectorConfig

---

documentation/modules/ROOT/pages/connectors/postgresql.adoc
documentation/modules/ROOT/pages/install.adoc
documentation/modules/ROOT/pages/operations/monitoring.adoc
documentation/modules/ROOT/pages/postgres-plugins.adoc
documentation/modules/ROOT/pages/tutorial.adoc
documentation/modules/ROOT/partials/assemblies/tutorial/assembly-starting-services.adoc
documentation/modules/ROOT/partials/modules/tutorial/con-considerations-running-debezium-with-docker.adoc
documentation/modules/ROOT/partials/modules/tutorial/proc-registering-connector-monitor-inventory-database.adoc

https://issues.redhat.com/browse/DBZ-3747

DBZ-3747 Misc. doc fixes

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3683

DBZ-3683 Capture changes made by connector user & document that SYS/SYSTEM changes are not captured

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetrics.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetricsMXBean.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3756

DBZ-3756 Add UGA/PGA memory statistics to JMX metrics

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-3623

DBZ-3623 Support Mysql INVISIBLE COLUMN syntax

---

documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc
documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc

https://issues.redhat.com/browse/DBZ-3681

DBZ-3681 Un-document monitored tables option

---

documentation/modules/ROOT/pages/configuration/signalling.adoc

Improves signal documentation by being more explicit about required configurations
Documents SQL Server quirks
Provides an example for incremental snapshotting
https://issues.redhat.com/browse/DBZ-3699

Improves signaling documentation

---

debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedIncrementalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-3725

DBZ-3725 Validate table before start incemental processing

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java

https://issues.redhat.com/browse/DBZ-3769

DBZ-3769 Throw sqlexception from postgres message decoder

---

debezium-bom/pom.xml
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java

This reverts commit 4f4c14acdd815338ad0d4aa3ddca67fa44aa3db1.

DBZ-3655 Revert driver upgrade - incompatible behaviour

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleChangeEventSourceFactory.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSignalBasedIncrementalSnapshotChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerOracleOffsetContextLoader.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamOracleOffsetContextLoader.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionalBufferTest.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedIncrementalSnapshotChangeEventSource.java
debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3692

DBZ-3692 Oracle incremental snapshot support

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-3784

DBZ-3784 Add DEFAULT to partition option engine

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-3788

DBZ-3788 Avoid oplog collection scan

---

jenkins-jobs/job-dsl/deploy_docker_images.groovy
jenkins-jobs/job-dsl/release_debezium_nightly_image.groovy
jenkins-jobs/pipelines/build-debezium-images.groovy
jenkins-jobs/scripts/trigger-nightly-docker.sh

https://issues.redhat.com/browse/DBZ-3809
Requires https://github.com/debezium/docker-images/pull/237

DBZ-3809 Support images push from Jenkins

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/FieldSelector.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FiltersTest.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java

https://issues.redhat.com/browse/DBZ-3028

DBZ-3028 Validate field.exclude.list & field.renames for MongoDB connector

---

debezium-testing/debezium-testing-system/pom.xml

This was requested by Apicurio's QE team
https://issues.redhat.com/browse/DBZ-3826

DBZ-3826 Allow system test-suite to build KC images with arbitrary  debezium version

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresDefaultValueConverter.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java

https://issues.redhat.com/browse/DBZ-3816

DBZ-3816 Workaround for Kafka Connect bug

---

debezium-core/src/test/java/io/debezium/data/VerifyRecord.java

https://issues.redhat.com/browse/DBZ-3842

DBZ-3842 Validate keySchema is null and not valueSchema

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DecoderDifferences.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java

https://issues.redhat.com/browse/DBZ-3828

DBZ-3828 Update event LSN for commits

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/StreamingSourceIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/legacy/BinlogReaderIT.java
debezium-core/src/test/java/io/debezium/junit/DatabaseVersionResolver.java

https://issues.redhat.com/browse/DBZ-3839

DBZ-3839 Correctly skip tests with minor/patch not specified

---

debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/db2/OcpAvroDB2ConnectorIT.java

https://issues.redhat.com/browse/DBZ-3851

DBZ-3851 Fixed test tags for OcpAvroDB2ConnectorIT

---

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java

https://issues.redhat.com/browse/DBZ-3228

DBZ-3228 Make sure to change db in streaming

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-3838

DBZ-3838 Do not reset trx isolation when using minimal_percona

---

debezium-server/debezium-server-pravega/src/main/java/io/debezium/server/pravega/PravegaChangeConsumer.java

https://issues.redhat.com/browse/DBZ-3792

DBZ-3792 Default value for Pravega scope

---

debezium-api/pom.xml
debezium-bom/pom.xml
debezium-core/pom.xml
debezium-core/src/test/java/io/debezium/kafka/KafkaServer.java
pom.xml

https://issues.redhat.com/browse/DBZ-3444
@jpechane, still working on the container upgrade, but here's the core change for the AK 2.8 upgrade. Also did some POM clean-up, while at it.

DBZ-3444 Upgrade to AK 2.8

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
documentation/modules/ROOT/pages/connectors/mongodb.adoc

https://issues.redhat.com/browse/DBZ-3836

DBZ-3836 Allow configurable execution timeout

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MysqlBinaryProtocolFieldReader.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MysqlTextProtocolFieldReader.java

https://issues.redhat.com/browse/DBZ-3773

DBZ-3773 Treat empty TIME blob value as null

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/StreamingSourceIT.java

https://issues.redhat.com/browse/DBZ-3869

DBZ-3869 Stop connector only after error was recorded

---

debezium-bom/pom.xml
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
documentation/modules/ROOT/pages/connectors/mysql.adoc

[Link to issue](https://issues.redhat.com/browse/DBZ-3833)
Work on upgrading to the latest version of mysql-connector-java.

DBZ-3833 Updated mysql-connector-java dependency to 8.0.26

---

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-3857
The https://github.com/debezium/debezium/pull/2604 might need addition changes due to this one.

DBZ-3857 Exclude database name in snapshot tables filtering

---

documentation/antora.yml
documentation/modules/ROOT/pages/configuration/avro.adoc

https://issues.redhat.com/browse/DBZ-3879

DBZ-3879 Use DockerKafkaConnect variable in Avro docs

---

documentation/modules/ROOT/nav.adoc
documentation/modules/ROOT/pages/transformations/content-based-routing.adoc
documentation/modules/ROOT/pages/transformations/event-flattening.adoc
documentation/modules/ROOT/pages/transformations/filtering.adoc
documentation/modules/ROOT/pages/transformations/mongodb-event-flattening.adoc
documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc
documentation/modules/ROOT/pages/transformations/topic-routing.adoc

DBZ-3873 Extract new top-level menu node for SMTs

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresShutdownIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
debezium-connector-postgres/src/test/resources/log4j.properties
debezium-core/src/test/java/io/debezium/util/ContainerImageVersions.java
debezium-testing/debezium-testing-testcontainers/pom.xml
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/ApicurioRegistryContainer.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumContainer.java

https://issues.redhat.com/browse/DBZ-3889

DBZ-3889 Avoiding some log noise

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java

https://issues.redhat.com/browse/DBZ-3876
Through discussions with  Chris Cranford, I think this is reasonable.

DBZ-3876 Improve the SCN update method in MemoryLogMinerEventProcessor

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/ChunkColumnValues.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java

https://issues.redhat.com/browse/DBZ-3893

DBZ-3893 Treat EMPTY_XLOB() as an empty LOB value instead of NULL

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java
debezium-core/src/test/java/io/debezium/junit/logging/LogInterceptor.java

https://issues.redhat.com/browse/DBZ-3902

DBZ-3902 Fix test failure shouldNotEmitDdlEventsForNonTableObjects

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-3886

DBZ-3886 Improve ALTER TABLE DROP grammar for Oracle

---

debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedIncrementalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-3901

DBZ-3901 Guard against chunk signal coming when none expected

---

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java

https://issues.redhat.com/browse/DBZ-2398

DBZ-2398 Handle more than one transaction in the list

---

debezium-server/debezium-server-nats-streaming/src/main/java/io/debezium/server/nats/streaming/NatsStreamingChangeConsumer.java
debezium-server/debezium-server-nats-streaming/src/test/java/io/debezium/server/nats/streaming/NatsStreamingIT.java
debezium-server/debezium-server-nats-streaming/src/test/java/io/debezium/server/nats/streaming/NatsStreamingTestConfigSource.java
debezium-server/debezium-server-nats-streaming/src/test/java/io/debezium/server/nats/streaming/NatsStreamingTestResourceLifecycleManager.java
debezium-server/debezium-server-nats-streaming/src/test/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource

https://issues.redhat.com/browse/DBZ-3910

DBZ-3910 Use standard Java package naming

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerDatabaseStateWriter.java

https://issues.redhat.com/browse/DBZ-3911

DBZ-3911 Fix SQLException due to column name typo

---

debezium-testing/debezium-testing-system/pom.xml
jenkins-jobs/pipelines/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-3909

DBZ-3909 Simplify version handling of Debezium testing dependencies

---

.github/workflows/cassandra-workflow.yml
.github/workflows/db2-workflow.yml
.github/workflows/mongodb-workflow.yml
.github/workflows/mysql-legacy-workflow.yml
.github/workflows/mysql-workflow.yml
.github/workflows/oracle-workflow.yml
.github/workflows/postgres-workflow.yml
.github/workflows/quarkus-outbox-workflow.yml
.github/workflows/sanity-check.yml
.github/workflows/server-workflow.yml
.github/workflows/sqlserver-workflow.yml
.github/workflows/testing-workflow.yml
.github/workflows/vitess-workflow.yml

https://issues.redhat.com/browse/DBZ-3913

DBZ-3913 Specify branch name on push/pull_request step

---

CONTRIBUTE.md

To be merged after the release is out

[docs] Updating contribution info

---

documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc

* Wording fixes
* Don't show ByteBuffer converter in downstream docs

DBZ-3584 Misc. doc fixes;

---

jenkins-jobs/job-dsl/ocp_downstream_apicurio_prepare.groovy
jenkins-jobs/job-dsl/ocp_downstream_strimzi_prepare.groovy
jenkins-jobs/job-dsl/rhel_downstream_prepare.groovy
jenkins-jobs/pipelines/downstream_apicurio_prepare_pipeline.groovy
jenkins-jobs/scripts/copy-images.sh

https://issues.redhat.com/browse/DBZ-3908

DBZ-3908 Apicurio image prepare jenkins job

---

jenkins-jobs/job-dsl/ocp_openshift_test.groovy
jenkins-jobs/pipelines/openshift_pipeline.groovy

https://issues.redhat.com/browse/DBZ-3932

DBZ-3932 Support for running apicurio tests in CI

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java

https://issues.redhat.com/browse/DBZ-3935

DBZ-3935 Invalid validation of truncate handling mode

---

RELEASING.md

closes https://issues.redhat.com/browse/DBZ-3918

DBZ-3918 Update RELEASING.md to current process

---

debezium-server/debezium-server-redis/src/main/java/io/debezium/server/redis/RedisStreamChangeConsumer.java

In case of a failure the entire batch would be skipped and the whole process
crashes. Adding a try catch block similar to other sinks
Issue - https://issues.redhat.com/browse/DBZ-3713

DBZ-3713 Wrapped client.xadd within Try-Catch in RedisStreamChangeConsumer

---

.github/workflows/octocat-commits-check.yml

https://issues.redhat.com/browse/DBZ-3822

DBZ-3822 GH Action that flags octocat commits

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/UnistrHelper.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/UnistrHelperTest.java

https://issues.redhat.com/browse/DBZ-3892

DBZ-3892 Correctly parse concatenated UNISTR values

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3954

DBZ-3954 Restrict capturing change events to configured PDB

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_drop.sql

https://issues.redhat.com/browse/DBZ-3962

DBZ-3962 Support DROP TABLE using recycle bin as-clause

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java

https://issues.redhat.com/browse/DBZ-3976

DBZ-3976 fix MySqlValueConvertes.java typo

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorConfigDefTest.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbTransformationConfigDefTest.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorConfigDefTest.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigDefTest.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorConfigDefTest.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorConfigDefTest.java
debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordStateConfigDefinition.java
debezium-core/src/test/java/io/debezium/config/ConfigDefinitionMetadataTest.java
debezium-core/src/test/java/io/debezium/config/CoreTransformationConfigDefinitionMetadataTest.java
debezium-core/src/test/java/io/debezium/config/TransformationConfigDefinitionMetadataTest.java
debezium-scripting/src/test/java/io/debezium/transforms/ScriptingTransformationConfigDefTest.java

* Including fix for errors
closes https://issues.redhat.com/browse/DBZ-3943

DBZ-3943 Add ConfigDef unit tests to verify all Debezium Field instances have a proper documentation/description set

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/ColumnDefinitionParserListener.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4

Fix [DBZ-3984](https://issues.redhat.com/browse/DBZ-3984)
And fix pattern split issue
To config my github email, i had to resubmit a pr,  Sorry for the inconvenient...
The antlr pr:
https://github.com/antlr/grammars-v4/pull/2324

DBZ-3984 Mysql-Connector fails parsing invalid decimal format DDL statement

---

jenkins-jobs/job-dsl/release_debezium_stage_prod.groovy
jenkins-jobs/pipelines/prod-release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-3861

DBZ-3861 Use bacon CLI to automate product builds; generate Maven repo

---

debezium-bom/pom.xml
debezium-connector-mysql/pom.xml
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlParserIT.java
debezium-connector-mysql/src/test/resources/docker/conf/mysql.cnf
debezium-core/src/main/java/io/debezium/relational/history/MemoryDatabaseHistory.java

https://issues.redhat.com/browse/DBZ-3787

DBZ-3787 Upgrade binlog-client to 0.25.3

---

.github/workflows/formatting-check.yml
.github/workflows/sanity-check.yml

https://issues.redhat.com/browse/DBZ-3822

DBZ-3822 Add comments to handle commit message check on failure

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_truncate.sql

https://issues.redhat.com/browse/DBZ-3977
* Add support for truncating subpartitions with ALTER
* Add support for dropping storage with TRUNCATE

DBZ-3977 Extend ALTER and TRUNCATE table Oracle DDL support

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java

https://issues.redhat.com/browse/DBZ-4013

DBZ-4013 Skip invalid table

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-4017

DBZ-4017 Support multiple (sub)partitions in ALTER TABLE truncate syntax

---

.github/workflows/contributor-check.yml

https://issues.redhat.com/browse/DBZ-4023

DBZ-4023 Check if author names are present in COPYRIGHT.txt

---

jenkins-jobs/job-dsl/ocp_downstream_artifact_server_prepare.groovy
jenkins-jobs/pipelines/downstream_artifact_server_prepare_pipeline.groovy
jenkins-jobs/scripts/build-connect-image.sh
jenkins-jobs/scripts/copy-images.sh
jenkins-jobs/scripts/copy-plugins.sh

https://issues.redhat.com/browse/DBZ-3934

DBZ 3934-2 Added jenkins job for artifact server preparation

---

jenkins-jobs/job-dsl/ocp_downstream_artifact_server_prepare.groovy
jenkins-jobs/pipelines/downstream_artifact_server_prepare_pipeline.groovy
jenkins-jobs/scripts/copy-plugins.sh

https://issues.redhat.com/browse/DBZ-3934

DBZ-3934 Added image tagging

---

debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java

https://issues.redhat.com/browse/DBZ-4040

DBZ-4040 Fix IncrementalSnapshotIT test failure for Oracle connector

---

.github/workflows/sanity-check.yml

https://issues.redhat.com/browse/DBZ-4047

DBZ-4047 Fix commit message action for multi-line commits

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java

https://issues.redhat.com/browse/DBZ-3712

DBZ-3712 Support start/change archive.log.only.mode gracefully

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java

https://issues.redhat.com/browse/DBZ-3346

DBZ-3346 Expanding SQL Server connector error handler

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-3712
Follow-up adding a configuration option for the poll interval.

DBZ-3712 Add poll interval configuration option

---

.github/workflows/contributor-check.yml
.github/workflows/formatting-check.yml

https://issues.redhat.com/browse/DBZ-4058

DBZ-4058 Trigger contributor check action only when PR is opened

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
debezium-core/src/main/java/io/debezium/pipeline/source/spi/StreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-4057

DBZ-4057 Initialize Postgres schema before incremental snapshot restart

---

debezium-bom/pom.xml
debezium-server/debezium-server-bom/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-4049

DBZ-4049 Override Quarkus JDBC drivers

---

COPYRIGHT.txt
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresDefaultValueConverter.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
jenkins-jobs/scripts/config/Aliases.txt
pom.xml

See #2743 for initial implementation which went all the way to 42.2.24

DBZ-4060 Update PgJDBC to 42.2.22 to fix cloud provider connection issues

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/grant.sql

https://issues.redhat.com/browse/DBZ-4034

DBZ-4034 Add missing tokens for DDL parser

---

jenkins-jobs/pipelines/build-debezium-images.groovy

https://issues.redhat.com/browse/DBZ-4074

DBZ-4074 Authenticate to Github API

---

jenkins-jobs/pipelines/build-debezium-images.groovy
jenkins-jobs/pipelines/deploy-snapshots.groovy
jenkins-jobs/pipelines/downstream_apicurio_prepare_pipeline.groovy
jenkins-jobs/pipelines/downstream_artifact_server_prepare_pipeline.groovy
jenkins-jobs/pipelines/downstream_prepare_pipeline.groovy
jenkins-jobs/pipelines/openshift_pipeline.groovy
jenkins-jobs/pipelines/prod-release-pipeline.groovy
jenkins-jobs/pipelines/release-pipeline.groovy
jenkins-jobs/pipelines/rhel_downstream_prepare_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4071

DBZ-4071 Recipient email address should be a variable in all Jenkins jobs

---

debezium-quarkus-outbox/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/AdditionalJaxbMappingProducerImpl.java
debezium-quarkus-outbox/deployment/src/main/resources/META-INF/services/org.hibernate.boot.spi.AdditionalJaxbMappingProducer
debezium-quarkus-outbox/runtime/pom.xml
debezium-quarkus-outbox/runtime/src/main/resources/META-INF/quarkus-extension.yaml
debezium-quarkus-outbox/runtime/src/main/resources/META-INF/services/org.hibernate.boot.spi.AdditionalJaxbMappingProducer
debezium-server/debezium-server-eventhubs/src/test/java/io/debezium/server/eventhubs/EventHubsTestConfigSource.java
debezium-server/debezium-server-kafka/src/test/java/io/debezium/server/kafka/KafkaTestConfigSource.java
debezium-server/debezium-server-kinesis/src/test/java/io/debezium/server/kinesis/KinesisTestConfigSource.java
debezium-server/debezium-server-nats-streaming/src/test/java/io/debezium/server/nats/streaming/NatsStreamingTestConfigSource.java
debezium-server/debezium-server-pubsub/src/test/java/io/debezium/server/pubsub/PubSubTestConfigSource.java
debezium-server/debezium-server-pulsar/src/test/java/io/debezium/server/pulsar/PulsarTestConfigSource.java
debezium-server/debezium-server-redis/src/test/java/io/debezium/server/redis/RedisTestConfigSource.java
pom.xml

https://issues.redhat.com/browse/DBZ-3785

DBZ-3785 Bump Quarkus from 2.0.0.Final to 2.2.3.Final

---

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SchemaHistoryTopicIT.java

https://issues.redhat.com/browse/DBZ-4082
@jpechane could you take a quick look? Thx!

DBZ-4082 Awaiting connector start-up

---

jenkins-jobs/job-dsl/connector_postgresql_matrix_test.groovy
jenkins-jobs/pipelines/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-4079
@jpechane, is that's all that's needed build-wise for the PG update?

DBZ-4079 Updating build config for Postgres 14

---

jenkins-jobs/job-dsl/deploy_debezium_tool_images.groovy
jenkins-jobs/pipelines/build-debezium-tool-images.groovy

https://issues.redhat.com/browse/DBZ-3907

DBZ-3907 Publish debezium tool images to dockerhub using Jenkins

---

.github/workflows/contributor-check.yml
.github/workflows/sanity-check.yml

https://issues.redhat.com/browse/DBZ-4073

DBZ-4073 Allow [ci] & [maven-release-plugin] prefix for actions

---

jenkins-jobs/job-dsl/deploy_debezium_tool_images.groovy
jenkins-jobs/job-dsl/deploy_docker_images.groovy
jenkins-jobs/job-dsl/ocp_downstream_apicurio_prepare.groovy
jenkins-jobs/job-dsl/ocp_downstream_artifact_server_prepare.groovy
jenkins-jobs/job-dsl/ocp_downstream_strimzi_prepare.groovy
jenkins-jobs/job-dsl/ocp_openshift_test.groovy
jenkins-jobs/job-dsl/release_debezium_stage_prod.groovy
jenkins-jobs/job-dsl/release_deploy_snapshots.groovy
jenkins-jobs/job-dsl/release_upstream.groovy
jenkins-jobs/job-dsl/rhel_downstream_prepare.groovy
jenkins-jobs/pipelines/build-debezium-images.groovy
jenkins-jobs/pipelines/build-debezium-tool-images.groovy
jenkins-jobs/pipelines/deploy-snapshots.groovy
jenkins-jobs/pipelines/downstream_apicurio_prepare_pipeline.groovy
jenkins-jobs/pipelines/downstream_artifact_server_prepare_pipeline.groovy
jenkins-jobs/pipelines/downstream_prepare_pipeline.groovy
jenkins-jobs/pipelines/openshift_pipeline.groovy
jenkins-jobs/pipelines/prod-release-pipeline.groovy
jenkins-jobs/pipelines/release-pipeline.groovy
jenkins-jobs/pipelines/rhel_downstream_prepare_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4071

DBZ-4071 Pass recipient mail address as a param to pipeline job

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/junit/PostgresDatabaseVersionResolver.java

https://issues.redhat.com/browse/DBZ-4081

DBZ-4081 Close leaking connections

---

debezium-testing/debezium-testing-system/pom.xml
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/ConfigProperties.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/OpenShiftUtils.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/OperatorController.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/artifacts/OcpArtifactServerController.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/artifacts/OcpArtifactServerDeployer.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/OcpKafkaConnectDeployer.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/StrimziOperatorController.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/fixtures/kafka/OcpKafka.java
debezium-testing/debezium-testing-system/src/test/resources/artifact-server/010-deployment.yaml
debezium-testing/debezium-testing-system/src/test/resources/artifact-server/020-service.yaml
debezium-testing/debezium-testing-system/src/test/resources/kafka-resources/v1beta1/021-kafka-connect.yaml
debezium-testing/debezium-testing-system/src/test/resources/kafka-resources/v1beta2/021-kafka-connect.yaml
debezium-testing/debezium-testing-system/src/test/resources/kafka-resources/v1beta2/121-kafka-connect-build.yaml
jenkins-jobs/pipelines/openshift_pipeline.groovy

https://issues.redhat.com/browse/DBZ-1777

Using Strimzi's KC build 

---

debezium-server/debezium-server-bom/pom.xml

https://issues.redhat.com/browse/DBZ-4070

DBZ-4070 Use Debezium version drivers in Server

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/InfinispanLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java

https://issues.redhat.com/browse/DBZ-4106
This PR can safely be applied to both 1.8 and 1.7.  I'll open a separate PR specifically for 1.6.

DBZ-4106 Don't continuously reconfigure DatabaseHistory

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlParserIT.java

https://issues.redhat.com/browse/DBZ-4005

DBZ-4005 Remove hard-coded version of MySQL example image

---

debezium-server/debezium-server-dist/pom.xml
debezium-server/debezium-server-dist/src/main/resources/distro/conf/application.properties.example
documentation/modules/ROOT/pages/operations/debezium-server.adoc

Related jira issue:
https://issues.redhat.com/browse/DBZ-4114

Add Quarkus json logging extension

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-4215

DBZ-4215 Support MySQL dual password syntax

---

debezium-testing/debezium-testing-system/pom.xml

https://issues.redhat.com/browse/DBZ-4226

DBZ-4226 Upgraded strimzi dependency

---

jenkins-jobs/job-dsl/node_snapshot_build.groovy
jenkins-jobs/job-dsl/view_list_jenkins.groovy
jenkins-jobs/pipelines/node_snapshot_build_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4122

DBZ-4122 added jenkins job for creating image snapshots

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java

https://issues.redhat.com/browse/DBZ-4231

DBZ-4231 Remove SqlServerConnector database.user Required Validator

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresDefaultValueConverter.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresDefaultValueConverterIT.java

https://issues.redhat.com/browse/DBZ-4137
Supersedes https://github.com/debezium/debezium/pull/2876/

DBZ-4137 Default value fixes for Postgres connector

---

debezium-testing/debezium-testing-system/pom.xml
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/ConfigProperties.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/OpenShiftUtils.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/OperatorController.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/OcpKafkaConnectDeployer.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/OcpKafkaDeployer.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/fixtures/databases/OcpOracle.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/fixtures/kafka/OcpKafka.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/fixtures/registry/OcpApicurio.java
debezium-testing/debezium-testing-system/src/test/resources/kafka-resources/v1beta2/010-kafka.yaml
debezium-testing/debezium-testing-system/src/test/resources/kafka-resources/v1beta2/021-kafka-connect.yaml
debezium-testing/debezium-testing-system/src/test/resources/kafka-resources/v1beta2/121-kafka-connect-build.yaml

https://issues.redhat.com/browse/DBZ-4227

DBZ-4227 Ability to use authenticated image registry with KC build 

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTimestampColumnIT.java

https://issues.redhat.com/browse/DBZ-4241

DBZ-4241 Add more assertions for MySqlTimestampColumnIT

---

jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4242

DBZ-4242 Using 0.0.0.0 as database hostnem in oracle ci

---

jenkins-jobs/job-dsl/ocp_downstream_apicurio_prepare.groovy
jenkins-jobs/job-dsl/ocp_downstream_artifact_server_prepare.groovy
jenkins-jobs/job-dsl/ocp_downstream_strimzi_prepare.groovy
jenkins-jobs/job-dsl/rhel_downstream_prepare.groovy
jenkins-jobs/pipelines/downstream_apicurio_prepare_pipeline.groovy
jenkins-jobs/pipelines/rhel_downstream_prepare_pipeline.groovy
jenkins-jobs/scripts/build-rhel-kafka-image.sh
jenkins-jobs/scripts/copy-plugins.sh

https://issues.redhat.com/browse/DBZ-4235

DBZ-4235 QE jenkins jobs consolidation

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java

https://issues.redhat.com/browse/DBZ-4204

DBZ-4204 Allow ORA-04030 exceptions to be retried

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDdlParserTest.java

https://issues.redhat.com/browse/DBZ-4240

DBZ-4240 Resolve asterisk precision as default number precision

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/DmlParser.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java
debezium-microbenchmark-oracle/src/main/java/io/debezium/performance/connector/oracle/parser/LogMinerDmlParserPerf.java

https://issues.redhat.com/browse/DBZ-4252

DBZ-4252 Remove unused code

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetrics.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/InfinispanLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleStreamingMetricsTest.java

https://issues.redhat.com/browse/DBZ-4222
This is still a WIP while I review each metric.

DBZ-4222 Fix Oracle metrics calculations

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-4255

DBZ-4255 Reduce verbosity of logging Oracle memory metrics

---

debezium-server/debezium-server-redis/src/main/java/io/debezium/server/redis/RedisStreamChangeConsumer.java
documentation/modules/ROOT/pages/operations/debezium-server.adoc

https://issues.redhat.com/browse/DBZ-3708

DBZ-3708 Add `debezium.sink.redis.null.value` configurable option

---

debezium-testing/debezium-testing-system/pom.xml
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/databases/AbstractOcpDatabaseDeployer.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/databases/db2/OcpDB2Deployer.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/databases/oracle/OcpOracleDeployer.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/fixtures/databases/OcpDB2.java

https://issues.redhat.com/browse/DBZ-4268

DBZ-4268 Updated system testsuite to use private images for DB2

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java

https://issues.redhat.com/browse/DBZ-3611

DBZ-3611 Avoid NPE with database include/exclude lists

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/IncrementalSnapshotWithRecompileIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
documentation/modules/ROOT/pages/connectors/sqlserver.adoc

https://issues.redhat.com/browse/DBZ-4249

DBZ-4249 Creates the incremental.snapshot.option.recompile connector configuration for SQL Server

---

debezium-core/src/main/java/io/debezium/relational/history/AbstractDatabaseHistory.java

https://issues.redhat.com/browse/DBZ-4275

DBZ-4275 fix AbstractDatabaseHistory typo

---

debezium-server/debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java

https://issues.redhat.com/browse/DBZ-3570

DBZ-3570 return non-zero exit code from Debezium server upon failure

---

pom.xml

https://issues.redhat.com/browse/DBZ-4286

DBZ-4286 Upgrade MySQL driver to 8.0.27

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/BinlogReader.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java

https://issues.redhat.com/browse/DBZ-1344

DBZ-1344 Don't warn about empty schema when using snapshot mode 'never'

---

.github/workflows/db2-workflow.yml
.github/workflows/vitess-workflow.yml

https://issues.redhat.com/browse/DBZ-4289

DBZ-4289 Avoiding superfluous component builds

---

debezium-bom/pom.xml
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
documentation/modules/ROOT/pages/connectors/mysql.adoc

https://issues.redhat.com/browse/DBZ-4286
Sending this PR, as I'm not sure whether the update from 8.0.21 to 8.0.27 will go without any other accomodating changes.

DBZ-4286 (Debezium 1.6)

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
documentation/modules/ROOT/pages/connectors/postgresql.adoc

https://issues.redhat.com/browse/DBZ-1931

postgres: Reflect decimal.handling.mode in money conversion and allow to specify scale

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-4225

DBZ-4225 Handle null lastOffset value

---

documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/sqlserver.adoc

Updating docs with the new config option
This is the follow-up to https://github.com/debezium/debezium/pull/2853

DBZ-4196 Document allow.schema.changes config option

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java

https://issues.redhat.com/browse/DBZ-1042

postgres: allow numeric slot name

---

documentation/modules/ROOT/pages/connectors/vitess.adoc

Add documentation for the new config in https://issues.redhat.com/browse/DBZ-4295

DBZ-4295 documentation for the new config

---

.github/workflows/mongodb-workflow.yml
debezium-connector-mongodb/pom.xml
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TestHelper.java

https://issues.redhat.com/browse/DBZ-3938

DBZ-3938 Add CI for MongoDB 5.0

---

.github/workflows/vitess-workflow.yml
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouter.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouterConfigDefinition.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouterTest.java
debezium-core/src/main/java/io/debezium/transforms/SmtManager.java
debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java
debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterConfigDefinition.java
debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterDelegate.java
debezium-core/src/main/java/io/debezium/transforms/tracing/ActivateTracingSpan.java
debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc
documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc

https://issues.redhat.com/browse/DBZ-4012
This PR is based on PR #2877 and therefore once the parent PR is merged, this can follow afterward.

DBZ-4012 Promote Outbox SMT to GA

---

jenkins-jobs/job-dsl/connector_db2_matrix_test.groovy
jenkins-jobs/job-dsl/connector_mongodb_matrix_test.groovy
jenkins-jobs/job-dsl/connector_mysql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_postgresql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_sql_server_matrix_test.groovy
jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4316

DBZ-4316 Updated functional ci jobs to work with new downstream source archive

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/grant.sql

https://issues.redhat.com/browse/DBZ-4304

DBZ-4304 Add MariaDB specific username for MySQL parser

---

jenkins-jobs/job-dsl/connector_db2_matrix_test.groovy
jenkins-jobs/job-dsl/connector_mongodb_matrix_test.groovy
jenkins-jobs/job-dsl/connector_mysql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_postgresql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_sql_server_matrix_test.groovy
jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy

Continuation of https://issues.redhat.com/browse/DBZ-4316

DBZ-4316 ignore SSL verification when performing tests over downstremm bits

---

jenkins-jobs/job-dsl/connector_db2_matrix_test.groovy

https://issues.redhat.com/browse/DBZ-4316

DBZ-4316 Updated db2 functional ci job

---

jenkins-jobs/job-dsl/connector_postgresql_matrix_test.groovy

https://issues.redhat.com/browse/DBZ-4333

DBZ-4333 increased nonactive timeout for postgresql connector ci job

---

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouterTest.java
documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc

https://issues.redhat.com/browse/DBZ-4318
---
Modified default type of aggregateid In outbox collection expected by MongoDB Outbox Event Router for both tests and documentation.

DBZ-4318 Modified default type of aggregateid In outbox collection

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java

https://issues.redhat.com/browse/DBZ-4236
With all the refactoring in DBZ-4169, it made sense to make this PR on top of those changes.

DBZ-4236 Unify Oracle LogMiner event processors

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4

https://issues.redhat.com/browse/DBZ-4320

DBZ-4320 support for JSON function in MySQL index

---

debezium-testing/debezium-testing-system/pom.xml
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/OcpKafkaDeployer.java
debezium-testing/debezium-testing-system/src/test/resources/kafka-resources/v1beta2/121-kafka-connect-build.yaml

https://issues.redhat.com/browse/DBZ-4344

DBZ-4344: updated pull secret configuration for downstream builds

---

jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4322
Hi @jcechace.  Could you please review and merge this if it looks good to you?  I've pushed an Oracle 12.2.0.1 image to the internal image repository and confirmed that it's available.

DBZ-4322 Test Oracle 12.2.0.1 on CI

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresOffsetContext.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java

https://issues.redhat.com/browse/DBZ-4343

DBZ-4343 Use schema component for incremental snapshot TableId

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java

https://issues.redhat.com/browse/DBZ-4276

DBZ-4276 Extend LOB tests when LOB is disabled

---

documentation/modules/ROOT/pages/connectors/sqlserver.adoc

A proposition of doc for https://issues.redhat.com/browse/DBZ-4330

Expliciting SQL Server connector limitation for materialized views

---

debezium-testing/debezium-testing-system/pom.xml
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/ConfigProperties.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/databases/SqlDatabaseClient.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/databases/db2/OcpDB2Controller.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/oracle/OcpOracleConnectorIT.java
jenkins-jobs/job-dsl/ocp_openshift_test.groovy
jenkins-jobs/pipelines/openshift_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4267

DBZ-4267 Updated testsuite CI job

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SignalsIT.java
debezium-connector-postgres/src/test/resources/log4j.properties
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
debezium-core/src/main/java/io/debezium/pipeline/signal/Signal.java
debezium-core/src/test/java/io/debezium/data/VerifyRecord.java

https://issues.redhat.com/browse/DBZ-4364

DBZ-4364 Fix missing method call

---

COPYRIGHT.txt
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDefaultValueIT.java
documentation/modules/ROOT/pages/connectors/oracle.adoc
jenkins-jobs/scripts/config/Aliases.txt

https://issues.redhat.com/browse/DBZ-1539

DBZ-1539 Add `interval.handling.mode` to Oracle connector

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDefaultValueConverter.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDefaultValueIT.java

https://issues.redhat.com/browse/DBZ-4360

DBZ-4360 Correctly parse default values with trailing spaces

---

documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/oracle.adoc
documentation/modules/ROOT/pages/connectors/postgresql.adoc
documentation/modules/ROOT/pages/connectors/sqlserver.adoc

https://issues.redhat.com/browse/DBZ-4127

DBZ-4127 Document `incremental.snapshot.chunk.size`

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotIT.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeEventSourceFactory.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSignalBasedIncrementalSnapshotChangeEventSource.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/util/ColumnUtils.java
debezium-core/src/test/java/io/debezium/junit/SkipTestRule.java
debezium-core/src/test/java/io/debezium/junit/SkipWhenConnectorUnderTest.java
debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/oracle.adoc
documentation/modules/ROOT/pages/connectors/postgresql.adoc
documentation/modules/ROOT/pages/connectors/sqlserver.adoc

https://issues.redhat.com/browse/DBZ-4272
https://issues.redhat.com/browse/DBZ-4331

DBZ-4272 Incrementally snapshot after schema change without NPE

---

jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4377
Additionally fixed few other structural issues since this is our first pipeline matrix.

DBZ-4377 Fixed and restructured Oracle test matrix in order to execute correctly with multiple versions

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java

https://issues.redhat.com/browse/DBZ-4384

DBZ-4384 Correctly skip emitting events when LOB_ERASE is detected

---

jenkins-jobs/job-dsl/ocp_openshift_test.groovy
jenkins-jobs/pipelines/openshift_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4382

 DBZ-4382 Fixed Apicurio deployment and test execution in CI

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-4376

DBZ-4376 Fix NPE when database.dbname or database.pdb.name is in non-uppercase

---

debezium-parent/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-4386

DBZ-4386 Upgrade impsort-maven-plugin to 1.6.2

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/FieldTest.java

Add schema metadata for SqlServer Connector, and test case

DBZ-3697 Adding metadata to fields for SQLServerConnector

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/grant.sql

https://issues.redhat.com/browse/DBZ-4397
Upstream PR https://github.com/antlr/grammars-v4/pull/2408

DBZ-4397 Add MySQL grant username to username syntax

---

debezium-parent/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-4387

DBZ-4387 Upgrade formatter-maven-plugin to 2.16.0

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBinaryModeIT.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-4400

Support `binary.handling.mode` for Oracle

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-4402

DBZ-4402 Support keyword CHAR SET for defining charset options

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_analyze.sql

https://issues.redhat.com/browse/DBZ-4396

DBZ-4396 Improve Oracle ANALYZE grammar support

---

.github/workflows/connect-rest-extension-workflow.yml
debezium-bom/pom.xml
debezium-connect-rest-extension/pom.xml
debezium-connect-rest-extension/src/test/java/io/debezium/kcrestextension/DebeziumResourceIT.java
debezium-connect-rest-extension/src/test/java/io/debezium/kcrestextension/DebeziumResourceNoTopicCreationIT.java
debezium-connect-rest-extension/src/test/java/io/debezium/kcrestextension/TestHelper.java

https://issues.redhat.com/browse/DBZ-4028

DBZ-4028 Add test cases for KC REST extension

---

debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/ConfigProperties.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/resources/ConnectorFactories.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/oracle/DockerRhelOracleConnectorIT.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/oracle/OcpAvroOracleConnectorIT.java

Additional touches for
https://issues.redhat.com/browse/DBZ-3963
https://issues.redhat.com/browse/DBZ-4382

Oracle and APC fixes

---

debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
debezium-core/src/main/java/io/debezium/util/Strings.java

Also fixing incorrect JavaDoc.
Supersedes https://github.com/debezium/debezium/pull/3013.
https://issues.redhat.com/browse/DBZ-4341

DBZ-4341 Improving logging;

---

debezium-server/debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/EventHubsChangeConsumer.java

https://issues.redhat.com/browse/DBZ-4277

DBZ-4277 Multi-batch dispatch to EventHubs

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-4426

DBZ-4426 Log message when Oracle schema locks are disabled by configuration

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-3306

DBZ-3306 Only emit schema changes if table schema actual changed

---

documentation/modules/ROOT/pages/connectors/postgresql.adoc

Fix typo in postgresql.adoc

---

debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-infinispan.xml
debezium-connector-oracle/pom.xml

https://issues.redhat.com/browse/DBZ-4446

DBZ-4446 Option to disable Infinispan in Oracle

---

.github/workflows/formatting-check.yml

https://issues.redhat.com/browse/DBZ-4429

DBZ-4429 Improve caching for formatter job

---

debezium-server/debezium-server-dist/src/main/resources/assemblies/server-distribution.xml

https://issues.redhat.com/browse/DBZ-4452

DBZ-4452 Remove log4j from server distribution

---

jenkins-jobs/job-dsl/connector_db2_matrix_test.groovy
jenkins-jobs/job-dsl/connector_mongodb_matrix_test.groovy
jenkins-jobs/job-dsl/connector_mysql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_postgresql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_sql_server_matrix_test.groovy
jenkins-jobs/job-dsl/kafka_1_x_test.groovy

https://issues.redhat.com/browse/DBZ-4373

DBZ-4373 Run CI during weekends

---

debezium-connect-rest-extension/src/test/java/io/debezium/kcrestextension/TestHelper.java

https://issues.redhat.com/browse/DBZ-4465

DBZ-4465 Change version under test to 1.9.0

---

.github/workflows/vitess-workflow.yml
pom.xml

https://issues.redhat.com/browse/DBZ-4463

DBZ-4463 Upgrade to SQL Server driver 9.x

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresShutdownIT.java

https://issues.redhat.com/browse/DBZ-4469

DBZ-4469 Test should run with any Postgres version

---

jenkins-jobs/pipelines/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-4072
Will be merged after 1.8.0.Final release

DBZ-4072 Verify the version is present in Jira

---

jenkins-jobs/pipelines/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-4383
Deployed after the 1.8.0.Final release

DBZ-4383 Use Jira PAT insted of basic auth

---

.github/workflows/db2-workflow.yml
debezium-core/src/test/java/io/debezium/junit/SkipTestRule.java
debezium-core/src/test/java/io/debezium/junit/SkipWhenConnectorUnderTest.java
debezium-core/src/test/java/io/debezium/junit/SkipWhenConnectorsUnderTest.java
debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java

https://issues.redhat.com/browse/DBZ-4467

DBZ-4467 Skip unsupported test for Db2

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbPartition.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetPartition.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlPartition.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OraclePartition.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresPartition.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerPartition.java
debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java

refer https://issues.redhat.com/browse/DBZ-4472

DBZ-4472 Make connector task partition readability for log

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-core/src/main/java/io/debezium/relational/ddl/DataTypeBuilder.java
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4

Refer [DBZ-4497](https://issues.redhat.com/browse/DBZ-4497)

DBZ-4497 Parse multiple signed/unsigned keyword from ddl statement failed

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-core/src/main/java/io/debezium/relational/TableEditorImpl.java

https://issues.redhat.com/projects/DBZ/issues/DBZ-4503

DBZ-4503 Drop the primary key column getting exception

---

COPYRIGHT.txt
README.md
README_ZH.md
jenkins-jobs/scripts/config/Aliases.txt

- update readme_zh.md to catch up with readme.md.
- fix misspell in readme.md

update readme_zh.md and readme.md

---

jenkins-jobs/job-dsl/node_snapshot_build.groovy
jenkins-jobs/pipelines/node_snapshot_build_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4486

DBZ-4486 Image snapshot creation jenkins job uses ansible-vault

---

jenkins-jobs/job-dsl/connector_db2_matrix_test.groovy
jenkins-jobs/job-dsl/connector_mongodb_matrix_test.groovy
jenkins-jobs/job-dsl/connector_mysql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_oracle_matrix.groovy
jenkins-jobs/job-dsl/connector_postgresql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_sql_server_matrix_test.groovy
jenkins-jobs/job-dsl/deploy_debezium_tool_images.groovy
jenkins-jobs/job-dsl/deploy_docker_images.groovy
jenkins-jobs/job-dsl/kafka_1_x_test.groovy
jenkins-jobs/job-dsl/node_snapshot_build.groovy
jenkins-jobs/job-dsl/ocp_downstream_apicurio_prepare.groovy
jenkins-jobs/job-dsl/ocp_downstream_artifact_server_prepare.groovy
jenkins-jobs/job-dsl/ocp_downstream_strimzi_prepare.groovy
jenkins-jobs/job-dsl/ocp_openshift_test.groovy
jenkins-jobs/job-dsl/release_debezium_nightly_image.groovy
jenkins-jobs/job-dsl/release_deploy_snapshots.groovy
jenkins-jobs/job-dsl/rhel_downstream_prepare.groovy
jenkins-jobs/job-dsl/tools_source_clear.groovy

https://issues.redhat.com/browse/DBZ-4506

DBZ-4506 Set number of stored builds for jobs to 10

---

debezium-connect-rest-extension/pom.xml
debezium-connect-rest-extension/src/main/java/io/debezium/kcrestextension/Module.java
debezium-connect-rest-extension/src/main/resources/io/debezium/kcrestextension/build.version
debezium-connect-rest-extension/src/test/java/io/debezium/kcrestextension/DebeziumResourceIT.java
debezium-connect-rest-extension/src/test/java/io/debezium/kcrestextension/DebeziumResourceNoTopicCreationIT.java
debezium-connect-rest-extension/src/test/java/io/debezium/kcrestextension/TestHelper.java

https://issues.redhat.com/browse/DBZ-4466

DBZ-4466 Make REST extension tests independent of source code version

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotContext.java

An infinite while loop can happen on connector restart when the first event after the restart is a transaction commit event and the current GTID is still undefined.
The solution is to check that the GTID changes when the current GTID is undefined.

DBZ-4502 Check GTID changes when current GTID is undefined

---

debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-drivers.xml
debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-infinispan.xml
debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution.xml

https://issues.redhat.com/browse/DBZ-4507

DBZ-4507 Remove wrong scope test dep

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbChangeSnapshotOplogRecordEmitter.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbChangeStreamChangeRecordEmitter.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlChangeRecordEmitter.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/BinlogReader.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/BaseChangeRecordEmitter.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerChangeRecordEmitter.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamChangeRecordEmitter.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeRecordEmitter.java
debezium-core/src/main/java/io/debezium/pipeline/AbstractChangeRecordEmitter.java
debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
debezium-core/src/main/java/io/debezium/pipeline/metrics/ChangeEventSourceMetricsMXBean.java
debezium-core/src/main/java/io/debezium/pipeline/metrics/PipelineMetrics.java
debezium-core/src/main/java/io/debezium/pipeline/metrics/StreamingChangeEventSourceMetrics.java
debezium-core/src/main/java/io/debezium/pipeline/source/spi/DataChangeEventListener.java
debezium-core/src/main/java/io/debezium/pipeline/spi/ChangeRecordEmitter.java
debezium-core/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java
debezium-core/src/main/java/io/debezium/relational/SnapshotChangeRecordEmitter.java
documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc

Refer https://issues.redhat.com/browse/DBZ-4351

DBZ-4351 Add create/update/delete event seen metrics for monitor upstream dml operation

---

jenkins-jobs/pipelines/node_snapshot_build_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4516

DBZ-4516 Added double quotes when accessing variable

---

debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-drivers.xml
debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-infinispan.xml
debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution.xml
debezium-connector-mongodb/pom.xml
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/metadata/MongoDbConnectorMetadata.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/metadata/MongoDbConnectorMetadataProvider.java
debezium-connector-mongodb/src/main/resources/META-INF/services/io.debezium.metadata.ConnectorMetadataProvider
debezium-connector-mysql/pom.xml
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/metadata/MySqlConnectorMetadata.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/metadata/MySqlConnectorMetadataProvider.java
debezium-connector-mysql/src/main/resources/META-INF/services/io.debezium.metadata.ConnectorMetadataProvider
debezium-connector-oracle/pom.xml
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/metadata/OracleConnectorMetadata.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/metadata/OracleConnectorMetadataProvider.java
debezium-connector-oracle/src/main/resources/META-INF/services/io.debezium.metadata.ConnectorMetadataProvider
debezium-connector-postgres/pom.xml
debezium-connector-sqlserver/pom.xml
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metadata/SqlServerConnectorMetadata.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metadata/SqlServerConnectorMetadataProvider.java
debezium-connector-sqlserver/src/main/resources/META-INF/services/io.debezium.metadata.ConnectorMetadataProvider
debezium-schema-generator/src/main/java/io/debezium/schemagenerator/SchemaGenerator.java
debezium-schema-generator/src/main/java/io/debezium/schemagenerator/maven/OpenApiGeneratorMojo.java
debezium-schema-generator/src/main/java/io/debezium/schemagenerator/maven/SchemaGeneratorMojo.java

https://issues.redhat.com/browse/DBZ-4460

DBZ-4460 Apply schema generator plug-in to all connectors

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-4504

DBZ-4504 Update date functions for MariaDB

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-4528

DBZ-4528 Document ORA-04036 PGA_AGGREGATE_LIMIT solution

---

jenkins-jobs/scripts/generate-release-notes.groovy

https://issues.redhat.com/browse/DBZ-4513
@Naros Could you please take a look?

DBZ-4513 Generator for release notes and changelog fragments

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-4494

DBZ-4494 Document reason/description for user grants w/Oracle

---

debezium-bom/pom.xml

https://issues.redhat.com/browse/DBZ-4527

DBZ-4527 Upgrade protobuf to 3.19.2

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java

https://issues.redhat.com/browse/DBZ-4408

DBZ-4408 Remove `log.mining.log.file.query.max.retries`

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/EmbeddedInfinispanLogMinerEventProcessor.java

https://issues.redhat.com/browse/DBZ-4526
We originally relied on `Map#get` when parsing the configuration to retrieve the specific `ConfigurationBuilder` associated with the user provided XML configuration for an embedded Infinispan cache.  If the user's configuration used a name that differed from the names we rely upon in `CacheProvider`, this lead to a `NullPointerException`.
We can make some assumptions that the provided XML should only ever map to 1 cache configuration and it should be valid.  So when we detect only 1 valid XML configuration from the parser, we can fetch the ConfigurationBuilder using the iterator instead, avoiding the NullPointerException if the user provided a different cache name, and therefore being more resilient.

DBZ-4526 Relax cache name limitations on Infinispan embedded cache configs

---

RELEASING.md

https://issues.redhat.com/browse/DBZ-4539
This is a follow-up to https://github.com/debezium/debezium/pull/3104 and should be merged after.

DBZ-4539 Update release procedure on documentation configuration

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java

https://issues.redhat.com/browse/DBZ-4542

DBZ-4542 Fix LogMinerHelperIT test failure w GH Oracle CI

---

documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/mongodb.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/oracle.adoc
documentation/modules/ROOT/pages/connectors/postgresql.adoc
documentation/modules/ROOT/pages/connectors/sqlserver.adoc

https://issues.redhat.com/browse/DBZ-4300
Supersedes PR #3113

DBZ-4300 Fix incorrect attribute for link to DBZ supported config pg

---

pom.xml

https://issues.redhat.com/browse/DBZ-4374

DBZ-4374 Upgrade to PostgreSQL driver 42.3.1

---

pom.xml

https://issues.redhat.com/browse/DBZ-4117

DBZ-4117 Upgrade to Quarkus 2.6.2.Final

---

documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc
documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc

https://issues.redhat.com/browse/DBZ-4457

DBZ-4457 Clarify Outbox JSON expansion requirements

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractMysqlFieldReader.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MysqlBinaryProtocolFieldReader.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MysqlTextProtocolFieldReader.java

https://issues.redhat.com/browse/DBZ-4371

DBZ-4371 Log problematic column values

---

.github/workflows/server-workflow.yml

https://issues.redhat.com/browse/DBZ-4468

DBZ-4468 Skip non-server tests

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnector.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java

https://issues.redhat.com/browse/DBZ-4415

DBZ-4415 oplog mode is not supported for MongoDB 5+

---

documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/oracle.adoc
documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc

[DBZ-4563](https://issues.redhat.com/browse/DBZ-4563)
Updates to address downstream build errors and tweak content.
Tested locally in Antora and in a downstream build.
The changes in this PR should be backported to 1.7.

DBZ-4563 Misc updates to fix build errors and update content.

---

debezium-bom/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-4565

DBZ-4565 Align Apicurio dependency with Quarkus

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DebeziumEngineIT.java
debezium-embedded/src/main/java/io/debezium/embedded/ConvertingEngineBuilder.java

https://issues.redhat.com/browse/DBZ-4566

DBZ-4566 Used topic names for Debezium Engine converters

---

jenkins-jobs/pipelines/rhel_downstream_prepare_pipeline.groovy
jenkins-jobs/scripts/build-rhel-kafka-image.sh
jenkins-jobs/scripts/copy-plugins.sh

https://issues.redhat.com/browse/DBZ-4296

DBZ-4296 Fixed incorrect pushing of autotag images

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/ReplicationConnectionIT.java

https://issues.redhat.com/browse/DBZ-4517

DBZ-4517 Enable correct config opts for retrying

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java

https://issues.redhat.com/browse/DBZ-4575

DBZ-4575 Filter events based on database name

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbErrorHandler.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlErrorHandler.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresErrorHandler.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java
debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
debezium-core/src/main/java/io/debezium/pipeline/ErrorHandler.java
debezium-core/src/test/java/io/debezium/pipeline/ErrorHandlerTest.java

https://issues.redhat.com/browse/DBZ-4577
Please review - if approved the changes the extra connectors will be added.

DBZ-4577 Provide custom error message handling

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresErrorHandler.java

https://issues.redhat.com/browse/DBZ-4520

DBZ-4520 Add backend errors among retriable

---

.github/workflows/missing-commits-by-issue-key.yml

https://issues.redhat.com/browse/DBZ-4063

DBZ-4063 Use defined secret token

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresErrorHandler.java

@jpechane @Naros, could one of you review and merge this one? It's an amendment to Jiri's earlier PR for this issue. In general, let's make static collections immutable whenever we can, and also let's use those annotations for designating these aspects.

DBZ-4520 Making static collections immutable

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
documentation/modules/ROOT/pages/connectors/postgresql.adoc

https://issues.redhat.com/browse/DBZ-4419

DBZ-4419 Deprecate TruncateHandlingMode, favor skipped.operations

---

debezium-bom/pom.xml
debezium-server/debezium-server-core/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-4569

DBZ-4569 Upgrade Apicurio and Confluent to the latest version

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresErrorHandler.java

https://issues.redhat.com/browse/DBZ-4592

DBZ-4592 Make OID not found exception retriable

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java

https://issues.redhat.com/browse/DBZ-4567

DBZ-4567 DDL and DML events exclude built-in schemas

---

debezium-parent/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-4580

DBZ-4580 Remove non-plugin `maven-filtering` from build plugins

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleRowIdDataTypeIT.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-4595

DBZ-4595 Support Oracle ROWID data type

---

jenkins-jobs/job-dsl/system_test.groovy
jenkins-jobs/pipelines/system_pipeline.groovy
jenkins-jobs/scripts/ocp-projects.sh

https://issues.redhat.com/browse/DBZ-4602

DBZ 4602: Cleanup project management in test-suite job

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/ColumnDefinitionParserListener.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
documentation/modules/ROOT/pages/connectors/mysql.adoc

https://issues.redhat.com/browse/DBZ-4583

DBZ-4583 Workround for columns longer than max int

---

debezium-core/src/test/java/io/debezium/kafka/KafkaServer.java
debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
pom.xml

https://issues.redhat.com/browse/DBZ-4610

DBZ-4610 Upgrade to Kafka 3.1.0

---

documentation/modules/ROOT/pages/operations/debezium-server.adoc

https://issues.redhat.com/browse/DBZ-4613

DBZ-4613 Fix property name for `debezium.transforms.<name>.type`

---

.github/workflows/debezium-workflow.yml

https://issues.redhat.com/browse/DBZ-4562

DBZ-4562 Use fetch-depth 0 for file changes job

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-4597

DBZ-4597 Add Oracle FAQ entry about "Logs don't contain offset"

---

jenkins-jobs/job-dsl/release_upstream.groovy
jenkins-jobs/pipelines/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-4623
https://issues.redhat.com/browse/DBZ-4624

Release pipeline changes

---

documentation/modules/ROOT/pages/connectors/mysql.adoc

https://issues.redhat.com/browse/DBZ-4171

DBZ-4171 Connector name is database server name

---

jenkins-jobs/pipelines/node_snapshot_build_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4611

DBZ-4611 Fixed incorrect updating of gitlab certificate in node image snapshot job

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-4609

DBZ-4609 Using partition_extended_names for drop partition

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotCaseSensitiveIT.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedSnapshotChangeEventSourceTest.java
debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java

https://issues.redhat.com/browse/DBZ-4584

DBZ-4584 Support case-sensitive Oracle incremental snapshots

---

documentation/antora.yml

https://issues.redhat.com/browse/DBZ-4644

DBZ-4644 Refer to `main` branch as `main` version

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java

https://issues.redhat.com/browse/DBZ-4650

DBZ-4650 Mark incompatible Xstream tests as LogMiner-only

---

pom.xml

https://issues.redhat.com/browse/DBZ-4658

DBZ-4658 Upgrade PostgreSQL driver

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorJsonIT.java
pom.xml

https://issues.redhat.com/browse/DBZ-4605
This will for for MySQL 8 only after new binlog client with https://github.com/osheroff/mysql-binlog-connector-java/pull/64 is used,

DBZ-4605 Test MySQL partial update

---

debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-3679

DBZ-3679 Clarify log messages

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/FieldTest.java
debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java

Addition of Oracle connector property metadata to define grouping and ordering

DBZ-4314 Define Oracle category grouping and ordering

---

jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4305

DBZ-4305 Add Oracle 21.3.0 to Oracle LogMiner CI matrix

---

debezium-bom/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-4668

DBZ-4668 Making sure right protoc version is used

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/zzz/ZZZGtidSetIT.java

https://issues.redhat.com/browse/DBZ-4294

DBZ-4294 Awaiting PURGE has happened

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4

https://issues.redhat.com/browse/DBZ-4675

DBZ-4675 parse page_compressed and page_compression_level table options

---

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoUtilIT.java

https://issues.redhat.com/browse/DBZ-4676

DBZ-4676 Fix MongoUtilIT test failure

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleRowIdDataTypeIT.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-4702

DBZ-4702 Document & fix test - XStream does not support ROWID data type

---

debezium-connector-oracle/src/test/resources/logback-test.xml

https://issues.redhat.com/browse/DBZ-4703

DBZ-4703 Enable DEBUG logging for LcrEventHandler for tests

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerOracleOffsetContextLoader.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamOracleOffsetContextLoader.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/projects/DBZ/issues/DBZ-4367
Supersedes PR #3133

DBZ-4367 LogMiner start mining from oldest pending TX instead of snapshot SCN

---

.github/workflows/debezium-workflow.yml
.github/workflows/sanity-check.yml

https://issues.redhat.com/browse/DBZ-4672

DBZ-4672 GH action build trigger adjustments

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java

https://issues.redhat.com/browse/DBZ-4701

DBZ-4701 executeWithoutCommitting throw exception when auto-commit is enabled

---

pom.xml

https://issues.redhat.com/browse/DBZ-4677

DBZ-4677 Upgrade to Quarkus 2.7.0.Final

---

documentation/antora.yml
documentation/modules/ROOT/pages/install.adoc

https://issues.redhat.com/browse/DBZ-4712

DBZ-4712 Fix documentation build for `main` branch

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java

https://issues.redhat.com/browse/DBZ-4701

DBZ-4701 Align Oracle to adhere to executeWithoutCommitting semantics

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SignalsIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/OracleDatabaseVersionResolver.java

https://issues.redhat.com/browse/DBZ-4305

DBZ-4305 Skip test when using Oracle 21

---

jenkins-jobs/pipelines/deploy-snapshots.groovy

https://issues.redhat.com/browse/DBZ-4628

DBZ-4628 Remove the blocking pauses in the build

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java

https://issues.redhat.com/browse/DBZ-2306

DBZ-2306 Avoid long running TX for publication query

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresDefaultValueConverter.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresDefaultValueConverterIT.java
debezium-core/src/main/java/io/debezium/data/SchemaUtil.java

https://issues.redhat.com/browse/DBZ-4736

DBZ-4736 Handle string NULL default values correctly

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-4707

DBZ-4707 MySQL unparseable DDL - CREATE PROCEDURE

---

pom.xml

https://issues.redhat.com/browse/DBZ-4743

DBZ-4743 Upgrade to Quarkus 2.7.1.Final

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetrics.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java

https://issues.redhat.com/browse/DBZ-4715

DBZ-4715 Fix stream event's source timestamp tz resolution

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/postgresql.adoc
documentation/modules/ROOT/pages/connectors/vitess.adoc

Also making set up section titles consistent.
https://issues.redhat.com/browse/DBZ-4731

DBZ-4731 Adding note on MongoDB Atlas;

---

documentation/modules/ROOT/pages/connectors/sqlserver.adoc

@roldanbob can you check this out, will it create an issue for downstream in particular (I'm not sure how those "module id" attributes in comments play a role here). Thx!

[docs] Updating broken anchor links

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotSourceIT.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/relational/RelationalTableFilters.java
debezium-core/src/test/java/io/debezium/data/SchemaChangeHistory.java
debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java

https://issues.redhat.com/browse/DBZ-3952

DBZ-3952 Store schema for tables not in schema collection list

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-4716

DBZ-4716 Document XStream and DBMS_LOB behavior differences

---

pom.xml

https://issues.redhat.com/browse/DBZ-4759

DBZ-4759 Upgrade MySQL JDBC driver to 8.0.28

---

debezium-testing/debezium-testing-system/pom.xml
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/databases/DatabaseInitListener.java

https://issues.redhat.com/browse/DBZ-4781

DBZ-4781 Excludeding overlapping jackson dependencies

---

jenkins-jobs/pipelines/system_pipeline.groovy

https://issues.redhat.com/browse/DBZ-4601

DBZ-4601 Removed Artifact server build from testsuite pipeline

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-4763

DBZ-4763 Relax parsing of heap & index organized clauses

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSignalBasedIncrementalSnapshotChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleTableIdParser.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleTableIdParserTest.java
debezium-core/src/main/java/io/debezium/relational/TableId.java

https://issues.redhat.com/browse/DBZ-4744

DBZ-4744 Correctly parse signal table name when using domain name

---

debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java

https://issues.redhat.com/browse/DBZ-4773
@jpechane / @Naros, a quick one for one of you.

DBZ-4773 Using right constructor signature based on Kafka client version

---

debezium-testing/debezium-testing-system/pom.xml

https://issues.redhat.com/browse/DBZ-4601

DBZ-4601 Update default KC and AS image names in testsuite

---

debezium-schema-generator/src/main/java/io/debezium/schemagenerator/maven/SchemaGeneratorMojo.java

closes https://issues.redhat.com/browse/DBZ-4800

DBZ-4800 Fix SchemaGeneratorMojo execution with default values no Windows

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-4325
@roldanbob these are the documentation updates I took as action items from our call.  I believe some of this may need to be moved around and/or annotated comments added for downstream rendering.  This PR is open for pushes, so feel free to pull the PR down and add any additional commits to it as you see fit.
@gunnarmorling this is not all the changes related to this issue; these are only the ones that I took as actionable items.

DBZ-4325 Oracle documentation updates

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSourceMetrics.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/SnapshotReader.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/SnapshotReaderMetrics.java
debezium-core/src/main/java/io/debezium/pipeline/metrics/traits/StreamingMetricsMXBean.java

https://issues.redhat.com/browse/DBZ-4824

DBZ-4824 Expect the null value with snapshot CapturedTables metric when skipping snapshotting

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDatabaseSchema.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-4823

DBZ-4823 Log the tableId is null when filter out some tables

---

debezium-testing/debezium-testing-system/pom.xml
jenkins-jobs/job-dsl/ocp_upstream_artifact_server_prepare.groovy
jenkins-jobs/job-dsl/ocp_upstream_kafka_connect_prepare.groovy
jenkins-jobs/pipelines/upstream_artifact_server_prepare_pipeline.groovy
jenkins-jobs/pipelines/upstream_kafka_connect_prepare_pipeline.groovy
jenkins-jobs/scripts/upstream-artifact-server-prepare.sh
jenkins-jobs/scripts/upstream-kafka-connect-prepare.sh

https://issues.redhat.com/browse/DBZ-4601

DBZ-4601 Added Oracle connector handling to AS and KC image creation

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/MySqlJdbcContext.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTestConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnector.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresConnectionIT.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnector.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConfiguration.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
debezium-core/src/test/java/io/debezium/jdbc/JdbcConnectionTest.java
debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedSnapshotChangeEventSourceTest.java
debezium-server/debezium-server-pulsar/src/test/java/io/debezium/server/pulsar/PulsarIT.java
debezium-server/debezium-server-redis/src/test/java/io/debezium/server/redis/RedisOffsetIT.java
debezium-server/debezium-server-redis/src/test/java/io/debezium/server/redis/RedisStreamIT.java

https://issues.redhat.com/browse/DBZ-4801

DBZ-4801 Using JdbcConfiguration over Configuration

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-4823
Just adding event type for flitering trace message

DBZ-4823 Add event type for filtering trace message

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BinlogReaderBufferIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadBinLogIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/UniqueDatabase.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/legacy/MySqlTaskContextTest.java

https://issues.redhat.com/browse/DBZ-4787
Misc. test adjustments

DBZ-4787 Adjusting several tests to run with SSL enabled

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDefaultValueConverter.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java

https://issues.redhat.com/browse/DBZ-4822

DBZ-4822 Mysql: Getting ERROR `Failed due to error: connect.errors.ConnectException: For input string: "false"

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/BinlogReader.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/MySqlJdbcContext.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/MySqlTaskContext.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java

https://issues.redhat.com/browse/DBZ-4832

DBZ-4832 Don't set truststore/keystore parameters to system variables

---

documentation/modules/ROOT/pages/operations/kubernetes.adoc

https://issues.redhat.com/browse/DBZ-2646

DBZ-2646 Add secret configuration to k8s documentation

---

debezium-microbenchmark-oracle/src/main/java/io/debezium/performance/connector/oracle/EndToEndPerf.java

https://issues.redhat.com/browse/DBZ-4860

DBZ-4860 Use JdbcConfiguration class

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-4842

DBZ-4842 Relax supplemental log check when table does not exist

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java

https://issues.redhat.com/browse/DBZ-4787

DBZ-4787 Change mysql ssl truststore/keystore properties description.

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc

https://issues.redhat.com/browse/DBZ-4802

DBZ-4802 Document requirement for primary in the seed

---

documentation/modules/ROOT/pages/integrations/outbox.adoc

https://issues.redhat.com/browse/DBZ-4430

DBZ-4430 Promote Quarkus Outbox to stable (sans OpenTracing support)

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-4851

DBZ-4851 Allow multiple index_attributes in a using_index_clause

---

debezium-core/src/main/java/io/debezium/relational/history/DatabaseHistory.java
debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java

https://issues.redhat.com/browse/DBZ-3762

DBZ-3762 Filter out MySQL inline comments by default

---

documentation/modules/ROOT/pages/connectors/vitess.adoc

Add documentation for https://github.com/debezium/debezium-connector-vitess/pull/78

DBZ-4886 update documentation

---

COPYRIGHT.txt
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java

(ORA-00310,ORA-01343,ORA-01371)

DBZ-4850 Add several retriable SQL error codes

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-core/src/main/java/io/debezium/relational/TableEditorImpl.java

https://issues.redhat.com/browse/DBZ-4786

DBZ-4786 Avoid NPE when removing column which doesn't exists

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java

https://issues.redhat.com/browse/DBZ-4900

DBZ-4900 Use exponential back-off for log availability check

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-4869

DBZ-4869 Log warning rather than exception on incorrect table-level logging level

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDefaultValueTest.java

See [DBZ-3541](https://issues.redhat.com/browse/DBZ-3541).

DBZ-3541: Round decimal default values of integer columns

---

debezium-server/debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java
debezium-server/debezium-server-redis/src/main/java/io/debezium/server/redis/RedisOffsetBackingStore.java
debezium-server/debezium-server-redis/src/test/java/io/debezium/server/redis/RedisOffsetConfigurationIT.java
debezium-server/debezium-server-redis/src/test/java/io/debezium/server/redis/RedisOffsetConfigurationTestProfile.java
debezium-server/debezium-server-redis/src/test/java/io/debezium/server/redis/RedisTestResourceLifecycleManager.java

https://issues.redhat.com/browse/DBZ-4864

DBZ-4864 pass sink properties

---

debezium-testing/debezium-testing-system/pom.xml
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/OcpKafkaConnectDeployer.java

-  Fixed pull secret usage on KC resources
-  Using   Always update policy for snapshots

DBZ-4892 tweaks

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-4884

DBZ-4884 Document AWS timeout and keep-alive requirements

---

.github/workflows/jdk-outreach-workflow.yml

https://issues.redhat.com/browse/DBZ-4924

DBZ-4924 Use new action to setup openjdk in all build steps

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java

https://issues.redhat.com/browse/DBZ-4907

DBZ-4907 Increment Commit SCN when any COMMIT is detected

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleOffsetContextTest.java

https://issues.redhat.com/browse/DBZ-4937

DBZ-4937 Correctly read/write snapshot_scn and snapshot_pending_trx offsets

---

pom.xml

https://issues.redhat.com/browse/DBZ-4955

DBZ-4955 Bump Jackson to 2.23.2

---

jenkins-jobs/job-dsl/release_upstream.groovy
jenkins-jobs/pipelines/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-4957

DBZ-4957 Release pipeline toggle to ignore snapshot deps

---

COPYRIGHT.txt
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresErrorHandler.java

https://issues.redhat.com/browse/DBZ-4948

DBZ-4948 Added connection has been closed PSQLException as retriable

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-4936

DBZ-4936 Don't re-emit transaction on restart with commit SCN equal to offset commit SCN

---

.github/workflows/contributor-check.yml
.github/workflows/debezium-workflow.yml
.github/workflows/octocat-commits-check.yml
.github/workflows/oracle-workflow-test.yml
.github/workflows/sanity-check.yml
.github/workflows/website-build-workflow.yml

https://issues.redhat.com/browse/DBZ-4971

DBZ-4971 Add triggers for 2.x paths in Github CI

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java

https://issues.redhat.com/browse/DBZ-3318

DBZ-3318 Add integration test for `database.url`

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-4936

DBZ-4936 Restrict test to only memory-based buffer

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-4932

DBZ-4932 Use LCR v1 format with Oracle 12.0 and 12.1

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-4953

DBZ-4953 Correctly handle TRUNCATE when LOB is enabled

---

debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-4979

DBZ-4979 Guard against NPE for non-table related DDLs

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java

https://issues.redhat.com/browse/DBZ-4978

DBZ-4978 Avoid NPE during Oracle connector shutdown

---

COPYRIGHT.txt
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractMysqlFieldReader.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
jenkins-jobs/scripts/config/Aliases.txt

https://issues.redhat.com/browse/DBZ-4983

DBZ-4983 Use correct Java encoding Charset in AbstractMysqlFieldReader

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-4980

DBZ-4980 Support CTE with create view statement in MySQL parser

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java

https://issues.redhat.com/browse/DBZ-4987

DBZ-4987 Propagate up all exceptions from LCR handler

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/SelectLobParser.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SelectLobParserTest.java

https://issues.redhat.com/browse/DBZ-4994

DBZ-4994 Fix LOB locator event parsing with escaped single quotes

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnector.java

https://issues.redhat.com/browse/DBZ-5003
MongoDb connector should use "config" database if the database exists. Otherwise, "local" database should be used to get MongoDB version during connector validation.
This is similar to the approach implemented in ReplicaSetDiscovery class.

DBZ-5003 Can't use 'local' database through mongos
