debezium/debezium

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-4963

DBZ-4963 Introduce `log.mining.session.max.ms` config option for Oracle

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-4996

DBZ-4996 Parse references_clause without referenced column list

---

debezium-parent/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-5025
Dry run has passed with this one

DBZ-5025 Update staging plugin

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleOffsetContextTest.java

https://issues.redhat.com/browse/DBZ-5028

DBZ-5028 Scope OracleOffsetContextTest to the LogMiner adapter

---

jenkins-jobs/job-dsl/connector_mongodb_matrix_test.groovy
jenkins-jobs/job-dsl/connector_mysql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_postgresql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_sql_server_matrix_test.groovy

https://issues.redhat.com/browse/DBZ-5017

DBZ-5017 Build debezium-bom locally first

---

debezium-server/README.md
debezium-server/debezium-server-pubsub/pom.xml
debezium-server/debezium-server-pubsub/src/main/java/io/debezium/server/pubsub/PubSubChangeConsumer.java
debezium-server/debezium-server-pubsub/src/test/java/io/debezium/server/pubsub/PubSubIT.java
debezium-server/debezium-server-pubsub/src/test/java/io/debezium/server/pubsub/PubSubTestConfigSource.java
debezium-server/debezium-server-pubsub/src/test/java/io/debezium/server/pubsub/PubSubTestResourceLifecycleManager.java
documentation/modules/ROOT/pages/operations/debezium-server.adoc

https://issues.redhat.com/browse/DBZ-4491
Hi, 
Let me give you a disclaimer and say, that I am not a java developer. So whatever bad stuff you see... please bear with me. 🙏 
There are still a couple of things to do, but I just want to get your feedback before advancing any further.
What I still need to do
PS:
I do have some issues running `mvn clean install`. So formatting might be off. 
The PostgreSQL connector ITs fail for some reason, but I will take this in the chat.

DBZ-4491 add support for Google PubSub emulator

---

debezium-parent/pom.xml

https://issues.redhat.com/browse/DBZ-5026

DBZ-5026 Remove duplicate definition of maven plugin

---

documentation/modules/ROOT/pages/operations/debezium-server.adoc

https://issues.redhat.com/browse/DBZ-5058

DBZ-5058 Fix formatting

---

jenkins-jobs/docker/artifact-server/listing.sh

https://issues.redhat.com/browse/DBZ-5051

DBZ-5051 Update listing.sh

---

.github/workflows/jdk-outreach-workflow.yml

https://issues.redhat.com/browse/DBZ-5041

DBZ-5041 Build debezium-bom along with connectors in jdk outreach job

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-5057

DBZ-5057 Document ORA-01882 and Oracle 11g

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-4762

DBZ-4762 Document excluded built-in schemas

---

debezium-connector-mysql/pom.xml

https://issues.redhat.com/browse/DBZ-5054

DBZ-5054 Wait for the MySQL to be fully started before starting tests

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java

https://issues.redhat.com/browse/DBZ-5006

DBZ-5006 Allow "/" characters in Oracle table names

---

pom.xml

https://issues.redhat.com/browse/DBZ-5062

DBZ-5062 Upgrade to Quarkus 2.8.2.Final

---

.github/workflows/debezium-workflow.yml
.github/workflows/oracle-workflow-test.yml

https://issues.redhat.com/browse/DBZ-5064

DBZ-5064 Use Maven 3.8.4 for GitHub CI

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/AbstractMySqlFieldReader.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlBinaryProtocolFieldReader.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlFieldReader.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTextProtocolFieldReader.java

https://issues.redhat.com/browse/DBZ-5078

DBZ-5078 Rename "Mysql" to "MySql" in related MysqlFieldReader interface

---

debezium-core/src/main/java/io/debezium/transforms/ByLogicalTableRouter.java
documentation/modules/ROOT/pages/transformations/topic-routing.adoc

https://issues.redhat.com/browse/DBZ-5072

DBZ-5072 Config the cache size property for ByLogicalTableRouter caches

---

jenkins-jobs/job-dsl/maven_artifact_check.groovy
jenkins-jobs/scripts/maven-artifact-check.sh

https://issues.redhat.com/browse/DBZ-5082

DBZ-5082 Create CI job for maven repository verification

---

debezium-connect-rest-extension/src/main/java/io/debezium/kcrestextension/DebeziumResource.java

https://issues.redhat.com/browse/DBZ-5092

DBZ-5092 Introduce a new extension api for query debezium version

---

pom.xml

https://issues.redhat.com/browse/DBZ-5060

DBZ-5060 Upgrade postgres driver to version 42.3.5

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationConnection.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorTaskIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresConnectionIT.java
debezium-server/debezium-server-pulsar/src/test/java/io/debezium/server/pulsar/PulsarIT.java
debezium-server/debezium-server-redis/src/test/java/io/debezium/server/redis/RedisOffsetIT.java
debezium-server/debezium-server-redis/src/test/java/io/debezium/server/redis/RedisStreamIT.java

https://issues.redhat.com/browse/DBZ-5074

DBZ-5074 Reduce number of Postgres database connections

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql

Please see https://issues.redhat.com/browse/DBZ-5077 for problem description.

DBZ-5077 Support DROP FOREIGN KEY IF EXISTS grammar

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
documentation/modules/ROOT/pages/connectors/mysql.adoc

https://issues.redhat.com/browse/DBZ-5100

DBZ-5100 Do not default `database.server.id`

---

debezium-parent/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-5112

DBZ-5112: Surefire/Failsafe upgrade

---

documentation/modules/ROOT/pages/connectors/postgresql.adoc

https://issues.redhat.com/browse/DBZ-4734

DBZ-4734 Document PostgreSQL `xmin.fetch.interval.xs`

---

pom.xml

https://issues.redhat.com/browse/DBZ-5107

DBZ-5107 Upgrade Jackson Databind to 2.13.2.2

---

debezium-testing/debezium-testing-system/pom.xml

https://issues.redhat.com/browse/DBZ-5114?orderby=created+DESC%2C+priority+DESC%2C+updated+DESC

DBZ-5114 Upgraded Fixture5 JUnit extension to released version

---

jenkins-jobs/job-dsl/node_snapshot_history_cleanup.groovy
jenkins-jobs/job-dsl/view_list_jenkins.groovy
jenkins-jobs/pipelines/node_snapshot_history_cleanup_pipeline.groovy
jenkins-jobs/scripts/cleanup_images_ansible.yml

https://issues.redhat.com/browse/DBZ-5094

DBZ-5094 Add cleanup job and ansible script

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/LogMinerEventProcessor.java

https://issues.redhat.com/browse/DBZ-4973

DBZ-4973 Clean up Oracle connector code base

---

debezium-server/debezium-server-redis/src/test/java/io/debezium/server/redis/RedisDatabaseHistoryTestProfile.java

https://issues.redhat.com/browse/DBZ-5117

DBZ-5117 Add mandatory database.server.id into Redis test profile

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlBinaryProtocolFieldReader.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/IncrementalSnapshotIT.java
pom.xml

https://issues.redhat.com/browse/DBZ-5118

DBZ-5118 Use Java 8 release with OpenJDK 17

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-5121

DBZ-5121 Support if not exists/if exists key words in alter table statement

---

jenkins-jobs/job-dsl/connector_mysql_matrix_test.groovy

[DBZ-5124](https://issues.redhat.com/browse/DBZ-5124)

DBZ-5124 moved to MySQL 5.7 in CI

---

debezium-core/src/main/java/io/debezium/relational/history/DatabaseHistoryMetrics.java

With the proposed change, the recovery is logged as follows:
```
2022-05-12 23:11:24,901 INFO  Started database history recovery   [io.debezium.relational.history.DatabaseHistoryMetrics]
2022-05-12 23:11:26,924 INFO  Database history recovery in progress, recovered 18323 records   [io.debezium.relational.history.DatabaseHistoryMetrics]
2022-05-12 23:11:27,419 INFO  Already applied 25688 database changes   [io.debezium.relational.history.DatabaseHistoryMetrics]
2022-05-12 23:11:28,925 INFO  Database history recovery in progress, recovered 56325 records   [io.debezium.relational.history.DatabaseHistoryMetrics]
2022-05-12 23:11:29,419 INFO  Already applied 66074 database changes   [io.debezium.relational.history.DatabaseHistoryMetrics]
2022-05-12 23:11:30,925 INFO  Database history recovery …
```

DBZ-5130: Log history recovery progress every two seconds

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateTableParserListener.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDefaultValueTest.java

https://issues.redhat.com/browse/DBZ-5134

DBZ-5134 java.lang.NumberFormatException: For input string: \"0.000000000000000000\"

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/JsonSerialization.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbChangeRecordEmitter.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbChangeSnapshotOplogRecordEmitter.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbCollectionSchema.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbOffsetContext.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoUtil.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetOffsetContext.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java

https://issues.redhat.com/browse/DBZ-5113 
Use BsonDocument for type safety

DBZ-5113 Use bson document

---

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/ConnectorConfiguration.java

https://issues.redhat.com/browse/DBZ-4867
@jcechace can you review and merge if this looks okay to you?
@jpechane should we consider backporting this to 1.9?

DBZ-4867 Do not set `database.dbname` for SQL Server

---

debezium-core/src/main/java/io/debezium/metrics/Metrics.java

https://issues.redhat.com/browse/DBZ-5141

DBZ-5141 Should be sleep with REGISTRATION_RETRY_DELAY when registry MBean failed

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java

https://issues.redhat.com/browse/DBZ-5140

DBZ-5140 Do not log transaction warning when lob-enabled is true

---

debezium-server/debezium-server-dist/src/main/resources/assemblies/server-distribution.xml
pom.xml

https://issues.redhat.com/browse/DBZ-5144

DBZ-5144 Upgrade Kafka to 3.2.0

---

documentation/antora.yml
pom.xml

https://issues.redhat.com/browse/DBZ-4877

DBZ-4877 Upgrade Oracle InstantClient to 21.5.0.0

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-5148

DBZ-5148 Retry starting Oracle LogMiner after ORA-01291

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresDefaultValueConverter.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresDefaultValueConverterIT.java

https://issues.redhat.com/browse/DBZ-5038

DBZ-5038 Support default values for PostgreSQL enum types

---

debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/fixtures/kafka/OcpKafka.java

https://issues.redhat.com/browse/DBZ-5160

DBZ-5160 Setting pull secret after either image or build is configured for KC

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-4958
Associated upstream PR has been created: https://github.com/antlr/grammars-v4/pull/2628

DBZ-4958 Support `CREATE OR REPLACE TABLE` syntax for MySQL

---

debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/ConfigProperties.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/artifacts/OcpArtifactServerController.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/artifacts/OcpArtifactServerDeployer.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/fixtures/kafka/DockerKafka.java
jenkins-jobs/docker/rhel_kafka/Dockerfile
jenkins-jobs/job-dsl/rhel_downstream_prepare.groovy
jenkins-jobs/pipelines/rhel_downstream_prepare_pipeline.groovy
jenkins-jobs/scripts/build-rhel-kafka-image.sh

https://issues.redhat.com/browse/DBZ-5162

DBZ-5162 Downstream issues

---

debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/db2/DockerRhelDb2ConnectorIT.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/oracle/DockerRhelOracleConnectorIT.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/postgresql/DockerRhelPostgreSqlConnectorIT.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/postgresql/OcpAvroPostgreSqlConnectorIT.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/sqlserver/DockerRhelSqlServerConnectorIT.java

https://issues.redhat.com/browse/DBZ-5162

DBZ-5162 Fixed incorrect inheritance in connector system ITs

---

jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy

https://issues.redhat.com/browse/DBZ-5164

DBZ-5164 Updated oracle instnat client in oracle connector pipeline

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
debezium-server/debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java

https://issues.redhat.com/browse/DBZ-5052

DBZ-5052 Don't send tombstones when consumer doesn't support them

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-5146

DBZ-5146 Remove `log.mining.view.fetch.size`, use `query.fetch.size` instead

---

.github/workflows/debezium-workflow.yml

https://issues.redhat.com/browse/DBZ-4947

DBZ-4947 Build Debezium UI upon changes in debezium-core

---

debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java

https://issues.redhat.com/browse/DBZ-5172

DBZ-5172 Expose more useful exception info with building the field default value schema

---

debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/ConfigProperties.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/registry/builders/FabricApicurioBuilder.java

https://issues.redhat.com/browse/DBZ-5162

DBZ-5162 Fixed missing persistence type for ApicurioRegistry resources

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlPartition.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDatabaseSchemaTest.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlPartitionTest.java
debezium-connector-mysql/src/test/java/io/debezium/relational/history/KafkaDatabaseHistoryTest.java
debezium-connector-mysql/src/test/resources/logback-test.xml
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OraclePartition.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OraclePartitionTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/AbstractProcessorUnitTest.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresPartition.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresPartitionTest.java
debezium-connector-postgres/src/test/resources/logback-test.xml
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerPartition.java
debezium-core/src/main/java/io/debezium/relational/AbstractPartition.java

https://issues.redhat.com/browse/DBZ-5042

Move DB name logging support from SQL Server into core

---

jenkins-jobs/scripts/generate-release-notes.groovy

https://issues.redhat.com/browse/DBZ-5191

DBZ-5191 Use correct project id in release notes groovy script

---

debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/artifacts/OcpArtifactServerController.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/ConnectorConfigBuilder.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/resources/ConnectorFactories.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/db2/Db2Tests.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/mongodb/MongoTests.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/mysql/MySqlTests.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/oracle/OracleTests.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/postgresql/PostgreSqlTests.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/sqlserver/SqlServerTests.java

https://issues.redhat.com/browse/DBZ-2581

DBZ-2581 Content based routing tests in system testsuite

---

jenkins-jobs/docker/artifact-server/listing.sh
jenkins-jobs/pipelines/upstream_artifact_server_prepare_pipeline.groovy
jenkins-jobs/pipelines/upstream_kafka_connect_prepare_pipeline.groovy
jenkins-jobs/scripts/upstream-artifact-server-prepare.sh
jenkins-jobs/scripts/upstream-kafka-connect-prepare.sh

https://issues.redhat.com/browse/DBZ-5183

Add groovy libraries preparation to testsuite preparation jobs

---

pom.xml

https://issues.redhat.com/browse/DBZ-4806

DBZ-4806 Upgrade to Quarkus 2.9.2.Final

---

documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc
documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc

https://issues.redhat.com/browse/DBZ-5153

DBZ-5153 Update MBean name references for SQL Server

---

jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy

Fixed issue introduced with previous DBZ-5185 PR

DBZ-5185 fixed invalid dir in Oracle matrix pipeline

---

jenkins-jobs/scripts/build-connect-image.sh
jenkins-jobs/scripts/build-rhel-kafka-image.sh
jenkins-jobs/scripts/copy-images.sh
jenkins-jobs/scripts/copy-plugins.sh
jenkins-jobs/scripts/upstream-artifact-server-prepare.sh
jenkins-jobs/scripts/upstream-kafka-connect-prepare.sh

https://issues.redhat.com/browse/DBZ-5212

DBZ-5212 Add set -e to bash scripts used in our jobs

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerAdapter.java

https://issues.redhat.com/browse/DBZ-5202

DBZ-5202 Add retry/delay to offset transaction id resolution

---

jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy
jenkins-jobs/pipelines/upstream_artifact_server_prepare_pipeline.groovy
jenkins-jobs/pipelines/upstream_kafka_connect_prepare_pipeline.groovy
jenkins-jobs/scripts/upstream-artifact-server-prepare.sh
jenkins-jobs/scripts/upstream-kafka-connect-prepare.sh

https://issues.redhat.com/browse/DBZ-5217

DBZ 5217 add debezium scripting in kafka connect preparation and change grep to mvn:evaluate in jenkins pipelines

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-5211

DBZ-5211 DDL statement couldn't be parsed - Oracle connector 1.9.3.Final

---

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoMetricsIT.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSourceMetrics.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlMetricsIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresMetricsIT.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
debezium-core/src/main/java/io/debezium/pipeline/metrics/ChangeEventSourceMetricsMXBean.java
debezium-core/src/main/java/io/debezium/pipeline/metrics/DefaultSnapshotChangeEventSourceMetrics.java
debezium-core/src/main/java/io/debezium/pipeline/metrics/DefaultStreamingChangeEventSourceMetrics.java
documentation/modules/ROOT/pages/connectors/oracle.adoc
documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc
documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc

https://issues.redhat.com/browse/DBZ-5206

DBZ-5206 Remove the deprecated monitored tables metrics

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java

https://issues.redhat.com/browse/DBZ-5204

DBZ-5204 Do not cache connection details in `TypeRegistry`.

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/DefaultValueParserListener.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-5201

DBZ-5201 Debezium does NOT support unix_timestamp() as DEFAULT value

---

debezium-server/debezium-server-dist/pom.xml

https://issues.redhat.com/browse/DBZ-5224

DBZ-5224 Remove invalid scope

---

jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy
jenkins-jobs/pipelines/system_pipeline.groovy
jenkins-jobs/pipelines/upstream_artifact_server_prepare_pipeline.groovy
jenkins-jobs/pipelines/upstream_kafka_connect_prepare_pipeline.groovy

https://issues.redhat.com/browse/DBZ-5185

DBZ-5185 add oracle version evaluation to testsuite job

---

jenkins-jobs/scripts/build-connect-image.sh
jenkins-jobs/scripts/build-rhel-kafka-image.sh

https://issues.redhat.com/browse/DBZ-5190

DBZ-5190 downstream preparation jobs have wildcard option for libs needed in each plugin directory

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-5226

DBZ-5226 Improve test wait-time performance

---

pom.xml

https://issues.redhat.com/browse/DBZ-5069

DBZ-5069 Use maven 3.8.4 version with enforcer plugin

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerTableIdPredicates.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
debezium-core/src/main/java/io/debezium/relational/TableId.java
debezium-core/src/main/java/io/debezium/relational/TableIdParser.java
debezium-core/src/main/java/io/debezium/relational/TableIdPredicates.java
debezium-core/src/test/java/io/debezium/relational/TableIdParserTest.java

https://issues.redhat.com/browse/DBZ-5198

Add support for table ID delimiter characters

---

README_JA.md
debezium-schema-generator/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-5069

DBZ-5069 Upgarde maven-core & maven-plugin-api to 3.8.4

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotCaseSensitiveIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SignalsIT.java

https://issues.redhat.com/browse/DBZ-5258

DBZ-5258 Fix test assertions using static database names

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java

https://issues.redhat.com/browse/DBZ-5257

DBZ-5257 Source info table order deterministic for rename schema changes

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSourceInfoStructMaker.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java

https://issues.redhat.com/browse/DBZ-5225

DBZ-5225 Align `source.scn` with the event's scn

---

pom.xml

https://issues.redhat.com/browse/DBZ-5259

DBZ-5259 Upgrade to Quarkus 2.10.0.Final

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/IncrementalSnapshotIT.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotCaseSensitiveIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/IncrementalSnapshotIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/IncrementalSnapshotWithRecompileIT.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java

https://issues.redhat.com/browse/DBZ-4834
There will also be a sibling PR in the DB2 connector repository to make adjustments for the integration test changes.

DBZ-4834 Fix incremental snapshot of table added to include list

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresOffsetContext.java

https://issues.redhat.com/browse/DBZ-3942

DBZ-3942 Load correct last commit LSN from offsets

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_drop.sql
debezium-ddl-parser/src/test/resources/mysql/examples/grant.sql

https://issues.redhat.com/browse/DBZ-5271

DBZ-5271 Support set role statement for mysql8

---

COPYRIGHT.txt
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/WalPositionLocator.java

I dedicated to use INFO instead DEBUG, cause this information will be really useful to observe normal flow of debezium.

DBZ-5031 Additional logging when offset flushing is not allowed

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/kill.sql

https://issues.redhat.com/browse/DBZ-5273
Upstream PR: https://github.com/antlr/grammars-v4/pull/2669

DBZ-5273 Support using variables in KILL command

---

debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java

https://issues.redhat.com/browse/DBZ-5272

DBZ-5272 Notify all threads in case of mutliple writers

---

pom.xml

https://issues.redhat.com/browse/DBZ-5287

DBZ-5287 Upgrade MongoDB driver to 4.6.1

---

pom.xml

https://issues.redhat.com/browse/DBZ-5261

DBZ-5261 Upgrade PostgreSQL driver to 42.4.0

---

pom.xml

https://issues.redhat.com/browse/DBZ-5289

DBZ-5289 Upgrade Oracle driver to 21.6.0.0

---

pom.xml

https://issues.redhat.com/browse/DBZ-5288

DBZ-5288 Upgrade MySQL driver to 8.0.29

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java

https://issues.redhat.com/browse/DBZ-5301

DBZ-5301 FIx LogMinerHelperIT to work on Oracle RAC with multiple nodes

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/junit/SkipOnDatabaseOption.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/junit/SkipTestDependingOnDatabaseOptionRule.java

https://issues.redhat.com/browse/DBZ-5303

DBZ-5303 Rework SkipOnDatabaseOption, allow for enabled/disabled toggles

---

.github/workflows/debezium-workflow.yml
.github/workflows/jdk-outreach-workflow.yml
.github/workflows/oracle-workflow-test.yml
README.md
README_JA.md
README_ZH.md
debezium-connector-oracle/README.md
debezium-connector-oracle/pom.xml
jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy
jenkins-jobs/pipelines/release-pipeline.groovy
jenkins-jobs/scripts/release-pipeline.groovy
pom.xml

https://issues.redhat.com/browse/DBZ-5234

DBZ-5234 Build Oracle connector by default without Maven profiles

---

debezium-bom/pom.xml

https://issues.redhat.com/browse/DBZ-5251
@jpechane the follow-up to add the Quarkus artifacts to our BOM.

DBZ-5251 Add debezium-quarkus-outbox to BOM

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RowDeserializers.java

https://issues.redhat.com/browse/DBZ-5267

DBZ-5267 Invalid date 'SEPTEMBER 31'

---

debezium-testing/debezium-testing-system/pom.xml

https://issues.redhat.com/browse/DBZ-5305

DBZ-5305 pass Oracle namespace property to test runtime

---

pom.xml

https://issues.redhat.com/browse/DBZ-5299

DBZ-5299 Allow the maven version is greater than the current 3.8.4

---

COPYRIGHT.txt
documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc

Hi, want to improve documentation in the main branch.

DBZ-5296 Correct documentation of Event Router in expand.json mode

---

debezium-core/src/main/java/io/debezium/relational/RelationalTableFilters.java

https://issues.redhat.com/browse/DBZ-5270
When enabling the `database.history.store.only.captured.tables.ddl`, the logging in RelationalSnapshotChangeEventSource does not take into account this setting when logging, leading to a false impression of what tables will actually be captured in the schema history.

DBZ-5270 Reduce table schema capture logging verbosity

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java

https://issues.redhat.com/browse/DBZ-5285

DBZ-5285 Fix store.only.captured.tables.ddl to work during streaming

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java

https://issues.redhat.com/browse/DBZ-5300

DBZ-5300 Exclude ADT indices as relational primary keys

---

debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java
debezium-core/src/test/java/io/debezium/connector/base/ChangeEventQueueTest.java
debezium-microbenchmark/src/main/java/io/debezium/performance/core/ChangeEventQueuePerf.java

- ReentrantLock based write and read coordination
- Condition based Inter Thread communication for isFull and isNotFull conditions

DBZ-5277 ChangeEventQueue - Support Multiple Writer (doEnqueue) and Reader (poll) Threads

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlHistoryRecordComparator.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDatabaseSchemaTest.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java

See [DBZ-5291](https://issues.redhat.com/browse/DBZ-5291).

DBZ-5291: Fix binlog filename comparison

---

jenkins-jobs/scripts/build-rhel-kafka-image.sh
jenkins-jobs/scripts/upstream-artifact-server-prepare.sh
jenkins-jobs/scripts/upstream-kafka-connect-prepare.sh

https://issues.redhat.com/browse/DBZ-5280

DBZ-5280 change test-infrastructure image names for better clarity

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java

https://issues.redhat.com/browse/DBZ-5240

DBZ-5240 Add partitioned tables into supported table types

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldExcludeListIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldRenamesIT.java

https://issues.redhat.com/browse/DBZ-5328

DBZ-5328 field.exclude.list doesn't accept dashes (-) in database name

---

jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy

https://issues.redhat.com/browse/DBZ-5338

DBZ-5338 Removed invalid whitespaces from oracle test pipeline

---

jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy

https://issues.redhat.com/browse/DBZ-5332

DBZ-5332 Add Oracle 19.3 non-CDB to test matrix

---

debezium-connector-oracle/README.md

https://issues.redhat.com/browse/DBZ-5250

DBZ-5250 Update Oracle README.md, clarifying 11g requirements

---

jenkins-jobs/pipelines/deploy-snapshots.groovy

https://issues.redhat.com/browse/DBZ-4875

DBZ-4875 Deploy javadocs with nightly snapshots

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java

https://issues.redhat.com/browse/DBZ-5373

DBZ-5373 Propagate commit timestamp to transaction metadata

---

debezium-server/debezium-server-dist/src/main/resources/assemblies/server-distribution.xml
pom.xml

https://issues.redhat.com/browse/DBZ-5346

DBZ-5346 Upgrade to Apache Kafka 3.2.0

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresDefaultValueConverter.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresDefaultValueConverterIT.java

https://issues.redhat.com/browse/DBZ-5340

DBZ-5340 Allow schema prefix on default value function calls

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDatabaseSchema.java

https://issues.redhat.com/browse/DBZ-5386

DBZ-5386 Missing "previousId" property with parsing the rename statement in kafka history topic

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/converters/TinyIntOneToBooleanConverter.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTinyIntIT.java
debezium-connector-mysql/src/test/resources/ddl/tinyint_test.sql
documentation/modules/ROOT/pages/connectors/mysql.adoc

https://issues.redhat.com/browse/DBZ-5343

DBZ-5343 Unsigned tinyint conversion fails for MySQL 8.x

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/CommitScn.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java

https://issues.redhat.com/browse/DBZ-5381

DBZ-5381 Add a pretty loggable format for commit_scn

---

COPYRIGHT.txt
README.md
README_JA.md
README_KO.md
README_ZH.md

Translate the README document into Korean.

[docs] Translate the README document into Korean

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/FieldSelector.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldExcludeListIT.java

https://issues.redhat.com/browse/DBZ-4846

DBZ-4846 MongoConnector's field exclusion configuration does not work with fields with the same name but from different collections

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java

https://issues.redhat.com/browse/DBZ-5295

DBZ-5295 Exclude test for wal2json

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresDefaultValueConverter.java

https://issues.redhat.com/browse/DBZ-5403

DBZ-5403 Convert timestamps with tz default values to GMT

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
debezium-core/src/test/java/io/debezium/kafka/KafkaServer.java
jenkins-jobs/job-dsl/kafka_2_x_test.groovy

https://issues.redhat.com/browse/DBZ-5404

DBZ-5404 Restore build compatibility with Kafka 2.x and 3.0.x

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDdlParserTest.java
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-5390

DBZ-5390 Reorder relational_property definition to give priority to out_of_line_constraint

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-5399

DBZ-5399 Clarify database name usage in signal.data.collection for Oracle

---

jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy

https://issues.redhat.com/browse/DBZ-5411

DBZ-5411 Fix Oracle non-cdb builds to use correct env variables

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTopicNamingStrategyTest.java
debezium-core/src/main/java/io/debezium/schema/AbstractTopicNamingStrategy.java

https://issues.redhat.com/browse/DBZ-5414

DBZ-5414 Validate topic naming strategy relative topic name properties

---

debezium-core/src/main/java/io/debezium/schema/AbstractTopicNamingStrategy.java
debezium-core/src/main/java/io/debezium/schema/DefaultRegexTopicNamingStrategy.java
debezium-core/src/main/java/io/debezium/schema/DefaultTopicNamingStrategy.java
debezium-core/src/main/java/io/debezium/schema/SchemaTopicNamingStrategy.java
documentation/modules/ROOT/pages/connectors/cassandra.adoc
documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/mongodb.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/oracle.adoc
documentation/modules/ROOT/pages/connectors/postgresql.adoc
documentation/modules/ROOT/pages/connectors/sqlserver.adoc
documentation/modules/ROOT/pages/connectors/vitess.adoc

https://issues.redhat.com/browse/DBZ-5413

DBZ-5413 Update the topic naming strategy doc to all connectors

---

documentation/modules/ROOT/pages/connectors/sqlserver.adoc

[DBZ-4312](https://issues.redhat.com/browse/DBZ-4312)
Per comment in Jira, this statement can be removed.
Please backport this change to 1.9.

DBZ-4312 Remove disclaimer re: connector not being tested against Azure

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateTableParserListener.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateUniqueIndexParserListener.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java

https://issues.redhat.com/browse/DBZ-5424

DBZ-5424 Verify the unique index whether including function or arbitrary expression

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-5428

DBZ-5248 Avoid NumberFormatException in OracleConnectorIT tests

---

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/EventProcessingFailureHandlingIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java

https://issues.redhat.com/browse/DBZ-4004

DBZ-4004 Fix SQL Server test EventProcessingFailureHandlingIT

---

debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java

https://issues.redhat.com/browse/DBZ-5433

DBZ-5433 stop OffsetStore if it fails to fully start

---

COPYRIGHT.txt
debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaDatabaseHistory.java
documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc

https://issues.redhat.com/browse/DBZ-5249
KafkaDatabaseHistory without check database history topic create result caused UnknowTopicOrPartitionException

DBZ-5249 KafkaDatabaseHistory without check database history topic create result caused UnknowTopicOrPartitionException

---

pom.xml

https://issues.redhat.com/browse/DBZ-5427

DBZ-5427 Upgrade to Quarkus 2.11.0.Final

---

COPYRIGHT.txt
documentation/modules/ROOT/pages/connectors/sqlserver.adoc
jenkins-jobs/scripts/config/Aliases.txt

Link https://issues.redhat.com/browse/DBZ-5440 .

DBZ-5440 Fix typo in sqlserver document.

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-5371

DBZ-5371 Use initial snapshot position if "$natural:-1" is not supported

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java

https://issues.redhat.com/browse/DBZ-5292

DBZ-5292 Treat SQLServerException with "Broken pipe (Write failed)" exception message as a retriable exception

---

pom.xml

https://issues.redhat.com/browse/DBZ-5445

DBZ-5445 Upgrade formatter-maven-plugin to 2.20.0

---

pom.xml

https://issues.redhat.com/browse/DBZ-5446

DBZ-5446 Upgrade impsort-maven-plugin to 1.7.0

---

documentation/modules/ROOT/pages/connectors/postgresql.adoc

Link https://issues.redhat.com/browse/DBZ-5450 .

DBZ-5450 Typo in postgresql document.

---

documentation/modules/ROOT/pages/integrations/testcontainers.adoc

[docs] Avoiding reference to Guava types

---

debezium-server/debezium-server-http/src/main/java/io/debezium/server/http/HttpChangeConsumer.java
debezium-server/debezium-server-http/src/test/java/io/debezium/server/http/HttpIT.java
debezium-server/debezium-server-http/src/test/java/io/debezium/server/http/HttpTestResourceLifecycleManager.java
documentation/modules/ROOT/pages/operations/debezium-server.adoc

https://issues.redhat.com/browse/DBZ-5307

Retry failed events when sending them to HTTP sink

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/CreateTableParserListener.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java

https://issues.redhat.com/browse/DBZ-5441

DBZ-5441 Gracefully skip Oracle non-relational tables

---

jenkins-jobs/job-dsl/node_snapshot_build.groovy

https://issues.redhat.com/browse/DBZ-5466

DBZ-5466 Change default base image of node snapshot preparation job

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/MongoDataConverter.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTestIT.java

https://issues.redhat.com/browse/DBZ-5434

DBZ-5434 Translation from mongodb document to kafka connect schema fails when nested arrays contain no elements

---

debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/OpenShiftUtils.java
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/StrimziOperatorController.java

https://issues.redhat.com/browse/DBZ-5465

DBZ-5465 Ability to detect AMQ Streams operator installed via OLM

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/KafkaSignalThread.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/StopSnapshotKafkaSignal.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java
documentation/modules/ROOT/pages/connectors/mysql.adoc

https://issues.redhat.com/browse/DBZ-5453

DBZ-5453 Add `stop-snapshot` MySQL read-only Kafka signal

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java

https://issues.redhat.com/browse/DBZ-5478

DBZ-5478: Restart SQL Server task on "Socket closed" exception

---

debezium-core/src/main/java/io/debezium/transforms/outbox/SchemaBuilderUtil.java
debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
debezium-core/src/test/java/io/debezium/transforms/outbox/SchemaBuilderUtilTest.java

https://issues.redhat.com/browse/DBZ-5475

Ensure Outbox JSON NUMBER arrays are of the same type

---

debezium-server/debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java

https://issues.redhat.com/browse/DBZ-5116
Example output after the failure:
$ ./run.sh
Failed to load mandatory config value 'debezium.sink.type'. Please check you have correct Debezium server config in /home/vjuranek/tmp/debezium-server/conf/application.properties or required properties are defined via system or environment variables.
{"timestamp":"2022-08-08T13:37:35.848+02:00","sequence":155,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.runtime.Application","level":"ERROR","message":"Failed to start application (with profile prod)","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"fedora","processName":"io.debezium.server.Main","processId":1048188,"exception":{"refId":1,"exceptionType":"java.util.NoSuchElementException","message":"SRCFG00014: The …

DBZ-5116 Provide more clear message when cannot load config

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java

https://issues.redhat.com/browse/DBZ-5483

DBZ-5483 Fix testStopSnapshotKafkaSignal random failure

---

pom.xml

https://issues.redhat.com/browse/DBZ-5493

DBZ-5493 Upgrade PostgreSQL driver to 42.4.1

---

documentation/antora.yml
pom.xml

https://issues.redhat.com/browse/DBZ-5463
Sibling PR: https://github.com/debezium/container-images/pull/300

DBZ-5463 Upgrade Kafka to 3.2.1

---

.github/workflows/debezium-workflow.yml

https://issues.redhat.com/browse/DBZ-5501

DBZ-5501 Force snapshot updates when building UI

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-5508
Refer to https://dev.mysql.com/doc/refman/8.0/en/create-table.html

DBZ-5508 DDL statement couldn't be parsed : mismatched input 'ENGINE'

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
debezium-server/debezium-server-core/src/main/java/io/debezium/server/DebeziumMetrics.java
debezium-server/debezium-server-core/src/test/java/io/debezium/server/DebeziumServerIT.java

Backport DBZ-5240 and DBZ-5235 to 1.9.x

1.9 Backport DBZ-5240 and DBZ-5235

---

debezium-core/src/main/java/io/debezium/relational/history/ConnectTableChangeSerializer.java
debezium-core/src/test/java/io/debezium/relational/history/HistoryRecordTest.java

https://issues.redhat.com/browse/DBZ-5511

DBZ-5511 Keep consistence with method serialize of Connect/Json Table Change Serializer

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotContext.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/ExecuteSnapshotKafkaSignal.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/KafkaSignalThread.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
debezium-core/src/main/java/io/debezium/pipeline/signal/AbstractSnapshotSignal.java
debezium-core/src/main/java/io/debezium/pipeline/signal/ExecuteSnapshot.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/DataCollection.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/IncrementalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/IncrementalSnapshotContext.java
debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedSnapshotChangeEventSourceTest.java
debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/partials/modules/all-connectors/con-connector-ad-hoc-snapshots.adoc
documentation/modules/ROOT/partials/modules/all-connectors/con-connector-incremental-snapshot.adoc

https://issues.redhat.com/browse/DBZ-5327

DBZ-5327 Smart Backfills

---

COPYRIGHT.txt
README_ZH.md
jenkins-jobs/scripts/config/Aliases.txt

[docs]Correct the jdk version in CN readme file

[docs]correct cn readme jdk version

---

debezium-server/debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java
debezium-server/debezium-server-redis/src/main/java/io/debezium/server/redis/RedisOffsetBackingStore.java
debezium-server/debezium-server-redis/src/test/java/io/debezium/server/redis/RedisOffsetTestProfile.java

DBZ-5513 Simplify passing of SINK config properties to OffsetBackingStore

DBZ-5513 Simplify passing of SINK config properties to OffsetBackingStore

---

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/EventProcessingFailureHandlingIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java

https://issues.redhat.com/browse/DBZ-5525

DBZ-5525 DBZ-5527 Fix SQL Server test failures

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchema.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorTaskIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java

See [DBZ-5470](https://issues.redhat.com/browse/DBZ-5470).

DBZ-5470: Remove the dependency of JdbcConnection on DatabaseSchema

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java

https://issues.redhat.com/browse/DBZ-5521

DBZ-5521 Fix concatenation operator handling in LogMiner DML parser

---

debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedSnapshotChangeEventSourceTest.java

https://issues.redhat.com/browse/DBZ-5533

DBZ-5533 Unit test fails on Windows

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotCaseSensitiveIT.java
debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java

https://issues.redhat.com/browse/DBZ-5327

DBZ-5327 Fix Oracle/Db2 test failures

---

debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/resources/ConnectorFactories.java

https://issues.redhat.com/browse/DBZ-5539

DBZ-5539 Added server.id to MySQL connector config in system testsuite

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
debezium-core/src/main/java/io/debezium/data/VariableScaleDecimal.java
debezium-core/src/main/java/io/debezium/util/Metronome.java

https://issues.redhat.com/browse/DBZ-5535

DBZ-5535 Disable preferring DDL before logical schema in history recovery

---

.github/workflows/debezium-workflow.yml

https://issues.redhat.com/browse/DBZ-5528

DBZ-5528 Restrict connector workflows based on individual grammar changes in DDL module

---

debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java

https://issues.redhat.com/browse/DBZ-5484

DBZ-5484 Better error reporting in SKIP/WARN cases

---

COPYRIGHT.txt
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDatabaseSchemaTest.java
debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
jenkins-jobs/scripts/config/Aliases.txt

see https://issues.redhat.com/browse/DBZ-5489

DBZ-5489 add column comment to schema 

---

debezium-testing/debezium-testing-system/pom.xml
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/ConfigProperties.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/resources/ConnectorFactories.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/sqlserver/SqlServerTests.java

https://issues.redhat.com/browse/DBZ-5554

DBZ-5554 Updated SqlServer configuration used in system testsuite t reflect multi task changes

---

debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/connectors/CustomResourceConnectorDeployer.java
debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/assertions/KafkaAssertions.java

https://issues.redhat.com/browse/DBZ-5563

DBZ-5563  Logging improvements in TestSuite

---

debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedSnapshotChangeEventSourceTest.java
pom.xml

https://issues.redhat.com/browse/DBZ-5568
@vjuranek Could you please review and merge this one? Thanks

DBZ-5568 Use only Java 11 for tests

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java

https://issues.redhat.com/browse/DBZ-5569

DBZ-5569 Oracle connector's max.queue.size.in.bytes is invalid

---

documentation/modules/ROOT/pages/configuration/topic-auto-create-config.adoc

This fixes the language type for the source code listings in this page.
I did a search for the full documentation project, and I didn't find any other.

DBZ-5573 fix source positional attributes

---

pom.xml

https://issues.redhat.com/browse/DBZ-5574

DBZ-5574 Upgrade mysql-binlog-connector-java library version

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTopicNamingStrategyTest.java
debezium-core/src/main/java/io/debezium/config/Field.java
debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java

https://issues.redhat.com/browse/DBZ-5538

DBZ-5538 Unclear validation error when required field is missing

---

debezium-api/src/main/java/io/debezium/spi/topic/TopicNamingStrategy.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTopicNamingStrategyIT.java
debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
debezium-core/src/main/java/io/debezium/schema/AbstractRegexTopicNamingStrategy.java
debezium-core/src/main/java/io/debezium/schema/SchemaRegexTopicNamingStrategy.java

https://issues.redhat.com/browse/DBZ-5480

DBZ-5480 Augment a uniqueness key filed/value in regex topic naming strategy

---

debezium-core/src/main/java/io/debezium/config/Field.java

https://issues.redhat.com/browse/DBZ-5588

DBZ-5588 Field validation errors are misleading for positive, non-zero expectations

---

COPYRIGHT.txt
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/DefaultValueParserListener.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java

https://issues.redhat.com/browse/DBZ-5587
This PR add a test to reproduce an error when using COLLATE.

DBZ-5587 add alter add column test with COLLATE

---

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumContainer.java
debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java
debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/DebeziumContainerTest.java

https://issues.redhat.com/browse/DBZ-5601

DBZ-5601 Switch Debezium test containers to nightly

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-core/src/main/java/io/debezium/relational/TableEditorImpl.java

https://issues.redhat.com/browse/DBZ-5589

DBZ-5589 Mysql connector can't handle the case sensitive of rename/change column statement

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java

https://issues.redhat.com/browse/DBZ-5043

DBZ-5043 Make topic prefix field manadatory and with proper group

---

.github/workflows/debezium-workflow.yml

https://issues.redhat.com/browse/DBZ-5606

DBZ-5606 Include storage modules into the build for DB2 workflow

---

debezium-core/src/test/java/io/debezium/util/ContainerImageVersions.java

https://issues.redhat.com/browse/DBZ-5603

DBZ-5603 Move test containers to quay.io

---

pom.xml

https://issues.redhat.com/browse/DBZ-5620

DBZ-5620 Upgrade mysql-binlog-connector-java library version

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-5622

DBZ-5622 Support READ ONLY/ENCRYPTION options for alter database statment

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/ParserUtils.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/SelectLobParser.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java

https://issues.redhat.com/browse/DBZ-5581

DBZ-5581 Apply unavailable value placeholder on when parsing SELECT_LOB_LOCATOR event types

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-5591
[zulip thread](https://debezium.zulipchat.com/#narrow/stream/302529-users/topic/source.2Ets_ms)

DBZ-5591 Snapshot process setting source.ts_ms

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateTableParserListener.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/TableCommonParserListener.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4

https://issues.redhat.com/browse/DBZ-5623

DBZ-5623 DDL Parsing Error

---

documentation/modules/ROOT/pages/transformations/content-based-routing.adoc
documentation/modules/ROOT/pages/transformations/event-flattening.adoc
documentation/modules/ROOT/pages/transformations/filtering.adoc
documentation/modules/ROOT/pages/transformations/mongodb-event-flattening.adoc
documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc
documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc
documentation/modules/ROOT/pages/transformations/topic-routing.adoc

[DBZ-4417](https://issues.redhat.com/browse/DBZ-4417)
Adds paragraph to emphasize that the basic configuration generally requires customizaiton through the use of  SMT predicates.

SDBZ-4417 Add information about customizing basic SMT configuration

---

debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-5639

DBZ-5639 Logging enhancement for non-incremental snapshot in postgres connector

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java

https://issues.redhat.com/browse/DBZ-5635

DBZ-5635 Reduce undo trx log verbosity when LOB enabled

---

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDefaultValueTest.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTopicNamingStrategyTest.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectionIT.java
debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
debezium-core/src/main/java/io/debezium/schema/AbstractTopicNamingStrategy.java
debezium-core/src/main/java/io/debezium/schema/DefaultTopicNamingStrategy.java
debezium-core/src/main/java/io/debezium/schema/SchemaTopicNamingStrategy.java
debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java

https://issues.redhat.com/browse/DBZ-5594

DBZ-5594 Clean up "logical name" config

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/WalPositionLocator.java

https://issues.redhat.com/browse/DBZ-5597

DBZ-5597 Record LSNs seen the location phase

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java

https://issues.redhat.com/browse/DBZ-5645

DBZ-5645 Skip rollback trx cache when LOB is disabled

---

COPYRIGHT.txt
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/kill.sql
jenkins-jobs/scripts/config/Aliases.txt

https://issues.redhat.com/browse/DBZ-5636
Upstream pr:
https://github.com/antlr/grammars-v4/pull/2836

DBZ-5636 support for using any expression in kill statements

---

.github/workflows/debezium-workflow.yml

https://issues.redhat.com/browse/DBZ-5660
@ani-sha can you take a look and see if this solves our UI test visibility concerns?

DBZ-5660 Run UI tests when dependenceis have changed

---

debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterDelegate.java
debezium-core/src/main/java/io/debezium/transforms/outbox/SchemaBuilderUtil.java
debezium-core/src/test/java/io/debezium/transforms/outbox/SchemaBuilderUtilTest.java
debezium-core/src/test/resources/json/restaurants5.json

https://issues.redhat.com/browse/DBZ-5654

DBZ-5654 Outbox pattern nested payload leads to connector crash

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
debezium-core/src/test/java/io/debezium/junit/relational/TestRelationalDatabaseConfig.java
debezium-core/src/test/java/io/debezium/pipeline/ErrorHandlerTest.java
debezium-core/src/test/java/io/debezium/pipeline/signal/SignalTest.java
debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedSnapshotChangeEventSourceTest.java
debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java
debezium-core/src/test/java/io/debezium/relational/mapping/ColumnMappersTest.java

https://issues.redhat.com/browse/DBZ-5671

DBZ-5671 Remove logic name parameter from sub connector config

---

documentation/antora.yml
pom.xml

https://issues.redhat.com/browse/DBZ-5600

DBZ-5600 Upgrade to Kafka 3.3.1

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java

https://issues.redhat.com/browse/DBZ-5670

DBZ-5670 Use new driver prefix

---

.github/workflows/debezium-workflow.yml
COPYRIGHT.txt
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbCollectionSchema.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSchema.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/converters/MongoDbRecordParser.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/AbstractMongoConnectorIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/AbstractMongoIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorWithConnectionStringIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/PreImageIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TestHelper.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/junit/MongoDbDatabaseVersionResolver.java
jenkins-jobs/scripts/config/Aliases.txt
pom.xml

https://issues.redhat.com/browse/DBZ-5628

DBZ-5628 Added support for Mongo pre-image in change stream

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-5708

DBZ-5708 MySqlConnector parse create view statement failed

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc

doc for: https://github.com/debezium/debezium/pull/3894
cc: @jpechane

DBZ-5628 Add documentation for pre-image support

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-5679

DBZ-5679 Function DATE_ADD can be used as an identifier

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/RenameTableParserListener.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-5710

DBZ-5710 Remove whitelist/blacklist from log messages

---

debezium-server/debezium-server-bom/pom.xml

https://issues.redhat.com/browse/DBZ-5711

DBZ-5711 Prevent Quarkus from overriding driver version

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlSchemaMigrationIT.java

https://issues.redhat.com/browse/DBZ-5728

DBZ-5728 MySqlSchemaMigrationIT runs failed

---

jenkins-jobs/job-dsl/deploy_docker_images.groovy
jenkins-jobs/job-dsl/release_upstream.groovy
jenkins-jobs/pipelines/build-debezium-images.groovy
jenkins-jobs/pipelines/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-5213
related to https://github.com/debezium/container-images/pull/302

DBZ-5213 Support for multiarch image build

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
debezium-core/src/main/java/io/debezium/function/Predicates.java
debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
debezium-core/src/main/java/io/debezium/relational/history/AbstractSchemaHistory.java
debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java

https://issues.redhat.com/browse/DBZ-5709

DBZ-5709 The DDL_FILTER of SchemaHistory doesn't work for including break lines ddl statement

---

jenkins-jobs/job-dsl/deploy_docker_images.groovy

DBZ-5213 Adding option to skip UI when building container images

---

jenkins-jobs/job-dsl/ocp_cluster_deployment.groovy
jenkins-jobs/pipelines/cluster_deployment.groovy

https://issues.redhat.com/browse/DBZ-3129

DBZ-3129 Add OCP cluster on AWS provisioning job

---

debezium-server/debezium-server-bom/pom.xml

https://issues.redhat.com/browse/DBZ-5737

DBZ-5737 Upgrade Pulsar to 2.10.1

---

.github/workflows/debezium-workflow.yml
debezium-connector-postgres/pom.xml
jenkins-jobs/job-dsl/connector_postgresql_matrix_test.groovy

https://issues.redhat.com/browse/DBZ-5370
https://github.com/debezium/container-images/pull/307 must be merged and images published before the PR can pass

DBZ-5370 Support for PostgreSQL 15

---

documentation/modules/ROOT/pages/postgres-plugins.adoc

Fixed link typo Updated postgresql link from 14 to current (15)

[docs] Update postgres-plugins.adoc

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-5682

DBZ-5682 Allow unique index NULL values in trx reconciliation

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
documentation/modules/ROOT/pages/connectors/mongodb.adoc

https://issues.redhat.com/browse/DBZ-5736

DBZ-5736 Expose heartbeatFrequency to Mongo connector config

---

debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedSnapshotChangeEventSourceTest.java

https://issues.redhat.com/browse/DBZ-5727

DBZ-5727 Columns are not excluded when doing incremental snapshots

---

COPYRIGHT.txt
jenkins-jobs/scripts/config/Aliases.txt
pom.xml

Update protobuf to address  CVE-2022-3171

DBZ-5747 Update pom.xml to address CVE-2022-3171

---

debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/databases/AbstractOcpDatabaseController.java

https://issues.redhat.com/browse/DBZ-5753

DBZ-5753 ingres connection on Azure

---

debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/fixtures/databases/docker/DockerSqlServer.java

https://issues.redhat.com/browse/DBZ-5764

DBZ-5764 Using correct jdbc driver class with docker fixture in testsuite

---

debezium-core/src/main/java/io/debezium/config/Configuration.java

https://issues.redhat.com/browse/DBZ-5615

DBZ-5615 Mask additional credentials during log events

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/KafkaSignalThread.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
debezium-core/src/main/java/io/debezium/util/Loggings.java
debezium-core/src/main/java/io/debezium/util/Throwables.java
debezium-storage/debezium-storage-file/src/main/java/io/debezium/storage/file/history/FileSchemaHistory.java
debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java
debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/history/RedisSchemaHistory.java

https://issues.redhat.com/browse/DBZ-5760

DBZ-5760 Only log full row data at TRACE level

---

jenkins-jobs/docker/artifact-server/listing.sh
jenkins-jobs/scripts/build-rhel-kafka-image.sh
jenkins-jobs/scripts/copy-plugins.sh

https://issues.redhat.com/browse/DBZ-5767

DBZ-5767 Reflecting downstream name changes

---

pom.xml

https://issues.redhat.com/browse/DBZ-5780

DBZ-5780 Upgrade postgres driver to version 42.5.0

---

debezium-bom/pom.xml

https://issues.redhat.com/browse/DBZ-5766

DBZ-5766 Upgraded jsonpath to version 2.7.0

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-5756

DBZ-5756 Exclude Oracle Compression Advisor tables from capture

---

pom.xml

https://issues.redhat.com/browse/DBZ-5786

DBZ-5786 Upgrade to Quarkus 2.14.0.Final

---

COPYRIGHT.txt
documentation/modules/ROOT/pages/operations/debezium-server.adoc
jenkins-jobs/scripts/config/Aliases.txt

DBZ-5788 Doc typo

---

COPYRIGHT.txt
documentation/modules/ROOT/pages/connectors/postgresql.adoc
jenkins-jobs/scripts/config/Aliases.txt

Replaces https://github.com/debezium/debezium/pull/4019

[docs] Postgresql connector documentation: add a missing word

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-5626

Add snapshot mode ALWAYS into Oracle connector

---

debezium-api/src/main/java/io/debezium/spi/topic/TopicNamingStrategy.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTopicNamingStrategyTest.java

https://issues.redhat.com/browse/DBZ-5790

DBZ-5790 Enhance the ability to sanitize topic name

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java

https://issues.redhat.com/browse/DBZ-5783

DBZ-5783 Suppress logging of undetermined optionality for explicitly excluded columns

---

COPYRIGHT.txt
documentation/modules/ROOT/pages/connectors/oracle.adoc

[docs] Providing instructs for oracle aws rds cdc. Many of the commands provided are disabled for the rds version.

[docs] oracle cdc for aws rds

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
debezium-core/src/main/java/io/debezium/config/Configuration.java
debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java

https://issues.redhat.com/browse/DBZ-5801

DBZ-5801 The merge method of configuration is not work

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

Nested tables are currently not supported.
https://issues.redhat.com/browse/DBZ-5738

DBZ-5738 Skip nested tables and their parent tables

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java

https://issues.redhat.com/browse/DBZ-5773

DBZ-5773 Correctly discard LOB_ERASE events

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java

https://issues.redhat.com/browse/DBZ-5791

DBZ-5791 Make ORA-01089 retriable based on its message

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java

https://issues.redhat.com/browse/DBZ-5648

DBZ-5648 Move LogMiner RegEx handling into Java

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-5816
As we had discussed regarding the internal FAQ document, I added those to this FAQ section and merged the previous "When things go wrong" section into the FAQ as well.  I'm not sure whether the formatting is acceptable for everyone, but it's a start.

DBZ-5816 Introduce FAQ section; document ORA-01555

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java

https://issues.redhat.com/browse/DBZ-5759
I've started a discussion on the Jira issue about any other logging that might be useful.  I've added the two bits that I know of that I wanted to have added here, but I wanted some clarification on the others mentioned in the Jira before we merge.

DBZ-5759 Improve data logged by the Oracle connector

---

COPYRIGHT.txt
debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/DebeziumTracerEventDispatcher.java
jenkins-jobs/scripts/config/Aliases.txt

https://issues.redhat.com/browse/DBZ-5821

DBZ-5821 Quarkus outbox extention never finish open tracing span

---

documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc

I introduced an error on the documentation by not closing a NOTE block. Fixing it.

DBZ-5770 Update documentation regarding the Binary Data Converter

---

jenkins-jobs/job-dsl/connector_db2_matrix_test.groovy
jenkins-jobs/job-dsl/connector_mongodb_matrix_test.groovy
jenkins-jobs/job-dsl/connector_mysql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_oracle_matrix.groovy
jenkins-jobs/job-dsl/connector_postgresql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_sql_server_matrix_test.groovy

https://issues.redhat.com/browse/DBZ-2131

DBZ-2131 Run tests against Apicurio registy on internal CI

---

jenkins-jobs/docker/debezium-testing-system/Dockerfile
jenkins-jobs/docker/debezium-testing-system/deployment-template.sh
jenkins-jobs/docker/debezium-testing-system/testsuite.sh
jenkins-jobs/job-dsl/ocp_system_test.groovy
jenkins-jobs/pipelines/ocp_system_pipeline.groovy

Changed OCP testsuite job to pod. 
Added readiness probe to the pod description to indicate testsuite is finished. 
Modified the testsuite script to save logs and trigger the readiness probe once finished. 
Modified the OCP testsuite jenkins job to wait for the readiness probe and copy the testsuite logs.

DBZ-5785 Modify ocp system tests to archive test results and logs

---

jenkins-jobs/job-dsl/ocp_cluster_deployment.groovy
jenkins-jobs/pipelines/cluster_deployment_pipeline.groovy

https://issues.redhat.com/browse/DBZ-5844

DBZ-5844 Add Kubernetes plugin for cluster deployment

---

documentation/modules/ROOT/pages/configuration/avro.adoc
documentation/modules/ROOT/pages/configuration/topic-auto-create-config.adoc
documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/mongodb.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/postgresql.adoc
documentation/modules/ROOT/pages/connectors/sqlserver.adoc
documentation/modules/ROOT/pages/connectors/vitess.adoc
documentation/modules/ROOT/pages/operations/debezium-ui.adoc

https://issues.redhat.com/browse/DBZ-5762

DBZ-5762 Update Confluent Avro usage documentation

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc

https://issues.redhat.com/browse/DBZ-5817

DBZ-5817 removing mongodb.name references from docs

---

jenkins-jobs/job-dsl/ocp_aro_deployment.groovy
jenkins-jobs/job-dsl/ocp_aro_teardown.groovy
jenkins-jobs/pipelines/aro_deployment_pipeline.groovy
jenkins-jobs/pipelines/aro_teardown_pipeline.groovy

https://issues.redhat.com/browse/DBZ-5742

DBZ-5742 Add ARO provision and teardown jobs

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java

https://issues.redhat.com/browse/DBZ-5850

DBZ-5850 Fix test OracleConnectorIT shouldIgnoreAllTablesInExcludedSchemas

---

debezium-assembly-descriptors/src/main/resources/assemblies/rest-distribution.xml
debezium-connect-rest-extension/pom.xml
debezium-connect-rest-extension/src/main/java/io/debezium/kcrestextension/Module.java

https://issues.redhat.com/browse/DBZ-4303
Related to: https://github.com/debezium/container-images/pull/308
Should be merged before: https://github.com/debezium/debezium/pull/4015

DBZ-4303 Added assembly profile to debezium-connect-rest-extension

---

COPYRIGHT.txt
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/GtidSet.java

if statement never will be true

Remove Unreachable if statement

---

.github/workflows/debezium-workflow.yml
.github/workflows/doc-changes-workflow.yml
.github/workflows/jdk-outreach-workflow.yml
.github/workflows/missing-commits-by-issue-key.yml
.github/workflows/oracle-workflow-test.yml
.github/workflows/release-contributors-list.yml

https://issues.redhat.com/browse/DBZ-5870

Upgrade all usages of actions/checkout to v3

---

jenkins-jobs/pipelines/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-4303
Depends on: 
https://github.com/debezium/container-images/pull/308
https://github.com/debezium/debezium/pull/4060

DBZ-4303 Replace md5 sum of connect extension in Dockerfile during release

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-5877

DBZ-5877 Fix typo in Oracle documentation

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java

Prevent unnecessary list creation.

Prevent unnecessary list creation

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlChangeRecordEmitter.java

Remove Unnecessary null checks

Remove Unnecessary null checks

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java

Simplify to flow. 
- Remove nested if check
- Postpone possible unused stamement which is connection.isBinlogRowImageFull()

Remove nested if check

---

debezium-server/debezium-server-nats-jetstream/pom.xml
debezium-server/debezium-server-nats-jetstream/src/test/java/io/debezium/server/nats/jetstream/NatsJetStreamIT.java

https://issues.redhat.com/browse/DBZ-5901

DBZ-5901 Migrate debezium-server-nats-jetstream to AssertJ

---

COPYRIGHT.txt
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
documentation/modules/ROOT/pages/connectors/postgresql.adoc
jenkins-jobs/scripts/config/Aliases.txt

Issue : https://issues.redhat.com/browse/DBZ-5811

DBZ-5811 Implement support for skipping LSN commit on postgres source based on config

---

jenkins-jobs/docker/artifact-server/Dockerfile
jenkins-jobs/docker/artifact-server/listing.sh

https://issues.redhat.com/browse/DBZ-5890

DBZ-5890 Fix artefact server container

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnector.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetDiscovery.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorWithConnectionStringIT.java
debezium-core/src/main/java/io/debezium/util/Strings.java

https://issues.redhat.com/browse/DBZ-5893

DBZ-5893 Masking credentials in connection string when logging

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/TableCommonParserListener.java
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/dml_insert.sql

https://issues.redhat.com/browse/DBZ-5904
Upstream pr:
https://github.com/antlr/grammars-v4/pull/2945

DBZ-5904 Suppport INSERT INTO statements with dots in column names

---

debezium-connector-mongodb/pom.xml
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDecimalIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
debezium-connector-oracle/pom.xml
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotCaseSensitiveIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDefaultValueIT.java
debezium-connector-postgres/pom.xml
debezium-connector-sqlserver/pom.xml
debezium-core/src/test/java/io/debezium/data/VerifyRecord.java
jenkins-jobs/job-dsl/connector_db2_matrix_test.groovy
jenkins-jobs/job-dsl/connector_mongodb_matrix_test.groovy
jenkins-jobs/job-dsl/connector_mysql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_oracle_matrix.groovy
jenkins-jobs/job-dsl/connector_postgresql_matrix_test.groovy
jenkins-jobs/job-dsl/connector_sql_server_matrix_test.groovy

https://issues.redhat.com/browse/DBZ-5838

DBZ-5838 Run test against Apicurio registry

---

documentation/modules/ROOT/pages/install.adoc

https://issues.redhat.com/browse/DBZ-5928

DBZ-5928 Fix required Java version in Install docs

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorTaskIT.java

https://issues.redhat.com/browse/DBZ-5931

DBZ-5931 Clean up useless methods

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/UnchangedToastedReplicationMessageColumn.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java

- DBZ-4941 Handle Toasted array columns
- DBZ-4941 Create a separate table for test
- DBZ-4941 add a comment

DBZ-4941 Toasted string array

---

debezium-server/debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java
debezium-server/debezium-server-core/src/test/java/io/debezium/server/DebeziumServerTest.java
debezium-server/debezium-server-core/src/test/java/io/debezium/server/TestConfigSource.java

Add predicate configuration support

DBZ-5940 Support predicate parameters in Debezium Server

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/converters/NumberToZeroScaleConverter.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleNumberNegativeScaleIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/junit/SkipTestWhenRunWithApicurioRule.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/junit/SkipWhenRunWithApicurio.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-5880

Implement converte to zero scale decimals

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/UnchangedToastedReplicationMessageColumn.java

Similar to https://github.com/debezium/debezium/pull/4136 but handles `character varying[]` type

DBZ-5944 Toasted varchar array is not correctly processed

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/FieldSelector.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldExcludeListIT.java

https://issues.redhat.com/browse/DBZ-4846

Backport DBZ-4846 to 1.9

---

CHANGELOG.md
COPYRIGHT.txt
documentation/antora.yml
jenkins-jobs/job-dsl/release_upstream.groovy
jenkins-jobs/pipelines/release-pipeline.groovy
jenkins-jobs/scripts/config/Aliases.txt

- [release] Update jobs
- [release] Add contributors
- [release] Changelog for 2.1.0.Beta1

[release] Changelog for 2.1.0.Beta1

---

debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java

https://issues.redhat.com/browse/DBZ-5946

DBZ-5946 Print the correct data class name in JdbcValueConverters.handleUnknownData

---

debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java

https://issues.redhat.com/browse/DBZ-5344

DBZ-5344 Add complex json array test case to EventRouterTest

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/Configurator.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FiltersTest.java

https://issues.redhat.com/browse/DBZ-5818

DBZ-5818 field.exclude.list in MongoDB Connector v2.0 doesn't accept * as a wildcard for collectionName

---

COPYRIGHT.txt
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresShutdownIT.java
documentation/modules/ROOT/pages/connectors/postgresql.adoc

https://issues.redhat.com/browse/DBZ-3921
https://issues.redhat.com/browse/DBZ-5949

Backport DBZ-3921 and DBZ-5949 to 1.9

---

pom.xml

https://issues.redhat.com/browse/DBZ-5977

DBZ-5977 Upgrade Apicurio to 2.4.1.Final

---

jenkins-jobs/pipelines/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-5979

DBZ-5979 Properly handle multiplatform files in release

---

jenkins-jobs/pipelines/aro_deployment_pipeline.groovy
jenkins-jobs/pipelines/aro_teardown_pipeline.groovy
jenkins-jobs/pipelines/build_debezium_images_pipeline.groovy
jenkins-jobs/pipelines/build_debezium_tool_images_pipeline.groovy
jenkins-jobs/pipelines/cluster_deployment_pipeline.groovy
jenkins-jobs/pipelines/deploy_snapshots_pipeline.groovy
jenkins-jobs/pipelines/downstream_artifact_server_prepare_pipeline.groovy
jenkins-jobs/pipelines/downstream_prepare_pipeline.groovy
jenkins-jobs/pipelines/node_snapshot_build_pipeline.groovy
jenkins-jobs/pipelines/node_snapshot_history_cleanup_pipeline.groovy
jenkins-jobs/pipelines/prod-release-pipeline.groovy
jenkins-jobs/pipelines/release-pipeline.groovy
jenkins-jobs/pipelines/rhel_downstream_prepare_pipeline.groovy
jenkins-jobs/pipelines/system_pipeline.groovy
jenkins-jobs/pipelines/upstream_artifact_server_prepare_pipeline.groovy
jenkins-jobs/pipelines/upstream_kafka_connect_prepare_pipeline.groovy

Also show the build status directly in email subject
https://issues.redhat.com/browse/DBZ-5974

DBZ-5974 Use `catchError` instead of try/finall block

---

pom.xml

https://issues.redhat.com/browse/DBZ-5980

DBZ-5980 Upgrade PostgreSQL JDBC driver to 42.5.1

---

debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java
debezium-core/src/test/java/io/debezium/transforms/ExtractNewRecordStateTest.java

https://issues.redhat.com/browse/DBZ-5966

DBZ-5966 Truncate records incompatible with ExtractNewRecordState

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorTest.java

https://issues.redhat.com/browse/DBZ-4663

DBZ-4663 Remove option for specifying driver class from MySQL Connector

---

debezium-testing/debezium-testing-system/pom.xml
debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java

Update to latest version of apicurio
Force apicurio docker image to 2.3.1 temporarily

DBZ-5282 Debezium is not working with apicurio and custom truststores

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-5985

DBZ-5985 Disable to print invalid estimated row count when config "snapshot.select.statement.overrides"

---

debezium-bom/pom.xml
debezium-server/debezium-server-bom/pom.xml
debezium-server/debezium-server-dist/pom.xml
debezium-server/debezium-server-infinispan/pom.xml
debezium-server/debezium-server-infinispan/src/main/java/io/debezium/server/infinispan/InfinispanSinkConsumer.java
debezium-server/debezium-server-infinispan/src/test/java/io/debezium/server/infinispan/InfinispanSinkConsumerIT.java
debezium-server/debezium-server-infinispan/src/test/java/io/debezium/server/infinispan/InfinispanTestConfigSource.java
debezium-server/debezium-server-infinispan/src/test/java/io/debezium/server/infinispan/InfinispanTestResourceLifecycleManager.java
debezium-server/debezium-server-infinispan/src/test/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource
debezium-server/debezium-server-infinispan/src/test/resources/infinispan-local.xml
debezium-server/pom.xml
documentation/modules/ROOT/pages/operations/debezium-server.adoc
pom.xml

https://issues.redhat.com/browse/DBZ-5986

DBZ-5986 Add server sink adapter for Infinispan

---

.github/workflows/contributor-check.yml
.github/workflows/octocat-commits-check.yml
.github/workflows/oracle-workflow-test.yml
.github/workflows/sanity-check.yml

https://issues.redhat.com/browse/DBZ-5998
Respective changes in non-core repos :

DBZ-5998 Use correct format for GITHUB_OUTPUT in CI 

---

.github/workflows/sanity-check.yml

https://issues.redhat.com/browse/DBZ-5998

DBZ-5998 Use github context instead of hard coded values in CI

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorRegressionIT.java
debezium-core/src/main/java/io/debezium/time/ZonedTimestamp.java

https://issues.redhat.com/browse/DBZ-6002

DBZ-6002 Run PostgresConnectorIT.shouldReceiveChangesForChangeColumnDefault() failed

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/AbstractColumnValue.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationMessage.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationMessageColumnValueResolver.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgproto/PgProtoColumnValue.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresMoneyIT.java

https://issues.redhat.com/browse/DBZ-5991

DBZ-5991 There is a problem with postgresql connector parsing the boundary value of money type

---

debezium-api/src/main/java/io/debezium/engine/ChangeEvent.java
debezium-api/src/main/java/io/debezium/engine/DebeziumEngine.java
debezium-api/src/main/java/io/debezium/engine/Header.java
debezium-api/src/main/java/io/debezium/engine/format/JsonByteArray.java
debezium-api/src/main/java/io/debezium/engine/format/KeyValueHeaderChangeEventFormat.java
debezium-embedded/src/main/java/io/debezium/embedded/ConvertingEngineBuilder.java
debezium-embedded/src/main/java/io/debezium/embedded/ConvertingEngineBuilderFactory.java
debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngineChangeEvent.java
debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngineHeader.java
debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java
debezium-server/debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java
debezium-server/debezium-server-core/src/test/java/io/debezium/server/TestConfigSource.java
debezium-server/debezium-server-kafka/src/main/java/io/debezium/server/kafka/KafkaChangeConsumer.java
debezium-server/debezium-server-kafka/src/test/java/io/debezium/server/kafka/AddHeaderTransform.java
debezium-server/debezium-server-kafka/src/test/java/io/debezium/server/kafka/KafkaIT.java
debezium-server/debezium-server-kafka/src/test/java/io/debezium/server/kafka/KafkaTestConfigSource.java
documentation/modules/ROOT/pages/development/engine.adoc
documentation/modules/ROOT/pages/operations/debezium-server.adoc

Add headers support to ChangeEvent
Add SerializationFormat support headers

DBZ-5926 Add support for Connect Headers to Debezium Server

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java

https://issues.redhat.com/browse/DBZ-6012

DBZ-6012 Allow skipping of LSN check failure

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDefaultValueIT.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java

https://issues.redhat.com/browse/DBZ-5996

DBZ-5996 Properly handle zoned timestamp width in Oracle

---

pom.xml

https://issues.redhat.com/browse/DBZ-6005

Upgrade to Quarkus 2.16.0.Final

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/grant.sql

https://issues.redhat.com/browse/DBZ-6019

DBZ-6019 Role REVOKE with user-like role name

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java

https://issues.redhat.com/browse/DBZ-6026

DBZ-6026 Don't update last offsets in statistics

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-6031

DBZ-6031 Support compression/logging clauses after LOB storage clauses

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java

https://issues.redhat.com/browse/DBZ-6029

DBZ-6029 Unexpected format for TIME column: 8:00

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-6020

DBZ-6020 ALTER and CREATE USER allow ROLE option

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java

https://issues.redhat.com/browse/DBZ-6040

DBZ-6040 Remove the redundancy "schema.history.internal" from MySqlConnectorConfig

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSourceInfoStructMaker.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetOffsetContext.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java

https://issues.redhat.com/browse/DBZ-6038

DBZ-6038 Add wallTime in mongo source info

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDatabaseSchema.java

https://issues.redhat.com/browse/DBZ-5798

DBZ-5798 Data type conversion failed for mysql bigint

---

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/IncrementalSnapshotIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java

https://issues.redhat.com/browse/DBZ-6035

DBZ-6035 Fix race condition in SQL server tests

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-6016

DBZ-6016 Add CLUSTERING KEY constraint for TOKUDB

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateUniqueIndexParserListener.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/TableCommonParserListener.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java

https://issues.redhat.com/browse/DBZ-6003

DBZ-6003 Nullable columns marked with "optional: false" in DDL events

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/zzz/ZZZGtidSetIT.java

return false instead of true from isGtidModeEnabled for GTID_MODEs of OFF_PERMISSIVE and ON_PERMISSIVE

DBZ-2296 Change handling of GTID_MODE=OFF_PERMISSIVE and ON_PERMISSIVE

---

debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java

https://issues.redhat.com/browse/DBZ-6037

DBZ-6037 Data no longer logged on error

---

debezium-bom/pom.xml
debezium-server/debezium-server-bom/pom.xml
debezium-storage/debezium-storage-rocketmq/pom.xml
debezium-storage/debezium-storage-rocketmq/src/main/java/io/debezium/storage/rocketmq/RocketMqAdminUtil.java
debezium-storage/debezium-storage-rocketmq/src/main/java/io/debezium/storage/rocketmq/RocketMqConfig.java
debezium-storage/debezium-storage-rocketmq/src/main/java/io/debezium/storage/rocketmq/ZeroMessageQueueSelector.java
debezium-storage/debezium-storage-rocketmq/src/main/java/io/debezium/storage/rocketmq/history/RocketMqSchemaHistory.java
debezium-storage/debezium-storage-rocketmq/src/test/java/io/debezium/storage/rocketmq/ZeroMessageQueueSelectorTest.java
debezium-storage/pom.xml
documentation/modules/ROOT/pages/operations/debezium-server.adoc
pom.xml

https://issues.redhat.com/browse/DBZ-5997

DBZ-5997 Debezium Storage add support for Apache RocketMQ

---

.github/workflows/contributor-check.yml
.github/workflows/debezium-workflow.yml
.github/workflows/octocat-commits-check.yml
.github/workflows/oracle-workflow-test.yml
.github/workflows/sanity-check.yml
.github/workflows/website-build-workflow.yml

Signed-off-by: dependabot[bot] <support@github.com>

[ci] Bump actions

---

pom.xml

https://issues.redhat.com/browse/DBZ-6054

DBZ-6054 Upgrade to Kafka 3.3.2

---

.github/dependabot.yml

Once reviewed and merged, I'll push the same change to other repos as well (let me know if you merge it, but don't want me to push it to other repos).

[ci] Configure depenecy bot to use [ci] prefix for PRs

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotChangeEventSource.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/IncrementalSnapshotIT.java

https://issues.redhat.com/browse/DBZ-5973

DBZ-5973 Support for more types as key in mongodb incremental snapshot implementation

---

debezium-core/src/main/java/io/debezium/config/Instantiator.java
debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java

https://issues.redhat.com/browse/DBZ-6075

DBZ-6075 Related DBZ-5561 Use TCCL to load configuration classes by default

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/converters/PostgresCloudEventsMaker.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/converters/PostgresRecordParser.java

https://issues.redhat.com/browse/DBZ-6089

DBZ-6089 Expose sequence in postgres parser

---

debezium-core/src/main/java/io/debezium/data/SpecialValueDecimal.java
debezium-core/src/main/java/io/debezium/data/VariableScaleDecimal.java
debezium-core/src/main/java/io/debezium/data/geometry/Point.java
debezium-core/src/main/java/io/debezium/transforms/ExtractChangedRecordState.java
debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java
debezium-core/src/test/java/io/debezium/transforms/AbstractExtractStateTest.java
debezium-core/src/test/java/io/debezium/transforms/ExtractChangedRecordStateTest.java
debezium-core/src/test/java/io/debezium/transforms/ExtractNewRecordStateTest.java
documentation/modules/ROOT/nav.adoc
documentation/modules/ROOT/pages/transformations/event-changes.adoc
documentation/modules/ROOT/pages/transformations/event-flattening.adoc

https://issues.redhat.com/browse/DBZ-5283

DBZ-5283 Introduce a new SMT ExtractChangedRecordState to capture the names of changed/unchanged field within headers

---

documentation/modules/ROOT/pages/connectors/postgresql.adoc

@jpechane, @Naros, small typo fix :)

[docs] Adding missing comma in listing

---

pom.xml

https://issues.redhat.com/browse/DBZ-6102

DBZ-6102 Upgrade Kafka to 3.4.0

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSourceInfoStructMaker.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/events/LogMinerEventRow.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SourceInfoTest.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-6091
This PR supersedes PR #4274 and should only be applied to `main`.  There will be a separate PR opened that specifically targets the behavior as it relates to branch `2.1`.

DBZ-6091 Fix SSN NumericOverflow exception

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/converters/MongoDbRecordParser.java

https://issues.redhat.com/browse/DBZ-6038
Follow up to get wallTime accessible

DBZ-6038 Expose walltime from mongo record parser

---

.github/workflows/jdk-outreach-workflow.yml

https://issues.redhat.com/browse/DBZ-5825

DBZ-5825 Use Java 19 in Java Outreach action

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-6079

DBZ-6079 Change query.fetch.size default from 0 to 2000.

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-6120

DBZ-6120 Correctly handle quoting table/schema names

---

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/ConnectorConfiguration.java

https://issues.redhat.com/browse/DBZ-6136

DBZ-6136 Add toJson to TestContainers ConnectorConfiguration impl

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-6143

DBZ-6143 Unify Oracle TIMESTAMP WITH TIME ZONE format

---

debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
debezium-core/src/main/java/io/debezium/config/Configuration.java
debezium-core/src/main/java/io/debezium/config/Field.java
debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java

https://issues.redhat.com/browse/DBZ-6156

DBZ-6156 Add hostname validator to connector configuration

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
debezium-connector-postgres/src/test/resources/postgres_create_tables.ddl

https://issues.redhat.com/browse/DBZ-6163

DBZ-6163 Properly handle zoned timestamp within PostgreSQL

---

pom.xml

https://issues.redhat.com/browse/DBZ-6144

DBZ-6144 Upgrade impsort-maven-plugin from 1.7.0 to 1.8.0

---

jenkins-jobs/pipelines/deploy_snapshots_pipeline.groovy

https://issues.redhat.com/browse/DBZ-5951

DBZ-5951 Init Maven repo with DSE artifacts

---

debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java

Issue : https://issues.redhat.com/browse/DBZ-6179

DBZ-6179 Fix swallowing of exception cause of finally block in RelationalSnapshotChangeEventSource

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java

https://issues.redhat.com/browse/DBZ-6191

DBZ-6191 Do not fail if slot cannot be advanced

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
debezium-connector-mysql/src/test/java/io/debezium/relational/history/KafkaSchemaHistoryTest.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java
debezium-core/src/main/java/io/debezium/relational/history/AbstractSchemaHistory.java
debezium-core/src/main/java/io/debezium/relational/history/SchemaHistory.java
debezium-core/src/main/java/io/debezium/schema/HistorizedDatabaseSchema.java

https://issues.redhat.com/browse/DBZ-6197

DBZ-6197 Remove duplicated createDdlFilter method from historized connector config

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-6188

DBZ-6188 Allow optional uidList for partitionFunctionKey rule

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-6194

DBZ-6194 Use CHARSET for alterByConvertCharset clause

---

.github/workflows/oracle-workflow-test.yml

https://issues.redhat.com/browse/DBZ-6115

DBZ-6115 Use correct format for output

---

.github/workflows/oracle-workflow-test.yml

https://issues.redhat.com/browse/DBZ-6239

DBZ-6239 Use pull_request instead of pull_request_target

---

debezium-api/src/main/java/io/debezium/engine/ChangeEvent.java
debezium-api/src/main/java/io/debezium/engine/DebeziumEngine.java
debezium-api/src/main/java/io/debezium/engine/RecordChangeEvent.java
debezium-api/src/main/java/io/debezium/engine/format/Avro.java
debezium-api/src/main/java/io/debezium/engine/format/ChangeEventFormat.java
debezium-api/src/main/java/io/debezium/engine/format/CloudEvents.java
debezium-api/src/main/java/io/debezium/engine/format/Json.java
debezium-api/src/main/java/io/debezium/engine/format/KeyValueChangeEventFormat.java
debezium-api/src/main/java/io/debezium/engine/format/KeyValueHeaderChangeEventFormat.java
debezium-api/src/main/java/io/debezium/engine/format/Protobuf.java
debezium-api/src/main/java/io/debezium/engine/format/SerializationFormat.java
debezium-api/src/main/java/io/debezium/engine/spi/OffsetCommitPolicy.java
documentation/modules/ROOT/pages/operations/debezium-server.adoc

https://issues.redhat.com/browse/DBZ-6235

DBZ-6235 Remove incubation notice from Debezium Server page

---

COPYRIGHT.txt
documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot.adoc

JSON has an extra closing brace

[docs] Fix SQL JSON

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc

[DBZ-6223 ](https://issues.redhat.com/browse/DBZ-6223)Adds anchor id and downstream metadata, and edits to change streams content.

DBZ-6223 Add metadata; additional edits

---

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumContainer.java

https://issues.redhat.com/browse/DBZ-6244

DBZ-6244 Support ImageFromDockerfile syntax with testcontainers

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc

https://issues.redhat.com/browse/DBZ-6090
Does not yet incorporate changes introduced by https://github.com/debezium/debezium/pull/4366

DBZ-6090 Updated connection information in MongoDB documentation

---

debezium-testing/debezium-testing-testcontainers/pom.xml
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbContainer.java
debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/MongoDbReplicaSetTest.java

https://issues.redhat.com/browse/DBZ-6247

DBZ-6247 More resilient image version handling for MongoDbContainer and related tests

---

documentation/modules/ROOT/pages/configuration/topic-auto-create-config.adoc

[docs] Adding missing comma

---

documentation/modules/ROOT/nav.adoc
documentation/modules/ROOT/pages/transformations/header-to-value.adoc
documentation/modules/ROOT/pages/transformations/index.adoc

Docs for https://github.com/debezium/debezium/pull/4383

DBZ-6201: Add docs for HeaderToValue SMT

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresConnectionIT.java

A follow-up for https://github.com/debezium/debezium/pull/4265
When  Debezium tries to fetch a replication slot with null confirmed_flush_lsn from Postgres it checks for any long-running transactions before fallback to restart_lsn and if there are any it needs to wait for them to be finished. However, during start-up Debezium connector creates this kind of transaction itself and it needs to be ignored during this check.

DBZ-6251 Ignore Debezium internal transactions during fallback to restart_lsn in Postgres connector if confirmed_flush_lsn is NULL

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4

https://issues.redhat.com/browse/DBZ-6221

DBZ-6221 Correctly interpret CHARACTER data types while streaming

---

debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-6072

DBZ-6072 NPE when setting schema.history.internal.store.only.captured.tables.ddl=true

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc

@roldanbob Rest of the docs needed for https://issues.redhat.com/browse/DBZ-6090 
Can you please have a look and modify as you see fit? Feel free to add commits.

DBZ-6090 Added documentation for mongodb.connection.mode

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlJdbcSinkDataTypeConverterIT.java

https://issues.redhat.com/browse/DBZ-6225
https://issues.redhat.com/browse/DBZ-6226
https://issues.redhat.com/browse/DBZ-6231

DBZ-6225 DBZ-6226 DBZ-6231 Fix test failure

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java

https://issues.redhat.com/browse/DBZ-6274

DBZ-6274 Fix compatibility with Oracle tests and Infinispan 14

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java

https://issues.redhat.com/browse/DBZ-6275

DBZ-6275 Correctly sync Infinispan cache on event counter reset

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/marshalling/LogMinerEventAdapter.java

https://issues.redhat.com/browse/DBZ-6273

DBZ-6273 Fix Infinispan serialization of table names with spaces

---

documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mysql-sqlserver-connector.adoc
documentation/modules/ROOT/partials/modules/all-connectors/proc-verifying-the-connector-deployment.adoc

[DBZ-6272](https://issues.redhat.com/browse/DBZ-6272)
Edits to address review feedback about naming inconsistencies in the verification steps of the downstream installation documentation.
This change has no effect on the community version of the documenation.

DBZ-6272  2.1 branch cherrypick review feedback updates

---

debezium-bom/pom.xml
debezium-connector-mysql/pom.xml
debezium-testing/debezium-testing-system/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-6304

DBZ-6304 Upgrade MySQL driver and change Maven coordinates

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_revoke.sql

Fix for https://issues.redhat.com/browse/DBZ-6314

DBZ-6314: Add revoke statement for Oracle parser

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-6198

DBZ-6198 Update Oracle permissions to include statistics tables

---

debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
debezium-core/src/main/java/io/debezium/config/Field.java
debezium-core/src/main/java/io/debezium/transforms/HeaderToValue.java
debezium-core/src/main/java/io/debezium/transforms/SmtManager.java
debezium-core/src/main/java/io/debezium/transforms/partitions/ComputePartition.java
debezium-core/src/main/java/io/debezium/transforms/partitions/ComputePartitionConfigDefinition.java
debezium-core/src/main/java/io/debezium/transforms/partitions/ComputePartitionException.java
debezium-core/src/main/java/io/debezium/transforms/partitions/PartitionRouting.java
debezium-core/src/test/java/io/debezium/transforms/HeaderToValueTest.java
debezium-core/src/test/java/io/debezium/transforms/partitions/ComputePartitionTest.java
debezium-core/src/test/java/io/debezium/transforms/partitions/PartitionRoutingTest.java

Address request https://issues.redhat.com/browse/DBZ-5902. New `PartitionRouting` SMT has been implemented that will replace `ComputePartition` with the aim to address more use cases.
With this configuration
```json
{
"name": "inventory-connector",  
"config": {  
"connector.class": "io.debezium.connector.mysql.MySqlConnector",
"tasks.max": "1",  
"database.hostname": "mysql",  
"database.port": "3306",
"database.user": "debezium",
"database.password": "dbz",
"database.server.id": "184054",  
"topic.prefix": "dbserver1",  
"database.include.list": "inventory",  
"schema.history.internal.kafka.bootstrap.servers": "kafka:9092",  
"schema.history.internal.kafka.topic": "schema-changes.inventory",
"topic.creation.default.partitions": 2,
"topic.creation.default.replication.factor": 1, …
```

DBZ-5902: Create a more generic SMT to route events to specific partition

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDatabaseSchema.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSchemaChangeEventEmitter.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/relational/RelationalTableFilters.java
debezium-core/src/main/java/io/debezium/relational/history/AbstractSchemaHistory.java
debezium-core/src/main/java/io/debezium/relational/history/SchemaHistory.java
debezium-core/src/main/java/io/debezium/schema/HistorizedDatabaseSchema.java
debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java
documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc

https://issues.redhat.com/browse/DBZ-6070

DBZ-6070 DDL events not stored in schema history topic for excluded tables

---

COPYRIGHT.txt
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetrics.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
documentation/modules/ROOT/pages/connectors/oracle.adoc
jenkins-jobs/scripts/config/Aliases.txt

https://issues.redhat.com/browse/DBZ-6155
More conversation is under https://github.com/debezium/debezium/pull/4322 which was unfortunatelly accidentally closed during rebase and force push.

DBZ-6155 Adjust LogMiner batch size based on the default batch size

---

documentation/modules/ROOT/nav.adoc
documentation/modules/ROOT/pages/connectors/index.adoc
documentation/modules/ROOT/pages/connectors/jdbc.adoc

https://issues.redhat.com/browse/DBZ-6310

DBZ-6310 Document JDBC sink connector

---

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/ConnectorConfiguration.java

https://issues.redhat.com/browse/DBZ-6306

DBZ-6306 Use connection string configuration in ConnectorConfiguration#forMongoDbContainer

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-6318

DBZ-6318 Remove outdated SYS account usage

---

COPYRIGHT.txt
documentation/modules/ROOT/pages/operations/debezium-server.adoc

Also, be consistent about using {prodname} instead of the constant string "Debezium".
This PR is for [DBZ-6325](https://issues.redhat.com/browse/DBZ-6325).

DBZ-6325 Describe example configuration

---

documentation/modules/ROOT/pages/operations/debezium-server.adoc

This PR adds documentation for RabbitMQ sink added via https://github.com/debezium/debezium-server/pull/13

 DBZ-6260 documentation for RabbitMQ sink

---

debezium-core/src/test/java/io/debezium/junit/ConditionalFail.java
debezium-core/src/test/java/io/debezium/junit/Flaky.java

https://issues.redhat.com/browse/DBZ-6324

DBZ-6324 Provide @Flaky annotation for CI unstable tests

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-5395

DBZ-5395 Improve Oracle offset management when LOB enabled

---

documentation/modules/ROOT/pages/integrations/outbox.adoc

https://issues.redhat.com/browse/DBZ-5859

DBZ-5859 first draft of reactive outbox docs

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/events/LogMinerEventRow.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java

https://issues.redhat.com/browse/DBZ-6329

DBZ-6329 Make sure Oracle source rs_id field populated

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java

https://issues.redhat.com/browse/DBZ-6353

DBZ-6353 Use SQL state to identify missing function

---

.github/workflows/debezium-workflow.yml
debezium-core/src/main/java/io/debezium/relational/history/AbstractFileBasedSchemaHistory.java
debezium-storage/debezium-storage-azure-blob/src/main/java/io/debezium/storage/azure/blob/history/AzureBlobSchemaHistory.java
debezium-storage/debezium-storage-file/src/main/java/io/debezium/storage/file/history/FileSchemaHistory.java
debezium-storage/debezium-storage-s3/src/main/java/io/debezium/storage/s3/history/S3SchemaHistory.java

https://issues.redhat.com/browse/DBZ-6209

DBZ-6209 Refactor storage implementations

---

COPYRIGHT.txt
documentation/modules/ROOT/pages/operations/debezium-server.adoc
jenkins-jobs/scripts/config/Aliases.txt

https://issues.redhat.com/projects/DBZ/issues/DBZ-6372

DBZ-6372 - Kinesis Sink - AWS Credentials Provider

---

.github/workflows/debezium-workflow.yml

https://issues.redhat.com/browse/DBZ-6360

DBZ-6360: Add job for build jdbc connector

---

COPYRIGHT.txt
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql
jenkins-jobs/scripts/config/Aliases.txt

https://issues.redhat.com/projects/DBZ/issues/DBZ-6386

DBZ-6386 Support shrink clause for Oracle table partition

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java

https://issues.redhat.com/browse/DBZ-6259

DBZ-6259 Add missing description of various snapshot modes in the connector field definitions

---

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/ConnectorConfiguration.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbContainer.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbReplicaSet.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbShardedCluster.java

https://issues.redhat.com/browse/DBZ-6363
Superseding PR to #4455  
Related UI PR: https://github.com/debezium/debezium-ui/pull/701

DBZ-6363 Support for MongoDB tests in UI build with Debezium 2.2

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java

https://issues.redhat.com/browse/DBZ-6357

DBZ-6357 Fix parsing of NATIONAL CHAR

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlFloatIT.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-6388

DBZ-6388 __source_ts_ms r (read) operation date is set to future for SQL Server

---

COPYRIGHT.txt
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
jenkins-jobs/scripts/config/Aliases.txt

https://issues.redhat.com/browse/DBZ-6353

DBZ-6353 Add a conditions of 'OBJECT_IN_USE', 'NOT_IMPLEMENTED'.

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerJdbcConfiguration.java
debezium-core/src/main/java/io/debezium/config/Configuration.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConfiguration.java

https://issues.redhat.com/browse/DBZ-6157

DBZ-6157 Disable potentially dangerous MySQL JDBC props

---

debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/history/JdbcSchemaHistoryConfig.java
debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/offset/JdbcOffsetBackingStoreConfig.java

- Make insert/delete SQL statements configurable for JDBC Offset.
- Make insert SQL statement configurable for JDBC Schema history.

Dbz 6433 JDBC offset/schema history enhancements

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/logwriter/CommitLogWriterFlushStrategy.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/FlushStrategyIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-6254
* Add `log.mining.query.filter.mode` configuration option
* Add `log.mining.username.include.list` configuration option

DBZ-6254 Add LogMiner Query and Username Include Filtering

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_drop.sql

https://issues.redhat.com/browse/DBZ-6442

DBZ-6442 Support FORCE-clause in DROP TABLE

---

.github/workflows/debezium-workflow.yml

closes: https://issues.redhat.com/browse/DBZ-6443

DBZ-6443 Add step to build Debezium Connector MySQL in store build job

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-6355

DBZ-6355 Fix test failure - race condition

---

jenkins-jobs/pipelines/release/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-6437

DBZ-6437 Modify parent for server BOM during release

---

debezium-core/src/main/java/io/debezium/pipeline/signal/channels/FileSignalChannel.java
debezium-core/src/test/java/io/debezium/pipeline/signal/FileSignalChannelTest.java
debezium-core/src/test/resources/debezium_signaling_file.signals.txt

cc @jpechane  @Naros is this looks any good?

DBZ-4027 implement external signaling source, FileSignalChannel

---

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumContainer.java

https://issues.redhat.com/browse/DBZ-5359; relates to https://github.com/debezium/debezium-ui/pull/702

DBZ-5339 Enable Jolokia using DebeziumContainer class

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-6457

DBZ-6457 Use PDB for parallel snapshot connections

---

debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/offset/JdbcOffsetBackingStore.java

- Change encoding of JDBC offset data from UTF-16 to UTF-8

[DBZ-6476] Change encoding of JDBC offset data from UTF-16 to UTF-8

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java

https://issues.redhat.com/browse/DBZ-6465
[2.1](https://github.com/debezium/debezium/tree/2.1) branch only

DBZ-6465 Set "snapshot" field to LAST when snapshot is completed

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-6492

DBZ-6492 Support logical_replication_clause in Oracle

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-6502
Solves ORA-18176 error "{} not in any time zone.DATE" error.

DBZ-6502 Fix Oracle 23.x JDBC driver compatibility

---

debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java

https://issues.redhat.com/browse/DBZ-6515

DBZ-6515 Add units to the description

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/recordemitter/MongoDbChangeRecordEmitter.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/recordemitter/MongoDbSnapshotRecordEmitter.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlChangeRecordEmitter.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/BaseChangeRecordEmitter.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeRecordEmitter.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
debezium-core/src/main/java/io/debezium/pipeline/AbstractChangeRecordEmitter.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java
debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/relational/SnapshotChangeRecordEmitter.java

DBZ-6366: Code Improvements for skip.messages.without.change

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java
debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
debezium-core/src/main/java/io/debezium/pipeline/signal/SignalProcessor.java
debezium-core/src/main/java/io/debezium/pipeline/signal/channels/FileSignalChannel.java
debezium-core/src/main/java/io/debezium/pipeline/signal/channels/KafkaSignalChannel.java
debezium-core/src/main/java/io/debezium/pipeline/signal/channels/SignalChannelReader.java

closes: https://issues.redhat.com/browse/DBZ-6511

DBZ-6511 Restore Kafka signal offset only when KafkaSignalChannel is enabled

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationMessageColumnValueResolver.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java

closes: https://issues.redhat.com/browse/DBZ-6524

DBZ-6524 Add support for `ltree` and `isbn` PostgreSQL data-types

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/NotificationsIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/NotificationsIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/NotificationsIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SignalsIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/NotificationsIT.java
debezium-core/src/main/java/io/debezium/metrics/Metrics.java
debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
debezium-core/src/main/java/io/debezium/pipeline/JmxUtils.java
debezium-core/src/main/java/io/debezium/pipeline/notification/Notification.java
debezium-core/src/main/java/io/debezium/pipeline/notification/NotificationService.java
debezium-core/src/main/java/io/debezium/pipeline/notification/channels/jmx/JmxNotificationChannel.java
debezium-core/src/main/java/io/debezium/pipeline/notification/channels/jmx/JmxNotificationChannelMXBean.java
debezium-core/src/main/java/io/debezium/pipeline/signal/SignalRecord.java
debezium-core/src/main/java/io/debezium/pipeline/signal/channels/FileSignalChannel.java
debezium-core/src/main/java/io/debezium/pipeline/signal/channels/KafkaSignalChannel.java
debezium-core/src/main/java/io/debezium/pipeline/signal/channels/jmx/JmxSignalChannel.java
debezium-core/src/main/java/io/debezium/pipeline/signal/channels/jmx/JmxSignalChannelMXBean.java
debezium-core/src/main/resources/META-INF/services/io.debezium.pipeline.notification.channels.NotificationChannel
debezium-core/src/main/resources/META-INF/services/io.debezium.pipeline.signal.channels.SignalChannelReader
debezium-core/src/test/java/io/debezium/pipeline/signal/SignalProcessorTest.java
debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
debezium-embedded/src/test/java/io/debezium/pipeline/notification/AbstractNotificationsIT.java

closes: https://issues.redhat.com/browse/DBZ-6424

DBZ-6424 Allow sending signals and receiving notifications via JMX 

---

jenkins-jobs/scripts/trigger-nightly-docker.sh

https://issues.redhat.com/browse/DBZ-6536

DBZ-6536 Adding debezium server nightly image build

---

jenkins-jobs/pipelines/release/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-6542

DBZ-6542 operator release image support

---

jenkins-jobs/scripts/trigger-nightly-docker.sh

https://issues.redhat.com/browse/DBZ-6541

DBZ-6541 operator nightly image support

---

jenkins-jobs/pipelines/release/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-6539

DBZ-6539 Adding operator release modifications to the pipeline

---

debezium-core/src/main/java/io/debezium/transforms/partitions/PartitionRouting.java
debezium-core/src/test/java/io/debezium/transforms/partitions/PartitionRoutingTest.java

closes: https://issues.redhat.com/browse/DBZ-6543

DBZ-6543 Fix NPE due to optional fields in PartitionRouting SMT

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java

https://issues.redhat.com/browse/DBZ-6547

DBZ-6547 Declare exactly-once semantic support for Postgres connector

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotSourceIT.java
debezium-connector-mysql/src/test/resources/ddl/connector_test_ro.sql
debezium-connector-mysql/src/test/resources/ddl/mysql_dbz_6533.sql
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java

Fixes https://issues.redhat.com/browse/DBZ-6533

DBZ-6533: fix table order on partial match when snapshotting

---

debezium-core/src/main/java/io/debezium/transforms/partitions/PartitionRouting.java

closes: https://issues.redhat.com/browse/DBZ-6543

DBZ-6543 Unhandled NullPointerException in PartitionRouting will crash the whole connect plugin

---

COPYRIGHT.txt
jenkins-jobs/scripts/config/Aliases.txt

https://issues.redhat.com/browse/DBZ-6554

DBZ-6554 Add contributor

---

github-support/list-contributors.sh
github-support/list-missing-commits-by-issue-key.sh

https://issues.redhat.com/browse/DBZ-6556

DBZ-6556 Add missing repositories to contrib/missing commit workflows

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/logwriter/RacCommitLogWriterFlushStrategy.java

https://issues.redhat.com/browse/DBZ-6359

DBZ-6359 Allow specifying SIDs in Oracle `rac.nodes` parameter

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-6528

DBZ-6528 Fix Oracle NPE when storing only captured table schemas with signals

---

debezium-connector-oracle/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-6193
NOTE: Artifacts for Infinispan 14.0.11.Final have not yet been published; will move from draft once available.

DBZ-6193 Upgrade Infinispan to 14.0.11.Final

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSourceInfoStructMaker.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorTest.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSourceInfoStructMaker.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorTest.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSourceInfoStructMaker.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/CustomPostgresSourceInfoStructMaker.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSourceInfoStructMaker.java
debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
debezium-core/src/main/java/io/debezium/connector/AbstractSourceInfoStructMaker.java
debezium-core/src/main/java/io/debezium/connector/LegacyV1AbstractSourceInfoStructMaker.java
debezium-core/src/main/java/io/debezium/connector/SourceInfoStructMaker.java

Added support to use custom connector config using custom task.

DBZ-6076: Add support for custom SourceInfoStructMaker for adding new fields to source field

---

documentation/modules/ROOT/pages/configuration/notification.adoc

completes: https://issues.redhat.com/browse/DBZ-6552

[docs] Document new `status` property for incremental snapshot notification

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-6513

DBZ-6513 Fix the computation of Oracle's negative interval

---

debezium-core/src/main/java/io/debezium/schema/SchemaNameAdjuster.java
debezium-core/src/test/java/io/debezium/relational/TableSchemaBuilderTest.java
debezium-core/src/test/java/io/debezium/util/SchemaNameAdjusterTest.java

closes: https://issues.redhat.com/browse/DBZ-6559

DBZ-6559 Restore backward compatibility for field that stars with a digit

---

.github/workflows/debezium-workflow.yml
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlJdbcSinkDataTypeConverterIT.java
pom.xml

closes: https://issues.redhat.com/browse/DBZ-6534

DBZ-6534 Update MySQL test image from 5.7 to 8.0

---

documentation/modules/ROOT/pages/configuration/notification.adoc

https://issues.redhat.com/browse/DBZ-6552
Completes:  https://github.com/debezium/debezium/pull/4599 and https://github.com/debezium/debezium/pull/4603
Adding explanation for each of the status value

DBZ-6552 Document new TABLE_SCAN_COMPLETED status property

---

debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/history/RedisSchemaHistory.java

https://issues.redhat.com/browse/DBZ-6580

DBZ-6580 Support retries for reconnect

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbChangeEventSourceFactory.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnector.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetDiscovery.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSets.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/ConnectionContext.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/ConnectionStrings.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/MongoDbClientFactory.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/MongoDbConnection.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/AbstractMongoIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ConnectionIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TestHelper.java
debezium-core/src/main/java/io/debezium/config/Configuration.java

https://issues.redhat.com/browse/DBZ-6578

DBZ-6578 Debezium should honor read preference from connection string

---

debezium-core/src/main/java/io/debezium/transforms/HeaderToValue.java
debezium-core/src/test/java/io/debezium/transforms/HeaderToValueTest.java

closes: https://issues.redhat.com/browse/DBZ-6588

DBZ-6588 Skip tombstone record on HeaderToValue SMT

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnector.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectionIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorConfigTest.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java

https://issues.redhat.com/browse/DBZ-5676

DBZ-5676 Align QUERY_FETCH_SIZE config in SQLServer Connector to use a default value

---

debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/history/RedisSchemaHistory.java

https://issues.redhat.com/browse/DBZ-6594

DBZ-6594 Make retry logic more robust

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SignalsIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/spi/CustomActionProvider.java
debezium-connector-postgres/src/test/resources/META-INF/services/io.debezium.pipeline.signal.actions.SignalActionProvider
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
debezium-core/src/main/java/io/debezium/pipeline/signal/actions/SchemaChanges.java
debezium-core/src/main/java/io/debezium/pipeline/signal/actions/SignalActionProvider.java
debezium-core/src/main/java/io/debezium/pipeline/signal/actions/StandardActionProvider.java
debezium-core/src/main/resources/META-INF/services/io.debezium.pipeline.signal.actions.SignalActionProvider

closes: https://issues.redhat.com/browse/DBZ-6417

DBZ-6417 Provide extensible signal actions mechanism through SPI

---

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbContainer.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbDeployment.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbReplicaSet.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbShardedCluster.java
debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/MongoDbReplicaSetAuthTest.java

https://issues.redhat.com/browse/DBZ-6596
This is required to test https://github.com/debezium/debezium/pull/4631

DBZ-6596 Support authentication for ReplicaSet testcontainers deployments

---

documentation/modules/ROOT/pages/configuration/signalling.adoc

docs for: https://github.com/debezium/debezium/pull/4635

DBZ-6417 Document how to implement a custom action

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-6622

DBZ-6622 MySQL ALTER USER with RETAIN CURRENT PASSWORD fails with parsing exception

---

documentation/modules/ROOT/pages/connectors/jdbc.adoc

https://issues.redhat.com/browse/DBZ-6602

DBZ:6602: Support record header as primary_key

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectionTest.java

closes: https://issues.redhat.com/browse/DBZ-6633

DBZ-6633 Throw a RetriableException when a SQLRecoverableException occurs during OracleConnection instantiation

---

documentation/modules/ROOT/pages/connectors/jdbc.adoc

closes: https://issues.redhat.com/browse/DBZ-6632

DBZ-6632 Improve properties description on JDBC connector documentation

---

debezium-connector-mysql/pom.xml
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlParserIT.java
debezium-connector-postgres/pom.xml
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresShutdownIT.java
debezium-testing/debezium-testing-testcontainers/pom.xml
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/ApicurioRegistryContainer.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumContainer.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/util/ContainerImageVersions.java

https://issues.redhat.com/browse/DBZ-6525

DBZ-6525 Removing runtime dependency on core for testcontainers module

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc

https://issues.redhat.com/browse/DBZ-6592

DBZ-6592 Documenting database permissions required by the MongoDB connector

---

debezium-bom/pom.xml

https://issues.redhat.com/browse/DBZ-6649

DBZ-6649 Upgrade gRPC to 1.56.1

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbTaskContext.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/metrics/MongoDbSnapshotChangeEventSourceMetrics.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTaskContext.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleTaskContext.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresMetricsIT.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerTaskContext.java
debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
debezium-core/src/main/java/io/debezium/config/Field.java
debezium-core/src/main/java/io/debezium/connector/common/CdcSourceTaskContext.java
debezium-core/src/main/java/io/debezium/metrics/Metrics.java
debezium-core/src/main/java/io/debezium/pipeline/JmxUtils.java
debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
documentation/modules/ROOT/pages/connectors/cassandra.adoc
documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/mongodb.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/oracle.adoc
documentation/modules/ROOT/pages/connectors/postgresql.adoc
documentation/modules/ROOT/pages/connectors/spanner.adoc
documentation/modules/ROOT/pages/connectors/sqlserver.adoc
documentation/modules/ROOT/pages/connectors/vitess.adoc

https://issues.redhat.com/browse/DBZ-6603

DBZ-6603 Support for custom tags in the connector metrics

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DebeziumEngineIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/spi/CustomActionProvider.java
debezium-core/src/main/java/io/debezium/converters/CloudEventsConverter.java
debezium-core/src/test/java/io/debezium/converters/CloudEventsConverterTest.java
debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
debezium-embedded/src/main/java/io/debezium/embedded/KafkaConnectUtil.java
debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java
debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/offset/JdbcOffsetBackingStore.java
debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/offset/RedisOffsetBackingStore.java
pom.xml

https://issues.redhat.com/browse/DBZ-6047
Related PR - https://github.com/debezium/debezium-connector-vitess/pull/143

DBZ-6047 Upgrade to Kafka 3.5

---

documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/oracle.adoc
documentation/modules/ROOT/pages/connectors/sqlserver.adoc

https://issues.redhat.com/browse/DBZ-5518

DBZ-5518 Document message schema format

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotParallelSourceIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotSourceIT.java
debezium-core/src/main/java/io/debezium/jdbc/DefaultMainConnectionProvidingConnectionFactory.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/util/ColumnUtils.java

https://issues.redhat.com/browse/DBZ-6472

DBZ-6472 MySqlSnapshotChangeEventSource parallel execute createSchemaEventsForTables

---

COPYRIGHT.txt
jenkins-jobs/scripts/config/Aliases.txt

related to: 
https://github.com/debezium/debezium-connector-vitess/pull/144

Add contributor

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
debezium-core/src/main/java/io/debezium/schema/SchemaChangeEvent.java

https://issues.redhat.com/browse/DBZ-6650

DBZ-6650 Avoid ConcurrentModificationException during dispatch

---

debezium-embedded/src/test/java/io/debezium/pipeline/notification/AbstractNotificationsIT.java

closes: https://issues.redhat.com/browse/DBZ-6672

DBZ-6672 Improve NotificationIT stability

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-6676
@roldanbob This is a follow-up from DBZ-3605 (PR #4615).

DBZ-6676 Oracle XML/RAW documentation updates

---

documentation/modules/ROOT/pages/operations/debezium-server.adoc

Related to PR https://github.com/debezium/debezium-server/pull/30

DBZ-6581 Documentation - update configs on Rabbitmq

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoUtil.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/MongoDbConnection.java

https://issues.redhat.com/browse/DBZ-6700

DBZ-6700 using hello command instead of ping 

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java

closes: https://issues.redhat.com/browse/DBZ-6669

DBZ-6669 Snapshot will not capture data when signal.data.collection is present without table.include.list

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbErrorHandler.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorDatabaseRestrictedIT.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlErrorHandler.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresErrorHandler.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresErrorHandlerTest.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java
debezium-core/src/main/java/io/debezium/pipeline/ErrorHandler.java
debezium-core/src/test/java/io/debezium/pipeline/ErrorHandlerTest.java

https://issues.redhat.com/browse/DBZ-6670

DBZ-6670 Replace error handler instead of recreate in order to keep retry counter

---

documentation/modules/ROOT/pages/connectors/jdbc.adoc

closes: https://issues.redhat.com/browse/DBZ-6655

DBZ-6655 Document not supported schema change records on JDBC connector

---

documentation/modules/ROOT/pages/connectors/jdbc.adoc

https://issues.redhat.com/browse/DBZ-6637
Documents changes in https://github.com/debezium/debezium-connector-jdbc/pull/19.

DBZ-6637 Document JDBC sink `dialect.postgres.postgis.schema` property

---

debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java

https://issues.redhat.com/browse/DBZ-6730

DBZ-6730 Exit consumption loop if engine has stopped

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-6733

DBZ-6733 Skip mining distance calc. if upper bounds not within distance

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc

[DBZ-6592](https://issues.redhat.com/browse/DBZ-6592)
Updates a previously merged documentation change to fix a grammatically incorrect sentence.

DBZ-6592 Revises unclear sentence

---

documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-nosql.adoc

fixed typo on line 20 - missing period in MyCollection - changed to My.Collection

[docs] Update proc-triggering-an-incremental-snapshot-nosql.adoc

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java

https://issues.redhat.com/browse/DBZ-6751

DBZ-6751 Fix failing test OracleSchemaMigrationIT

---

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java

https://issues.redhat.com/browse/DBZ-6743

DBZ-6743 Remove duplicate query.fetch.size definition

---

debezium-quarkus-outbox-common/pom.xml
debezium-quarkus-outbox-reactive/deployment/pom.xml
debezium-quarkus-outbox-reactive/integration-tests/pom.xml
debezium-quarkus-outbox-reactive/pom.xml
debezium-quarkus-outbox-reactive/runtime/pom.xml
debezium-quarkus-outbox/deployment/pom.xml
debezium-quarkus-outbox/integration-tests/pom.xml
debezium-quarkus-outbox/pom.xml
debezium-quarkus-outbox/runtime/pom.xml
debezium-storage/debezium-storage-redis/pom.xml
debezium-testing/debezium-testing-testcontainers/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-6744

DBZ-6744 Decouple extension and server quarkus versions

---

debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/history/JdbcSchemaHistory.java
debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/history/JdbcSchemaHistoryConfig.java
debezium-storage/debezium-storage-jdbc/src/test/java/io/debezium/storage/jdbc/history/JdbcSchemaHistoryTest.java

https://issues.redhat.com/browse/DBZ-6484
Cleanup of https://github.com/debezium/debezium/pull/4639

DBZ-6484 Support FQDN table name in history

---

debezium-core/src/main/java/io/debezium/pipeline/signal/SignalProcessor.java

https://issues.redhat.com/browse/DBZ-6745

DBZ-6745 Remove redundant filter logic from SignalProcessor

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/UnchangedToastedPlaceholder.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/UnchangedToastedReplicationMessageColumn.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/BlockingSnapshotIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DecoderDifferences.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java

https://issues.redhat.com/browse/DBZ-6767

DBZ-6767 Add missing type name

---

debezium-core/src/main/java/io/debezium/pipeline/notification/channels/jmx/JmxNotificationChannel.java
debezium-core/src/main/java/io/debezium/pipeline/signal/channels/SourceSignalChannel.java
debezium-core/src/main/java/io/debezium/pipeline/signal/channels/jmx/JmxSignalChannel.java

closes: https://issues.redhat.com/browse/DBZ-6777

DBZ-6777 Fix wrong static notification and signals lists that lead to be wrongly shared between connectors instances

---

pom.xml

https://issues.redhat.com/browse/DBZ-6785

DBZ-6785 Upgrade Kafka to 3.5.1

---

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TestHelper.java
debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/MongoDbReplicaSetTest.java

https://issues.redhat.com/browse/DBZ-6779

DBZ-6779 Fix version parsing of non-numerical chars

---

debezium-core/src/main/java/io/debezium/schema/SchemaFactory.java
debezium-core/src/main/java/io/debezium/transforms/SchemaChangeEventFilter.java
debezium-core/src/main/java/io/debezium/transforms/SmtManager.java
debezium-core/src/test/java/io/debezium/transforms/SchemaChangeEventFilterTest.java
documentation/modules/ROOT/nav.adoc
documentation/modules/ROOT/pages/transformations/schema-change-event-filter.adoc

Change stream supports filtering schema change event

DBZ-6240 Change stream supports filtering schema change event

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
debezium-ddl-parser/src/test/resources/mysql/examples/dml_select.sql

https://issues.redhat.com/browse/DBZ-6780

DBZ-6780 Relax lexicon rule for MySQL `REAL_LITERAL`

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/MongoDataConverter.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouter.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/MongoArrayConverterTest.java

https://issues.redhat.com/browse/DBZ-6760

DBZ-6760 Outbox transformation can cause connector to crash

---

COPYRIGHT.txt
debezium-core/src/main/java/io/debezium/pipeline/signal/channels/KafkaSignalChannel.java
jenkins-jobs/scripts/config/Aliases.txt

Closes: https://issues.redhat.com/browse/DBZ-6689

DBZ-6689 make kafka signal consumer group configurable

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/dml_select.sql

https://issues.redhat.com/browse/DBZ-6794

DBZ-6794 Dbz crashed on parsing MySQL DDL statement (SELECT 1 + @sum:=1 AS ss;)

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputColumnValue.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java

https://issues.redhat.com/browse/DBZ-6758

DBZ-6758 When using pgoutput in postgres connector, (+/-)Infinity is not supported in decimal values

---

debezium-connector-mysql/pom.xml
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/UniqueDatabase.java

https://issues.redhat.com/browse/DBZ-6791

DBZ-6791 Disable default ssl in tests

---

documentation/modules/ROOT/pages/configuration/signalling.adoc
documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-pass-through-kafka-signals-configuration-properties.adoc

closes: https://issues.redhat.com/browse/DBZ-6688

DBZ-6688 Improve Kafka channel documentation

---

documentation/modules/ROOT/pages/connectors/jdbc.adoc

https://issues.redhat.com/browse/DBZ-6801
Documents https://github.com/debezium/debezium-connector-jdbc/pull/27

DBZ-6801 Introduce JDBC sink option `dialect.sqlserver.identity.insert`

---

COPYRIGHT.txt
debezium-core/src/main/java/io/debezium/relational/RelationalTableFilters.java
debezium-core/src/test/java/io/debezium/relational/Configurator.java
debezium-core/src/test/java/io/debezium/relational/RelationalTableFiltersTest.java
jenkins-jobs/scripts/config/Aliases.txt

author Matan Cohen <matan.c@Matans-MacBook-Pro.local> 1691399798 +0300 committer Jiri Pechanec <jpechane@redhat.com> 1692100081 +0200
DBZ-6712 fix snapshot to history internal topic to respect schema.history.internal.store.only.captured.databases.ddl flag

DBZ-6712 fix snapshot to history internal topic to respect schema.history.internal.store.only.captured.databases.ddl flag

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentState.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTestIT.java

https://issues.redhat.com/browse/DBZ-6774

DBZ-6774 MongoDB New Document State Extraction: nonexistent field for add.headers

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-6813

DBZ-6813 Improve Infinispan configuration example

---

documentation/modules/ROOT/pages/configuration/signalling.adoc
documentation/modules/ROOT/partials/modules/all-connectors/con-connector-ad-hoc-snapshots.adoc
documentation/modules/ROOT/partials/modules/all-connectors/con-connector-blocking-snapshot.adoc
documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-kafka.adoc
documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-sql.adoc
documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot.adoc

related to: https://github.com/debezium/debezium/pull/4741

DBZ-6731 Document blocking snapshot signal configuration

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetrics.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetricsMXBean.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/EmbeddedInfinispanLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/RemoteInfinispanLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-6615

DBZ-6615 Add OldestScnAgeInMilliseconds LogMiner based metric.

---

documentation/modules/ROOT/pages/configuration/signalling.adoc
documentation/modules/ROOT/partials/modules/all-connectors/con-connector-blocking-snapshot.adoc

[DBZ-6731](https://issues.redhat.com/browse/DBZ-6731)
Per [discussion](https://github.com/debezium/debezium/pull/4769#issuecomment-1680935521) in PR #4769, this change applies minor edits to the description of the `filter` property of the `additional-conditions` property.

DBZ-6731 Update description of `additional-conditions` `filter` property

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/dml_select.sql

https://issues.redhat.com/browse/DBZ-6724
Upstream - https://github.com/antlr/grammars-v4/pull/3668

DBZ-6724 Modify JOIN clause to support unstructured joins

---

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/NotificationsIT.java
debezium-core/src/main/java/io/debezium/pipeline/notification/Notification.java
debezium-core/src/main/java/io/debezium/pipeline/notification/channels/jmx/JmxNotificationChannel.java
debezium-embedded/src/test/java/io/debezium/pipeline/notification/AbstractNotificationsIT.java

Closes: https://issues.redhat.com/browse/DBZ-6742

DBZ-6742 use JSON format for JMX Notitication userData

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDefaultValueConverter.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java

[Fix DBZ-6824.](https://issues.redhat.com/browse/DBZ-6824)

DBZ-6824 trim default value for the BIGINT and SMALLINT types when parsing MySQL DDL

---

debezium-core/src/main/java/io/debezium/relational/history/SchemaHistory.java
debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java

https://issues.redhat.com/browse/DBZ-6840

DBZ-6840 Wrong filtered comments

---

debezium-core/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java

Closes: https://issues.redhat.com/browse/DBZ-6843

DBZ-6843 change skipped change event log to debug

---

documentation/modules/ROOT/pages/connectors/vitess.adoc

Add docs on this config since it's fully supported for vitess connector.

DBZ-6844 Add truncate column config to Vitess connector docs

---

debezium-embedded/src/main/java/io/debezium/embedded/KafkaConnectUtil.java

https://issues.redhat.com/browse/DBZ-6853

DBZ-6853 Use topic admin

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-6860

DBZ-6860 Fix NPE Oracle shouldContinueToUpdateOffsetsEvenWhenTableIsNotChanged

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/pipeline/signal/actions/snapshotting/ExecuteSnapshot.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-6865

DBZ-6865 Avoid getting NPE when executing the arrived method in ExecuteSnapshot

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactory.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FiltersTest.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/IncrementalSnapshotIT.java

https://issues.redhat.com/browse/DBZ-6867

DBZ-6867 streaming pipeline should match events from collection include list as well as signal collection

---

debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java

https://issues.redhat.com/browse/DBZ-6866

DBZ-6866 Fix behaviour when errors.max.retries = 0

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentState.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTest.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTestIT.java

https://issues.redhat.com/browse/DBZ-6773

DBZ-6773 Adding support for new field/header mappings to ExtractNewDocumentState

---

COPYRIGHT.txt
documentation/modules/ROOT/pages/connectors/mysql.adoc
jenkins-jobs/scripts/config/Aliases.txt

Fix link in MySQL connector doc

[docs] Update mysql.adoc

---

debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/offset/JdbcOffsetBackingStoreConfig.java
debezium-storage/debezium-storage-jdbc/src/test/java/io/debezium/storage/jdbc/JdbcOffsetBackingStoreIT.java
debezium-storage/debezium-storage-jdbc/src/test/java/io/debezium/storage/jdbc/JdbcOffsetBackingStoreTest.java

https://issues.redhat.com/browse/DBZ-6855

DBZ-6855 Use correct naming prefix

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-6876

DBZ-6876 Add key/drop index clause to all drop constraints

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/events/LogMinerEventRow.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java

https://issues.redhat.com/browse/DBZ-6880
@zalmane here's the PR I talked about.  It should be a direct back-port to Debezium 2.3 branch.  Let me know what you think about these log changes,.

DBZ-6880 Move some Oracle log messages to DEBUG

---

documentation/antora.yml
documentation/modules/ROOT/pages/install.adoc
documentation/modules/ROOT/pages/operations/debezium-server.adoc

https://issues.redhat.com/browse/DBZ-6850
Sibling website PR - https://github.com/debezium/debezium.github.io/pull/940

DBZ-6850 Improve documentation artifact links

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java

https://issues.redhat.com/browse/DBZ-6481

DBZ-6481 Support Postgres enum as key in incremental snapshot

---

.github/workflows/debezium-workflow.yml

https://issues.redhat.com/browse/DBZ-6151

DBZ-6151 Removing MongoDB 4.2 from test matrix

---

.github/workflows/debezium-workflow.yml

https://issues.redhat.com/browse/DBZ-6882

DBZ-6882 Adding MongoDB 7.0 to test matrix

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactory.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactoryTest.java

https://issues.redhat.com/browse/DBZ-6872
prepares the ground for https://issues.redhat.com/browse/DBZ-6871

DBZ-6872 Ability to switch the order of user defined and internal aggregation pipeline

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactory.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactoryTest.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java

https://issues.redhat.com/browse/DBZ-6871
Should be merged only after https://github.com/debezium/debezium/pull/4834

DBZ-6871 MongoDB connector is now able to skip events for oversized documents

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnector.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/ConnectionContext.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/ConnectionStrings.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/Configurator.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorWithConnectionStringIT.java
documentation/modules/ROOT/pages/connectors/mongodb.adoc

https://issues.redhat.com/browse/DBZ-6892

DBZ-6892 Removing all code related to previously deprecated MongoDB conenctor configuration

---

documentation/modules/ROOT/pages/connectors/oracle.adoc

https://issues.redhat.com/browse/DBZ-2543
Documentation for PR #4719

DBZ-2543 Document Oracle OpenLogReplicator adapter

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
documentation/modules/ROOT/pages/connectors/mongodb.adoc

https://issues.redhat.com/browse/DBZ-6883
First commit ought to be applied to both 2.3 and 2.4 
Second commit is exclusive to 2.4

DBZ-6883 documentation

---

debezium-connector-oracle/pom.xml

https://issues.redhat.com/browse/DBZ-6903

DBZ-6903 Use distinct dir for protobuf generated sources

---

.github/workflows/debezium-workflow.yml
debezium-connector-postgres/pom.xml
jenkins-jobs/pipelines/release/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-6911
Depends on https://github.com/debezium/container-images/pull/345

DBZ-6911 Support for PostgreSQL 16

---

debezium-core/src/main/java/io/debezium/transforms/outbox/JsonSchemaData.java
debezium-core/src/test/java/io/debezium/transforms/outbox/JsonSchemaDataTest.java

https://issues.redhat.com/browse/DBZ-6910

DBZ-6910 Values being omitted from list of JSON object

---

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDatabaseSchemaTest.java
debezium-core/src/main/java/io/debezium/relational/history/ConnectTableChangeSerializer.java
debezium-core/src/main/java/io/debezium/relational/history/JsonTableChangeSerializer.java
debezium-core/src/main/java/io/debezium/relational/history/TableChanges.java
debezium-core/src/main/java/io/debezium/schema/SchemaChangeEvent.java
debezium-core/src/main/java/io/debezium/schema/SchemaFactory.java

closes: https://issues.redhat.com/browse/DBZ-6945

DBZ-6945 Remove Table object for DROP schema event

---

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/NotificationsIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SignalsIT.java
debezium-core/src/main/java/io/debezium/pipeline/JmxUtils.java
debezium-embedded/src/test/java/io/debezium/pipeline/notification/AbstractNotificationsIT.java

closes: https://issues.redhat.com/browse/DBZ-6957

DBZ-6957 Remove spaces in Signal and Notification JMX ObjectName

---

debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/DataCollection.java

https://issues.redhat.com/browse/DBZ-6956

DBZ-6956 Add parenthesis around additional condition

---

debezium-core/src/main/java/io/debezium/transforms/TimezoneConverter.java
debezium-core/src/test/java/io/debezium/transforms/TimezoneConverterTest.java

https://issues.redhat.com/browse/DBZ-6940

DBZ-6940 Refactor & add check for unsupported schema types

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql

https://issues.redhat.com/browse/DBZ-6971

DBZ-6971 Support parse mariadb keyword "NOCOPY" in related index statement

---

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/NotificationsIT.java
debezium-core/src/main/java/io/debezium/pipeline/notification/IncrementalSnapshotNotificationService.java
debezium-core/src/main/java/io/debezium/pipeline/notification/InitialSnapshotNotificationService.java
debezium-core/src/main/java/io/debezium/pipeline/notification/Notification.java
debezium-core/src/main/java/io/debezium/pipeline/notification/NotificationService.java
debezium-core/src/main/java/io/debezium/pipeline/notification/channels/SinkNotificationChannel.java
debezium-core/src/main/java/io/debezium/schema/SchemaFactory.java
debezium-core/src/test/java/io/debezium/pipeline/notification/IncrementalSnapshotNotificationServiceTest.java
debezium-core/src/test/java/io/debezium/pipeline/notification/NotificationServiceTest.java
debezium-embedded/src/test/java/io/debezium/pipeline/notification/AbstractNotificationsIT.java
documentation/modules/ROOT/pages/configuration/notification.adoc

closes: https://issues.redhat.com/browse/DBZ-6793
Since documentation changes are small I preferred to have it in the same PR.

DBZ-6793 Add timestamp to Notification

---

debezium-core/src/main/java/io/debezium/transforms/SchemaChangeEventFilter.java
debezium-core/src/test/java/io/debezium/transforms/SchemaChangeEventFilterTest.java
documentation/modules/ROOT/pages/transformations/schema-change-event-filter.adoc

https://issues.redhat.com/browse/DBZ-6966

DBZ-6966 Fix reverted filtering logic

---

documentation/modules/ROOT/pages/configuration/signalling.adoc
documentation/modules/ROOT/pages/connectors/jdbc.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/oracle.adoc
documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-pass-through-kafka-signals-configuration-properties.adoc

closes: https://issues.redhat.com/browse/DBZ-6941

DBZ-6941 MySQL Kafka Signalling documentation is incorrect

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactory.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Filters.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/AbstractMongoConnectorIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactoryTest.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/Configurator.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FiltersTest.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TestHelper.java
debezium-core/src/main/java/io/debezium/function/Predicates.java

... and the ablity to override internal aggregation pipeline for MongoDB conenctor
https://issues.redhat.com/browse/DBZ-6973

DBZ-6973 Literal matching mode for database/collection filters

---

jenkins-jobs/job-dsl/release/release_upstream.groovy
jenkins-jobs/pipelines/release/release-pipeline.groovy

https://issues.redhat.com/browse/DBZ-6738

DBZ-6738 create OLM manifest archive during operator release

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc

https://issues.redhat.com/browse/DBZ-6968

DBZ-6968 Added units to the documentation of cursor.oversize.skip.threshold

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc

…and 'user…_only' option of cursor.pipeline.order
https://issues.redhat.com/browse/DBZ-6973

DBZ-6973 Documentation for filters.match.mode configuration 

---

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java

https://issues.redhat.com/browse/DBZ-6987

DBZ-6987 Create schema in Postgres test if not exists

---

pom.xml

https://issues.redhat.com/browse/DBZ-6992

DBZ-6992 Update Quarkus dev version to compile with JDK 21

---

debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterDelegate.java
debezium-core/src/main/java/io/debezium/transforms/outbox/JsonSchemaData.java
debezium-core/src/test/java/io/debezium/transforms/outbox/JsonSchemaDataTest.java

https://issues.redhat.com/browse/DBZ-6983

DBZ-6983 Add the ability to sanitize field name when inferencing json schema

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
debezium-core/src/main/java/io/debezium/util/ElapsedTimeStrategy.java
debezium-core/src/test/java/io/debezium/util/ElapsedTimeStrategyTest.java

https://issues.redhat.com/browse/DBZ-6778

DBZ-6778 Refactor ElapsedTimeStrategy

---

debezium-storage/debezium-storage-redis/pom.xml
debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/JedisClient.java
debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/RedisClient.java
debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/WaitReplicasRedisClient.java
debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/offset/RedisOffsetBackingStore.java
debezium-storage/debezium-storage-redis/src/test/java/io/debezium/storage/redis/WaitReplicasRedisClientTest.java
debezium-storage/debezium-storage-redis/src/test/java/io/debezium/storage/redis/offset/RedisOffsetBackingStoreTest.java

https://issues.redhat.com/browse/DBZ-6952

DBZ-6952 Fix reconnect issue

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/UnistrHelper.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-6975

DBZ-6975 Correctly handle escaped single-quotes in UNISTR arguments

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java

https://issues.redhat.com/browse/DBZ-7006

DBZ-7006 Properly handle escaped CLOB single-quotes

---

documentation/modules/ROOT/pages/connectors/mysql.adoc

Hey @jpechane quick doc update. Just cost me half a day or so :)

[docs] Clarifying RDS binlog requirement

---

documentation/modules/ROOT/pages/connectors/postgresql.adoc

Addresses https://issues.redhat.com/browse/DBZ-7041

DBZ-7041: pgoutput limitation for generated columns

---

debezium-core/src/main/java/io/debezium/transforms/TimezoneConverter.java
debezium-core/src/test/java/io/debezium/transforms/TimezoneConverterTest.java

https://issues.redhat.com/browse/DBZ-7020

DBZ-7020 Use optional schema for Timezone Converter tests

---

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java

Reverts debezium/debezium#4456
The change in https://github.com/debezium/debezium/pull/4502 should address the underlying issue.

DBZ-7015 Enable replication slot advance check

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/EventBuffer.java
debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
debezium-connector-mysql/src/test/resources/logback-test.xml

closes: https://issues.redhat.com/browse/DBZ-7035

DBZ-7035 MySqlStreamingChangeEventSource will effectively stop during a blocking snapshot

---

COPYRIGHT.txt
documentation/modules/ROOT/pages/connectors/postgresql.adoc
jenkins-jobs/scripts/config/Aliases.txt

I think it would be very helpful for the criminally dense like myself to have this explicitly stated in the documentation. What seems obvious to me now comes after nearly a week of frustration.

[docs] Add note about including heartbeats table in publications

---

debezium-connect-rest-extension/src/main/java/io/debezium/kcrestextension/DebeziumResource.java
debezium-core/src/test/java/io/debezium/kafka/KafkaServer.java
debezium-storage/debezium-storage-redis/pom.xml
pom.xml

https://issues.redhat.com/browse/DBZ-7033

DBZ-7033 Upgrade Kafka to 3.6.0

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java

https://issues.redhat.com/browse/DBZ-6975

DBZ-6975 Fix test failures

---

documentation/modules/ROOT/pages/connectors/jdbc.adoc

https://issues.redhat.com/browse/DBZ-6970
Sibling PR - https://github.com/debezium/debezium-connector-jdbc/pull/37

DBZ-6970 Add the new property "truncate.enabled" to jdbc doc

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java

https://issues.redhat.com/browse/DBZ-7067

DBZ-7067 Improve Oracle logging for COMMITs

---

documentation/modules/ROOT/pages/connectors/jdbc.adoc

Suggestion to clarify description.

DBZ-6970 Edit description for JDBC connector `truncate.enabled` property

---

documentation/modules/ROOT/nav.adoc
documentation/modules/ROOT/pages/integrations/outbox.adoc
documentation/modules/ROOT/pages/integrations/tracing.adoc

Installation and configuration of OpenTelemetry to enable traceability

DBZ-2862 Documentation

---

debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordStateConfigDefinition.java
documentation/modules/ROOT/pages/transformations/event-flattening.adoc
documentation/modules/ROOT/pages/transformations/mongodb-event-flattening.adoc

https://issues.redhat.com/browse/DBZ-7062

DBZ-7062 Update transformation property "delete.tombstone.handling.mode" to debezium doc

---

debezium-core/src/main/java/io/debezium/converters/CloudEventsConverter.java
debezium-core/src/main/java/io/debezium/converters/CloudEventsConverterConfig.java
debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadataHeaderImpl.java
debezium-core/src/test/java/io/debezium/converters/CloudEventsConverterTest.java
documentation/modules/ROOT/pages/integrations/cloudevents.adoc

https://issues.redhat.com/browse/DBZ-7060

DBZ-7060 Rename `metadata.location` -> `metadata.source`

---

.github/workflows/oracle-workflow-test.yml
debezium-bom/pom.xml
debezium-connector-oracle/pom.xml
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/rest/DebeziumOracleConnectorResourceIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/rest/DebeziumOracleConnectorResourceNoDatabaseIT.java
debezium-connector-oracle/src/test/resources/Dockerfile.rest.test
debezium-parent/pom.xml
debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/ConfigProperties.java
debezium-testing/debezium-testing-testcontainers/pom.xml
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/OracleContainer.java
debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/testhelper/RestExtensionTestInfrastructure.java
pom.xml

closes to https://issues.redhat.com/browse/DBZ-6763

DBZ-6763 Add integration tests for the Debezium Connect REST extension for the Oracle connector / Oracle Connect REST extension

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/FieldSelector.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldBlacklistIT.java

https://issues.redhat.com/browse/DBZ-7058

DBZ-7058 Fixed index handling in FieldSelector

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/expressions.sql

https://github.com/antlr/grammars-v4/pull/3804

DBZ-7095 The MySqlParser.g4 parser has a priority problem

---

debezium-embedded/src/main/java/io/debezium/embedded/ConvertingEngineBuilder.java
debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
debezium-embedded/src/test/java/io/debezium/embedded/ConnectorOutputTest.java
debezium-microbenchmark-oracle/src/main/java/io/debezium/performance/connector/oracle/EndToEndPerf.java

https://issues.redhat.com/browse/DBZ-7110

DBZ-7110 Remove deprecated EmbeddedEngine interfaces

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetDiscovery.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/ReplicaSet.java
documentation/modules/ROOT/pages/connectors/mongodb.adoc

https://issues.redhat.com/browse/DBZ-7108

DBZ-7108 Switched default connection mode for sharded clusters

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc

Suggested terminology edit to property description.

DBZ-7108 Minor edit to description of mongodb.connection.mode property

---

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbReplicaSet.java

https://issues.redhat.com/browse/DBZ-6875

DBZ-6875 ensuring root user is created before secured Mongo RS is considered started

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactory.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
pom.xml

https://issues.redhat.com/browse/DBZ-6726

DBZ-6726 support for $changeStreamSplitLargeEvent aggregation in MongoDB connector

---

debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/RedisCommonConfig.java
debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/history/RedisSchemaHistory.java
documentation/modules/ROOT/pages/operations/debezium-server.adoc

https://issues.redhat.com/browse/DBZ-7120

DBZ-7120 Add a connection max retry limit to Redis schema history

---

documentation/modules/ROOT/pages/connectors/mongodb.adoc

Docs for https://issues.redhat.com/browse/DBZ-6726

DBZ-6726 Documenting split handling mode for oversized change events

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionCommitConsumerIT.java

https://issues.redhat.com/browse/DBZ-6963

DBZ-6963 Do not merge events if table has no LOB columns

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/dml_insert.sql

https://issues.redhat.com/browse/DBZ-7119
Upstream PR - https://github.com/antlr/grammars-v4/pull/3813

DBZ-7119 Allow empty column list in INSERT

---

debezium-core/src/main/java/io/debezium/transforms/extractnewstate/DefaultDeleteHandlingStrategy.java
debezium-core/src/main/java/io/debezium/transforms/extractnewstate/LegacyDeleteHandlingStrategy.java

Related to https://github.com/debezium/debezium-connector-jdbc/pull/43

DBZ-6317 Document tombstone behavior

---

documentation/modules/ROOT/pages/connectors/informix.adoc

Documentation of new Informix connector

DBZ-4999 [docs] Documentation of Informix connector

---

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql

https://issues.redhat.com/browse/DBZ-7140

DBZ-7140 Debezium-ddl-parser crashes on parsing MySQL DDL statement (specific UNION)

---

documentation/modules/ROOT/pages/connectors/mysql.adoc

https://issues.redhat.com/browse/DBZ-7132

DBZ-7132 Document MySQL database.ssl.* options

---

documentation/modules/ROOT/nav.adoc
documentation/modules/ROOT/pages/transformations/convert-cloudevent-to-saveable-form.adoc
documentation/modules/ROOT/pages/transformations/index.adoc

better to merge after https://github.com/debezium/debezium-connector-jdbc/pull/46

[docs] Docs for `ConvertCloudEventToSaveableForm`

---

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/EmbeddedInfinispanLogMinerEventProcessor.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/InMemoryPendingTransactionsCache.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/RemoteInfinispanLogMinerEventProcessor.java

Already discussed with @Naros.
I tested it on our environment, including the cache reload from ISPN data during restart

DBZ-7153 in memory cache to speed up infinispan

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-7146

DBZ-7146 Configurable inactivity pause duration in MongoDB connector

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbChangeEventSourceFactory.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/metrics/MongoDbChangeEventSourceMetricsFactory.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/metrics/MongoDbStreamingChangeEventSourceMetrics.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/metrics/MongoDbStreamingChangeEventSourceMetricsMBean.java

https://issues.redhat.com/browse/DBZ-7162

DBZ-7162 Various streaming metrics for MongoDB connector

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/JsonSerialization.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbCollectionSchema.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSchema.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/recordemitter/MongoDbSnapshotRecordEmitter.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/IncrementalSnapshotIT.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/JsonSerializationTest.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ShardedIncrementalSnapshotIT.java

https://issues.redhat.com/browse/DBZ-7157

DBZ-7157: Key serialisation for events from sharded collections with composite sharding key

---

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/rest/DebeziumMySqlConnectorResource.java

closes to https://issues.redhat.com/browse/DBZ-7179

DBZ-7179 Fix DebeziumMySqlConnectorResource not using the new MySQL adatper structure to support different MySQL flavors

---

pom.xml

https://issues.redhat.com/browse/DBZ-7144

DBZ-7144 Upgrade protobuf-java-util to 3.25.1

---

pom.xml

https://issues.redhat.com/browse/DBZ-7187

DBZ-7187 Upgrade to Infinispan 14.0.20.Final

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/events/SplitEventHandler.java

https://issues.redhat.com/browse/DBZ-7186

DBZ-7186 Cleanup event processing loop in streaming event source of MongoDB connector

---

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbReplicaSet.java

take 2 on https://issues.redhat.com/browse/DBZ-6875 this time featuring the correct exception!

DBZ-6875 Ignoring the correct exception when awaiting RS primary

---

COPYRIGHT.txt
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseVersion.java
jenkins-jobs/scripts/config/Aliases.txt

https://issues.redhat.com/browse/DBZ-7194

DBZ-7194 Use a more relaxed Oracle version pattern

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/NotificationsIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/NotificationsIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/NotificationsIT.java
debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/NotificationsIT.java
debezium-core/src/main/java/io/debezium/pipeline/notification/InitialSnapshotNotificationService.java
debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
debezium-embedded/src/test/java/io/debezium/pipeline/notification/AbstractNotificationsIT.java
documentation/modules/ROOT/pages/configuration/notification.adoc

DBZ-6878 add table specific notification in initial snapshot

DBZ-6878 add table specific notification in initial snapshot

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java

https://issues.redhat.com/browse/DBZ-7206

DBZ-7206 Always check for blocking snapshot pause request 

---

documentation/modules/ROOT/pages/connectors/jdbc.adoc

https://issues.redhat.com/browse/DBZ-6636

DBZ-6636 Document JDBC sink field include/exclude list

---

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/NotificationsIT.java

Just a follow-up for https://github.com/debezium/debezium/pull/5026

DBZ-6878 Fix NotificationsIT for Oracle

---

debezium-bom/pom.xml

https://issues.redhat.com/browse/DBZ-7209

DBZ-7209 Upgrade logback to 1.2.12

---

documentation/antora.yml
pom.xml

https://issues.redhat.com/browse/DBZ-7198

DBZ-7198 Upgrade apicurio to 2.5.3.Final

---

COPYRIGHT.txt
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/UnchangedToastedReplicationMessageColumn.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
jenkins-jobs/scripts/config/Aliases.txt

Jira Issue: https://issues.redhat.com/browse/DBZ-7193
Affected Debezium versions > 2.0

DBZ-7193 Unchanged toasted array columns are substituted with placeholder even if  REPLICA IDENTITY == FULL

---

documentation/antora.yml
pom.xml

This reverts commit 5aed12951ab0f54dc33590e77253b2d81f6576ad.

DBZ-7198 Revert "Upgrade apicurio to 2.5.3.Final"

---

COPYRIGHT.txt
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java
debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/UnchangedToastedReplicationMessageColumn.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
jenkins-jobs/scripts/config/Aliases.txt

Jira Issue: https://issues.redhat.com/browse/DBZ-7193
Affected Debezium versions > 2.0

DBZ-7193 Unchanged toasted array columns are substituted with placeholder even if REPLICA IDENTITY == FULL

---

documentation/modules/ROOT/pages/connectors/db2.adoc
documentation/modules/ROOT/pages/connectors/informix.adoc
documentation/modules/ROOT/pages/connectors/mongodb.adoc
documentation/modules/ROOT/pages/connectors/mysql.adoc
documentation/modules/ROOT/pages/connectors/oracle.adoc
documentation/modules/ROOT/pages/connectors/postgresql.adoc
documentation/modules/ROOT/pages/connectors/sqlserver.adoc

Doc for : https://github.com/debezium/debezium/pull/5061

DBZ-6834 Add docs for incremental.snapshot.watermarking.strategy

---

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbChangeEventSourceFactory.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbOffsetContext.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbDeleteWindowCloser.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotChangeEventSource.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotContext.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbInsertWindowCloser.java
debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/ReplicaSetNotifier.java
debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/IncrementalSnapshotIT.java
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java
debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotIT.java
debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
debezium-core/src/main/java/io/debezium/pipeline/signal/actions/snapshotting/CloseIncrementalSnapshotWindow.java
debezium-core/src/main/java/io/debezium/pipeline/signal/actions/snapshotting/OpenIncrementalSnapshotWindow.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/DeleteWindowCloser.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/InsertWindowCloser.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedIncrementalSnapshotChangeEventSource.java
debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/WatermarkWindowCloser.java
debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractSnapshotTest.java

closes: https://issues.redhat.com/browse/DBZ-6834
Todo:

DBZ-6834 Provide INSERT/DELETE semantics for incremental snapshot watermarking

---

debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadata.java
debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadataBaseImpl.java
debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadataHeaderImpl.java
debezium-core/src/main/java/io/debezium/converters/spi/CloudEventsMaker.java
debezium-core/src/test/java/io/debezium/converters/CloudEventsConverterTest.java

https://issues.redhat.com/browse/DBZ-7216

DBZ-7216 Fix data schema name in case of metadata is in headers
