COPYRIGHT.txt, debezium-connector-mongodb/pom.xml, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetDiscovery.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ReplicaSetDiscoveryTest.java
Unavailable replica set members are still returned in the `clusterDescription.getServerDescriptions`
If the first in the list is unavailable then we fail to get the replica set name which later causes a "Unable to start MongoDB connector task since no replica sets were found"
I believe we should filter out all the unavailable members before creating the `addressStr` as later on in https://github.com/debezium/debezium/blob/3fb5bf133947e3a447a1e9ba5822333ca561d3ec/debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java#L142
We simply choose the first address to connect to the replicaset
=> DBZ-5260 Filter out unavailable replicaset members

COPYRIGHT.txt, debezium-server/debezium-server-redis/src/main/java/io/debezium/server/redis/RedisConnection.java, jenkins-jobs/scripts/config/Aliases.txt
**GCP Managed Redis does not support client commands.** 
**Solution:** 
Removing clientSetName to be able to use GCP Managed Redis
=> DBZ-5268 Removing clientSetName command in Redis to be able to use GCP Managed Redis

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresOffsetContextTest.java
Currently we update first `lsn` and then update `lastCommitLsn`.
However, when `lastCommitLsn` is for whatever reason `null`, previously
updated `lsn` is reset to `null` as `updateLastCommit()` updates also
`lsn`. This can have unwanted consequences like streaming again records
which were already streamed. To prevent this, update `lastCommitLsn`
only when it's not `null`.
Unfortunately, I wasn't able to figure out any reasonable test for it. Still looking on it, but I'm already little bit skeptical I'll come up with something reasonable:-(. So far tested only manually with Debezium server.
https://issues.redhat.com/browse/DBZ-5070
=> DBZ-5070 Don't reset lsn when lastCommitLsn is null

documentation/antora.yml, documentation/modules/ROOT/pages/transformations/content-based-routing.adoc, documentation/modules/ROOT/pages/transformations/filtering.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-db2-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-oracle-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/shared-deploy-kafka-connect-yaml.adoc
[DBZ-5227](issues.redhat.com/browse/DBZ-5227)
Per @jcechace's findings,  when using Streams to deploy Debezium to Kafka Connect, the CR must download script language archives from Maven as JAR files. This changes updates the downstream shared deployment instructions with that information.
Upon further discussion, it also came out that, as written, the instructions for deploying the scripting SMT were incomplete, so I addressed that as well. , and made changes to the content-based routing, and filtering SMT topics.  
I'd like to revisit this next quarter to apply further conditionalization to eliminate the need for multiple versions of `*kafka-connect-yaml.adoc`. This should be doable by using a single shared file with tagged regions. I spent some time trying to  implement that, but in the …
=> DBZ-5227 Specify use of JAR artifact for script engine language

debezium-connector-oracle/pom.xml
https://issues.redhat.com/browse/DBZ-5234
This profile can be enabled in an IDE environment so that working with the source is easier and less painful.  IDEA does not seem to automatically react to the maven-compiler-plugin include/exclude configurations and this profile allows the IDE to successfully build the sources with all dependencies for sake of running tests in the IDE.
=> DBZ-5234 Add `oracle-ide` profile, simplifies IDE integrations

debezium-connector-oracle/pom.xml, jenkins-jobs/pipelines/deploy-snapshots.groovy, jenkins-jobs/pipelines/release-pipeline.groovy, jenkins-jobs/pipelines/system_pipeline.groovy, jenkins-jobs/pipelines/upstream_artifact_server_prepare_pipeline.groovy, jenkins-jobs/pipelines/upstream_kafka_connect_prepare_pipeline.groovy, jenkins-jobs/scripts/release-pipeline.groovy
https://issues.redhat.com/browse/DBZ-5234
I did one last scrub across the Jenkins jobs and found a few references I missed.  In addition, I decided to change the `oracle-ide` profile to `oracle-all` as it made more sense from the perspective of its usage in the various job scripts imo.
=> DBZ-5234 Rename `oracle-ide` to `oracle-all`

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/CommitScn.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSourceInfoStructMaker.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerOracleOffsetContextLoader.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/events/LogMinerEventRow.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/CommitScnTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDatabaseHistoryTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleOffsetContextTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SourceInfoTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/AbstractProcessorUnitTest.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-5245
@jpechane So this is forward compatible but isn't backward compatible.  Do we think we need to be backward compatible and if not we can scope this change to 2.0 rather than including 1.9.  We can discuss this tomorrow.
=> DBZ-5245 Track commit scn per redo thread

documentation/modules/ROOT/partials/modules/all-connectors/con-connector-incremental-snapshot.adoc
https://issues.redhat.com/browse/DBZ-5336
Updated incremental snapshot documentation to note that tables that have a dot (.) in their name should be escaped with double-quotes.
=> DBZ-5336 Add note about escaping dot (.) characters

COPYRIGHT.txt, debezium-parent/pom.xml
Running 'mvn clean verify' for vitess connector (which includes launch docker for integration tests) would fail when run on an Mac M1 laptop:
[*ERROR*] Failed to execute goal io.fabric8:docker-maven-plugin:0.31.0:build (start) on project debezium-connector-vitess: Execution start of goal io.fabric8:docker-maven-plugin:0.31.0:build failed: An API incompatibility was encountered while executing io.fabric8:docker-maven-plugin:0.31.0:build: java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
The problem is specific to Apple M1 laptop, and is discussed further in: https://github.com/fabric8io/docker-maven-plugin/issues/1257
This is already fixed in docker-maven-plugin 0.39.1
=> DBZ-5374: docker-maven-plugin needs to be upgraded for Mac Apple M1

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/BaseChangeRecordEmitter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerChangeRecordEmitter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamChangeRecordEmitter.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-core/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java
https://issues.redhat.com/browse/DBZ-5295
This PR primarily focuses on two critical points:
1. Reselection of LOB column values when an UPDATE changes the row's primary key
2. Performance improvements by caching the LOB column state in `OracleDatabaseSchema`.
The latter point is similar to the TOAST column handling done with PostgreSQL where instead of needing to iterate the relational `Table` model on each change event, we iterate the model once at registration and cache information about whether the specified table has any LOB columns and use this cache during event processing.  This should improve performance, particularly for tables with larger numbers of columns than for those with fewer columns.
While I was unable to reproduce the same behavior with the PG connector, I did add a …
=> DBZ-5295 Reselect LOB columns on Primary Key changes

RELEASING.md, debezium-connector-postgres/NOTES.md, debezium-connector-postgres/README.md, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/postgres-plugins.adoc, documentation/modules/ROOT/pages/transformations/index.adoc, documentation/modules/ROOT/partials/modules/tutorial/proc-starting-mysql-database.adoc, github-support/list-contributors.sh, github-support/list-missing-commits-by-issue-key.sh, jenkins-jobs/docker/rhel_kafka/Dockerfile, jenkins-jobs/job-dsl/deploy_debezium_tool_images.groovy, jenkins-jobs/job-dsl/deploy_docker_images.groovy, jenkins-jobs/job-dsl/release_debezium_nightly_image.groovy, jenkins-jobs/job-dsl/release_upstream.groovy, jenkins-jobs/pipelines/release-pipeline.groovy, jenkins-jobs/scripts/check-contributors.sh, jenkins-jobs/scripts/release-pipeline.groovy
Besides updating links to renamed GH repo, update also documentation and
replace 'Docker' with 'containers' when possible.
https://issues.redhat.com/browse/DBZ-5048
=> DBZ-5048 Rename GH repo with containes

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java
This PR doesn't replace setting of the last snapshot record with doing so in heartbeat message, but only removes setting of the last snapshot event in MySQL connector where it's done twice. Setting last snapshot record once snapshot is finished doesn't seems to be possible without bigger changes as we send the event immediately. If we decide to proceed further, the most easy way seems to be to do in the same way as MySQL - buffer the events and change the last one once we are done. This is also suggested in [DBZ-3113](https://issues.redhat.com/browse/DBZ-3113).
https://issues.redhat.com/browse/DBZ-5047
=> Cleanup setting of the last snapshot record

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-5418](https://issues.redhat.com/browse/DBZ-5418)
Incorporates review comments.
Tested in a local Antora build and in a downstream build.
Please backport to `1.9`.
**Note**: @Naros re: the comment that you made in our Zulip chat about a random `+` before the warning in description of the  `database.server.name` config property -- this was previously fixed in `main`. But a corresponding change did not make it to `1.9`.  I don't know whether the backport might throw a merge conflict. Probably not, because I didn't change anything there now. After this is merged, I can do a [docs] update directly to `1.9` to make the change.
=> DBZ-5418 Downstream edits based on review

DOCUMENTATION.md, documentation/antora.yml, documentation/modules/ROOT/pages/install.adoc
[DBZ-2595](https://issues.redhat.com/browse/DBZ-2595)
Updates upstream `antora.yml`,  `DOCUMENTATION.MD`, and `install.adoc` files to remove references to unused version variables.
This change does not affect the downstream documentation. 
No need to backport this change.
=> DBZ-2595 Removes unused documentation variables in `antora.yml`

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/CreateTableParserListener.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java, debezium-core/src/main/java/io/debezium/relational/Attribute.java, debezium-core/src/main/java/io/debezium/relational/AttributeEditor.java, debezium-core/src/main/java/io/debezium/relational/AttributeEditorImpl.java, debezium-core/src/main/java/io/debezium/relational/AttributeImpl.java, debezium-core/src/main/java/io/debezium/relational/NoOpTableEditorImpl.java, debezium-core/src/main/java/io/debezium/relational/Table.java, debezium-core/src/main/java/io/debezium/relational/TableEditor.java, debezium-core/src/main/java/io/debezium/relational/TableEditorImpl.java, debezium-core/src/main/java/io/debezium/relational/TableImpl.java, debezium-core/src/main/java/io/debezium/relational/Tables.java, debezium-core/src/main/java/io/debezium/relational/history/JsonTableChangeSerializer.java, debezium-core/src/test/java/io/debezium/relational/TableEditorTest.java, debezium-core/src/test/java/io/debezium/relational/TableTest.java, debezium-core/src/test/java/io/debezium/relational/history/HistoryRecordTest.java, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.redhat.com/browse/DBZ-5396
So this is an early draft of the connector-specific relational model attribute support I need for DBZ-3401.  I'd prefer to get some early feedback on the approach in case there are some suggestions or preferences we'd like to take before I get too far into the details and incorporate this into DBZ-3401.
**Why is this needed**
I want to move to a situation where `log.mining.strategy` is no longer a requirement.  Instead, the Oracle connector will use the existing `online_catalog` as the default mode of operation, reducing the overhead on the database and increasing the performance for all Oracle users.  
For this mode to work reliably, we need to be able to support resolving the table/column names for LogMiner redo records when LogMiner fails to do …
=> DBZ-5396 Add support for connector-specific relational model attributes

documentation/modules/ROOT/pages/connectors/db2.adoc
https://issues.redhat.com/browse/DBZ-5429
This complements the actual change made for the Db2 connector.
Db2 PR: https://github.com/debezium/debezium-connector-db2/pull/65
=> DBZ-5429: Modify documentation for initial_only flag

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc
Default `max.batch.size` is 2048 [1].
Default `poll.interval.ms` is 500 ms [2] (except Cassandra where it's
still 1000 ms and Mongo which has it's own config)
[1] https://github.com/debezium/debezium/blob/v2.0.0.Alpha3/debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java#L300
[2] https://github.com/debezium/debezium/blob/v2.0.0.Alpha3/debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java#L302
=> [docs] Fix defaut values of `max.batch.size` and `poll.interval.ms`

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSchemaIT.java
https://issues.redhat.com/browse/DBZ-5398
@jpechane @Naros I couldn't find a graceful solution to parse the column name from index definition including a function. Currently, the regex expression just support the function including parameters which split by comma, and the nested function also not be supported as below.
coalesce(coalesce(col1,'1'),'xxx')
=> DBZ-5398 The column is referenced as PRIMARY KEY, but a matching column is not defined in table

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlErrorHandler.java
https://issues.redhat.com/browse/DBZ-5333
This reading byte issue should happen occasionally, the `MySqlErrorHandler` handle following exception message to restart connector is good approach.
`Caused by: java.io.EOFException: Failed to read next byte from position 2005308603`
=> DBZ-5333 Caused by: java.io.EOFException: Failed to read next byte from position 2005308603

documentation/modules/ROOT/partials/modules/tutorial/proc-starting-kafka-connect.adoc
@Naros another one. No link from KC to ZK is needed nowadays.
=> [docs] Removing obsolete ZK reference from tutorial

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbTopicSelector.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TopicSelectorTest.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTopicSelector.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleTopicSelector.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTopicSelector.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerTopicSelector.java, debezium-core/src/main/java/io/debezium/schema/TopicSelector.java
https://issues.redhat.com/browse/DBZ-5457
=> DBZ-5457 Deprecate legacy topic selector for all connectors

documentation/modules/ROOT/partials/modules/tutorial/con-introduction-debezium.adoc
[DBZ-5422](https://issues.redhat.com/browse/DBZ-5422)
While testing the downstream documentation for Debezium 1.9, the build failed because a cross-reference in the upstream `con-introduction.debezium-adoc` file, which is used as-is in the downstream build, uses a format that is incompatible with the downstream build for two reasons:
* The link uses the `xref` macro to link to a book that in the downstream docs is external to the current context. Downstream, such links require use of the `link` prefix. 
* The link target specifies only a general context, but omits use of a specific anchor id, which is required to target content downstream.
I manually fixed this link in the released downstream documentation. This change is necessary to ensure that the link isn't reverted when fetching …
=> DBZ-5422 Update link format and multiple edits

documentation/modules/ROOT/pages/configuration/signalling.adoc
[DBZ-5458](https://issues.redhat.com/browse/DBZ-5458)
Removes `community` conditional delimiters around references to Oracle connector ad hoc and incremental snapshots.
Changes tested in local Antora build, and a local downstream documentation build.
Please backport this change to 1.9. Thanks!
=> DBZ-5458 Remove conditionals surrounding Oracle ad hoc/incremental refs

debezium-core/src/main/java/io/debezium/schema/DefaultRegexTopicNamingStrategy.java
https://issues.redhat.com/browse/DBZ-5471
=> DBZ-5471 Missing the regex properties validation before start connector of DefaultRegexTopicNamingStrategy

debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
https://issues.redhat.com/browse/DBZ-5476
=> DBZ-5476 Fix record accumulator during statistics log entry

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresEventMetadataProvider.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSourceInfoStructMaker.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
During incremental snapshot fields `xmin`, `lsn` and `txId` are not
updated and therefore we stream obsolete values from previous records
in `source` struct. Don't include these obsolete value in the `source`
struct during incremental snapshot.
https://issues.redhat.com/browse/DBZ-4329
=> DBZ-4329 Don't send fileds with obsolete values

COPYRIGHT.txt, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbErrorHandler.java, jenkins-jobs/scripts/config/Aliases.txt
https://issues.redhat.com/browse/DBZ-5479
Debezium connector task is not retried when failover in mongodb 5
I tested mongo debezium connector for failover in mongo 4 and 5.
In case of 4, when failover, the task is retried successfully with MongoSocketOpenException on tail
but, in case of 5, the task is not retried with MongoNodeIsRecoveringException on tail
it looks mongo didn't close socket when primary failover in 5 version like recovery mode.
follow [this doc about the exception](https://mongodb.github.io/mongo-java-driver/3.6/javadoc/com/mongodb/MongoNodeIsRecoveringException.html)
then, we need to retry the exception
v1.8.0.Final
=> DBZ-5479 Retry MongoNodeIsRecoveringException when failover

documentation/modules/ROOT/pages/connectors/db2.adoc
[DBZ-4345](https://issues.redhat.com/browse/DBZ-4345)
Adds entry for `snapshot.include.collection.list` to the Db2 connector properties table.
Tested in local Antora build and local downstream build
=> DBZ-4345 Document snapshot.include.collection.list property for Db2

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorTest.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorTest.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-5497
**Changes**
* Promote truncate skip default from PostgreSQL to core library
* Adjust behavior for Oracle with truncates skipped by default
Sibling PR for Vitess repository - https://github.com/debezium/debezium-connector-vitess/pull/93
=> DBZ-5497 Skip truncate operations by default

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoClients.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnector.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbTaskContext.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoUtil.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSet.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetDiscovery.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSets.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoClientsIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorWithConnectionStringIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ReplicaSetDiscoveryTest.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java, documentation/modules/ROOT/pages/connectors/mongodb.adoc
https://issues.redhat.com/browse/DBZ-4733
Initial support for connection string. The CS is currently used only to retrieve the initial Replica Sets,  once that is done the connector works the same as before. 
Configuration of other connection properties (e.g. ssl, timeouts, etc..) is still kept in separate properties, with he exception of credential (which when provided in connection string is extracted and applied to our client's cluster settings). This needs to be done this way because the configuration can differ for the initial connection and for direct connection to replica sets (for example when SRV protocol is in use with Atlas). 
The PR also 
- consolidates some  connection methods names in ConnectionContext
- Fixes thread safety of MongoClients
- Fixes some incorrect usage of v4 …
=> DBZ-4733: support mongodb connection string 

COPYRIGHT.txt, documentation/modules/ROOT/pages/operations/debezium-server.adoc, jenkins-jobs/scripts/config/Aliases.txt
Add missing value format type `eventclouds`  ([code ref](https://github.com/debezium/debezium/blob/539d9a39588bfecf75513433b2e51f5eaf81571c/debezium-server/debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java#L186)) for debezium-server doc.
=> DBZ-5546 Add missing value format in debezium-server doc

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlBinaryModeIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlFixedLengthBinaryColumnIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBinaryModeIT.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/LogicalDecodingMessageMonitor.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerBinaryModeIT.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Background
* For high-volume processing, Relational Databases typically store UUIDs as binary(16) type. This is usually used as a unique identifier and can be exposed in the URL. Therefore, the Base64 Url Safe Encoding method should be user-selectable.
* Debezium JdbcValueConverters.java support BASE64 BinaryHandlingMode. But it is not url safe.
Purpose
* Support BASE64_URL_SAFE in BinaryHandlingMode 
Jira
* https://issues.redhat.com/browse/DBZ-5544
=> DBZ-5544 Support BASE64_URL_SAFE in BinaryHandlingMode

debezium-server/debezium-server-dist/pom.xml, documentation/modules/ROOT/pages/operations/debezium-server.adoc
DBZ-5122 Include Oracle Debezium Connector in Debezium Server distribution
also checked the lib folder of Debezium Server distribution for duplicate libraries with different version and there is none
=> DBZ-5122 Include Oracle Debezium Connector in Debezium Server distribution

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc
[DBZ-5555 ](https://issues.redhat.com/browse/DBZ-5555)
The `read.only` property for the MySQL connector currently applies to the community version of the connector only, but the property table entry `mysql.adoc` was not conditionalized, with the result that the property is listed in the downstream documentation. 
This change adds a conditional directive to filter the entry for the so that it is not rendered in the downstream documentation.  
I've also updated the ModuleID declarations for the **Connector properties** topics in several of the connector docs for consistency.
Separately, I've updated files in the downstream documentation repository, and will stage those for publishing to update the 1.9 product documentation.
None of these changes are visible …
=> DBZ-5555 Adds conditional to hide read.only property in downstream doc

debezium-connector-oracle/pom.xml, debezium-schema-generator/pom.xml, debezium-schema-generator/src/main/java/io/debezium/schemagenerator/JsonSchemaCreatorService.java
https://issues.redhat.com/browse/DBZ-5229
So rather than meddle with what was done in `debezium-core` and `debezium-storage-xxxx` modules, I've opted to simply check whether the connector exposes a `database.history` property and if so, we inject the Kafka-based history fields back into the schema directly.
While this approach is not compatible with any other storage modules, I also think we have a much larger architecture problem we need to think about and design.  Additionally, at the very least, this mitigates the existing problem for components that are based on the schema generator module for now by restoring previous before as it was prior to DBZ-5229.
=> DBZ-5229 Restore Kafka-based database history options in SchemaGenerator

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbErrorHandler.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlErrorHandler.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresErrorHandler.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresErrorHandlerTest.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java, debezium-core/src/main/java/io/debezium/pipeline/ErrorHandler.java, debezium-core/src/main/java/io/debezium/util/Collect.java
https://issues.jboss.org/browse/DBZ-5244
We've originally decided to retry everything by default. Thinking about that let's try to limit it to set of exceptions that are usually related to communications like IOException, SqlException etc.
=> DBZ-5244 Retry all communication exceptions by default

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/AbstractMessageDecoder.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.redhat.com/browse/DBZ-3007
Introduced the "rate limit" for logging this particular log message at most once in 10 seconds.
=> DBZ-3007: limit 'Streaming requested from LSN' logging

documentation/modules/ROOT/pages/connectors/vitess.adoc
offset.storage.per.task mode allows the vitess connector to launch multiple tasks and have each task persists the offsets in offset storage by task id.
=> DBZ-5382: Add the doc for offset.storage.per.task mode

COPYRIGHT.txt, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/CommitScn.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSourceInfoStructMaker.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/CommitScnTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleOffsetContextTest.java, debezium-core/pom.xml, jenkins-jobs/scripts/config/Aliases.txt
https://issues.redhat.com/browse/DBZ-5439
Hi @thangdc94 I've reworked your PR by addressing the following outstanding items.  To avoid conflicts with your current branch, I've elected to open up this new PR based on my fork instead but with your commits cherry-picked.
1. Fixed your commit with your missing GH email address.
2. Used `TreeSet` rather than `HashSet` to guarantee output order of the formatted string
3. Removed `RS_ID` and `SSN` from the `CommitScn`, they're still part of the source info block, but not in the offsets.
=> DBZ-5439 Add transaction id associate with commit scn

documentation/modules/ROOT/pages/connectors/cassandra.adoc
As requested in https://issues.redhat.com/browse/DBZ-5410, please find the documentation to enable real-time processing in Cassandra 4 connector.
=> DBZ-5410 Added documentation for Cassandra 4 real-time streaming

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java, debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java, debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java, debezium-core/src/main/java/io/debezium/pipeline/source/spi/StreamingChangeEventSource.java
Keep track of partitions offsets being committed belong to in
`BaseSourceTask`. Supply the partition along with the offset in calls to
`commitOffset`.
=> DBZ-5557: Supply partition when comiting offsets with source database

COPYRIGHT.txt, documentation/modules/ROOT/pages/connectors/postgresql.adoc
I've added a note saying that some managed offerings actually replicate the replication slot.
I found this information very critical when evaluating reliability of Debezium. I'll look for links in the docs tomorrow. [Patroni](https://patroni.readthedocs.io/en/latest/) also seems to support this feature.
=> [docs] Note about replication in managed cloud providers

COPYRIGHT.txt, debezium-core/src/main/java/io/debezium/config/Configuration.java
https://issues.redhat.com/browse/DBZ-5561
Unless there is a specific reason to use getClass().getClassLoader() as the default class loader, Thread.currentThread().getContextClassLoader() would be a safer default from the integration perspective with environments that define their own classloading policies.
The original issue was reported in Quarkus [quarkusio/quarkus#27565](https://github.com/quarkusio/quarkus/issues/27565). When a project contains a custom converter implementation, the CommonConnectorConfig in the Debezium core (which is an external project dependency) loading converter classes may fail with a class loading exception. What happens in in this case is Quarkus loads the local project dependencies in a classloader that is higher in the hierarchy than the classloader loading …
=> Use TCCL to load configuration classes by default

documentation/.asciidoctorconfig
This sets some attributes for the preview to make the gap between the IDE and the real site smaller, and to reduce the number of warnings shown in the editor as those attributes are now known to the IDE.
The changes in the `antora.yml` make the `community` attribute a soft-set attribute so that it can be overwritten when writing the docs as needed, for example in an `.asciidoctorconfig` file.
Before: 
After:
=> DBZ-5576 Initial .asciidoctorconfig file to improve editing experience

documentation/modules/ROOT/pages/connectors/mysql.adoc
https://issues.redhat.com/browse/DBZ-5577
=> DBZ-5577 Fix `database.server.id` documentation's default value

documentation/modules/ROOT/pages/configuration/signalling.adoc, documentation/modules/ROOT/pages/configuration/topic-auto-create-config.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/install.adoc, documentation/modules/ROOT/pages/transformations/content-based-routing.adoc, documentation/modules/ROOT/pages/transformations/event-flattening.adoc, documentation/modules/ROOT/pages/transformations/filtering.adoc, documentation/modules/ROOT/pages/transformations/mongodb-event-flattening.adoc, documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc, documentation/modules/ROOT/pages/transformations/topic-routing.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-incremental-snapshot.adoc
This approach updated the `xref:[]`s with the best matching anchor I found. Alternatively, the anchor in the target could have been changed, and I can update this PR if that is preferred. 
After the change, the IntelliJ AsciiDoc plugin doesn't report any more broken anchors.
To test his, I used version 0.37.49 of the IntelliJ AsciiDoc plugin.
=> DBZ-5618 fix broken anchors in the docs

documentation/.asciidoctorconfig
This adds the necessary configuration to have the preview styled like the website for the Antora based documentation. 
Pre-requisites: 
* PR https://github.com/debezium/debezium.github.io/pull/830 merged
* AsciiDoc plugin for IntelliJ updated to 0.37.49 or later
* JCEF preview activated in the AsciiDoc plugin's settings (should be the default for new installations of the plugin)
Then the preview will change for example for `mysql.adoc` as follows:
Compared to the [original page](https://debezium.io/documentation/reference/2.0/connectors/mysql.html):
=> DBZ-5616 Use website's stylesheet for the preview

debezium-embedded/src/main/java/io/debezium/embedded/ConvertingEngineBuilder.java, debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java
Running this test with the system property set -Dfile.encoding=ASCII will still succeed.
Running this test with the system property set -Dfile.encoding=ASCII without the fix you can see it fail.
=> DBZ-4213 Use UTF-8 encoding when creating new Strings

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnector.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectionIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
If the SQL Server connector is configured to capture changes from a single database, pass it to the JDBC connection string in order to bypass the limitation of Azure SQL which does not allow switching between databases within a single connection.
See the [documentation](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/use-transact-sql?view=sql-server-ver15#arguments) for more details.
All the tests that use the default configuration (the majority of them) will now use the single-database connection, so no additional tests should be necessary.
UPD: we can actually test that if the connection is passed a single database, it is the current database. Otherwise, `master` should be the current database (which will hold true unless overridden for the Debezium login, i.e. reliable …
=> DBZ-5496: Improve compatibility with Azure SQL

documentation/modules/ROOT/pages/connectors/cassandra.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc
[DBZ-3327](https://issues.redhat.com/browse/DBZ-3327) 
Low impact change to certain connector configuration properties tables that inserts the string `No default` when a cell in the **Default**  column of an entry is empty.
=> Dbz 3327 populate empty default value cells in connector properties tables

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/DefaultValueParserListener.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDefaultValueTest.java
Besides single quotes for string literals, MySQL allows double quotes.
=> DBZ-5630: Unquote double quotes from default values on MySQL

COPYRIGHT.txt, documentation/modules/ROOT/pages/connectors/mysql.adoc
with regards to conversation on [zulip](https://debezium.zulipchat.com/#narrow/stream/302529-users/topic/Debezium.20missing.20update.20events)
`binlog_row_value_options=PARTIAL_JSON` might cause missing UPDATE events on mysql connector in such cases user should validate variable is unset
=> [docs] update mysql setup docs - binlog_row_value_options

COPYRIGHT.txt, debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4, debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql, debezium-ddl-parser/src/test/resources/mysql/examples/dml_select.sql, jenkins-jobs/scripts/config/Aliases.txt
[DBZ-5650](https://issues.redhat.com/browse/DBZ-5650)
From MariaDB 10.1.2, pre-query variables are supported
src: https://mariadb.com/kb/en/set-statement/
=> DBZ-5650 Support set statement in mariadb

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
Fix randomly failing
SqlServerConnectorIT#updatePrimaryKeyWithRestartInMiddle.
It seems the main source of instability in slow environments is consuming snapshot record. It's actually not consumed and as the test assumes exact order of messages, it leads to failures.
Wait for snapshot to be completed using mbean server. Also add more asserts to make clear where is the issue if the test continues to fail.
https://issues.redhat.com/browse/DBZ-4490
=> DBZ-4490 Fix randomly failing updatePrimaryKeyWithRestartInMiddle test

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumContainer.java
Reasoning: There original strategy is scrapping logs, but there is a race between "Session key updated" being logged and Kafka Connect REST interface being up. Hence, on slow machines the KC REST `/connectors` interface was occasionally replying with HTTP 404.
=> DBZ-5651 More reliable wait strategy for DebeziumContainer 

debezium-connector-mongodb/pom.xml, debezium-connector-mysql/pom.xml, debezium-connector-oracle/pom.xml, debezium-connector-postgres/pom.xml, debezium-connector-sqlserver/pom.xml, debezium-parent/pom.xml
Allow docker maven plugin external properties to override default or ones specified in `pom.xml`. Also bump docker maven plugin to avoid bug related to multiple images one pom file.
https://issues.redhat.com/browse/DBZ-5657
https://issues.redhat.com/browse/DBZ-5658
=> Bump docker maven plugin version and allow to use external properties

documentation/modules/ROOT/pages/connectors/cassandra.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-5625](https://issues.redhat.com/browse/DBZ-5625)
Adds information to property descriptions to explain that the regular expressions that the connector uses to match various identifiers (table names, schema names, column names, etc) are evaluated as anchored regular expressions.
Also edits property descriptions across connectors for consistency.
=> Dbz 5625 specify use of anchored regex for include and exclude properties

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldExcludeListIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FieldRenamesIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/IncrementalSnapshotIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/TopicNameSanitizationIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SpecialCharsInNamesIT.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, debezium-core/src/main/java/io/debezium/transforms/ByLogicalTableRouter.java, debezium-embedded/src/main/java/io/debezium/embedded/ConvertingEngineBuilder.java, debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/ConnectorConfigBuilder.java, debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java, documentation/modules/ROOT/pages/configuration/avro.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc, documentation/modules/ROOT/pages/integrations/cloudevents.adoc, documentation/modules/ROOT/pages/transformations/topic-routing.adoc
=> DBZ-5541: Default Debezium schema.name.adjustment.mode to "none"

documentation/modules/ROOT/pages/connectors/mongodb.adoc
`oplog` option was removed in 707eeab3d8c4a3c9 and is not available in 2.x any more. Remove it from Mongo connector documentation.
=> [docs] Remove oplog capture mode from MongoDB documentation

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/KafkaSignalThread.java, debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java, debezium-core/src/main/java/io/debezium/util/Throwables.java, debezium-core/src/test/java/io/debezium/kafka/KafkaCluster.java, debezium-server/debezium-server-redis/src/main/java/io/debezium/server/redis/RedisSchemaHistory.java, debezium-storage/debezium-storage-file/src/main/java/io/debezium/storage/file/history/FileSchemaHistory.java, debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java
Looks like the connector logs records at certain points which may contain sensitive user information. 
This PR aims to prevent records from being logged at all logging levels.
No tests required.
=> DBZ-5612 Remove records from being logged at all levels

debezium-embedded/src/main/java/io/debezium/connector/simple/SimpleSourceConnector.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java, debezium-embedded/src/test/java/io/debezium/connector/simple/SimpleSourceConnectorOutputTest.java, debezium-embedded/src/test/resources/simple/test/f/connector.properties, debezium-embedded/src/test/resources/simple/test/f/env.properties, debezium-embedded/src/test/resources/simple/test/f/expected-records.json, debezium-embedded/src/test/resources/simple/test/g/connector.properties, debezium-embedded/src/test/resources/simple/test/g/env.properties, debezium-embedded/src/test/resources/simple/test/g/expected-records.json, documentation/modules/ROOT/pages/development/engine.adoc
This is a re-make of this older pull request: https://github.com/debezium/debezium/pull/3268
I have one comment, related to the errors.max.retries property. Value of 0 means the mechanism is disabled and it is equivalent to the old behavior, which was swallowing the RetriableException in EmbeddedEngine.
=> DBZ-4629 Debezium server crashes when no connection to the source db

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresEventDispatcher.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/pipeline/txmetadata/PostgresTransactionMonitor.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TransactionMetadataIT.java, debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java, debezium-core/src/main/java/io/debezium/pipeline/txmetadata/TransactionMonitor.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java, documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-5329
=> Add LSN into Postregs transaction ID

COPYRIGHT.txt, documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc
https://issues.redhat.com/browse/DBZ-5715
For the MongoDB Outbox Event router the property:
`transforms.outbox.table.fields.additional.placement` doesn't works because the Mongo event router looks to the property `transforms.outbox.collection.fields.additional.placement` to expose additional fields.
=> DBZ-5715 MongoDB router uses collection not table in names

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-5735](https://issues.redhat.com/browse/DBZ-5735)
In preparation for downstream GA, removes TP designation from RAC content in Oracle connector docs.
Please backport this change to 1.9.7.
=> DBZ-5735 Promote Oracle RAC content to GA by removing TP admonitions

documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-5352
Note when backporting to 1.9, the `schema.history.internal.` prefix needs to be changed to `database.history.`.
=> DBZ-5352 Clarify table eligibility rules for schema history topic

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlChangeRecordEmitter.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDatabaseSchema.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, debezium-core/src/main/java/io/debezium/schema/SchemaChangeEvent.java, documentation/modules/ROOT/pages/connectors/cassandra.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc
https://issues.redhat.com/browse/DBZ-5610
The truncate command sample data of table topic as below:
key: null
value:
`
{
"before": null,
"after": null,
"source": {
"version": "2.0.0-SNAPSHOT",
"connector": "mysql",
"name": "test_avro",
"ts_ms": 1665304468000,
"snapshot": {
"string": "false"
},
"db": "workdb",
"sequence": null,
"table": {
"string": "dbz5236"
},
"server_id": 112233,
"gtid": null,
"file": "mysql-bin.000035",
"pos": 125109,
"row": 0,
"thread": null,
"query": null
},
"op": "t",
"ts_ms": {
"long": 1665304468970
},
"transaction": null
}`
=> DBZ-5610 MySQL Connector capture TRUNCATE command as message in table topic

documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-incremental-snapshot-metrics.adoc
[DBZ-5748](https://issues.redhat.com/browse/DBZ-5748)
Deletes from the shared snapshot metrics file an incremental snapshots Tech Preview note that was intended for removal when the feature was promoted to GA in the previous 2022.Q3 downstream release .  A[ separate commit in the downstream docs repo ](https://gitlab.cee.redhat.com/red-hat-integration-documentation/integration/-/merge_requests/993)removes the note from the published downstream documentation.
=> DBZ-5748 Remove note that refers to incremental snapshots as TP feature

debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/databases/sqlserver/OcpSqlServerController.java
https://issues.redhat.com/browse/DBZ-5763
This is fix for ocp connections, for test-containers it needs further investigation
=> DBZ-5763 disabling connection encryption for SqlServer connections 

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java
See [DBZ-5777](https://issues.redhat.com/browse/DBZ-5777).
I only noticed the changes from https://github.com/debezium/debezium/pull/3824 while rebasing this patch from our internal `1.9.5` branch to `main`. If this change is non-essential or too disruptive for `1.9`, please feel free to discard it.
=> DBZ-5777: Restart SQL Server task on "Cannot continue the execution because the session is in the kill state."

debezium-quarkus-outbox/runtime/pom.xml, debezium-server/debezium-server-pravega/pom.xml, pom.xml
https://issues.redhat.com/browse/DBZ-5774
In regards to the upstream PR requirements of https://github.com/quarkusio/quarkus-platform/pull/673
=> DBZ-5774 Upgrade to Quarkus 2.14.CR1

COPYRIGHT.txt, documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc, documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc, jenkins-jobs/scripts/config/Aliases.txt
Updated all references from `ByteBufferConverter` to `BinaryDataConverter`.
Also added special note about changing the settings before upgrading when running in Kafka Connect (otherwise Kakfa Connect will fail to start).
=> DBZ-5770: Update documentation regarding the Binary Data Converter

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-5757](https://issues.redhat.com/browse/DBZ-5757)
Adds missing steps to examples for creating YAML to build custom Kafka Connect container images for each of the downstream connectors. This change has no bearing on the community version of the documentation. 
The change also replaces the callout legends that follow the Kafka Connect YAML file and KafkaConnect resource examples with tables. to workaround the customer portal rendering problem that results in multiple entries for each numbered item.
Please backport this change to 1.9
=> DBZ-5757 Updates downstream steps to build KC custom container images

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
`ALWAYS` should mean always and also this should be in line with Postgres `ALWAYS` option.
https://issues.redhat.com/browse/DBZ-5626
=> DBZ-5626 Do the snapshot also in case of schema history errors

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbTaskContext.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbTaskContextTest.java
https://issues.redhat.com/browse/DBZ-5629
Root cause of the issue seems to be the use of default task ID. This in turn leads to the same name of the mbean for each task.
=> DBZ-5629 Correctly setting task id for MongoDbTaskContext

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/ReplicationConnectionIT.java
https://issues.redhat.com/browse/DBZ-5800
This is not a fix but it disables the test to unblock CI. The issue does not exhibit locally nor on CI when only a subset of tests is executed. We can try to re-eable the tests sometimes in future.
=> DBZ-5800 Disable test failing on CI

COPYRIGHT.txt, debezium-parent/pom.xml, jenkins-jobs/scripts/config/Aliases.txt
The removed plug-in version properties are duplicates of the same properties in parent POM debezium-build-parent and should not be needed.
There are some plug-in version properties still in debezium-parent that are duplicated by name from debezium-build-parent, but differ in version. I wasn't comfortable removing those without further direction as it would change the version of the plug-in in debezium-parent. I also checked all other POMs that are parented to debezium-build-parent and did not find any other duplicates like this. Local `./mvnw clean verify -DskipITs` build is passing. I'm having issues running integration tests locally and still troubleshooting that.
=> DBZ-4669 Remove duplicate plug-in version properties from debezium-parent POM

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
While `ALWAYS` mode allows also snapshot on schema error, it allows snapshot also on other ocassions. Don't throw exception when offset is missing and schema is set to `ALWAYS`.
https://issues.redhat.com/browse/DBZ-5626
=> DBZ-5626 Don't check ofsset for AWLAYS mode

debezium-connector-mongodb/pom.xml, debezium-connector-mysql/pom.xml, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDecimalIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java, debezium-connector-oracle/pom.xml, debezium-connector-postgres/pom.xml, debezium-connector-sqlserver/pom.xml, debezium-core/pom.xml, debezium-core/src/test/java/io/debezium/data/VerifyRecord.java, debezium-embedded/pom.xml, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
Run tests with Apicurio registry. Create separate profile which, if activated, starts Apicurio registry container. If the Apicurio registry is available, use it in the tests instead of in-memory Confluent registry. Otherwise fall back to Confluent registry.
https://issues.redhat.com/browse/DBZ-2131
=> Run tests with Apicurio

documentation/modules/ROOT/pages/connectors/db2.adoc
[DBZ-5504](https://issues.redhat.com/browse/DBZ-5504)
Replaces #3795, because the original branch had grown too stale. 
Removes invalid `MONEY`, `SMALLMONEY`, `DATETIME2`, and `SMALLDATETIME` entries from the table in _Data type mappings_ section, including the following  `DATETIME2` entries:
>
|`DATETIME2(0)`, `DATETIME2(1)`, `DATETIME2(2)`, `DATETIME2(3)`
|`INT64`
|`io.debezium.time.Timestamp` +
+
Represents the number of milliseconds since the epoch, and does not include timezone information.
|`DATETIME2(4)`, `DATETIME2(5)`, `DATETIME2(6)`
|`INT64`
|`io.debezium.time.MicroTimestamp` +
+
Represents the number of microseconds since the epoch, and does not include timezone information.
|`DATETIME2(7)`
|`INT64`
|`io.debezium.time.NanoTimestamp` + 
In the paragraph in the _Timestamp types_ …
=> Dbz 5504 remove invalid datatypes from db2 connector doc

documentation/modules/ROOT/pages/connectors/postgresql.adoc
Hey @jpechane, just noticed this inconsistency in the docs. The actual default is [500ms indeed](https://github.com/debezium/debezium/blob/c781832f41b34461c601879f22e8b0089cce7067/debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java#L310).
=> [docs] Updating default poll.intervall.ms in PG connector docs

documentation/modules/ROOT/pages/connectors/postgresql.adoc
[DBZ-5789](https://issues.redhat.com/browse/DBZ-5789)
Removes the obsolete **Meta Information** section from the PostgreSQL connector documentation.
=> DBZ-5789 Remove obsolete info about PG metadata from doc

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.redhat.com/browse/DBZ-5423
=> DBZ-5423 Add test case to support table rename for SQLServer

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-5833
Current issue is that it logs tons and tons of log data at DEBUG level when knowing that other tables had changes is not helpful.
I need debug level on this class to get other useful data
=> AbstractLogMinerEventProcessor DEBUG to TRACE loglevel

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/StreamingSourceIT.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnector.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java, debezium-embedded/src/main/java/io/debezium/connector/simple/SimpleSourceConnector.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java, debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java, debezium-server/debezium-server-core/src/main/java/io/debezium/server/ConnectorLifecycle.java, debezium-server/debezium-server-kafka/src/test/java/io/debezium/server/kafka/KafkaIT.java, debezium-server/debezium-server-pulsar/src/test/java/io/debezium/server/pulsar/PulsarIT.java, debezium-server/debezium-server-redis/src/main/java/io/debezium/server/redis/RedisStreamChangeConsumer.java, debezium-server/debezium-server-redis/src/main/java/io/debezium/server/redis/RedisStreamChangeConsumerConfig.java, debezium-server/debezium-server-redis/src/test/java/io/debezium/server/redis/RedisSchemaHistoryIT.java, debezium-storage/debezium-storage-file/src/main/java/io/debezium/storage/file/history/FileSchemaHistory.java, debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/RedisCommonConfig.java, debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/history/RedisSchemaHistory.java, debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/history/RedisSchemaHistoryConfig.java, debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/offset/RedisOffsetBackingStore.java, debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/offset/RedisOffsetBackingStoreConfig.java
The first commit implements configuration validation for the connector.
The second commit implements configuration validation for Redis sink, offset storage and schema history. If this looks fine, it could be implemented for all other sinks and storages.
=> DBZ-4720 Validate Debezium Server configuration properties

COPYRIGHT.txt, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/WalPositionLocator.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DebeziumEngineIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/ReplicationConnectionIT.java
closes https://issues.redhat.com/projects/DBZ/issues/DBZ-5739
Detect replication slot recreation and fail the connector if we can't seek to the last known offset. We use the function `pg_replication_slot_advance` to seek to a specific location, which is available from Postgres 11 onwards.
=> DBZ-5739 Postgres connector results in silent data loss if replication slot is recreated

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
With the separate `forEach` loop used for logging before, we'll only get to see the columns in the log if they all could be created. If something goes wrong before and an exception is raised, no information will be logged at all, also for those columns which could be created before.
https://issues.redhat.com/browse/DBZ-5874
=> DBZ-5874 Making sure trace message gets logged

debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java
https://issues.redhat.com/browse/DBZ-5855
- The PR only removes "end offset was modified" check as it doesn't fit multi task model and may cause issues. 
- The PR doesn't introduce / suggest any alternative
=> DBZ-5855: IllegalStateException is thrown if task is recovering while other tasks are running

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
Certain versions of RDS Postgres (e.g. RDS Postgres 12.3) are returning the following error when using the `pg_replication_slot_advance()` even though the user has superuser or replication roles. Since we can't use the function on these versions, catch and ignore these errors when validating the replication slot. This function works on RDS Postgres 12.5 for the same user.
```
ERROR:  must be superuser or replication role to use replication slots 
```
=> DBZ-5739 Handle permission error from RDS Postgres

documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-db2-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-oracle-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/shared-deploy-kafka-connect-yaml.adoc
[DBZ-5883](https://issues.redhat.com/browse/DBZ-5883)
Appends missing build number string to Maven URL for the Debezium scripting archive to YAML example in the  instructions for using Streams to deploy connectors.
Also implements new downstream attributes for assigning the  build number for the Debezium release and for the Apicurio registry release.
This change is targeted solely at the downstream product version of the documentation and has no effect on the community version of the documentation.
A separate change to implement this correction was merged to the downstream documentation repository.
=> DBZ-5882 Fix Debezium scripting archive url in downstream deploy example

documentation/modules/ROOT/pages/connectors/mongodb.adoc
[DBZ-5812](https://issues.redhat.com/browse/DBZ-5812)
Updates the description of the `snapshot.mode` property to remove incorrect references to the behavior of the `initial` option. Also revises the common problems topic about failures after a connector is stopped for an extended interval.
=> Dbz 5812 inconsistent documentation about mongodb snapshot.mode behavior

debezium-connect-rest-extension/pom.xml, debezium-connector-mongodb/pom.xml, debezium-connector-mysql/pom.xml, debezium-connector-oracle/pom.xml, debezium-connector-postgres/pom.xml, debezium-connector-sqlserver/pom.xml, debezium-parent/pom.xml, debezium-quarkus-outbox/integration-tests/pom.xml, debezium-server/debezium-server-core/pom.xml, debezium-server/debezium-server-eventhubs/pom.xml, debezium-server/debezium-server-http/pom.xml, debezium-server/debezium-server-kafka/pom.xml, debezium-server/debezium-server-kinesis/pom.xml, debezium-server/debezium-server-nats-jetstream/pom.xml, debezium-server/debezium-server-nats-streaming/pom.xml, debezium-server/debezium-server-pravega/pom.xml, debezium-server/debezium-server-pubsub/pom.xml, debezium-server/debezium-server-pulsar/pom.xml, debezium-server/debezium-server-redis/pom.xml, debezium-testing/debezium-testing-system/pom.xml
Run the tests alwyas in thr same order to make it more easy to debug failures. If needed, the order can be changed (e.g. to `random`) by overriding propeperty `runOrder`.
https://issues.redhat.com/browse/DBZ-5889
=> DBZ-5889 Run integration tests in specified order

documentation/modules/ROOT/pages/connectors/mongodb.adoc
This reverts commit 4dba1503a7da96f84f6bb9b6ae7e0477223bae84 which wasn't supposed to be backported to 1.9
=> [docs] Revert "DBZ-5817 removing mongodb.name references from docs"

documentation/modules/ROOT/pages/connectors/cassandra.adoc, documentation/modules/ROOT/pages/install.adoc
[DBZ-5922](https://issues.redhat.com/browse/DBZ-5922)
Removes note stating that the Cassandra connector is in an incubating state. 
Also includes minor edits for formatting and language.
=> Dbz 5922 remove cassandra incubating notes

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
`PostgresConnection.getAllTableIds(String)` method was added to unify getting all tables in database catalog, including partitioned tables.
https://issues.redhat.com/browse/DBZ-5949
=> DBZ-5949 Support partitioned tables when updating PG publication

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotChangeEventSource.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoUtil.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoUtilIT.java
https://issues.redhat.com/browse/DBZ-4339
So far this PR does several things
- Generalises `MongoPrimary` to `MongoPreferredNode`
- Oplog positions are read from primary to get latest data (However this can easily be configurable as oplog[ can be read from secondary](https://www.mongodb.com/docs/manual/core/replica-set-oplog/)) 
- Collection names are read from primary as well 
- The actual data reading (event construction) in snapshot is performed against secondary
- Change stream is opened against secondary 
What is missing
- `MongoDbIncrementalSnapshotChangeEventSource` still uses primary 
-  When secondary which is being used to stream changes is promoted to primary the event stream is not recreated
This also needs to be tested somehow against a real replica set (what we have in tests …
=> DBZ-4339 MongoDB connector to prefer secondaries

debezium-connector-oracle/pom.xml, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/logwriter/ReadOnlyLogWriterFlushStrategy.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/junit/SkipOnReadOnly.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/junit/SkipTestDependingOnReadOnly.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/FlushStrategyIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-3866
This explicitly removes the writing of the flush table to support read-only logical standby connections with LogMiner only.  I have configured the option for triggering read-only to be internal, `internal.log.mining.read.only`, as this is highly experimental.
=> DBZ-3866 Add internal read-only LogMiner support

debezium-core/src/main/java/io/debezium/transforms/partitions/ComputePartition.java, debezium-core/src/main/java/io/debezium/transforms/partitions/ComputePartitionConfigDefinition.java, debezium-core/src/main/java/io/debezium/transforms/partitions/ComputePartitionException.java, debezium-core/src/test/java/io/debezium/transforms/partitions/ComputePartitionTest.java
- Fix negative partition number in ComputePartition SMT
- Improved check on configuration consistency to avoid 0 as the partition number.
=> DBZ-5967: Fix negative partition number in ComputePartition SMT

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryTransaction.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-5907
This PR correctly performs transaction event undo by only reversing the last event in the transaction event queue that matches the row-id, rather than undoing all events with the same row-id.
@jpechane I would suggest we consider backporting this to 2.0 and/or 2.1.
=> DBZ-5907 Fix Oracle transaction event undo

COPYRIGHT.txt, debezium-bom/pom.xml, documentation/modules/ROOT/pages/integrations/testcontainers.adoc
The container needs to be marked as a compatible substitute for the official postgres image. 
Otherwise, with recent versions of testcontainers, the postgres container will fail to initialise with: 
```Failed to verify that image 'debezium/postgres:11' is a compatible substitute for 'postgres'.```
=> [docs] Update the postgres container initialisation example

COPYRIGHT.txt, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorConfigTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorConfigTest.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, jenkins-jobs/scripts/config/Aliases.txt
Add support for `incremental.snapshot.isolation.mode` for Postgres, Oracle, and MySQL connectors and set isolation mode based on this new connector config value during the incremental snapshot if it's not set then use the default translation level
https://issues.redhat.com/browse/DBZ-3653
=> [DBZ-3653] Set Transaction Isloation mode for incremental snapshot

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDatabaseSchema.java
The warning message emitted when the Debezium Connector for MySQL encounters an unparseable DDL statement contains a superfluous placeholder.
Refs https://issues.redhat.com/browse/DBZ-5993
=> DBZ-5993 Remove superfluous placeholder in log message (MySqlDatabaseSchema)

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
This fixes the NPE which arises when we try to send a `execute-snapshot` signal with an invalid table name (rather than schema.table only give table). This only happens in the case of using `exclude.tables` config.
The fix for this is to check that the schema name and table name are not null before applying the lowercase operation on them.
=> DBZ-5988:Impose null check on schema value prior to any operation

COPYRIGHT.txt, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDefaultValueTest.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlValueConvertersTest.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java, debezium-core/src/main/java/io/debezium/time/ZonedTimestamp.java, jenkins-jobs/scripts/config/Aliases.txt
For bug reports, provide this information, please:
Connector: MySqlSourceConnector
Version: 1.9.7.FINAL
time.precision.mode is default.
MySql 8.0.30 Source distribution
AWS RDS.
Database has field with type as timestamp(6). When debezium produces the field's value to kafka, it truncates any leading zeros there might be in the nano/microsecond part. If the value contains only zeros in the nano/microsecond part, then the whole part is excluded.
For ex.
2023-01-11 12:30:00.123123 --> 2023-01-11T12:30:00.123123Z
2023-01-11 12:30:00.123000 --> 2023-01-11T12:30:00.123Z
2023-01-11 12:30:00.000000 --> 2023-01-11T12:30:00Z
This breaks the sink connectors which expect the date time type to be in the format yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'. 
Expected was that the leading zeros should not get …
=> DBZ-5996 Debezium truncating micro/nanosecond part if it is all zeros

.github/workflows/debezium-workflow.yml, debezium-bom/pom.xml, debezium-storage/debezium-storage-s3/pom.xml, debezium-storage/debezium-storage-s3/src/main/java/io/debezium/storage/s3/history/S3SchemaHistory.java, debezium-storage/debezium-storage-tests/pom.xml, debezium-storage/debezium-storage-tests/src/test/java/io/debezium/storage/s3/history/S3SchemaHistoryIT.java, debezium-storage/pom.xml
This implementation provides caching `HistoryRecord` on the main memory.
Since S3 does not support Append operation on the object level, `S3SchemaHistory#start()` fetches history log
from S3 first and store the `HistoryRecord`'s  on the main memory. 
Also `S3SchemaHistory#storeRecord(HistoryRecord)` creates new history object every time invokes on S3.
S3 Object keys created names after the `Thread` that creates `DatabaseHistory` object.
=> DBZ-5402: debezium-storage-s3 module

documentation/modules/ROOT/pages/transformations/mongodb-event-flattening.adoc
[DBZ-5975](https://issues.redhat.com/browse/DBZ-5975)
Brings the MongoDB version of the SMT level with the SQL-based version by removing the statement that implies that the SMT is still incubating. 
=> DBZ-5975 Remove note that indicates SMT is under active development.

documentation/modules/ROOT/pages/connectors/vitess.adoc
Vitess connector finally supports the snapshot feature.
And the snapshot.mode specifies the criteria for performing a snapshot when the connector starts.
=> DBZ-5930: Add the doc for vitess snapshot.mode

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SnapshotSourceIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java, debezium-core/pom.xml, debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java, debezium-core/src/test/java/io/debezium/connector/common/BaseSourceTaskTest.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
Reworked when task requests start from subclasses
Add support for restarting
=> DBZ-5879 Support retrying database connection failures during connector start

COPYRIGHT.txt, documentation/modules/ROOT/pages/connectors/mysql.adoc, jenkins-jobs/scripts/config/Aliases.txt
The configuration `event.processing.failure.handling.mode` property is not present in the documentation but I see it is present in the common configuration in code - https://sourcegraph.com/github.com/debezium/debezium/-/blob/debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java?L400
This PR adds the configuration to the documentation
=> DBZ-4829 : Update mysql.adoc

COPYRIGHT.txt, debezium-server/debezium-server-pulsar/src/main/java/io/debezium/server/pulsar/PulsarChangeConsumer.java, documentation/modules/ROOT/pages/operations/debezium-server.adoc
To address Jira https://issues.redhat.com/browse/DBZ-6033
This PR supports non-default Pulsar tenant and namespace in Debezium Server. 
In Pulsar, a topic without tenant/namespace implicitly defaults the public tenant and the default namespace. This is what the current implementation is. This feature is required for Pulsar's multiple tenant deployment, so that the debezium server can produce messages to non-default tenant and namespaces.
=> DBZ-6033 dbz-server-pulsar support non-default tenant and namespace

debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc
Additionally, update the documentation to reflect the actual default value: https://github.com/debezium/debezium/blob/48136e08c3f23257523c97dcec668e69463a715e/debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java#L145-L147
=> DBZ-6039: Reset history recovery attempt counter upon success

.github/dependabot.yml, .github/workflows/debezium-workflow.yml
* Updating `changed-files` version will hopefully fix issue with `Argument list too long` (e.g. [here](https://github.com/debezium/debezium/actions/runs/4017138191/jobs/6901095978)).
* Setup dependency bot for github actions as current `changed-files` is very old and nobody probably noticed it
=> [CI] update changed-files version and setup dependency bot

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/IncrementalSnapshotWithRecompileIT.java
Override no-op `waitForCdcTransactionPropagation()` also in `IncrementalSnapshotWithRecompileIT` which also fails very often.
https://issues.redhat.com/browse/DBZ-6035
=> DBZ-6035 Await transactions also in IncrementalSnapshotWithRecompileIT

documentation/modules/ROOT/pages/connectors/vitess.adoc
Add doc for the new `bigint.unsigned.handling.mode`
=> DBZ-6043: Vitess: Support Mapping unsigned bigint mysql column type to long

COPYRIGHT.txt, documentation/modules/ROOT/pages/connectors/mysql.adoc, jenkins-jobs/scripts/config/Aliases.txt
It is necessary to query for server_id instead of server-id, which is being used on the config file.
=> [docs] Variable name clarified

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java
https://issues.redhat.com/browse/DBZ-6064
Also double checked the usage of ``connectionSeed()`` method, it's now not used in any logs.
=> DBZ-6064 masking sensitive information in connection string on close

documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-6069](https://issues.redhat.com/browse/DBZ-6069)
Update connector files to remove or update links that could not be resolved in the downstream version of the docs.
Tested in a local Antora build (no effect on the community version of the doc) and a local downstream build.
Please backport this change to 2.1.
=> DBZ-6069 Remove problematic links

debezium-core/src/main/java/io/debezium/transforms/tracing/ActivateTracingSpan.java
Change txLogSpan to use processingTimestamp for span finish.
=> DBZ-5827 ActivateTracingSpan wrong timestamps reported

documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://www.postgresql.org/message-id/CAJ3gD9fE%3D0w50sRagcs%2BjrktBXuJAWGZQdSTMa57CCY%2BDh-xbg%40mail.gmail.com is encoded and works.
The link is currently broken because `@` generate a `mailto:` link. See page https://debezium.io/documentation/reference/2.1/connectors/postgresql.html#postgresql-when-things-go-wrong
=> postgresql doc: fix link to PG List

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-6094
It's possible the connector sees "empty transactions" where we have a START and a matching COMMIT/ROLLBACK, but all the DML operations within the transaction were filtered out due to the include/exclude filters.  In this case, there is no reason to log information about that transaction being skipped and this should help reduce the frequency of this message after a connector restart where there is a large number of transactions with no relevant DML events.
=> DBZ-6094 Reduce frequency of "Transaction already processed" debug message

COPYRIGHT.txt, documentation/modules/ROOT/pages/operations/debezium-server.adoc, jenkins-jobs/scripts/config/Aliases.txt
The recent extraction of debezium-server to its own repo left behind a broken link.
=> DBZ-6111 Fix docs link to debezium-server Kinesis sink

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-6107
This PR now enforces additional checks in `TransactionCommitConsumer` when two UPDATE events are read from the event stream for the same table within the same transaction.  We can determine whether this subsequent UPDATE is synthetic by examining the columns manipulated in the `SET` clause.  If none are LOB columns, the event is treated like a standalone UPDATE event.  If they're LOB columns, the event is considered mergeable and is handled as such.
This PR includes a test where `lob.enabled=true` is set, and we do bulk updates on a table that has no LOB columns, as well as another test where again `lob.enabled=true` and we are doing various update operations against this table, including setting the LOB column to `NULL`.
=> DBZ-6107 Fix bulk updates when LOB is enabled

documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/transformations/event-flattening.adoc, documentation/modules/ROOT/pages/transformations/mongodb-event-flattening.adoc
[DBZ-6006](https://issues.redhat.com/browse/DBZ-6006)
Edits to prepare the SMT doc for downstream use. Includes changes to related content in the doc for the  SQL-based version of the SMT and the MongoDB connector doc. 
Tested in local Antora build and local downstream build.
The downstream build initially failed due to unrelated linking errors present in the Oracle, PG, and SQL Server connector files. I'll open a separate issue to fix those problems.
Please backport this change to 2.1.
=> DBZ-6006 prepare mongodb extract new document state smt doc for use downstream

COPYRIGHT.txt, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, jenkins-jobs/scripts/config/Aliases.txt
=> DBZ-6123 fix typo "evemts" to "events" in docs.

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
https://issues.redhat.com/browse/DBZ-6125
**Description:**
DBZ-5648 introduced a regression where transaction start, commit, and rollback events were only being read from within the scope of the configured PDB that the connector was capturing changes instead of the entire Oracle database. This can lead to situations where the offsets may not be advanced as quickly in a low traffic PDB environment, potentially causing stale offsets.
=> DBZ-6125 Fix potential stale offsets when using PDBs

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotChangeEventSource.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/IncrementalSnapshotIT.java, documentation/modules/ROOT/pages/connectors/mongodb.adoc
https://issues.redhat.com/browse/DBZ-6116
follow up PR on https://github.com/debezium/debezium/pull/4239
@jcechace @jpechane
=> DBZ-6116: Support String type for key in Mongo incremental snapshot

COPYRIGHT.txt, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ConnectionContext.java
This change respects current max attempts but avoids possible negative attempts (current behaviour): 
`Error while attempting to connect to primaryPreferred node of '###' after attempt #17 (-1 remaining)`
Also adjusts incorrect max reconnection attempts (was [actual max attempts]+1)
=> DBZ-6113: Fix negative remaining reconnect attempts

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
Also remove deprecated unused method for handling `SNAPSHOT_MODE_TABLES` option.
https://issues.redhat.com/browse/DBZ-3594
=> DBZ-3594 Warn when obtaning table schema which should be alread present

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactory.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Filters.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetOffsetContext.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ResumeTokens.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactoryTest.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java, documentation/modules/ROOT/pages/connectors/mongodb.adoc
This change migrates from doing client-side filtering of streaming change events to performing it server-side via MongoDB's support for aggregation pipelines. This can drastically cut down on the amount of data sent between the client and server. In addition, a new approach to heartbeating has been added which relies on the `postBatchResumeToken` to advance the the cursor even when no changes occur on the pipeline.
=> DBZ-5201: Add support for server-side filtering of replica set change streams

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactory.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactoryTest.java
Idea is to remove unnecessary processing in the aggregation pipeline, to generally simplify the code and make it easier to understand when viewing a pipeline. See Jira for additional details.
=> DBZ-6152: Remove hardcoded list of system database exclusions that are not required for change streaming

documentation/modules/ROOT/pages/transformations/event-flattening.adoc, documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc, documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc, documentation/modules/ROOT/pages/transformations/topic-routing.adoc
[DBZ-6130](https://issues.redhat.com/browse/DBZ-6130)
Updates SMT docs to refer to adding SMTs settings via the connector configuration rather than via `.properties` files.
=> DBZ-6130 Remove references to using properties files to configure SMTs

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-6073](https://issues.redhat.com/browse/DBZ-6073)
Fixes overlapping/embedded conditionals in the Oracle connector deployment doc and removes a redundant reference in the community content to obtaining the Oracle JDBC driver. The duplicate content was inserted in error, because it appeared to have been omitted. In fact, the original text was present, but it was contained in a `community` conditional that was embedded within a `product` conditional, preventing it from rendering upstream.
This change preserves a note that was contained in the deleted duplicate section about how Xstream user can obtain the `ojdbc8` driver file. The note now appears in the context of Step 3 of the upstream deployment procedure.
=> DBZ-6073 Move note text and eliminate embedded community conditional

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ChangeStreamPipeline.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactory.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/Filters.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactoryTest.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorConfigTest.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java, documentation/modules/ROOT/pages/connectors/mongodb.adoc
MongoDB Kafka Source Connector's [pipeline](https://www.mongodb.com/docs/kafka-connector/current/source-connector/configuration-properties/change-stream/#std-label-source-configuration-change-stream) property allows a user to configure:
> An array of aggregation pipelines to run in your change stream.
For example:
```json
[{"$match": { "$and": [{"operationType": "insert"}, {"fullDocument.eventId": 1404 }] } }]
```
This PR adds this capability to the Debezium MongoDB connector for change stream mode. New docs:
Some related resources:
- https://www.mongodb.com/docs/kafka-connector/current/source-connector/configuration-properties/change-stream/#std-label-source-configuration-change-stream
- https://github.com/mongodb/mongo-kafka/blob/41d7f8760d6785c488fba408736c2e480ccddfa5/src/main/java/com …
=> DBZ-6131: Support change stream filtering using MongoDBs aggregation pipeline step.

documentation/modules/ROOT/pages/integrations/cloudevents.adoc
@jpechane, @Naros, a small fix to the CE docs. The id is there another time on line 86.
=> [docs] Removing redundant TX ids from CloudEvents docs

documentation/modules/ROOT/pages/connectors/postgresql.adoc
It breaks tombstone events to have the proper key created because non-primary key columns will be null, and their values in the key will also be null.
=> DBZ-5490 Document the case when `message.key.columns` is set and `REPLICA IDENTITY` of the tables is not `FULL`.

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-db2-ora-pg-connector.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mongodb-connector.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mysql-sqlserver-connector.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-db2-connector-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-db2-ora-connector-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-oracle-connector-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-postgresql-connector-yaml.adoc
[DBZ-6153](https://issues.redhat.com/browse/DBZ-6153)
This change fixes errors in the connector YAML file that's included in the downstream documentation for using Streams to deploy connectors. Earlier, I did a band-aid fix on the published 2022.Q4/DBZ 1.9.7 version of the  downstream docs, but this change fixes the errors for the 2.x stream.
Due to differences among the connectors, the YAML example requires small tweaks depending on the context. The differences are not complex, but because of a shortcoming in the docs toolchain, when fetching content from upstream, `ifeval` conditionals are not supported. So to get the required results, I had to refactor the docs. It's a bit of a hack, but it mirrors the structure currently in place for creating the YAML to deploy Kafka Connect. 
Tested …
=> DBZ-6153 Refactor Streams deployment content to fix errors

documentation/modules/ROOT/partials/modules/all-connectors/con-connector-ad-hoc-snapshots.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot.adoc
- Document the new added field inside the `execute-snapshot` signal record in #4207
=> DBZ-6023 [doc] Documentation for `surrogate-key` field 

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-6215](https://issues.redhat.com/browse/DBZ-6215)
Restores Nebel annotation comments that are used by the script that fetches and splits content for downstream use.
Tested in a local Antora build and local downstream build. This change has no effect on the community version of the documentation.
Please backport this change to 2.1/2.2.
=> DBZ-6215 Adds missing annotation comments for Oracle connector FAQ topic

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/WalPositionLocator.java
When the last operation before connector stop was tx BEGIN, subsequent INSERT done after connector stop can have same LSN as BEGIN and thus it was possible to skip this INSERT when we search for the resume LSN, This issue was described and fixed in DBZ-5915. However, the same LSN can have also previous tx, so the WAL can look like this:
LSN | operation
------------------
123 | COMMIT
123 | BEGIN
123 | INSERT
124 | COMMIT
When last stored LSN is 123 for COMMIT operation, we skip also BEGIN and INSERT operations with LSN 123 and resume from COMMIT with LSN 124.
Adjust condition introduced in DBZ-5915 to consider also the case when the last processed operation is COMMIT.
https://issues.redhat.com/browse/DBZ-6204
=> DBZ-6204 Avoid skipping record when determining resume LSN

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactory.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbChangeEventSourceFactory.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotChangeEventSource.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbOffsetContext.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoUtil.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetOffsetContext.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ResumeTokens.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/MongoDbConnection.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ChangeStreamPipelineFactoryTest.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ConnectionIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoUtilTest.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java
https://issues.redhat.com/browse/DBZ-5987
This is just a draft for now -- although tests seem to be passing just fine, I still have some doubts.
Depending on our timeline for 2.2 release I would also like to follow up on this and finished some long overdue clean ups in `ReplicaSetOffsetContext` / `SourceInfo` classes (dates way back when the connector was ported to the common framework).
=> DBZ-5987 Refactor snapshotting to use change streams instead of oplog

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-823](https://issues.redhat.com/browse/DBZ-823)
This change updates the description for `snapshot.max.threads` that was modified in DBZ-823, by conditionalizing the existing note about parallel snapshots being in an incubating state so that it renders only in the community version of the docs. 
It also adds an equivalent Tech Preview statement for the product version.
At present, in the MongoDB documentation, the property description does not include any caveats. If that is ok, then this can be merged as-is. Let me know if I need to add a similar note for the MongoDB connector.
=> Dbz 823 conditionalize incubation note as tp for downstream

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4, debezium-ddl-parser/src/test/resources/mysql/examples/dml_delete.sql
https://issues.redhat.com/browse/DBZ-6243
=> DBZ-6243: Fix MySql parser to permit alias in single delete statements

debezium-connector-mongodb/pom.xml, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetDiscovery.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/ReplicaSet.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ShardedMongoConnectorIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TestHelper.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/junit/MongoDbDatabaseProvider.java, debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbDeployment.java, debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbReplicaSet.java, debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbShardedCluster.java
https://issues.redhat.com/browse/DBZ-6170
This PR brings support for connecting to sharded clusters as a single connection via monos instance(s). 
In order to remain backwards compatible a new config property `mongodb.connection.mode` is introduced. This property defaults to `replica_set` which keeps the current behaviour when the connector processes each shard as individual replica set. 
When the value is set to `sharded` then the connector will internally create a single instance of `ReplicaSet` with artificial name `cluster` which results in single connector where all connections are processed via the initially supplied connection string. 
Testing is not done yet -- I will have to introduce the very first tests for sharded cluster which is unlikely to work in GH actions. Additionally …
=> DBZ-6170 Connect and stream from sharded clusters through mongos instances

documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-db2-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-oracle-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/shared-deploy-kafka-connect-yaml.adoc
[DBZ-6263](https://issues.redhat.com/browse/DBZ-6263)
Fixes broken links to Streams docs from shared deployment files.
This change updates content that is used only in the downstream product, and it has no effect on the community version of the documentation.
Tested in a local downstream build.  
For the downstream release, I'm applying this update first to the `2.1` branch. It must also be applied to `2.2` and `main`.
=> DBZ-6263 Update shared deployment content to fix link

documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mysql-sqlserver-connector.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-db2-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-mysql-connector-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-oracle-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-sqlserver-connector-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/shared-deploy-kafka-connect-yaml.adoc
[DBZ-6267](https://issues.redhat.com/browse/DBZ-6267)
Upstream edits and refactoring to correct errors in the configuration examples for deploying connectors.
These changes combine with updates in the downstream documentation repository to correct errors in the User Guide and OCP installation guide. 
These changes do not affect the community version of the documentation.
Tested in a local downstream build.
Applies to the 2.1 and later releases.
=> DBZ-6267 update shared config example used in ocp install instructions

documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mysql-sqlserver-connector.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-db2-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-mysql-connector-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-oracle-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-sqlserver-connector-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/shared-deploy-kafka-connect-yaml.adoc
[DBZ-6267](https://issues.redhat.com/browse/DBZ-6267)
Cherry-pick of PR #4416 into 2.1 to correct errors in YAML examples.
This content is rendered in the downstream documenation build only.
=> DBZ-6267 2.1 correct Kafka YAML examples

documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mysql-sqlserver-connector.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-verifying-the-connector-deployment.adoc
[DBZ-6272](https://issues.redhat.com/browser/DBZ-6272)
Incorporates into `main` branch the 2.1.3 review feedback about naming inconsistencies found in the verification steps of the downstream installation documentation.
This change has no effect on the community version of the documenation.
=> DBZ-6272 Update shared files for downsream user guide & ocp install doc

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-6271
If we're in the initial_only mode of the snapshotter and don't require streaming CDC, we don't need the bin log position to be retrieved and can safely skip it and start the snapshot from scratch.
=> DBZ-6271 allow binlog to be absent when doing a snapshot only

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
https://issues.redhat.com/browse/DBZ-6265 
Refactored the Postgres connector class to extract the individual connection check methods, changed the WAL_LEVEL test to only run if the snapshot mode involves streaming.
=> DBZ-6265 skip the wal level check if no cdc is to occur

jenkins-jobs/job-dsl/release_debezium_nightly_image.groovy, jenkins-jobs/pipelines/build_debezium_images_pipeline.groovy, jenkins-jobs/pipelines/build_debezium_tool_images_pipeline.groovy, jenkins-jobs/pipelines/release-pipeline.groovy, jenkins-jobs/scripts/trigger-nightly-docker.sh
Partially revert commits which related to stop publishing images to Docker Hub:
* revert removing Docker credentials
* publish nightly images again on Docker Hub
https://issues.redhat.com/browse/DBZ-6216
=> DBZ-6216 Enable publishing to Docker Hub again

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbContainer.java
https://issues.redhat.com/browse/DBZ-6305
=> DBZ-6305 Allow specifying `DockerImageName` reference for MongoDB

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-nosql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-sql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-nosql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-sql.adoc
[DBZ-6327](https://issues.redhat.com/browse/DBZ-6327)
2.1 version of #4446 to separate the topics for triggering and stopping incremental snapshots into separate files for the SQL-based and MongoDB connectors.
=> DBZ-6327 Refactor incr. snapshot files (cherry-pick 34cfb36 from main)

debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-infinispan.xml, debezium-bom/pom.xml, debezium-connector-oracle/pom.xml, debezium-parent/pom.xml, debezium-quarkus-outbox-common/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/OutboxCommonProcessor.java, debezium-quarkus-outbox-common/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/OutboxEventHbmWriter.java, debezium-quarkus-outbox-common/runtime/src/main/java/io/debezium/outbox/quarkus/internal/AdditionalJaxbMappingProducerImpl.java, debezium-quarkus-outbox-common/runtime/src/main/java/io/debezium/outbox/quarkus/internal/JsonNodeAttributeConverter.java, debezium-quarkus-outbox-common/runtime/src/main/java/io/debezium/outbox/quarkus/internal/OutboxConstants.java, debezium-quarkus-outbox-reactive/integration-tests/src/main/java/io/debezium/outbox/reactive/quarkus/it/MyService.java, debezium-quarkus-outbox-reactive/integration-tests/src/main/java/io/debezium/outbox/reactive/quarkus/it/TestEntity.java, debezium-quarkus-outbox-reactive/integration-tests/src/main/java/io/debezium/outbox/reactive/quarkus/it/UpperCaseAttributeConverter.java, debezium-quarkus-outbox-reactive/integration-tests/src/test/java/io/debezium/outbox/reactive/quarkus/it/AbstractOutboxTest.java, debezium-quarkus-outbox-reactive/integration-tests/src/test/java/io/debezium/outbox/reactive/quarkus/it/OutboxTest.java, debezium-quarkus-outbox-reactive/runtime/pom.xml, debezium-quarkus-outbox-reactive/runtime/src/main/java/io/debezium/outbox/reactive/quarkus/internal/AbstractEventDispatcher.java, debezium-quarkus-outbox-reactive/runtime/src/main/java/io/debezium/outbox/reactive/quarkus/internal/DebeziumOutboxHandler.java, debezium-quarkus-outbox-reactive/runtime/src/main/java/io/debezium/outbox/reactive/quarkus/internal/DebeziumTracerEventDispatcher.java, debezium-quarkus-outbox-reactive/runtime/src/main/java/io/debezium/outbox/reactive/quarkus/internal/DefaultEventDispatcher.java, debezium-quarkus-outbox/integration-tests/src/main/java/io/debezium/outbox/quarkus/it/MyService.java, debezium-quarkus-outbox/integration-tests/src/main/java/io/debezium/outbox/quarkus/it/TestEntity.java, debezium-quarkus-outbox/integration-tests/src/main/java/io/debezium/outbox/quarkus/it/UpperCaseAttributeConverter.java, debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/AbstractOutboxTest.java, debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/OutboxTest.java, debezium-quarkus-outbox/runtime/pom.xml, debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/AbstractEventDispatcher.java, debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/DebeziumTracerEventDispatcher.java, debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/DefaultEventDispatcher.java, debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/EventDispatcher.java, pom.xml
https://issues.redhat.com/browse/DBZ-6129
=> DBZ-6129 Upgrade to Quarkus 3.0.0.Final

documentation/modules/ROOT/partials/modules/all-connectors/con-connector-streams-deployment.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-db2-ora-pg-connector.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mongodb-connector.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mysql-sqlserver-connector.adoc
[DBZ-6351](https://issues.redhat.com/browse/DBZ-6351)
Updates shared modules to fix broken links in downstream OCP install and User guides. Tested in a local downstream build.
=> DBZ-6351 Fixes broken links in deployment instructions

documentation/modules/ROOT/partials/modules/all-connectors/con-connector-streams-deployment.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-db2-ora-pg-connector.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mongodb-connector.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mysql-sqlserver-connector.adoc
[DBZ-6351](https://issues.redhat.com/browse/DBZ-6351)
Updates shared modules to fix broken links in downstream OCP install and User guides. Tested in a local downstream build.
(cherry picked from commit f997b8400d4533f9550e5e04f3091f3e2c76ba1c)
=> DBZ-6351 Fixes broken links in deployment instructions in 2.1 branch

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlChangeRecordEmitter.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlSkipMessagesWithoutChangeConfigIT.java, debezium-connector-mysql/src/test/resources/ddl/skip_messages_test.sql, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/BaseChangeRecordEmitter.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSkipMessagesWithoutChangeConfigIT.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSkipMessagesWithoutChangeConfigIT.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeRecordEmitter.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SQLServerSkipMessagesWithNoUpdateConfigIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerSkipMessagesWithNoUpdateConfigIT.java, debezium-core/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java, debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseConnectorConfig.java, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
If config is enabled and If `column.include.list/column.exclude.list` is used and the target table receives an update for the excluded (or not included) column - such events should be ignored
Addresses/Closes DBZ-2979
https://issues.redhat.com/browse/DBZ-2979
=> DBZ-2979 -  Feat: Add Config skip.messages.without.change to skip updates where there is no change in whitelisted columns

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-6276
Skip the archive log check in case we're in INITIAL_ONLY snapshot mode, which doesn't require the redo log.
=> DBZ-6276 remove the archive log check for Oracle

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
This is to address this comment: https://github.com/debezium/debezium/pull/4425#issuecomment-1501691602
This means that the WAL_LEVEL check always happens and an appropriate warning message will be given if it's not configured properly but the connector can function without it (initial_only mode).
Note: [Oracle](https://github.com/debezium/debezium/pull/4425/files) and MySQL have the desired behaviour already.
=> DBZ-6265 always check the WAL_LEVEL but fail if streaming is required

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/AbstractShardedMongoConnectorIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ShardedIncrementalSnapshotIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/ShardedMongoConnectorIT.java, debezium-connector-mongodb/src/test/resources/logback-test.xml, debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbContainer.java, debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbShardedCluster.java
https://issues.redhat.com/browse/DBZ-4427
Few noteworthy comments 
1) At this point tests in MongoDB module would benefit from some cleanup and code deduplication 
2) currently the test uses a chunk size of 100. This is a change compared to non sharded variant of the tests due to yet unknown performance issue. When running the tests against sharded MongoDB incremental snapshot is almost 100x slower when the chunk size is extremely low (e.g. chunk size 10 for 10000 entries). This will be documented for the next release and the support marked as incubating. I will continue with the investigation in the meantime.
=> DBZ-4427 basic test for incremental snapshot support with sharded MongoDB deployments

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/KafkaSignalThread.java
https://issues.redhat.com/browse/DBZ-6361
KafkaSignalThread#SIGNAL_POLL_TIMEOUT_MS option duplicate signal prefix. need remove one.
=> DBZ-6361 KafkaSignalThread#SIGNAL_POLL_TIMEOUT_MS option duplicate signal prefix

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-6371](https://issues.redhat.com/browse/DBZ-6371)
This change provides more usable examples in the downstream legacy Dockerfile-based deployment instructions by replacing the formatted text that was used  to represent the build numbers with the `debezium-build-number` attribute that is used in the Streams deployment instructions.
The change renders in the downstream content only and has no effect on the community version of the content. 
Tested in a local downstream build and merged to the downstream docs repository  in [MR 1221](https://gitlab.cee.redhat.com/red-hat-integration-documentation/integration/-/merge_requests/1221).
=> DBZ-6371 Replaces <build_number> references in examples w/ attributes.

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/UniqueDatabase.java, documentation/modules/ROOT/pages/connectors/mysql.adoc
https://github.com/debezium/debezium/pull/4460 made "prefer" the default SSL mode for the Postgres connector. This [comment](https://issues.redhat.com/browse/DBZ-6340?focusedId=22110644&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22110644) suggested doing similar work for other connectors. This PR makes a similar change for MySQL.
=> DBZ-6340 Make "preferred" the new default SSL mode for the MySQL connector

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, documentation/modules/ROOT/pages/connectors/postgresql.adoc
The supported values for database.sslmode are disable, require, verify-ca and verify-full. In In addition to those values, the Postgres JDBC [driver](https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/jdbc/SslMode.html) supports 2 more values:
* allow: try to connect to Postgres without encryption and, failing that, try encrypted 
* prefer: try to connect to Postgres with encryption and, failing that, try unencrypted
Let's add support for both of those modes and then make the prefer value the default mode.  
[DBZ-6340](https://issues.redhat.com/browse/DBZ-6340)
=> DBZ-6340 Add support to the Postgres connector for allow and prefer SSL modes  (with prefer as the new default value)

jenkins-jobs/job-dsl/release/release_deploy_snapshots.groovy
After debezium-server repo has been moved out the main repo it was no more deployed on Sonatype.
https://issues.redhat.com/browse/DBZ-6395
=> DBZ-6395 Restore debezium-server artifact Sonatype

documentation/modules/ROOT/pages/operations/debezium-server.adoc
Add documentation for JWT authentication support described in [DBZ-6348](https://issues.redhat.com/browse/DBZ-6348) and implemented via https://github.com/debezium/debezium-server/pull/20 .
=> DBZ-6348 Add documentation for HTTP Client JWT authentication

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/logwriter/CommitLogWriterFlushStrategy.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/logwriter/LogWriterFlushStrategy.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/logwriter/RacCommitLogWriterFlushStrategy.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/FlushStrategyIT.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-6256
_Premise:_
There is the potential when using multiple connector deployments on Oracle that there could be some level of lock contention with all connectors using the same table. This allows users to configure the flush table name themselves, reducing the lock contention across multiple connector deployments.
@jpechane its safe to back-port this to Debezium 2.2 at least, the code is completely backward compatible.
=> DBZ-6256 Add `log.mining.flush.table.name` Oracle config option

debezium-core/src/main/java/io/debezium/transforms/HeaderToValue.java, debezium-core/src/test/java/io/debezium/transforms/HeaderToValueTest.java
https://issues.redhat.com/browse/DBZ-6411
When the connector starts for the first time with initial snapshot, records with read operation will be created. In this phase the ExtractChangedRecordState will produce no headers and since HeaderToValue was not skipping records without headers the cache of the new schema will be created only with the old fields.
=> DBZ-6411 Fix HeaderToValue schema update cache.

documentation/modules/ROOT/pages/connectors/postgresql.adoc
[DBZ-6046](https://issues.redhat.com/browse/DBZ-6046)
Replaces #4503, #4403. This version of the PR addresses feedback received in earlier versions.
This change adds a section to the PostgreSQL connector documentation to provide guidance about how to upgrade PostgreSQL databases that Debezium captures from.
Tested in a local Antora build and a local downstream build.
=> DBZ-6046 Adds documentation about upgrading PG DB used by Debezium

COPYRIGHT.txt, documentation/modules/ROOT/pages/connectors/postgresql.adoc, jenkins-jobs/scripts/config/Aliases.txt
Property `skip.messages.without.change` in Postgresql Connector documentation has a note with a grammatical error.
=> [docs] resolve grammatical error with note

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-6440
Fixes 
`
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.kafka.clients.consumer.KafkaConsumer.seek(org.apache.kafka.common.TopicPartition, long)" because "this.signalsConsumer" is null
`
=> DBZ-6440 Init Kafka signal channel

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerDatabaseStateWriter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-6436
This change explicitly captures the state of two critical tables when the connector fails to start a LogMiner session, namely V$LOGMNR_LOGS and V$LOGMNR_PARAMETERS. While these were previously captured by the LogMinerDatabaseStateWriter, the old code required DEBUG log level and that isn't always feasible, so this change will capture these in ERROR log level regardless moving forward.
@jpechane I'd prefer we backport this as far back as you're comfortable, preferably 2.1, as it shouldn't be an intrusive change.
=> DBZ-6436 Improve Oracle LogMiner failure logging

debezium-core/src/main/java/io/debezium/pipeline/signal/SignalProcessor.java, debezium-core/src/test/java/io/debezium/pipeline/signal/SignalProcessorTest.java
Removes parallelStreams while processing signalChannelReaders
=> DBZ-6462 Schedule SignalProcessor task with a more relaxed scheduling

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java, debezium-core/src/test/java/io/debezium/junit/logging/LogInterceptor.java
* Enable set log level in tests (https://issues.redhat.com/browse/DBZ-6460)
* Don't scan all the tables when loading schema (https://issues.redhat.com/browse/DBZ-6439)
=> DBZ-6439 Don't scan all the tables when loading schema

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4, debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4, debezium-ddl-parser/src/test/resources/mysql/examples/userstat.sql
The MariaDB User Statistics (userstat) plugin adds 4 new keywords:
`USER_STATISTICS`, `CLIENT_STATISTICS`, `INDEX_STATISTICS`, and `TABLE_STATISTICS`
Additionally, it adds unusual variants of the `SHOW` and `FLUSH` statements which aren't covered by the MariaDB SQL grammar yet, for example
```
SHOW TABLE_STATISTICS;
FLUSH USER_STATISTICS;
```
See also:
- https://mariadb.com/kb/en/user-statistics/
- https://mariadb.com/kb/en/show-client-statistics/
- https://mariadb.com/kb/en/show-index-statistics/
- https://mariadb.com/kb/en/show-table-statistics/
- https://mariadb.com/kb/en/show-user-statistics/
Refs https://github.com/antlr/grammars-v4/pull/3400
=> DBZ-6459 [MariaDB] Add support for userstat plugin keywords

COPYRIGHT.txt, documentation/modules/ROOT/pages/configuration/signalling.adoc
While creating signaling table we need to have privileges to create table in source database not target
=> DBZ-6470 Refer correctly to the source database

debezium-core/src/main/java/io/debezium/util/ApproximateStructSizeCalculator.java, debezium-core/src/test/java/io/debezium/util/ApproximateStructSizeCalculatorTest.java
https://issues.redhat.com/browse/DBZ-6490
=> DBZ-6490 Convert the field BigDecimal value to bytes failure of ApproximateStructSizeCalculator

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotChangeEventSource.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotContext.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetNotifier.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/notification/IncrementalSnapshotNotificationService.java, debezium-core/src/main/java/io/debezium/pipeline/notification/Notification.java, debezium-core/src/main/java/io/debezium/pipeline/notification/NotificationService.java, debezium-core/src/main/java/io/debezium/pipeline/signal/actions/snapshotting/ExecuteSnapshot.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/IncrementalSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/IncrementalSnapshotContext.java, debezium-core/src/test/java/io/debezium/pipeline/notification/IncrementalSnapshotNotificationServiceTest.java, debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedSnapshotChangeEventSourceTest.java, debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
Incremental snapshot notification ids are now equal to the id sent in the `execute-snapshot` signal.
closes: https://issues.redhat.com/browse/DBZ-6447
=> DBZ-6447 Correlate incremental snapshot notifications ids with execute signal

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotCaseSensitiveIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/IncrementalSnapshotWithRecompileIT.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
closes: https://issues.redhat.com/browse/DBZ-6496
=> DBZ-6496 Fix `signal.poll.interval.ms` default value

debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, documentation/antora.yml, documentation/modules/ROOT/nav.adoc, documentation/modules/ROOT/pages/configuration/notification.adoc, documentation/modules/ROOT/pages/configuration/signalling.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-ad-hoc-snapshots.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-kafka.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-nosql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-sql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-kafka.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-nosql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-sql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot.adoc
closes: https://issues.redhat.com/browse/DBZ-6408
=> DBZ 6408 Add docs on how to extend channels and notification

debezium-core/src/main/java/io/debezium/transforms/partitions/PartitionRouting.java, debezium-core/src/main/java/io/debezium/util/MurmurHash3.java, debezium-core/src/test/java/io/debezium/transforms/partitions/PartitionRoutingTest.java, documentation/modules/ROOT/pages/transformations/partition-routing.adoc
Use better hash function than default Java Object::hash function to get better hashes which would be more equally spred over the hash space and thus more equally over the Kafka partitions.
Use Murmur3 hash function for computing hashes of the fields. Murmur3 implementation is taken from from Infinispan project code base.
https://issues.redhat.com/browse/DBZ-6529
=> DBZ-6529 Use Murmur hash for PartitionRouting SMT

COPYRIGHT.txt, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, jenkins-jobs/scripts/config/Aliases.txt
The link to the examples page was broken.
=> [docs] Fixed "SQL Server on Azure" link to examples.

COPYRIGHT.txt, documentation/modules/ROOT/pages/connectors/postgresql.adoc, jenkins-jobs/scripts/config/Aliases.txt
This adds a bit more clarity into the `initial` mode since it was very confusing as a new user to understand that `initial` was the default value but didn't exist in the table.
=> [docs] Add initial to table snapshot.mode in postgresql.adoc

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/notification/IncrementalSnapshotNotificationService.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java, debezium-core/src/test/java/io/debezium/pipeline/notification/IncrementalSnapshotNotificationServiceTest.java
https://issues.redhat.com/browse/DBZ-6552
Send `TABLE_SCAN_COMPLETED` notification even when incremental snapshot of a table fails.
Add information about incremental snapshot completion status to the `additional_data` field in `TABLE_SCAN_COMPLETED` notification.
The status can take one of the values:
```
EMPTY,
NO_PRIMARY_KEY,
SKIPPED,
SQL_EXCEPTION,
SUCCEEDED,
UNKNOWN_SCHEMA
```
=> DBZ-6552 Notify when incremental snapshot fails

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-6499
Introduces a new configuration option, `log.mining.restart.connection`, which closes and re-opens the JDBC connection when an Oracle Log switch occurs or when the optionally configured log mining session max lifetime is reached.
@jpechane I'm open to renaming the option if you think a better name is useful.
=> DBZ-6499 Support restarting JDBC connections

documentation/modules/ROOT/pages/configuration/signalling.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-6474](https://issues.redhat.com/browse/DBZ-6474)
Updates descriptions for Oracle connector `database.dname` and `snapshot.include.collection.list`
Please backport to 2.3.
=> Dbz 6474 doc non pdb prefix for oracle snapshot.include.collection.list

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-6579
Getting ConcurrentModificationException because KafkaSignal `init` is getting called from the connector task thread and KafkaSignal `reset` is getting called from the `change-event-source-coordinator` thread.
```
Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted   [org.apache.kafka.connect.runtime.WorkerTask] thread=task-thread-test_connector-0
org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:72)
at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:125)
at …
```
=> DBZ-6570 Fix ConcurrentModificationException in KafkaSignal

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4, debezium-ddl-parser/src/test/resources/mysql/examples/dml_select.sql
https://issues.redhat.com/browse/DBZ-6590
Upstream PR: https://github.com/antlr/grammars-v4/pull/3545
CLI example:
> SELECT CAST('1' AS DEC);
+------------------+
| CAST('1' AS DEC) |
+------------------+
|                1 |
+------------------+
=> DBZ-6590 Support MySQL CAST AS DEC

COPYRIGHT.txt, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
in the browser, it uses https://learn.microsoft.com/en-us/samples/azure-samples/azure-sql-db-change-stream-debezium/azure-sql%E2%80%94%E2%80%8Bsql-server-change-stream-with-debezium/ and then returns a 404
=> [docs] Link doesnt work in Chrome

COPYRIGHT.txt, debezium-core/src/main/java/io/debezium/pipeline/notification/IncrementalSnapshotNotificationService.java, debezium-core/src/test/java/io/debezium/pipeline/notification/IncrementalSnapshotNotificationServiceTest.java, documentation/modules/ROOT/pages/configuration/notification.adoc, jenkins-jobs/scripts/config/Aliases.txt
https://issues.redhat.com/browse/DBZ-6605
This is a fix to see only the table name for which the table scan has completed. The notification should be per table so that the it can be acted on correctly.
=> DBZ-6605 Fix DataCollections for snapshot completion notification

pom.xml
DBZ-6619 Connector postgres driver v42.5.0 has a vulnerability CVE-2022-41946, Upgrade driver to v42.6.0
https://issues.redhat.com/browse/DBZ-6619
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-41946
=> DBZ-6619 Fix Connector postgres driver v42.5.0 has a vulnerability  CVE-2022-41946 issue

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
max retries config is only implemented in SqlServerConnectorConfig
move this config to HistorizedRelationalDatabaseConnectorConfig 
[doc link](https://issues.redhat.com/browse/DBZ-6573)
=> DBZ-6573 Move retries config 

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
Some label combined with some keywords (when written without a space in between, which is valid for MySQL) can look like beginning of an IPv6 address, e.g.
aaa:BEGIN
is currectly prased as IPv6 address `aaa:be` and leads to a parsing failure.
Make parsing of IPv6 address more robust and require at least two `:` to make sure there is no confusion with labels.
Upstream PR: https://github.com/antlr/grammars-v4/pull/3606
=> DBZ-6651 Avoid confusing label and IPv6 address

documentation/modules/ROOT/pages/configuration/signalling.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-kafka.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot.adoc
[DBZ-6628](https://issues.redhat.com/browse/DBZ-6628)
Updates formatting of string values in `additional-condition` examples.
The original examples incorrectly omitted single quotes around string values for the parameter.
This bug fix should be backported to 2.3
=> DBZ-6628 Correct formatting in `additional-condition` examples

documentation/modules/ROOT/pages/connectors/vitess.adoc
Update docs with new shard field added. Some other parts of the message schema were out of date so update with other fields as well. Another part referred to mysql binlog position but it's really VGTID so also update that. Also a few lines had trailing whitespace so remove those to fix formatting.
=> DBZ-6627 Update Vitess Connector docs with new shard field; remove trailing whitespace

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
The root cause of DBZ-6648 is using long number as a fallback value, while String is expected and thus falling conversion and returning `null`.
Use String fallback when interval handling mode is String.
https://issues.redhat.com/browse/DBZ-6648
=> DBZ-6648 Use String fallback when interval handling mode is String

debezium-bom/pom.xml, debezium-connector-mysql/pom.xml, debezium-connector-postgres/pom.xml, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DebeziumEngineIT.java, debezium-testing/debezium-testing-system/pom.xml, debezium-testing/debezium-testing-testcontainers/pom.xml
https://issues.redhat.com/browse/DBZ-6659
A proper test would be to switch to junit vintage and get rid of these issue once and for all. 
For what it's worth I tried running the test and replacing `junit:junit` with `org.junit.vintage:junit-vintage-engine` seems to be enough. I am opened to try replacing it in all modules and seeing what happens.
=> DBZ-6659 Fixing junit dependencies

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-6673
The shouldCaptureChangesForTransactionsAcrossSnapshotBoundaryWithoutReemittingDDLChanges test only expects the tables created by the entire test to exist but tables from other tests not, and it would appear this commonly happens when another test fails to cleanup after itself.
This fix is to guarantee that the Oracle database state is set properly so that tests from within this class are executed with the right number of tables expected to exist.
=> DBZ-6673 Fix flaky Oracle test

documentation/modules/ROOT/pages/connectors/mongodb.adoc
https://issues.redhat.com/browse/DBZ-6591
=> DBZ-6591: Document read preference changes in 2.4

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlUnsignedIntegerIT.java
When using the "precise" configuration for `bigint.unsigned.handling.mode`, the output decimal types were not specifying a precision. Adjust the code to generate an Avro schema with a decimal precision of 20, which is sufficient to represent all possible unsigned bigints.
**Warning to reviewer:** I couldn't get the tests running locally, so I was only able to test that this compiled, not that the test succeeded.
=> DBZ-6714 Set precision of MySQL unsigned bigints in output decimal type

documentation/modules/ROOT/pages/operations/debezium-server.adoc
[DBZ-6706](https://issues.redhat.com/browse/DBZ-6706)
Corrects two instances in the Debezium server doc where `pulsar` is misspelled as `pusar` in the Pulsar properties table.
=> DBZ-6706 Fixes typos in Apache Pulsar properties table in DBZ server doc

documentation/modules/ROOT/pages/connectors/mongodb.adoc
[DBZ-6705](https://issues.redhat.com/browse/DBZ-6705)
Removes duplicate `include` directive that resulted in two instances of the sink notifications properties table in the MongoDB connector doc.
Tested in local Antora build
=> DBZ-6705 Removes dup include directive for sink notification props file

documentation/modules/ROOT/pages/operations/debezium-server.adoc
[DBZ-6707](https://issues.redhat.com/browse/DBZ-6707)
This change specifies that the `debezium.sink.redis.ssl.enabled` configuration property accepts a Boolean value. 
For this PR I did not comprehensively review all Debezium configuration properties to ensure that each of them specifies the required data type.
=> DBZ-6707 Specifies Boolean values for debezium.sink.redis.ssl.enabled

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc
[DBZ-6219](https://issues.redhat.com/browse/DBZ-6219)
Replaces PR #4530 
This version incorporates feedback received for the original PR.
Enhance the connector documentation to describe default schema capture behavior during initial snapshots, how to modify the defaults, and how to capture tables whose schema were not captured:
[x] Update description of schema.history.internal.store.only.captured.tables.ddl property in shared file (ref-connector-configuration-database-history-properties.adoc).
[x] Update Db2 snapshots topic
[x] Update MySQL snapshots topic
[x] Update Oracle snapshots topic
[x] Update SQL Server snapshots topic
[x] Add subtopic to Snapshots section that explains why snapshots do not honor the table.include.list settings when capturing the table schema
[ ] Add steps for …
=> DBZ-6219 Doc update to explain default snapshot behavior for capturing schema history

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4, debezium-ddl-parser/src/test/resources/oracle/examples/ddl_drop.sql
https://issues.redhat.com/browse/DBZ-6716
Compared with upstream grammar, rule already exists.
=> DBZ-6716 Support Oracle `DROP USER` statements

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-6729
=> DBZ-6729 Use default of 10000 for snapshot/query fetch sizes

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql
https://issues.redhat.com/browse/DBZ-6736
MariaDB supports conditionally altering tables with the `IF EXISTS` clause.
Refs
- https://mariadb.com/kb/en/alter-table/
- https://github.com/antlr/grammars-v4/pull/3642
=> DBZ-6736 Add support for ALTER TABLE IF EXISTS

debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/Connector.java
[KIP-875](https://cwiki.apache.org/confluence/display/KAFKA/KIP-875%3A+First-class+offsets+support+in+Kafka+Connect) added a new `STOPPED` state for connectors that causes the `Connector` instance to be paused and all `Task` instances to be shut down (as opposed to left ready-but-idling, which is the case for the `PAUSED` state). See [this section](https://cwiki.apache.org/confluence/display/KAFKA/KIP-875%3A+First-class+offsets+support+in+Kafka+Connect#KIP875:FirstclassoffsetssupportinKafkaConnect-Newtargetstate:STOPPED) of the KIP for more details.
Tasks will never appear in the `STOPPED` state, only connectors.
This PR adds that state to the testcontainers library to make custom testing easier (e.g., with `DebeziumContainer::ensureConnectorState`).
I'm unsure about the backporting …
=> DBZ-6734: Add new STOPPED state for connectors to testing library

pom.xml
https://issues.redhat.com/browse/DBZ-6740
@jpechane I've tagged this with `2.3` due to a CVE discussed in the Jira.  I suspect the CVE is mostly a corner case as it only affects the UI, so perhaps a backport isn't necessary, but I'll defer to you to decide.
=> DBZ-6740 Upgrade to Quarkus 3.2.3.Final

documentation/modules/ROOT/pages/configuration/notification.adoc
[DBZ-6754](https://issues.redhat.com/browse/DBZ-6754)
Adds metadata and provides edits to prepare the notfications content for downstream use.
Tested in a local downstream build.
=> DBZ-6754 Prepares content for downstream use

debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java, debezium-core/src/test/java/io/debezium/connector/common/BaseSourceTaskTest.java
* Try to start the connector in BaseSourceTask::start(). This is the root cause of DBZ-6213 as EmbeddedEngine calls start() and assumes it really tries to start the connector.
* Simplify the code by removing unnecessary checks and restartDelay.hasElapsed() call.
https://issues.redhat.com/browse/DBZ-6213
=> DBZ-6213 Adjust connector restart

COPYRIGHT.txt, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java, jenkins-jobs/scripts/config/Aliases.txt, pom.xml
In regards to this JIRA issue: https://issues.redhat.com/browse/DBZ-6783
We have internally upgraded the Binlog Client to v0.28.1 for MySQL to take advantage of https://github.com/osheroff/mysql-binlog-connector-java/issues/98
We wanted to bring it upstream to share it with the community.
Here are some performance enhancements we have seen with the async-profiler:
Old:
New:
=> DBZ-6783 Upgrade MySQL Binlog Client to v0.28.1

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/UnchangedToastedPlaceholder.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/UnchangedToastedReplicationMessageColumn.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DecoderDifferences.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
Addresses https://issues.redhat.com/browse/DBZ-6720
The designated format for an unchanged toasted UUID array is a singleton array containing a UUID element that represents the encoded UUID of the placeholder string.
The uuid encoding of the default placeholder value `__debezium_unavailable_value` is `b68a35a7-17ad-35b3-af2a-ae46edb4545a`.
=> DBZ-6720: handle unchanged toasted uuid array

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
Heartbeats should be sent when Debezium is not sending any events obatined from the DB. Send heartbeat before finishing itteration which doesn't contain any updates from the DB.
https://issues.redhat.com/browse/DBZ-6811
=> DBZ-6811 Send heartbeats when there are no updates in the DB

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetrics.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetricsMXBean.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/Scn.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-6798
The SCN data types were previously exposed as `String` types, which is not consumable by Grafana and Prometheus. By using `BigInteger`, we can now make these accessible on dashboards.
=> DBZ-6798 Expose SCN-based metrics as `BigInteger`

documentation/modules/ROOT/pages/connectors/db2.adoc
The Procedure for compiling the capture agent didn't show how to correctly invoke `bldrtn` as it assumed it was in the same directory as the Debezium management UDFs, which is isnt.  I've added instructions for getting it on PATH and also an example later on for how to invoke SQL commands from the command line once they're already logged on.  (I didn't update the following two SQL statements, as I'd assume that an intelligent viewer could learn from the first example!)
=> [docs] Improve DB2 example commands; Update db2.adoc

COPYRIGHT.txt, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentState.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTestIT.java, jenkins-jobs/scripts/config/Aliases.txt
Adding Integration Test and the feature to add beforeRecord in delete events of event flattening with delete handling mode rewrite. Works only if the collection has ChangeStreamPreAndPostImagesOptions turned on and capture mode is *_with_pre_image (MongoDB 6.0 or later)
=> DBZ-6725 Include beforeRecord if the delete handling mode is REWRITE

documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/development/converters.adoc
[DBZ-6704](https://issues.redhat.com/browse/DBZ-6704)
For consistency, this change moves properties in the MongoDB and MySQL connector documentation from the Required connector properties table to the Advanced connector properties table. 
In addressing this change it became apparent that the MongoDB connector documentation does not reference the `converters` configuration property, but the Custom converters documentation does not explicitly state that you cannot create custom converters for MongoDB. 
To complete this work, one of the following further updates is required, depending on whether the content about custom converters applies to  MongoDB:
~~* Add the `converters` property to the table of Advanced MongoDB connector configuration properties.~~
* Add a note to the Custom converters …
=> Dbz 6704 config properties inconsistently classified as advanced vs required

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-6821
=> DBZ-6821 Dbz crashes on DDL statement (non Latin chars in variables)

documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Adds definite article that was omitted when the content was first added in #1971.
The content in question is used only in the productized doc.
=> [docs] Insert missing word in SQL Server connector doc

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/CustomPostgresSourceInfoStructMaker.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
PostgresConnectorIT#shouldAddNewFieldToSourceInfo fails only when run together with other tests and the failure is random. It seem there is a caching issue in Apicuro, when `test_server.s1.a-value` artifact references `io.debezium.connector.postgresql.Source` version 1, which hasnt't `newField` field and this reference is used also in `shouldAddNewFieldToSourceInfo` where artifact with version 2 should be used. Using dedicated table and thus creating new artifact in Apucurio should fix this issue.
Also remove unused variable from `CustomPostgresSourceInfoStructMaker`.
https://issues.redhat.com/browse/DBZ-6839
=> DBZ-6839 Fix PostgresConnectorIT#shouldAddNewFieldToSourceInfo

debezium-core/src/test/java/io/debezium/connector/common/BaseSourceTaskTest.java
Test was passing locally and in the CI as the start was very fast and after the first start retriable wait condition wasn't met, so we actually sleep and while the sleep we doesn't increment the counter and the state is still `RESTARTING`. On slower machines when start takes longer time and we don't wait, the test is actualy wrong. The correct test either should remove last assert for `RESTARTING` state or increase number of failures and add a sleep time after initial start, so that there is no retry wait time.
This PR implements the later option.
https://issues.redhat.com/browse/DBZ-6841
=> DBZ-6841 Fix randomly failing BaseSourceTaskTest#verifyTaskRestartsSuccessfully

documentation/modules/ROOT/pages/connectors/vitess.adoc
The same behavior & headers as other debezium connectors (e.g., [mysql](https://github.com/debezium/debezium/blob/main/documentation/modules/ROOT/pages/connectors/mysql.adoc?plain=1#L1447-L1455)) is done for primary key updates with the vitess connector. The docs make no mention of this so update them to do so.
=> [docs] Add primary key updates Kafka headers section to Vitess connector

documentation/modules/ROOT/nav.adoc, documentation/modules/ROOT/pages/transformations/index.adoc, documentation/modules/ROOT/pages/transformations/timezone-converter.adoc
https://issues.redhat.com/browse/DBZ-6835
=> DBZ-6835 Documentation for Timezone SMT

jenkins-jobs/pipelines/release/release-pipeline.groovy
Oracle re-build fails after OLR was introduced due to protoc generated sources. The re-build (unless clean is provided) fails with Compilation unit is not of SOURCE kind: ".../debezium-connector-oracle/target/generated-sources/oracle.json"
=> [jenkins-jobs] Clean project befor rebuild for snapshots

debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java, debezium-core/src/test/java/io/debezium/transforms/AbstractExtractStateTest.java, debezium-core/src/test/java/io/debezium/transforms/ExtractNewRecordStateTest.java
https://issues.redhat.com/browse/DBZ-6901
=> DBZ-6901 ExtractNewRecordState's schema cache is not updated with arrival of the ddl change event

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerOracleOffsetContextLoader.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/olr/OpenLogReplicatorOracleOffsetContextLoader.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/olr/OpenLogReplicatorStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/olr/client/OlrNetworkClient.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/olr/client/StreamingEvent.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamOracleOffsetContextLoader.java, debezium-connector-oracle/src/main/proto/OraProtoBuf.proto, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaHistoryTest.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-6895
=> DBZ-6895 Fix OpenLogReplicator confirmation

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerAdapter.java
https://issues.redhat.com/browse/DBZ-6869
Pending transactions with a START_SCN of 0 are considered transactions that have started before the oldest available archive log, and these will be ignored as the entire transaction cannot be mined.
=> DBZ-6869 Ignore pending transactions with zero START_SCN

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/IncrementalSnapshotIT.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
closes: https://issues.redhat.com/browse/DBZ-6937
=> DBZ-6937 MySql connector get NPE when snapshot.mode is set to never and signal data collection configured

debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java
=> DBZ-6870 throw producer exception during poll() even if the queue isn't empty yet.

COPYRIGHT.txt, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/converters/MongoDbCloudEventsProvider.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/converters/MongoDbRecordParser.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/CloudEventsConverterIT.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/converters/MySqlCloudEventsProvider.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/converters/MySqlRecordParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/CloudEventsConverterIT.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/converters/OracleCloudEventsProvider.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/converters/OracleRecordParser.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/converters/PostgresCloudEventsProvider.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/converters/PostgresRecordParser.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/CloudEventsConverterIT.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/converters/SqlServerCloudEventsProvider.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/converters/SqlServerRecordParser.java, debezium-core/src/main/java/io/debezium/converters/CloudEventsConverter.java, debezium-core/src/main/java/io/debezium/converters/CloudEventsConverterConfig.java, debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadata.java, debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadataBaseImpl.java, debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadataHeaderImpl.java, debezium-core/src/main/java/io/debezium/converters/spi/CloudEventsProvider.java, debezium-core/src/main/java/io/debezium/converters/spi/RecordParser.java, debezium-core/src/test/java/io/debezium/converters/CloudEventsConverterTest.java, debezium-embedded/src/test/java/io/debezium/converters/AbstractCloudEventsConverterTest.java, jenkins-jobs/scripts/config/Aliases.txt
This makes Outbox SMT (that removes source info) + CloudEventsConverter working (by getting source info from headers), that is to publish events from `outbox` table converted to CloudEvents format.
This works when the connector is configured in appropriate way, particularly:
* filter unwanted messages, such as, heartbeats and tombstones (this is only needed for `HeaderFrom` transform)
* add `source`, `op`, `transaction` headers
* enable schemas for header converter
The following is an example of a configured connector:
```
{
"name": "book-db-source-connector",
"config": {
"connector.class": "io.debezium.connector.postgresql.PostgresConnector",
"plugin.name": "pgoutput",
"database.hostname": "book-db",
"database.port": "5432",
"database.user": "postgres",
"database.password": "password", …
```
=> DBZ-3642 CloudEventsConverter can retrieve metadata from headers

debezium-connector-postgres/pom.xml, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
* Use quay.io image as a base images for postgres test image
* Skip RecordsStreamProducerIT#shouldReceiveChangesForInfinityNumericWithInfinity on Postgres < 14
https://issues.redhat.com/browse/DBZ-6986
=> Skip RecordsStreamProducerIT#shouldReceiveChangesForInfinityNumericWithInfinity on Postgres < 14

documentation/modules/ROOT/pages/configuration/notification.adoc
[DBZ-6980](https://issues.redhat.com/browse/DBZ-6980)
Moves closing delimiter for `community` conditional to end of file to include custom notifications topic not supported in productization release.
=> DBZ-6980 Relocates conditional delimiter

documentation/modules/ROOT/pages/configuration/notification.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/jdbc.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/transformations/event-changes.adoc, documentation/modules/ROOT/pages/transformations/event-flattening.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-ad-hoc-snapshots.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-pass-through-kafka-signals-configuration-properties.adoc
[DBZ-6997](https://issues.redhat.com/browse/DBZ-6997)
Updates to fix downstream build issues.
Unfortunately, I did not achieve the main goal of this change, which was to expose the instructions for using Kafka signals to trigger and stop incremental snapshots.
But the other build fixes were also necessary. 
To explore a downstream one-off change to  fix the target issue for the Q4 product.  
Tested in a local Antora build. Antora continues to correctly render the content, so no adverse effects in the community docs.
Merging these changes into the 2.3 branch. I'll port these same changes to `main` later, but I don't think we'll be able to drop them in as-is, so a separate PR will be necessary.
=> Dbz 6997 further refactoring of incremental snapshots topics

.github/workflows/debezium-workflow.yml
https://issues.redhat.com/browse/DBZ-6881
=> DBZ-6881 Deprecating MongoDB 4.4 in Debezium 2.5

documentation/modules/ROOT/partials/modules/all-connectors/con-connector-streams-deployment.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mysql-sqlserver-connector.adoc
[DBZ-7021](https://issues.redhat.com/browse/DBZ-7021)
Fixes links in downstream version of the connector deployment docs that broke when the target content was moved to new titles in the Streams docs
Tested in downstream build. This change has no effect on the community version of the documentation.
=> DBZ-7021 Update links to Streams docs targets

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/events/LogMinerEventRow.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/events/LogMinerEventRowTooLargeException.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerEventRowTest.java
https://issues.redhat.com/browse/DBZ-7018
In some corner cases, users may have unusually large SQL statements that need to be buffered due to the number of columns paired with the data in those columns. Previously we capped this to 4000*10 or 40kb primarily to address situations with LOB operations that could lead to OOM scenarios. The new code rather logs a warning when exceeding 100kb and hard faults ony when the connector sees Integer.MAX_VALUE number of SQL lines for a single SQL buffer.
=> DBZ-7018 Allow SQL statements greater than 40kb

documentation/modules/ROOT/pages/configuration/notification.adoc, documentation/modules/ROOT/pages/configuration/signalling.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-ad-hoc-snapshots.adoc
[DBZ-7046](https://issues.redhat.com/browse/DBZ-7046)
Fixes invalid formatting and incorrect link targets. Some of these errors caused the downstream documentation build to fail, or required manual intervention to enable content to render as expected.
Tested in an local Antora build and local downstream build.
=> DBZ-7046 Formatting and xref fixes; addresses downstream build errors

pom.xml
https://issues.redhat.com/browse/DBZ-7055
This is to see whether this fixes the GitHub Actions stability issue in this repository with the error:
```
[WARNING] Corrupted channel by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/runner/work/debezium/debezium/debezium-connector-mysql/target/failsafe-reports/2023-10-18T23-08-57_003-jvmRun1.dumpstream
```
If it does, we can replicate this to other sibling repositories.
=> DBZ-7055 Upgrade maven-surefire-plugin to 3.1.2

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-5891
https://issues.redhat.com/browse/DBZ-7026
https://issues.redhat.com/browse/DBZ-7037
Fake Rotates Event skip tableMapEventByTableId clear
When the connection to the Mysql database is lost, a fake Rotate Event occurs in communication with the master. Currently, even when initializing tableMapEventByTableId when a fake Rotate Event occurs, an error occurs because the corresponding tableMapEvent for the tableId cannot be found.
I think this could be the issue with this problem. What do you think?
https://mariadb.com/kb/en/fake-rotate_event/
https://github.com/go-mysql-org/go-mysql/blob/3a75f6a26d8819c2a88629e54c7de0b7698ae05c/replication/backup.go#L59
=> DBZ-7037 com.github.shyiko.mysql.binlog.event.deserialization.MissingTableMapEventException: No TableMapEventData has been found for table id:137

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/EmbeddedInfinispanLogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/RemoteInfinispanLogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-7047
Using parallel streams, this causes a severe loss of performance.
=> DBZ-7047 Infinispan Embedded Performance with Oracle

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorDatabaseRestrictedIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/EventProcessingFailureHandlingIT.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngineConfig.java, debezium-embedded/src/main/java/io/debezium/embedded/Predicates.java, debezium-embedded/src/main/java/io/debezium/embedded/Transformations.java, debezium-embedded/src/test/java/io/debezium/connector/simple/SimpleSourceConnectorOutputTest.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java, debezium-embedded/src/test/java/io/debezium/embedded/ConnectorOutputTest.java, debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java, debezium-embedded/src/test/java/io/debezium/embedded/TestingDebeziumEngine.java, debezium-embedded/src/test/java/io/debezium/embedded/TestingEmbeddedEngine.java, debezium-microbenchmark-oracle/src/main/java/io/debezium/performance/connector/oracle/EndToEndPerf.java
https://issues.redhat.com/browse/DBZ-7007
=> DBZ-7007 Use DebeziumEngine API instead of EmbeddedEngine in the testsuite

debezium-core/src/main/java/io/debezium/connector/common/RelationalBaseSourceConnector.java
DBZ-7105 Fix exceptions that are triggered by RelationalBaseSourceConnector#validate when calling #validateConnection() with an invalid configuration. Other, not-checked fields can cause an exception when the ConnectorConfig class is instantiated to setup the connection. Now we are only allowing connection validation when all config options are free of errors.
closes to https://issues.redhat.com/browse/DBZ-7105
=> DBZ-7105 Fix exceptions that are triggered by RelationalBaseSourceConnector#validate when calling #validateConnection() with an invalid configuration

debezium-bom/pom.xml, debezium-connector-mysql/pom.xml, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MariaDbProtocolFieldReader.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTestConnection.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/UniqueDatabase.java, debezium-storage/debezium-storage-jdbc/src/test/java/io/debezium/storage/jdbc/JdbcOffsetBackingStoreIT.java, debezium-storage/debezium-storage-jdbc/src/test/java/io/debezium/storage/jdbc/history/JdbcSchemaHistoryIT.java, pom.xml
https://issues.redhat.com/browse/DBZ-7085
=> DBZ-7085 Add MariaDB driver and use with MariaDB profile

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/LogMinerHelperTest.java
https://issues.redhat.com/browse/DBZ-6942
There is a corner case where it's possible the Oracle connector may query the Oracle metadata tables quicker than the ARC process can generate an archive log history record in V$ARCHIVED_LOG, and this can lead to a race condition where we may incorrectly advance the connector forward to start mining a group of logs when a log sequence gap exists in the log ranges.
For users who use the online_catalog strategy, there are some checks that LogMiner does automatically which it skips, and one is with log sequence gaps. This fix enforces that check by Debezium even for users who may use the faster online_catalog mode so that no logs are omitted and events could be missed.
=> DBZ-6942 Verify no log sequence gaps on log switch

debezium-api/src/main/java/io/debezium/engine/spi/OffsetCommitPolicy.java, debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java
In 7b4cf1901 deprecated `io.debezium.embedded.spi.OffsetCommitPolicy`, which provided also constructor for `Configuration`, was removed. This constructor was actually used for creating `OffsetCommitPolicy`. `Configuration` provides default values for options which are not explicitly set, while `Properties` based constructor cannot do that and therefore with this switch the default value for `offset.flush.interval.ms` is now missing.
As debezium-api package has no knowledge about `Configuration` interface, which is part of debezium-core, and thus about the default values, specify default value direcly in the `PeriodicCommitOffsetPolicy` class.
https://issues.redhat.com/browse/DBZ-7099
=> DBZ-7099 Provide default value for PeriodicCommitOffsetPolicy

debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterConfigDefinition.java, debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
Guys, I do understand that it is not a major improvement to the codebase, but believe me - it will significantly improve life of many people (those who use different UIs to manage connectors).
Two minor points here:
- technically there is no sense in adding ".trim()" to a "AdditionalFieldPlacement placement = AdditionalFieldPlacement.parse(parts[1]);" line (line 332) as AdditionalFieldPlacement.parse() function does call trim() under the hood. But I still decided to add it to keep the consistent for all 3 parts and not to confuse any of its future readers
- there already exists a test for this functionality, so I just slightly modified it
=> DBZ-7142 Improved Outbox Event Router SMT to handle whitespaces inside of fields.additional.placement setting

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/BlockingSnapshotIT.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
Use namespace instead of identifierto match collections to be snapshotted
=> DBZ-7139 MongoDB data collection filter requires replica set specification on blocking/initial snapshot execution

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/LogMinerHelperTest.java
https://issues.redhat.com/browse/DBZ-7158
@jpechane This fixes the discussion had on https://issues.redhat.com/browse/DBZ-6942 with Lucas.  This should also be back ported to 2.4.2.Final as 2.4.1.Final will likely not work on Oracle RAC but should be fine for Oracle Standalone.
=> DBZ-7158 Treat Oracle RAC redo thread log sequences independently

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/CloudEventsConverterIT.java, debezium-core/src/main/java/io/debezium/converters/CloudEventsConverter.java, debezium-core/src/main/java/io/debezium/converters/CloudEventsConverterConfig.java, debezium-core/src/main/java/io/debezium/converters/spi/CloudEventsValidator.java, debezium-core/src/test/java/io/debezium/converters/CloudEventsConverterTest.java, debezium-embedded/src/test/java/io/debezium/converters/AbstractCloudEventsConverterTest.java
https://issues.redhat.com/browse/DBZ-7159
A new validator will also be used by [`ConvertCloudEventToSaveableForm`](https://github.com/debezium/debezium-connector-jdbc/blob/main/src/main/java/io/debezium/connector/jdbc/transforms/ConvertCloudEventToSaveableForm.java#L156)
=> DBZ-7159 Fail fast during deserialization if a value is not a CloudEvent

COPYRIGHT.txt, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java, jenkins-jobs/scripts/config/Aliases.txt
to be in sync with memory event processor
I tested that with this change the connector runs stable, finally ( for our case). However I'm struggling to make Docker based integration test working on my machine so I did not run those.
=> DBZ-7169 - populating processed transaction cache only if lobs enabled

COPYRIGHT.txt, debezium-api/src/main/java/io/debezium/engine/ChangeEvent.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngineChangeEvent.java, jenkins-jobs/scripts/config/Aliases.txt, support/revapi/src/main/resources/revapi/debezium-api-changes.xml
Link: https://issues.redhat.com/browse/DBZ-6723
Based on feedback in https://github.com/debezium/debezium-server/pull/33 this commit adds the `partition()` method to the ChangeEvent interface and implements it in the EmbeddedEngineChangeEvent. 
This allows reading the assigned partition for an event in downstream processors, for example in custom Sinks that need the assigned partition for routing purposes.
The change triggered a warning in the `revapi` checks, that I for now add to the ignores as I don't think there are any other implementations. Please let me know if this should be handled in a different way.
=> DBZ-6723 Expose partition in ChangeEvent interface

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-7189
=> DBZ-7189 Parsing MySQL indexes for JSON field fails, when casting is used with types double and float

debezium-core/src/main/java/io/debezium/converters/CloudEventsConverter.java, debezium-core/src/main/java/io/debezium/converters/spi/CloudEventsValidator.java
The validator can be configured once, during initialization, as well as the CE converter
=> DBZ-7159 Simplify CE validator API by setting serializer type at the configuration phase

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/LogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
this closes the feature gap between memory and ISPN based processors.
It also fixes 2 bugs in existing ISPN processors impl (AFAIK): 
- the transactions abandonment was already implemented in ISPN version but the events were not removed from the event cache (it was staying there forever)
- if event came for abandoned transaction, it would be processed normally (not sure what would happen exactly, but not good situation anyway)
It also fixes dubious name `removeTransactionAndEventsFromCache` which was not doing what it says (e.g. in memory version it was not removing neither transaction nor events)
=> Dbz 7192 ispn abandoned transactions

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java
=> DBZ-7208 - implemented check for NPE

COPYRIGHT.txt, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SourceInfo.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java, jenkins-jobs/scripts/config/Aliases.txt, pom.xml
References and depends on https://github.com/osheroff/mysql-binlog-connector-java/pull/130
More accurate metrics and also `source.ts_ms` for `MySQL >= 8.0.1` with `GTID` replication mode enabled. At Shopify we're doubling down on lower latency business use cases for CDC and we're aware of the second resolution (int4) timestamp constraint in binlog event headers for some time.
This issue and Github pull requests to the binlog client and Debezium is an attempt to engage with the community to report higher resolution metrics and `source.ts_ms` in a backwards compatible way.
Some example graphs from a lower environment connecting to MySQL 8 writers where the higher resolution timestamps are rendered - a lot easier to spot trends and variance for the writer -> binlog client hop.
I could not …
=> Support MySQL 8 high resolution replication timestamps from GTID events

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/metrics/MongoDbStreamingChangeEventSourceMetrics.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/metrics/MongoDbStreamingChangeEventSourceMetricsMBean.java
Removes the duplicit metric introduced in https://github.com/debezium/debezium/pull/5024
=> DBZ-7162 Removed duplicit source event count metric for MongoDB

documentation/modules/ROOT/pages/operations/debezium-server.adoc
Add documentation to explain different strategies to route events via debezium-server to one or multiple partitions in Azure EventHubs.
See https://github.com/debezium/debezium-server/pull/51 for implementation details.
Link:  https://issues.redhat.com/browse/DBZ-6723
=> DBZ-6723 Update docs on Eventhub partition configuration

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
MySQL BIT Type should have a default length 1
https://dev.mysql.com/doc/refman/8.0/en/bit-type.html
=> DBZ-7230 MySQL BIT Type should have a default length 1

documentation/modules/ROOT/pages/connectors/cassandra.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/informix.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc
=> [docs] Fix typo found in each of the source connector docs

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
https://issues.redhat.com/browse/DBZ-7275
=> DBZ-7275 Close connection registerd with bean registry

documentation/modules/ROOT/partials/modules/tutorial/proc-starting-mysql-command-line-client.adoc
Deleted the extra --rm flag in Docker and Podman commands.
=> [docs] Remove redundant --rm flag

documentation/modules/ROOT/pages/connectors/mysql.adoc
In the description of the `database.ssl.keystore.password` property, the xref to the `database.ssl.keystore` property is incorrectly prefixed with the `{context}` attribute
(cherry picked from commit 13703c74577af767f002235557b70b456d4a7dcb)
=> [docs] remove unnecessary `context` attribute that prefixes xref target

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/JsonSerialization.java
See [Jira ticket](https://issues.redhat.com/browse/DBZ-7287) and [Zulip discussion](https://debezium.zulipchat.com/#narrow/stream/348106-community-mongodb/topic/Raw.20string.20manipulation.20during.20extraction.20of.20document.20keys)
The code in the lines at  https://github.com/debezium/debezium/blob/main/debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/JsonSerialization.java#L60-L66 seems at first to be a little convoluted – in order to get an id out of the document argument, it first extracts the id, then re-nests the id in a new document with a fieldname of fixed length, then serializes that, then extracts the id again, this time using raw string manipulation.
This seems odd but there's a good reason for it: it's tough to serialize scalar bson values and this is …
=> DBZ-7287 Clarify comment about how we extract and serialize document ids

debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/CloudEventsConverterIT.java, debezium-core/src/main/java/io/debezium/converters/CloudEventsConverter.java, debezium-core/src/main/java/io/debezium/converters/CloudEventsConverterConfig.java, debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadata.java, debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadataBaseImpl.java, debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadataHeaderImpl.java, debezium-core/src/main/java/io/debezium/converters/spi/CloudEventsMaker.java, debezium-core/src/main/java/io/debezium/converters/spi/RecordParser.java, debezium-core/src/test/java/io/debezium/converters/CloudEventsConverterTest.java, debezium-embedded/src/test/java/io/debezium/converters/AbstractCloudEventsConverterTest.java
To actually retrieve data schema name from the `dataSchemaName` header, a user should specify two properties:
```
"value.converter.metadata.source": "header",
"value.converter.schema.data.name.source.header.enable": true,
```
The second property by default is `false` which provides backward compatibility
If it is Outbox SMT + CloudEventsConverter integration, the header can be added as follows:
```
"transforms.outbox.table.fields.additional.placement": "type:header,aggregate_type:header:dataSchemaName",
```
=> DBZ-7284 Provide config option to customize CloudEvents.data schema name

documentation/modules/ROOT/partials/modules/tutorial/proc-cleaning-up.adoc, documentation/modules/ROOT/partials/modules/tutorial/proc-starting-kafka-connect.adoc, documentation/modules/ROOT/partials/modules/tutorial/proc-starting-kafka.adoc, documentation/modules/ROOT/partials/modules/tutorial/proc-starting-mysql-command-line-client.adoc, documentation/modules/ROOT/partials/modules/tutorial/proc-starting-mysql-database.adoc, documentation/modules/ROOT/partials/modules/tutorial/proc-starting-zookeeper.adoc, documentation/modules/ROOT/partials/modules/tutorial/proc-viewing-create-event.adoc
I removed the sudo prefix from the podman commands for the following reasons:
1. There's no need to run podman commands with sudo. It is unnecessary.
2. Pods created with sudo won't appear in Podman Desktop.
3. Maintain consistency with the Docker commands in the tutorial (they are not prefixed with sudo).
When `dbz` pod is created, only port 8083 will be published. This is because the host will only interact with Kafka Connect (8083) via curl. The host will not interact with Apache Zookeeper (9092) or MySQL (3306), thus opening these two ports in the pod is unnecessary.
=> [docs] Update Podman commands in the tutorial

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-7313](https://issues.redhat.com/browse/DBZ-7313)
Although the name of the metric that was added in #5137  includes the word "count", its description refers only to an undefined "size".
=> DBZ-7313 Provide more precise description of metric

debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java, documentation/modules/ROOT/pages/post-processors/reselect-columns.adoc
https://issues.redhat.com/browse/DBZ-7358
This fix uses the relational table primary key by default; however, as a user can define `message.key.columns` to even override the primary key configuration or to handle keyless tables, the user can override the `reselect.use.event.key` option with `true` so use the event key fields instead for the re-select so that keyless tables can also participate with the column reselection process.
=> DBZ-7358 Use relational table primary key by default

documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-nosql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-sql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-kafka.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-nosql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-sql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot.adoc
PR https://github.com/debezium/debezium/pull/4721 documented blocking snapshot added in [DBZ-6566](https://issues.redhat.com/browse/DBZ-6566). But it missed a
few spots.
Also, for consistency use "snapshot type" instead of "snapshot kind".
=> [docs] incremental snapshot: blocking snapshot are also supported

documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-7314](https://issues.redhat.com/browse/DBZ-7314) Follow-up to #5149 
This change includes the following updates:
- Reword note that follows Table 8, _Description of change event key_
- Reword description of `column.include.list` property to make it clear that settings must permit capture of primary key/unique key columns.
=> DBZ-7314 Update `column.include.list` note and property description

documentation/modules/ROOT/pages/connectors/sqlserver.adoc
This documents a new SQL Server connector setting introduced in #5122.
=> DBZ-7273: Document `data.query.mode` for sqlserver connector

COPYRIGHT.txt, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerDefaultValueConverter.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectionIT.java, jenkins-jobs/scripts/config/Aliases.txt
https://issues.redhat.com/browse/DBZ-7374
SQL server connector -- allow the default value mapper properly to accept character strings & Unicode character strings _**n(char|varchar|text)**_, when using NULL as the default value
=> DBZ-7374 Allow NULL as the default value for SQL server (Unicode) character strings

documentation/modules/ROOT/pages/configuration/notification.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/transformations/event-flattening.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-ad-hoc-snapshots.adoc
[DBZ-6997](https://issues.redhat.com/browse/DBZ-6997)
[DBZ-7039](https://issues.redhat.com/browse/DBZ-7039)
[DBZ-7046](https://issues.redhat.com/browse/DBZ-7046)
This change fixes formatting and link errors that result in downstream build failures.
These changes were previously applied downstream for the 2.3.4 release and were applied upstream to `main`, but not backported to `2.3`.
=> DBZ-7046 Backport formatting and link fixes to 2.3

documentation/modules/ROOT/pages/connectors/jdbc.adoc
[DBZ-7430](https://issues/redhat.com/browse/DBZ-7430)
In the last release, the JDBC connector was marked as _Dev Preview_ in the downstream doc repo only. 
This change adds a conditionalized DP statement to `jdbc.adoc` in the `2.3` branch so that any future 2.3 updates preserve that designation.  
The change has no effect on the community version of the documentation.
=> DBZ-7430 Mark JDBC connector in product doc as Dev Preview in 2.3 branch

debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java, debezium-microbenchmark/src/main/java/io/debezium/performance/core/IncrementalSnapshotContextPerf.java
a possibile solution for https://issues.redhat.com/browse/DBZ-7421
Before
```
Benchmark                             (numberOfTableToSnapshot)   Mode  Cnt       Score   Error  Units
IncrementalSnapshotContextPerf.store                          1  thrpt    2  962999.691          ops/s
IncrementalSnapshotContextPerf.store                          5  thrpt    2  118903.880          ops/s
IncrementalSnapshotContextPerf.store                         10  thrpt    2   31712.744          ops/s
IncrementalSnapshotContextPerf.store                         50  thrpt    2     786.632          ops/s
IncrementalSnapshotContextPerf.store                        100  thrpt    2     195.274          ops/s
```
After some code optimization
```
Benchmark                             (numberOfTableToSnapshot) …
```
=> DBZ-7421 Improve incremental snapshot performance with increasing number of collections to snapshot

COPYRIGHT.txt, documentation/modules/ROOT/pages/operations/debezium-server.adoc, jenkins-jobs/scripts/config/Aliases.txt
Correct case discrepancy for configuration variables between docs and pubsub sink connector https://github.com/debezium/debezium-server/blob/df953233220e5250129135fabf1d97212d77ea40/debezium-server-pubsub/src/main/java/io/debezium/server/pubsub/PubSubChangeConsumer.java#L98C3-L98C88
[DBZ-7443](https://issues.redhat.com/browse/DBZ-7443)
=> DBZ-7443 Correct debezium.sink.pubsub.flowcontrol variables

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SignalsIT.java, debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java, debezium-core/src/main/java/io/debezium/pipeline/signal/channels/KafkaSignalChannel.java
This will avoid, for channels that not depends on the event streaming like the 'source' channel, to start processing signals before the IncrementalSnapshotChangeEventSource is initialized.
closes: https://issues.redhat.com/browse/DBZ-7441
=> DBZ-7441 Postpone SignalProcessor start after streaming is initialized

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/events/LogMinerEventRow.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerEventRowTest.java
Oracle Connector can create a new string when reading SQL_REDO column only if CSF column value is 1.
https://issues.redhat.com/browse/DBZ-7446
=> DBZ-7446 Reduce string creation during SQL_REDO column read

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
The condition for increasing the LogMiner batch size must depend on `log.mining.batch.size.max`, and not on `log.mining.batch.size.min`.
https://issues.redhat.com/browse/DBZ-7445
=> DBZ-7445 LogMiner batch size does not increase automatically

COPYRIGHT.txt, debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java, jenkins-jobs/scripts/config/Aliases.txt
The "reselect.columns.exclude.list" property is not applied when configuring the connector. Configuration without exclude+include do not processed (all passed values ignoring).
Reason:
The reselectColumnInclusions predicate never becomes null.
Build filter condition is always true.
=> DBZ-7437: ReselectColumnsPostProcessor filter not use exclude predicate.

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
Logged a follow-up for this in https://issues.redhat.com/browse/DBZ-7453.
=> [ci] Mark testEmptyChangesProducesHeartbeat as flaky

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
Enclose column names in square brackets to account for spaces and special characters.
=> DBZ-7463: SQL Server queries with special characters fail after applying DBZ-7273

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/operations/monitoring.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-streams-deployment.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-db2-ora-pg-connector.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mongodb-connector.adoc
[DBZ-7440](https://issues.redhat.com/browse/DBZ-7440)
Review of the 2.3.7 documentation identified multiple broken links to targets in the Streams documentation.  
This change cherry picks link fixes that were previously applied to the `2.3` and `main` branches.
=> Dbz 7440 2.5 cherry pick link fixes from main

documentation/modules/ROOT/pages/connectors/jdbc.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/integrations/cloudevents.adoc, documentation/modules/ROOT/pages/operations/logging.adoc, documentation/modules/ROOT/partials/modules/tutorial/proc-updating-database-viewing-update-event.adoc
For unknown reasons, callout description lists that render correctly in the community Antora documentation are not rendered correctly in the productized documentation. Instead, entries for each numbered description are repeated one or more times.
To  work around the issue, this change modifies the formatting in the sources to convert callout lists to tables.
Tested in a local Antora build and in a local downstream build.
=> Dbz 7418 convert callout description lists to tables

documentation/modules/ROOT/pages/connectors/jdbc.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/integrations/cloudevents.adoc, documentation/modules/ROOT/pages/operations/logging.adoc, documentation/modules/ROOT/partials/modules/tutorial/proc-updating-database-viewing-update-event.adoc
DBZ-7418
Applies changes from `main` to `2.3` branch to address rendering anomalies by converting numbered lists of callout descriptions in the productized documentation into table format
=> Dbz 7418 cherry pick callout list conversion to 2.3

documentation/modules/ROOT/pages/connectors/jdbc.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/integrations/cloudevents.adoc, documentation/modules/ROOT/pages/operations/logging.adoc, documentation/modules/ROOT/partials/modules/tutorial/proc-updating-database-viewing-update-event.adoc
[DBZ-7418](https://issues.redhat.com/browse/DBZ-7418) Applies changes to convert callout lists to tables to address the wonky rendering of the lists in the productized documentation. 
Previously applied to `main` and `2.3`.
=> Dbz 7418 2.5 apply callout list fixes

documentation/modules/ROOT/pages/operations/logging.adoc
_Whack-a-mole_ fix to address a second callouts problem that cropped up in `logging.adoc`. This new instance of the problem only surfaced after I published the updated downstream doc with the fix to the original instance that occurs  earlier in the file.
=> Dbz 7418 fix additional callout list problem in logging doc

documentation/modules/ROOT/pages/operations/logging.adoc
Follows up on [DBZ-7418](https://issues/redhat.com/browse/DBZ-7418) changes.
This change removes the second `<3>` callout annotation from the `log4j.properties` example In `logging.adoc` and rewords the callout description to make it clear that it applies to two entries in the example.
In Step 2 of  `Setting the logging level by configuring loggers`, the example repeats the `<3>` callout annotation for each of the two `additivity.io.debezium` entries.  
In the published upstream documentation, this works, because the annotations for the two instances both show the expected `3`, which collates to the related callout description in the table that follows the example. However, in the downstream customer portal, the value of the second annotation renders as `4`, which has no related entry in …
=> DBZ-7418 Removes duplicate callout annotation from example

documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc
Re-structure and add more documentation about setting up the converters in the Outbox Event Router SMT. My objective is make it clear how to properly use JSON and Avro regarding the value converters, the db column types, and the delegate converter configuration.
I'm also adding an extra example of how to setup a delegate converter in Avro format.
Needless to say, this is just a suggestion and is open to any comment or recommendation.
Jira [DBZ-7368](https://issues.redhat.com/browse/DBZ-7368)
=> DBZ-7368: add more documentation for converters in outbox router

documentation/modules/ROOT/pages/integrations/cloudevents.adoc
Further fix to callout list rendering (CloudEvents)
Cherry-pick #5278 from `2.3`
=> Dbz 7418 2.5 branch cherry pick pr 5278 from 2.3

documentation/modules/ROOT/pages/connectors/index.adoc, documentation/modules/ROOT/pages/connectors/spanner.adoc, documentation/modules/ROOT/pages/install.adoc
Remove incubating from Debezium documentation since the connector has been launched for quite some time now.
=> DBZ-7501 Remove incubating from Debezium documentation

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java, debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java
Each time, Oracle connector creates a new instance of PreparedStatement because value of commit SCN is added directly to SQL query to reselect column values.
https://issues.redhat.com/browse/DBZ-7479
=> DBZ-7479 PreparedStatement leak in Oracle ReselectColumnsProcessor

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
Jira issue: https://issues.redhat.com/browse/DBZ-7500
Fixes: https://github.com/debezium/debezium/pull/5036
Applied to a MySQL 8 connector:
Proof of millisecond resolution `source.ts_ms`:
```json
"source": {
"query": "REDACTED",
"thread": 3683566,
"server_id": 12844,
"version": "2.6.0-SNAPSHOT",
"sequence": "",
"file": "binlog.726557",
"connector": "mysql",
"pos": 59658237,
"name": "REDACTED",
"gtid": "6aafb3ca-9b99-11ee-a237-4201f300802c:187141265",
"row": 0,
"ts_ms": 1708126035867,
"snapshot": "false",
"db": "REDACTED",
"table": "products"
},
```
=> Fix MySQL 8 event timestamp resolution logic error where fallback to seconds occurs erroneously for non-GTID events

documentation/modules/ROOT/pages/configuration/avro.adoc
Required JAR files are added to properly integrate the Debezium integration with AVRO and Confluent Schema Registry.
=> [docs] List required files for Confluent Avro converter

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SignalsIT.java
closes: https://issues.redhat.com/browse/DBZ-7526
=> DBZ-7526 Fix table name with escaped characters

documentation/modules/ROOT/pages/configuration/notification.adoc, documentation/modules/ROOT/pages/development/converters.adoc, documentation/modules/ROOT/pages/integrations/cloudevents.adoc
Addresses problem in downstream documentation portal where fixing the rendering a list of callout descriptions would cause rendering problems in the next instance. 
Proactively converts remaining description lists to tables in: 
- `configuration/notification.adoc`
- `development/converters.adoc`
- `integrations/cloudevents.adoc`
=> Dbz 7418 replace remaining callout description lists with tables

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java, debezium-core/src/test/java/io/debezium/connector/common/BaseSourceTaskTest.java
https://issues.redhat.com/browse/DBZ-6236
=> DBZ-6236 Reset ErrorHandler retry counter on successful poll

debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
closes: https://issues.redhat.com/browse/DBZ-7508
=> DBZ-7508 Exit from readChunk after createDataEventsForTable if snapshot is not running anymore

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
References https://issues.redhat.com/browse/DBZ-7567 and a null value edge case introduced in https://github.com/debezium/debezium/pull/5281 for the `FORMAT_DESCRIPTION` and `PREVIOUS_GTIDS` events which the MySQL connector does not directly handle.
I stumbled on them by logs from the `choked` event logger:
```
Feb 26, 2024 11:22:00 PM com.github.shyiko.mysql.binlog.BinaryLogClient notifyEventListeners
WARNING: io.debezium.connector.mysql.MySqlStreamingChangeEventSource$$Lambda$1860/0x00000008016a7b80@78ecf20b choked on Event{header=EventHeaderV4{timestamp=1708989435000, eventType=FORMAT_DESCRIPTION, serverId=6656, headerLength=19, dataLength=103, nextPosition=126, flags=0}, data=FormatDescriptionEventData{binlogVersion=4, serverVersion='8.0.34-26', headerLength=19, dataLength=98, …
```
=> DBZ-7567 Fix null event timestamp possible from FORMAT_DESCRIPTION and PREVIOUS_GTIDS events in MySqlStreamingChangeEventSource::setEventTimestamp

pom.xml
The current version is affected by [SNYK-JAVA-ORGPOSTGRESQL-6252740](https://security.snyk.io/vuln/SNYK-JAVA-ORGPOSTGRESQL-6252740)
The vulnerability fix is the only change in the [changelog](https://github.com/pgjdbc/pgjdbc/compare/REL42.6.0...REL42.6.1)
Jira [DBZ-7571](https://issues.redhat.com/browse/DBZ-7571)
=> DBZ-7571: Bump of PostgreSQL driver to 42.6.1

documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-db2-ora-pg-connector.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mongodb-connector.adoc
[DBZ-7499](https://issues.redhat.com/browse/DBZ-7499)
In the downstream documentation the step to create the connector resource when using Streams to deploy a connector contained an attribute name (`{context}`), rather than displaying the attribute value.
This change corrects formatting of the related source blocks so that attribute values correctly display.
Tested in a local downstream build. 
This change appears in a part of the source file that is conditionalized for the `product` build and has no effect on the community version of the documentation.
=> DBZ-7499 Fix deployment examples that expose attribute names vs values

COPYRIGHT.txt, debezium-api/src/main/java/io/debezium/engine/format/Binary.java, debezium-api/src/main/java/io/debezium/engine/format/SimpleString.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DebeziumEngineIT.java, debezium-embedded/src/main/java/io/debezium/embedded/ConverterBuilder.java, debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java, documentation/modules/ROOT/pages/operations/debezium-server.adoc, jenkins-jobs/scripts/config/Aliases.txt
Outbox event router supports arbitrary payload formats with BinaryDataConverter as the value.converter which passes payload transparently. However this is  currently not supported with the embedded engine which handles message conversion using value.format to specify the format.
In addition, when we want to pass payload transparently, it makes sense to also pass aggregateid i.e. the event key transparently. The default outbox table configuration specifies aggregateid as a varchar which is also not supported by embedded engine.
Propose to introduce the following change to support the above use cases.
1. Support for string and binary serialization formats on debezium api.
2. Allow configuring separate key and value formats on embedded engine.
=> DBZ-7512 Support arbitrary payloads with outbox event router on debezium server

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/AbstractProcessorUnitTest.java
Do not handle start event from V$LOGMNR_CONTENTS view if CLOB/BLOB support is disabled and memory buffer is used.
https://issues.redhat.com/browse/DBZ-7473
=> DBZ-7473 Defer transaction capture until the first DML event occurs

debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
Fixes https://issues.redhat.com/browse/DBZ-7614
Adds a try-catch block around the `validate` call, which means that we can catch NoClassDef exceptions when a jar file is missing from the plugin directory
=> Dbz 7614 Catch exceptions during validation

documentation/modules/ROOT/pages/post-processors/reselect-columns.adoc, documentation/modules/ROOT/pages/transformations/timezone-converter.adoc
[DBZ-7602](https://issues.redhat.com/browse/DBZ-7602)
- Adds tooling annotations to Timezone converter SMT and post processor documentation for productization.
- Docs also edited for language, formatting, style.
- Default lists of callout descriptions converted to tables to address downstream rendering problems (DBZ-7418)
=> Dbz 7602 prep new tz smt and post processor docs for downstream release

documentation/modules/ROOT/pages/connectors/vitess.adoc
It is a subtle behavior that should be documented. Although called ts_ms the precision is seconds converted to milliseconds. The examples are also misleading.
=> [docs] Vitess connector ts_ms is seconds level precision in milliseconds units

debezium-connect-rest-extension/src/main/java/io/debezium/kcrestextension/DebeziumConnectRestExtension.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouter.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/transforms/ReadToInsertEvent.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/transforms/timescaledb/TimescaleDb.java, debezium-core/src/main/java/io/debezium/Module.java, debezium-core/src/main/java/io/debezium/converters/BinaryDataConverter.java, debezium-core/src/main/java/io/debezium/converters/ByteArrayConverter.java, debezium-core/src/main/java/io/debezium/converters/CloudEventsConverter.java, debezium-core/src/main/java/io/debezium/transforms/AbstractExtractNewRecordState.java, debezium-core/src/main/java/io/debezium/transforms/ByLogicalTableRouter.java, debezium-core/src/main/java/io/debezium/transforms/ExtractChangedRecordState.java, debezium-core/src/main/java/io/debezium/transforms/ExtractSchemaToNewRecord.java, debezium-core/src/main/java/io/debezium/transforms/HeaderToValue.java, debezium-core/src/main/java/io/debezium/transforms/SchemaChangeEventFilter.java, debezium-core/src/main/java/io/debezium/transforms/TimezoneConverter.java, debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouter.java, debezium-core/src/main/java/io/debezium/transforms/partitions/PartitionRouting.java, debezium-core/src/main/java/io/debezium/transforms/tracing/ActivateTracingSpan.java, debezium-core/src/main/resources/io/debezium/build.version, debezium-microbenchmark/pom.xml, debezium-microbenchmark/src/main/java/io/debezium/performance/Module.java, debezium-microbenchmark/src/main/java/io/debezium/performance/core/FilterSmtPerf.java, debezium-microbenchmark/src/main/java/io/debezium/performance/core/SmtOverheadPerf.java, debezium-microbenchmark/src/main/resources/io/debezium/performance/build.version, debezium-scripting/debezium-scripting/pom.xml, debezium-scripting/debezium-scripting/src/main/java/io/debezium/transforms/Module.java, debezium-scripting/debezium-scripting/src/main/java/io/debezium/transforms/ScriptingTransformation.java, debezium-scripting/debezium-scripting/src/main/resources/io/debezium/scripting/build.version
https://issues.redhat.com/browse/DBZ-7618
=> DBZ-7618 Implement Versioned interfaces in Transformation and Converter plugins

debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/RedisConnection.java
https://issues.redhat.com/browse/DBZ-7646
=> DBZ-7646 Support empty or null user/passwords with Redis connections

debezium-connector-sqlserver/pom.xml
https://issues.redhat.com/browse/DBZ-7657
As a result of the discussion about Linux kernel compatibility: https://github.com/microsoft/mssql-docker/issues/868
=> DBZ-7657 Use SQL Server 2022 instead of 2019

COPYRIGHT.txt, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
This PR adds the missing test annotation `@Test` from the file `PostgresConnectorIT.java`.
=> [DBZ-7649] Add missing test annotation in PostgresConnectorIT

documentation/modules/ROOT/pages/connectors/mongodb.adoc
[DBZ-7647](https://issues.redhat.com/browse/DBZ-7647)
Updates the MongoDB documentation by adding an entry for `capture.mode.full.update.type` to  the table of Advanced connector configuration properties.
=> DBZ-7647 Adds capture.mode.full.update.type entry to config props table

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleXmlDataTypesIT.java, documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-6896
OpenLogReplicator 1.5 introduces XML support that works with Debezium. I have removed all skip annotations on such tests and updated documentation.
// cc @bersler
=> DBZ-6896 Enable XML tests for Oracle OpenLogReplicator

documentation/modules/ROOT/pages/connectors/cassandra.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/spanner.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc
[DBZ-6573](https://issues.redhat.com/browse/DBZ-6573)
Follow up to the original issue to provide more detail in the description of the `errors.max.retries` connector configuration property.  
Backport to 2.5 and 2.6.
=> DBZ-6573 Enhance description of errors.max.retries property

documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc
[DBZ-7653](https://issues.redhat.com/browse/DBZ-7653)
Adds and removes conditionalized DP and TP boilerplate text to reflect changes in release status of MongoDB, MySQL, and PostgreSQL connector features. 
Backport to 2.5 (bc 2.6 is not targeted for downstream release, I assume that no bp is needed there, unless we have strong feelings about keep branch content in sync).
=> Dbz 7653 adjust tech preview designations for 2.5 productization

debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/mongodb/sharded/OcpShardedReplicaMongoConnectorIT.java
for replicaset test added new tag and removed all others, so this test is ran only if explicitly specified
https://issues.redhat.com/browse/DBZ-7706
=> DBZ-7706 added mongo-sharded-replicaset tag to system tests

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/CustomSnapshotterIT.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, debezium-core/src/main/java/io/debezium/snapshot/SnapshotterServiceProvider.java, debezium-core/src/main/java/io/debezium/snapshot/mode/AlwaysSnapshotter.java, debezium-core/src/main/java/io/debezium/snapshot/mode/ConfigurationBasedSnapshotter.java, debezium-core/src/main/resources/META-INF/services/io.debezium.spi.snapshot.Snapshotter
closes: https://issues.redhat.com/browse/DBZ-7497
Provides an implementation of `Snapshotter` SPI that permits to configure it through connector configuration properties.
=> DBZ-7497 Add a configuration based snapshot modes configurable via connector properties

documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-7359](https://issues.redhat.com/browse/DBZ-7359)
- Fixes formatting of admonition title.
- Fix capitalization (unicode ==> Unicode).
- Remove use of possessive with trademarked terms (Unicode, SQL Server).
- Replace hardcoded name (Debezium) with reference to _the connector_.
- Fix reference to property being part of the connector configuration.
- Other edits for clarity.
Please backport to `2.5`.
=> DBZ-7359 Edit warning about data loss due to incompatible sorting rules

documentation/modules/ROOT/pages/connectors/mysql.adoc
[DBZ-7653](https://issues.redhat.com/browse/DBZ-7653) added duplicate notes that describe how use of the MySQL connector with MariaDB is a Tech Preview feature.  
This change removes the first instance of the note, and also adds a downstream mini-toc entry to link to the information about applying the MariaDB supplemental configuration.
Backport to 2.5.
=> [docs] Remove duplicate TP message about using connector with MariaDB

documentation/modules/ROOT/pages/connectors/mysql.adoc
DBZ-7653 added duplicate notes to inform downstream users that use of the MySQL connector with MariaDB is a Tech Preview feature. This change removes the first instance of the note and adds a downstream mini-toc entry that links to the topic about applying the MariaDB supplemental configuration.   
(cherry picked from commit f5e794b2ea56fb1fc6ec2cfaa96f025fc5d86207)
=> [docs] Remove duplicate downstream TP message re: use of connector w/MariaDB

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
closes: https://issues.redhat.com/browse/DBZ-7729
=> DBZ-7729 Fix shouldNotStreamWhenUsingSnapshotModeInitialOnly test assertion due to log message change

debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/strategy/AbstractConnectorConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java, debezium-core/src/main/java/io/debezium/function/LogPositionValidator.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
closes: https://issues.redhat.com/browse/DBZ-7717
=> DBZ-7717 Move LogPositionValidator outside JdbcConnection

documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-7754](https://issues.redhat.com/browse/DBZ-7754)
During review of the downstream docs, QE noticed that the connector YAML example in the deployment instructions still included a reference to the `database.names` property, even though that property is no longer supported. This change removes that line from the example. 
This change applies to the downstream documentation only and does not affect the version that's published to the community site.
=> DBZ-7754 Removes `database.names` entry from connector yaml example

pom.xml
JIRA ticket: https://issues.redhat.com/browse/DBZ-7757
Applies https://github.com/osheroff/mysql-binlog-connector-java/pull/141 which addresses a bug that manifests like this for very large transactions:
```
io.debezium.DebeziumException: Failed to deserialize data of EventHeaderV4
{timestamp=1709171907000, eventType=GTID, serverId=28775006, headerLength=19, dataLength=62, nextPosition=80207890, flags=0}
at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1091)
at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onEventDeserializationFailure(MySqlStreamingChangeEventSource.java:1144)
at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1081)
at …
```
=> Bump the MySQL binlog client version to 0.29.1 (fixes a bug when deserializing a large gtid transaction's length)

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Addressing https://issues.redhat.com/browse/DBZ-7750
=> DBZ-7750: Set default for max.iteration.transactions to 500

COPYRIGHT.txt, debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/RedisConnection.java
This PR aims to fix NOAUTH authentication required error thrown when redis database index property is specified in the configuration
You can see the details of the issue here:
https://issues.redhat.com/browse/DBZ-7740
=> DBZ-7740 Fixed NOAUTH authentication required error while initializing Redis connection

.github/workflows/debezium-workflow-push.yml
@ani-sha can you double-check my logic here, the idea is that on pushes, this would make sure that we check out the sibling repository with the same branch name as in the core repository, i.e. `main`, `2.6`, etc.  
@jpechane if Anisha gives this the green light, we should backport this to 2.6.
=> [ci] Use github.ref_name on pushes for sibling checkouts

documentation/modules/ROOT/pages/connectors/mongodb.adoc
[DBZ-6116](https://issues.redhat.com/browse/DBZ-6116)
This documentation was previously merged, but never received my review/approval. 
Per style guidelines, `please` is not for use in _"technical information or in instructions. Terms of politeness are superfluous, convey the wrong tone for technical material, and are not regarded the same way in all cultures. "_
Also, updated the reference to the database to refer to its correct trade name, and made other edits intended to enhance clarify.
=> DBZ-6116 Rewrite to comply with style guidelines

debezium-microbenchmark-engine/src/main/java/io/debezium/performance/engine/DebeziumEnginePerf.java, debezium-microbenchmark-engine/src/main/java/io/debezium/performance/engine/connector/PreComputedRecordsSourceConnector.java
https://issues.redhat.com/browse/DBZ-7776
Example output (and yes, very poor async-engine results are not a mistake, see DBZ-7777):
Benchmark                                        (processingOrder)  (recordCount)  (threadCount)  Mode  Cnt    Score   Error  Units
DebeziumEnginePerf.processRecordsAsyncEngine               ORDERED         100000              1    ss       295.353           s/op
DebeziumEnginePerf.processRecordsAsyncEngine               ORDERED         100000              2    ss       310.652           s/op
DebeziumEnginePerf.processRecordsAsyncEngine               ORDERED         100000              4    ss       305.956           s/op
DebeziumEnginePerf.processRecordsAsyncEngine               ORDERED         100000              8    ss       334.755           s/op …
=> DBZ-7776 JMH benchmarks for engine processing only

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mariadb/generated/MariaDBParser.g4, debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4, debezium-ddl-parser/src/test/resources/mariadb/examples/fast/ddl_create.sql, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-7788
@jpechane I separated these as only the one applicable for MySQL should be backported since the MariaDB one will only be relevant to 2.7 with the new connector grammar.
=> DBZ-7788 Support with statement/clause in binlog connectors

debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtAndConvertAsyncConsumerProcessor.java, debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtAndConvertConsumerProcessor.java, debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtAsyncConsumerProcessor.java, debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtConsumerProcessor.java, debezium-microbenchmark-engine/src/main/java/io/debezium/performance/engine/AbstractDebeziumEnginePerf.java, debezium-microbenchmark-engine/src/main/java/io/debezium/performance/engine/DebeziumConvertingEnginePerf.java, debezium-microbenchmark-engine/src/main/java/io/debezium/performance/engine/DebeziumEnginePerf.java
ParallelSmtAndConvertConsumerProcessors:
Before the change:
Benchmark                                        (processingOrder)  (recordCount)  (threadCount)  Mode  Cnt    Score   Error  Units
DebeziumEnginePerf.processRecordsAsyncEngine               ORDERED         100000              1    ss       295.353           s/op
DebeziumEnginePerf.processRecordsAsyncEngine               ORDERED         100000              2    ss       310.652           s/op
DebeziumEnginePerf.processRecordsAsyncEngine               ORDERED         100000              4    ss       305.956           s/op
DebeziumEnginePerf.processRecordsAsyncEngine               ORDERED         100000              8    ss       334.755           s/op
DebeziumEnginePerf.processRecordsAsyncEngine               ORDERED …
=> DBZ-7777 Improve processing speed of async engine processors which use List#get()

documentation/modules/ROOT/pages/transformations/filtering.adoc
- Fixes DBZ-7798
- Refs https://github.com/debezium/debezium/pull/5500
The original PR missed another occurrence of `headers` vs. `header`.
=> DBZ-7798 Fix documentation for `header` variable in filters (part 2)

documentation/modules/ROOT/pages/connectors/mongodb.adoc
[DBZ-7789](https://issues.redhat.com/browse/DBZ-7789)
Adds warning admonition to the description of the `lookup` option of the MongoDB `capture.mode.full.update.type` property.
=> DBZ-7789 Adds warning explaining unexpected behavior of `lookup` setting

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/informix.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/spanner.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc, documentation/modules/ROOT/partials/modules/all-connectors/frag-common-mbean-name.adoc
[DBZ-7800](https://issues.redhat.com/browse/DBZ-7800)
This change includes the following updates:
- Adds a shared topic to describe how you can customize the default MBean names that Debezium uses for connector metrics. 
- Updates descriptions for the `custom.metric.tags` property in the documentation for each connector.
- Inserts a _Customized MBean names_ topic heading in the documentation file for each connector,  and adds an `include` directive that pulls in the shared topic.
During downstream testing, I discovered that changes implemented in [DBZ-7304](https://issues.redhat.com/browse/DBZ-7304) resulted in ID collisions because the same anchor ID is used multiple times in the upstream files.  I opened …
=> Dbz 7800 enhance docs about using tags to customize mbean names

debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/jdbc/BinlogValueConverters.java, debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogValueConvertersTest.java
That warn message could happen for every event processed in the worst case so change to debug.
Also there's an edge case with the year zero value that can still be valid.
https://issues.redhat.com/browse/DBZ-7811
=> DBZ-7811 Reduce logging level for invalid timestamp/date values, fix edge case

documentation/modules/ROOT/pages/transformations/timezone-converter.adoc
[DBZ-7803](https://issues.redhat.com/browse/DBZ-7803)
Fixes an incomplete sentence in the Timezone converter SMT doc to indicate that the SMT adjusts time values in the original message to reflect the configured target timezone.
=> DBZ-7803 Fixes incomplete sentence in TZ converter SMT doc

documentation/modules/ROOT/pages/transformations/timezone-converter.adoc
(cherry picked from commit 1aaa39241c60916669ec9da1b55c055725a83223)
Backport to 2.5 to apply correction to published downstream doc.
=> DBZ-7803 Finish incomplete sentence in TZ converter SMT doc

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/transformations/outbox-event-router.adoc
[DBZ-7815](https://issues.redhat.com/browse/DBZ-7815)
Ensures uniqueness of anchor IDs in connector docs and makes other corrections to fix build errors in downstream documentation.
This changes requires a backport to 2.7.
=> Dbz 7815 fix doc anchor id collisions

pom.xml
https://issues.redhat.com/browse/DBZ-7841
* Quarkus to 3.8.3
* Netty to 4.1.107.Final
* Apicurio 2.5.8.Final
Sibling PR in Debezium Server repository - https://github.com/debezium/debezium-server/pull/88
=> DBZ-7841 Bump Quarkus to 3.8.3 for Debezium Server

debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogReadOnlyIncrementalSnapshotIT.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/BlockingSnapshotIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java, debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractSnapshotTest.java
closes: https://issues.redhat.com/browse/DBZ-7806
@jpechane The intent here is to skip the search on the WAL when the connector has an offset that is the result of the initial snapshot. Not sure if there is a better way to check this condition.
=> DBZ-7806 Skip search for WAL position when offset exist and is just after the initial snapshot

COPYRIGHT.txt, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
[The documentation](https://github.com/debezium/debezium/blob/main/debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngineConfig.java#L184) of `errors.max.retries` states that `-1` should mean _unlimited_, but the implementation doesn't handle it.
We discovered this because we have these two messages in the log (after Postgres update), and the Debezium wasn't processing any data then.
```
Retriable exception thrown, connector will be restarted; errors.max.retries=-1
Can't start the connector, max retries to connect exceeded; stopping connector...
```
=> DBZ-7870 default value of -1 for connection error retries interpreted as no limit

COPYRIGHT.txt, debezium-core/src/main/java/io/debezium/data/Envelope.java, debezium-core/src/test/java/io/debezium/data/EnvelopeTest.java, jenkins-jobs/scripts/config/Aliases.txt
reduce Java enum array allocation by caching the result of .values() method.
Reference:
https://www.gamlor.info/wordpress/2017/08/javas-enum-values-hidden-allocations/
https://issues.redhat.com/projects/DBZ/issues/DBZ-7859
=> DBZ-7859: reduce enum array allocation

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java
…ostgres types first. Does not override types that are already registered (e.g does not allow orafce module types to be registered and override default postgres types)
=> DBZ-5182 Fetch Postgres types by ascending order

debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
https://issues.redhat.com/browse/DBZ-7871
=> DBZ-7871 Change logging level for `Found previous partition offset`

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java, documentation/modules/ROOT/pages/connectors/mongodb.adoc
https://issues.redhat.com/browse/DBZ-7862
@roldanbob  Feel free to update as you see fit.
=> DBZ-7862 Updated MongoDB connector docs to reflect replica_set connection mode removal

documentation/modules/ROOT/pages/post-processors/index.adoc
[DBZ-7890](https://issues.redhat.com/browse/DBZ-7890)
Aligns text of post processors `index.adoc` file with the downstream version, and removes incubation note.  
The product docs do not use this file, so this update has no affect on the downstream version.
Per @Naros, it's safe to apply this change to 2.6 and later.
=> DBZ-7890 Updates text of PP index file and removes incubation note

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SpecialCharsInNamesIT.java
In the case when there is a `#` in a column name it gets replaced with the capture instance name according to how the CDC data query is built.
This patch makes the replacement more specific by changing the replacement placeholder from `#` to `#table` in this particular case.
=> DBZ-7893: Account for possible `#` in a column name

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, debezium-core/src/main/java/io/debezium/relational/ChangeTable.java
There is a small chance the connector doesn't advance and re-reads the same LSN range. This happens under the following conditions:
* a new capture instance has been added in the current LSN range;
* while reading CDC changes one of existing capture instances dissapears. 
The dissapeared capture instance causes an exception which is catched and processed in `processErrorFromChangeTableQuery`. This leads to the current connector iteration to be correctly exited without advancing. On the next iteration the connector starts from the same LSN as the previous iteration and finds the same new capture instance. Although `Set` was used to track the list of tables to be removed `SqlServerChangeTable` doesn't implement `hashCode` so same table could be added multiple times to the same set.
The fix …
=> DBZ-7889: Multiple completed reading from a capture instance notifications

debezium-core/src/main/java/io/debezium/relational/mapping/ColumnMappers.java, debezium-core/src/main/java/io/debezium/relational/mapping/MaskStrings.java, debezium-core/src/main/java/io/debezium/relational/mapping/TruncateColumn.java, debezium-core/src/test/java/io/debezium/relational/mapping/TruncateColumnTest.java
Expand truncate strings to also work for byte buffers (e.g., for mysq/vitess blob types).
Rename class from TruncateStrings to TruncateColumn to be more generically named, and we can expand to include any other types that we want to truncate going forward.
We added an itest in vitess-connector repo that is passing locally with these changes https://github.com/debezium/debezium-connector-vitess/pull/198
=> DBZ-7925 Expand truncate support to byte arrays in addition to strings

documentation/modules/ROOT/pages/integrations/cloudevents.adoc
[DBZ-7926](https://issues.redhat.com/browse/DBZ-7926)
To align with an earlier code change ([DBZ-7216](https://issues.redhat.com/browse/DBZ-7216)), this issue makes the following changes to the CloudEvents documentation:
- Updates the format that is used for values of the `type` field of a CloudEvents change record.
- Implements other related minor formatting changes.
Changes were tested in a local Antora build.
=> DBZ-7926 Update format of `type` field values in CloudEvent records 

debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
Fibonacci pollIntervals cause some tests to take very long time. Changing to fixed interval (100 millis) like other wait-methods.
=> DBZ-7813: waitForAvailableRecords fix Awaitility pollInterval

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4, debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-7931
@Naros I think similar issues had come up regarding ordering of the constraints. In this particular issue, the DDL should be using the `out_of_line_constraint`, but it doesn't. Even if we did a reordering in the past for the `relational_property` so the preference would be given to `out_of_line_constraint` before using the `column_definition` clause, it didn't work as the definition of `out_of_line_constraint` goes by 
```
out_of_line_constraint
: (CONSTRAINT constraint_name)?
```
But if DDL contains has `CONSTRAINTS`, it would go to the `column_definition` clause and end up near the `inline_clause` throwing an error. 
Adding the change in the PR works for corner cases. But it also makes me wonder why the DDL failed earlier near the …
=> DBZ-7931 Modify out_of_line_constraint clause

COPYRIGHT.txt, documentation/modules/ROOT/pages/connectors/mongodb.adoc
DBZ-7260 Removed multi-task capability, so I'm removing notice about this function from docs.
=> [docs] Remove no longer valid note

COPYRIGHT.txt, debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/history/JdbcSchemaHistory.java, debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/offset/JdbcOffsetBackingStore.java
PostgreSQL does not auto-commit DDL statements so, currently, other clients trying to execute DDL statements might get stuck until commit is invoked in storeRecord for instance.
=> Call commit after running DDL statements

documentation/modules/ROOT/pages/connectors/jdbc.adoc
https://issues.redhat.com/browse/DBZ-6618
=> DBZ-6618 Document usage of `${source.` prefix for table name formatting

documentation/modules/ROOT/pages/connectors/informix.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/spanner.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/connectors/vitess.adoc
[DBZ-7968 ](https://issues.redhayt.com/browse/[DBZ-7968)
Updates the downstream title for the connector topics about customizing the connector MBean name. The published version of the documentation incorrectly repeats the Db2 version of the title in each of the connector docs.
The `Title` annotation comment for the _Customized MBean names_ topic is present in all of the source connector docs, including the docs for connectors that are not exposed downstream. Strictly speaking, this update it was not necessary in the Informix, Spanner, and Vitess documentation, but there was no harm in making those changes, so I went ahead with them.   
This change applies only to the productized Debezium documentation. The updates are not visible in the community version of the documentation.
=> DBZ-7968 Replace incorrect Title annotation comments in connector docs

documentation/modules/ROOT/pages/connectors/postgresql.adoc
This patch documents possible inconsistency issues caused by replication slots.
=> Document Postgres' Limitations

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java, debezium-core/src/test/java/io/debezium/connector/common/BaseSourceTaskSnapshotModesValidationTest.java, debezium-core/src/test/java/io/debezium/connector/common/BaseSourceTaskTest.java
https://issues.redhat.com/browse/DBZ-7964
=> DBZ-7964 (quickfix) Only reset error retry counter if poll() successfully produced records

debezium-quarkus-outbox-common/pom.xml, debezium-quarkus-outbox-reactive/pom.xml, debezium-quarkus-outbox/pom.xml
https://issues.redhat.com/browse/DBZ-7224
Follows on https://github.com/debezium/debezium/pull/5654
replaces https://github.com/debezium/debezium/pull/5659
=> DBZ-7224 Switched to centralised JDK version control for Quarkus Outbox

documentation/modules/ROOT/pages/development/converters.adoc
In the custom converters documentation, the introductory topic includes a note that specifies that these converters are for use only with relational database source connectors. DBZ-8031 added information to explicitly state that custom converters are not intended for use with sink connectors, such as the Debezium JDBC sink connector.
However,  later in the document, the _Configuring and Using Converters_ and _Configuring a custom connector_ topics do not mention anything about the requirement to use a relational database connector. To remove any ambiguity and reinforce the message that you cannot configure a custom converter for the MongoDB connector, this change adds information to explicitly state that you can only configure a custom converter  for a  relational database connector.
=> [docs] Specify that custom converters require relational DB connector

documentation/modules/ROOT/pages/development/converters.adoc
(cherry picked from commit 9bc7b1f7e35afda6a7b7a1830536f93ca90b0ab7)
In the custom converters documentation, the introductory topic includes a note that specifies that these converters are for use only with relational database source connectors. DBZ-8031 added information to explicitly state that custom converters are not intended for use with sink connectors, such as the Debezium JDBC sink connector.
However, later in the document, the _Configuring and Using Converters_ and _Configuring a custom connector_ topics do not mention anything about the requirement to use a relational database connector. To remove any ambiguity and reinforce the message that you cannot configure a custom converter for the MongoDB connector, this change adds to the 2.7 branch the information that explicitly …
=> DBZ-8031 Specify that custom converters require relational DB connector

COPYRIGHT.txt, documentation/modules/ROOT/pages/connectors/spanner.adoc
The spanner connector is getting support for FLOAT32 type in https://github.com/debezium/debezium-connector-spanner/pull/92. This is documenting the data type mapping.
It uses the correct spanner type names (`s/FLOAT/FLOAT32`, `s/DOUBLE/FLOAT64`), and the earlier mapping of `FLOAT -> DOUBLE` to `FLOAT64 -> DOUBLE`
=> DBZ-8043 Document the support for spanner's FLOAT32 type

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-7895](https://issues.redhat.com/browse/DBZ-7895)
DBZ-7895, which seeks clarification about whether the Debezium Oracle connector can use a physical vs. a logical standby database, was submitted based on the 2.5 release of the connector.  This change backports PR #5672 to the `2.5` branch so that we can refresh the 2.5.4 product doc with the new information.
=> Dbz 7895 cherry pick oracle logical standby from main to 2.5

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-7895](https://issues.redhat.com/browse/DBZ-7895)
This change addresses a customer issue about confusion over whether the Oracle connector worked with a physical standby database.   
Please backport to 2.7. 
To address the original customer in 2.5.4, I'll create a separate PR to apply the change to the 2.5 branch.
=> DBZ-7895 Specify that Oracle connector captures from logical standby

debezium-embedded/src/main/java/io/debezium/embedded/ClientProvided.java, debezium-embedded/src/main/java/io/debezium/embedded/ConverterBuilder.java
This PR in combination with a PR from Debezium Server supports the ability to do custom converters. Internally we have multiple custom converters and needed to build our own modules and hardcore our class names.
Now we can do the following: (operator spec)
```
type: clientprovided
config:
class: com.shopify.cdc.transforms.ByteArrayHeaderConverter
```
If you don't provide the config
```
java.lang.RuntimeException: Failed to start quarkus
at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
at io.quarkus.runtime.Application.start(Application.java:101)
at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
at …
```
=> DBZ-8040: Custom Converter Support

documentation/modules/ROOT/pages/operations/debezium-server.adoc
Update documentation of config options for Standard Webhooks authentication.
Main PR: https://github.com/debezium/debezium-server/pull/108
=> DBZ-8063 Add documentation for webhook auth config

COPYRIGHT.txt, debezium-core/src/main/java/io/debezium/config/Configuration.java, jenkins-jobs/scripts/config/Aliases.txt
In https://github.com/debezium/debezium-server/pull/108 a new configuration value `debezium.sink.http.authentication.webhook.secret` has been introduced. This value is currently not marked as a password and will be logged during initialization.
=> DBZ-8078 Standard Webhooks auth secret config value is not marked as PASSWORD_PATTERN

jenkins-jobs/pipelines/release/release-pipeline.groovy
https://issues.redhat.com/browse/DBZ-8088
@jpechane this is the follow-up we discussed for https://github.com/debezium/container-images/pull/386.  I'm not sure since this also modifies the release pipeline for 2.7 if this needs to be backported, deferring to you.
=> DBZ-8088 Add MariaDB connector to release pipeline

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-8055
We have identified cases where on Oracle RAC, due to each node flushing LGWR buffers independently, we cannot rely precisely on the existing LogMiner SCN range calculation.  In short, the range's `endScn` needs to be capped based on the minimum `LAST_REDO_CHANGE#` in `V$THREAD`, which represents the data of the last redo thread flush.  This cap is only applied to open redo threads, any threads that are disabled or closed will not factor into the upper bound cap.
=> DBZ-8055 Cap LogMiner range to min open redo thread last scn

documentation/modules/ROOT/pages/connectors/mariadb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc
This change relocates the  `MARIADB` and `MYSQL` attributes that are declared at the head of the `mariadb.adoc` and `mysql.adoc` files so that they are not listed with a conditionalized block.
Because the files that provide shared content for the MariaDB and MySQL connectors contain a subset information that is not common to both, the files use `ifdef` statements with the `MARIADB` and `MYSQL` attributes to identify connector-specific content. After building a downstream version of the documentation, I found that the content inside the `ifdef` directive was not rendered correctly. During troubleshooting, I realized that I mistakenly declared the attributes in a block that is conditionalized for `community` use.
=> [docs] Declare attributes outside of `community`-conditionalized blocks

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-8124](https://issues.redhat.com/browse/DBZ-8124)
Provides guidance about how you might reduce the scope of the permissions that you set when creating the Debezium LogMiner user.
=> DBZ-8124 Adds info about limiting the scope of FLASHBACK/SELECT grants

documentation/modules/ROOT/pages/operations/logging.adoc
[DBZ-8117](https://issues.redhat.com/browse/DBZ-8117)
This change updates instances in `logging.adoc` that incorrectly refer to the log4j properties file as `log4j.properties` rather than `connect-log4j.properties`. In addition, to improve scannability, unique titles are applied to examples, and example formatting is also applied.
=> DBZ-8117 Correct log file name; add example titles and formatting

documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc
[DBZ-8081](https://issues.redhat.com/browse/DBZ-8081)
This change conditionalizes the default value field of the `schema.history.internal.store.only.captured.databases.ddl` property  in the shared `ref-connector-configuration-database-history-properties.adoc` file to render the value `true` for the MariaDB and MySQL connectors, and `false` in all other contexts.
=> DBZ-8081 Conditionalize default value field of schema.history.internal.store.only.captured.databases.ddl property 

debezium-connector-postgres/pom.xml, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchemaFactory.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/transforms/DecodeLogicalDecodingMessageContent.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/CloudEventsConverterIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/transforms/DecodeLogicalDecodingMessageContentTest.java, debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadataHeaderImpl.java, debezium-core/src/main/java/io/debezium/transforms/ConnectRecordUtil.java, debezium-core/src/main/java/io/debezium/transforms/outbox/JsonSchemaData.java
The transform:
1) puts the encoded binary data (only `BYTES` case) to `after` field and replaces `op` field value with `c` that makes a record suitable for Outbox SMT
2) supposes that a logical decoding messages contains data in JSON form
3) is not tested with non-Postgres logical decoding messages
=> DBZ-8103 Add SMT to decode binary content of a logical decoding message

pom.xml
https://issues.redhat.com/browse/DBZ-8095
=> DBZ-8095 Bump Quarkus to 3.8.5 & Apicurio to 2.5.8.Final

documentation/modules/ROOT/pages/configuration/signalling.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-ad-hoc-snapshots.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-kafka.adoc
[DBZ-8107](https://issues.redhat.com/browse/DBZ-8107)
Removes entries for the `additional-condition` parameter from snapshot and signal tables that describe the fields in signal records.
Please backport to 2.7.
=> DBZ-8107 Remove references to `additional-condition` signal paramter

debezium-core/src/main/resources/META-INF/services/io.debezium.spi.snapshot.Snapshotter
closes: https://issues.redhat.com/browse/DBZ-8147
=> DBZ-8147 Add SchemaOnlyRecoverySnapshotter to SPI service implementation

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/ReplicationConnectionIT.java
Addressing https://issues.redhat.com/browse/DBZ-8127
=> DBZ-8127: Use SQLState instead of error strings

debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java, debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractSnapshotTest.java, debezium-embedded/src/test/java/io/debezium/transforms/outbox/AbstractEventRouterTest.java, documentation/modules/ROOT/pages/connectors/informix.adoc
In AbstractEventRouterTest, start connector after altering schema to avoid having to stop and start it again for Informix (which does not permit altering schema during capture)
=> Adaptions for Informix integration tests (DBZ-8114)

debezium-embedded/src/main/java/io/debezium/embedded/ConverterBuilder.java, debezium-embedded/src/test/java/io/debezium/embedded/async/AsyncEmbeddedEngineTest.java, debezium-embedded/src/test/java/io/debezium/embedded/async/FixedValueHeader.java
Part of: https://issues.redhat.com/browse/DBZ-8082
We want to be able to use headers in the key/value converter. When a configuration is set, the headers will be passed through to the converters.
My gut reaction to the increased complexity this configuration adds would be to keep the code clean and change the default behaviour. Converters by default call the current method if you pass the Headers so I think we don't need a configuration. I understand the extra `cast` will be slower - but I'm curious if that really warrants the extra complexity.
```
/**
* Convert a Kafka Connect data object to a native object for serialization,
* potentially using the supplied topic and headers in the record as necessary.
*
* <p>Connect uses this method directly, and for backward compatibility reasons this …
```
=> DBZ-8082: Pass Headers to Key/Value Converters

COPYRIGHT.txt, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresMoneyIT.java, jenkins-jobs/scripts/config/Aliases.txt
The fallback value is now been created in accordance with decimalMode that is set in the connector configuration. So it always fits the scheme.
=> DBZ-8027 updated type "money" fallback value creating.

debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractChunkQueryBuilder.java, debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/DefaultChunkQueryBuilderTest.java
Fixes https://issues.redhat.com/browse/DBZ-7797
=> DBZ-7797 Fail fast if surrogate key for incremental snapshot doesn't exist

debezium-storage/debezium-storage-tests/pom.xml
https://issues.redhat.com/browse/DBZ-8169
upgrade to latest version of s3mock
https://github.com/adobe/S3Mock/releases
=> DBZ-8169 Upgrade Adobe s3mock to 3.10.0

COPYRIGHT.txt, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresReselectColumnsProcessorIT.java, debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java, jenkins-jobs/scripts/config/Aliases.txt
The `isUnavailableValueHolder` method checks if a field of type JSON matches the `unavailableValuePlaceholderJson`. However, the actual value was stored as `unavailableValuePlaceholder` using PostgreSQL's JSON/B fields.
I'm not entirely sure if this is the best approach, but I have modified the condition to always check for the `unavailableValuePlaceholder` string. Additionally, if the field is of JSON type, it will also check if the value matches `unavailableValuePlaceholderJson`.
A better approach would actually save the unavailable value correctly with JSON/JSONB fields, but since strings are also a valid JSON object, I made it like that.
Reference:
https://issues.redhat.com/browse/DBZ-8168
https://debezium.zulipchat.com/#narrow/stream/348249-community-postgresql/topic/JSONB.20Fields.20 …
=> DBZ-8168 Fix issue with reselecting JSONB fields in PostgreSQL

.github/workflows/debezium-workflow-pr.yml
- Runtime: ~30 minutes
* Core dependencies update ~17m
* Debezium Server update ~9m
- Runtime: ~3m 30 seconds
* Core dependencies update ~2m
* Debezium Server update ~1m
This should help get pull requests running the tests significantly faster without sacrificing any stability in the checks by electing to try and reuse the caches based on this precedence:
1. Uses the PR's previously executed cache if it exists
2. Fallback to push to target branch cache where the hash of core pom.xml files hasn't changed (no deps changed)
3. Fallback to the most recent push to target branch cache, overlaying this PR's dep changes as needed
Options (2) and (3) get the PR up and testing faster, while storing the cache using this PR's metadata so that on future pushes to the PR, it will attempt to use (1) as …
=> [ci] Speed up the "Update dependencies" stage on CI

debezium-api/src/main/java/io/debezium/engine/DebeziumEngine.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SignalsIT.java, debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java, debezium-core/src/main/java/io/debezium/pipeline/signal/SignalRecord.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngineSignaler.java, debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java, debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEngineSignaler.java, debezium-embedded/src/main/java/io/debezium/engine/source/EngineSourceTask.java, debezium-embedded/src/test/java/io/debezium/embedded/async/AbstractAsyncEngineConnectorTest.java, debezium-embedded/src/test/java/io/debezium/embedded/async/TestingAsyncEmbeddedEngine.java
https://issues.redhat.com/browse/DBZ-8160
THe original approach proved to be poorly usable as there was no way to ensure (or know) which implementation of signaler to use. This PR does the following
- Add Signal record to DebeziumEngine API
- Simplifies Signaler interface so that it always accepts Signal
- Moves the responsibility of creating Signaler to the engine implementations
- Exposes Signaler via DebeziumEngine API
this allows use as following 
```java
engine.getSignaler().signal(mySignal)
```
=> DBZ-8160 Update engine's signal API

debezium-core/src/main/java/io/debezium/relational/mapping/TruncateColumn.java, debezium-core/src/test/java/io/debezium/relational/mapping/TruncateColumnTest.java
[DBZ-8189](https://issues.redhat.com/browse/DBZ-8189)
For some converters they properly only look at the byte buffer slice. However for Kafka Connect's [default json converter](https://github.com/apache/kafka/blob/3.8.0/connect/json/src/main/java/org/apache/kafka/connect/json/JsonConverter.java#L631) it gets the underlying array which undoes the truncate logic. So we fix that here by returning a new byte buffer & new byte array that way no subsequent converter can access the original untruncated byte array.
Add unit test to reproduce the error with the call to get the underlying array that the slice view is referencing.
We also had a case where a connector we were running ran into this issue & RecordTooLargeException and deploying this change fixed it.
=> DBZ-8189 Return new byte array/buffer when truncating

documentation/modules/ROOT/pages/configuration/signalling.adoc, documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/informix.adoc, documentation/modules/ROOT/pages/connectors/mariadb.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-incremental-snapshot.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-running-an-ad-hoc-snapshot-with-additional-conditions.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-kafka.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-nosql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-sql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-sql.adoc
Cherry-picks multiple changes from `main` to `2.7` 
[DBZ-8090](https://issues.redhat.com/browse/DBZ-8090)
Updates the incremental snapshot documentation to correct the format for specifying fully qualified table names in snapshot signals. A relatively simple content change that's made complex due to the many moving parts. This PR includes the following changes:
-     Refactors the existing shared files to reference new snippet files that host examples with the appropriate FQ names for each context.
-     Edits content to clarify the use of multiple signaling channels and place information about the proper naming formats in-line vs. relying on cross-references to descriptions in configuration properties.
-     Defines new attribute collection-container to identify the container used to …
=> DBZ-8090 Cherry-pick from main to 2.7

documentation/modules/ROOT/nav.adoc, documentation/modules/ROOT/pages/connectors/index-sink.adoc, documentation/modules/ROOT/pages/connectors/index.adoc
[DBZ-8220](https://issues.redhat.com/browse/DBZ-8220)
Add separate Sink connectors section to Navigation in community version of the docs.
This change should be backported to 2.7.
Because this change is not directly reflected in the product documentation repo, a separate MR applies a parallel change downstream: https://gitlab.cee.redhat.com/red-hat-integration-documentation/integration/-/merge_requests/1875
=> Dbz 8220 add source and sink connectors sections to documentation nav

documentation/modules/ROOT/pages/connectors/mariadb.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-nosql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-sql.adoc
[DBZ-8227](https://issues.redhat.com/browse/DBZ-8227)
Adds TP statement conditionalized for product use to the MariaDB connector docs. This change is not rendered in the community version of the documentation.
Also backporting the change to 2.7.
=> Dbz 8227 add technology preview admonition for mariadb connector

documentation/modules/ROOT/pages/connectors/mariadb.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-nosql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-sql.adoc
[DBZ-8227](https://issues.redhat.com/browse/DBZ-8227)
Cherry-pick commits from main to 2.7 to add TP admonition to MariaDB doc.
=> Dbz 8227 apply mariadb tp admonition to 2.7 branch

documentation/modules/ROOT/pages/operations/logging.adoc
[DBZ-8231](https://issues.redhat.com/browse/DBZ-8231)
Revises the target of a link in `logging.adoc` to point to a new location in the Streams for Apache Kafka doc.   Both the attribute reference and the target ID in the original link were obsolete.
A related downstream change updates the value of the `LinkDeployManageStreamsOpenShift` and `NameDeployManageStreamsOpenShift` attributes.
Tested in a local downstream build. Because the content is located in a section that is conditionalized for product-only use, this change has no affect on the community version of the documentation.
=> DBZ-8231 Fixes broken link from logging doc to Streams doc

debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java, debezium-microbenchmark-engine/src/main/java/io/debezium/performance/engine/DebeziumEnginePerf.java, documentation/modules/ROOT/pages/development/engine.adoc, documentation/modules/ROOT/pages/operations/debezium-server.adoc
Before change:
```
Benchmark                                     (processingOrder)  (recordCount)  Mode  Cnt  Score   Error  Units
DebeziumEnginePerf.processRecordsAsyncEngine            ORDERED         100000    ss       0.511           s/op
DebeziumEnginePerf.processRecordsAsyncEngine            ORDERED        1000000    ss       4.026           s/op
DebeziumEnginePerf.processRecordsAsyncEngine          UNORDERED         100000    ss       0.495           s/op
DebeziumEnginePerf.processRecordsAsyncEngine          UNORDERED        1000000    ss       4.423           s/op
```
After change:
```
Benchmark                                     (processingOrder)  (recordCount)  Mode  Cnt  Score   Error  Units
DebeziumEnginePerf.processRecordsAsyncEngine            ORDERED         100000    ss …
```
=> DBZ-8237 Don't use unbounded number of processing threads in async engine

.github/workflows/debezium-workflow-pr.yml
Without specifying the branch default branch is checked out and in case of backport PRs (PR to 2.7 branch), build of DBZ server dependecies (an others) fails as it use 3.0.0 branch and requires Java 21.
=> [ci] Use the PR base branch also for other dependecies repos

documentation/modules/ROOT/pages/connectors/jdbc.adoc
[DBZ-8232](https://issues.redhat.com/browse/DBZ-8232)
Adds information about setting passthrough properties to customize Hibernate behavior for the JDBC connector.
Also converts the titles for each of the properties subsections to headings to expose them in the table of contents.
Please backport to 2.7.
=> DBZ-8232 Describes passthru Hibernate props; converts titles to headings

.github/actions/build-debezium-db2/action.yml, .github/workflows/jdk-outreach-workflow.yml, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
https://issues.redhat.com/browse/DBZ-8250
@jpechane as requested, this should continue to satisfy the original logic but avoid the premature loop exits when data still needs to be consumed that hasn't yet been drained from the queue. I tested this with the Db2ConnectorIT method you referred me to and it now passes on the first execution :tada:
=> DBZ-8250 Move engine running check to avoid premature exit

debezium-api/src/main/java/io/debezium/engine/DebeziumEngine.java, debezium-embedded/src/test/java/io/debezium/embedded/async/AsyncEmbeddedEngineTest.java
Order of loading classes via SPI is not guaranteed. As DebeziumEngine.create() method is defined in debezium-api module which we don't want to depends on embedded module, possibly the only how to prevend loading async engine builder via SPI is to remove it from SPI.
https://issues.redhat.com/browse/DBZ-8241
=> DBZ-8241 Use pre-defined builder factory when none is specified 

documentation/modules/ROOT/pages/connectors/jdbc.adoc
closes: https://issues.redhat.com/browse/DBZ-8252
improves docs from this https://github.com/debezium/debezium/pull/5854
=> DBZ-8252 Add a note about flush-retry properties for JDBC connector

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-mariadb-mysql-adv-connector-cfg-props.adoc, documentation/modules/ROOT/partials/modules/all-connectors/shared-mariadb-mysql.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-db2-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-informix-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-mariadb-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-mysql-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-oracle-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-sqlserver-props-snippets.adoc
[DBZ-8254](https://issues.redhat.com/browse/DBZ-8254)
In DBZ-7786 we implemented content sharing between the MariaDB and MySQL connector documentation. One important goal of that original implementation was to preserve the few instances where content differed between the two connectors by assigning the conditional attributes, `MARIADB` and `MYSQL` to blocks that contained connector-specific content.
Unfortunately, while the conditionalization worked for the Antora-based content in the community documention, the distinctions were not preserved when content was processed for productization. 
This change refactors the previous conditionalization implementation by reusing the mechanism employed in DBZ-8090, creating shared snippet files to contain chunks of context-specific text within tagged …
=> Dbz 8254 fix conditionalization in shared mariadb mysql files

debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-infinispan.xml, debezium-bom/pom.xml, debezium-connector-jdbc/pom.xml, debezium-connector-oracle/pom.xml, debezium-microbenchmark-oracle/pom.xml, debezium-testing/debezium-testing-system/README.md, debezium-testing/debezium-testing-system/pom.xml, debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/builders/FabricKafkaConnectBuilder.java, documentation/antora.yml, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-oracle-kafka-connect-yaml.adoc, jenkins-jobs/pipelines/release/deploy_snapshots_pipeline.groovy, jenkins-jobs/pipelines/release/release-pipeline.groovy, jenkins-jobs/scripts/upstream-artifact-server-prepare.sh, pom.xml
https://issues.redhat.com/browse/DBZ-3658
@obabec your favorite task -- we'll need to align the testing farm to contain `ojdbc11` 21.11.0.0, when you have time :grinning:
=> DBZ-3658 Oracle JDBC driver JDK8 to JDK11 (ojdbc11) 21.15.0.0

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SnapshotIsolationIT.java
This change allows users to define the desired transaction isolation for the postgres snapshot.
This will allow for running the initial snapshot with a reader instance that doesn't support SERIALIZABLE.
=> DBZ-1252 Allow configuring the postgres snapshot isolation level

documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-mariadb-mysql-adv-connector-cfg-props.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-db2-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-informix-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-mariadb-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-mysql-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-oracle-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-sqlserver-props-snippets.adoc
[DBZ-8249](https://issues.redhat.com/browse/DBZ-8249)
- Adds a note to caution users against setting the `snapshot.fetch.size` property for the MySQL connector. 
- Also includes an unrelated fix to correct a rendering problem that caused attributes that are set in the `include` directive that provides the value of the `schema.history.internal.store.only.captured.databases.ddl` for multiple connectors to bleed through into the published content.
Tested in a local Antora build and a local downstream build.
2.7 PR: #5891
=> Dbz 8249 note that mysql snapshot fetch size property default provides best performance

documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-mariadb-mysql-adv-connector-cfg-props.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-db2-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-informix-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-mariadb-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-mysql-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-oracle-props-snippets.adoc, documentation/modules/ROOT/partials/modules/snippets/frag-sqlserver-props-snippets.adoc
[DBZ-8249](https://issues.redhat.com/browse/DBZ-8249)
Cherry-picked from `main` (#5887)
=> DBZ-8249 Adds caution about setting MySQL snapshot.fetch.size to 2.7 branch

documentation/modules/ROOT/pages/connectors/postgresql.adoc
[DBZ-8268](https://issues.redhat.com/browse/DBZ-8268)
Cherry-pick update from PR #5892 in `main` to 2.7` for description of `publication.autocreate.mode` `ALL_TABLES` option.
=> Dbz 8268 2.7 cherry pick from main fix `ALL_TABLES` option description

documentation/modules/ROOT/pages/connectors/postgresql.adoc
[DBZ-8268](https://issues.redhat.com/browse/DBZ-8268)
Edits the description of the `publication.autocreate.mode` property to remove inaccurate statement, add cross reference to setting account permissions to permit the connector to create publications, and fix formatting.
Tested in a local Antora and downstream builds. 
PR #5894 applies this change to 2.7.
=> DBZ-8268 Fix errors in description of `publication.autocreate.mode`

documentation/modules/ROOT/pages/architecture.adoc
[DBZ-8279](https://issues.redhat.com/browse/DBZ-8279)
To support the downstream DP release of Debezium Server, this change conditionalizes text in the architecture topic of the documentation to expose references to the component and to adjust content based on the release context. I also made a few other minor edits, such as removing the use of the possessive when referring to Debezium artifacts. 
Tested in local Antora and downstream releases.
The changes are evident only in the productized version of the documentation; no changes are visible in the community edition.
=> DBZ-8279 Edit & conditionalize architecture.adoc text for DBZ Server DP

.github/workflows/contributor-check.yml
If the PR included the contributor details, the contributor check would always fail due to the check only fetching the details from the `main` branch. This change will now take the contents from `main` and append any differences in this PR before performing the check, so it should pass.
=> [ci] Allow contributor check to pass when details are included in pull request

documentation/modules/ROOT/pages/architecture.adoc
[DBZ-8279](https://issues.redhat.com/browse/DBZ-8279)
Cherry-picks from main to 2.7 adjustments to the conditionalization in `architecture.adoc` designed to expose information about the Debezium Server DP in the product doc.
=> Dbz 8279 cherry pick from main to 2.7 updated conditionalization in architecture doc

COPYRIGHT.txt, debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkDeleteEnabledTest.java, jenkins-jobs/scripts/config/Aliases.txt
https://issues.redhat.com/browse/DBZ-8247
Problem happens when evaluation of truncate record doesn't stops on truncating and go on with trying to use this record for update event also.
=> DBZ-8247 Truncate record ruins work in JDBC

documentation/modules/ROOT/partials/modules/tutorial/proc-deleting-record-database-viewing-delete-event.adoc
[DBZ-8284](https://issues.redhat.com/browse/DBZ-8284)
Fixes redundant callouts in the product Getting Started guide that were found during pre-release review.
TBD: Local Antora and downstream build tests.
After verification, this change should be backported to 2.7.
=> DBZ-8284 Address callout formatting error detected during review

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/pages/post-processors/reselect-columns.adoc, documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-sql.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-sql.adoc, documentation/modules/ROOT/partials/modules/snippets/db2-frag-signaling-fq-table-formats.adoc, documentation/modules/ROOT/partials/modules/snippets/mariadb-frag-signaling-fq-table-formats.adoc, documentation/modules/ROOT/partials/modules/snippets/mysql-frag-signaling-fq-table-formats.adoc, documentation/modules/ROOT/partials/modules/snippets/oracle-frag-signaling-fq-table-formats.adoc, documentation/modules/ROOT/partials/modules/snippets/postgresql-frag-signaling-fq-table-formats.adoc, documentation/modules/ROOT/partials/modules/snippets/sqlserver-frag-signaling-fq-table-formats.adoc
[DBZ-8293](https://issues.redhat.com/browse/DBZ-8293)
Fixes formatting errors that caused in list continuation characters and other formatting artifacts to render in the built documentation.
Please backport to 2.7.
=> Dbz 8293 formatting chars render literally in docs

documentation/modules/ROOT/pages/connectors/oracle.adoc
Adds anchor IDs for headings in the Oracle custom converters section to enable linking from other contexts.
=> [docs] Add anchor IDs for Oracle custom converters

documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Aligns the documentation with the official MS docs for sys.sp_cdc_enable_table (https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sys-sp-cdc-enable-table-transact-sql)
=> DBZ-8314 Clarifies on enabling CDC on MS SQL Server table

debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogReadOnlyIncrementalSnapshotChangeEventSource.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSchema.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotChangeEventSource.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotContext.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/IncrementalSnapshotIT.java, debezium-core/src/main/java/io/debezium/pipeline/signal/actions/snapshotting/StopSnapshot.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/IncrementalSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/IncrementalSnapshotContext.java, debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
Issue: https://issues.redhat.com/browse/DBZ-8303
[Conversation](https://groups.google.com/g/debezium/c/4Ir18BzYTiE/m/PeEzHa_cAQAJ)
The `AbstractIncrementalSnapshotContext` is accessed by two threads—the main binlog thread and the `SignalProcessor` thread. A race condition occurs when the `SignalProcessor` thread calls `stopSnapshot()` while the main thread is executing `readChunk()`. This can lead to inconsistencies, causing exceptions during snapshot processing.
- Instead of immediately modifying the snapshot state in `stopSnapshot()`, a queue (`dataCollectionsToStop`, a `LinkedBlockingQueue<String>`) is used to manage the list of collections to stop. This queue can contain collection names or regex patterns. ".*" is used to stop all collections' snapshots.
- The method `stopSnapshot()` …
=> DBZ-8303 Fix race condition in stop snapshot

debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogStreamingChangeEventSource.java
When GTID is enabled, binlog client tracks GTID and eventually resumes from the last GTID position. However, to enable GTID on the client, client has to set initial GTID position (can be empty). When GTID is enbled in the connector, always enable GTID also on the binlog client to make sure that it tracks GTID and its keep alive thread eventually resumes from the right position.
https://issues.redhat.com/browse/DBZ-8194
=> DBZ-8194 Always set binlog client GTID when GTID is enabled

documentation/modules/ROOT/pages/operations/debezium-server.adoc
Currently Debezium server allows to use only sinks which implements `ChangeConsumer` interface, which excludes these options. Listing these properties may be confusing for users. Remove them until we actually allow to use them in the Debezium sever.
=> [docs] Remove unordered record processing from sever docs

documentation/modules/ROOT/pages/operations/debezium-server.adoc
Corrected `STM` to `SMT` (Single Message Transformation) in Debezium Server documentation. Updated to `SMTs` to show that multiple transformations can be applied.
=> [docs] Typo fix in Debezium Server documentation

.github/actions/build-debezium-storage/action.yml, debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogAntlrDdlParserTest.java, debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogDefaultValueTest.java, debezium-connector-mariadb/src/main/java/io/debezium/connector/mariadb/MariaDbDatabaseSchema.java, debezium-connector-mariadb/src/main/java/io/debezium/connector/mariadb/antlr/MariaDbAntlrDdlParser.java, debezium-connector-mariadb/src/test/java/io/debezium/connector/mariadb/DefaultValueTest.java, debezium-connector-mariadb/src/test/java/io/debezium/connector/mariadb/MariaDbAntlrDdlParserTest.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlDatabaseSchema.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/MySqlAntlrDdlParser.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDefaultValueTest.java, debezium-storage/debezium-storage-s3/src/main/java/io/debezium/storage/s3/history/S3SchemaHistory.java
Remove converters from mysql parsers.
A refactor to make https://github.com/debezium/debezium-connector-vitess/pull/210 possible.
I tried moving more language specific DDL parsers (eg mariadb, mysql, oracle) to the debezium-ddl-parser package but they are quite inter-tangled with other parts of the mariadb/mysql connectors (eg converters, charset registry). Additionally, the test modules (eg MySqlAntlrDdlParserTest) rely on BinlongAntlrDdlParserTest which relies on specific TableSchemaBuilders (eg MySqlTableSchemaBuilder) and others. It seems difficult to do a proper refactor without circular dependencies. I could move the AntlrDdlParsers and not their tests but it seems odd to have a class in one package and its unit tests located in another package. Based on this, I am just having the …
=> DBZ-8360 Remove converters from mysql parsers

pom.xml
The current version of the protobuf libraries (3.25.2) is affected by [SNYK-JAVA-COMGOOGLEPROTOBUF-8055227](https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEPROTOBUF-8055227).
The recommended fix is to upgrade to 3.25.5, which should be safe as it's just a patch fix.
=> DBZ-8371 bump protobuf dependencies to avoid vulnerability

documentation/modules/ROOT/partials/modules/tutorial/proc-deleting-record-database-viewing-delete-event.adoc, documentation/modules/ROOT/partials/modules/tutorial/proc-updating-database-viewing-update-event.adoc
Added a comma after `"name": "dbserver1.inventory.customers.Key"` in JSON.
=> [docs] JSON syntax fix in tutorial

debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
This seems to be more reliable then waiting more or less random time and assuming that all transaction were already processed by the database.
https://issues.redhat.com/browse/DBZ-8386
=> DBZ-8386 Consume all records before starting actual snapshot test

debezium-embedded/src/test/java/io/debezium/pipeline/AbstractBlockingSnapshotTest.java
As we may miss one record (the last one, see DBZ-8335) when Debezium hit some error while running blocking snapshot and records don't have to be ordered by the primary key, we may be missing any record, not only the record with highest PK.
Modify snapshot query to always return ordered records, so the eventually missed records is the last one.
https://issues.redhat.com/browse/DBZ-8398
=> DBZ-8398 Order snapshot records to miss always the last one

debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java, debezium-core/src/test/java/io/debezium/transforms/AbstractExtractStateTest.java, debezium-core/src/test/java/io/debezium/transforms/ExtractNewRecordStateTest.java
This is to avoid NPE for non-envelope rerords.
=> DBZ-8393 ExtractNewRecordState transform: move processing of headers after envelope has been checked

documentation/modules/ROOT/pages/install.adoc
There is a typo error in installation docs that corrupted download link for `informix` and `jdbc` connector on the documentation online!
=> DBZ-8429: fix install docs

debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java, debezium-embedded/src/test/java/io/debezium/embedded/async/AsyncEmbeddedEngineTest.java
Otherwise engine shutdown may get stuck as in such case the count down
of `shutDownLatch` would be skipped and engine would wait for `shutDownLatch` forever.
https://issues.redhat.com/browse/DBZ-8414
=> DBZ-8414 Catch exception from stopping the connector

debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtAndConvertConsumerProcessor.java, debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtConsumerProcessor.java, debezium-embedded/src/test/java/io/debezium/embedded/async/AsyncEmbeddedEngineTest.java
If user SMT for whatever reason return `null`, don't pass such records to consumer as it woudl result into NPE in async engine chain. This is in concordance with old `EmbeddedEngine` which skipped `null` records as well.
https://issues.redhat.com/browse/DBZ-8434
=> DBZ-8434 Don't pass null records to consumer

debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/offset/JdbcOffsetBackingStore.java
During the load function, a SELECT operation is performed on the debezium_offset_storage table. This operation locks the table, and the lock is not released after the offset storage initialization. We added a commit of the connection to the load function. This ensures, that the lock on the debezium_offset_storage table is released, when no longer needed.
=> DBZ-8423 Resolved the issue that the debezium_offset_storage table is locked after storage initialization

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-8450](https://issues.redhat.com/browse/DBZ-8450)
This change removes extraneous list continuation characters (i.e., plus signs [`+`]) from the descriptions of the Oracle connector properties `log.mining.query.filter.mode` and `log.mining.strategy`.
The documentation for the two Oracle connector properties uses definition list formatting to present information about the available configuration options. In an AsciiDoc definition list, a pair of colon characters represent the delimiter between the term being defined and its description. In the previous version of the documentation, the definition list formatting is incorrectly combined with the use of list continuation characters, i.e., `+` signs. As a result, instead of serving as markup characters, the colon characters render …
=> DBZ-8450 Extra list-continuation (`+`) chars corrupt formatting of description lists

documentation/modules/ROOT/pages/connectors/postgresql.adoc
Edits the description of the PostgreSQL `replica.identity.autoset.values` property to specify that it applies changes only to captured tables. 
Also applies additional unrelated language and formatting changes to improve clarity and consistency with other documentation.
Supersedes the closed PR #6005 on which it is based
=> [docs] Update description of pg replica identity prop

debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java, debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java
With this change, all `EmbeddedEngine` stuff which is used in the tests should be localted only in `EmbeddedEngineTest` and `TestingEmbeddedEngine` classes, i.e. used only for running tests for `EmbeddedEngine` itself.
https://issues.redhat.com/browse/DBZ-8441
=> DBZ-8441 Make AbstractConnectorTest#createEngine method abstract

debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
[DBZ-8472](https://issues.redhat.com/browse/DBZ-8472)
Use `StringBuilder` to build a consolidated connector configuration log message.
=> DBZ-8472 connector configuration logging improvement

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSignalBasedIncrementalSnapshotChangeEventSource.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/IncrementalSnapshotCollationSortOrderMismatchIT.java, debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java, debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
https://issues.redhat.com/browse/DBZ-4903
Hi there!  I wanted to take a stab at this, so I resurrected my extremely old ticket, hopefully that's okay?  I believe there are other tickets as well that deal with a similar idea.
What I'm trying to do is retrieve the schema when currentTable == null in the isTableInvalid.  My thinking was that it could be similar to the process to create the schema when transactions are done on a table whose schema hasn't been captured yet.
I tested in mysql and oracle and seems to do the job, but definitely need someone to look over it and let me know if I'm on completely the wrong track or not.  I could only find Oracle examples where the DDL is included in the schemaChangeEvent
=> DBZ-4903 Allow schema retrieval when schema is missing during incremental snapshot

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationConnection.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java, documentation/modules/ROOT/pages/connectors/postgresql.adoc
Creating Postgres replication slots enabled for failover when both of the following conditions are true:
- Postgres version is >= 17
- Debezium is connecting to a primary (only primaries support failover slots right now)
Updating the docs to reflect the support for failover slots, as well as to clarify that replication slots on stand-by servers are supported with Postgres 16 or newer.
Fixes https://issues.redhat.com/browse/DBZ-8412
=> DBZ-8412: Support for Postgres 17 failover slots;

debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/history/JdbcSchemaHistoryConfig.java
https://issues.redhat.com/browse/DBZ-8500
=> DBZ-8500 using correct name for table.exists property in JdbcSchemaHistoryConfig

debezium-bom/pom.xml, debezium-core/pom.xml, debezium-core/src/main/java/io/debezium/transforms/tracing/ActivateTracingSpan.java, debezium-core/src/main/java/io/debezium/transforms/tracing/TracingSpanUtil.java, debezium-core/src/test/java/io/debezium/transforms/ActivateTracingSpanTest.java
In the ActivateTracingSpan SMT, emitting traces when no propagated trace context is found is controlled by the `tracing.with.context.field.only` setting. However, the if/else condition was flawed, resulting in traces not being emitted event with this setting being set to `false`. This commit fixes the condition logic.
Debezium offers to create traces when processing records. The [documentation](https://debezium.io/documentation/reference/stable/integrations/tracing.html#_activatetracingspan_smt) states that when provided with a serialized upstream application tracing context (through a specific SQL table field), it will use this trace context as a parent trace context for its own spans. If it doesn't find any, it will create traces from scratch.
In reality, if no propagated trace context …
=> DBZ-8467 Emit traces even when no propagated trace context is found

debezium-core/src/main/java/io/debezium/transforms/TimezoneConverter.java, debezium-core/src/test/java/io/debezium/transforms/TimezoneConverterTest.java
Fix for what I would consider to be a bug in TimezoneConverter `include.list`.
If you specify entries e.g. 
```
transforms.convertTimezone.include.list=source:table_one:DATE_CREATED,table_one:LAST_UPDATED,table_two:CREATED_AT,table_two:UPDATED_AT
```
and an event from `table_three` is received, the TimezoneConverter will currently apply the conversion to all columns within. The fallback from not finding a table match in config is to convert all columns, instead of not converting any of them.
This leaves you with no way to opt in to select columns on select tables without adding workaround config e.g. `table_three:workaround_cfg`.
See https://issues.redhat.com/browse/DBZ-8514
=> DBZ-8514 TimezoneConverter include.list should be respected if set

debezium-core/src/main/java/io/debezium/transforms/TimezoneConverter.java, debezium-core/src/test/java/io/debezium/transforms/TimezoneConverterTest.java
Fix for what I would consider to be a bug in TimezoneConverter `include.list`.
If you specify entries e.g. 
```
transforms.convertTimezone.include.list=source:table_one:DATE_CREATED,table_one:LAST_UPDATED,table_two:CREATED_AT,table_two:UPDATED_AT
```
and an event from `table_three` is received, the TimezoneConverter will currently apply the conversion to all columns within. The fallback from not finding a table match in config is to convert all columns, instead of not converting any of them.
This leaves you with no way to opt in to select columns on select tables without adding workaround config e.g. `table_three:workaround_cfg`.
See https://issues.redhat.com/browse/DBZ-8514
=> DBZ-8514 TimezoneConverter include.list should be respected if set (2.7.x)

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/transforms/timescaledb/TimescaleDbDatabaseIT.java, debezium-quarkus-outbox-reactive/integration-tests/src/test/java/io/debezium/outbox/reactive/quarkus/it/OutboxIT.java, debezium-quarkus-outbox-reactive/integration-tests/src/test/java/io/debezium/outbox/reactive/quarkus/it/OutboxTestIT.java, debezium-quarkus-outbox-reactive/integration-tests/src/test/java/io/debezium/outbox/reactive/quarkus/it/OutboxWithoutOpenTelemetryIT.java, debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/OutboxIT.java, debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/OutboxTestIT.java, debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/OutboxWithoutOpenTelemetryIT.java, debezium-storage/debezium-storage-redis/src/test/java/io/debezium/storage/redis/offset/RedisOffsetBackingStoreIT.java, debezium-testing/debezium-testing-testcontainers/pom.xml, debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTestIT.java, debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ConnectorConfigurationIT.java, debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/DebeziumContainerIT.java, debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/MongoDbReplicaSetAuthContainerIT.java, debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/MongoDbReplicaSetContainerIT.java, debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/MongoDbShardedClusterContainerIT.java
Currently if someone wants to run tests without Docker by using the command:
```
$ mvn clean verify -DskipITs 
```
but the execution presents containers/integration tests not skipped, causing the build to fail in environments without Docker installed.
**Expected Behavior:**
Skip tests that use Docker with `-DskipITs` in maven
**Actual Behavior:** 
mvn executes tests that use Docker in some modules with  arg `-DskipITs`
This issue affects some modules:
- `debezium-testing-testcontainers`
- `debezium-quarkus-outbox-integration-tests`
- `debezium-quarkus-outbox-reactive`
- `debezium-storage-redis`
- `debezium-connector-postgres`
The Tests are named without using the convention `IT` which permits to be executed with the `maven-failsafe-plugin` that has the property `skipITs`. Furthermore …
=> Dbz 8509 Container Tests are executed with -DskipITs

debezium-core/src/main/java/io/debezium/util/Strings.java, debezium-core/src/test/java/io/debezium/util/StringsTest.java
Fixes https://issues.redhat.com/browse/DBZ-3720
Depends on https://github.com/debezium/debezium-server/pull/142
=> DBZ-3720 Error with debezium.sink.pulsar.client.serviceUrl and debezium-server

jenkins-jobs/pipelines/release/deploy_snapshots_pipeline.groovy
With the default 512MiB it randomly fails with
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.1:single (default) on project debezium-storage-rocketmq: Failed to create assembly: Error creating assembly archive store: Problem creating zip: Execution exception: Java heap space -> [Help 1]
=> [ci] Increase maven heap size to 4GiB

documentation/modules/ROOT/pages/operations/debezium-server.adoc
In [DBZ-8206](https://issues.redhat.com/browse/DBZ-8206) moved the configuration directory from [`conf` to `config`](https://github.com/debezium/debezium-server/pull/120), but the docs are still mentioning the old `conf` directory.
=> [docs] update to show correct configuration directory

debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogConnectorConfig.java, debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogNotificationsIT.java, debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogSnapshotSourceIT.java, debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/util/UniqueDatabase.java
closes https://issues.redhat.com/browse/DBZ-8291 and https://issues.redhat.com/browse/DBZ-6709
=> DBZ-8291 DBZ-6709 Handle store.only.captured.tables.ddl regression

documentation/modules/ROOT/pages/connectors/mongodb.adoc
The default value of `poll.interval.ms` is incorrectly documented as 1000ms in some parts of the documentation.
According to the source code and description, the correct default value is 500ms.
https://github.com/debezium/debezium/blob/6246808308200ae9877f25f3a04e378578def98c/debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java#L642-L650
https://github.com/debezium/debezium/blob/6246808308200ae9877f25f3a04e378578def98c/debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java#L572
=> Fix default value of `poll.interval.ms` in MongoDB connector docs

documentation/modules/ROOT/partials/modules/tutorial/proc-deleting-record-database-viewing-delete-event.adoc
Found a small typo in the docs.
=> Update Typo in Tutorial Documentation

debezium-bom/pom.xml
Upgrade to new vitess client version. Allows us to both backward & forward compatibly handle enum/set types correctly. See [DBZ-8561](https://issues.redhat.com/browse/DBZ-8561) for more details and https://github.com/debezium/debezium-connector-vitess/pull/222
=> Upgrade vitess client version

documentation/modules/ROOT/partials/modules/tutorial/proc-starting-kafka.adoc
Kafka otherwise bind to some randomly assigned IP address and further step in the tutorial, which starts Kafka Connect, fails with connection timeout exception.
=> [docs] Bind Kafka container to localhost in podman

debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/jdbc/BinlogValueConverters.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresTemporalPrecisionHandlingIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java, debezium-core/src/main/java/io/debezium/jdbc/TemporalPrecisionMode.java, debezium-core/src/main/java/io/debezium/time/IsoDate.java, debezium-core/src/main/java/io/debezium/time/IsoTime.java, debezium-core/src/main/java/io/debezium/time/IsoTimestamp.java, debezium-core/src/test/java/io/debezium/jdbc/JdbcValueConvertersTemporalPrecisionTest.java
Adding 3 new non **adaptive** temporal modes:
- `isostring`: converts to UTC ISO 8601
- `microseconds`: converts to int64, always with microseconds precision mode. not adaptive
- `nanoseconds`: converts to int64, always with nanoseconds precision mode. not adaptive
Implements [DBZ-6387](https://issues.redhat.com/browse/DBZ-6387)
remaining todos
Requires https://github.com/debezium/debezium-connector-vitess/pull/219
=> DBZ-6387 Addding new isostring, microseconds, nanoseconds TemporalPrecisionModes

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/Lsn.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeTablePointer.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/TxLogPosition.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TransactionMetadataIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java, debezium-core/src/main/java/io/debezium/pipeline/source/spi/ChangeTableResultSet.java, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Sqlserver connector requires unbounded memory to process big transactions. This happens due to the fact that `mssql-jdbc` driver buffers any not yet consumed result sets in memory in order to execute the next select statement. On the other hand the connector doesn't limit the number of rows it selects. This leads to almost all transaction rows being buffered in memory.
An obvious solution to that is to limit the number of rows selected. This patch does exactly that. It introduces a new connector setting called `streaming.fetch.size` (by analogy with `snapshot.fetch.size`) with the default value of `0` which means the old behavior is preserved.
=> DBZ-8557: Implement keyset pagination in sqlserver connector

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
During certain scenarios, especially during RDS reboots (planned or unplanned), Postgres becomes available in such a way that Debezium is not aware that Postgres went away.  In many cases, this can result in connectors thinking they are healthy (with all statuses returning RUNNING), but are not actually reading from the replication slots.
By notifying the errorHandler when these occur, we are able to have the in-built retry mechanism reconnect after these failures.
Due to the inconsistent nature of how this happens - not every reboot will cause a connector to get stuck - we are catching erros happening in both the PostgresStreamingChangeEventSource, and the core ChangeEventSourceCoordinator.  In my testing, I have seen only some types of events get caught by the error handler in the …
=> DBZ-2386 Notify errorHandler on Postgres errors

documentation/modules/ROOT/pages/operations/debezium-server.adoc
This update addresses [DBZ-8563 Issue](https://issues.redhat.com/browse/DBZ-8563). The corresponding change has already been merged into the Debezium Server repository:
- https://github.com/debezium/debezium-server/pull/149
=> DBZ-8563: Update documentation to specify the batcherBuilder for Pulsar producers

debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/e2e/AbstractJdbcSinkPipelineIT.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/junit/jupiter/e2e/source/SourcePipelineInvocationContextProvider.java
https://issues.redhat.com/browse/DBZ-6387
The JDBC sink tests were not designed to expect the temporal columns to be created as strings when `isostring` is set as the source's temporal precision mode. This PR disables that mode in the test suite for now, and a follow-up PR will update the tests to introduce this.
=> DBZ-6387 Disable testing with `isostring` temporal precision mode

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/informix.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-mariadb-mysql-rqd-connector-cfg-props.adoc
@roldanbob just FYI - I copied the same from SQL Server, but this seems to be missing in Oracle docs.
=> [docs] Add missing `include.schema.changes` configuration property

documentation/modules/ROOT/pages/connectors/jdbc.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/partials/modules/all-connectors/con-connector-streams-deployment.adoc, documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-db2-ora-pg-connector.adoc
[DBZ-8549](https://issues.redhat.com/browse/DBZ-8549) Adds downstream deployment instructions to the JDBC connector doc.
This PR supersedes #6107, which I closed. I've addressed any of the questions that were raised against that submission.
Tested in a local Antora and downstream builds. 
In the community version of the documentation, there are no visible changes, but I fixed link errors in the MongoDB and Oracle connector properties tables that resulted from mismatched anchors and links.  These mismatches prevented the downstream build from completing correctly.
This should be ready for reviewing and merging now.
=> Dbz 8549 provide streams deploy steps for jdbc connector

documentation/modules/ROOT/pages/connectors/vitess.adoc
This change follows up on [DBZ-8456](https://issues.redhat.com/browse/DBZ-8456) to update the description of the `skipped.operations` property for the Vitess connector to align with other connectors.
Similar to Db2, MongoDB, and SQL Server, the Vitess connector does not emit truncate events to data change topics. Thus, setting the value of the `skipped-operations` property for the connector to the default `t` (truncate) value, is equivalent to configuring the connector not to skip any events. i.e, setting the value to `none`.
=> [docs] Describes default Vitess `skipped.operations` behavior

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/all-connectors/shared-mariadb-mysql.adoc
[DBZ-8566](https://issues.redhat.com/browse/DBZ-8566)  Adds note to the top-level Deployment topic in the product edition of the connector docs to notify users about future removal of the Containerfile version of the deployment instructions.
=> DBZ-8566 Adds notes re: deprecation of Containerfile deployment steps

debezium-connector-jdbc/pom.xml, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkDeleteEnabledTest.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkInsertModeTest.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkPrimaryKeyModeTest.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkSaveConvertedCloudEventTest.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkSchemaEvolutionTest.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkTest.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/db2/JdbcSinkDeleteEnabledIT.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/mysql/JdbcSinkInsertModeIT.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/postgres/JdbcSinkFieldFilterIT.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/postgres/JdbcSinkInsertModeIT.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/junit/TestHelper.java
- Upgrade AssertJ-DB from 2.0.2 to 3.0.0
- Use new AssertDbConnection factory
=> [DBZ-8609] Upgrade AssertJ-DB to 3.0.0

debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcKafkaSinkRecord.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkPrimaryKeyModeTest.java
https://issues.redhat.com/browse/DBZ-8648
=> DBZ-8648 Avoid NPE with primary key mode `record_value` and delete events

documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/partials/modules/all-connectors/shared-mariadb-mysql.adoc
Updating procedure docs to follow deprecation notices of parameters mentioned :
Maria + Mysql:
https://github.com/debezium/debezium/blob/cc04be65aa54dc7b4aa85d34f715d02e62296d0a/documentation/modules/ROOT/partials/modules/all-connectors/shared-mariadb-mysql.adoc?plain=1#L611-L612
https://github.com/debezium/debezium/blob/cc04be65aa54dc7b4aa85d34f715d02e62296d0a/documentation/modules/ROOT/partials/modules/all-connectors/shared-mariadb-mysql.adoc?plain=1#L621-L622
Same for Oracle, just can't find the source file 😅
=> [docs] Update procedure documentation

documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-kafka.adoc
Fixes a formatting error in which a missing new-line before an `include` directive causes code from the directive to be appended to the introductory sentence of the example for using the Kafka signaling channel to send a stop incremental snapshot signal:
> `The following example shows a typical stop-snapshot Kafka message: :leveloffset: +1`
This error is present in the documentation for all connectors that provide instructions for using the Kafka signaling channel to stop incremental snapshots. 
=> [docs] Fix formatting in Kafka stop snapshot partial

jenkins-jobs/job-dsl/release/release_deploy_snapshots.groovy
Add sandbox check to the release snapshot Jenkins pipeline in order to make it work without any admin approval.
=> DBZ-8604 Add Sandbox release snapshot jenkins pipeline

documentation/modules/ROOT/pages/connectors/postgresql.adoc
In the PostgreSQL connector documentation, the Data type mappings section includes an unordered "mini-TOC" list of links to subsections that describe how the connector maps different PostgreSQL data types. This list is conditionalized to render only in the productized edition of the documentation.
The main focus of this change is to update that list to add links to a couple of subsections that were missing.
Because I had the file open, I took the opportunity to also make some other changes throughout the Data type mappings section, for example, moving sentences onto separate lines, and applying minor language edits. These latter changes are visible in both editions of the content.
=> [docs] Adds list entries and xrefs for pgvector and default data types

debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/artifacts/OcpArtifactServerController.java
Apicurio depends on older libraries than JDBC sink requires to work properly. Libs which Apicurio depends on are part of Kafka distribution but by including Apicurio and its libs, the older Apicurio libs have precedence and JDBC sink fails to start. By including these libraries into the connector we are trying to put the libs on the class path before Apicurio libs so that the right ones are loaded for JDBC sink.
https://issues.redhat.com/browse/DBZ-8651
=> DBZ-8651 Add libraries to override older Apicurio libs

debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/artifacts/OcpArtifactServerController.java, debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/fixtures/connectors/ConnectorFixture.java, debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/fixtures/connectors/JdbcSinkConnector.java
We don't run any JDBC sink test with Apicurio anyway at the moment, so there's no need to add these libs into JDBC sink pluing.
Related DBZ issues: DBZ-8675 and DBZ-8676.
https://issues.redhat.com/browse/DBZ-8651
=> DBZ-8651 Skip adding Apicurio bits into JDBC sink connector tests

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-8665
This change restores nearly the identical performance for constraint violations found in Debezium 2.7.4 before the processor and cache logic was refactored and unified.
=> DBZ-8665 Improve performance for handling constraint violations

documentation/modules/ROOT/pages/connectors/postgresql.adoc
[DBZ-8659](https://issues.redhat.com/browse/DBZ-8659)
Adds an entry for the `snapshot.isolation.mode` property to the table of Advanced connector properties. 
This property was previously added to the PostgreSQL connector in DBZ- 1252, but it was never documented.
=> DBZ-8659 Adds `snapshot.isolation.mode` description;edits snapshot steps

debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbOffsetContext.java, debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java, debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java
https://issues.redhat.com/browse/DBZ-8708
=> Mongo read events shoudl produce source info with ts_ms field set to current timestamp

debezium-core/src/main/java/io/debezium/transforms/ExtractChangedRecordState.java, debezium-core/src/test/java/io/debezium/transforms/ExtractChangedRecordStateTest.java
Ensure that when a field is update from its default value to null or vice versa the change is detected by the SMT and added to the appropriate header.
=> DBZ-8721 Detect Default Value Changes in ExtractChangedRecordState

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/util/OracleUtils.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-8710
The goal of this change is to be backward compatible by applying upper-case semantics to `database.dbname` and `database.pdb.name` when these two configuration properties are not specified in double-quotes. If these are defined in double quotes, the case will be treated as provided for case-sensitive use cases.
Example 1 - Values will be uppercased (case insensitive)
```
"database.dbname": "orclcdb",
"database.pdb.name": "pdb1"
```
Example 2 - Values left as-is (case sensitive)
```
"database.dbname": "\"orclcdb\"",
"database.pdb.name": "\"pdb1\"",
```
=> DBZ-8710 Allow specifying case-sensitive database and PDB names

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/BlockingSnapshotIT.java, debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java, debezium-core/src/main/java/io/debezium/pipeline/source/spi/ChangeEventSource.java
If there is no activity on the streaming connection while the blocking snapshot is being taken, there is a possibility that the streaming connection might be disconnected.
Periodically run a probing query on the streaming connection during the blocking snapshot.
This is done by adding an overload of waitSnapshotCompletion which allows the user to provide a heartbeat callback function, which is regularly called while waiting.  This will allow other databases to easily add the functionality as well.
=> DBZ-8680 Postgres: Probe streaming connection during blocking snapshots

documentation/modules/ROOT/pages/development/engine.adoc
=> [docs] Missing semicolon in MySQL connector example property setting

debezium-core/src/main/java/io/debezium/config/Configuration.java, debezium-core/src/test/java/io/debezium/config/ConfigurationTest.java
https://issues.redhat.com/browse/DBZ-8748
Specifically targeted at very observant people such as myself
=> DBZ-8748 trim configuration keys when converting from properties

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
Both `connectionCreated()` and `lockTablesForSchemaSnapshot()` are called only from `RelationalSnapshotChangeEventSource#doExecute()`. Before it we just determine snapshot tables, offset and do the locking of the captured tables. We don't need schema for these operations and it should be sufficient to refresh the schema only before taking the actual snapshot. At this point fo time tables are already lock, so we take schema refresh from consitent DB view.
https://issues.redhat.com/browse/DBZ-8595
=> DBZ-8595 Remove unnecesarry refreshes of schema

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-8749
Verified locally setting Oracle container TZ=CET and leaving the TZ unset (UTC), and in both scenarios, a quick test of the envelope `ts_ms` and the `source.ts_ms` were within milliseconds of one another, as expected.
=> DBZ-8749 Account for database system tz in snapshot source ts_ms

documentation/modules/ROOT/pages/operations/debezium-server.adoc
This PR adds documentation for the new `debezium.sink.pubsub.region` configuration parameter introduced in [debezium-server PR #160](https://github.com/debezium/debezium-server/pull/160). 
Related Issue: https://issues.redhat.com/browse/DBZ-8735
=> DBZ-8735: Added documentation for Google Cloud Pub/Sub locational endpoints configuration

documentation/modules/ROOT/pages/connectors/oracle.adoc
Change :The most important changes is correcting the default mode to the `online_catalog` strategy.
Before:
=> DBZ-3656 Clarify default mining strategies in Oracle documentation

debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogDefaultValueIT.java, debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogRegressionIT.java, debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogStreamingSourceIT.java, debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/util/UniqueDatabase.java, debezium-connector-mariadb/pom.xml, debezium-connector-mariadb/src/test/java/io/debezium/connector/mariadb/util/MariaDbUniqueDatabase.java, debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlUniqueDatabase.java
In the MariaDB driver version 3.5 some fixes has been applied to how the default zoned times are calculated. Those changes lead to change the behavior of the tests. This PR updates the affected test cases.
=> DBZ-8742 Update the way tests calculates the default zoned times for MariaDB

CONTRIBUTE.md, README.md, README_JA.md, README_KO.md, README_ZH.md, debezium-connector-jdbc/README.md, documentation/antora.yml, documentation/modules/ROOT/pages/install.adoc, pom.xml
As mentioned in the title, I have updated the documentation to state that JDK 21 is required
https://issues.redhat.com/browse/DBZ-8771
=> DBZ-8771 fix docs and comment of minimum Java version requirement from 11 to 21

documentation/modules/ROOT/pages/connectors/postgresql.adoc
[DBZ-8687](https://issues.redhat.com/browse/DBZ-8687)
Updates the PostgreSQL _Supported topologies_ topic to remove community-only conditional to expose information about using the PG connector in cluster environments that run PG 15 vs. 16 vs. 17. Adds a product-conditionalized note that specifies that using the connector with PG17 is a TP feature.   
Supersedes #6220
=> Dbz 8687 enhance pg docs w info about replication slot failover

documentation/modules/ROOT/pages/connectors/postgresql.adoc
Fixes subject-verb agreement in PG failover slots TP note
=> [docs] Grammar fix in conditional TP note

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerAdapter.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerAdapterTest.java
https://issues.redhat.com/browse/DBZ-8141
I need to add a test to this PR, and given the depth of the code and the fact an integration test could easily generate a false positive if the LogMiner data isn't generated exactly 100% correctly, so I will likely just create a mock for the `LogMinerAdapter` and expose some private methods for testing to just have a unit test for it to be safe.  Will do that tomorrow if the existing Oracle tests pass.
=> DBZ-8141 Capture in-flight transaction within snapshot boundary

debezium-core/src/main/java/io/debezium/config/Field.java, debezium-core/src/test/java/io/debezium/config/FieldTest.java
the method `withDefault()` for `Field` class used for configuration purpose create a new `Field` value without `deprecatedAliases`
**Expected Behavior:**  
the values for deprecated aliases should be mantained even if we have a default one
closes: https://issues.redhat.com/browse/DBZ-8832
=> Dbz 8832 Unexpected null value for Field Configuration deprecated aliases

debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/JdbcCommonConfig.java, debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/history/JdbcSchemaHistoryConfig.java, debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/offset/JdbcOffsetBackingStoreConfig.java, debezium-storage/debezium-storage-jdbc/src/test/java/io/debezium/storage/jdbc/JdbcOffsetBackingStoreIT.java
JDBC storage configuration names are not aligned with the others storage module. This misalignment can create some issue on configurations. The Proposal convention is the following:
| current    | new |
| -------- | ------- |
| offset.storage.jdbc.*  | offset.storage.jdbc.connection.*    |
| offset.storage.jdbc.offset.table.* | offset.storage.jdbc.table.*     |
| schema.history.internal.jdbc.* | schema.history.internal.jdbc.connection.*|
| schema.history.internal.jdbc.schema.history.table.* | schema.history.internal.jdbc.table.*|
The `JdbcSchemaHistoryConfig`, `JdbcOffsetBackingStoreConfig` fields are aligned with the new convention and the current names are deprecated for future removal.
closes https://issues.redhat.com/browse/DBZ-8573
=> Dbz 8753 Align JDBC storage configuration naming

debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
This PR improves the log message introduced with the change done in #6222 
Current log line:
`Incremental snapshot for table 's1.part2' will end at position`
Update to log line
`Incremental snapshot for table 's1.part2' will end at maximum key`
=> DBZ-8525: Improves log message introduced in #6222

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-8818](https://issues.redhat.com/browse/DBZ-8818)
Removes conditionalized incubating and TP admonitions.
Adds note describing factors that can contribute to idle thread exceptions and how to recover from the error by reverting the value of `snapshot.max.threads` and then retrying the snapshot.
This change should be backported to 3.0.
=> DBZ-8818 Removes obsolete admonition; adds note about idle thread exception

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-8838](https://issues.redhat.com/browse/DBZ-8838)
Conditionalizes note to show different content for community and product editions. 
This change should be backported to 3.0.
=> DBZ-8838 Rewrite note re: unescaped single quotes in extended fields

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-8823](https://issues.redhat.com/browse/DBZ-8823)
The current downstream release exposes the use of *LOB character types and the hybrid mining strategy as GA features. This change removes admonitions that designated content for those features as Technology Preview or incubating, and also removes obsolete conditionals that prevented that content from rendering in the product edition of the documentation.
This change should be backported to 3.0.
=> DBZ-8823 Removes TP and incubating statements for LOB and hybrid mining

documentation/modules/ROOT/pages/connectors/postgresql.adoc
A link from the Supported topologies topic to a procedure in the Troubleshooting section specified a non-existent target. 
The error resulted in a failure in the downstream build.
Re-homed the target to the correct anchor ID and tested in a local Antora build.
=> [docs] Fix broken link to Troubleshooting procedure

documentation/modules/ROOT/pages/connectors/jdbc.adoc
In the JDBC sink connector doc, a list at the head of the Connector properties topic provides easy access to the tables for each of the different types of properties. The first item in the list, is intended to link to the Kafka consumer properties, but the link URL targeted the non-existent ID `properties-generic` rather than the correct `properties-kafka-consumer`.
The error resulted in a failure in the downstream build.
Re-homed the target to the correct anchor ID and tested in a local Antora build.
=> [docs] Re-target link to correct topic ID

debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
https://issues.redhat.com/browse/DBZ-8856
=> DBZ-8856 Correctly treat AsyncEmbeddedEngine commit timeout as milliseconds

debezium-core/src/main/java/io/debezium/transforms/ExtractChangedRecordState.java, debezium-core/src/test/java/io/debezium/transforms/ExtractChangedRecordStateTest.java, documentation/modules/ROOT/pages/transformations/event-changes.adoc
https://issues.redhat.com/browse/DBZ-8855
@jpechane I'm on the fence on this change because, on one hand I like the idea that it simplifies and provides consistent logic when paired with other transforms; however at the same time, I can see the argument that when paired with other transforms, perhaps having a predicate chain to run one or the other transform makes sense.
Let me know what you think.
=> DBZ-8855 Add configured headers for read, insert, and delete events.

documentation/modules/ROOT/pages/integrations/tracing.adoc
Users needs to know its fully qualified class name to configure SMT.
=> [docs] Use fully qualified class name of ActivateTracingSpan

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Adding `__$command_id ASC` to the `ORDER BY` clause of the query allows for the usage of the clustered index when the connector is running with `data.query.mode=direct`.
=> DBZ-8858: Use the clustered index in sqlserver connector queries

debezium-core/src/main/java/io/debezium/pipeline/JmxUtils.java
https://issues.redhat.com/browse/DBZ-8862 
When the error 'Unable to register metrics as an old set with the same name ......' occurs, it can quickly locate the cause of the error.
=> Log JMX MBean name when registration fails

documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Should be backported to 3.0 and 3.1
=> [docs] Fix oboslete JDBC passthrough prefix

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-8841](https://issues.redhat.com/browse/DBZ-8841)
Updates Oracle connector doc to expose XStream DP content downstream.
Cherry picks changes from `main`.
Tested in a local Antora and downstream builds.
=> Apply DBZ- 8841 changes to 3.0

documentation/modules/ROOT/pages/connectors/postgresql.adoc
[DBZ-8687](https://issues.redhat.com/browse/DBZ-8687)
Followup to #6225 to add TP note to the description of the `slot.failover` property.
Please backport this change to 3.0.
=> DBZ-8687 Edits `slot.failover` description, adds TP note.

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/mariadb.adoc, documentation/modules/ROOT/pages/connectors/mysql.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc, documentation/modules/ROOT/pages/connectors/postgresql.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc, documentation/modules/ROOT/partials/modules/all-connectors/frag-common-mbean-name.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-schema-history-metrics.adoc
[DBZ-8840](https://issues.redhat.com/browse/DBZ-8840)
Refactors the _Schema history metrics_ topic in the Db2, MariaDB, MySQL, Oracle, and SQL Server connector files  to correct the schema history MBean name for SQL Server to include the `task.id`. In the original version of the topics, a common MBean name was shared to all of the relevant connectors via an entry in a shared file  `ref-connector-monitoring-schema-history-metrics.adoc`.
To assign a unique MBean name for SQL Server, it was necessary to remove the single MBean name from the beginning of the shared file, and create two separate name entries in the fragment file {{/partials/frag-common-mbean-name.adoc}} that is already used to provide instances of other MBean names. The single MBean name is now replaced by one of the …
=> Dbz 8840 doc update to sqlserver schema history mbean name

.github/actions/build-debezium-oracle/action.yml, .github/workflows/connector-oracle-workflow.yml, .packit.yaml, debezium-connector-oracle/pom.xml
https://issues.redhat.com/browse/DBZ-8882
Prefix the Infinispan-specific profiles to match the other buffer profiles. I've also added a new job on the testing farm to test the Oracle connector with embedded ISPN using Oracle 19.
=> DBZ-8882 Prefix Oracle infinispan profiles with `oracle-`

debezium-connector-mariadb/src/main/java/io/debezium/connector/mariadb/MariaDbConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
**Improve MySQL/MariaDB connector resilience during post-schema recovery reconnect**
While investigating an issue where the MySQL connector fails with:
_The client was disconnected by the server because of inactivity_
I found that even though the connector logs Reconnecting after finishing schema recovery, the actual connection object is reused and not revalidated. If the MySQL server silently drops the connection during a long schema recovery (due to wait_timeout), this leads to a failure when setAutoCommit(false) is called.
I contributed a patch that:
1. Validates the JDBC connection after schema recovery,
2. And reconnects if the existing connection is no longer valid
=> DBZ-8877 MySQL/MariaDB connector enhancement

documentation/modules/ROOT/pages/configuration/signalling.adoc
[docs] In the downstream Signaling documentation, the description for the single callout in the Debezium core module dependencies example is preceded by 12 rows of callout numbers. 
To eliminate this rendering error, this change reformats the single-entry list of callout descriptions, converting it to a paragraph.
The content is modified slightly to accommodate the new format.
=> [docs] Convert callout description to table to fix redundant numbering

documentation/modules/ROOT/pages/configuration/signalling.adoc
(cherry picked from commit bc7da1b23519c2db36e3068b85b95b0a4a83f036)
=> [docs] Convert callout description to paragraph to fix redundant numbering

documentation/modules/ROOT/pages/connectors/db2.adoc, documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-8551](https://issues.redhat.com/browse/DBZ-8551)
Enhance descriptions of `poll.interval.ms` and `heartbeat.interval.ms` in the Db2 and SQL Server connector documentation to highlight how the the polling interval influences how frequently the connector emits heartbeat messages.
Tested in an local Antora build.
Please backport to 3.0 and 3.1.
=> DBZ-8551 Highlight interaction btw/ poll & heartbeat interval properties

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4, debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql
https://issues.redhat.com/browse/DBZ-8895
This is an undocumented Oracle clause, so I don't intend to push this upstream.
=> DBZ-8895 Add Oracle virtual column `BY USER FOR STATISTICS` clause

documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-db2-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-oracle-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/shared-deploy-kafka-connect-yaml.adoc
Fixes a small error (dash [`-`]  vs.  dot [`.`]) that was present in the Apicurio URLs in the Kafka Connect CR YAML examples within the Streams deployment instructions.
Also replaces the `build-number` placeholder in the URL with an attribute.
Tested in a local downstream build.
This change relates only to content that is exposed in the downstream product edition of the docs and has no effect on the community version.
=> [docs] Fix KC YAML apicurio URL;sub attr for `build-number` placeholder

documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-db2-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-oracle-kafka-connect-yaml.adoc, documentation/modules/ROOT/partials/modules/all-connectors/shared-deploy-kafka-connect-yaml.adoc
Replaces obsolete attributes that referenced external docs in the Streams-based deployment instructions for the connectors. Because the attributes could not be resolved, the attribute text either rendered literally in the docs, or resulted in broken links.
=> [docs] Corrects refs to external Streams docs (downstream only)

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metrics/SqlServerStreamingPartitionMetrics.java, debezium-core/src/main/java/io/debezium/pipeline/meters/StreamingMeter.java, debezium-core/src/main/java/io/debezium/pipeline/metrics/DefaultStreamingChangeEventSourceMetrics.java, debezium-core/src/main/java/io/debezium/pipeline/metrics/traits/StreamingMetricsMXBean.java
https://issues.redhat.com/browse/DBZ-8885
During idle periods at the source, when no records are received by the connector, the `lagBehindSource` metric retains its old value, incorrectly indicating that the connector is lagging behind. A mechanism is needed to reset the `lagBehindSource` metric in such cases.  
Currently, there is no way to reset this metric individually; only a group reset is available, which resets all metrics in `StreamingMeter` together. Additionally, `StreamingMeter` is a private variable in `DefaultStreamingChangeEventSourceMetrics`, making it inaccessible when extending this class. 
This PR provides a getter method for StreamingMeter object and provides a method to reset the `lagBehindSource` separately.
=> DBZ-8885: Add an option to reset the lagBehindSource metric separately

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java, debezium-core/src/main/java/io/debezium/pipeline/signal/channels/KafkaSignalChannel.java, debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java, debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java, debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java, pom.xml
Addressing https://issues.redhat.com/browse/DBZ-8875
=> DBZ-8875: Replace deprecated poll and commitRecord methods to support Kafka 4.0

debezium-microbenchmark-engine/src/main/java/io/debezium/performance/engine/DebeziumConvertingEnginePerf.java, debezium-microbenchmark-engine/src/main/java/io/debezium/performance/engine/DebeziumEnginePerf.java, debezium-microbenchmark-engine/src/main/java/io/debezium/performance/engine/PostgresEndToEndPerf.java, debezium-microbenchmark-oracle/src/main/java/io/debezium/performance/connector/oracle/EndToEndPerf.java, debezium-microbenchmark-oracle/src/main/java/io/debezium/performance/connector/oracle/parser/LogMinerDmlParserPerf.java
https://issues.redhat.com/browse/DBZ-8444
Just for curiosity, Oracle microbenchmark numbers
* embedded engine:
```
Benchmark                                           (columnCount)  (dmlEvents)  (miningStrategy)   Mode  Cnt        Score        Error  Units
i.d.p.c.o.parser.LogMinerDmlParserPerf.testDeletes              1          N/A               N/A  thrpt    3  1879060.534 ±  68113.973  ops/s
i.d.p.c.o.parser.LogMinerDmlParserPerf.testDeletes              2          N/A               N/A  thrpt    3   996384.807 ±  98246.248  ops/s
i.d.p.c.o.parser.LogMinerDmlParserPerf.testDeletes              5          N/A               N/A  thrpt    3   399696.024 ± 195095.453  ops/s
i.d.p.c.o.parser.LogMinerDmlParserPerf.testDeletes             10          N/A               N/A  thrpt    3 …
```
=> DBZ-8444 Migrate performance microbenchmarks to async engine

documentation/modules/ROOT/pages/connectors/cassandra.adoc
This commit updates the Cassandra connector documentation for connection configurations.
https://github.com/debezium/debezium-connector-cassandra/commit/3fe4963a61bf0919384f75267eb030f92ff15622#diff-cb8507d61cddae8b7d293cd7100ffe8afe87ef201c54a231d1a24243187f468a removed many of the Cassandra connection configuration parameters and replaced them with a single parameter, `cassandra.driver.config.file`, which is a path to a configuration file for the Cassandra driver. The removed connection parameters have to be configured with the Cassandra driver now, not with the connector itself. This commit updates the documentation to reflect this change. The language of the documentation is mostly taken from this blog post,
https://debezium.io/blog/2022/03/25/debezium-1-9-cr1-released/, which details …
=> Update Cassandra connector docs for conn config

documentation/modules/ROOT/pages/configuration/avro.adoc
The documentation on Avro schema registry has two sections - Apicurio registry and Confluent registry.   However it doesn't have anything for Apicurio in "compatibility mode".  however the Apicurio mode is not very popular but It's possible to run Apicurio serialization in compatibilty mode with just a few settings
We propose to add a section in the avro serialization documentation that explain how to use the __confluent compatibility mode__. 
closes: https://issues.redhat.com/browse/DBZ-8945
=> DBZ-8945 Apicurio registry configuration should include instructions for confluent compatibility mode

debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/AbstractBinlogConnectorIT.java, debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogConnectorTest.java, debezium-connector-mariadb/src/test/java/io/debezium/connector/mariadb/SnapshotSourceIT.java, pom.xml
MariaDB allows `DATETIME` values with incomplete date parts (e.g., `2015-00-12` is considered valid by MariaDB).
In Debezium MariaDB connector versions up to 3.0.7.Final, such values were silently converted to `null`.
Starting with 3.0.8.Final and 3.1.x, processing these incomplete DATETIME values causes the connector to fail with a `java.time.DateTimeException`.
The current behavior causes the connector to fail when encountering invalid or incomplete DATETIME values. The root cause is a regression introduced by `maria-db-client` with version >`3.2.0`. We update the  client to `3.5.3`.
[Supported values for datetime in MariaDB](https://mariadb.com/kb/en/datetime/#supported-values)
[Dates conatining zero day or month result into DateTimeException](https://jira.mariadb.org/browse/CONJ-1226) …
=> Dbz 8940 Processing error because of incomplete date part of DATETIME datatype in MariaDB

debezium-connector-binlog/src/test/java/io/debezium/relational/history/AbstractKafkaSchemaHistoryTest.java, debezium-core/src/main/java/io/debezium/relational/history/AbstractSchemaHistory.java
https://issues.redhat.com/browse/DBZ-8999
When Debezium connectors start up, they replay previously ingested DDL statements from Kafka schema history topics. During this process, the connector logs filtered DDL statements at INFO level, potentially exposing sensitive data like hashed passwords to log aggregation systems.
Updated the DDL filter logging in AbstractSchemaHistory to use debug/trace level instead of info level by replacing the direct logger call with Loggings.logDebugAndTraceRecord(). This prevents sensitive DDL content from appearing in standard logs and log aggregation platforms like Observe.
Testing performed on shopify [fork](https://github.com/Shopify/debezium)
=> Prevent logging sensitive data in AbstractSchemaHistory

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
https://issues.redhat.com/browse/DBZ-9003
@jpechane this is in reference to the Zulip conversation [#community-postgresql > Snapshot connectors cause idle in transaction @ 💬](https://debezium.zulipchat.com/#narrow/channel/348249-community-postgresql/topic/Snapshot.20connectors.20cause.20idle.20in.20transaction/near/515885512). I need to test this change against my recent expectations with the Oracle LogMiner unification, but I have little cause for concern.
=> DBZ-9003 Prevent `idle in transaction` connection state with initial only snapshots

debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogIncrementalSnapshotIT.java, debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogReadOnlyIncrementalSnapshotIT.java, debezium-core/src/main/java/io/debezium/pipeline/notification/IncrementalSnapshotNotificationService.java, debezium-core/src/test/java/io/debezium/pipeline/notification/IncrementalSnapshotNotificationServiceTest.java
https://issues.redhat.com/browse/DBZ-8207
=> DBZ-8207 Use whole composite key in incremental snapshot notifications

debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/Buffer.java, debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java, debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/RecordBuffer.java, debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/ReducedRecordBuffer.java, debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/ReducedRecordBufferTest.java
With a reduction buffer, we can leave only the last event within all buffers (delete and upsert buffers) since we can reduce events not only within a single buffer but across both of them.
=> DBZ-8982 Leave last event w/i single PK in JDBC

debezium-connector-mariadb/src/main/java/io/debezium/connector/mariadb/antlr/MariaDbAntlrDdlParser.java, debezium-connector-mariadb/src/main/java/io/debezium/connector/mariadb/jdbc/MariaDbValueConverters.java, debezium-connector-mariadb/src/test/java/io/debezium/connector/mariadb/UuidColumnIT.java, debezium-connector-mariadb/src/test/resources/ddl/uuid_column_test.sql
https://issues.redhat.com/browse/DBZ-9027
This makes UUIDs columns in mariadb work.
I just noticed before submitting this PR that by pure coincidence work was being done on this already today in #6419 .
My changes here are bit more complete: they also handle the value conversion.
I put the tests in the mariadb module, instead of in the common binlog module with annotations on it to ignore them for mysql. I'm not sure what the preferred way is.
Note that this PR is putting the first file in `debezium-connector-mariadb/src/test/resources/ddl/`.
In the test I added a consumeSkippingSchemaChanges helper method because the number of records to skip is different between testing streaming vs snapshots; and I didn't want to hardcode imo fragile numbers of how many records to skip when.
=> DBZ-9027 Support UUID columns in debezium-connector-mariadb

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/AbstractLogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/BufferedLogMinerQueryBuilder.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/BufferedLogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/unbuffered/UnbufferedLogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/ClientIdFilterIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/UsernameFilterIT.java
https://issues.redhat.com/browse/DBZ-8884
Hi @jchipmunk, this reverts the change [DBZ-7473](https://issues.redhat.com/browse/DBZ-7473) you introduced.  I know that the delayed transaction construction was important for your environment, but doing so creates an issue with both capturing the username in events and filtering by usernames.
Oracle only records the username attribute in the `START` event and its only reflected in DML events for that transaction thereafter if the DML event is captured in the same query as the `START`. If there are two mining iterations where on the first there is only the `START` and some non-captured tables and in the second is where we see the first DML for a captured table, the username attribute reference is lost and LogMiner always populates the field as …
=> DBZ-8884 Populate source.user_name based on start events

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
https://issues.redhat.com/browse/DBZ-8744
In Oracle, when you refresh an instance from another, you do so by copying the other instance's database data files into the new instance along with all the recent archive logs, adding them to the catalog during the recovery process. This makes sure that when you refresh from the backup of the other instance, you have all changes. 
Once you've finished the refresh/recovery, the DBA most often elects to create a new log incarnation. You can think of this as closing off the log stream you restored from and starting a brand new log stream for the newly refreshed instance. When you do this, log sequences are reset.
If the DBA accidentally leaves the old archive logs from the prior incarnation in the catalog, this confuses Debezium and it will …
=> DBZ-8744 Limit archive logs to current log incarnation only

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/AbstractLogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/BufferedLogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/unbuffered/UnbufferedLogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-9062
This addresses several metrics issues:
- Fixes regression on lag calculation that was mistakenly changed
- Aligned commit metrics
- Introduced setting active transaction count to 1 on `START` and 0 on `COMMIT` for unbuffered impl.
=> DBZ-9062 Fix Oracle metrics regression and align behavior

.github/actions/build-quarkus-extensions/action.yml
To enforce the CI to build all dependent modules correctly, it is necessary to explicitly list all the required modules in the `-pl` (project list) parameter. Maven’s `-am` (also make) option only includes the direct and transitive dependencies of the modules specified in `-pl`, but it does not automatically include unrelated sibling modules or the entire module tree. Therefore, to ensure the complete set of interdependent modules is built—especially in a multi-module project—you must provide a comprehensive list of all relevant modules in the `-pl` argument. This approach guarantees that Maven can resolve all dependencies within the reactor and build them in the correct order during the CI process.
#closes https://issues.redhat.com/browse/DBZ-9077
=> DBZ-9077 enforce CI to build all dependent modules

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresReselectColumnsProcessorIT.java
https://issues.redhat.com/browse/DBZ-9086
`::serial` cast caused errors when primary key was serial type
=> DBZ-9086 Fix Postgres reselectColumns for serial primary key

debezium-bom/pom.xml, debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/RedisCommonConfig.java, debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/RedisConnection.java, debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/history/RedisSchemaHistory.java, debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/offset/RedisOffsetBackingStore.java, documentation/modules/ROOT/pages/configuration/storage.adoc, documentation/modules/ROOT/pages/operations/debezium-server.adoc
This change introduces additional configuration options for specifying custom keystore/truststore for the jedis client in redis sink. This allows the client to use different keys and certificates than the default ones passed to the JVM.
This change updates the Jedis client to version 6.0.0. and takes advantage of the newly introduced SSL options to set the keystore/truststore. The options are applied only if redis.ssl.enabled is true.
Configuration properties for each new SSL options:
`redis.ssl.truststore.path`: Specifies the path to the truststore file used for SSL.
`redis.ssl.truststore.password`: Specifies the password for the truststore file.
`redis.ssl.truststore.type`: Specifies the type of the truststore (e.g., JKS, PKCS12) (default: JKS).
`redis.ssl.keystore.path`: Specifies the …
=> DBZ-9082 Add option to specify custom keystore and truststore for Redis sink

debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4, debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
The following query is valid in Mysql but invalid for mariaDB:
```sql
CREATE TABLE IF NOT EXISTS table_with_encrypted_column_name(uuid VARCHAR(40) NOT NULL PRIMARY KEY, encrypted VARCHAR(40) DEFAULT NULL)
```
Removed the keyword `encrypted` in mysql grammar
=> DBZ-9092 Column name encrypted is not supported by MySqlParser

debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java, debezium-core/src/test/java/io/debezium/jdbc/JdbcConnectionTest.java
jira: https://issues.redhat.com/browse/DBZ-8660
Fixed a bug where we connections to databases with `$` in name was failing on verify step (found for sqlserver).
Added a unit test which checks if patternBasedFactory creates correct jdbc url for config with special characters
=> DBZ-8660 Add Quote replacement when formatting jdbc url to allow special characters

debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogConnectorIT.java, debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogDatabaseSchemaTest.java, debezium-connector-binlog/src/test/java/io/debezium/relational/history/AbstractKafkaSchemaHistoryTest.java, debezium-connector-binlog/src/test/java/io/debezium/relational/history/AbstractSchemaHistoryTest.java, debezium-connector-mariadb/src/main/java/io/debezium/connector/mariadb/MariaDbConnectorTask.java, debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java, debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java, debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java, debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java, debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java, debezium-core/src/main/java/io/debezium/relational/history/AbstractSchemaHistory.java, debezium-core/src/main/java/io/debezium/relational/history/SchemaHistory.java, debezium-core/src/main/java/io/debezium/schema/HistorizedDatabaseSchema.java, debezium-core/src/test/java/io/debezium/connector/common/BaseSourceTaskSnapshotModesValidationTest.java, debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java, debezium-embedded/src/test/java/io/debezium/relational/history/AbstractSchemaHistoryTest.java, debezium-storage/debezium-storage-file/src/main/java/io/debezium/storage/file/history/DelayingFileBasedSchemaHistory.java, debezium-storage/debezium-storage-file/src/main/java/io/debezium/storage/file/history/FileSchemaHistory.java, debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java, debezium-storage/debezium-storage-tests/src/test/java/io/debezium/storage/AbstractSchemaHistoryTest.java
https://issues.redhat.com/browse/DBZ-8562
In most production scenarios, there is an operator which tracks the state of the task and re-starts it when it is failed. Also it might do it at certain frequency (let's say a minute). Schema history recovery takes place inside the task's `start` method. Once this `start` metod is complete, the task is transitioned to RUNNING state. Hence, if the schema history recovery is not complete (let's say it takes 10 minutes), then after a minute operator would re-start the task and hence, it would create another task thread. The previous task thread would still be running for 9 more minutes.
This can lead to thread leak, high CPU usage and other issues in production environments. The reason why this happens is connect runtime's assumption/contract for …
=> DBZ-8562 - Move schema history recovery out of task start

debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/ConfigProperties.java, debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/OcpKafkaDeployer.java, debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/builders/FabricKafkaBuilder.java
With this PR we can run Kafka in KRaft mode without adding/changing any of the actual parameters. 
I have also added the param test.force.kraft in case we want to force the use of KRaft. 
And then, if the kafka version is equals or greater than 4.0.0, KRaft is used. And if the build is not productized and strimzi version is equals or greater than 0.46.0, we are also using KRaft (in this version Zookeeper is deprecated and no longer available).
=> DBZ-9097 Support KRaft for Kafka Cluster

documentation/modules/ROOT/pages/development/converters.adoc
This commit fixes the closing bracket typo in the example code of the Custom Converter 'IsbnConverter' due to an extra closing bracket on line 15, which was causing the code to throw an error.
=> DBZ-9153 Typo in the example code of the Custom Converter

debezium-core/src/main/java/io/debezium/openlineage/emitter/OpenLineageEmitter.java
According to OpenLineage docs:
https://openlineage.io/docs/spec/facets/run-facets/nominal_time
> The nominal usually means the time the job run was expected to run (like a scheduled time)
But facet contains current time, which is already passed to eventTime field.
=> DBZ-9146 Remove nominalTime facet from OpenLineage events

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SpecialCharsInNamesIT.java, debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
This is a continuation of the effort started in https://github.com/debezium/debezium/pull/6464.
Here's the change summary:
The parameter and variable names in some `JdbcConnection` methods are inconsistent:
1. There is `tableName` but `databaseCatalog`. The latter has been renamed to `catalogName` for consistency.
2. The collision between the `tableName` parameter and the table name introspected via the JDBC is addressed by naming the variable representing the introspected value as `metaTableName`, but `catalogName` is not prefixed with "metadata" because it doesn't conflict with `databaseCatalog`.
Before making the actual code changes, I'd like to unify the naming. This way, the changes themselves are easier to review and validate.
Even though all modified methods accept the …
=> DBZ-9117: Create schemaNamePattern from schemaName for schema introspection

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
A background keepalive thread is used to periodically send status updates on the replication stream. If this status update fails, we should immediately log the failure.
The old code catches and rethrows the exception.  This is a problem because:
1.  The exception is not logged at all.  The ExecutorService would rethrow the exception when the "get" function is called on the Future.  However, we never check for results of this future at all by calling "get", so... nothing gets logged.
2.  Even if we did call "get" on the Future in the stopKeepAlive function, the exception would not be immediately logged.  Having the log message be outputted at the correct time the exception actually happened is better for end-user debugging.
=> DBZ-9161 Postgres: log errors from keepalive thread for replication

debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogReselectColumnsProcessorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleReselectColumnsProcessorIT.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresReselectColumnsProcessorIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerReselectColumnsProcessorIT.java, debezium-core/src/main/java/io/debezium/processors/PostProcessorRegistryServiceProvider.java, debezium-embedded/src/test/java/io/debezium/processors/AbstractReselectProcessorTest.java
Actually the configuration for post processing is the following:
```txt
"post.processors": "reselector", 
"reselector.type": "io.debezium.processors.reselect.ReselectColumnsPostProcessor", 
"reselector.reselect.columns.include.list": "<schema>.<table>:<column>,<schema>.<table>:<column>", 
"reselector.reselect.unavailable.values": "true", 
"reselector.reselect.null.values": "true" 
"reselector.reselect.use.event.key": "false" 
"reselector.reselect.error.handling.mode": "WARN"
```
which differs from the canonical convention used for `transformers`, `predicates` like:
```txt
transforms=t0
transforms.t0.add.fields=op,table
transforms.t0.add.headers=db,table
transforms.t0.negate=false
```
We support both aligning the new configuration to `transformers` and `predicates`.
```txt …
```
=> DBZ-9170 Align configuration for post processors to transforms, predicates

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/WalPositionLocator.java
This pull request replaces the following misleading statement in the JavaDoc with a more accurate version:
> The LSNs are not guaranteed to be ordered in the WAL.
=> DBZ-9203: Improve WalPositionLocator JavaDoc

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metrics/SqlServerSnapshotPartitionMetrics.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metrics/SqlServerSnapshotTaskMetrics.java, debezium-core/src/main/java/io/debezium/pipeline/meters/SnapshotMeter.java, debezium-core/src/main/java/io/debezium/pipeline/metrics/DefaultSnapshotChangeEventSourceMetrics.java, debezium-core/src/main/java/io/debezium/pipeline/metrics/traits/SnapshotMetricsMXBean.java, debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java, debezium-core/src/main/java/io/debezium/pipeline/source/spi/SnapshotProgressListener.java, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc
https://issues.redhat.com/browse/DBZ-8610 
Add SnapshotSkipped metric as an additive metric which doesn't reset the other snapshot metrics. 
**Build CI errors**
This commit is related to a [PR](https://github.com/debezium/debezium-connector-spanner/pull/115) which implements the changes to the SnapshotProgressListener in `debezium-connector-spanner`. Due to a circular dependency (the spanner connector depends on debezium-core interfaces and the debezium CI depends on the spanner-connector CI test) the failing spanner connector build step should probably be manually ignored. Once this change is in main the corresponding PR in the spanner connector can be merged which will resolve the issue.
**Alternative approach to adding the snapshotSkipped metric**
The currently proposed implementation …
=> DBZ-8610 Add SnapshotSkipped metric

quarkus-debezium-parent/quarkus-debezium-engine-parent/deployment/src/main/java/io/quarkus/debezium/deployment/engine/EngineProcessor.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/pom.xml, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/DebeziumNotification.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/DefaultNotificationHandler.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/Notification.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/NotificationHandler.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/QuarkusNotificationChannel.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/SnapshotAborted.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/SnapshotCompleted.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/SnapshotEvent.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/SnapshotHandler.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/SnapshotInProgress.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/SnapshotPaused.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/SnapshotResumed.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/SnapshotSkipped.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/SnapshotStarted.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/notification/SnapshotTableScanCompleted.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/resources/META-INF/services/io.debezium.pipeline.notification.channels.NotificationChannel, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/test/java/io/quarkus/debezium/notification/QuarkusNotificationChannelTest.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/test/java/io/quarkus/debezium/notification/SnapshotHandlerTest.java, quarkus-debezium-parent/quarkus-debezium-postgres-parent/deployment/src/test/java/io/quarkus/debezium/postgres/deployment/NotificationTest.java, quarkus-debezium-parent/quarkus-debezium-postgres-parent/runtime/src/main/java/io/quarkus/debezium/engine/PostgresEngineProducer.java
Debezium connectors can emit notification events related to internal state changes, such as:
- Snapshot completion
- Other Events
Quarkus developers need a declarative mechanism to observe these events.
Introduce a series of events that are observable using `Observes` like:
```java
@ApplicationScoped
static class SnapshotNotificationsHandler {
public void observe(@Observes SnapshotEvent event) {
// here
}
}
```
#link: https://github.com/debezium/debezium-design-documents/pull/16
#closes: https://issues.redhat.com/browse/DBZ-8964
=> DBZ-8964 Debezium Engine Quarkus Extension: expose Debezium Notification Events

debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/OpenLineageIT.java
Test are failing because we are waiting for port 5432 (postgres) but we are actually working with port (55432) and that makes the test fail. Checking it dynamically solves the problem.
=> DBZ-9201 Fix OpenLineageIT tests

debezium-core/src/main/java/io/debezium/processors/PostProcessorFactory.java, debezium-core/src/main/java/io/debezium/processors/PostProcessorRegistryServiceProvider.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/deployment/src/main/java/io/quarkus/debezium/deployment/PostProcessorGenerator.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/deployment/src/main/java/io/quarkus/debezium/deployment/engine/ClassesInConfigurationHandler.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/deployment/src/main/java/io/quarkus/debezium/deployment/engine/EngineProcessor.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/deployment/src/main/java/io/quarkus/debezium/deployment/engine/GeneratedClassMetaData.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/deployment/src/main/java/io/quarkus/debezium/deployment/engine/InvokerGenerator.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/deployment/src/main/java/io/quarkus/debezium/deployment/engine/PostProcessorGenerator.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/deployment/src/main/resources/META-INF/services/io.debezium.processors.PostProcessorFactory, quarkus-debezium-parent/quarkus-debezium-engine-parent/deployment/src/test/java/io/quarkus/debezium/deployment/engine/ClassesInConfigurationHandlerTest.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/engine/post/processing/ArcPostProcessorFactory.java, quarkus-debezium-parent/quarkus-debezium-engine-parent/runtime/src/main/java/io/quarkus/debezium/engine/post/processing/DynamicPostProcessingSupplier.java, quarkus-debezium-parent/quarkus-debezium-engine-spi-parent/deployment/src/main/java/io/quarkus/debezium/deployment/dotnames/DebeziumDotNames.java, quarkus-debezium-parent/quarkus-debezium-engine-spi-parent/deployment/src/main/java/io/quarkus/debezium/deployment/items/DebeziumGeneratedPostProcessorBuildItem.java, quarkus-debezium-parent/quarkus-debezium-engine-spi-parent/deployment/src/main/java/io/quarkus/debezium/deployment/items/DebeziumMediatorBuildItem.java, quarkus-debezium-parent/quarkus-debezium-engine-spi-parent/runtime/src/main/java/io/debezium/runtime/PostProcessing.java, quarkus-debezium-parent/quarkus-debezium-postgres-parent/deployment/src/test/java/io/quarkus/debezium/postgres/deployment/PostProcessingTest.java, quarkus-debezium-parent/quarkus-debezium-postgres-parent/integration-test/src/main/resources/application.properties
Post processors perform lightweight, per-message mutations, similar to the modifications that are performed by single message transformations (SMTs). Quarkus developers should be able to define `post-processor` in the *normal* way and using a Quarkus way.
In the context of Quarkus, we introduce an annotation `PostProcessing` in order to create `post-processor` inside the Quarkus CDI. like in this example:
```java
@ApplicationScoped
static class PostProcessingHandler {
@PostProcessing()
public void postProcessing(Object key, Struct struct) {
// do your stuff
}
}
```
in this PR we introduce:
#depends https://github.com/debezium/debezium/pull/6523
#closes https://issues.redhat.com/browse/DBZ-8965
#link: https://github.com/debezium/debezium-design-documents/pull/16
We have introduced a …
=> DBZ 8965 Debezium Engine Quarkus Extension: introduce PostProcessor handler

documentation/modules/ROOT/pages/connectors/db2.adoc
Cherry-pick updates to `db2.adoc` from `main`:
- Replaces hard-coded name with `prodname` attribute
- Updates line formatting (one sentence per line)
- Minor language edits
=> [docs] Add line breaks+other edits (3.2)

documentation/modules/ROOT/nav.adoc, documentation/modules/ROOT/pages/transformations/index.adoc
Cherry-pick changes from `main` to `3.2`.
=> Dbz 9244 3.2 remove reference to obsolete file from smt doc index

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/AbstractLogMinerQueryBuilder.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/BufferedLogMinerQueryBuilder.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/BufferedLogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/unbuffered/UnbufferedLogMinerQueryBuilder.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/unbuffered/UnbufferedLogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/CteQueryIT.java
https://issues.redhat.com/browse/DBZ-9272 
While the `log.mining.query.filter.mode` provides ways to push query criteria to the Oracle database to filter the change stream so that we get the least amount of events in the connector, this is not always adequate, especially in situations where there may be far more activity for non-captured tables. In these situations, this can lead to the connector receiving a large number of transaction commit or rollback marker events that have no changes in the transaction.
This PR introduces a new internal, experimental feature that enables the use of a CTE-based query. The CTE query is designed to apply the same filter as the main query, but limits the scope to only non-transaction marker changes (inserts, updates, deletes, LOB operations, DDL, and so …
=> DBZ-9272 Add option to use CTE-based LogMiner queries

debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java
https://issues.redhat.com/browse/DBZ-9237
So the issue here is that when more than one task executes a `CREATE TABLE`, the non-first task will throw a runtime exception, `ConstraintViolationException` in case of PostgreSQL. These runtime exceptions were not being caught previously, and immediately forced the connector to fail. 
This PR is designed to instead fallthrough to the `ALTER TABLE` if the `CREATE TABLE` failed, as a more resilient way to deal with multiple tasks that may attempt to create the table concurrently, allowing the non-first tasks to safely fall through and process the insert, update, or upsert without failing.
=> DBZ-9237 Do not immediately fail JDBC sink if create table fails

documentation/modules/ROOT/pages/connectors/jdbc.adoc
Correct spelling in title of the JDBC vector types mappings table
=> [docs] Fix typo in table title

debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java, debezium-core/src/main/java/io/debezium/util/ByteBuffers.java
The PostProcessor, ReselectColumnsPostProcessor, bug that otherwise occurs when the source table contains a BINARY type column is fixed by the modifications below. With these modifications, HeapByteBuffer and byte array objects will be accurately compared.
=> DBZ-9356 Fix comparing ByteBuffer with byte array

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
SQL Server connector now emits heartbeats while catching up to the current LSN through empty LSN ranges.
=> DBZ-9364 SQL Server Heartbeats in Empty LSN Ranges

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java
https://issues.redhat.com/browse/DBZ-9366
When relaxed quote parsing was enabled and string contains escaped quotes during the inserts and updates, the logic for parsing the column value would reduce the `''` sequence a single `'` for updates, but would leave the `''` untouched for inserts. This caused inserts to publish a value that was not identical to the same value present for updates.
=> DBZ-9366 Adjust relaxed quote insert column value list parsing

documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Fixes a misspelling and a couple of references to Db2 that were inadvertently incorporated into the SQL Server connector documentation when content was copied from the earlier Db2 docs.
=> [docs] Fix typo and copy/paste errors

documentation/modules/ROOT/pages/connectors/mariadb.adoc
Cherry-pick changes from #6672 to 3.2
=> Dbz 9367 3.2 doc update to specify that mariadb connector does not support binlog compression

documentation/modules/ROOT/pages/connectors/oracle.adoc
Fixes a downstream build error by updating a cross-reference to refer to the correct  `ModuleID` for the topic _Creating a user account for the connector_.  DBZ-9129 replaced the original `ModuleID`, but did not update the target in the `xref` link that appears earlier in the file.
=> [docs] Updates xref to match new ModuleID for Creating Oracle user topic

documentation/modules/ROOT/pages/connectors/jdbc.adoc
[DBZ-9414 ](https://issues.redhat.com/browse/DBZ-9414)
- Content edits and fixes to address build errors.
- Refactoring of JDBC Transformations topic; 4th level headings converted to description list entries.
- Miscellaneous editorial changes.
=> Dbz 9414 fix downstream build error due to misinterpreted formatting tags

documentation/modules/ROOT/pages/connectors/jdbc.adoc
[DBZ-9414](https://issues.redhat.com/browse/DBZ-9414)
Cherry-pick from `main`. 
- JDBC connector content edits and fixes to address build errors.
- Refactoring of JDBC Transformations topic; 4th level headings converted to description list entries.
- Miscellaneous editorial changes.
=> Dbz 9414 cherry pick jdbc connector updates from main

debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java, debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresPublicationTableComparisonTest.java
Addressing https://issues.redhat.com/browse/DBZ-9395
Also, replaced client-side `Statement#setQueryTimeout(...)` with server-side `SET statement_timeout` at session scope to prevent orphaned queries when the connector stops or shuts down ungracefully. `setQueryTimeout` only cancels on the client, if the client disappears while the DB is waiting/blocked, the server query can keep running, leaking resources. `statement_timeout` is enforced by PostgreSQL, so the server cancels the statement even if the client is gone.
=> DBZ-9395: Selectively call ALTER PUBLICATION for filtered publication

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
https://issues.redhat.com/browse/DBZ-9413
@mfvitale this was the fix and the reason we were seeing odd behaviors with offsets during blocking snapshots :sob: I am curious to see how tests fair with this change, along with incremental snapshots :crossed_fingers:
=> DBZ-9413 Fix offset changes for incremental/blocking snapshots

documentation/modules/ROOT/pages/connectors/jdbc.adoc
(cherry picked from commit 39dd8d68d93d16fbdb401b98f678c6945e5435db)
=> [docs] Fix typo

documentation/modules/ROOT/pages/connectors/oracle.adoc
[DBZ-9402](https://issues.redhat.com/browse/DBZ-9402)
Adds information to Oracle _Data Types_ section about data types that the connector does not support.
=> DBZ-9402-adds-section-to-discuss-unsupported-oracle-datatypes

documentation/modules/ROOT/pages/connectors/jdbc.adoc
Adds `sink` designation to initial ID and heading strings
Tested in local Antora build to ensure that the change does not introduce build errors.
=> [docs] Reflect connector type in title and anchor ID

documentation/modules/ROOT/pages/connectors/jdbc.adoc
This change adjusts metadata in the JDBC connector doc to correct build errors in the downstream documentation: 
- Reverts earlier change to the top-level heading and anchor ID, instead applying those changes via downstream metadata annotations.
- Adds missing anchor ID for designated concept topic
=> [docs] Adjustments to correct downstream build errors

documentation/modules/ROOT/pages/connectors/oracle.adoc
A note in the Oracle connector Extended Strings topic linked to the Tech Preview release note for the feature. In the 3.2.3 release, the feature is promoted to GA. This change updates the link to reflect that change.
=> [doc] Fix URL in link to release notes from Extended strings topic

documentation/modules/ROOT/pages/connectors/mongodb-sink.adoc, documentation/modules/ROOT/pages/connectors/oracle.adoc
Adjusts the following issues constructions that led to errors in the downstream User guide build:
- Missing ID that prevented tooling from creating downstream topic module file
- Non-standard ID and xref formatting (` xref:#_archive_log_destinations[]`
- Escaped curly brace preceding property value that the parser mistook for an asciidoc attribute
=> [docs] Adjustments to resolve downstream build errors

documentation/modules/ROOT/pages/connectors/mongodb.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc, documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc
[DBZ-9510](https://issues.redhat.com/browse/DBZ-9510)
Add entries for the `NumberOfErroneousEvents` metric to the shared tables of snapshot and streaming metrics.
Tested in a local Antora and downstream builds.
Please backport to `3.2` and `3.3`.
=> DBZ-9510 Documents the `NumberOfErroneousEvents` metric
