- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
https://github.com/debezium/debezium/pull/5055 introduced this unfortunate mistake
> DBZ-7236 simple fix of inversed if logic

- debezium-core/src/main/java/io/debezium/data/SchemaUtil.java
- debezium-core/src/main/java/io/debezium/relational/mapping/ColumnMappers.java
- debezium-core/src/main/java/io/debezium/relational/mapping/PropagateSourceMetadataToSchemaParameter.java
- debezium-core/src/main/java/io/debezium/schema/SchemaFactory.java
- debezium-core/src/main/java/io/debezium/transforms/ExtractSchemaToNewRecord.java
- debezium-core/src/test/java/io/debezium/transforms/AbstractExtractStateTest.java
- debezium-core/src/test/java/io/debezium/transforms/ExtractSchemaToNewRecordTest.java
https://issues.redhat.com/browse/DBZ-7145
@Naros @jpechane Please help to review it. Refer the schema history change schema and add the `metadata`(not sure is an appropriate name) block to payload.
I will add a IT tests for this SMT later.
> DBZ-7145 Introduce a new SMT to extract table schema information for jdbc sink connector

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-7218
> DBZ-7218 Clarify Oracle log destination requirements

- pom.xml
https://issues.redhat.com/browse/DBZ-7238
> DBZ-7238 Upgrade Kafka to 3.6.1

- documentation/modules/ROOT/pages/operations/debezium-server.adoc
Documentation for https://github.com/debezium/debezium-server/pull/55
> DBZ-6071 [doc] document `StreamNameMapper` support for Kafka sink

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/antlr/listener/AlterTableParserListener.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
- debezium-core/src/main/java/io/debezium/relational/ColumnEditor.java
- debezium-core/src/main/java/io/debezium/relational/ColumnEditorImpl.java
https://issues.redhat.com/browse/DBZ-7251
> DBZ-7251 Length value is not removed when changing a column's type

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
https://issues.redhat.com/browse/DBZ-7237
This reworks the original code in https://github.com/debezium/debezium/pull/5082 to be based on aligning snapshot output to streaming instead.
> DBZ-7237 Align LOB behavior in snapshot and streaming

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-7252
@jpechane This also affect the notifications in upper level -- see https://issues.redhat.com/browse/DBZ-7253 However there I don't see any simple solution, so for now I'd recommend just documenting that the offset information may be incorrect in certain cases. 
//cc @mfvitale
> DBZ-7252 Using correct offsets in table/collection notifications for MongoDB

- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/informix.adoc
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/mysql.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
[DBZ-6834](https://issues.redhat.com/browse/DBZ-6834)
Applies changes to the description of the `incremental.snapshot.watermarking.strategy` property in all of the relevant connector documentation files.
> DBZ-6834 Updates property decription

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-7264
> DBZ-7264: Propagating exception when using multiple snapshotting threads

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ReplicaSetDiscovery.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/ReplicaSet.java
https://issues.redhat.com/browse/DBZ-7272
> DBZ-7272 Guarding against implicit offset invalidation 

- COPYRIGHT.txt
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SignalsIT.java
- debezium-core/src/main/java/io/debezium/pipeline/signal/channels/KafkaSignalChannel.java
- jenkins-jobs/scripts/config/Aliases.txt
Documentation: https://github.com/debezium/debezium/pull/5116
> DBZ-7164 Support offset commit for the signal topic

- documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-pass-through-kafka-signals-configuration-properties.adoc
Implementation: https://github.com/debezium/debezium/pull/5112
> DBZ-7164 Support offset commit for the signal topic documentation

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/converters/MongoDbCloudEventsMaker.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/converters/MongoDbCloudEventsProvider.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/CloudEventsConverterIT.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/converters/MySqlCloudEventsMaker.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/converters/MySqlCloudEventsProvider.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/converters/OracleCloudEventsMaker.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/converters/OracleCloudEventsProvider.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/converters/PostgresCloudEventsMaker.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/converters/PostgresCloudEventsProvider.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/converters/SqlServerCloudEventsMaker.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/converters/SqlServerCloudEventsProvider.java
- debezium-core/src/main/java/io/debezium/converters/CloudEventsConverter.java
- debezium-core/src/main/java/io/debezium/converters/CloudEventsConverterConfig.java
- debezium-core/src/main/java/io/debezium/converters/spi/CloudEventsMaker.java
- debezium-core/src/main/java/io/debezium/converters/spi/CloudEventsProvider.java
- debezium-core/src/main/java/io/debezium/converters/spi/CloudEventsValidator.java
- debezium-core/src/test/java/io/debezium/converters/CloudEventsConverterTest.java
- debezium-embedded/src/test/java/io/debezium/converters/AbstractCloudEventsConverterTest.java
https://issues.redhat.com/browse/DBZ-7235
> DBZ-7235 Add config option to customize CloudEvent schema type name

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
- debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lnpls/CREATE-PACKAGE-statement.html#GUID-03A70A54-90FF-4293-B6B8-F0B35E184AC5
> DBZ-7283 Support for Creating EDITIONABLE or NONEDITIONABLE Packages

- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java
Adding more log to help the investigation of https://issues.redhat.com/browse/DBZ-7256
> DBZ-7256 Enhance logs for incremental snapshot

- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/CommitScnTest.java
https://issues.redhat.com/browse/DBZ-7288
> DBZ-7288 Unittest for hasCommitAlreadyBeenHandled in CommitScn Class

- debezium-connector-mongodb/src/main/resources/META-INF/services/org.apache.kafka.connect.source.SourceConnector
- debezium-connector-mongodb/src/main/resources/META-INF/services/org.apache.kafka.connect.transforms.Transformation
- debezium-connector-mysql/src/main/resources/META-INF/services/org.apache.kafka.connect.source.SourceConnector
- debezium-connector-mysql/src/main/resources/META-INF/services/org.apache.kafka.connect.transforms.Transformation
- debezium-connector-oracle/src/main/resources/META-INF/services/org.apache.kafka.connect.source.SourceConnector
- debezium-connector-postgres/src/main/resources/META-INF/services/org.apache.kafka.connect.source.SourceConnector
- debezium-connector-postgres/src/main/resources/META-INF/services/org.apache.kafka.connect.transforms.Transformation
- debezium-connector-sqlserver/src/main/resources/META-INF/services/org.apache.kafka.connect.source.SourceConnector
- debezium-core/src/main/resources/META-INF/services/org.apache.kafka.connect.storage.Converter
- debezium-core/src/main/resources/META-INF/services/org.apache.kafka.connect.storage.HeaderConverter
- debezium-core/src/main/resources/META-INF/services/org.apache.kafka.connect.transforms.Transformation
Add manifests for source/sink connectors, converters and transformations.
> DBZ-7298 Add service loader manifests for all Connect plugins

- debezium-embedded/src/main/java/io/debezium/embedded/ConvertingEngineBuilder.java
https://issues.redhat.com/browse/DBZ-7098
> DBZ-7098 Converting engine should honor unsupported tombstone flag

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
- debezium-core/src/main/java/io/debezium/util/Strings.java
https://issues.redhat.com/browse/DBZ-7315
> DBZ-7315 Fix Oracle include/exclude lists with spaces

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/BlockingSnapshotIT.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/source/SnapshottingTask.java
- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
- debezium-embedded/src/test/java/io/debezium/pipeline/AbstractBlockingSnapshotTest.java
closes: https://issues.redhat.com/browse/DBZ-7311
> DBZ-7311 Permits to execute a blocking snapshot even if snapshot.mode=never

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionCommitConsumerIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/LogMinerHelperTest.java
Backports for Debezium 2.3 for Oracle missed transaction fixes.
> Debezium 2.3 Oracle backports

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeEventSourceCoordinator.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/QueryingSnapshotter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/spi/Snapshotter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/BlockingSnapshotIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/CustomTestSnapshot.java
closes: [DBZ-7312](https://issues.redhat.com/browse/DBZ-7312)
> DBZ-7312 On demand blocking snapshot will not set transaction snapshot

- pom.xml
https://issues.redhat.com/browse/DBZ-7352
> DBZ-7352 Upgrade to Quarkus 3.6.5

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetrics.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetricsMXBean.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-7313
> DBZ-7313: Oracle Infinispan abandoned trasactions minor enhancements

- COPYRIGHT.txt
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/NotificationsIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/NotificationsIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/NotificationsIT.java
- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
- jenkins-jobs/scripts/config/Aliases.txt
Proposed solution to the feature request seen in DBZ-7347. Could potentially be done in a nicer way with an interface api change but can easily get around that for now.
https://issues.redhat.com/browse/DBZ-7347
> DBZ-7347 Initial snapshot notifications should use full identifier

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDecimalIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlJdbcSinkDataTypeConverterIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlDefaultValueIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotCaseSensitiveIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDefaultValueIT.java
https://issues.redhat.com/browse/DBZ-7355
> DBZ-7355 Skip Avro serialization validation

- debezium-bom/pom.xml
- debezium-core/pom.xml
- debezium-microbenchmark/pom.xml
- debezium-scripting/debezium-scripting-languages/pom.xml
- debezium-scripting/debezium-scripting/pom.xml
- documentation/antora.yml
- documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-db2-kafka-connect-yaml.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-oracle-kafka-connect-yaml.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/shared-deploy-kafka-connect-yaml.adoc
- jenkins-jobs/scripts/upstream-artifact-server-prepare.sh
https://issues.redhat.com/browse/DBZ-7340
> DBZ-7340 Upgrade Groovy and GraalJS to the latest 2023 version

- debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/JdbcCommonConfig.java
addresses https://issues.redhat.com/browse/DBZ-7366
> DBZ-7366 use `withMaskedPasswords()` to mask password of `JdbcSchemaHistory` config

- debezium-core/src/main/java/io/debezium/transforms/TimezoneConverter.java
- debezium-core/src/test/java/io/debezium/transforms/TimezoneConverterTest.java
- documentation/modules/ROOT/pages/transformations/timezone-converter.adoc
https://issues.redhat.com/browse/DBZ-7022
> DBZ-7022 Allow conversion of source block timestamp fields in TZ SMT

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-7376
> DBZ-7376 Fix logging for schema only recovery in mysql

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
- debezium-core/src/main/java/io/debezium/pipeline/txmetadata/TransactionContext.java
https://issues.redhat.com/browse/DBZ-7380
> DBZ-7380 Offset transaction id only when it's non null

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
https://issues.redhat.com/browse/DBZ-7273
> DBZ-7273: Introduce mode to query capture tables directly

- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/DockerKafkaController.java
https://issues.redhat.com/browse/DBZ-7386
> DBZ-7386 Remove Lombok in system testsuite

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotParallelProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
https://issues.redhat.com/browse/DBZ-7382
> DBZ-7382 Don't check record order in parallel snapshot tests

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
https://issues.redhat.com/browse/DBZ-7299
> DBZ-7299 Ability to use post images for full document update

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
https://issues.redhat.com/browse/DBZ-7299
Backport for https://github.com/debezium/debezium/pull/5192
> [2.5] DBZ-7299 Ability to use post images for full document update

- debezium-schema-generator/pom.xml
- pom.xml
https://issues.redhat.com/browse/DBZ-7387
> DBZ-7387 Use Java 17 for compile time

- debezium-quarkus-outbox-common/deployment/pom.xml
- debezium-quarkus-outbox-common/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/DebeziumOutboxCommonConfig.java
- debezium-quarkus-outbox-common/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/OutboxEventHbmWriter.java
- debezium-quarkus-outbox-common/runtime/pom.xml
- debezium-quarkus-outbox-reactive/integration-tests/src/test/java/io/debezium/outbox/reactive/quarkus/it/AbstractOutboxTest.java
- debezium-quarkus-outbox-reactive/integration-tests/src/test/java/io/debezium/outbox/reactive/quarkus/it/OutboxTest.java
- debezium-quarkus-outbox-reactive/integration-tests/src/test/java/io/debezium/outbox/reactive/quarkus/it/OutboxWithoutOpenTelemetryTest.java
- debezium-quarkus-outbox-reactive/integration-tests/src/test/java/io/debezium/outbox/reactive/quarkus/it/TestAsserts.java
- debezium-quarkus-outbox-reactive/pom.xml
- debezium-quarkus-outbox-reactive/runtime/src/main/java/io/debezium/outbox/reactive/quarkus/internal/DebeziumOutboxHandler.java
- debezium-quarkus-outbox-reactive/runtime/src/main/java/io/debezium/outbox/reactive/quarkus/internal/DebeziumTracerEventDispatcher.java
- debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/AbstractOutboxTest.java
- debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/OutboxWithoutOpenTelemetryTest.java
- debezium-quarkus-outbox/integration-tests/src/test/java/io/debezium/outbox/quarkus/it/TestAsserts.java
- pom.xml
https://issues.redhat.com/browse/DBZ-7388
This PR includes the same commits from PR #5186, as it depends on those changes.  Please merge that PR first, and then we can rebase this PR to support Quarkus 3.7 with the Outbox extension.
> DBZ-7388 Upgrade Outbox Extension to Quarkus 3.7.0

- documentation/modules/ROOT/pages/connectors/mysql.adoc
[DBZ-7143](https://issues.redhat.com/browse/DBZ-7143)
Edit description for style, clarity.
> DBZ-7143 Edit description of MySQL event.converting.failure.handling.mode

- documentation/modules/ROOT/pages/connectors/jdbc.adoc
https://issues.redhat.com/browse/DBZ-7431
Awaits https://github.com/debezium/debezium-connector-jdbc/pull/60
> DBZ-7431 Document JDBC connector sink option `connection.provider`

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/DefaultMongoDbAuthProvider.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/MongoDbConnectionContext.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/client/DefaultMongoDbClientFactory.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/client/MongoDbClientFactory.java
https://issues.redhat.com/browse/DBZ-7379
> DBZ-7379 Connector specific keystore/truststore

- debezium-testing/debezium-testing-system/pom.xml
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/ConnectorConfigBuilder.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/registry/OcpApicurioController.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/registry/OcpApicurioDeployer.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/registry/builders/FabricApicurioBuilder.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/assertions/AvroKafkaAssertions.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/assertions/KafkaAssertions.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/assertions/PlainKafkaAssertions.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/db2/Db2Tests.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/mongodb/MongoTests.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/mysql/MySqlTests.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/oracle/OracleTests.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/postgresql/PostgreSqlTests.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/sqlserver/SqlServerTests.java
- debezium-testing/debezium-testing-system/src/test/resources/kube/Pod.example.yaml
- Bumping apicurio model version
- Adding test for unwrap SMT
> DBZ-7432 Create systemtests for Unwrap SMT

- pom.xml
https://issues.redhat.com/browse/DBZ-7442
> DBZ-7442 Upgrade protobuf to 3.25.2

- debezium-core/src/main/java/io/debezium/util/Stopwatch.java
- debezium-core/src/test/java/io/debezium/util/StopwatchTest.java
closes: https://issues.redhat.com/browse/DBZ-7436
> DBZ-7436 Add empty statistics for SingleDuration to avoid NPE

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
Doc for https://github.com/debezium/debezium/pull/5157
> DBZ-7300 Review PostgreSQL documentations with new Snapshotter interfaces

- pom.xml
https://issues.redhat.com/browse/DBZ-7449
> DBZ-7449 Upgrade Quarkus (Debezium Server) to 3.2.9.Final

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/StreamingAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/olr/OpenLogReplicatorAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamAdapter.java
https://issues.redhat.com/browse/DBZ-7425
> DBZ-7425 Use adapter-specific offset loaders when copying offsets

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/transforms/timescaledb/TimescaleDbDatabaseTest.java
closes: https://issues.redhat.com/browse/DBZ-7452
> DBZ-7452 defaultJdbcConfig will use correct hostname and port from parameters

- debezium-connect-rest-extension/src/main/java/io/debezium/kcrestextension/DebeziumResource.java
- debezium-connect-rest-extension/src/test/java/io/debezium/kcrestextension/DebeziumResourceIT.java
Added deduplication with a Map with a key based on the SMT's fully-qualified class name and version.
closes https://issues.redhat.com/browse/DBZ-7416
> DBZ-7416 Fix duplicate SMTs sometimes returned by Kafka Connect

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeEventSourceCoordinator.java
closes: https://issues.redhat.com/browse/DBZ-7467
> DBZ-7467 Fix missing signaling actions

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/BaseChangeRecordEmitter.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
https://issues.redhat.com/browse/DBZ-7456
> DBZ-7456 Skip PK change LOB column reselect if column is excluded

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/client/DefaultMongoDbClientFactory.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotChangeEventSource.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/AbstractMongoConnectorIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/AbstractMongoIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/IncrementalSnapshotIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TestHelper.java
https://issues.redhat.com/browse/DBZ-7451
> DBZ-7451 Support for standard BSON representation of UUID in incremental snapshots

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/custom/snapshotter/CustomTestSnapshot.java
- debezium-connector-postgres/src/test/resources/META-INF/services/io.debezium.snapshot.spi.SnapshotQuery
- debezium-connector-postgres/src/test/resources/META-INF/services/io.debezium.spi.snapshot.Snapshotter
- debezium-core/src/main/java/io/debezium/snapshot/SnapshotterServiceProvider.java
closes: https://issues.redhat.com/browse/DBZ-7481
> DBZ-7481 SnapshotterServiceProvider will check if snapshot mode class is related to the running connector.

- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/listeners/NamespacePreparationListener.java
https://issues.redhat.com/browse/DBZ-7002
Also added minor refactor for better code readability
> DBZ-7002 Remove the need for OCP cluster in non-OCP system tests

- documentation/modules/ROOT/pages/operations/logging.adoc
Additional fixes to callout Cherrypicked from #5264
> Dbz 7418 cherry pick from main pr 5264

- documentation/modules/ROOT/pages/operations/logging.adoc
Cherry-picks changes to `2.5` from #5264 on `main`
> Dbz 7418 2.5 cherry pick from main pr 5264

- .github/workflows/oracle-workflow-test.yml
https://issues.redhat.com/browse/DBZ-7494
> DBZ-7494 Skip Oracle integration tests on GitHub actions

- .github/workflows/debezium-workflow.yml
https://issues.redhat.com/browse/DBZ-7490
> DBZ-7490 Add Informix to Debezium CI workflow

- debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java
- debezium-embedded/src/test/java/io/debezium/processors/AbstractReselectProcessorTest.java
https://issues.redhat.com/browse/DBZ-7488
> DBZ-7488 Skip re-selection on `r` (read) events

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouterTest.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/SourceInfoTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SourceInfoTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SourceInfoTest.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SourceInfoTest.java
- debezium-core/src/main/java/io/debezium/connector/AbstractSourceInfo.java
- debezium-core/src/main/java/io/debezium/connector/AbstractSourceInfoStructMaker.java
- debezium-core/src/main/java/io/debezium/data/Envelope.java
- debezium-core/src/main/java/io/debezium/schema/SchemaFactory.java
- debezium-core/src/test/java/io/debezium/data/EnvelopeTest.java
- debezium-core/src/test/resources/json/serde-with-schema.json
https://issues.redhat.com/browse/DBZ-7107
@jpechane once we agree on the implementation, I'll address the documentation.
> DBZ-7107 Introduce micro/nano second based envelope timestamps

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/PreambleSingleColumnReconstructedSelectParser.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleXmlDataTypesIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/XmlBeginParserTest.java
https://issues.redhat.com/browse/DBZ-7489
> DBZ-7489 Correctly parse XML preamble SQL ending with "IS NULL"

- documentation/modules/ROOT/pages/connectors/mysql.adoc
https://issues.redhat.com/browse/DBZ-7487
> DBZ-7487 Document enablement of MariaDB mode

- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java
https://issues.redhat.com/browse/DBZ-7504
> DBZ-7504 Fix LogMinerHelperIT random test failure

- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/pipeline/signal/SignalProcessor.java
- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEngineConfig.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
- debezium-embedded/src/test/java/io/debezium/embedded/async/AsyncEmbeddedEngineTest.java
https://issues.redhat.com/browse/DBZ-7496
https://issues.redhat.com/browse/DBZ-7495
> DBZ-7496 Make sure completion callback is called after engine is stopped

- LICENSE-3rd-PARTIES.txt
- debezium-connector-oracle/pom.xml
https://issues.redhat.com/browse/DBZ-7364
> DBZ-7364 Distribute Oracle ojdbc8 with Oracle connector

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SignalsIT.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/relational/TableId.java
https://issues.redhat.com/browse/DBZ-7480
> DBZ-7480 Allow special characters in signal table name

- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbReplicaSet.java
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/testhelper/RestExtensionTestInfrastructure.java
https://issues.redhat.com/browse/DBZ-7054
> DBZ-7054 Move timeout configuration of MongoDbReplicaSet into Builder class

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSourceInfoStructMaker.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/events/RedoSqlDmlEvent.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/marshalling/LogMinerEventMarshaller.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/marshalling/RedoSqlDmlEventAdapter.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SourceInfoTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerSourceInfoRedoSqlIT.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-6960
> DBZ-6960 Include REDO SQL in Oracle source info block

- .github/workflows/debezium-workflow.yml
This reverts commit 3b470c30388a96278b760a849ba31181e1fadbf2.
> DBZ-7490 Revert "DBZ-7490 Disable IT tests"

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerReselectColumnsProcessorIT.java
- debezium-embedded/src/test/java/io/debezium/processors/AbstractReselectProcessorTest.java
https://issues.redhat.com/browse/DBZ-7516
> DBZ-7516 Correctly enable table CDC to avoid failures

- documentation/modules/ROOT/pages/connectors/jdbc.adoc
https://issues.redhat.com/browse/DBZ-7521
> DBZ-7521 Promote JDBC sink from Incubating

- debezium-testing/debezium-testing-system/pom.xml
https://issues.redhat.com/browse/DBZ-7520
> DBZ-7520 Upgrade commons-commpress to 1.26.0

- documentation/modules/ROOT/pages/configuration/notification.adoc
- documentation/modules/ROOT/pages/development/converters.adoc
- documentation/modules/ROOT/pages/integrations/cloudevents.adoc
Applies  #5311 changes from `main` to `2.5` to fix funky rendering of callout descriptions.
> DBZ-7418 Cherry pick pr 5311 from main to 2.5

- documentation/modules/ROOT/pages/configuration/notification.adoc
- documentation/modules/ROOT/pages/development/converters.adoc
- documentation/modules/ROOT/pages/integrations/cloudevents.adoc
Cherry-pick #5311 to apply changes from `main` to `2.3` to fix funky rendering of callout descriptions.
> Dbz 7418 cherry pick pr 5311 from main

- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
- debezium-embedded/src/test/java/io/debezium/embedded/async/AsyncEmbeddedEngineTest.java
- debezium-embedded/src/test/java/io/debezium/embedded/async/DebeziumAsyncEngineTestUtils.java
Add also `INFO` log with number of failed tasks.
https://issues.redhat.com/browse/DBZ-7535
> DBZ-7535 Ensure at least one task starts and one fails

- .github/workflows/debezium-workflow.yml
- debezium-connect-rest-extension/src/main/java/io/debezium/kcrestextension/DebeziumResource.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/metadata/MongoDbConnectorMetadata.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/rest/DebeziumMongoDbConnectorResource.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/metadata/MySqlConnectorMetadata.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/rest/DebeziumMySqlConnectorResource.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/metadata/OracleConnectorMetadata.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/rest/DebeziumOracleConnectorResource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metadata/PostgresConnectorMetadata.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/rest/DebeziumPostgresConnectorResource.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metadata/SqlServerConnectorMetadata.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/rest/DebeziumSqlServerConnectorResource.java
- debezium-core/src/main/java/io/debezium/metadata/ConnectorDescriptor.java
- debezium-core/src/main/java/io/debezium/rest/ConnectionValidationResource.java
- debezium-core/src/main/java/io/debezium/rest/ConnectorAware.java
- debezium-core/src/main/java/io/debezium/rest/FilterValidationResource.java
Moved deduplication from Map to LinkedHashSet, based on feedback from #5242
closes https://issues.redhat.com/browse/DBZ-7416
> DBZ-7416 Fix duplicate SMTs sometimes returned by Kafka Connect. 

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-7559
> DBZ-7559 Retry XStream ORA-23656 exceptions

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotParallelProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
https://issues.redhat.com/browse/DBZ-7530
@jpechane here is what I came up with and it seems stable across Parallel and Non-Parallel snapshots
> DBZ-7530 DBZ-7534 DBZ-7453 Stablize PG tests

- COPYRIGHT.txt
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnector.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- jenkins-jobs/scripts/config/Aliases.txt
this resolves [DBZ-2015](https://issues.redhat.com/browse/DBZ-2015)
PTAL @jpechane
> DBZ-2015 Remove redundant fields

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresDefaultValueConverterIT.java
https://issues.redhat.com/browse/DBZ-7562
> DBZ-7562 Truncate values that exceed column scale

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-7565
> DBZ-7565 Align PostgreSQL `hstore.handling.mode` default values

- documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-db2-ora-pg-connector.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/proc-using-streams-to-deploy-a-debezium-mongodb-connector.adoc
(cherry picked from commit 82b5a0b84cc37c299529b0581111a58d69f9e829)
> DBZ-7499 Fix deployment examples that expose attribute names vs values

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresDefaultValueConverterIT.java
https://issues.redhat.com/browse/DBZ-7582
> DBZ-7582 Correctly serialize toasted HSTORE values when unavailable

- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/InsertWindowCloser.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedIncrementalSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/SignalMetadata.java
https://issues.redhat.com/browse/DBZ-6858
> DBZ-6858 Timestamp metadata for watermarking signals

- pom.xml
https://issues.redhat.com/browse/DBZ-7574
> DBZ-7574 Upgrade Kafka to 3.7.0

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-7072
> DBZ-7072 Retry Oracle Flashback-based snapshot queries

- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
- debezium-embedded/src/test/java/io/debezium/embedded/async/AsyncEmbeddedEngineTest.java
https://issues.redhat.com/browse/DBZ-7568
> Use default wait time in all AsyncEmbeddedEngineTest

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
https://issues.redhat.com/browse/DBZ-7581
> DBZ-7581 Log exception and stack trace

- debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-infinispan.xml
https://issues.redhat.com/browse/DBZ-7579
> DBZ-7579 Exclude OpenLogReplicator dependencies

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/DefaultMongoDbAuthProvider.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TestHelper.java
https://issues.redhat.com/browse/DBZ-6434
> DBZ-6434 Handle NPE due to missing credentials

- .github/workflows/jdk-outreach-workflow.yml
https://issues.redhat.com/browse/DBZ-7510
> DBZ-7510 Add Informix to Java Outreach

- .github/workflows/debezium-workflow.yml
- .github/workflows/jdk-outreach-workflow.yml
https://github.com/debezium/debezium-connector-db2/pull/141 changes Db2 flaky handling to the unified one
> [ci] Use unified flaky flag for Db2

- documentation/modules/ROOT/pages/connectors/mysql.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/custom-snapshotter-spi.adoc
docs for https://github.com/debezium/debezium/pull/5245
> DBZ-7461 Update doc for snapshot modes alignment

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/CloudEventsConverterIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TransactionMetadataIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/IncrementalSnapshotIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlMetricsIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlParserIT.java
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MysqlNonUtfDatabaseCharsetIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresShutdownIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresConnectionIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/transforms/timescaledb/TimescaleDbDatabaseTest.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectionIT.java
- debezium-storage/debezium-storage-jdbc/src/test/java/io/debezium/storage/jdbc/history/JdbcSchemaHistoryIT.java
closes: https://issues.redhat.com/browse/DBZ-7588
> DBZ-7588 Disable debug prints on tests

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/events/LogMinerEventRow.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerColumnResolverDmlParser.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBinaryModeIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleRawDataTypeIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleReselectColumnsProcessorIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleXmlDataTypesIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SnapshotDatatypesIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/StreamingDatatypesIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/junit/SkipTestDependingOnStrategyRule.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/junit/SkipWhenLogMiningStrategyIs.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/HybridMiningStrategyIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerEventRowTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionCommitConsumerIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/AbstractProcessorUnitTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-3401
> DBZ-3401 Add new hybrid mining strategy

- debezium-bom/pom.xml
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-storage/debezium-storage-rocketmq/pom.xml
- debezium-storage/debezium-storage-rocketmq/src/main/java/io/debezium/storage/rocketmq/RocketMqAdminUtil.java
- debezium-storage/debezium-storage-rocketmq/src/main/java/io/debezium/storage/rocketmq/history/RocketMqSchemaHistory.java
- pom.xml
https://issues.redhat.com/browse/DBZ-7525
> DBZ-7525 Update to RocketMQ 5.1.4

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/snapshot/SqlServerSnapshotLockProvider.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/snapshot/SqlServerSnapshotterServiceProvider.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/snapshot/lock/ExclusiveSnapshotLock.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/snapshot/lock/NoSnapshotLock.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/snapshot/query/SelectAllSnapshotQuery.java
- debezium-connector-sqlserver/src/main/resources/META-INF/services/io.debezium.snapshot.spi.SnapshotLock
- debezium-connector-sqlserver/src/main/resources/META-INF/services/io.debezium.snapshot.spi.SnapshotQuery
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/CustomTestSnapshot.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-connector-sqlserver/src/test/resources/META-INF/services/io.debezium.snapshot.spi.SnapshotQuery
- debezium-connector-sqlserver/src/test/resources/META-INF/services/io.debezium.spi.snapshot.Snapshotter
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-core/src/main/java/io/debezium/snapshot/SnapshotLockProvider.java
- debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
closes: https://issues.redhat.com/browse/DBZ-7303
The PR is based on https://github.com/debezium/debezium/pull/5245, so duplicate commits depends on that.
> DBZ-7303: Align snapshot modes for SQLServer

- documentation/modules/ROOT/pages/connectors/mysql.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
docs for https://github.com/debezium/debezium/pull/5334
> DBZ-7303 Update doc for snapshot modes alignment

- debezium-connector-oracle/src/test/resources/Dockerfile.rest.test
https://issues.redhat.com/browse/DBZ-7597
> DBZ-7597 No need to install driver, it's included by default

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/marshalling/XmlWriteEventAdapter.java
https://issues.redhat.com/browse/DBZ-7598
> DBZ-7598 Permit Infinispan nullable XML value serialization

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerUtilsTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
https://issues.redhat.com/browse/DBZ-7610
> DBZ-7610 Remove deprecated, undocumented continuous mining option

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetrics.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-7619
> DBZ-7619 Metric ScnFreezeCount never increases

- debezium-core/src/main/java/io/debezium/transforms/AbstractExtractNewRecordState.java
- debezium-core/src/test/java/io/debezium/transforms/AbstractExtractStateTest.java
- debezium-core/src/test/java/io/debezium/transforms/ExtractNewRecordStateTest.java
https://issues.redhat.com/browse/DBZ-7615
> DBZ-7615 Fix struct resolution for micro/nano second envelope time

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
closes: https://issues.redhat.com/browse/DBZ-7608
> DBZ-7608 Resolve performance issue during addSchemaEvent

- .github/workflows/debezium-workflow-pr.yml
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbReplicaSet.java
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbShardedCluster.java
https://issues.redhat.com/browse/DBZ-7626
> DBZ-7626 MongoDbReplicaSet & MongoDbShardedCluster reuse networks by default

- pom.xml
https://issues.redhat.com/browse/DBZ-7623
> DBZ-7623 Update Debezium Quarkus Outbox to Quarkus 3.8.2

- pom.xml
https://issues.redhat.com/browse/DBZ-7624
> DBZ-7624 Update Debezium Server/Operator to Quarkus 3.2.10

- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java
https://issues.redhat.com/browse/DBZ-7611
> DBZ-7611 Exclude signal table from re-selection

- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/databases/mongodb/sharded/OcpMongoShardedDeployer.java
https://issues.redhat.com/browse/DBZ-7634
> DBZ-7634 removed leftover lombok usage

- documentation/modules/ROOT/pages/post-processors/reselect-columns.adoc
- documentation/modules/ROOT/pages/transformations/timezone-converter.adoc
[DBZ-7602](https://issues.redhat.com/browse/DBZ-7602)
Cherry-pick from `main`
> DBZ-7602 Prepare TZ SMT and post processor docs for 2.5

- documentation/modules/ROOT/pages/connectors/oracle.adoc
> [Docs] Fix typo in Oracle connector documentation

- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
related to: https://github.com/debezium/debezium-connector-db2/pull/142
> DBZ-7305 Update Db2 doc for snapshot modes alignment

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractChunkQueryBuilder.java
- debezium-core/src/main/java/io/debezium/relational/Key.java
- debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/DefaultChunkQueryBuilderTest.java
closes: https://issues.redhat.com/browse/DBZ-7617
> DBZ-7616 Incremental snapshot query doesn't honor message.key.columns order

- jenkins-jobs/docker/artifact-server/listing.sh
https://issues.redhat.com/browse/DBZ-7644
> DBZ-7644 Add JDBC connector to listing.sh in artefact server

- pom.xml
https://issues.redhat.com/browse/DBZ-7656
> DBZ-7656 Upgrade Debezium Quarkus Outbox Extension to Quarkus 3.8.3

- pom.xml
https://issues.redhat.com/browse/DBZ-7652
> DBZ-7652 Upgrade MySQL driver to 8.3.0

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerUtilsTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
https://issues.redhat.com/browse/DBZ-7645
> DBZ-7645 Revert removal of LogMiner continuous mining

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
Logged https://issues.redhat.com/browse/DBZ-7655 to follow-up on fixing this.
> [ci] Mark SqlServerConnectorIT restartInMiddleOfTx* tests Flaky

- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleReselectColumnsProcessorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresReselectColumnsProcessorIT.java
- debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java
- debezium-embedded/src/test/java/io/debezium/processors/AbstractReselectProcessorTest.java
https://issues.redhat.com/browse/DBZ-7596
> DBZ-7596 Support reselection of PostgreSQL hstore values

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/BaseChangeRecordEmitter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerChangeRecordEmitter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/olr/OpenLogReplicatorChangeRecordEmitter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/util/TimestampUtils.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OraclePrimaryKeyLobReselectIT.java
https://issues.redhat.com/browse/DBZ-7458
> DBZ-7458 Fix PK change LOB re-query with converted values

- debezium-testing/debezium-testing-system/pom.xml
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/OpenShiftUtils.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/WaitConditions.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/ConnectorConfigBuilder.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/OcpKafkaConnectController.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/OcpKafkaConnectDeployer.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/OcpKafkaController.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/OcpKafkaDeployer.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/builders/FabricKafkaBuilder.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/builders/FabricKafkaConnectBuilder.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/connectors/CustomResourceConnectorDeployer.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/registry/OcpApicurioController.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/registry/builders/FabricApicurioBuilder.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/listeners/NamespacePreparationListener.java
https://issues.redhat.com/browse/DBZ-7630
> DBZ-7630 Bump up system test dependencies

- debezium-connector-mysql/pom.xml
- debezium-testing/debezium-testing-testcontainers/pom.xml
https://issues.redhat.com/browse/DBZ-7665
> DBZ-7665 Exclude jcl-over-slf4j dependency

- pom.xml
https://issues.redhat.com/browse/DBZ-7662
> DBZ-7662 Update Debezium Server to Quarkus 3.2.11.Final

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbChangeEventSourceFactory.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/MongoDbConnection.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbSnapshotterServiceProvider.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/query/SelectAllSnapshotQuery.java
- debezium-connector-mongodb/src/main/resources/META-INF/services/io.debezium.snapshot.spi.SnapshotQuery
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/CustomTestSnapshot.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
- debezium-connector-mongodb/src/test/resources/META-INF/services/io.debezium.spi.snapshot.Snapshotter
closes: https://issues.redhat.com/browse/DBZ-7304
> DBZ-7304 Align snapshot modes for MongoDb connector

- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/mysql.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
related to: https://github.com/debezium/debezium/pull/5371
> DBZ-7304 Update MongoDb doc for snapshot modes alignment

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/strategy/AbstractHistoryRecordComparator.java
https://issues.redhat.com/browse/DBZ-7690
> DBZ-7690 Fix history comparisons for SERVER_ID_KEY and TIMESTAMP_KEY

- debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java
https://issues.redhat.com/browse/DBZ-7437
@obabec this fixes the 2.5 test suite failures we discussed.
> Backport DBZ-7437 to 2.5

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/IncrementalSnapshotWithRecompileIT.java
- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
- debezium-embedded/src/main/java/io/debezium/engine/source/DebeziumSourceConnectorContext.java
- debezium-embedded/src/main/java/io/debezium/engine/source/EngineSourceConnectorContext.java
https://issues.redhat.com/browse/DBZ-7661
> Alwyas shut down records processing thread pool and offset store

- debezium-testing/debezium-testing-system/pom.xml
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/artifacts/OcpArtifactServerDeployer.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/KafkaController.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/OcpKafkaController.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/builders/FabricKafkaConnectBuilder.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/assertions/JdbcAssertions.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/fixtures/connectors/JdbcSinkConnector.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/fixtures/databases/ocp/OcpMySql.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/resources/ConnectorFactories.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/jdbc/sink/JdbcSinkTests.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/jdbc/sink/OcpJdbcSinkConnectorIT.java
https://issues.redhat.com/browse/DBZ-7592
> DBZ-7592 Add OCP JDBC sink system tests

- debezium-testing/debezium-testing-system/pom.xml
https://issues.redhat.com/browse/DBZ-7708
> DBZ-7708 Exclude Jackson from connect-runtime

- debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtAndConvertConsumerProcessor.java
- debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtConsumerProcessor.java
https://issues.redhat.com/browse/DBZ-7710
> DBZ-7710 Remove unneded copying from RecordProcessors

- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbContainer.java
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbReplicaSet.java
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbShardedCluster.java
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/util/DockerUtils.java
https://issues.redhat.com/browse/DBZ-7711
> DBZ-7711 Adjust fakeDNS startup conditional for Max OS

- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/mysql.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
related to: https://github.com/debezium/debezium/pull/5422
> DBZ-7497 Document configuration based snapshot mode

- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/databases/mysql/OcpMySqlDeployer.java
https://issues.redhat.com/browse/DBZ-7714
Merge after https://github.com/debezium/debezium/pull/5431
> DBZ-7714 Fix Pesistent volume claim reusage between Mysql deployments

- documentation/modules/ROOT/pages/connectors/informix.adoc
related to: https://github.com/debezium/debezium-connector-informix/pull/36
> DBZ-7699 Document new snapshot modes for Informix connector

- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/assertions/JdbcAssertions.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/jdbc/sink/JdbcSinkTests.java
https://issues.redhat.com/browse/DBZ-7726
> DBZ-7726 Increase stability of JDBC sink system tests

- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/ConnectorConfigBuilder.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/assertions/AvroKafkaAssertions.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/assertions/KafkaAssertions.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/assertions/PlainKafkaAssertions.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/db2/Db2Tests.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/mongodb/MongoTests.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/mysql/MySqlTests.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/oracle/OracleTests.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/postgresql/PostgreSqlTests.java
- debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/tests/sqlserver/SqlServerTests.java
https://issues.redhat.com/browse/DBZ-7731
> DBZ-7731 Fix mongodb extract SMT systemtest

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
https://issues.redhat.com/browse/DBZ-7737
> DBZ-7737 Column CON_ID is missing in view V$THREAD in Oracle 11

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/BlockingSnapshotIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/BlockingSnapshotIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/BlockingSnapshotIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/BlockingSnapshotIT.java
- debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java
- debezium-embedded/src/test/java/io/debezium/pipeline/AbstractBlockingSnapshotTest.java
closes: https://issues.redhat.com/browse/DBZ-7718
> DBZ-7718 Support table name escaping in data collection to be snapshotted

- debezium-testing/debezium-testing-system/pom.xml
https://issues.redhat.com/browse/DBZ-7748
> DBZ-7748 Exclude logger from connect-api

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnector.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/MongoDbConnectionContext.java
https://issues.redhat.com/browse/DBZ-7744
> DBZ-7744 RS name is not required when cluster type is not REPLICA_SET

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/query/SelectAllSnapshotQuery.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/snapshot/lock/DefaultSnapshotLock.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/snapshot/lock/ExtendedSnapshotLock.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/snapshot/lock/MinimalPerconaSnapshotLock.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/snapshot/lock/MinimalSnapshotLock.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/snapshot/lock/NoneSnapshotLock.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/snapshot/query/SelectAllSnapshotQuery.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/snapshot/lock/NoSnapshotLock.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/snapshot/lock/SharedSnapshotLock.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/snapshot/query/SelectAllSnapshotQuery.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/lock/NoSnapshotLock.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/lock/SharedSnapshotLock.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/query/SelectAllSnapshotQuery.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/snapshot/lock/ExclusiveSnapshotLock.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/snapshot/lock/NoSnapshotLock.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/snapshot/query/SelectAllSnapshotQuery.java
- debezium-core/src/main/java/io/debezium/annotation/ConnectorSpecific.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/snapshot/AbstractSnapshotProvider.java
- debezium-core/src/main/java/io/debezium/snapshot/SnapshotLockProvider.java
- debezium-core/src/main/java/io/debezium/snapshot/SnapshotQueryProvider.java
- debezium-core/src/test/java/io/debezium/snapshot/SnapshotLockProviderTest.java
- debezium-core/src/test/java/io/debezium/snapshot/SnapshotQueryProviderTest.java
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/PostgresTestResourceLifecycleManager.java
closes: https://issues.redhat.com/browse/DBZ-7732
> DBZ-7732 Add ConnectorSpecific annotation to manage multiple SPI connector specific implementation

- debezium-testing/debezium-testing-system/src/test/resources/docker/testsuite.sh
https://issues.redhat.com/browse/DBZ-7747
> DBZ-7747 Add parallel maven build to testsuite pod

- documentation/modules/ROOT/pages/connectors/mongodb.adoc
(cherry picked from commit 3d5ea663bc3c5e86bdfe28191228447e0feacabd)
If the MR in `main` is approved, I'll merge this and then update the downstream doc to reflect the change.
> DBZ-6116 Rewrite to comply with style guidelines

- debezium-bom/pom.xml
- debezium-connector-oracle/pom.xml
https://issues.redhat.com/browse/DBZ-7761
> DBZ-7761 Add `orai18n.jar` to improve Oracle NLS character set support

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/strategy/AbstractConnectorConnection.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-core/src/main/java/io/debezium/function/LogPositionValidator.java
closes: https://issues.redhat.com/browse/DBZ-7765
> DBZ-7765: Use different query for validating log position for SQLServer

- pom.xml
https://issues.redhat.com/browse/DBZ-7662
> DBZ-7662 Upgrade Quarkus Outbox to Quarkus 3.9.2

- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEngineConfig.java
- documentation/modules/ROOT/pages/development/engine.adoc
and use cached thread pool as the default.
https://issues.redhat.com/browse/DBZ-7763
https://issues.redhat.com/browse/DBZ-7764
> DBZ-7763 Remove record processing thread cap

- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java
- debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
closes: https://issues.redhat.com/browse/DBZ-7716
> DBZ-7716 Correct IncrementalSnapshotContext dataCollectionsToSnapshot cache update

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/MongoDbConnection.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
https://issues.redhat.com/browse/DBZ-7770
> DBZ-7770 Fixed MongoDb resume token validation

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/events/BufferingChangeStreamCursor.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
closes https://issues.redhat.com/browse/DBZ-7759
> DBZ-7759 Ensure error handling of oversized events swallowed by BufferedChangeStreamCursor thread

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/events/BufferingChangeStreamCursor.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
Refines https://github.com/debezium/debezium/pull/5475/
> DBZ-7759 Await fetcher thread shutdown 

- documentation/modules/ROOT/pages/connectors/mysql.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-7762
> DBZ-7762 Document connector-specific custom converters

- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-core/src/test/java/io/debezium/connector/common/BaseSourceTaskSnapshotModesValidationTest.java
closes: https://issues.redhat.com/browse/DBZ-7780
> DBZ-7780 NO_DATA snapshot mode validation throw DebeziumException on restarts if snapshot is not completed

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FiltersRestrictedIT.java
https://issues.redhat.com/browse/DBZ-7485
> DBZ-7485 Refine testing for database and collection filters in MongoDb

- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/informix.adoc
- documentation/modules/ROOT/pages/connectors/mysql.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
related to: https://github.com/debezium/debezium/pull/5483
> DBZ-7616 Document `database.query.timeout.ms` property

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotChangeEventSource.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotContext.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/IncrementalSnapshotIT.java
closes https://issues.redhat.com/browse/DBZ-7138
> DBZ-7138 Additional Conditions for MongoDb Incremental Snapshot

- documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-nosql.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot.adoc
https://issues.redhat.com/browse/DBZ-7138
> DBZ-7138 Documentation for additional-conditions for MongoDb incremental snapshot

- documentation/modules/ROOT/pages/transformations/mongodb-event-flattening.adoc
Document https://github.com/debezium/debezium/pull/5416
> DBZ-7695 document adding _id field to tombstone rewrite events, for delete events

- COPYRIGHT.txt
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- jenkins-jobs/scripts/config/Aliases.txt
https://issues.redhat.com/browse/DBZ-7820
> DBZ-7820 Adding documentation for Postgres custom data type converters

- documentation/modules/ROOT/pages/connectors/jdbc.adoc
https://issues.redhat.com/browse/DBZ-7822
> DBZ-7822 Add JDBC connection idle timeouts

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
https://issues.redhat.com/browse/DBZ-7833
> DBZ-7833 Move undocumented option to internal namespace

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/logwriter/CommitLogWriterFlushStrategy.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/FlushStrategyIT.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-7819
> DBZ-7819 Allow `log.mining.flush.table.name` to optionally include schema

- pom.xml
https://issues.redhat.com/browse/DBZ-7842
> DBZ-7842 Bump Quarkus to 3.10.0 for Outbox Extension

- debezium-connector-mariadb/src/main/resources/META-INF/services/org.apache.kafka.connect.rest.ConnectRestExtension
- debezium-connector-mariadb/src/test/java/io/debezium/connector/mariadb/rest/DebeziumMariaDbConnectorResourceIT.java
- debezium-connector-mariadb/src/test/java/io/debezium/connector/mariadb/rest/DebeziumMariaDbConnectorResourceNoDatabaseIT.java
- debezium-connector-mariadb/src/test/resources/Dockerfile.rest.test
- debezium-testing/debezium-testing-testcontainers/pom.xml
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/ConnectorResolver.java
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/testhelper/RestExtensionTestInfrastructure.java
https://issues.redhat.com/browse/DBZ-7785
Depends on https://github.com/debezium/container-images/pull/372
> DBZ-7785 Add MariaDB REST extension tests

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSourceInfoStructMaker.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SourceInfoTest.java
https://issues.redhat.com/browse/DBZ-4332
> DBZ-4332 Add `row_id` to Oracle event's source info block

- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-4332
Sibling PR for https://github.com/debezium/debezium/pull/5524
> DBZ-4332 Update documentation about `row_id`

- documentation/modules/ROOT/pages/connectors/spanner.adoc
- documentation/modules/ROOT/pages/connectors/vitess.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc
https://issues.redhat.com/browse/DBZ-7844
> DBZ-7844 Fix typos

- jenkins-jobs/pipelines/release/release-pipeline.groovy
https://issues.redhat.com/browse/DBZ-7827
> DBZ-7827 Replace all version definitions in server

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
- debezium-core/src/main/java/io/debezium/pipeline/source/SnapshottingTask.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/SnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
closes: https://issues.redhat.com/browse/DBZ-7828
> DBZ-7828 Correct filter query in snapshot task to handle SQLServer table quote

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
- pom.xml
https://issues.redhat.com/browse/DBZ-7847
> DBZ-7847 Support in query filter mode with 1000+ tables

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
https://issues.redhat.com/browse/DBZ-7790
@leoloel added this as I couldn't push to your original PR.
This supersedes PR #5493
> DBZ-7790 Improve LOB merge when table is keyless

- pom.xml
https://issues.redhat.com/browse/DBZ-7841
> DBZ-7841 Rollback to Quarkus 3.2.12

- pom.xml
https://issues.redhat.com/browse/DBZ-7863
Should pass after https://github.com/debezium/debezium/pull/5552 is merged
> DBZ-7863 Enforce Java 11 bytecode

- debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java
- debezium-embedded/src/test/java/io/debezium/pipeline/notification/AbstractNotificationsIT.java
closes: https://issues.redhat.com/browse/DBZ-7858
> DBZ-7858 Initial snapshot completed/aborted notifications will the correct offset

- COPYRIGHT.txt
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
- jenkins-jobs/scripts/config/Aliases.txt
https://issues.redhat.com/browse/DBZ-7881
DDL parser failed to parse MySQL 8 create trigger statement with "if not exists" keywords.
> DBZ-7881 DDL parse error in MySQL create trigger if not exists statement

- COPYRIGHT.txt
- jenkins-jobs/scripts/config/Aliases.txt
https://issues.redhat.com/browse/DBZ-7874
> DBZ-7874 Add contributor

- COPYRIGHT.txt
- debezium-core/src/main/java/io/debezium/serde/json/JsonSerde.java
Resolves https://issues.redhat.com/browse/DBZ-7887
> DBZ-7887 added additional JsonSerde constructor

- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedIncrementalSnapshotChangeEventSource.java
closes: https://issues.redhat.com/browse/DBZ-7886
> DBZ-7886 Skip current data collection snapshot when SQLException occurs

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
https://issues.redhat.com/browse/DBZ-7882
> DBZ-7882 Apply `decimal.handling.mode` to 0-scale numeric values

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsSnapshotProducerIT.java
related to: https://issues.redhat.com/browse/DBZ-7878
> DBZ-7878 Add test for GIS types during snapshot

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/pipeline/spi/SnapshotResult.java
- debezium-core/src/test/java/io/debezium/pipeline/ChangeEventSourceCoordinatorTest.java
Addresses: https://issues.redhat.com/browse/DBZ-7902
> DBZ-7902 Add configurable delay after snapshotting, before starting streaming

- COPYRIGHT.txt
- documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc
- jenkins-jobs/scripts/config/Aliases.txt
address : https://issues.redhat.com/browse/DBZ-7912
> DBZ-7912 Add content to the docs - 'Metrics'

- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/informix.adoc
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/mysql.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Ref: https://github.com/debezium/debezium/pull/5589
> DBZ-7902: Added Docs changes for streaming.delay.ms

- documentation/modules/ROOT/pages/connectors/db2.adoc
Documentation for https://github.com/debezium/debezium-connector-db2/pull/154
> DBZ-4812 Add Db2 platform related config

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
https://issues.redhat.com/browse/DBZ-7936
> DBZ-7936 Fix test by removing earlier validation

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeTablePointer.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerDefaultValueConverter.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/AbstractSqlServerDatatypesTest.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/DatatypesFromStreamingIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectionIT.java
https://issues.redhat.com/browse/DBZ-7933
> DBZ-7933 Fix TIME precision for micro/nano -seconds

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/olr/OpenLogReplicatorStreamingChangeEventSource.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-7823
> DBZ-7823 Add serialization for ROW_ID for OpenLogReplicator

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
https://issues.redhat.com/browse/DBZ-7801
> DBZ-7801 Add SQL Server `heartbeat.action.query` support

- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-7640
> DBZ-7640 Guard row calculation with logger `BinlogRowEstimateLogger`

- debezium-connector-postgres/pom.xml
https://issues.redhat.com/browse/DBZ-7128
> DBZ-7128 Move to PostgreSQL 12 as baseline

- debezium-core/src/main/java/io/debezium/relational/mapping/TruncateColumn.java
- debezium-core/src/test/java/io/debezium/relational/mapping/TruncateColumnTest.java
https://issues.redhat.com/browse/DBZ-7079
> DBZ-7079 Support 0 length byte buffer / string column truncation

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/AbstractStreamingAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-7831
> DBZ-7831 Allow streaming from tables with single-quotes in name

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PgSnapshot.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeEventSourceFactory.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresOffsetContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresReadOnlyIncrementalSnapshotChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresReadOnlyIncrementalSnapshotContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PgSnapshotTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/ReadOnlyIncrementalSnapshotIT.java
- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
- debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
- debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractSnapshotTest.java
closes: https://issues.redhat.com/browse/DBZ-7917
> DBZ-7917: Read-only incremental snapshots for PostgreSQL

- .github/actions/build-debezium-jdbc/action.yml
- .github/workflows/debezium-workflow-pr.yml
https://issues.redhat.com/browse/DBZ-7948
> DBZ-7948 Run JDBC sink integration tests on connector changes

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSignalBasedIncrementalSnapshotChangeEventSource.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleTableIdParser.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleTableIdParserTest.java
https://issues.redhat.com/browse/DBZ-7942
> DBZ-7942 Address parsing signal tables with special characters

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-7944
> DBZ-7944 Exclude signal table from data snapshot

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/ReadOnlyIncrementalSnapshotIT.java
- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
Follow up of : https://github.com/debezium/debezium/pull/5611
> DBZ-7917: Document PostgreSQL read-only incremental snapshot.

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnector.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ServerInfo.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresConnectionIT.java
closes: https://issues.redhat.com/browse/DBZ-7947
> DBZ-7947 Check for read-only mode incompatibility

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbOffsetContext.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/ResumeTokens.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/SourceInfo.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorDatabaseRestrictedIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java
https://issues.redhat.com/browse/DBZ-6522
> DBZ-6522 Resume token handling for documents with complex ids

- pom.xml
https://issues.redhat.com/browse/DBZ-7961
> DBZ-7961 Bump Quarkus Outbox Extension to Quarkus 3.12.0

- documentation/modules/ROOT/pages/connectors/vitess.adoc
- documentation/modules/ROOT/pages/transformations/index.adoc
- documentation/modules/ROOT/pages/transformations/vitess-filter-transaction-topic-records.adoc
- documentation/modules/ROOT/pages/transformations/vitess-remove-field.adoc
- documentation/modules/ROOT/pages/transformations/vitess-use-local-vgtid.adoc
We added some vitess-specific SMTs so add docs for them
Relevant PR https://github.com/debezium/debezium-connector-vitess/pull/194
> DBZ-6721 Add docs for SMTs

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
- debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-7967
> DBZ-7967 Fix Oracle MONITORING/NOMONITORING clause on CREATE TABLE

- debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
https://issues.redhat.com/browse/DBZ-7976
> DBZ-7976 Mark EmbeddedEngine as deprecated

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoUtils.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/connection/MongoDbConnection.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorCollectionRestrictedIT.java
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
https://issues.redhat.com/browse/DBZ-7760
> DBZ-7760 MongoDb collection scoped streaming

- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumKafkaContainer.java
- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java
- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/DebeziumContainerTest.java
https://issues.redhat.com/browse/DBZ-7986
> DBZ-7986 Fix testcontainers Kafka container

- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
https://issues.redhat.com/browse/DBZ-7988
> DBZ-7988 Guard for connector without coordinator

- .github/actions/setup-java/action.yml
- debezium-parent/pom.xml
- pom.xml
https://issues.redhat.com/browse/DBZ-7224
Related PRs
* https://github.com/debezium/debezium-connector-cassandra/pull/131
* https://github.com/debezium/debezium-connector-db2/pull/156
* https://github.com/debezium/debezium-connector-ibmi/pull/20
* https://github.com/debezium/debezium-connector-informix/pull/56
* https://github.com/debezium/debezium-connector-jdbc/pull/86
* https://github.com/debezium/debezium-connector-spanner/pull/89
* https://github.com/debezium/debezium-connector-vitess/pull/201
* https://github.com/debezium/debezium-server/pull/102
* https://github.com/debezium/debezium-operator/pull/61
> DBZ-7224 Use Java 17 as baseline

- pom.xml
https://issues.redhat.com/browse/DBZ-7224
Follows on https://github.com/debezium/debezium/pull/5654
> DBZ-7224 Use JDK 21 as specific target for Server, Operator, Outbox

- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
Quick PR to fix a Typo in the logs
> Typo in AsyncEmbeddedEngine

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
Fixes https://issues.redhat.com/browse/DBZ-8023
> DBZ-8023 check PDB field against both null and blank

- .github/workflows/debezium-workflow-pr.yml
- .github/workflows/debezium-workflow-push.yml
- debezium-connector-postgres/pom.xml
https://issues.redhat.com/browse/DBZ-8062
> DBZ-8062 Upgrade postgres server version to 15

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorConfigTest.java
- debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
- debezium-core/src/main/java/io/debezium/pipeline/signal/SignalRecord.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/DeleteWindowCloser.java
closes: https://issues.redhat.com/browse/DBZ-8011
> DBZ-8011 CloseWindow signal with INSERT_DELETE strategy will be processed through the event dispatcher

- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java
- debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
closes: https://issues.redhat.com/browse/DBZ-8050
> DBZ-8050 Skip data collection names that fails to be parsed as TableId

- jenkins-jobs/pipelines/release/release-pipeline.groovy
https://issues.redhat.com/browse/DBZ-8041
> DBZ-8041 Updated k8s manifests and examples with dev version at the end of release process

- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
closes: https://issues.redhat.com/browse/DBZ-8058
> DBZ-8058 Connection will be validated and re-connect if not valid

- COPYRIGHT.txt
- documentation/modules/ROOT/pages/development/engine.adoc
- jenkins-jobs/scripts/config/Aliases.txt
Use correct class instance JsonChangeConsumer in .notifiy in example code sinpshot Advanced Record Consuming  using Json data structure
> [docs] : Update Advanced Record Consuming

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mariadb/generated/MariaDBParser.g4
- debezium-ddl-parser/src/test/resources/mariadb/examples/fast/ddl_create.sql
https://issues.redhat.com/browse/DBZ-8066
> DBZ-8066 Support RENAME TABLE IF EXISTS

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-8070
> DBZ-8070 Change some log entries to debug level

- pom.xml
https://issues.redhat.com/browse/DBZ-8010
> DBZ-8010 Bump Infinispan to 14.0.29.Final

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresShutdownIT.java
https://issues.redhat.com/browse/DBZ-8075
> DBZ-8075 Speed-up PostgresShutdownIT test

- documentation/modules/ROOT/pages/connectors/jdbc.adoc
related to: https://github.com/debezium/debezium-connector-jdbc/pull/89
> DBZ-8018 Add note to JDBC documentation about the primary.key.fields

- documentation/modules/ROOT/pages/connectors/oracle.adoc
Fixes subject-verb agreement in content added in DBZ-7895.
> [docs] Fix typo in standby database topic

- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/jdbc/BinlogValueConverters.java
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogBinaryModeIT.java
https://issues.redhat.com/browse/DBZ-8076
> DBZ-8076 Support capturing BLOB during snapshots

- documentation/modules/ROOT/pages/connectors/oracle.adoc
(cherry picked from commit 8ff152d91cfa0f5cbc88de056a776628ddf63f2d)
Follow-up to DBZ-7895
Adds titles and implements further wording changes to improve scannability and clarity.
> [docs] Update standby database topic for clarity

- documentation/modules/ROOT/pages/connectors/vitess.adoc
Adding docs for the config here https://github.com/debezium/debezium-connector-vitess/pull/203
> DBZ-8069 Add docs on override data change topic prefix config

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/events/BufferingChangeStreamCursor.java
https://issues.redhat.com/browse/DBZ-8022
> DBZ-8022 Handle pause/resume polling for buffer changestreams cursor

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java
https://issues.redhat.com/browse/DBZ-8089
> DBZ-8089 Reset column scale on MODIFY ddl statements

- COPYRIGHT.txt
- documentation/modules/ROOT/pages/configuration/signalling.adoc
- jenkins-jobs/scripts/config/Aliases.txt
> [docs] Update signalling.adoc

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
A follow-up on https://github.com/debezium/debezium/pull/5704
> [docs] Add `driver.*` namespace pass-through section for PostgreSQL

- LICENSE-3rd-PARTIES.txt
https://issues.redhat/browse/DBZ-8099
> DBZ-8099 Add MariaDB Connector/J License

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-3656
> DBZ-3656 Use `online_catalog` as default strategy

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-8102
> DBZ-8102 Make ORA-26928 "Unable to communicate with XStream apply coordinator process" retriable

- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/shared-mariadb-mysql.adoc
https://issues.redhat.com/browse/DBZ-8104
> DBZ-8104 Fix converters documentation examples

- debezium-bom/pom.xml
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorTask.java
- debezium-core/src/test/java/io/debezium/kafka/KafkaClusterTest.java
- debezium-core/src/test/java/io/debezium/kafka/KafkaServer.java
- pom.xml
https://issues.redhat.com/browse/DBZ-8105
> DBZ-8105 Upgrade Kafka to 3.8.0

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/transforms/timescaledb/TimescaleDbDatabaseTest.java
https://issues.redhat.com/browse/DBZ-8123
> DBZ-8123 Process compression notification messages

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchemaFactory.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationMessageColumnValueResolver.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/data/vector/HalfVector.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/data/vector/SparseVector.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/data/vector/Vector.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/data/vector/Vectors.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/VectorDatabaseIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/VectorDatabaseTest.java
- debezium-connector-postgres/src/test/resources/init_pgvector.ddl
https://issues.redhat.com/browse/DBZ-8121
Tests require https://github.com/debezium/container-images/pull/390
> DBZ-8121 Support for pgvector datatypes

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
Documents https://github.com/debezium/debezium/pull/5735
> DBZ-8121 Document pgvector

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/AbstractRecordsProducerTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/CustomSnapshotterIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/LogicalDecodingMessageIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresDefaultValueConverterIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresMoneyIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresShutdownIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresSkipMessagesWithoutChangeConfigIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SignalsIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TransactionMetadataIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/transforms/timescaledb/TimescaleDbDatabaseTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/transforms/timescaledb/TimescaleDbTest.java
https://issues.redhat.com/browse/DBZ-8077
> DBZ-8077 Migrate Postgres testsuite to async engine

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/ReplicationConnectionIT.java
Addressing: https://issues.redhat.com/browse/DBZ-8073
> DBZ-8073: Added timeout for replication slot creation command

- debezium-core/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java
https://issues.redhat.com/browse/DBZ-8113
> DBZ-8113 Preserve source info during emitting PK change

- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogConvertingFailureIT.java
https://issues.redhat.com/browse/DBZ-8128
> DBZ-8128 Don't stop engine twice

- .github/workflows/debezium-workflow-pr.yml
- COPYRIGHT.txt
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java
- jenkins-jobs/scripts/config/Aliases.txt
Fixes [DBZ-8130](https://issues.redhat.com/browse/DBZ-8130)
> DBZ-8130 Preserve ordering of tables inside batch

- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogConnectorConfig.java
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogConnectorIT.java
https://issues.redhat.com/browse/DBZ-8134
> DBZ-8134 Fix parsing of server ID

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/converters/PostgresCloudEventsMaker.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
closes: https://issues.redhat.com/browse/DBZ-7601
> DBZ-7601 Fix NPE when converting incremental snapshot events to cloud events

- documentation/modules/ROOT/pages/transformations/decode-logical-decoding-message-content.adoc
[DBZ-8103](https://issues.redhat.com/browse/DBZ-8103)
Edit property description
> DBZ-8103 Edit property description

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/AbstractProcessorTest.java
- debezium-connector-oracle/src/test/resources/logback-test.xml
https://issues.redhat.com/browse/DBZ-8044
> DBZ-8044 Add abandoned transaction details to log

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
https://issues.redhat.com/browse/DBZ-8125
> DBZ-8125 Make ORA-00600 errors related to `krvrdGetUID` retriable

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-8143
> DBZ-8143 Add LogMiner start mining session retry attempt counter to logs

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/logwriter/CommitLogWriterFlushStrategy.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/logwriter/RacCommitLogWriterFlushStrategy.java
https://issues.redhat.com/browse/DBZ-8149
> DBZ-8149 Rework RAC flush connections to be elastic

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFileCollector.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogFileCollectorTest.java
https://issues.redhat.com/browse/DBZ-8144
> DBZ-8144 Check open redo thread has log with read scn

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
https://issues.redhat.com/browse/DBZ-8148
> DBZ-8148 Reduce XStream logging verbosity

- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogOffsetContext.java
https://issues.redhat.com/browse/DBZ-8140
> DBZ-8140 Validate log position method missing gtid info from SourceInfo

- pom.xml
https://issues.redhat.com/browse/DBZ-8145
> DBZ-8145 Bump apicurio-registry to 2.6.2.Final

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/sink/SinkConnectorIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/sink/SinkConnectorReplicaSetIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/sink/SinkConnectorShardedClusterIT.java
- debezium-core/src/test/java/io/debezium/junit/AnnotationBasedTestRule.java
- debezium-core/src/test/java/io/debezium/junit/RequiresAssemblyProfile.java
- debezium-core/src/test/java/io/debezium/junit/RequiresAssemblyProfileTestRule.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/testhelper/TestInfrastructureHelper.java
closes https://issues.redhat.com/browse/DBZ-8138
> DBZ-8138 Re-add check if assembly profile is active as JUnit annotation

- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorConfig.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/JdbcSinkConnectorConfigTest.java
https://issues.redhat.com/browse/DBZ-8151
> DBZ-8151 Allow `record_value` with no `primary.key.fields`

- debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
- debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractSnapshotTest.java
- debezium-embedded/src/test/java/io/debezium/transforms/outbox/AbstractEventRouterTest.java
- documentation/modules/ROOT/pages/connectors/informix.adoc
> Back porting adaptions for Informix integration tests (DBZ-8114)

- debezium-api/src/main/java/io/debezium/engine/DebeziumEngine.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SignalsIT.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-core/src/main/java/io/debezium/pipeline/signal/channels/process/InProcessSignalChannel.java
- debezium-core/src/main/java/io/debezium/pipeline/signal/channels/process/SignalChannelWriter.java
- debezium-core/src/main/resources/META-INF/services/io.debezium.pipeline.signal.channels.SignalChannelReader
- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEngineSignaler.java
- debezium-embedded/src/main/java/io/debezium/engine/source/EngineSourceTask.java
- debezium-embedded/src/test/java/io/debezium/embedded/async/AbstractAsyncEngineConnectorTest.java
https://issues.redhat.com/browse/DBZ-8135
I tried to be as non-invasive towards the public API as possible.
> DBZ-8135 In process signalling for Debezium Engine

- debezium-quarkus-outbox-common/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/DebeziumOutboxCommonConfig.java
- debezium-quarkus-outbox-common/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/OutboxEventHbmWriter.java
- debezium-quarkus-outbox-common/runtime/src/main/java/io/debezium/outbox/quarkus/internal/DebeziumOutboxCommonRuntimeConfig.java
- debezium-quarkus-outbox-reactive/deployment/src/main/java/io/debezium/outbox/reactive/quarkus/deployment/DebeziumOutboxConfig.java
- debezium-quarkus-outbox-reactive/deployment/src/main/java/io/debezium/outbox/reactive/quarkus/deployment/OutboxProcessor.java
- debezium-quarkus-outbox-reactive/runtime/src/main/java/io/debezium/outbox/reactive/quarkus/internal/AbstractEventDispatcher.java
- debezium-quarkus-outbox-reactive/runtime/src/main/java/io/debezium/outbox/reactive/quarkus/internal/DebeziumOutboxRuntimeConfig.java
- debezium-quarkus-outbox/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/DebeziumOutboxConfig.java
- debezium-quarkus-outbox/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/OutboxProcessor.java
- debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/AbstractEventDispatcher.java
- debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/DebeziumOutboxRuntimeConfig.java
- pom.xml
https://issues.redhat.com/browse/DBZ-8164
> DBZ-8164 Upgrade Outbox Extension to Quarkus 3.14.0

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFileCollector.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogFileCollectorTest.java
https://issues.redhat.com/browse/DBZ-8162
> DBZ-8162 Fix open redo log consistency with reopening nodes

- COPYRIGHT.txt
- documentation/modules/ROOT/pages/operations/debezium-server.adoc
- jenkins-jobs/scripts/config/Aliases.txt
This PR also includes documentation for the JWT authentication method introduced by [DBZ-7829](https://issues.redhat.com/browse/DBZ-7829).
> DBZ-7876 Improve NATS Jetstream sink properties for authentication

- documentation/modules/ROOT/pages/operations/debezium-server.adoc
`debezium.sink.kafka.wait.message.delivery.timeout.ms`
Documentation for https://github.com/debezium/debezium-server/pull/116
> DBZ-7575 Document the new property of Kafka sink 

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SignalsIT.java
- debezium-core/src/main/java/io/debezium/pipeline/JmxUtils.java
- debezium-embedded/src/test/java/io/debezium/pipeline/notification/AbstractNotificationsIT.java
closes: https://issues.redhat.com/browse/DBZ-8137
> DBZ-8137 Fix JMX signal and notification channel for multiple tasks connectors

- documentation/modules/ROOT/pages/operations/debezium-server.adoc
https://issues.redhat.com/browse/DBZ-8133
> DBZ-8133 Add async engine options also to Debezium server documentation

- .github/actions/build-debezium-mysql/action.yml
- .github/workflows/debezium-workflow-pr.yml
- .github/workflows/debezium-workflow-push.yml
- debezium-bom/pom.xml
- debezium-connector-binlog/pom.xml
- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogReadOnlyIncrementalSnapshotChangeEventSource.java
- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/jdbc/BinlogConnectorConnection.java
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogConnectorIT.java
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/util/BinlogTestConnection.java
- debezium-connector-mariadb/src/main/java/io/debezium/connector/mariadb/MariaDbSnapshotChangeEventSource.java
- debezium-connector-mysql/pom.xml
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/jdbc/MySqlConnection.java
- debezium-connector-mysql/src/test/docker/server-gtids/my.cnf
- debezium-connector-mysql/src/test/docker/server-replica/my.cnf
- debezium-connector-mysql/src/test/docker/server-ssl/my.cnf
- debezium-connector-mysql/src/test/docker/server/my.cnf
- pom.xml
https://issues.redhat.com/browse/DBZ-7838
> DBZ-7838 Support for MySQL 8.4

- debezium-connector-oracle/pom.xml
https://issues.redhat.com/browse/DBZ-8178
> DBZ-8178 Fix Ehcache JAXB dependencies

- .github/workflows/debezium-workflow-pr.yml
- .github/workflows/debezium-workflow-push.yml
- debezium-connector-mysql/src/test/docker/server-gtids/my.cnf
- debezium-connector-mysql/src/test/docker/server-replica/my.cnf
- debezium-connector-mysql/src/test/docker/server-ssl/my.cnf
- debezium-connector-mysql/src/test/docker/server/my.cnf
- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTestConnection.java
https://issues.redhat.com/browse/DBZ-8030
Built on top of https://github.com/debezium/debezium/pull/5765
> DBZ-8030 Add support for MySQL 9

- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogBlockingSnapshotIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/BlockingSnapshotIT.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
- debezium-embedded/src/test/java/io/debezium/embedded/TestingEmbeddedEngine.java
- debezium-embedded/src/test/java/io/debezium/embedded/async/AbstractAsyncEngineConnectorTest.java
- debezium-embedded/src/test/java/io/debezium/embedded/async/AsyncEmbeddedEngineTest.java
- debezium-embedded/src/test/java/io/debezium/embedded/async/TestingAsyncEmbeddedEngine.java
- debezium-embedded/src/test/java/io/debezium/pipeline/AbstractBlockingSnapshotTest.java
https://issues.redhat.com/browse/DBZ-8166
> Avoid using raw types in embedded engine tests

- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-8032
> DBZ-8032 Use better exception than NullPointerException

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-8188
> DBZ-8188 Use new connection on attach retries

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerStreamMetricsTest.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-8181
> DBZ-8181 Drop several deprecated Oracle configuration options

- documentation/modules/ROOT/pages/connectors/mysql.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/shared-mariadb-mysql.adoc
Documentation for https://github.com/debezium/debezium/pull/5784
> DBZ-8157 Document VECTOR type

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/LogicalDecodingMessageMonitor.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresEventDispatcher.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSchemaFactory.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/LogicalDecodingMessageIT.java
- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
https://issues.redhat.com/browse/DBZ-8185
> DBZ-8185 Add `transaction` field to change event of a logical decoding message

- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-8184
> DBZ-8184 Enable snapshot failure retries during Oracle tests

- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/AbstractProcessorTest.java
https://issues.redhat.com/browse/DBZ-8199
> DBZ-8199 Fix test to resolve database name from environment

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-8198
> DBZ-8198 Exclude Oracle vecsys tablespace from capture

- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-8187
> DBZ-8197 Increase wait time for XStream

- documentation/modules/ROOT/partials/modules/all-connectors/shared-mariadb-mysql.adoc
> [docs] Update shared-mariadb-mysql.adoc

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/olr/OpenLogReplicatorValueConverter.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-8142
> DBZ-8142 Fix conversion of `BigInteger` timestamp values

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/olr/client/OlrNetworkClient.java
https://issues.redhat.com/browse/DBZ-8201
> DBZ-8201 Reduce log verbosity on OpenLogReplicator confirmation

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-core/src/main/java/io/debezium/util/LRUCacheMap.java
https://issues.redhat.com/browse/DBZ-8071
> DBZ-8071 Improve hybrid mining performance with object-id-to-table-id cache

- documentation/modules/ROOT/partials/modules/all-connectors/ref-mariadb-mysql-rqd-connector-cfg-props.adoc
fix property name table-exclude-list to table.exclude.list
> [docs] Update ref-mariadb-mysql-rqd-connector-cfg-props.adoc

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
https://issues.redhat.com/browse/DBZ-5009
> DBZ-5009 Make ORA-00600 error `krvrdccs10` retriable

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-8208
> DBZ-8208 Extend `error.processing.failure.handling.mode` to DML parsing

- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/builders/FabricKafkaConnectBuilder.java
https://issues.redhat.com/browse/DBZ-8213
> DBZ-8213 Keep defaul KC name short not to acceed limit of 63 chars

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/grant.sql
https://issues.redhat.com/browse/DBZ-8209
[Upstream PR ](https://github.com/antlr/grammars-v4/pull/4230)
> DBZ-8209 Support for unkown roles and users in REVOKE

- debezium-connector-mariadb/pom.xml
https://issues.redhat.com/browse/DBZ-8226
> DBZ-8226 Bump MariaDB to 11.4.3

- debezium-connector-oracle/pom.xml
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/EhcacheLogMinerEventProcessor.java
- debezium-connector-oracle/src/main/resources/ehcache/configuration-template.xml
- pom.xml
https://issues.redhat.com/browse/DBZ-8219
> DBZ-8219 Fix JAXB xml parsing of Ehcache configuration

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
https://issues.redhat.com/browse/DBZ-8223
> DBZ-8223 Make ORA-00600 krvrdccs30 retriable

- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java
https://issues.redhat.com/browse/DBZ-7198
> DBZ-7198 Fix shouldConvertToAvro key failure with serialization

- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorConfig.java
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/dialect/DatabaseDialect.java
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/dialect/GeneralDatabaseDialect.java
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/dialect/mysql/MySqlDatabaseDialect.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkInsertModeTest.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/mysql/JdbcSinkRetryIT.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/junit/jupiter/JdbcConnectionProvider.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/junit/jupiter/Sink.java
- documentation/modules/ROOT/pages/connectors/jdbc.adoc
https://issues.redhat.com/browse/DBZ-7291
Port of the PR from https://github.com/debezium/debezium-connector-jdbc/pull/55 after moving the repository.
> DBZ-7291 Retry flush if failed with retriable exceptions each Dialect.

- .github/workflows/debezium-workflow-pr.yml
- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
- debezium-microbenchmark-engine/src/main/java/io/debezium/performance/engine/DebeziumEnginePerf.java
- debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java
- documentation/modules/ROOT/pages/development/engine.adoc
- documentation/modules/ROOT/pages/operations/debezium-server.adoc
* Backport of PR #5858
* Backport Apicurio fix
* Adjust GH wrokflow to checkout the same branch as one against PR was made
https://issues.redhat.com/browse/DBZ-8237
> DBZ-8237 Don't use unbounded number of processing threads in async engine

- pom.xml
https://issues.redhat.com/browse/DBZ-8246
> DBZ-8246 Bump Infinispan to 15.0.8.Final

- COPYRIGHT.txt
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-embedded/src/test/java/io/debezium/pipeline/AbstractBlockingSnapshotTest.java
- jenkins-jobs/scripts/config/Aliases.txt
https://issues.redhat.com/browse/DBZ-8238
work-in-progress: not able to run some ITs locally, need CI
> DBZ-8238 [WIP] fix streaming metrics after blocking snapshot

- .github/workflows/debezium-workflow-pr.yml
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mariadb/generated/MariaDBParser.g4
- debezium-ddl-parser/src/test/resources/mariadb/examples/fast/ddl_alter.sql
closes https://issues.redhat.com/browse/DBZ-8240 and correctly indents the rules and comments
upstream - https://github.com/antlr/grammars-v4/pull/4250
> DBZ-8240 Use ifNotExists rule for unique key constraint in Mariadb

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDefaultValueConverter.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDefaultValueIT.java
https://issues.redhat.com/browse/DBZ-8248
> DBZ-8248 Support `EMPTY_CLOB` and `EMPTY_BLOB` default values

- documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/shared-mariadb-mysql.adoc
- documentation/modules/ROOT/partials/modules/snippets/frag-db2-props-snippets.adoc
- documentation/modules/ROOT/partials/modules/snippets/frag-informix-props-snippets.adoc
- documentation/modules/ROOT/partials/modules/snippets/frag-mariadb-props-snippets.adoc
- documentation/modules/ROOT/partials/modules/snippets/frag-mysql-props-snippets.adoc
- documentation/modules/ROOT/partials/modules/snippets/frag-oracle-props-snippets.adoc
- documentation/modules/ROOT/partials/modules/snippets/frag-sqlserver-props-snippets.adoc
[DBZ-8254](https://issues.redhat.com/browse/DBZ-8254)
Applies conditionalization fixes from main to 2.7
> DBZ-8254 Cherry-pick from main to 2.7

- debezium-connector-binlog/pom.xml
https://issues.redhat.com/browse/DBZ-8263
> DBZ-8263 Common binlog code does not depend on MariaDB

- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
- debezium-embedded/src/test/java/io/debezium/pipeline/AbstractBlockingSnapshotTest.java
https://issues.redhat.com/browse/DBZ-8267
> DBZ-8267 Fix test failures

- debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-infinispan.xml
- debezium-connector-jdbc/pom.xml
https://issues.redhat.com/browse/DBZ-8261
> DBZ-8261 Allow removal of Oracle deps from package

- debezium-connector-mysql/pom.xml
https://issues.redhat.com/browse/DBZ-8258
> DBZ-8258 Override forced scope for dependency

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
- debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql
https://issues.redhat.com/browse/DBZ-8259
> DBZ-8259 Allow parallel clause in ADD CONSTRAINT clause

- LICENSE-3rd-PARTIES.txt
https://issues.redhat.com/browse/DBZ-8260
> DBZ-8260 Make Oracle NLS library provided

- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogSnapshotChangeEventSource.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/BlockingSnapshotIT.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java
- debezium-embedded/src/test/java/io/debezium/pipeline/AbstractBlockingSnapshotTest.java
closes: https://issues.redhat.com/browse/DBZ-8244
> DBZ-8244 Avoid blocking snapshot to remain in an inconsistent state in case of failure

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/UnchangedToastedPlaceholder.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresReselectColumnsProcessorIT.java
- debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java
[DBZ-8212](https://issues.redhat.com/browse/DBZ-8212)
> DBZ-8212 Add support for integer arrays

- debezium-core/src/main/java/io/debezium/pipeline/signal/actions/snapshotting/ExecuteSnapshot.java
closes: https://issues.redhat.com/browse/DBZ-8278
> DBZ-8278 Remove deprecated additional condition for incremental snapshot

- documentation/modules/ROOT/pages/development/converters.adoc
https://issues.redhat.com/browse/DBZ-7045
> DBZ-7045 Use more robust converter example

- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/testhelper/TestInfrastructureHelper.java
https://issues.redhat.com/browse/DBZ-8294
> DBZ-8294 Use connect:nightly rather than connect-base:latest

- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
- documentation/modules/ROOT/pages/post-processors/reselect-columns.adoc
- documentation/modules/ROOT/pages/transformations/mongodb-outbox-event-router.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-sql.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-sql.adoc
- documentation/modules/ROOT/partials/modules/snippets/db2-frag-signaling-fq-table-formats.adoc
- documentation/modules/ROOT/partials/modules/snippets/mariadb-frag-signaling-fq-table-formats.adoc
- documentation/modules/ROOT/partials/modules/snippets/mysql-frag-signaling-fq-table-formats.adoc
- documentation/modules/ROOT/partials/modules/snippets/oracle-frag-signaling-fq-table-formats.adoc
- documentation/modules/ROOT/partials/modules/snippets/postgresql-frag-signaling-fq-table-formats.adoc
- documentation/modules/ROOT/partials/modules/snippets/sqlserver-frag-signaling-fq-table-formats.adoc
[DBZ-8293](https://issues.redhat.com/browse/DBZ-8293)
Cherry-pick from main (#5914) to fix errors that caused formatting artifacts to render in the built documentation.
> Dbz 8293 cherry pick formatting fixes from main

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresReselectColumnsProcessorIT.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
- debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java
https://issues.redhat.com/browse/DBZ-8277
> DBZ-8277 Fix ReselectColumnsProcessor for Postgres datatypes

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/OracleDdlParser.java
https://issues.redhat.com/browse/DBZ-7040
> DBZ-7040 Fix Oracle DDL parsing to strip trailing new lines

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
https://issues.redhat.com/browse/DBZ-8304
> DBZ-8304 Fix column reselection for Oracle

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
https://issues.redhat.com/browse/DBZ-8292
Leaving this in draft until the questions on the Jira are answered, in case we need to add any additional fixes.
> DBZ-8292 Make ORA-01001 invalid cursor errors to be retried

- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/artifacts/OcpArtifactServerController.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/ConnectorConfigBuilder.java
Fix Artifacts server deployment, Remove apicurio headers
> [ci] Fix Artifacts server deployment, Remove apicurio headers

- documentation/modules/ROOT/pages/development/engine.adoc
closes: https://issues.redhat.com/browse/DBZ-8318
> DBZ-8318 Explain how to manage SPI and bundled jars for debezium engine applications

- .github/workflows/debezium-workflow-pr.yml
- .github/workflows/debezium-workflow-push.yml
- .github/workflows/jdk-outreach-workflow.yml
- debezium-connector-postgres/pom.xml
https://issues.redhat.com/browse/DBZ-8275
Depends on https://github.com/debezium/container-images/pull/400
> DBZ-8275 Add support for PostgreSQL 17

- jenkins-jobs/scripts/trigger-nightly-docker.sh
https://issues.redhat.com/browse/DBZ-8327
> DBZ-8324 Stop publishing to Docker Hub

- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/OcpKafkaConnectController.java
- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/kafka/connectors/RestPrometheusMetricReader.java
https://issues.redhat.com/browse/DBZ-8330
> DBZ-8330 Fix Prometheus REST URL

- debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/artifacts/OcpArtifactServerController.java
https://issues.redhat.com/browse/DBZ-8331
> DBZ-8331 Add jackson afterburner to classpath

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
- debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-8316
Upstream PR https://github.com/antlr/grammars-v4/pull/4287
> DBZ-8316 Support POSITION keyword as column name

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorConfig.java
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
https://issues.redhat.com/browse/DBZ-7927
> DBZ-7927 Document advanced mongodb ssl configuration

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFileCollector.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFileNotFoundException.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-8345
> DBZ-8345 Don't fault archive log only mode when SCN is unavailable

- pom.xml
https://issues.redhat.com/browse/DBZ-8194
https://issues.redhat.com/browse/DBZ-8340
> DBZ-8194 DBZ-8340 Upgrade binlog client

- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogStreamingChangeEventSource.java
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogConnectorIT.java
- debezium-core/src/test/java/io/debezium/junit/logging/LogInterceptor.java
https://issues.redhat.com/browse/DBZ-8290
> DBZ-8290 Increment binlog event counter

- documentation/modules/ROOT/pages/configuration/signalling.adoc
https://issues.redhat.com/browse/DBZ-6837
> DBZ-6837 Clarify signal data collection should be unique per connector

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-8208
> DBZ-8208 Use the Loggings utility class

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-8208
@jpechane backport to 2.7
> DBZ-8208 Extend error.processing.failure.handling.mode to DML parsing

- .github/actions/checkstyle-format/action.yml
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/junit/jupiter/e2e/source/SourcePipelineInvocationContextProvider.java
- debezium-storage/debezium-storage-jdbc/src/test/java/io/debezium/storage/jdbc/JdbcOffsetBackingStoreIT.java
- debezium-storage/debezium-storage-jdbc/src/test/java/io/debezium/storage/jdbc/history/JdbcSchemaHistoryIT.java
https://issues.redhat.com/browse/DBZ-8362
Sibling PR - https://github.com/debezium/debezium-connector-spanner/pull/98
> DBZ-8362 Use quay.io images

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/metrics/MongoDbSnapshotChangeEventSourceMetrics.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/metrics/MongoDbSnapshotChangeEventSourceMetricsMXBean.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/metrics/MongoDbStreamingChangeEventSourceMetrics.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/metrics/MongoDbStreamingChangeEventSourceMetricsMXBean.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/BlockingSnapshotIT.java
https://issues.redhat.com/browse/DBZ-8359
> DBZ-8359 Use correct MBean naming for OpenMbean remapping

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/AbstractMongoConnectorIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/AbstractShardedMongoConnectorIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/FiltersRestrictedIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorCollectionRestrictedIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/MongoDbConnectorDatabaseRestrictedIT.java
https://issues.redhat.com/browse/DBZ-8369
> DBZ-8369 Migrate MongoDB testsuite to async engine

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/AbstractSqlServerDatatypesTest.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/CaseSensitivenessIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/EventProcessingFailureHandlingIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SQLServerNumericColumnIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SchemaHistoryTopicIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotWithSelectOverridesIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SpecialCharsInNamesIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerBinaryModeIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerChangeTableSetIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorMultiPartitionModeIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerSchemaNameAdjustmentModeIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerSkipMessagesWithNoUpdateConfigIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TablesWithUniqueIndexOnlyIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TablesWithoutPrimaryKeyIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TransactionMetadataIT.java
- debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
https://issues.redhat.com/browse/DBZ-8353
> DBZ-8353 Migrate SQL server testsuite to async engine

- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/CustomSnapshotterIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBinaryModeIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDefaultValueIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleExtendedStringIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleNumberNegativeScaleIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleNumberOneIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OraclePrimaryKeyLobReselectIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleRawDataTypeIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleRawToStringIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleRowIdDataTypeIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSkipMessagesWithoutChangeConfigIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleXmlDataTypesIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SchemaHistoryTopicIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SignalsIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SnapshotSelectOverridesIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/TransactionMetadataIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/FlushStrategyIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/HybridMiningStrategyIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogFileCollectorIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerSourceInfoRedoSqlIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionCommitConsumerIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/AbstractProcessorTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/AbstractProcessorUnitTest.java
https://issues.redhat.com/browse/DBZ-8370
> DBZ-8370 Migrate Oracle testsuite to async engine

- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SnapshotIsolationIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/transforms/DecodeLogicalDecodingMessageContentTest.java
- debezium-embedded/src/test/java/io/debezium/pipeline/AbstractMetricsTest.java
- debezium-embedded/src/test/java/io/debezium/relational/history/AbstractSchemaHistoryTest.java
- debezium-embedded/src/test/java/io/debezium/transforms/outbox/AbstractEventRouterTest.java
- debezium-storage/debezium-storage-jdbc/src/test/java/io/debezium/storage/jdbc/JdbcOffsetBackingStoreIT.java
- debezium-storage/debezium-storage-jdbc/src/test/java/io/debezium/storage/jdbc/history/JdbcSchemaHistoryIT.java
https://issues.redhat.com/browse/DBZ-8375
> DBZ-8375 Migrate rest of Debezium testsuite to async engine

- documentation/antora.yml
- pom.xml
https://issues.redhat.com/browse/DBZ-8385
> DBZ-8385 Upgrade Kafka to 3.8.1

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/AbstractExtractNewDocumentStateTestIT.java
https://issues.redhat.com/browse/DBZ-8397
> DBZ-8397 Make sure connector is fully running before stopping it

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
https://issues.redhat.com/browse/DBZ-8396
> DBZ-8396 Don't stop already stopped engine

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java
https://issues.redhat.com/browse/DBZ-8399
> DBZ-8399 Insert key with null when objectIdToTableId finds no matches

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
https://issues.redhat.com/browse/DBZ-8379
> DBZ-8379 Adjust streaming NLS parameters micro/nano-second precision

- documentation/antora.yml
- pom.xml
https://issues.redhat.com/browse/DBZ-8400
> DBZ-8400 Upgrade Kafka to 3.9.0

- documentation/modules/ROOT/pages/configuration/signalling.adoc
https://issues.redhat.com/browse/DBZ-7245
> DBZ-7245 Add documentation for File Signal Channel

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetrics.java
https://issues.redhat.com/browse/DBZ-8395
> DBZ-8395 Return always positive value for OldestScnAgeInMilliseconds

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFileCollector.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogFileCollectorTest.java
https://issues.redhat.com/browse/DBZ-8389
> DBZ-8389 Avoid throwing ORA-01291 due to recent checkpoint

- pom.xml
https://issues.redhat.com/browse/DBZ-8409
> DBZ-8409 Update Quarkus Outbox Extension to Quarkus 3.16.3

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresValueConverter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/UnchangedToastedReplicationMessageColumn.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
https://issues.redhat.com/browse/DBZ-8416
> Add support for bpchar datatype

- .run/build-quick.run.xml
- .run/build-skipITs.run.xml
- .run/format-apply.run.xml
- .run/format-check.run.xml
- .run/postgres-start-docker.run.xml
Saving common IntelliJ run configurations for developer convenience. These will be shared across the dev team.
- related question: https://stackoverflow.com/a/24642246/2679740
- related guide: https://www.jetbrains.com/guide/javascript/tips/share-run-configurations/
> [docs] Add common IntelliJ run configs to git

- pom.xml
https://issues.redhat.com/browse/DBZ-8445
> DBZ-8445 Upgrade binlog client to 0.40.2

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/AbstractExtractNewDocumentStateTestIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/RecordsStreamProducerIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
https://issues.redhat.com/browse/DBZ-8461
> DBZ-8461Fix randomly failing tests related to stop of async engine

- documentation/modules/ROOT/pages/connectors/oracle.adoc
ALso replace `redo_in_catalog` with correct `redo_log_catalog` option.
> [docs] Correct the default value for log.mining.strategy

- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
Fixes issue https://issues.redhat.com/projects/DBZ/issues/DBZ-7980?filter=allopenissues
> DBZ-8433 Adds a handling event processing failure method and refactorizes in dispatchers

- .github/workflows/debezium-workflow-pr.yml
- .github/workflows/debezium-workflow-push.yml
closes https://issues.redhat.com/browse/DBZ-8451
> DBZ-8451 Support Mongo 8.0

- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogReadOnlyIncrementalSnapshotChangeEventSource.java
- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogReadOnlyIncrementalSnapshotContext.java
- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogSourceTask.java
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogSignalsIT.java
- debezium-connector-mariadb/src/main/java/io/debezium/connector/mariadb/MariaDbConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-core/src/main/java/io/debezium/pipeline/signal/channels/KafkaSignalChannel.java
- documentation/modules/ROOT/pages/configuration/signalling.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-pass-through-kafka-signals-configuration-properties.adoc
closes: https://issues.redhat.com/browse/DBZ-7856
> DBZ-7856 Remove signal offset support for KafkaSignalChannel

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
[DBZ-8455](https://issues.redhat.com/browse/DBZ-8455)
Edit property description for clarity and apply admonition formatting
> DBZ-8455 Edit property description and add admonition.

- debezium-core/src/main/java/io/debezium/connector/AbstractSourceInfoStructMaker.java
Let Connector schema snapshot field allowed values reference SnapshotRecord Enum.
> DBZ-8496 Make Connector schema snapshot field consist with SnapshotRecord Enum

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleReselectColumnsProcessorIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-8493
> DBZ-8493 Explicitly pin the bean registry JDBC connection to PDB

- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
https://issues.redhat.com/browse/DBZ-8492
> DBZ-8492 Do not log and gather attributes for views

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetrics.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetricsMXBean.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-8491
> DBZ-8491 Add metric to track partial rollback counters

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-8503
> DBZ-8503 Use LAST_REDO_CHANGE#-1 from V$THREAD for range boundaries

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerColumnResolverDmlParser.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleExtendedStringIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java
- debezium-microbenchmark-oracle/src/main/java/io/debezium/performance/connector/oracle/parser/LogMinerDmlParserPerf.java
https://issues.redhat.com/browse/DBZ-8034
https://issues.redhat.com/browse/DBZ-8200
> DBZ-8034 New internal option to relax quote handling in DML parser

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/events/EventType.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
https://issues.redhat.com/browse/DBZ-8533
> DBZ-8533 Always skip GoldenGate REPLICATION MARKER events

- .github/workflows/debezium-workflow-pr.yml
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/rest/DebeziumSqlServerConnectorResourceIT.java
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/testhelper/TestInfrastructureHelper.java
closes: https://issues.redhat.com/browse/DBZ-8531
> DBZ-8351 Fix TestInfrastructureHelper

- documentation/modules/ROOT/pages/operations/debezium-server.adoc
Same as #6060, just targeting nightly version too
> [docs] update to show correct configuration directory in nightly

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java
- pom.xml
https://issues.redhat.com/browse/DBZ-8554
> DBZ-8554 Upgrade mongo-driver to 5.2.0

- debezium-connector-postgres/pom.xml
related to: [DBZ-8564](https://issues.redhat.com/browse/DBZ-8564)
> DBZ-8564 Remove reference to dockerhub registry

- debezium-connector-mariadb/pom.xml
> DBZ-8564 Don't use dockerhub for pulling MariDB images

- debezium-connector-mysql/pom.xml
- pom.xml
> DBZ-8564 Don't use dockerhub in MySQL module

- debezium-connector-sqlserver/pom.xml
> DBZ-8564 Switch to quay.io for apicurio container

- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/junit/jupiter/Db2SinkDatabaseContextProvider.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/junit/jupiter/MySqlSinkDatabaseContextProvider.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/junit/jupiter/PostgresSinkDatabaseContextProvider.java
> DBZ-8564 Don't use docker hub for pulls (JDBC sink)

- debezium-connector-oracle/pom.xml
> DBZ-8564 Don't use docker hub for pulls (Oracle)

- debezium-connector-mongodb/pom.xml
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/MongoDbContainer.java
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/testhelper/TestInfrastructureHelper.java
relates to https://issues.redhat.com/browse/DBZ-8564
> DBZ-8564 Don't use dockerhub pulling for MongoDB

- debezium-bom/pom.xml
- debezium-storage/debezium-storage-azure-blob/pom.xml
- debezium-storage/debezium-storage-azure-blob/src/main/java/io/debezium/storage/azure/blob/history/AzureBlobSchemaHistory.java
- debezium-storage/debezium-storage-tests/pom.xml
- documentation/modules/ROOT/pages/operations/debezium-server.adoc
https://issues.redhat.com/browse/DBZ-8274
> DBZ-8274 Azure Managed Identity support for Azure Blob Schema History

- documentation/modules/ROOT/pages/transformations/content-based-routing.adoc
[DBZ-8550](https://issues.redhat.com/browse/DBZ-8550)
> DBZ-8550 docs correction for content-based routing header variable

- debezium-storage/debezium-storage-s3/src/main/java/io/debezium/storage/s3/history/S3SchemaHistory.java
- debezium-storage/debezium-storage-tests/src/test/java/io/debezium/storage/s3/history/S3SchemaHistoryIT.java
https://issues.redhat.com/browse/DBZ-8569
> DBZ-8569 Fix S3SchemaHistoryIT

- .github/workflows/debezium-workflow-pr.yml
- debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/DebeziumKafkaContainer.java
Fixes issue with JDBC tests that use non-KRaft deployments.
> DBZ-8564 Fix test failures using non-KRaft deployments

- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogSourceInfoTest.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/SourceInfoTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SourceInfoTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SourceInfoTest.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SourceInfoTest.java
- debezium-core/src/main/java/io/debezium/connector/AbstractSourceInfoStructMaker.java
- debezium-core/src/main/java/io/debezium/schema/SchemaFactory.java
https://issues.redhat.com/browse/DBZ-8499
> DBZ-8499 Make source info versioned

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFileCollector.java
https://issues.redhat.com/browse/DBZ-8546
> DBZ-8546 Simplify consistency check to avoid race condition

- pom.xml
https://issues.redhat.com/browse/DBZ-8583
> DBZ-8583 Upgrade Outbox Extension to Quarkus 3.17.7

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-8577
> DBZ-8577 On reconnection, make sure we're connected to container root

- debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java
- documentation/modules/ROOT/pages/post-processors/reselect-columns.adoc
https://issues.redhat.com/browse/DBZ-8336
> DBZ-8336 Error Handling Mode for ReselectColumnsPostProcessor

- documentation/modules/ROOT/partials/modules/all-connectors/con-connector-incremental-snapshot.adoc
closes: https://issues.redhat.com/browse/DBZ-8596
> DBZ-8595 Mention write permission on signaling data collection for incremental snapshot

- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/RecordWriter.java
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/ReducedRecordBuffer.java
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/dialect/GeneralDatabaseDialect.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/ReducedRecordBufferTest.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkPrimaryKeyModeTest.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/util/SinkRecordFactory.java
- debezium-sink/src/main/java/io/debezium/bindings/kafka/KafkaDebeziumSinkRecord.java
- debezium-sink/src/main/java/io/debezium/sink/DebeziumSinkRecord.java
https://issues.redhat.com/browse/DBZ-8593
> DBZ-8593 Fix ReducedRecord Buffer implementation in case of RECORD_VALUE mode

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerColumnResolverDmlParser.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/HybridMiningStrategyIT.java
https://issues.redhat.com/browse/DBZ-8597
> DBZ-8597 Fix hybrid column resolution for tables with generated columns

- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/RecordWriter.java
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/ReducedRecordBuffer.java
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/SinkRecordDescriptor.java
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/dialect/GeneralDatabaseDialect.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/ReducedRecordBufferTest.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkPrimaryKeyModeTest.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/util/SinkRecordFactory.java
https://issues.redhat.com/browse/DBZ-8593
> DBZ-8593 Fix ReducedRecord Buffer impl in case of RECORD_VALUE mode

- pom.xml
https://issues.redhat.com/browse/DBZ-8601
> DBZ-8601 Update server/operator to Quarkus 3.15.3

- jenkins-jobs/job-dsl/release/release_deploy_snapshots.groovy
- jenkins-jobs/pipelines/release/deploy_snapshots_pipeline.groovy
closes: https://issues.redhat.com/browse/DBZ-8604
depends on: https://github.com/debezium/debezium-platform/pull/18
> DBZ-8604 Change snapshot pipeline to publish conductor artifacts

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-8645
> DBZ-8645 Remove misplaced log entry

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetrics.java
https://issues.redhat.com/browse/DBZ-8646
> DBZ-8646 Apply timezone offset to OldestScnAgeInMilliseconds

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetrics.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetricsMXBean.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerStreamMetricsTest.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-8644
> DBZ-8644 Introduce new `MinedLogFileNames` metric

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetricsMXBean.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerStreamMetricsTest.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-8647
> DBZ-8647 Remove deprecated LogMiner streaming JMX metrics

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-8652
> DBZ-8652 Add dedicated increment/decrement property

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
https://issues.redhat.com/browse/DBZ-8653
> DBZ-8653 Emit LOB when available even when `lob.enabled` is off

- debezium-core/src/main/java/io/debezium/relational/history/SchemaHistory.java
- documentation/modules/ROOT/partials/modules/snippets/frag-mariadb-props-snippets.adoc
- documentation/modules/ROOT/partials/modules/snippets/frag-mysql-props-snippets.adoc
https://issues.redhat.com/browse/DBZ-8558
> DBZ-8558 Correct schema.history.internal.store.only.captured.databases.ddl default value for MariaDB/MySQL

- debezium-connector-jdbc/README.md
https://issues.redhat.com/browse/DBZ-8225
> DBZ-8225 Add README for the JDBC sink connector

- jenkins-jobs/scripts/trigger-nightly-docker.sh
closes: https://issues.redhat.com/browse/DBZ-8607
depends on: https://github.com/debezium/container-images/pull/421
> DBZ-8607 Build and publish stage/conductor nightly images to image registry

- pom.xml
https://issues.redhat.com/browse/DBZ-8695
> Update format-maven-plugin to 2.25.0

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-8681
> DBZ-8681 Avoid updating commit offsets for empty transactions with redo thread 0

- pom.xml
Reverts debezium/debezium#6166
> Revert "Update format-maven-plugin to 2.25.0"

- debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
https://issues.redhat.com/browse/DBZ-8692
> DBZ-8692 - Enhanced error messages on schema validation failures

- .github/actions/build-debezium-cassandra/action.yml
- .github/actions/build-debezium-db2/action.yml
- .github/actions/build-debezium-ibmi/action.yml
- .github/actions/build-debezium-informix/action.yml
- .github/actions/build-debezium-server/action.yml
- .github/actions/build-debezium-spanner/action.yml
- .github/actions/build-debezium-vitess/action.yml
closes: https://issues.redhat.com/browse/DBZ-8698
> DBZ-8698 Enable checkstyle and format on project outside main repo

- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/CommitScnTest.java
https://issues.redhat.com/browse/DBZ-8716
> DBZ-8716 Add more unit tests for deciding if the row was handled

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
https://issues.redhat.com/browse/DBZ-8725
> DBZ-8725 Fix ill-formed SQL query when archive.log.hours > 0

- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java
https://issues.redhat.com/browse/DBZ-8726
> DBZ-8726 Refactor JdbcChangeEventSink execute method for buffer resolution

- documentation/modules/ROOT/pages/operations/debezium-server.adoc
Documentation for DBZ-8715 (https://github.com/debezium/debezium-server/pull/157 is the change in debezium server)
> DBZ-8715 Added message compression and concurrency control

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDdlParserTest.java
https://issues.redhat.com/browse/DBZ-8700
> DBZ-8700 Only reset scale when column type is modified

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-8559
> DBZ-8559 Allow scalar expressions in Percona SEQUENCE_TABLE

- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-8159
> DBZ-8159 Add section about Oracle mTLS connectivity

- documentation/modules/ROOT/pages/transformations/content-based-routing.adoc
- documentation/modules/ROOT/pages/transformations/filtering.adoc
This is an initial take on it, I would be grateful to have some guidance on two aspects:
1. the content itself: and how is split for product/community
2. how do I preview locally the changes I'm doing? Trying to run antora locally gives the following error:
```bash
$ npx antora antora.yml
[18:36:21.107] FATAL (antora): ui.bundle.url: must be of type String in /.../debezium/documentation/antora.yml (cwd: /.../debezium/documentation, playbook: antora.yml)
```
thanks in advance :pray:
> DBZ-8666 Wasm SMT docs

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mariadb/generated/MariaDBParser.g4
- debezium-ddl-parser/src/test/resources/mariadb/examples/fast/ddl_alter.sql
https://issues.redhat.com/browse/DBZ-8741
> DBZ-8741 Extended support for MariaDB's ALTER INDEX DDL

- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogConvertingFailureIT.java
https://issues.redhat.com/browse/DBZ-8736
> DBZ-8595 Don't stop already stopped engine

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerPartition.java
- debezium-core/src/main/java/io/debezium/connector/common/OffsetReader.java
- debezium-core/src/main/java/io/debezium/pipeline/spi/Partition.java
Added fallback mechanism to retrieve offsets for partition in case of planned change
> DBZ-5845 Added fallback source for offsets retrieval

- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkDeleteEnabledTest.java
https://issues.redhat.com/browse/DBZ-8287
> DBZ-8287 Treat tombstones as delete events

- debezium-bom/pom.xml
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogCloudEventsConverterIT.java
- debezium-connector-mariadb/pom.xml
- debezium-connector-mongodb/pom.xml
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/CloudEventsConverterIT.java
- debezium-connector-mysql/pom.xml
- debezium-connector-postgres/pom.xml
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/CloudEventsConverterIT.java
- debezium-core/src/main/java/io/debezium/converters/CloudEventsConverter.java
- debezium-core/src/main/java/io/debezium/converters/CloudEventsConverterConfig.java
- debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadata.java
- debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadataBaseImpl.java
- debezium-core/src/main/java/io/debezium/converters/recordandmetadata/RecordAndMetadataHeaderImpl.java
- debezium-core/src/main/java/io/debezium/converters/spi/CloudEventsMaker.java
- debezium-core/src/test/java/io/debezium/converters/CloudEventsConverterTest.java
- debezium-embedded/src/test/java/io/debezium/converters/AbstractCloudEventsConverterTest.java
- pom.xml
https://issues.redhat.com/browse/DBZ-8669
> DBZ-8669 A CloudEvent can contain `traceparent` field which value is obtained from header

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSourceInfoStructMaker.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SourceInfoTest.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-8740
> DBZ-8740 Add start/commit scn and time values to Oracle source info

- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorConfig.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/JdbcSinkConnectorConfigTest.java
https://issues.redhat.com/browse/DBZ-7810
> DBZ-7810 Support empty passwords in jdbc connections

- debezium-bom/pom.xml
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/SnapshotIsolationIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
- debezium-core/src/test/java/io/debezium/converters/CloudEventsConverterTest.java
https://issues.redhat.com/browse/DBZ-8751
> DBZ-8751 Update to assertj 3.27.3

- jenkins-jobs/job-dsl/release/release_upstream.groovy
- jenkins-jobs/pipelines/release/release-pipeline.groovy
closes: https://issues.redhat.com/browse/DBZ-8682
these must be merged first: 
* https://github.com/debezium/debezium-platform/pull/22
* https://github.com/debezium/container-images/pull/428
> DBZ-8682 Add support for building debezium platform into release pipeline

- jenkins-jobs/job-dsl/release/release_charts_upstream.groovy
- jenkins-jobs/pipelines/release/release-charts-pipeline.groovy
- jenkins-jobs/pipelines/release/release-pipeline.groovy
- jenkins-jobs/vars/common.groovy
- jenkins-jobs/vars/fileUtils.groovy
closes: https://issues.redhat.com/browse/DBZ-8706
> DBZ-8706 Add pipeline for package and distribute helm charts

- jenkins-jobs/job-dsl/release/deploy_docker_images.groovy
- jenkins-jobs/job-dsl/release/parameters/common_parameters.groovy
- jenkins-jobs/job-dsl/release/parameters/deploy_docker_images_parameters.groovy
- jenkins-jobs/job-dsl/release/parameters/release_charts_upstream_parameters.groovy
- jenkins-jobs/job-dsl/release/parameters/release_upstream_parameters.groovy
- jenkins-jobs/job-dsl/release/release_charts_upstream.groovy
- jenkins-jobs/job-dsl/release/release_orchestrator.groovy
- jenkins-jobs/job-dsl/release/release_upstream.groovy
- jenkins-jobs/pipelines/release/build_debezium_images_pipeline.groovy
- jenkins-jobs/pipelines/release/release-charts-pipeline.groovy
- jenkins-jobs/pipelines/release/release-orchestrator-pipeline.groovy
- jenkins-jobs/pipelines/release/release-pipeline.groovy
- jenkins-jobs/vars/common.groovy
closes: https://issues.redhat.com/browse/DBZ-8731
based on: https://github.com/debezium/debezium/pull/6183 must be rebased after its merge.
> DBZ-8731: Create an orchestrator pipeline to run the release

- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/Buffer.java
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/RecordBuffer.java
- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/ReducedRecordBuffer.java
https://issues.redhat.com/browse/DBZ-8570
> DBZ-8570 Reduce frequency table exists and column metadata queries

- jenkins-jobs/job-dsl/release/parameters/release_upstream_parameters.groovy
- jenkins-jobs/pipelines/release/build_debezium_images_pipeline.groovy
- jenkins-jobs/pipelines/release/release-charts-pipeline.groovy
- jenkins-jobs/pipelines/release/release-pipeline.groovy
- jenkins-jobs/vars/common.groovy
Follow-up changes after Beta1 release.
> DBZ-8682 remove explicit tag for debezium platform in release pipeline

- debezium-core/src/main/java/io/debezium/config/Field.java
- debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordStateConfigDefinition.java
Addressing https://issues.redhat.com/browse/DBZ-8776
> DBZ-8776: Return delete.tombstone.handling.mode from ExtractNewRecordState config method

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
[DBZ-8687](https://issues.redhat.com/browse/DBZ-8687)
Backport updates from #6225 and #6226 to 3.0 branch.
> Dbz 8687 pg replication slot failover 3.0 branch

- jenkins-jobs/job-dsl/release/parameters/release_charts_upstream_parameters.groovy
- jenkins-jobs/pipelines/release/release-charts-pipeline.groovy
closes: https://issues.redhat.com/browse/DBZ-8707
> DBZ-8707 Centralize helm chart repo

- debezium-connector-mariadb/src/main/java/io/debezium/connector/mariadb/MariaDbErrorHandler.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlErrorHandler.java
https://issues.redhat.com/browse/DBZ-8786
> DBZ-8786 Improve Error Handling for Duplicate server_id / server_uuid in MySQL Connector

- debezium-core/src/main/java/io/debezium/transforms/ConnectRecordUtil.java
- debezium-core/src/main/java/io/debezium/transforms/HeaderToValue.java
https://issues.redhat.com/browse/DBZ-8825
> DBZ-8825 Make methods for adding fields into the record reuseable

- pom.xml
- support/ide-configs/src/main/resources/eclipse/debezium-formatter.xml
https://issues.redhat.com/browse/DBZ-8695
> Update format-maven-plugin to 2.26.0

- jenkins-jobs/job-dsl/release/parameters/deploy_docker_images_parameters.groovy
closes: https://issues.redhat.com/browse/DBZ-8829
> DBZ-8829 UI images are no more skipped by default

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/AbstractProcessorUnitTest.java
https://issues.redhat.com/browse/DBZ-8830
> DBZ-8830 Apply query timeout to Oracle LogMiner query

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-8844
> DBZ-8844 Don't skip transaction at snapshot boundary

- debezium-bom/pom.xml
https://issues.redhat.com/browse/DBZ-8848
> DBZ-8848 Update Azure Identity to 1.15.4

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-8834
> DBZ-8834 Support CURDATE and CURTIME functions for MySQL DDL

- debezium-connector-jdbc/src/test/resources/logback-test.xml
https://issues.redhat.com/browse/DBZ--8853
> DBZ-8853 Set JDBC sink test default log level as INFO

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
https://issues.redhat.com/browse/DBZ-8849
> DBZ-8849 Default column values can be scalar functions

- documentation/modules/ROOT/pages/connectors/postgresql.adoc
(cherry picked from commit 379f78bcda22292063da05b0e617ba1b1675cf44)
> [docs] Fix broken link to Troubleshooting procedure

- documentation/modules/ROOT/pages/connectors/jdbc.adoc
(cherry picked from commit 85ffc54aa0feda9d40ae61ab5c737164a490f604)
> [docs] Re-target link to correct topic ID

- documentation/modules/ROOT/pages/connectors/mariadb.adoc
https://issues.redhat.com/browse/DBZ-8755
> DBZ-8755 Add binlog admonition

- documentation/modules/ROOT/nav.adoc
closes: https://issues.redhat.com/browse/DBZ-8846
> DBZ-8846 Add new section "Standalone Debezium" for Debezium Server ad related components

- pom.xml
Updating the base project instead of debezium-connector-cassandra as requested by https://github.com/debezium/debezium-connector-cassandra/pull/145#discussion_r2013492112
> DBZ-8842 update cassandra4 from 4.0.2 to 4.1.x

- documentation/modules/ROOT/pages/operations/debezium-server.adoc
Documents https://github.com/debezium/debezium-server/pull/156
> DBZ-8634 Document Milvus sink

- debezium-connector-mariadb/src/test/docker/server-gtids/my.cnf
- debezium-connector-mariadb/src/test/docker/server-replica/my.cnf
- debezium-connector-mariadb/src/test/docker/server-ssl/my.cnf
- debezium-connector-mariadb/src/test/docker/server/my.cnf
https://issues.redhat.com/browse/DBZ-8755
> DBZ-8755 Add position of the next event in the binary log

- pom.xml
https://issues.redhat.com/browse/DBZ-8864
> DBZ-8864 Upgdare RocketMQ to 5.2.0

- documentation/modules/ROOT/pages/operations/debezium-server.adoc
https://issues.redhat.com/browse/DBZ-8637
> DBZ-8637 Document InstructLab sink

- debezium-bom/pom.xml
- debezium-scripting/debezium-scripting/src/main/java/io/debezium/transforms/scripting/wasm/ChicoryEngine.java
`ByteArrayMemory` is a faster implementation of the Memory.
> DBZ-8867 Bump Chicory and use ByteArrayMemory

- debezium-connector-mariadb/src/main/java/io/debezium/connector/mariadb/MariaDbConnectorConfig.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
https://issues.redhat.com/browse/DBZ-8868
> DBZ-8868 Make getHistoryRecordComparator() public

- .packit.yaml
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java
https://issues.redhat.com/browse/DBZ-8869
> DBZ-8869 Fix several SQL relaxed quote corner cases

- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-8788
> DBZ-8788 Document mTLS using JKS with Oracle

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-8880
> DBZ-8880 Clear events for abandoned transaction over threshold

- jenkins-jobs/pipelines/release/release-charts-pipeline.groovy
closes: https://issues.redhat.com/browse/DBZ-8878
> DBZ-8878 Change release chart pipeline execution node from release to slave

- documentation/modules/ROOT/pages/configuration/signalling.adoc
(cherry picked from commit bc7da1b23519c2db36e3068b85b95b0a4a83f036)
> [docs] Apply fix for signaling topic callout rendering to 3.0

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SnapshotDatatypesIT.java
https://issues.redhat.com/browse/DBZ-8889
> DBZ-8889 Fix ISOSTRING conversion for Oracle timestamps

- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/e2e/AbstractJdbcSinkPipelineIT.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/junit/jupiter/e2e/WithTemporalPrecisionMode.java
- debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/junit/jupiter/e2e/source/SourcePipelineInvocationContextProvider.java
https://issues.redhat.com/browse/DBZ-8574
> DBZ-8574 Add ISOSTRING tests to JDBC sink

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeRecordEmitter.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ReplicationMessage.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
- debezium-core/src/main/java/io/debezium/pipeline/spi/ChangeRecordEmitter.java
https://issues.redhat.com/browse/DBZ-8576
> DBZ-8576: Incorrect NumberOfEventsFiltered metrics in streaming

- pom.xml
https://issues.redhat.com/browse/DBZ-8905
> DBZ-8905 Upgrade Outbox Extension to Quarkus 3.21.2

- pom.xml
https://issues.redhat.com/browse/DBZ-8906
> DBZ-8906 Update to Quarkus LTS 3.15.4

- documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-db2-kafka-connect-yaml.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-oracle-kafka-connect-yaml.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/shared-deploy-kafka-connect-yaml.adoc
(cherry picked from commit 8fb1aa01b00516e911ee4587a55672cc0d8e9e60)
> [docs] Fix KC YAML apicurio URL;sub attr for `build-number` placeholder

- documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-db2-kafka-connect-yaml.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/ref-deploy-oracle-kafka-connect-yaml.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/shared-deploy-kafka-connect-yaml.adoc
(cherry picked from commit f9c59346623f02e52254abd9dfa837b08ebd2f74)
> [docs] Corrects refs to external Streams docs (downstream only)

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-8919
> DBZ-8919 Ignore continuous mining config on Oracle 18+

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/CacheCapacityExceededException.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/EhcacheEvictionListener.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/EhcacheLogMinerCache.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/EhcacheLogMinerEventProcessor.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/EhcacheLogMinerTransactionCache.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/EhcacheIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
- debezium-core/src/test/java/io/debezium/junit/logging/LogInterceptor.java
https://issues.redhat.com/browse/DBZ-8874
This PR depends on #6296, which includes the rework of the transaction/event caches.
> DBZ-8874 Guard against silent Ehcache evictions

- debezium-ai/debezium-ai-embeddings-ollama/src/main/java/io/debezium/ai/embeddings/OllamaModelFactory.java
- debezium-ai/debezium-ai-embeddings/src/main/java/io/debezium/ai/embeddings/FieldToEmbedding.java
https://issues.redhat.com/browse/DBZ-8907
https://issues.redhat.com/browse/DBZ-8908
> DBZ-8907 DBZ-8908 - Fix NPE; Add timeout configuration

- debezium-ai/debezium-ai-embeddings/src/test/java/io/debezium/ai/embeddings/FieldToEmbeddingTest.java
- debezium-core/src/main/java/io/debezium/transforms/ConnectRecordUtil.java
- debezium-core/src/test/java/io/debezium/transforms/ConnectRecordUtilTest.java
https://issues.redhat.com/browse/DBZ-8910
> DBZ-8910 Fix various ConnectRecordUtil  issues

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
https://issues.redhat.com/browse/DBZ-8921
> DBZ-8921 Remove extra filter check for non-hybrid strategies

- documentation/antora.yml
- documentation/modules/ROOT/pages/install.adoc
https://issues.redhat.com/browse/DBZ-8927
> DBZ-8927 Add MariaDB connector link to Installation Guide

- documentation/modules/ROOT/pages/operations/debezium-server.adoc
Following this PR:
https://github.com/debezium/debezium-server/pull/173
> DBZ-8911 docs: Add configuration option to skip heartbeat messages in Redis

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-embedded/src/test/java/io/debezium/pipeline/AbstractMetricsTest.java
closes: https://issues.redhat.com/browse/DBZ-8897
> DBZ-8897 Fix missing CapturedTables streaming metrics for PostgreSQL

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java
https://issues.redhat.com/browse/DBZ-8925
The goal here is to optimize repeated lookups for the same `objectId` / `dataObjectId` tuple. The lookup cost is quite costly for large transactions, and by caching the prior lookup, we can avoid the cache call entirely.  For this unique case, we can gain around a 4x - 4.5x performance increase alone.
> DBZ-8925 Improve Hybrid strategy performance with the Oracle ObjectId cache

- debezium-core/src/main/java/io/debezium/processors/PostProcessorRegistryServiceProvider.java
- debezium-embedded/src/test/java/io/debezium/processors/AbstractReselectProcessorTest.java
closes: https://issues.redhat.com/browse/DBZ-8901
> DBZ-8901 Improve exception message in case of a miss-configured post processor

- documentation/modules/ROOT/pages/configuration/signalling.adoc
https://issues.redhat.com/browse/DBZ-8723
> DBZ-8723 Update docs to mandate all column names of signal table

- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
- debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtAndConvertAsyncConsumerProcessor.java
- debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtAndConvertConsumerProcessor.java
- debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtAsyncConsumerProcessor.java
- debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtConsumerProcessor.java
- debezium-embedded/src/test/java/io/debezium/embedded/async/AsyncEmbeddedEngineTest.java
https://issues.redhat.com/browse/DBZ-8936
> DBZ-8936 Shut down gracefully upon StopEngineException

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/events/LogMinerEventRow.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractTransaction.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/Transaction.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/EhcacheLogMinerEventProcessor.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/EhcacheTransaction.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/serialization/EhcacheTransactionSerializer.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/InfinispanTransaction.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/marshalling/TransactionAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryTransaction.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/ClientIdFilterIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-8904
> DBZ-8904 Add filtering by LogMiner column CLIENT_ID

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
https://issues.redhat.com/browse/DBZ-8926
> DBZ-8926 Fetch `OBJ# %` rows only when using Hybrid with query filters

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
DBZ-8743 added functionality to check if PostgreSQL is in standby mode and to check publications, in particular that the publication includes all changes from the Postgres master node.
> DBZ-8743 Prevent write operations (Create/Alter) while Postgres in standBy mode.

- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java
https://issues.redhat.com/browse/DBZ-8938
> DBZ-8938 Remove unnecessary metadata query & map gets

- debezium-api/src/main/java/io/debezium/engine/DebeziumEngine.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/DebeziumEngineIT.java
- debezium-embedded/src/test/java/io/debezium/embedded/ConnectorOutputTest.java
- debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java
- debezium-embedded/src/test/java/io/debezium/embedded/async/AsyncEmbeddedEngineTest.java
https://issues.redhat.com/browse/DBZ-8779
> DBZ-8779 Use async engine factory as the default builder factory

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metrics/SqlServerStreamingPartitionMetrics.java
- debezium-core/src/main/java/io/debezium/pipeline/meters/StreamingMeter.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/DefaultStreamingChangeEventSourceMetrics.java
- debezium-core/src/main/java/io/debezium/pipeline/metrics/traits/StreamingMetricsMXBean.java
Backporting changes made in PR https://github.com/debezium/debezium/pull/6305
> DBZ-8885: Backporting option to reset lagBehindSource metric separately

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-8944
> DBZ-8944 Improve logging for partial rollback failures

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/AbstractStreamingAdapter.java
https://issues.redhat.com/browse/DBZ-8943
> DBZ-8943 Handle error codes 8180 through 8189 universally

- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcKafkaSinkRecord.java
https://issues.redhat.com/browse/DBZ-8946
> DBZ-8946 pass topic name in exception

- debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java
- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedIncrementalSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/txmetadata/TransactionMonitor.java
- debezium-core/src/main/java/io/debezium/relational/TableSchema.java
- debezium-core/src/main/java/io/debezium/transforms/HeaderToValue.java
- debezium-core/src/main/java/io/debezium/transforms/SmtManager.java
- debezium-core/src/main/java/io/debezium/transforms/extractnewstate/DefaultDeleteHandlingStrategy.java
- debezium-core/src/main/java/io/debezium/transforms/extractnewstate/LegacyDeleteHandlingStrategy.java
- debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterDelegate.java
- debezium-core/src/main/java/io/debezium/transforms/partitions/PartitionRouting.java
- debezium-core/src/main/java/io/debezium/util/Loggings.java
This PR addresses the performance regression introduced as part of #6222.
JIRA: https://issues.redhat.com/browse/DBZ-8879
Zulip Chat: https://debezium.zulipchat.com/#narrow/channel/302529-community-general/topic/Performance.20Regression.20after.203.2E1.2E0.2EBeta1
> DBZ-8879: Fix performance regression in debezium-core

- documentation/modules/ROOT/nav.adoc
- documentation/modules/ROOT/pages/configuration/storage.adoc
https://issues.redhat.com/browse/DBZ-6532
> DBZ-6532 Debezium Storage documentation

- debezium-connector-mariadb/pom.xml
- debezium-connector-mongodb/pom.xml
- debezium-connector-mysql/pom.xml
- debezium-connector-postgres/pom.xml
https://issues.redhat.com/browse/DBZ-8971
> DBZ-8971 Turn off open telemetry agent logging

- debezium-api/src/main/java/io/debezium/engine/DebeziumEngine.java
- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
- debezium-embedded/src/test/java/io/debezium/embedded/async/AsyncEmbeddedEngineTest.java
https://issues.redhat.com/browse/DBZ-8948
> DBZ-8948 Add polling start and stop engine callbacks

- jenkins-jobs/pipelines/release/release-charts-pipeline.groovy
closes: https://issues.redhat.com/browse/DBZ-8955
> DBZ-8955 Avoid to download operator from maven during dry run

- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogDecimalIT.java
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogDefaultValueIT.java
- debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogJdbcSinkDataTypeConverterIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotCaseSensitiveIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDefaultValueIT.java
https://issues.redhat.com/browse/DBZ-7356
> DBZ-7356 Remove skipping Avro validation

- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/StreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-8995
> DBZ-8995 Make StreamingChangeEventSource closeable

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotContext.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java
https://issues.redhat.com/browse/DBZ-8974
> DBZ-8974 Include JSON source in deserialization exceptions

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java
https://issues.redhat.com/browse/DBZ-9001
> DBZ-9001 Validate Oracle `signal.data.collection`

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-9002
> DBZ-9002 Delay relational snapshot in-progress notification until export begins

- debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java
- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedIncrementalSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/txmetadata/TransactionMonitor.java
- debezium-core/src/main/java/io/debezium/relational/TableSchema.java
- debezium-core/src/main/java/io/debezium/transforms/HeaderToValue.java
- debezium-core/src/main/java/io/debezium/transforms/SmtManager.java
- debezium-core/src/main/java/io/debezium/transforms/extractnewstate/DefaultDeleteHandlingStrategy.java
- debezium-core/src/main/java/io/debezium/transforms/extractnewstate/LegacyDeleteHandlingStrategy.java
- debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterDelegate.java
- debezium-core/src/main/java/io/debezium/transforms/partitions/PartitionRouting.java
- debezium-core/src/main/java/io/debezium/util/Loggings.java
Backporting https://github.com/debezium/debezium/pull/6313
> Backporting DBZ-8879 from main to 3.0

- .github/workflows/debezium-workflow-push.yml
Remove missing dependencies on rest-extensions
> DBZ-8777 Remove missing dependencies on rest-extensions

- debezium-ddl-parser/src/test/resources/mariadb/examples/fast/ddl_create.sql
https://issues.redhat.com/browse/DBZ-8916
> DBZ-8916 Fix comments in the MariaDB create DDL file

- debezium-bom/pom.xml
https://issues.redhat.com/browse/DBZ-9015
> DBZ-9015 Add IBMi connector to BOM

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresReadOnlyIncrementalSnapshotChangeEventSource.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/ReadOnlyIncrementalSnapshotIT.java
closes: https://issues.redhat.com/browse/DBZ-9016
> DBZ-9016 Avoid to process streaming event when incremental snapshot is not running

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/unbuffered/UnbufferedLogMinerStreamingChangeEventSource.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/unbuffered/UnbufferedLogMinerAdapterIT.java
https://issues.redhat.com/browse/DBZ-9013
> DBZ-9013 Fix updating the offset scn using LogMiner unbuffered

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/util/OracleUtils.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleUtilsTest.java
https://issues.redhat.com/browse/DBZ-9019
> DBZ-9019 Improve case-sensitive pdb/dbname handling

- debezium-testing/debezium-testing-system/pom.xml
- pom.xml
https://issues.redhat.com/browse/DBZ-9025
https://github.com/debezium/debezium-connector-cassandra/pull/147
https://github.com/debezium/debezium-connector-db2/pull/177
https://github.com/debezium/debezium-connector-ibmi/pull/46
https://github.com/debezium/debezium-connector-informix/pull/75
https://github.com/debezium/debezium-connector-spanner/pull/110
https://github.com/debezium/debezium-connector-vitess/pull/240
https://github.com/debezium/debezium-server/pull/181
https://github.com/debezium/debezium-operator/pull/105
Jenkins jobs will be updated in a separate PR
> DBZ-9025 Use Maven Central snapshot repository

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/memory/MemoryLogMinerTransactionCache.java
https://issues.redhat.com/browse/DBZ-9030
> DBZ-9030 Fix performance regression with transaction inserts

- documentation/modules/ROOT/pages/configuration/storage.adoc
- documentation/modules/ROOT/pages/development/engine.adoc
- documentation/modules/ROOT/pages/operations/debezium-server.adoc
- documentation/modules/ROOT/pages/transformations/partition-routing.adoc
- documentation/modules/ROOT/pages/transformations/timescaledb.adoc
Hi @roldanbob, can you check if these fixes create any issues for the downstream builds? These were generating several build warnings and errors.
> [docs] Fix several Antora doc build errors/warnings

- debezium-bom/pom.xml
https://issues.redhat.com/browse/DBZ-9037
> DBZ-9037 Update to Mockito 5.17.0

- pom.xml
https://issues.redhat.com/browse/DBZ-9032
> DBZ-9032 Upgrade Server/Operator to Quarkus 3.20.1

- pom.xml
https://issues.redhat.com/browse/DBZ-9033
> DBZ-9033 Upgrade Quarkus Outbox Extension to Quaruks 3.22.2

- debezium-bom/pom.xml
- debezium-connector-oracle/pom.xml
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/infinispan/marshalling/DmlEventAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/infinispan/marshalling/ExtendedStringBeginEventAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/infinispan/marshalling/LobWriteEventAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/infinispan/marshalling/LogMinerDmlEntryImplAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/infinispan/marshalling/LogMinerEventAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/infinispan/marshalling/LogMinerEventMarshaller.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/infinispan/marshalling/RedoSqlDmlEventAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/infinispan/marshalling/SelectLobLocatorEventAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/infinispan/marshalling/TransactionAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/infinispan/marshalling/TransactionMarshaller.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/infinispan/marshalling/TruncateEventAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/infinispan/marshalling/XmlBeginEventAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/infinispan/marshalling/XmlWriteEventAdapter.java
- pom.xml
https://issues.redhat.com/browse/DBZ-9038
> DBZ-9038 Update to Infinispan 15.2.1.Final

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
- debezium-ddl-parser/src/test/resources/mysql/examples/dml_insert.sql
https://issues.redhat.com/browse/DBZ-9034
> DBZ-9034 Support joins against MySQL JSON_TABLE types

- debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/type/AbstractType.java
https://issues.redhat.com/browse/DBZ-9040
> DBZ-9040 Correctly handle nested quotes in string default values

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-core/src/main/java/io/debezium/pipeline/signal/channels/KafkaSignalChannel.java
- debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
- debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java
Backporting https://github.com/debezium/debezium/pull/6345 from main to 3.1
> DBZ-8875 backport from main to 3.1

- pom.xml
https://issues.redhat.com/browse/DBZ-9032
> DBZ-9032 Revert Server/Operator update to Quarkus 3.20.1 / Antlr 4.13.0

- debezium-core/src/main/java/io/debezium/pipeline/signal/channels/KafkaSignalChannel.java
- debezium-core/src/test/java/io/debezium/pipeline/signal/KafkaSignalChannelTest.java
https://issues.redhat.com/browse/DBZ-9052
> DBZ-9052 Add validation for KafkaSignalChannel

- debezium-core/src/main/java/io/debezium/config/Field.java
https://issues.redhat.com/browse/DBZ-9060
> DBZ-9060 Propagate deprecatedAliases also in other config options

- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
https://issues.redhat.com/browse/DBZ-9055
> DBZ-9055 Always resume streaming after a blocking snapshot

- debezium-bom/pom.xml
Removing duplicate rest-assured version entry from bom. Updated the version to latest.
> DBZ-9069 : Removing duplicate rest-assured version entry from bom

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentState.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/MongoDataConverter.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/outbox/MongoEventRouter.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTestIT.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/MongoArrayConverterTest.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/MongoDataConverterTest.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ToAvroMongoDataConverterTest.java
https://issues.redhat.com/browse/DBZ-5920
> DBZ-5920 Refactor MongoDB ExtractNewDocumentState SMT

- debezium-connector-oracle/src/main/resources/META-INF/services/org.apache.kafka.connect.rest.ConnectRestExtension
https://issues.redhat.com/browse/DBZ-9101
> DBZ-9101 Remove REST extension plugin service load configuration

- debezium-connector-mongodb/src/main/resources/META-INF/services/org.apache.kafka.connect.rest.ConnectRestExtension
- debezium-connector-mysql/src/main/resources/META-INF/services/org.apache.kafka.connect.rest.ConnectRestExtension
- debezium-connector-postgres/src/main/resources/META-INF/services/org.apache.kafka.connect.rest.ConnectRestExtension
- debezium-connector-sqlserver/src/main/resources/META-INF/services/org.apache.kafka.connect.rest.ConnectRestExtension
https://issues.redhat.com/browse/DBZ-9101
> DBZ-9101 Remove more REST extension plugin service load configurations

- debezium-bom/pom.xml
- debezium-microbenchmark/pom.xml
- debezium-scripting/debezium-scripting-languages/pom.xml
- debezium-scripting/debezium-scripting/pom.xml
- debezium-scripting/debezium-scripting/src/main/java/io/debezium/transforms/scripting/WasmEngine.java
- debezium-scripting/debezium-scripting/src/main/java/io/debezium/transforms/scripting/wasm/ChicoryEngine.java
- debezium-scripting/debezium-scripting/src/test/java/io/debezium/transforms/wasm/WasmFilterTest.java
Both, compiler and annotations are now released as stable.
I took the chance to align the naming, no-one should be directly referencing those from code as far as I understand.
> DBZ-9100 Bump Chicory to 1.4.0

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/AbstractLogMinerStreamingChangeEventSource.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/olr/OpenLogReplicatorStreamingChangeEventSource.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-9111
> DBZ-9111 Improve NonRelationalTableException log/exception message

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresConnectionIT.java
https://issues.redhat.com/browse/DBZ-9011
> DBZ-9011 Don't use deprecated txid_current()

- documentation/modules/ROOT/pages/operations/debezium-server.adoc
[DBZ-8637](https://issues.redhat.com/browse/DBZ-8637)
Post-merge review of docs added for Debezium Server InstructLab sink.
> DBZ-8637 Suggested edits to Debezium Server InstructLab sink doc

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java
https://issues.redhat.com/browse/DBZ-9191
> DBZ-9191 Apply relaxed quoting heuristics to inserted values

- pom.xml
https://issues.redhat.com/browse/DBZ-9200
> DBZ-9200 Upgrade PostgreSQL driver to 42.7.7

- .github/workflows/website-build-workflow.yml
https://issues.redhat.com/browse/DBZ-9025
Works in conjunction with https://github.com/debezium/debezium.github.io/pull/1141
> DBZ-9025 Build documentation daily

- documentation/modules/ROOT/pages/integrations/openlineage.adoc
related to: https://github.com/debezium/debezium/pull/6496
> DBZ-9110 Update OpenLineage required dependencies after moving then in dedicated module

- debezium-quarkus-outbox-common/runtime/src/main/java/io/debezium/outbox/quarkus/internal/DebeziumOutboxMetadataSourcesContributor.java
- debezium-quarkus-outbox-reactive/runtime/src/main/resources/META-INF/services/org.hibernate.boot.spi.AdditionalJaxbMappingProducer
- debezium-quarkus-outbox-reactive/runtime/src/main/resources/META-INF/services/org.hibernate.boot.spi.MetadataSourcesContributor
- debezium-quarkus-outbox/runtime/src/main/resources/META-INF/services/org.hibernate.boot.spi.AdditionalJaxbMappingProducer
- debezium-quarkus-outbox/runtime/src/main/resources/META-INF/services/org.hibernate.boot.spi.MetadataSourcesContributor
- pom.xml
https://issues.redhat.com/browse/DBZ-9219
> DBZ-9219 Update to Quarkus 3.23.4 - Align with Hibernate 7.x

- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogConnector.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnector.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnector.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnector.java
https://issues.redhat.com/browse/DBZ-9177
I intentionally do it in separate commits so we can easily revert it if there is any issue reported for given connector.
> Add EOS support to main source connectors

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
https://issues.redhat.com/browse/DBZ-9236
> DBZ-9236 Add display name for transaction snapshot boundary mode

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotChangeEventSource.java
- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/IncrementalSnapshotIT.java
https://issues.redhat.com/browse/DBZ-9232
> DBZ-9232 Fix MongoDB additional conditions on first incremental chunk

- documentation/modules/ROOT/nav.adoc
- documentation/modules/ROOT/pages/configuration/eos.adoc
https://issues.redhat.com/browse/DBZ-9230
> DBZ-9230 Add documentation for exactly-once delivery

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
- debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql
https://issues.redhat.com/browse/DBZ-9238
Upstream PR - https://github.com/antlr/grammars-v4/pull/4557
> DBZ-9238 Add `ONLINE` to Oracle `split_table_partition`

- jenkins-jobs/pipelines/release/release-charts-pipeline.groovy
- jenkins-jobs/vars/common.groovy
closes: https://issues.redhat.com/browse/DBZ-8913
> DBZ-8913 Use semVer in chart released artifacts.

- documentation/modules/ROOT/pages/connectors/db2.adoc
Also includes:
- Updated line formatting (one sentence per line)
- Minor language edits
> [docs] Replace instances of Debezium name with `prodname` attribute

- debezium-parent/pom.xml
- pom.xml
https://issues.redhat.com/browse/DBZ-9246
> DBZ-9246 Switch to smallrye jandex plugin and bump version

- debezium-openlineage/debezium-openlineage-core/src/main/java/io/debezium/openlineage/emitter/OpenLineageEmitter.java
closes: https://issues.redhat.com/browse/DBZ-9285
> DBZ-9285 Fix dataset type for OpenLineage output datasets

- documentation/modules/ROOT/pages/connectors/cassandra.adoc
- documentation/modules/ROOT/pages/connectors/db2.adoc
- documentation/modules/ROOT/pages/connectors/informix.adoc
- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/spanner.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
- documentation/modules/ROOT/pages/connectors/vitess.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/ref-mariadb-mysql-adv-connector-cfg-props.adoc
related to: https://github.com/debezium/debezium/pull/6593
> DBZ-9248 Add documentation for `extended.headers.enabled` configuration

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/UnistrHelper.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/UnistrHelperTest.java
https://issues.redhat.com/browse/DBZ-9132
> DBZ-9132 Fix parsing of UNISTR values with nested `||` sequence

- pom.xml
Uppdate Informix JDBC Driver to 4.50.12
> DBZ-9288 BP 3.2

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetrics.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetricsMXBean.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/BufferedLogMinerStreamingChangeEventSource.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerStreamMetricsTest.java
- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-8991
> DBZ-8991 Add `NumberOfEventsInBuffer` JMX metric

- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleReselectColumnsProcessorIT.java
- debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java
https://issues.redhat.com/browse/DBZ-9293
> DBZ-9293 Fix reselect using VariableScaleDecimal column type

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerDatabaseStateWriter.java
https://issues.redhat.com/browse/DBZ-9322
> DBZ-9322 Log all V$LOGMNR_LOGS rows on failures

- debezium-core/src/test/java/io/debezium/pipeline/EventDispatcherTest.java
https://issues.redhat.com/browse/DBZ-9332
> DBZ-9332 Remove unncessary stubbing

- debezium-bom/pom.xml
https://issues.redhat.com/browse/DBZ-9343
> DBZ-9343 Update assertj to 3.27.4

- debezium-testing/debezium-testing-testcontainers/pom.xml
- debezium-testing/pom.xml
https://issues.redhat.com/browse/DBZ-9342
> DBZ-9342 Use mockito only in testcontainers module

- pom.xml
https://issues.redhat.com/browse/DBZ-9331
> DBZ-9331 Upgrade to Kafka 3.9.1

- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/transformations/content-based-routing.adoc
- documentation/modules/ROOT/pages/transformations/filtering.adoc
[DBZ-9347](https://issues.redhat.com/browse/DBZ-9347)
Adjust admonitions that designate the Developer Preview or Technology Preview status of features.
Changes apply to the following files:
- `connectors/mongodb.adoc`
- `connectors/oracle.adoc`
- `connectors/postgresql.adoc`
- `transformations/content-based-routing.adoc`
- `transformations/filtering.adoc`
> DBZ-9347 Update status for DP, TP, and GA features

- debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/OpenLineageIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/OpenLineageIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/OpenLineageIT.java
closes: https://issues.redhat.com/browse/DBZ-9393
> DBZ-9393 Relax check on `version` for OpenLineage emitted events

- debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
- debezium-embedded/src/test/java/io/debezium/pipeline/AbstractBlockingSnapshotTest.java
closes: https://issues.redhat.com/browse/DBZ-9337
> DBZ-9337 Fix wrong offset initialization during blocking snapshot

- debezium-core/src/main/java/io/debezium/config/Instantiator.java
- debezium-core/src/main/java/io/debezium/converters/BinaryDataConverter.java
- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
https://issues.redhat.com/browse/DBZ-9375
> DBZ-9375 Configure TCCL in threads where some classloading happens

- debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
- debezium-embedded/src/test/java/io/debezium/embedded/EmbeddedEngineTest.java
https://issues.redhat.com/browse/DBZ-9398
> DBZ-9398 Use only one batch to avoid RejectedExecutionException during shutdown

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
Fix the logic that handles BLOB/CLOB values to support large binary objects (2GB+).
> DBZ-9392 Fix CLOB/BLOB column handing to support large data

- documentation/modules/ROOT/pages/connectors/oracle.adoc
Cherrypick from `main` plus additional correction
> [docs]  Clean up Oracle wallet topic

- documentation/modules/ROOT/pages/connectors/jdbc.adoc
[DBZ-9414](https://issues.redhat.com/browse/DBZ-9414) 
Cherry-pick from `main`
> Dbz 9414 edits to jdbc connector doc

- debezium-core/src/main/java/io/debezium/pipeline/EventDispatcher.java
- debezium-core/src/test/java/io/debezium/pipeline/EventDispatcherTest.java
closes: https://issues.redhat.com/browse/DBZ-9422
> DBZ-9422 Fix duplicate context headers during incremental snapshot

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerSessionContext.java
https://issues.redhat.com/browse/DBZ-9452
> DBZ-9452 Correctly skip LogMiner options for file strategy

- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogSnapshotChangeEventSource.java
- debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/jdbc/BinlogConnectorConnection.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
related to: https://github.com/debezium/debezium-platform/pull/83
> DBZ-9317 Uniform how all tables are retrieved from relational database

- pom.xml
https://issues.redhat.com/browse/DBZ-9480
> DBZ-9480 Update to Mockito 5.19.0

- quarkus-debezium-parent/quarkus-debezium-postgres-parent/runtime/src/main/resources-filtered/META-INF/quarkus-extension.yaml
closes: https://issues.redhat.com/browse/DBZ-9478
> DBZ-9478 publish in Quarkus the extension for Postgres

- debezium-bom/pom.xml
https://issues.redhat.com/browse/DBZ-9482
> DBZ-9482 Update AssertJ to 3.27.5

- documentation/modules/ROOT/pages/connectors/mongodb.adoc
- documentation/modules/ROOT/pages/connectors/oracle.adoc
- documentation/modules/ROOT/pages/connectors/postgresql.adoc
- documentation/modules/ROOT/pages/connectors/sqlserver.adoc
- documentation/modules/ROOT/partials/modules/all-connectors/ref-mariadb-mysql-adv-connector-cfg-props.adoc
Ref: https://github.com/debezium/debezium/pull/6718
> DBZ-9427: Documentation for guardrail configs

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrPosition.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-9497
> DBZ-9497 Populate commit_scn source field for XStream

- documentation/modules/ROOT/pages/connectors/jdbc.adoc
(cherry picked from commit f243e2aec8afd43ac6842a92e1f610dad654a0ec)
> [docs] Reflect JDBC connector type in title and anchor ID

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
https://issues.redhat.com/browse/DBZ-8923
> DBZ-8923 Flush only largest watermark to XStream

- debezium-connector-mariadb/src/test/resources/logback-test.xml
- debezium-connector-mysql/src/test/resources/logback-test.xml
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-embedded/src/test/java/io/debezium/pipeline/AbstractBlockingSnapshotTest.java
- debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractSnapshotTest.java
This PR adds a fix with test for the issue explained here https://issues.redhat.com/browse/DBZ-9494
> DBZ-9494: Adds a fix to ensure streaming is resumed if blocking snapshot thread encounters a failure

- documentation/modules/ROOT/pages/connectors/jdbc.adoc
(cherry picked from commit 99087c2e754716499ff37d7fedf1d903da557c16)
> [docs] Adjustments to correct downstream build errors

- documentation/modules/ROOT/pages/connectors/oracle.adoc
Retargets link in Oracle connector topic to point to Promoted to GA entry in release notes
> [docs] 3.2 update relnote link from oracle extended strings topic

- documentation/modules/ROOT/pages/operations/debezium-operator.adoc
closes: https://issues.redhat.com/browse/DBZ-9365
> DBZ-9365 Remove note about the helm versioning

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/unbuffered/UnbufferedLogMinerQueryBuilder.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/unbuffered/UnbufferedLogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-9476
> DBZ-9476 Introduce upperbounds to unbuffered mining mode

- debezium-openlineage/debezium-openlineage-core/src/main/java/io/debezium/openlineage/emitter/DebeziumOpenLineageClient.java
closes: https://issues.redhat.com/browse/DBZ-9524
> DBZ-9524 Correctly shutdown OpenLineage emitter

- .github/workflows/apicurio-check-workflow.yml
- .github/workflows/connector-postgresql-workflow.yml
- .github/workflows/jdk-outreach-workflow.yml
- debezium-connector-postgres/pom.xml
- jenkins-jobs/pipelines/release/release-pipeline.groovy
https://issues.redhat.com/browse/DBZ-9523
> DBZ-9523 Support for PostgreSQL 18

- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mariadb/generated/MariaDBLexer.g4
- debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mariadb/generated/MariaDBParser.g4
- debezium-ddl-parser/src/test/resources/mariadb/examples/fast/ddl_create.sql
https://issues.redhat.com/browse/DBZ-9411
> DBZ-9411 Extend DDL support for system-versioned tables

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-9528
> DBZ-9528 Fix shouldHandleParentChildIndexOrganizedTables

- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/BaseChangeRecordEmitter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleChangeEventSourceFactory.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectionFactory.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnector.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/AbstractLogMinerStreamingAdapter.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/AbstractLogMinerStreamingChangeEventSource.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/logwriter/RacCommitLogWriterFlushStrategy.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/unbuffered/ResumePositionProvider.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
- debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectionTest.java
- debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
https://issues.redhat.com/browse/DBZ-9448
> DBZ-9448 Apply query.fetch.size to all Oracle non-snapshot queries

- documentation/modules/ROOT/pages/connectors/oracle.adoc
https://issues.redhat.com/browse/DBZ-9466
> DBZ-9466 - Readonly documentation
